### PR TITLE
Fix the ui language override helper method for input language "en" 

### LINKED ISSUE #9254: [Bug]: DOTNET_CLI_UI_LANGUAGE ignored for English
### Issue Description

Hello,
I think the parameter DOTNET_CLI_UI_LANGUAGE doesn't work for some languages.

MsBuild runs in French by default, as my OS is in French.
When I try to set the language to English(en or en-US), nothing changes, the output is still in French.

But for instance, Spanish works as expected.

I don't know if I missed something in the config ?

Thank you

### Steps to Reproduce

```powershell
dotnet new console
$msbuild = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe"
& $msbuild
```
```
Version MSBuild 17.7.2+d6990bcfa pour .NET Framework
La génération a démarré 22/09/2023 12:30:37.

Tentative d'annulation de la génération en cours...
```

```powershell
$env:DOTNET_CLI_UI_LANGUAGE="en"
& $msbuild
```
```
Version MSBuild 17.7.2+d6990bcfa pour .NET Framework
La génération a démarré 22/09/2023 12:31:09.

Tentative d'annulation de la génération en cours...
```

```powershell
$env:DOTNET_CLI_UI_LANGUAGE="es"
& $msbuild
```
```
Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
Compilación iniciada a las 22/09/2023 12:32:56.

Intentando cancelar la compilación...
```

### Expected Behavior

Output in English :
```
MSBuild version 17.7.2+d6990bcfa for .NET Framework
Build started 22/09/2023 14:01:39.

Attempting to cancel the build...
```

### Actual Behavior

Output in French :
```
Version MSBuild 17.7.2+d6990bcfa pour .NET Framework
La génération a démarré 22/09/2023 12:31:09.

Tentative d'annulation de la génération en cours...
```

### Analysis

The only way I could get it to work in English, is by setting the codepage.
Even then, it's half in english, half in french.
```powershell
chcp 437
& $msbuild
```
```
MSBuild version 17.7.2+d6990bcfa for .NET Framework
Build started 22/09/2023 12:31:58.

Tentative d'annulation de la génération en cours...
```

But I can't use this codepage for my build as I need some accents to display properly. I just want the MsBuild messages to be localized in english.

### Versions & Configurations

MSBuild version 17.7.2+d6990bcfa for .NET Framework
17.7.2.37605

### PR DESCRIPTION
**Pull request by f-alizada**
Fixes #9254

### Context
DOTNET_CLI_UI_LANGUAGE enviroment variable was not respected when TwoLetterISOLanguageName of CultureInfo was equal to en. 

### Changes Made
Removed the additional check for described in the context case

### Testing
Case covered by unit test of the method additionally to testing in debug mode.

### CODE REVIEW

File: src/Utilities.UnitTests/EncodingUtilities_Tests.cs [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+                return; // Do not run test to replicate the behaviour of the invoking method
+            }
+            const string DOTNET_CLI_UI_LANGUAGE = nameof(DOTNET_CLI_UI_LANGUAGE);
+            using TestEnvironment testEnvironment = TestEnvironment.Create();
+            
+            // Override the ui language by setting environment variable
+            testEnvironment.SetEnvironmentVariable(DOTNET_CLI_UI_LANGUAGE, inputLanguage);
+
+            var result = EncodingUtilities.GetExternalOverriddenUILanguageIfSupportableWithEncoding();
+            Assert.Equal(new CultureInfo(expectedLanguage), result);
```
Comment (rainersigwald) [inline src/Utilities.UnitTests/EncodingUtilities_Tests.cs:54]: nit: for new tests we generally prefer Shouldly assertions (they have much nicer errors than the default xunit ones):

```suggestion
            EncodingUtilities.GetExternalOverriddenUILanguageIfSupportableWithEncoding().ShouldBeEquivalentTo(new CultureInfo(expectedLanguage));
```

(and a `using Shouldly;`, and for the other assertions too please)

**Review by rainersigwald — APPROVED** [review]
Looking good! One nit that . . . I don't think we have written down anywhere, which isn't great.

File: src/Utilities.UnitTests/EncodingUtilities_Tests.cs (hunk 1 above)
Comment (f-alizada) [reply src/Utilities.UnitTests/EncodingUtilities_Tests.cs]: Thank you for the review! I have addressed the comment. 
Will it make sense to mentioned 'using Shouldly' in the documentation: https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Contributing-Code.md as one of the bullet points within the scope of this PR?

**Review by YuliiaKovalova — APPROVED** [review]
looks good!

**Review by JanKrivanek — APPROVED** [review]
LGTM!

File: src/Utilities.UnitTests/EncodingUtilities_Tests.cs (hunk 1 above)
Comment (rainersigwald) [reply src/Utilities.UnitTests/EncodingUtilities_Tests.cs]: Let's do that in a separate PR.

Comment (f-alizada) [reply src/Utilities.UnitTests/EncodingUtilities_Tests.cs]: Got it, thank you!
