### PR TITLE
Fixing the contention condition caused by RegisterResolversManifests

### LINKED ISSUE #11043: Collection was modified in SdkResolverService.ResolveSdkUsingResolversWithPatternsFirst
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at bool System.Collections.Generic.List<T>+Enumerator.MoveNextRare()
   at SdkResult Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdkUsingResolversWithPatternsFirst(int submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, string solutionPath, string projectPath, bool interactive, bool isRunningInVisualStudio, bool failOnUnresolvedSdk)
   at SdkResult Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.ResolveSdk(int submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, string solutionPath, string projectPath, bool interactive, bool isRunningInVisualStudio, bool failOnUnresolvedSdk)
   at void Microsoft.Build.Evaluation.Evaluator<P, I, M, D>.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(string directoryOfImportingFile, ProjectImportElement importElement, out List<ProjectRootElement> projects, out SdkResult sdkResult)
   at List<ProjectRootElement> Microsoft.Build.Evaluation.Evaluator<P, I, M, D>.ExpandAndLoadImports(string directoryOfImportingFile, ProjectImportElement importElement, out SdkResult sdkResult)
   at void Microsoft.Build.Evaluation.Evaluator<P, I, M, D>.EvaluateImportElement(string directoryOfImportingFile, ProjectImportElement importElement)
   at void Microsoft.Build.Evaluation.Evaluator<P, I, M, D>.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at void Microsoft.Build.Evaluation.Evaluator<P, I, M, D>.Evaluate() x 2
   at void Microsoft.Build.Evaluation.Project+ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at void Microsoft.Build.Evaluation.Project+ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) x 2
   at void Microsoft.Build.Evaluation.Project+ProjectImpl.Initialize(IDictionary<string, string> globalProperties, string toolsVersion, string subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, bool interactive)
   at new Microsoft.Build.Evaluation.Project(string projectFile, IDictionary<string, string> globalProperties, string toolsVersion, string subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory, bool interactive)
   at Project Microsoft.Build.Evaluation.Project.FromFile(string file, ProjectOptions options)
```

just randomly saw this during project evaluation

### PR DESCRIPTION
**Pull request by SimaTian**
Fixes #11043, #7927

### Context
There was a contention condition described [here](https://github.com/dotnet/msbuild/issues/7927#issuecomment-1973203412
):
One thread enters and locks, then initializes a list, starts pushing things onto the list, which is now no longer null.
Second thread then checks, sees the list is not empty and bypasses the lock, acquires enumerator.
First thread pushes additional item into the list.
Second thread throws.

### Changes Made
Initializing the list to a placeholder first, only assigning it when it is finished. Due to this, until the list is fully initialized, all threads have to enter the lock, then they will check that the list is now initialized and return.
This will result in some minor locking overhead, but it is not as strict as locking the collection for all reads.

Furthermore, since the collection is supposed to be read only as written [here](https://github.com/dotnet/msbuild/issues/7927#issuecomment-1232765468), I've made it into IReadOnlyList instead of the current IList.

### Testing
I got a reproduction, although a bit clunky.
First commit checks should fail. Then I will push the fix which should succeed.

### CODE REVIEW

File: src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs [hunk 1]
```diff
@@ -43,18 +47,20 @@ public SdkResolverService_Tests()
 
         public void Dispose()
```
Comment (donJoseLuis) [inline src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs:48]: please observe the [best practice implementation of the disposable pattern] (https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern)

File: src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs [hunk 2]
```diff
@@ -122,28 +130,87 @@ public void AssertResolverThrows()
...
+                manifests.Add(man);
+            }
+            s_sdkResolverService._fakeManifestRegistry = manifests.AsReadOnly();
+            s_sdkResolverService._fake_initialization = true;
+
+            SdkReference sdk = new SdkReference("2sdkName", "referencedVersion", "minimumVersion");
+
+            bool result1 = false;
+            bool result2 = false;
+            Thread thread1 = new Thread(() => TryResolveSdk(out result1));
```
Comment (donJoseLuis) [inline src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs:191]: consider coverting this to the use of asynchronous calls.

**Review by donJoseLuis — APPROVED** [review]
few minor comments; man one moving away from using the thread class

File: src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs [hunk 3]
```diff
@@ -484,24 +517,41 @@ private void RegisterResolversManifests(ElementLocation location)
...
+                    _generalResolversManifestsRegistryPlaceholder.Add(sdkDefaultResolversManifest);
                 }
+
+                // Until this is set(and this is under lock), the ResolveSdkUsingResolversWithPatternsFirst will always
+                // enter if branch leaving to this section.
+                // Then it will wait at the lock and return after we release it since the collections we have filled them before releasing the lock.
+                // The collections are never modified after this point.
+                // So I've made them ReadOnly
+                _generalResolversManifestsRegistry = _generalResolversManifestsRegistryPlaceholder.AsReadOnly();
+                _specificResolversManifestsRegistry = _specificResolversManifestsRegistryPlaceholder.AsReadOnly();
```
[the remark this answers is not in the document]
Comment (SimaTian) [reply src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs:554]: No, it is not important. It is only important that these are assigned after they're fully initialized.

File: src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs (hunk 1 above)
Comment (SimaTian) [reply src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs:48]: I looked at the s_sdkResolverService and I can see only my test using it. There might have been some older commit doing that due to an imprecise refactoring.

File: src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs [hunk 4]
```diff
@@ -122,28 +130,87 @@ public void AssertResolverThrows()
...
+                                                        "sln",
+                                                        "projectPath",
+                                                        interactive: false,
+                                                        isRunningInVisualStudio: false,
+                                                        failOnUnresolvedSdk: true);
+            }
+            catch (Exception)
+            {
+                success = false;
+            }
```
[the remark this answers is not in the document]
Comment (SimaTian) [reply src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs:166]: Fair enough. I will propagate the error message if it happens.
My original though was that it doesn't matter all that much since the test is targeted at only one specific error.

File: src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs (hunk 1 above)
Comment (SimaTian) [reply src/Build.UnitTests/BackEnd/SdkResolverService_Tests.cs:48]: As for the Dispose(), after a second look, I've removed the remaining static instance and so removed the Dispose as well since it should no longer be necessary.

File: src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs [hunk 5]
```diff
@@ -465,10 +487,21 @@ private void RegisterResolversManifests(ElementLocation location)
...
+                {
+                    allResolversManifests = _fakeManifestRegistry;
+                }
+                else
+                {
+#endif
+                    allResolversManifests = _sdkResolverLoader.GetResolversManifests(location);
+#if DEBUG
+                }
+#endif
```
[the remark this answers is not in the document]
Comment (SimaTian) [reply src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs]: I've reduced it to enclose an if-branch that I need removed for non-debug environment.
Otherwise build complains about stuff not being in scope (since the static definitions for the test are not there and I need at least the _fake_initialization one to insert the thread.sleeps)

File: src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs [hunk 6]
```diff
@@ -48,12 +51,17 @@ internal class SdkResolverService : ISdkResolverService
...
-        private IList<SdkResolverManifest> _specificResolversManifestsRegistry;
+        private IReadOnlyList<SdkResolverManifest> _specificResolversManifestsRegistry;
 
         /// <summary>
         /// Stores the list of manifests of general SDK resolvers which could be loaded.
         /// </summary>
-        private IList<SdkResolverManifest> _generalResolversManifestsRegistry;
+        private IReadOnlyList<SdkResolverManifest> _generalResolversManifestsRegistry;
+
+#if DEBUG
```
Comment (JanKrivanek) [inline src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs:61]: Can we use "Extended Unit Under Test" pattern instead of conditional code within production code?

File: src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs [hunk 7]
```diff
@@ -178,6 +186,13 @@ private SdkResult ResolveSdkUsingResolversWithPatternsFirst(int submissionId, Sd
             List<SdkResolverManifest> matchingResolversManifests = new();
             foreach (SdkResolverManifest manifest in _specificResolversManifestsRegistry)
             {
+#if DEBUG
+                // If we're checking about the race condition, we should better make sure we would hit it.
+                if (_fake_initialization)
+                {
+                    Thread.Sleep(10);
```
Comment (JanKrivanek) [inline src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs:193]: Would a signalable event be more reliable?

**Review by JanKrivanek — COMMENTED** [review]
First quick pass.

There is lots of test related code in production code - can we isolate it inot tests

**Review by rainersigwald — APPROVED** [review]
