### PR TITLE
Use `EntryPointNodes` in lieu of `GraphRoots` in `GetTargetLists` (#8…

### LINKED ISSUE #8056: Graph builds don't handle GeneratePackageOnBuild when the project multitargets and is referenced
### Issue Description
If a project multitargets, uses `GeneratePackageOnBuild`, and is referenced by another project in the graph, the `Pack` target is not run.

### Steps to Reproduce

`Library\Library.csproj` (multitargets and has `GeneratePackageOnBuild`):
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net7.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
</Project>
```

`Library2\Library2.csproj` (references `Library.csproj`):
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net7.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
  </ItemGroup>
</Project>
```

`repro.sln` (just a sln containing the two projects):
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31903.59
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Library", "Library\Library.csproj", "{6727BE74-84A6-448F-B8AD-F750AA7603CF}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Library2", "Library2\Library2.csproj", "{4791B1D6-0EAA-4630-A009-E93336BEDA5C}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{6727BE74-84A6-448F-B8AD-F750AA7603CF}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{6727BE74-84A6-448F-B8AD-F750AA7603CF}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{6727BE74-84A6-448F-B8AD-F750AA7603CF}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{6727BE74-84A6-448F-B8AD-F750AA7603CF}.Release|Any CPU.Build.0 = Release|Any CPU
		{4791B1D6-0EAA-4630-A009-E93336BEDA5C}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{4791B1D6-0EAA-4630-A009-E93336BEDA5C}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{4791B1D6-0EAA-4630-A009-E93336BEDA5C}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{4791B1D6-0EAA-4630-A009-E93336BEDA5C}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

### Expected Behavior
`Library\bin\Debug\Library.1.0.0.nupkg` is created.

### Actual Behavior
`Library\bin\Debug\Library.1.0.0.nupkg` is not created.

### Analysis
In this scenario, the only target that executes on the outer build of `Library.csproj` is `GetTargetFrameworks`. If one were to remove the reference from `Library2.csproj`, the `Build` target gets executed, which then hooks `Pack` due to `GeneratePackageOnBuild`.

### Versions & Configurations
```
MSBuild version 17.5.0-preview-22506-03+20ce296d6 for .NET Framework
17.5.0.50603
```

### PR DESCRIPTION
**Pull request by DmitriyShepelev**
Fixes #8056 

### Context

`GraphRoots` won't contain referenced projects (even if they're entry points), so use `EntryPointNodes` when obtaining the entry point nodes in `GetTargetLists`. This will result in `Build` being added to the referenced project's target list, which will in the case of #8056 result in `Pack` being called.

### Changes Made
`GetTargetLists` now uses `EntryPointNodes` in lieu of `GraphRoots` in obtaining the entry point nodes.

### Testing
Verified that a referenced entry project has the default target in its target list.

### Notes
`EntryPointNodes` was initially used (see https://github.com/dotnet/msbuild/commit/a1ac094e14c59d806ad4a621779a9ec5d96de09a) but was later changed to `GraphRoots` [here](https://github.com/dotnet/msbuild/pull/4218/commits/335267ca3f55741d97df191e94bff114e8ef1fc8).

@rainersigwald Do you have any insight as to why this change was made? You made [this comment](https://github.com/dotnet/msbuild/pull/4218#pullrequestreview-217423992) about non-graph-root outer build -- it seems relevant to the change made, so I was wondering if you could elaborate on it.

### CODE REVIEW

**Comment by Forgind** [comment]
cc: @dfederm

**Review by dfederm — APPROVED** [review]

**Comment by rainersigwald** [comment]
I think my questions then were here (https://github.com/dotnet/msbuild/pull/4218#discussion_r267830872), with replies.

Basically, in a non-graph build of `Foo.csproj` -> `Multitargeted.csproj`, the outer build's `Build` target in `Multitargeted.csproj` will not run; only the selected inner build will run.

But if you have a solution that points to both, the outer build _will_ run. Passing two projects as entry points in a graph is analogous to that, I think.

So I think the commit you linked switching from EntryPointNodes to GraphRoots is incorrect.

File: src/Build.UnitTests/Graph/ProjectGraph_Tests.cs [hunk 1]
```diff
@@ -1299,6 +1277,19 @@ public void GetTargetsListProjectReferenceTargetsOrDefaultComplexPropagation()
...
+        [Fact]
+        public void ReferencedMultitargetingEntryPointNodeTargetListContainsBuildTarget()
+        {
+            using (var env = TestEnvironment.Create())
+            {
+                TransientTestFile entryProject1 = CreateProjectFile(env, 1, projectReferences: new[] { 2 });
+                TransientTestFile entryProject2 = CreateProjectFile(env, 2, extraContent: MultitargetingSpecificationPropertyGroup);
+                var graph = new ProjectGraph(new HashSet<string> { entryProject1.Path, entryProject2.Path });
+                IReadOnlyDictionary<ProjectGraphNode, ImmutableList<string>> targetLists = graph.GetTargetLists(null);
+                targetLists[key: GetOuterBuild(graph, 2)].ShouldBe(expected: new[] { "Build" });
```
Comment (rainersigwald) [inline src/Build.UnitTests/Graph/ProjectGraph_Tests.cs:1289]: Does this list not include `GetTargetFrameworks` (or whatever the test equivalent is)?

I would expect it to merge, so that the outer build of another project can do its select-a-TF process and so the outer build of the referenced multitargeting project can do `Pack`.

Comment (DmitriyShepelev) [reply src/Build.UnitTests/Graph/ProjectGraph_Tests.cs]: I initially wanted to make the test case as simple as possible to test the inclusion of `Build` in the referenced node's target list. I've updated the test case to be more robust and generic, verifying the inclusion of the `GetTargetFrameworks` equivalent `AHelperOuter`.

**Review by rainersigwald — APPROVED** [review]
