### PR TITLE
Fix bug: Exec task trims leading whitespace in ConsoleToMsBuild

### LINKED ISSUE #9668: Exec task trims leading whitespace in ConsoleToMsBuild
Given `leading.txt`

```
line with no leading whitespace
    line with some leading whitespace
```

and a project that transforms it into Exec stdout:

```xml
<Project>
    <Target Name="Go">
        <Exec Command="type leading.txt"
              StandardOutputImportance="low"
              ConsoleToMsBuild="true">
            <Output TaskParameter="ConsoleOutput" ItemName="ConOut" />
        </Exec>

        <Message Importance="high" Text="--interactive @(ConOut)" />
    </Target>
</Project>
```

`Exec` is trimming leading whitespace

```sh-session
❯ msbuild -bl
MSBuild version 17.10.0-preview-24067-01+f1448f158 for .NET Framework
--interactive line with no leading whitespace;line with some leading whitespace

Build succeeded in 0.1s
```

binlog viewer screenshot showing missing whitespace

### PR DESCRIPTION
**Pull request by surayya-MS**
Fixes #9668

### Context

See the issue description with example

### Changes Made

Here the string is trimmed of all whitespace characters:
https://github.com/dotnet/msbuild/blob/195e7f5a3a8e51c37d83cd9e54cb99dc3fc69c22/src/Tasks/Exec.cs#L411-L413

I changed it to trim only the end, so that the leading whitespace characters are preserved in the output

### Testing

Added a unit test and tried out the example in the issue manually

### CODE REVIEW

File: src/Tasks.UnitTests/Exec_Tests.cs [hunk 1]
```diff
@@ -1033,6 +1033,19 @@ public void EndToEndMultilineExec_EscapeSpecialCharacters()
                 }
             }
         }
+
+        [Fact]
+        public void ConsoleOutputDoesNotTrimLeadingWhitespace()
+        {
+            Exec exec = PrepareExec("type .\\Exec_Tests.Attachments\\leading-whitespace.txt");
```
Comment (AR-May) [inline src/Tasks.UnitTests/Exec_Tests.cs:1040]: In order to keep the amount of test files limited, I suggest using `TestEnvironment` to create this one-line file during the test execution, as it was done in `EndToEndMultilineExec_EscapeSpecialCharacters` test above. It would be also help with having this line in one place instead of two.

**Review by AR-May — COMMENTED** [review]
LGTM, I only have one suggestion concerning the testing.

**Review by AR-May — APPROVED** [review]
Forgot to change from "Comment" to "Approve".

File: src/Tasks.UnitTests/Exec_Tests.cs (hunk 1 above)
Comment (surayya-MS) [reply src/Tasks.UnitTests/Exec_Tests.cs]: Thanks for suggestion! Done.

File: src/Tasks/Exec.cs [hunk 2]
```diff
@@ -410,7 +410,7 @@ protected override void LogEventsFromTextOutput(string singleLine, MessageImport
 
             if (ConsoleToMSBuild)
             {
-                string trimmedTextLine = singleLine.Trim();
+                string trimmedTextLine = singleLine.TrimEnd();
```
Comment (f-alizada) [inline src/Tasks/Exec.cs:413]: Writing my thoughts :) 
Was it considered to be put under change wave or it is not this kind of change ?

**Review by f-alizada — APPROVED** [review]
LGTM, left one question out of curiosity

File: src/Tasks/Exec.cs (hunk 2 above)
Comment (surayya-MS) [reply src/Tasks/Exec.cs:413]: Good question. @JanKrivanek, @ladipro, @rokonec what do you think?

Comment (surayya-MS) [reply src/Tasks/Exec.cs:413]: From our conversation with @rokonec, this change should be under change wave as some people can rely on the buggy behavior of the output lines being trimmed. I will make the changes to the code. Thanks Farhad!

**Review by rokonec — APPROVED** [review]

**Comment by ladipro** [comment]
The change wave check should be documented in https://github.com/dotnet/msbuild/blob/main/documentation/wiki/ChangeWaves.md#1710.
