### PR TITLE
Specialcase UAP == windows

### LINKED ISSUE #6150: ResolveSdkReferences complains about referencing UAP SDKs in a Desktop app
### Issue Description

When you try to reference either `Microsoft.VCLibs` or `Microsoft.UniversalCRT.Debug` when the `TargetPlatformIdentifier` == `Windows`, you get errors `MSB3842` and `MSB3843`.

This is a new scenario that is uncovered due to Project Reunion, where we are making efforts to remove all differences at the project system layer between Desktop and UWP Windows.

### Expected Behavior

Build succeeds

### Actual Behavior

Build fails.

### Analysis

This can be worked around by adding this:

```xml
  <PropertyGroup>
    <!-- Suppress warnings -->
    <LogSDKReferenceResolutionErrorsAsWarnings>true</LogSDKReferenceResolutionErrorsAsWarnings>
    <MSBuildWarningsAsMessages>
      $(MSBuildWarningsAsMessages);
      MSB3842;
      MSB3843;
    </MSBuildWarningsAsMessages>
  </PropertyGroup>
```
But this seems like an unnecessary big hammer. Since Desktop Windows is a complete superset of UWP Windows, it should be perfectly valid to have an SDK Reference to a UAP SDK when building Desktop, but not the other way around.

### Versions & Configurations
c:\dev\winui>msbuild -version
Microsoft (R) Build Engine version 16.9.0-preview-21065-09+34bbbedaf for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.9.0.6509
### Attach a binlog
[msbuild.zip](https://github.com/dotnet/msbuild/files/5966680/msbuild.zip)

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #6150

### Context
We verify that the target platform is appropriate for the target platform identifier, but that check is too specific; it doesn't permit equivalent strings from matching. So far, we only know of UAP being a windows app, hence valid for windows. This fixes that instance.

### Testing
Tried to reproduce this with and without this change. The error changed, and I don't think it's related, but I'm keeping this a draft PR anyway because I'm not confident about this.

### CODE REVIEW

**Comment by Forgind** [comment]
@BenVillalobos pointed out how I was being stupid with testing, and I verified this made the error go away 🙂

File: src/Tasks/ResolveSDKReference.cs [hunk 1]
```diff
@@ -1251,7 +1251,7 @@ private void CreateResolvedReferenceItem(string targetConfiguration, string targ
                     AddResolutionWarning("ResolveSDKReference.MaxPlatformVersionNotSpecified", projectName, DisplayName, Version, targetPlatformIdentifier, targetPlatformVersionFromItem.ToString(), targetPlatformIdentifier, targetPlatformVersion.ToString());
                 }
 
-                if (!String.IsNullOrEmpty(TargetPlatform) && !String.Equals(targetPlatformIdentifier, TargetPlatform))
+                if (!String.IsNullOrEmpty(TargetPlatform) && !String.Equals(targetPlatformIdentifier, TargetPlatform) && (!String.Equals("UAP", TargetPlatform, StringComparison.OrdinalIgnoreCase) || !String.Equals(targetPlatformIdentifier, "windows", StringComparison.OrdinalIgnoreCase)))
```
Comment (BenVillalobos) [inline src/Tasks/ResolveSDKReference.cs:1254]: I'd create a hashset of `supportedAliases` or something akin to that. Then we can comment next to the variable a link to the issue, and this new bit of code will be self-documenting.

Comment (BenVillalobos) [reply src/Tasks/ResolveSDKReference.cs:1254]: Actually, a dictionary <string,string> might make more sense.  `if (string.Equals(TargetPlatform, supportedAliases[TargetPlatform])`, this way we can directly map windows to UAP.

My priority in this case would be clarity + potential future cases similar to this, though admittedly I'm not 100% sure how often it would happen so I could be over-engineering.

Either way we should link back to this PR/issue.

Comment (BenVillalobos) [inline src/Tasks/ResolveSDKReference.cs:1254]:
```suggestion
                if (!String.IsNullOrEmpty(TargetPlatform) && !string.Equals(targetPlatformIdentifier, TargetPlatform) && (!String.Equals("UAP", TargetPlatform, StringComparison.OrdinalIgnoreCase) || !string.Equals(targetPlatformIdentifier, "windows", StringComparison.OrdinalIgnoreCase)))
```

nit

Comment (Forgind) [reply src/Tasks/ResolveSDKReference.cs:1254]: I agree, but I did it this way intentionally because the rest of the file uses String, and I didn't want to change everything or stand out.

Comment (rainersigwald) [reply src/Tasks/ResolveSDKReference.cs:1254]: I would consider making a local function so you can be a bit more verbose.

Comment (Forgind) [reply src/Tasks/ResolveSDKReference.cs]: I made a dictionary. I don't think it's quite as nice as just doing the string comparisons for just one alias, but if we have multiple, it starts to be clearer.

File: src/Tasks/ResolveSDKReference.cs [hunk 2]
```diff
@@ -1251,7 +1259,7 @@ private void CreateResolvedReferenceItem(string targetConfiguration, string targ
                     AddResolutionWarning("ResolveSDKReference.MaxPlatformVersionNotSpecified", projectName, DisplayName, Version, targetPlatformIdentifier, targetPlatformVersionFromItem.ToString(), targetPlatformIdentifier, targetPlatformVersion.ToString());
                 }
 
-                if (!String.IsNullOrEmpty(TargetPlatform) && !String.Equals(targetPlatformIdentifier, TargetPlatform))
+                if (!String.IsNullOrEmpty(TargetPlatform) && !String.Equals(targetPlatformIdentifier, TargetPlatform) && (!platformAliases.TryGetValue(TargetPlatform, out string platform) || !String.Equals(targetPlatformIdentifier, platform, StringComparison.OrdinalIgnoreCase)))
```
Comment (BenVillalobos) [inline src/Tasks/ResolveSDKReference.cs:1262]:
```suggestion
                if (!String.IsNullOrEmpty(TargetPlatform) && (!String.Equals(targetPlatformIdentifier, TargetPlatform) || (platformAliases.TryGetValue(TargetPlatform, out string platform) && !String.Equals(targetPlatformIdentifier, platform, StringComparison.OrdinalIgnoreCase))))
```

This reads easier to me. Even if this isn't preferred: If trygetvalue returned false, why bother checking if platform == TPI?

**Review by BenVillalobos — COMMENTED** [review]
We should have a test for this scenario.

File: src/Tasks/ResolveSDKReference.cs (hunk 2 above)
Comment (Forgind) [reply src/Tasks/ResolveSDKReference.cs:1262]: If TargetPlatform is not null or empty, and it isn't the same as targetPlatformIdentifier, and it isn't the same as the aliased version, we should fail.

Your version says that if TargetPlatform is not null or empty, and it _is_ the same as targetPlatformIdentifier, but it's also in the dictionary and the aliased version is not the same, then we should fail, and that isn't true. Similarly, with your version, if TargetPlatform is not null or empty, and it's different from targetPlatformIdentifier, then we don't bother checking the dictionary, and we fail, which again is not what we want.

Comment (BenVillalobos) [reply src/Tasks/ResolveSDKReference.cs:1262]: AH my bad, this is the **failing case**, not the continuing case.

**Review by BenVillalobos — APPROVED** [review]

File: src/Tasks/ResolveSDKReference.cs (hunk 2 above)
Comment (Forgind) [reply src/Tasks/ResolveSDKReference.cs:1262]: Added a unit test 🙂

File: src/Tasks.UnitTests/ResolveSDKReference_Tests.cs [hunk 3]
```diff
@@ -4202,6 +4203,27 @@ public void CheckDefaultingOfTargetConfigAndArchitecture()
...
+                new HashSet<string>() { "sdkName" },
+                treatErrorsAsWarnings: false,
+                prefer32Bit: false,
+                "windows",
+                new Version("1.0.2"),
+                "projectName",
+                enableMaxPlatformVersionEmptyWarning: true);
+
+            reference.ResolutionErrors.ShouldBeEmpty();
+            reference.ResolutionWarnings.ShouldBeEmpty();
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/ResolveSDKReference_Tests.cs:4224]: I don't think I understand this test and it doesn't look like the other tests. Can you clarify what it's testing?

File: src/Tasks/ResolveSDKReference.cs [hunk 4]
```diff
@@ -25,6 +25,14 @@ public class ResolveSDKReference : TaskExtension
     {
         #region fields
 
+        /// <summary>
+        /// Platform aliases
+        /// </summary>
+        private static Dictionary<string, string> platformAliases = new(StringComparer.OrdinalIgnoreCase)
```
Comment (rainersigwald) [inline src/Tasks/ResolveSDKReference.cs:31]: Unlikely to matter in this case but for cleanliness:

```suggestion
        private static readonly Dictionary<string, string> PlatformAliases = new(StringComparer.OrdinalIgnoreCase)
```

File: src/Tasks.UnitTests/ResolveSDKReference_Tests.cs (hunk 3 above)
Comment (Forgind) [reply src/Tasks.UnitTests/ResolveSDKReference_Tests.cs:4224]: If it understands the idea of aliases, it should be able to resolve the SDK reference without warnings or errors. This is a pretty barebones version, so most of the parameters end up taking default values, but it hits the one that led to this particular issue.

Comment (rainersigwald) [reply src/Tasks.UnitTests/ResolveSDKReference_Tests.cs:4224]: Can you call out via comment in the test code the relevant features of the test? That way it's less mysterious if it starts failing. Like here I think it's that in line 4210 UAP isn't a "real" platform but it should be aliased to "Windows" anyway?

Also, is there an assert you can apply to the resolution of the alias?

File: src/Tasks.UnitTests/CreateItem_Tests.cs [hunk 5]
```diff
@@ -154,7 +154,7 @@ public void WildcardsWithRecursiveDir()
             ObjectModelHelpers.DeleteTempProjectDirectory();
 
             ObjectModelHelpers.CreateFileInTempProjectDirectory("Myapp.proj", @"
-                <Project ToolsVersion=`msbuilddefaulttoolsversion` xmlns=`msbuildnamespace`>
+                <Project ToolsVersionresol=`msbuilddefaulttoolsversion` xmlns=`msbuildnamespace`>
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/CreateItem_Tests.cs:157]: ?

File: src/Tasks.UnitTests/ResolveSDKReference_Tests.cs [hunk 6]
```diff
@@ -4202,6 +4203,29 @@ public void CheckDefaultingOfTargetConfigAndArchitecture()
...
+            reference.TargetPlatform.ShouldBe("UAP");
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/ResolveSDKReference_Tests.cs:4226]: This doesn't do quite what I was thinking--is there no way to assert the uap/windows releationship?

Comment (Forgind) [reply src/Tasks.UnitTests/ResolveSDKReference_Tests.cs:4226]: Windows is passed in as a thing to compare against; it isn't part of the resolution. So no.

File: src/Tasks.UnitTests/CreateItem_Tests.cs (hunk 5 above)
Comment (Forgind) [reply src/Tasks.UnitTests/CreateItem_Tests.cs:157]: Not sure how that crept in; will revert.

File: src/Tasks/ResolveSDKReference.cs [hunk 7]
```diff
@@ -25,6 +25,14 @@ public class ResolveSDKReference : TaskExtension
     {
         #region fields
 
+        /// <summary>
+        /// Platform aliases
+        /// </summary>
+        private static readonly Dictionary<string, string> PlatformAliases = new(StringComparer.OrdinalIgnoreCase)
+        {
+            { "UAP", "windows" }
```
Comment (Nirmal4G) [inline src/Tasks/ResolveSDKReference.cs:33]:
```suggestion
            { "UAP", "Windows" }
```

Comment (Forgind) [reply src/Tasks/ResolveSDKReference.cs:33]: Although I'll admit that looks nicer, lower-case windows is what the string actually is, so this adds a layer of complexity to the check I'd like to avoid.

Comment (Nirmal4G) [reply src/Tasks/ResolveSDKReference.cs:33]: No, The `TargetPlatformIdentifier` is `Windows`, even in Windows XAML targets and in the Windows SDK targets. I can confirm. And besides, you're ignoring case, so it doesn't really matter.
