### PR TITLE
Ignore invalid import when expression empty

### LINKED ISSUE #6221: Project load setting IgnoreInvalidImports should apply to expressions that evaluate to empty
### Issue Description
In #2720, we were attempting to allow callers to the evaluation API to ignore invalid imports.  However, we missed the scenario that an import for an expression that evaluates to an empty string throws in a different part of the code.

https://github.com/dotnet/msbuild/blob/63087cde532910d409b2f5f6d0694c1bcb8bfb74/src/Build/Evaluation/Evaluator.cs#L1933-L1936

This was an oversight and leads to inconsistent behavior when you have the following imports:
```xml
<Import Project="$(Foo)" />
<Import Project="$(Foo)\bar.txt" />
```

The second import is correctly ignored because `\bar.txt` doesn't exist, but the first import still throws since that uses a different code path.
### Steps to Reproduce
1. Create a project with an import of an expression that evaluates to an empty string
  ```xml
  <Import Project="$(Foo)" />
  <Import Project="$(Foo)\bar.txt" />
  ```
2. Load the project with the `ProjectLoadSetting.IgnoreInvalidImports`

### Expected Behavior
The project is loaded and an event is logged indicating that the import was skipped.

### Actual Behavior
An `InvalidProjectFileException` is thrown.

### PR DESCRIPTION
**Pull request by jeffkl**
Fixes #6221

### Context
When the project load setting `IgnoreInvalidImports` is set, the caller expects imports that couldn't be loaded to just be ignored in a best effort attempt to load the project.  However, the code path of the project expression evaluating to an empty string was overlooked in #2720

### Changes Made
I've checked the `ProjectLoadSettings` in the evaluator when the project import expression evaluates to an empty string and logged an event and skipped the import

### Testing
I've added a unit test

### Notes
The first commit is the implementation, the second commit is just a conversion to Shouldly

### CODE REVIEW

**Review by cdmihai — APPROVED** [review]

File: src/Build/Evaluation/Evaluator.cs [hunk 1]
```diff
@@ -1927,17 +1927,45 @@ ProjectRootElement InnerCreate(string _, ProjectRootElementCacheBase __)
         private LoadImportsResult ExpandAndLoadImportsFromUnescapedImportExpression(string directoryOfImportingFile, ProjectImportElement importElement, string unescapedExpression,
                                             bool throwOnFileNotExistsError, out List<ProjectRootElement> imports)
         {
+            imports = new List<ProjectRootElement>();
+
+            bool ignoreInvalidImports = _loadSettings.HasFlag(ProjectLoadSettings.IgnoreInvalidImports);
```
Comment (Forgind) [inline src/Build/Evaluation/Evaluator.cs:1932]: nit:
Common case should be !String.IsNullOrWhiteSpace(importExpressionEscaped), so move this under that if?

**Review by Forgind — APPROVED** [review]
Thanks for all the changes to Shouldly!

File: src/Build/Evaluation/Evaluator.cs (hunk 1 above)
Comment (jeffkl) [reply src/Build/Evaluation/Evaluator.cs:1932]: Yes good point.  I was going to use the variable `ignoreInvalidImports` later in this method but didn't end up doing that.  I'll move this down inside the `if`.  I'll also do the bitwise comparison myself as I just read that `Enum.HasFlag()` is slow :(

https://stackoverflow.com/questions/7368652/what-is-it-that-makes-enum-hasflag-so-slow

Should I fix the other two calls to `HasFlag()` in the evaluator?  The first one isn't called that much but the second one is on the hot path

1. https://github.com/dotnet/msbuild/blob/master/src/Build/Evaluation/Evaluator.cs#L1768
2. https://github.com/dotnet/msbuild/blob/master/src/Build/Evaluation/Evaluator.cs#L2400

Or should we do that in a different change?

Comment (Forgind) [reply src/Build/Evaluation/Evaluator.cs]: Up to you—I'm happy with this change as-is, but the change is straightforward enough that it seems unlikely something would go wrong.

Comment (jeffkl) [reply src/Build/Evaluation/Evaluator.cs]: I'm going to do a separate change to get rid of the `HasFlag()` calls, just to be safe.  Feel free to merge.  Thanks!

**Review by BenVillalobos — APPROVED** [review]
LGTM
