### PR TITLE
Fix NullReferenceException when expanding property functions that return null

### LINKED ISSUE #6413: NullReferenceException in SpanBasedConcatenator when evaluating target dependencies
Seeing this exception when building a project:

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Evaluation.Expander`2.SpanBasedConcatenator.Add(Object obj)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.BackEnd.TargetEntry.GetDependencies(ProjectLoggingContext projectLoggingContext)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__58.MoveNext()
```

It does *not* repro with `16.9.0+5e4b48a27` but does with `16.10.0-preview-21181-05+80f316e90` and `16.10.0-preview-21227-06+1d1fec7c4`.

I'll try to get a minimal repro, but this is happening in a private repo I'm not very familiar with. Ping me on Teams for instructions cloning the repo this is happening to in the meantime.

### PR DESCRIPTION
**Pull request by ladipro**
Fixes #6413

### Context

This is a regression introduced in #6128. MSBuild crashes when evaluating a project where a property function returns null and its result is concatenated with another non-empty value.

### Changes Made

Add a null check.

### Testing

Fixed and extended the relevant test case.

### Notes

Enable "Hide whitespace changes" when reviewing this change.

### CODE REVIEW

File: src/Build.UnitTests/Evaluation/Expander_Tests.cs [hunk 1]
```diff
@@ -2010,13 +2010,16 @@ public void PropertyFunctionNullArgument()
         public void PropertyFunctionNullReturn()
         {
             PropertyDictionary<ProjectPropertyInstance> pg = new PropertyDictionary<ProjectPropertyInstance>();
-            pg.Set(ProjectPropertyInstance.Create("SomeStuff", "This IS SOME STUff"));
 
             Expander<ProjectPropertyInstance, ProjectItemInstance> expander = new Expander<ProjectPropertyInstance, ProjectItemInstance>(pg, FileSystems.Default);
 
-            string result = expander.ExpandIntoStringLeaveEscaped("$([System.Convert]::ChangeType(,$(SomeStuff.GetType())))", ExpanderOptions.ExpandProperties, MockElementLocation.Instance);
```
Comment (rainersigwald) [inline src/Build.UnitTests/Evaluation/Expander_Tests.cs:2017]: Was this just a fancy way to get `null` before, and you're using the easier approach now?

**Review by rainersigwald — APPROVED** [review]
LGTM and I agree that we should take this in 16.10. @marcpopMSFT, any objection? The regression was reported by 1ES.

**Review by Forgind — APPROVED** [review]

File: src/Build.UnitTests/Evaluation/Expander_Tests.cs [hunk 2]
```diff
@@ -2010,13 +2010,16 @@ public void PropertyFunctionNullArgument()
...
-
+            // The null-returning function is the only thing in the expression.
+            string result = expander.ExpandIntoStringLeaveEscaped("$([System.Environment]::GetEnvironmentVariable(`_NonExistentVar`))", ExpanderOptions.ExpandProperties, MockElementLocation.Instance);
```
Comment (BenVillalobos) [inline src/Build.UnitTests/Evaluation/Expander_Tests.cs:2017]: I'm now reminded that if an environment var doesn't exist, GetEnvironmentVariable returns null.

**Review by BenVillalobos — APPROVED** [review]
Took me a sec to realize the "meat" of the change is just making sure `propertyValue` doesn't get added if null. LGTM

File: src/Build.UnitTests/Evaluation/Expander_Tests.cs (hunk 1 above)
Comment (ladipro) [reply src/Build.UnitTests/Evaluation/Expander_Tests.cs:2017]: It was not evaluating to `null` before so not hitting the intended code path. Presumably because the `(,` argument omission makes us pass an empty string.
