### PR TITLE
Fix Loading of Plugin Assemblies

### LINKED ISSUE #6186: Regression when loading NuGet in MSBuild tasks
### Issue Description
https://github.com/dotnet/msbuild/pull/6126 pins NuGet loads from tasks to use the one in the SDK directly regardless of the version referenced by tasks.  This will unnaturally pin NuGet to the SDK version which will cause issues when tasks need to move ahead either for testing or for general functionality.  In the past we've been very careful about pinning NuGet.

Additionally, the closure of NuGet's assemblies is not loaded from ALC.  This leads to type unification problems, since the first load from MSBuild will cause NuGet to bind to these assemblies in MSBuild, then a task which runs later will bind to it's local copy (even if it is the exact same version).  https://github.com/dotnet/runtime/pull/48462#issuecomment-782854316
```
.packages/microsoft.dotnet.build.tasks.packaging/6.0.0-beta.21120.1/build/Packaging.targets(747,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Build) The "GenerateRuntimeDependencies" task failed unexpectedly.
System.MissingMethodException: Method not found: 'Void NuGet.RuntimeModel.JsonObjectWriter..ctor(Newtonsoft.Json.JsonWriter)'.
   at Microsoft.DotNet.Build.Tasks.Packaging.NuGetUtility.WriteRuntimeGraph(String filePath, RuntimeGraph runtimeGraph)
   at Microsoft.DotNet.Build.Tasks.Packaging.GenerateRuntimeDependencies.Execute() in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeDependencies.cs:line 144
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

cc @ViktorHofer 

### Steps to Reproduce
1. Run a task which uses both NuGet and Newtonsoft.JSON and calls NuGet APIs which use Newtonsoft.JSON types.  EG: https://github.com/dotnet/arcade/blob/ca7fab569267ed3bc73360882d652d119aae5653/src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeDependencies.cs

### Expected Behavior
Task runs to completion.

### Actual Behavior
Task fails with MissingMethodException since the calling task assembly and NuGet don't agree on the assembly that Newtonsoft.Json.JsonWriter lives in.

### Analysis
I think we need to rethink the solution for https://github.com/dotnet/msbuild/pull/6126.  I don't think the host should be pinning assemblies which don't need to unify.

It should be *possible* for tasks to defer to MSBuild's copy of assemblies if that works well for them.  In those cases the task should omit the entire assembly closure graph for those assemblies from their task layout, and they should ensure that they reference a version that is <= the one in MSBuild.  As part of the performance investigation/work we should go and talk to the folks that are bundling NuGet and ask them if they are OK with making this change to improve performance.

### Versions & Configurations
dotnet sdk 6.0.100-preview.2.21118.7

Binlog from when building the coreclr packages in dotnet/runtime which shows the `MissingMethodException`: 
[msbuild.zip](https://github.com/dotnet/msbuild/files/6031275/msbuild.zip)

### PR DESCRIPTION
**Pull request by brianrob**
Fixes #6186 

### Context
#6126 changed the load behavior for NuGet dlls by forcing them to load in the default assembly load context.  This effectively pinned their versions to the SDK, which is not a safe behavior for targets that may wish to carry their own versions of NuGet or other DLLs that they might load.

### Changes Made
Rather than pinning specific DLLs, change the behavior to load all DLLs that are in the MSBuild directory in the default assembly load context.  This allows targets to carry their own versions of dependencies, while avoiding loading assemblies that are packaged with MSBuild into multiple assembly load contexts, and thus losing the benefits of precompilation.

### Testing
Verified that dotnet build hello-world has the correct load and jitting behavior.
Verified that tasks can load their own copies of NuGet binaries into the plugin assembly load context.

### CODE REVIEW

**Comment by BenVillalobos** [comment]
Is there a way to create unit tests for this behavior?

**Comment by brianrob** [comment]
Yup, I am working on fixing that now.

File: src/Shared/CoreCLRAssemblyLoader.cs [hunk 1]
```diff
@@ -52,7 +58,11 @@ public Assembly LoadFromPath(string fullPath)
             // folders in a NuGet package).
             fullPath = FileUtilities.NormalizePath(fullPath);
 
-            if (Traits.Instance.EscapeHatches.UseSingleLoadContext)
+            // If the requested load comes from the same directory as MSBuild, assume that
+            // the load is part of the platform, and load it using the Default ALC.
+            string assemblyDir = Path.GetDirectoryName(fullPath);
+
+            if (Traits.Instance.EscapeHatches.UseSingleLoadContext || string.Equals(assemblyDir, _msbuildDirPath))
```
Comment (ericstj) [inline src/Shared/CoreCLRAssemblyLoader.cs:65]: Is any normalization needed for this path, or can you guarantee that a string comparison is sufficient?  Things that could matter: relative vs full path, casing on some platforms, directory separator normalization, whitespace, extended prefixes (eg `\??\`)

File: src/Shared/CoreCLRAssemblyLoader.cs [hunk 2]
```diff
@@ -52,7 +58,11 @@ public Assembly LoadFromPath(string fullPath)
...
             {
                 return LoadUsingLegacyDefaultContext(fullPath);
```
Comment (ViktorHofer) [inline src/Shared/CoreCLRAssemblyLoader.cs:67]: nit: why is the default ALC called legacy?

File: src/Shared/CoreCLRAssemblyLoader.cs (hunk 1 above)
Comment (Forgind) [reply src/Shared/CoreCLRAssemblyLoader.cs:65]: I think both should be full paths to the directory with MSBuild, assuming they match, and since they describe the exact same file system path, I think they should be identical in casing, too.

My related question is: is this the right MSBuild.exe? If we're running in, say, VS, this point to the version of MSBuild associated with VS, not the version that's executing at the moment. Is that correct?

Comment (brianrob) [reply src/Shared/CoreCLRAssemblyLoader.cs:65]: I have a commit that I'll post shortly that will normalize the path in the same way that the input is normalized, just to be sure.  The cost should be insignificant, as we only do it once per instance of MSBuild.

@forgind on your related question, I believe that this is the right MSBuild based on what you're saying.  We'd want to be pointing at the VS MSBuild in that case, right?  That would ensure that we only load DLLs in the task ALC for tasks that aren't "part of MSBuild".

File: src/Shared/CoreCLRAssemblyLoader.cs (hunk 2 above)
Comment (brianrob) [reply src/Shared/CoreCLRAssemblyLoader.cs:67]: Not sure.  This is beyond my time in this code base.

File: src/Shared/CoreCLRAssemblyLoader.cs (hunk 1 above)
Comment (Forgind) [reply src/Shared/CoreCLRAssemblyLoader.cs:66]: I don't know, but I trust you.

File: src/Shared/CoreCLRAssemblyLoader.cs (hunk 2 above)
Comment (Forgind) [reply src/Shared/CoreCLRAssemblyLoader.cs:68]: The not-legacy ALC was a recent addition. rainersigwald tried to make it on by default, but that broke people, so he switched it to off-by-default but encouraged. It might have been turned on by default in the SDK; not sure.

**Review by Forgind — APPROVED** [review]

File: src/Shared/CoreCLRAssemblyLoader.cs (hunk 1 above)
Comment (ericstj) [reply src/Shared/CoreCLRAssemblyLoader.cs:66]: Is it easy to test this?  Things like:
```
Task.dll
<msbuildDir>\sub\..\Task.dll
C:\<msBuildPath>\Task.dll
\<msbuildPath>\Task.dll
```
Presumably the path to the task is coming from the project/props/targets so it is user specified.  I think there's also a version of `UsingTask` that uses StrongName.  Does that need to be considered? 

Assuming that can be fed in at the right level.

**Comment by ericstj** [comment]
It might be interesting to measure the perf difference of this change compared to before the regression.  It may provide greater wins than the first fix since it is sharing more.

**Review by ericstj — APPROVED** [review]
This change is a reasonable fix to the issue we faced.  If you need to expedite the fix consider it approved: this is much better than current behavior.  I think it'd be good to add some test coverage but that could be a separate PR.

**Comment by brianrob** [comment]
Discovered a bug around case sensitivity of paths.  Consulted with @ladipro and landed at the latest iteration.

**Comment by brianrob** [comment]
@ericstj, I did some offline testing around the types of paths that you proposed above, and they are handled properly by the file path normalization logic.

File: src/Shared/CoreCLRAssemblyLoader.cs [hunk 3]
```diff
@@ -26,9 +26,9 @@ internal sealed class CoreClrAssemblyLoader
         private static string _msbuildDirPath;
         private static readonly Version _currentAssemblyVersion = new Version(Microsoft.Build.Shared.MSBuildConstants.CurrentAssemblyVersion);
 
-        internal CoreClrAssemblyLoader()
+        static CoreClrAssemblyLoader()
         {
-            _msbuildDirPath = FileUtilities.NormalizePath(BuildEnvironmentHelper.Instance.CurrentMSBuildExePath);
+            _msbuildDirPath = FileUtilities.NormalizePath(typeof(CoreClrAssemblyLoader).Assembly.Location);
```
Comment (Forgind) [inline src/Shared/CoreCLRAssemblyLoader.cs:31]: ComparePathsNoThrow handles the normalization part of this for you.

Comment (brianrob) [reply src/Shared/CoreCLRAssemblyLoader.cs:31]: Thanks @forgind.  I'd like to leave this here.  The reason is that it happens only once per process, and has the ability to simplify the checks that must happen per assembly, instead of just once per process.  If we don't do this here, and the value would have changed, then when loading an assembly, we'd have to do a string comparison which would fail, and then we'd have to normalize both inputs, and then try again.

If on the other hand, the initial normalize call here changed the input, it could possibly avoid the extra normalizations per assembly load.

File: src/Shared/CoreCLRAssemblyLoader.cs [hunk 4]
```diff
@@ -23,8 +23,15 @@ internal sealed class CoreClrAssemblyLoader
 
         private bool _resolvingHandlerHookedUp = false;
 
+        private static string _msbuildDirPath;
```
Comment (ladipro) [inline src/Shared/CoreCLRAssemblyLoader.cs:26]: super-nit: `readonly`

**Review by ladipro — APPROVED** [review]

**Comment by brianrob** [comment]
@marcpopMSFT, can you help me understand when this should be merged so that it doesn't impact the #6195?

**Comment by marcpopMSFT** [comment]
We have the final build for preview 2 now so we should be clear to get this in.  However, our PR queue backed up again because of a sev 3 feed livesite incident where our build feed was taking many hours to update with new builds so we haulted our checkins. They say that's fixed now so we need to confirm and get our 11 approved PRs flowing again.
