### PR TITLE
Remove incorrect checks from GetRuntimeVersion

### LINKED ISSUE #8731: [Bug]: Core version of RAR fails to read WinRT runtime version from assemblies
### Issue Description

The non-Framework / non-Windows implementation of RAR has a bug where it incorrectly assumes that the metadata version - referred to as "runtime version" in the code - has to start with 'v'. Metadata version of WinRT files looks like `WindowsRuntime 1.4` or `WindowsRuntime 1.4;CLR v4.0.30319`.

### Steps to Reproduce

Create a WinRT component using the Windows Runtime Component template in VS and add it as a reference to a .NET project. Build the project.

### Expected Behavior

image

### Actual Behavior

image

### Analysis

Here's the bug:

https://github.com/dotnet/msbuild/blob/6882ab9de1c4d5786e14370b0b123c78cae3a671/src/Tasks/AssemblyDependency/AssemblyInformation.cs#L1051-L1056

It's not clear what the downstream effect is. Since .winmd's cannot be referenced by modern .NET projects anyway - the build errors out in the `CheckForUnsupportedWinMDReferences` task - it is possible that this part of Core RAR may be deleted.

### Versions & Configurations

MSBuild version 17.6.0-preview-23174-01+e7de13307 for .NET

### PR DESCRIPTION
**Pull request by ladipro**
Fixes #8731

### Context

The .NET Core version of MSBuild has its own metadata reader implementation and `GetRuntimeVersion` contains checks that are stricter than what the full Framework implementation does. Specifically, it allows only "version-like" runtime versions, which makes it fail to read the version of WinRT assemblies.

### Changes Made

Removed the incorrect checks.

### Testing

- New unit test.
- Verified that referencing a WinRT assembly now makes RAR produce the right output.

### CODE REVIEW

File: src/Tasks/AssemblyDependency/AssemblyInformation.cs [hunk 1]
```diff
@@ -866,19 +866,30 @@ private class HeaderInfo
...
+        }
+
+        /// <summary>
+        /// Given a stream get the CLR runtime version of the underlying file.
+        /// </summary>
+        /// <param name="stream">A stream representing the file</param>
+        /// <returns>The CLR runtime version or empty if the stream does not represent an assembly.</returns>
+        internal static string GetRuntimeVersion(Stream stream)
+        {
+            using (var sr = new BinaryReader(stream))
```
Comment (JanKrivanek) [inline src/Tasks/AssemblyDependency/AssemblyInformation.cs:891]: Interesting choice that calee is disposing the resource instead of the owner (caller).
But since it's internal and single usage method - it probably  doesn't matter

**Review by JanKrivanek — APPROVED** [review]
Looks good!

File: src/Tasks/AssemblyDependency/AssemblyInformation.cs (hunk 1 above)
Comment (ladipro) [reply src/Tasks/AssemblyDependency/AssemblyInformation.cs:891]: You're bringing up a great point. Does disposing of the `BinaryReader` close the file on this code path? I have kept the calls exactly like before but I wonder if this is correct.

Comment (ladipro) [reply src/Tasks/AssemblyDependency/AssemblyInformation.cs:891]: Aha, that's one of the weirder BCL design choices. `BinaryReader` closes the underlying stream by default.
https://learn.microsoft.com/en-us/dotnet/api/system.io.binaryreader.-ctor?view=net-7.0#system-io-binaryreader-ctor(system-io-stream-system-text-encoding-system-boolean)

Though not needed, I'll add a `Dispose` call to the caller for clarity. Thank you!

Comment (JanKrivanek) [reply src/Tasks/AssemblyDependency/AssemblyInformation.cs:891]: Yeah - decoration and disposing is always bit tricky.
IIRC the decorating streams can usualy be instructed to not dispose the underlying streams.

The other option is not to disect the boundary between the caller-calee over the decorating chain, but rather let just one of those handle all streams. Again - overkill adjustments for this one-off scenario

**Review by Forgind — APPROVED** [review]

File: src/Tasks/AssemblyDependency/AssemblyInformation.cs (hunk 1 above)
Comment (ladipro) [reply src/Tasks/AssemblyDependency/AssemblyInformation.cs]: Done!
