### PR TITLE
6732: Default to sha2 digest for clickonce manifest

### LINKED ISSUE #6732: SecurityUtilities chooses sha1 when signing using certificate signed with sha384
### Issue Description
When using a certificate signed with sha384 to sign a file using the ManifestUtilities.SecurityUtilities class, it will choose the sha1 algorithm, which is considered deprecated in most contexts. 

We encountered this issue when making a clickonce release package. The issue is also present when using mage.exe

As of june 1, most or all certificate authorities have started issuing certificates with a larger key size, and signed using sha384.

### Steps to Reproduce

You need:
1. A certificate signed using the sha384 algorithm installed in your personal certificate store
2. a file to be signed. in our case a clickonce manifest and application.

Use the SecurityUtilities class to sign the file, something like below:
```
using Microsoft.Build.Tasks.Deployment.ManifestUtilities;
using System;

namespace NovaSoftware.NsFrameworkTools.ClickOnceSigner
{
    class Program
    {
        static void Main(string[] args)
        {
            SecurityUtilities.SignFile("thumbprint of certificate", new Uri("Uri to timestamp server"), "path to file", "4.7.2");
        }
    }
}
```
And then run the program.

### Expected Behavior
SecurityUtilities signs the file with at least sha256

### Actual Behavior
The file is signed using sha1

### Analysis
The SecurityUtilities class only chooses sha256 if the certificate used is signed with sha256, otherwise it defaults to sha1. Our understanding of how certificates work is that the algorithm used to signed the certificate should not affect the available signing algorithms when using the certificate.

### Versions & Configurations
The issue is present in MSBuild main. We have investigated this in the v16.10 version.

### PR DESCRIPTION
**Pull request by sujitnayak**
Default to sha2 digest instead of sha1 for clickonce manifest signing when certificate signing algorithm is sha256/384/512

Fixes #6732 

### Context
When using a certificate signed with sha384/sha512 as signature algorithm, ClickOnce defaults to the sha1 algorithm for it's digest hash.

### Changes Made
UseSha256Algorithm decides if we sign with sha1 or sha256 hash. The function has been updated to use sha256 hash when signature algorithm of the signing cert has sha256/sha384/sha512 signature algorithm.

### Testing
CTI has tested signing scenario for forms and wpf apps for all 4 hash types.

### CODE REVIEW

File: src/Tasks/ManifestUtil/SecurityUtil.cs [hunk 1]
```diff
@@ -572,7 +572,9 @@ public static void SignFile(string certPath, SecureString certPassword, Uri time
         private static bool UseSha256Algorithm(X509Certificate2 cert)
         {
             Oid oid = cert.SignatureAlgorithm;
-            return string.Equals(oid.FriendlyName, "sha256RSA", StringComparison.OrdinalIgnoreCase);
+            return string.Equals(oid.FriendlyName, "sha256RSA", StringComparison.OrdinalIgnoreCase) ||
```
Comment (John-Hart) [inline src/Tasks/ManifestUtil/SecurityUtil.cs:575]: Can you add a short comment explaining why we use sha256 for the other certs?

**Review by John-Hart — APPROVED** [review]

File: src/Tasks/ManifestUtil/SecurityUtil.cs [hunk 2]
```diff
@@ -572,7 +572,11 @@ public static void SignFile(string certPath, SecureString certPassword, Uri time
         private static bool UseSha256Algorithm(X509Certificate2 cert)
         {
             Oid oid = cert.SignatureAlgorithm;
-            return string.Equals(oid.FriendlyName, "sha256RSA", StringComparison.OrdinalIgnoreCase);
+            // Issue 6732: Clickonce does support sha384/sha512 hash so we default to sha256
```
Comment (rainersigwald) [inline src/Tasks/ManifestUtil/SecurityUtil.cs:575]:
```suggestion
            // Issue 6732: Clickonce does not support sha384/sha512 hash so we default to sha256 
```

?

Comment (rainersigwald) [reply src/Tasks/ManifestUtil/SecurityUtil.cs:575]: I'm not sure this question makes sense but: Is it possible for a cert to have sha384/sha512 and _not_ have 256?

Comment (sujitnayak) [reply src/Tasks/ManifestUtil/SecurityUtil.cs:575]: We use the signature algorithm of the cert to decide what file digest algorithm to use for the clickonce manifest files. So for certs with sha1 signature, we choose sha1 file digest algorithm for clickonce manfest. With this change, we will use sha256 file digest algorithm for clickonce manifest if the signature algorithm in the cert is sha256 or sha384 or sha512.

The cert's signature algorithm is the algorithm used to create the signature of the cert and can be only 1 value like sha1/sha256/sha384/sha512.

Comment (rainersigwald) [reply src/Tasks/ManifestUtil/SecurityUtil.cs]: Ah, so it's an independent signature/algorithm but it makes sense to use the strongest possible one based on the signal of the cert provided?

**Review by rainersigwald — APPROVED** [review]

File: src/Tasks/ManifestUtil/SecurityUtil.cs (hunk 2 above)
Comment (sujitnayak) [reply src/Tasks/ManifestUtil/SecurityUtil.cs]: Correct.
