### PR TITLE
Initialize XmlReaders using StreamReaders

### LINKED ISSUE #6847: Initialize XmlReader Using A Stream
### Issue Description
See https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/349706.

When XmlReader.Create is called and a file path is passed in, it's converted to a URI under the hood. This can mangle multi-byte characters. The solution (in the link above) is to initialize the XmlReader using a stream to the file instead of the path alone.

Note this isn't an issue that we know of yet, the repro steps would fail if they were.

### Steps to Reproduce

create dir with `啊阿鼾齄丂丄狚狛狜狝﨨﨩ˊˋ˙–⿻〇㐀㐁䶴䶵` as part of the path

`dotnet new console -o proj`

create transform.xslt in proj dir, copy contents from below

add foo target (below) to proj

`msbuild proj`

should see success

Foo target:
```xml
 <Target Name="Foo" AfterTargets="Build">

      <XslTransformation XslInputPath="transform.xslt" XmlInputPaths="$(MSBuildThisFileFullPath)"

        OutputPaths="$(IntermediateOutputPath)output.xml"

        Parameters="&lt;Parameter Name='Parameter1' Value='$(Parameter1)'/&gt;" />

  </Target>

transform.xslt

<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet version="1.0"

xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">

  <html>

  <body>

    <h2>My CD Collection</h2>

    <table border="1">

      <tr bgcolor="#9acd32">

        <th>Title</th>

        <th>Artist</th>

      </tr>

      <tr>

        <td><xsl:value-of select="catalog/cd/title"/></td>

        <td><xsl:value-of select="catalog/cd/artist"/></td>

      </tr>

    </table>

  </body>

  </html>

</xsl:template>

</xsl:stylesheet>
```

Build succeeds.

### Analysis
This isn't an issue yet, but could be down the line.

Our code calls XmlReader.Create in two locations within the XslTransformation class which can be changed easily. 

The complication comes from XmlReaderExtension, which initializes an XmlReader via `new XmlTextReader(...)` and a path is passed in. We should avoid this and call `.Create()` passing in a stream, but this comment suggests that would be a breaking change: 

```
            // Ignore loadAsReadOnly for now; using XmlReader.Create results in whitespace changes
            // of attribute text, specifically newline removal.
            // https://github.com/Microsoft/msbuild/issues/4210
```

https://github.com/Microsoft/msbuild/issues/4210 is something @ladipro had worked on so you might have a better idea of what to do here. Thoughts?

https://github.com/benvillalobos/msbuild/commit/6943a559e43a6408c24a811704e806b3be6ea2c6 was my proposed fix before digging into #4210

### PR DESCRIPTION
**Pull request by BenVillalobos**
Fixes #6847

### Context
When XmlReader.Create is called and a file path is passed in, it's converted to a URI under the hood. This can mangle multi-byte characters. The solution (in the link above) is to initialize the XmlReader using a stream to the file instead of the path alone.

### Changes Made
Call XmlReader.Create with a stream that will detect encodings.

### Testing
Tested using repro in #6847

### CODE REVIEW

File: src/Tasks/XslTransformation.cs [hunk 1]
```diff
@@ -334,7 +335,7 @@ public XmlReader CreateReader(int itemPos)
             {
                 if (XmlMode == XmlModes.XmlFile)
                 {
-                    return XmlReader.Create(_data[itemPos]);
+                    return XmlReader.Create(new StreamReader(_data[itemPos], new UTF8Encoding(encoderShouldEmitUTF8Identifier: false), detectEncodingFromByteOrderMarks: true));
```
Comment (rainersigwald) [inline src/Tasks/XslTransformation.cs:338]: Have you validated that these encoding assumptions are valid for arbitrary user XML (as opposed to project files)?

Comment (BenVillalobos) [reply src/Tasks/XslTransformation.cs:338]: I haven't. I've been poking around with this fix quite a bit now, maybe you'll have a better idea.

This fix is a bit overkill, all that's really needed is `new StreamReader(_data[itemPos])`. But there's a single failure in `XslDocumentFunctionWorks` that is somehow looking for `b.xml` in the bin directory of the running unit test that's very confusing. It occurs right as it's attempting to transform an xslt file

**Comment by BenVillalobos** [comment]
Digging into the error a bit more, it looks like initializing the XmlReader with a FileScheme Uri causes funky behavior when transforming an Xslt doc that calls the `Document` function. The Document function looks up data in another document.

From what I can tell, loading the document from a stream is causing issues when calling functions from the loaded xslt. When `Document` is called from `a.xml` and looks for `b.xml`, it now tries to find `b.xml` in the output bin directory from the current unit test project, _instead of_ temp where the files were generated.

----

A quick chat with Rainer showed that there's an overload to XmlReader.Create that takes a base path, and passing the original filepath ensures the path stays relative, solving the Document issue and the mangled character issue 🎉

**Comment by BenVillalobos** [comment]
To-Do: Test an xslt doc calling the `Document` method for a file in the same unicode-style path that causes the error.

**Comment by BenVillalobos** [comment]
> To-Do: Test an xslt doc calling the Document method for a file in the same unicode-style path that causes the error.

It fails

image

```
"C:\src\temp\9-16\11_25\new\???????????????'`?-?        ????U1[?????]U2[????]U3[?????]\proj1\proj1.csproj" (default target) (1) ->
(Foo target) ->
  C:\src\temp\9-16\11_25\new\???????????????'`?-?       ????U1[?????]U2[????]U3[?????]\proj1\proj1.csproj(11,5): error MSB3703: Unable to execute transformation. An error occurred while loading document 'b.xml'. See InnerException for a c
omplete description of the error.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.53
```

We'd need to catch this exception and output a better string here.

**Comment by BenVillalobos** [comment]
imo we merge this and file an issue in the runtime tracking this

**Review by rainersigwald — APPROVED** [review]

**Comment by BenVillalobos** [comment]
Issue filed: https://github.com/dotnet/runtime/issues/59353
