### PR TITLE
Make folder if needed for MSBUILDDEBUGPATH Fixes #7552

### LINKED ISSUE #7552: BuildEnvironmentHelper Tests With Process Detection Logic Get Confused
### Issue Description
The new-and-improved process detection logic in BuildEnvironmentHelper confuses tests, which run a "fake" 64-bit MSBuild.exe in an x86 process.

The detection logic:

https://github.com/BenVillalobos/msbuild/blob/525eebc0f31f8c770ad7b1636866aa2a15850e41/src/Shared/BuildEnvironmentHelper.cs#L540-L546

### Steps to Reproduce
Un-skip the relevant tests that were disabled in https://github.com/dotnet/msbuild/pull/7550 and run tests.

### LINKED ISSUE #7752: [REGRESSION] After upgrading to VS 17.2.5 the MSBuildDebugEngine environment variable is no longer respected.
## Visual Studio Version
17.2.5

## Summary
Setting MSBuildDebugEngine and MSBUILDDEBUGPATH does not produce the same effect as in VS 17.1.x, namely no binary logs no text files are produced at all.

## Steps to Reproduce

1. Set the aforementioned env variables
2. Open devenv from the console where the env is updated.
3. Build a project

## Expected Behavior
Binary logs and some text files are produced in the folder specified by MSBUILDDEBUGPATH 

## Actual Behavior
No files are produced.

## User Impact
Unable to troubleshoot VS build issues

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #7752

### Context
When using MSBuildDebugEngine, we recommend specifying MSBUILDDEBUGPATH. If you specify somewhere we can't write to, we have fallbacks. However, if you specify somewhere we can write to but doesn't yet exist, we can't write to it yet, so that part returns false, and we go on to the fallbacks. This makes the folder explicitly if we can, making it return true if we can write to a directory, but it doesn't yet exist.

### Changes Made
Create folder if needed.

### Testing
Tested before and after the change, and it worked.

### CODE REVIEW

File: src/Shared/FileUtilities.cs [hunk 1]
```diff
@@ -174,6 +174,8 @@ internal static bool CanWriteToDirectory(string directory)
             try
             {
                 string testFilePath = Path.Combine(directory, $"MSBuild_{Guid.NewGuid().ToString("N")}_testFile.txt");
+                FileInfo file = new(testFilePath);
+                file.Directory.Create(); // If the directory already exists, this method does nothing.
```
Comment (rainersigwald) [inline src/Shared/FileUtilities.cs:178]: Does this work if multiple levels of the nesting don't exist? I would assume so but the docs don't explicitly say. https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.create?view=net-6.0

Comment (Forgind) [reply src/Shared/FileUtilities.cs:178]: Yes. I tried `newFolder\otherFolder\thirdFolder` from a folder that existed (where none of those folders existed previously), and they were all made.

**Review by rainersigwald — APPROVED** [review]
