### PR TITLE
[LiveLogger] Fix for conhost.exe

### LINKED ISSUE #8455: [LiveLogger] Garbled output in cmd.exe
### Issue Description

LiveLogger does not work in cmd.exe.

### Steps to Reproduce

`dotnet build /ll` in cmd.exe.

### Expected Behavior

Either LiveLogger errors out or MSBuild falls back to regular console logging.

### Actual Behavior

My first attempt to use LiveLogger resulted in this:

image

### Analysis

If this console is not fancy-capable then the logger should not be allowed to run. Note that you still get this kind of console when running the VS Developer prompt as administrator so this would be a blocker for enabling LL by default.

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by edvilme**
Fixes #8455

### Context
LiveLogger is only enabled for terminal emulators that support VT100/ANSI escape sequences. On Windows, these are supported by default on Windows Terminal, but Console Host (the old terminal emulator) does not support all of them. Hence LiveLogger checks if the code is run on Windows Terminal via the `WT_SESSION` environment variable. 

### Changes Made
Added check for when `Environment.GetEnvironmentVariable("WT_SESSION") == null`

### CODE REVIEW

File: src/MSBuild/XMake.cs [hunk 1]
```diff
@@ -3444,7 +3444,7 @@ private static bool DoesEnvironmentSupportLiveLogger()
             }
             // If terminal is dumb
             if (
-                (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && Environment.GetEnvironmentVariable("WT_SESSION") == "")
+                (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && (Environment.GetEnvironmentVariable("WT_SESSION") == "" || Environment.GetEnvironmentVariable("WT_SESSION") == null))
```
Comment (Forgind) [inline src/MSBuild/XMake.cs:3447]: nit:
```suggestion
                (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && string.IsNullOrEmpty(Environment.GetEnvironmentVariable("WT_SESSION")))
```

I find this simpler and often use it even if I think only one of those will show up just because we often realize we need both, and they're often intended to indicate the same thing 🙂

**Review by Forgind — APPROVED** [review]

**Review by ladipro — APPROVED** [review]

**Review by JanKrivanek — APPROVED** [review]

**Comment by ladipro** [comment]
Just an observation that `WT_SESSION` is not defined when launching with F5 in Visual Studio, despite the terminal being capable. With the change in this PR I have to add the variable explicitly in order to debug LiveLogger. My launchSettings.json:

```json
{
  "profiles": {
    "Profile 1": {
      "commandName": "Executable",
      "executablePath": "C:\\src\\msbuild\\artifacts\\bin\\bootstrap\\net472\\MSBuild\\Current\\Bin\\amd64\\msbuild.exe",
      "commandLineArgs": "/ll",
      "workingDirectory": "C:\\temp\\SimpleWebApp",
      "environmentVariables": {
        "WT_SESSION": "abc"
      }
    }
  }
}
```

**Comment by Forgind** [comment]
> Just an observation that `WT_SESSION` is not defined when launching with F5 in Visual Studio, despite the terminal being capable. With the change in this PR I have to add the variable explicitly in order to debug LiveLogger. My launchSettings.json:
> 
> ```json
> {
>   "profiles": {
>     "Profile 1": {
>       "commandName": "Executable",
>       "executablePath": "C:\\src\\msbuild\\artifacts\\bin\\bootstrap\\net472\\MSBuild\\Current\\Bin\\amd64\\msbuild.exe",
>       "commandLineArgs": "/ll",
>       "workingDirectory": "C:\\temp\\SimpleWebApp",
>       "environmentVariables": {
>         "WT_SESSION": "abc"
>       }
>     }
>   }
> }
> ```

Is the LiveLogger supposed to be on in VS? I thought we'd decided we wanted it off.

**Comment by ladipro** [comment]
> Is the LiveLogger supposed to be on in VS? I thought we'd decided we wanted it off.

Adding to the list of items to clarify, thank you!

However, running the .NET build of MSBuild under VS has the same issue. The terminal created by VS on F5 does not have `WT_SESSION` defined.

**Comment by ladipro** [comment]
The Internet seems to think that checking the result of `GetConsoleMode` for `ENABLE_VIRTUAL_TERMINAL_PROCESSING` may be a better way of detecting fancy-capable environments.

**Comment by rainersigwald** [comment]
> The Internet seems to think that checking the result of `GetConsoleMode` for `ENABLE_VIRTUAL_TERMINAL_PROCESSING` may be a better way of detecting fancy-capable environments.

this snippet from pwsh looks relevant:

https://github.com/SteveL-MSFT/PowerShell/blob/4c01dcc5d5672f4b0ccbac87fe756de01f487887/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L64-L85
