### PR TITLE
Tasks `Log.HasLoggedError` now respects `MSBuildWarningsAsErrors`

### LINKED ISSUE #5511: HasLoggedErrors should respect MSBuildWarningsAsErrors
### Steps to reproduce

[warnaserr.tar.gz](https://github.com/microsoft/msbuild/files/4915653/warnaserr.tar.gz)

```csharp
    public class MyTask : Task
    {
        public override bool Execute()
        {
            Log.LogWarning(subcategory: null,
                           warningCode: "MyWarning1234",
                           helpKeyword: null,
                           file: null,
                           lineNumber: 0,
                           columnNumber: 0,
                           endLineNumber: 0,
                           endColumnNumber: 0,
                           message: "my warning");

            return !Log.HasLoggedErrors;
        }
    }
```

```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <MSBuildWarningsAsErrors>MyWarning1234</MSBuildWarningsAsErrors>
  </PropertyGroup>

  <UsingTask TaskName="task.MyTask" AssemblyFile="$(MSBuildThisFileDirectory)../task/bin/Debug/net5.0/task.dll" />
  <Target Name="MyTargetOuter"
          DependsOnTargets="MyTargetInner">
    <Message Importance="High" Text="Outer target" />
  </Target>

  <Target Name="MyTargetInner">
    <MyTask />
  </Target>
```

```
> dotnet msbuild /t:MyTargetOuter
warnaserr/project/project.csproj(16,5): error MyWarning1234: my warning
  Outer target
```

### Expected behavior

`Log.HasLoggedErrors` returns `true` when the logged warning is treated as an error due to `MSBuildWarningsAsErrors`, causing the build to stop after `MyTask`.

### Actual behavior

`HasLoggedErrors` returns `false`, the build continues, and the outer target runs even after the task produced an error. 

Perhaps this is the intended behavior. If that's the case, is there a recommended way for tasks to check whether any of their warnings have been turned into errors?

We are using ToolTask (which relies on `HasLoggedErrors` by default) for the IL linker MSBuild task, and we don't want to continue the build if any errors were logged - otherwise we touch a file on disk that prevents the linker from running incrementally next time.

### Environment data
`msbuild /version` output: 16.7.0.36003

OS info: 18.04.1-Ubuntu

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): dotnet cli

### PR DESCRIPTION
**Pull request by BenVillalobos**
Fixes #5511

### Context
Tasks have a Log.HasLoggedErrors property that does not respect warnings that were thrown as errors when listed under `MSBuildWarningsAsErrors`.

### Changes Made
- IBuildEngine8 has a hashset of warnings to be converted into errors.
- ILoggingService has a method to extract warnings to be logged as errors based on the build context.
- TaskHostConfiguration had warningsaserrors hashset added to it so that the OOPTaskHostNode can set up properly.

### Testing
- `TaskReturnsTrueButLogsError_BuildShouldContinue`
- `WarningsAsErrors_ExpectBuildToStopWhenTaskLogsWarningAsError`
- `TestTranslationWithWarningsAsErrors`
- [x] Confirmed this fixes the repro in the linked issue.
- [x] Need to test batched builds, as a `TaskHost` is generated per 'bucket'

### Notes
Comment from Rainer in previous PR about this: https://github.com/dotnet/msbuild/pull/5957 

> The PR that introduced warning-as-error is #1355--#1928 extended it to allow the project level properties.
> 
> Since that's done in the logging infrastructure rather than at the point of logging, I think that's the problem. Unfortunately I don't know if there's an easy way to move it. Can you investigate that angle? Is the warning-as-errors stuff available in TaskHost and if not how hard would it be to get it there?
> 
> I don't think we should attack the problem for TaskLoggingHelper alone--if you attack it at the IBuildEngine API layer, it'll work for everything, not just tasks that use the helper classes.

### CODE REVIEW

File: src/Utilities/Task.cs [hunk 1]
```diff
@@ -94,6 +94,11 @@ protected Task(ResourceManager taskResources, string helpKeywordPrefix)
         /// </summary>
         public IBuildEngine7 BuildEngine7 => (IBuildEngine7)BuildEngine;
 
+        /// <summary>
+        /// Retrieves the <see cref="IBuildEngine8" /> version of the build engine interface provided by the host.
+        /// </summary>
+        public IBuildEngine7 BuildEngine8 => (IBuildEngine8)BuildEngine;
```
Comment (Forgind) [inline src/Utilities/Task.cs:100]:
```suggestion
        public IBuildEngine8 BuildEngine8 => (IBuildEngine8)BuildEngine;
```

**Review by Forgind — COMMENTED** [review]
This looks like it should work, but it's also kinda a heavy solution. Is there something simpler? Alternatively, do you think it would make sense to add a Dictionary<string, string> with dict["warningsAsErrors"] == what WarningsAsErrors is here (post-serialization). The reason that might make sense is that it would be good to avoid having too many new IBuildEngines, and that would mean that, for any future IBE where we just need to make a certain piece of information more visible, we could add a kvp instead of adding a new ibe. What do you think?

**Comment by BenVillalobos** [comment]
@Forgind This is a great idea imo. This begs a few questions, like what is the key in this dictionary. It could be <string, string>, then the value would have to be a semicolon delimited list, then tasks are parsing more strings and therefore allocating. 

Perhaps <string, object>? Where the task that needs to use, say, dictionary["WarningsAsErrors] would know that the value is a list and would perform (dictionary["WarningsAsErrors] as List<string>).contains("msb1234") or something equivalent?

This might be complicated for the OOP task host that needs to translate these objects through the binary formatter. And we may need to special case every object. I'm slowly convincing myself <string, object> is a bad idea.

@cdmihai thoughts?

**Comment by Forgind** [comment]
Well, it has to translate them through the BinaryFormatter now, but that has to change eventually. I do like the reusability of `object` over string, but maybe as a middle ground, <string, serializable object>? That makes calling Translate on them relatively easy but avoids the excess allocations from my suggestion.

Also, if we're going this way, one thing to not do in this PR but possibly consider for the future is whether we could have a second dictionary of <string, delegate> that we could use for methods. Smaller win, in my view, for more ugliness, but that would hopefully mean we could stop making more IBuildEngines. I live for the day when you can just say `if (BuildEngine.<nameOfDict>.TryGet(<key>, out ...)) ... without needing to check whether your BuildEngine is a new enough BuildEngine. That's probably a pipe dream, though.

**Comment by cdmihai** [comment]
Regarding the `dict<string, object>` to avoid revving up the IBE interface, I don't like it :). Users would have to know the magic string and then explicitly cast the delegate object to its actual type in order to use the delegate's return type and arg types. I'd rather we add one last IBE interface that has a reference to an abstract class containing the functionality of future IBEs: `IBuildEngine9.EngineServices`, with `EngineServices` an abstract class that keeps on accumulating APIs.

The downside to the abstract class approach is that newer tasks that depend on a new `EngineServices` API won't be able to function as easily with older versions of msbuild that do not have that API. With the current interface numbering scheme and with the `dict<string, object>` scheme, tasks can query functionality at runtime. With the abstract class, tasks that really want back-compat (supporting older msbuilds) will have to use reflection on `EngineServices`. On the other hand, I don't think it's that common for tasks to support older engines and the few that do can use reflection.

**Comment by Forgind** [comment]
Currently, users need to know the exact name of property they need, which is the semantic equivalent of needing to know the exact string. To be clear, I consider Dictionary<string, delegate> as the more controversial and probably undesirable cousin of having Dictionary<string, object : Translatable> with the values specifically for things like properties. You presumably know what type they should be if you're trying to use them, just as you would need to figure out the type of a property. Letting it be object instead of string makes it more flexible if we need unusual objects later.

I do like the abstract class plan, although a simpler approach might be to have IBuildEngine9 (possibly renamed) be an abstract class itself, and have it extend IBuildEngine8 and be extended as if it were an interface. As long as we provide a default implementation for everything, it should prevent people from being broken just for extending it. Reflection is kinda slow.

Do you want to set up a meeting to talk about it?

File: src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs [hunk 2]
```diff
@@ -272,6 +272,34 @@ private string GetTestProject(bool? treatAllWarningsAsErrors = null, string warn
...
+                    </Target>
+                </Project>");
+
+                MockLogger logger = proj.BuildProjectExpectFailure();
+
+                logger.WarningCount.ShouldBe(0);
+                logger.ErrorCount.ShouldBe(1);
+
+                // The build should STOP when a task logs an error, make sure ReturnFailureWithoutLoggingErrorTask doesn't run. 
+                logger.AssertLogDoesntContain("MSB4181");
```
Comment (cdmihai) [inline src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs:299]: I think this may not work with tasks that implement ITask directly. Can you please add another test just like this one but calling a task implementing ITask directly?

Comment (BenVillalobos) [reply src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs:299]: Interesting. Going to brain dump this before making the test.

Someone implementing ITask wouldn't have access to a TaskLoggingHelper (like Task does) and thus have to log a warning through the `BuildEngine.LogWarningEvent`. The build engine would log it to the logging service as a warning and at `LoggingService.RouteBuildEvent` it would be translated into an error.

But I think the build would continue because it entirely depends on what the task returned right? So long as the task returns true despite logging an error, the build will complete.

Question, what context would someone implement itask vs inheriting from task?

**Comment by BenVillalobos** [comment]
I created https://github.com/dotnet/msbuild/issues/6183 to track discussion for making a more generalized IBuildEngine interface.

@Forgind, you created IBuildEngine7, how do you know whether that new property works in a OOP task host node?

I was under the impression we needed to pass that value to the OOPTaskHostNode through `TaskHostConfiguration`.
/cc @cdmihai for this question as well.

File: src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs (hunk 2 above)
Comment (cdmihai) [reply src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs:299]: Don't really know why people would do it, but according to this [GH search](https://sourcegraph.com/search?q=lang%3Acsharp+%28content%3A%22%3A+ITask+%22+or+content%3A%22%3A+ITask%5Cn%22%29+and+content%3A%22using+Microsoft.Build.Framework%22+count%3A1000&patternType=literal) they do it.

> So long as the task returns true despite logging an error, the build will complete.

I think MSBuild might either warn or error that the task returned true but an error was logged. Not super sure about this though, so worth writing a test to pin the behaviour :)
On the other hand, since an ITask implementation cannot know whether any errors were logged (because it does not have access to `Log`), maybe this whole scenario does not make sense and we can ignore it.

**Comment by Forgind** [comment]
I'm slightly confused by your question, so I'll answer what I think you're asking. Let me know if I'm wrong.

Wherever I have access to the BuildEngine, I can say `if be is IBuildEngine7 be7` (or the equivalent) then use be7 to access my property.

An out-of-proc TaskHost node is an IBuildEngine(7), so I can try to access properties directly without casting. A newer TH will succeed, and an older TH won't have the newer code that tries.

Did that answer your question?

**Comment by BenVillalobos** [comment]
@Forgind Yes~ish. I see how my question was confusing. IBE7 added a property that a task could set on its own. IBE8 will need information passed to it that a task can then access. From a taskhost perspective it's not difficult at all. OOPTHN is a slightly different story.

My confusion comes from the OOPTHN and how it receives this data. From what I could gather (and please correct me if I'm wrong /cc: @cdmihai or @KirillOsenkov 🙂), an OOPTHN needs to be passed initialization data in the form of a `TaskHostConfigurationData`. See here: https://github.com/dotnet/msbuild/blob/master/src/MSBuild/OutOfProcTaskHostNode.cs#L604. So that's how I need to give it the warnings that will be translated into errors.

Another question, do we not have tests for OOPTHN? I can't seem to find anything testing that specifically. Or is testing the translation data enough?

File: src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs (hunk 2 above)
Comment (BenVillalobos) [reply src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs:299]: I agree that there's no need to check this on an ITask. Something interesting about the error task. It explicitly returns false otherwise the build would continue: https://github.com/dotnet/msbuild/blob/f0eebf2872d76ab0cd43fdc4153ba636232b222f/src/Tasks/Error.cs#L47 that's a very strange disconnect that sounds to me like it should be an issue to fix. But if that's just how msbuild has been since the beginning of time...should we consider fixing it?

**Comment by BenVillalobos** [comment]
NTS: Test failures have to do with `WarningsAsMessages`. Apparently that takes precedence over `WarningsAsErrors`.

**Comment by cdmihai** [comment]
@BenVillalobos, we have the same impression on how OOPTHN gets its data. But always leave room for surprise ...

File: src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs (hunk 2 above)
Comment (cdmihai) [reply src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs:299]: It comes from an era where an error was an error, so returning false makes sense :)

I'd wait until somebody reports an issue and then update both Error and Warning.

Comment (Forgind) [reply src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs:299]: Sorry, why is that wrong? A task returns false if it logged an error. The Error task is designed to log an error, hence always returns "HasLoggedAnError."

**Comment by Forgind** [comment]
Adding which warnings should be treated as errors to the TaskHostConfiguration sounds right to me.

File: src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs (hunk 2 above)
Comment (BenVillalobos) [reply src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs:299]: I should have included it in the code sample, but the error task called `Log.LogError` and simply returns false, not `Log.HasLoggedErrors`.

Comment (Forgind) [reply src/Build.UnitTests/WarningsAsMessagesAndErrors_Tests.cs:299]: Right...it has always logged an error because it logs an error right before the return statement.

Right, and people who log errors tend to want execution to stop at that point. No point continuing if something went irrevocably wrong.

**Comment by BenVillalobos** [comment]
Current failing tests, it repros on running the cibuild bootstrapped msbuild script.
```
MSB4254: The MSBuild task is building project(s) ""C:\Users\VssAdministrator\AppData\Local\Temp\xgsgpevo.slz\tmpd327c2f9b2b44a92b1ac89182251db5b.tmp"" which are not specified in the ProjectReference item. In isolated builds this probably means that the references are not explicitly specified as a ProjectReference item in "C:\Users\VssAdministrator\AppData\Local\Temp\xgsgpevo.slz\tmp65202fb4e3174d70a0ec0ef0aa7c0560.tmp"  C:\Users\VssAdministrator\AppData\Local\Temp\xgsgpevo.slz\tmp65202fb4e3174d70a0ec0ef0aa7c0560.tmp
```

Not actually sure what to do here?

**Comment by Forgind** [comment]
This is from a test? Is it a new test? From what I can tell, that means you have project A that invokes the MSBuild task on project B, except B isn't a "known" reference to A, specified via ProjectReference. Fix should be as simple as adding a ProjectReference from A to B.

**Comment by BenVillalobos** [comment]
@Forgind these are from preexisting tests such as:

UndeclaredReferenceEnforcementShouldFailOnPreviouslyBuiltButUndeclaredReferences
UndeclaredReferenceEnforcementShouldFailOnUndeclaredReference 
CacheEnforcementShouldFailWhenReferenceWasNotPreviouslyBuiltWithoutContinueOnError

Unfortunately I need to download dogfood VS to debug this. I tried deploying a bootstrapped msbuild on a pre-stringtools commit and hit some errors. (296b3671db)

**Comment by cdmihai** [comment]
Those are the graph /isolate constraints. I would not expect this PR to touch any of that, so it's pretty weird that they're affected. Could mean that extra msbuild task calls get executed now whereas on master they're not.

**Comment by BenVillalobos** [comment]
@cdmihai I suspect it has something to do with `ContinueOnError`, that's the only thread I can see that seems remotely related.

File: src/Shared/TaskLoggingHelper.cs [hunk 3]
```diff
@@ -1016,6 +1016,35 @@ public void LogWarning
             // that gives the user something.
             bool fillInLocation = (String.IsNullOrEmpty(file) && (lineNumber == 0) && (columnNumber == 0));
 
+            IBuildEngine8 be8 = (BuildEngine as IBuildEngine8);
+
+            // This warning will be converted to an error if:
+            // 1. Its code exists within WarningsAsErrors
+            // 2. If WarningsAsErrors is a non-null empty set (treat all warnings as errors)
+            if (be8?.WarningsAsErrors?.Contains(warningCode) == true || be8?.WarningsAsErrors?.Count == 0)
```
Comment (Forgind) [inline src/Shared/TaskLoggingHelper.cs:1024]: Just to make this a little easier to reason about...
```suggestion
            // This warning will be converted to an error if:
            // 1. Its code exists within WarningsAsErrors
            // 2. If WarningsAsErrors is a non-null empty set (treat all warnings as errors)
            if (BuildEngine is IBuildEngine8 be8 && (be8.WarningsAsErrors.Contains(warningCode) || be8.WarningsAsErrors.Count == 0))
```

**Comment by Forgind** [comment]
Just looking at the first one, it's supposed to throw that error, so the surprise isn't _that_ it's throwing the error but that it isn't catching it and returning "test passed." In my quick pass through this PR, nothing stood out as a likely culprit. Since they're preexisting tests, maybe reset and run the tests with each commit one-by-one? Maybe AssertBuild works subtly differently now, and it's throwing errors in a different order than before?

**Comment by BenVillalobos** [comment]
@Forgind I hadn't considered testing commit by commit, good idea.

**Comment by BenVillalobos** [comment]
NTS: Didn't see this fail in 997b8fc781.

**Comment by BenVillalobos** [comment]
Turns out that test wasn't actually failing, I was failing to read the log properly. Added a null check for test compat.

File: src/Framework/IBuildEngine8.cs [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+
+namespace Microsoft.Build.Framework
+{
+    /// <summary>
+    /// This interface extends <see cref="IBuildEngine7" /> to allow tasks know if a warning
+    /// they logged was turned into an error.
+    /// </summary>
+    public interface IBuildEngine8 : IBuildEngine7
+    {
+        public HashSet<string> WarningsAsErrors { get; }
```
Comment (cdmihai) [inline src/Framework/IBuildEngine8.cs:14]: Do we actually need to make this a public API? Or to just ensure that HasLoggedErrors works as expected?

Comment (BenVillalobos) [reply src/Framework/IBuildEngine8.cs:14]: Good point. I'll remove public on warningsaserrors

Comment (KirillOsenkov) [reply src/Framework/IBuildEngine8.cs:14]: So do we need IBuildEngine8 then?

Comment (BenVillalobos) [reply src/Framework/IBuildEngine8.cs:14]: I may have been confused by the original question. WarningsAsErrors needs to be visible to the tasklogginghelper so it can determine if it actually logged an error when it tries to log a warning. Without IBE8 having this hashset I'm not aware of a to get that info.

Comment (KirillOsenkov) [reply src/Framework/IBuildEngine8.cs:14]: Interface members are public by default so if you remove the public keyword nothing will change, it will still be a public member on a public interface.

So I guess to answer Mihai's question we do need an `IBuildEngine8` and it does need to have the `WarningsAsErrors` member, right? Just to confirm.

Comment (KirillOsenkov) [reply src/Framework/IBuildEngine8.cs:14]: I'm thinking, should we make the return type `ICollection<string>`? It would still be backed by a HashSet<string> but we'd return a more general type. HashSet<T> feels like an implementation detail. Contains(T) would still be implemented efficiently by the HashSet<T>.

Feels like we're painting ourselves in the corner here, instead of leaving room for potential other implementations in the future shall the need arise.

File: src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs [hunk 5]
```diff
@@ -419,6 +457,7 @@ public void TestTranslationWithITaskItemArrayInDictionary()
                 "TaskName",
                 @"c:\MyTasks\MyTask.dll",
                 parameters,
+                null,
```
Comment (KirillOsenkov) [inline src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs:460]: It's a good practice to specify the parameter name when passing `null`, `false`, `true` or other literal as an argument.

Comment (KirillOsenkov) [reply src/Build.UnitTests/BackEnd/TaskHostConfiguration_Tests.cs:460]: Because when reading the code I have no idea what that parameter is and what type it is.

File: src/Build/BackEnd/Components/Logging/ILoggingService.cs [hunk 6]
```diff
@@ -219,6 +219,14 @@ bool IncludeTaskInputs
         /// <returns><code>true</code> if the build submission logged an errors, otherwise <code>false</code>.</returns>
         bool HasBuildSubmissionLoggedErrors(int submissionId);
 
+        /// <summary>
+        /// Returns a hashset of warnings to be logged as errors for the specified project instance ID.
+        /// Note that WarningsAsMessages takes priority over WarningsAsErrors and are excluded from the set.
+        /// </summary>
+        /// <param name="context">The build context through which warnings will be logged as errors.</param>
+        /// <returns>A Hashset containing warning codes that should be treated as warnings that will not be treated as messages.</returns>
+        HashSet<string> GetWarningsToBeLoggedAsErrorsByProject(BuildEventContext context);
```
Comment (KirillOsenkov) [inline src/Build/BackEnd/Components/Logging/ILoggingService.cs:228]: Consider returning `ICollection<string>` here.

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 7]
```diff
@@ -515,6 +515,40 @@ public bool HasBuildSubmissionLoggedErrors(int submissionId)
...
+        /// Note that WarningsAsMessages takes priority over WarningsAsErrors and are excluded from the set.
+        ///
+        /// If all warnings to be treated as errors should also be treated as messages, return null otherwise
+        /// all warnings will be treated as errors. <see cref="RequestBuilder.ConfigureWarningsAsErrorsAndMessages()"/>
+        /// </summary>
+        /// <param name="context">The build context through which warnings will be logged as errors.</param>
+        /// <returns>A Hashset containing warning codes that should be treated as errors.</returns>
+        public HashSet<string> GetWarningsToBeLoggedAsErrorsByProject(BuildEventContext context)
+        {
+            if(_warningsAsErrorsByProject == null)
```
Comment (KirillOsenkov) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:529]: If you format the file, a space will appear between `if` and `(` :) Best to add one :)

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 8]
```diff
@@ -515,6 +515,40 @@ public bool HasBuildSubmissionLoggedErrors(int submissionId)
...
+            {
+                return null;
+            }
+
+            int key = GetWarningsAsErrorOrMessageKey(context);
+
+            HashSet<string> warningsAsErrorsExcludingMessages = new HashSet<string>(_warningsAsErrorsByProject?[key]);
```
Comment (KirillOsenkov) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:536]: Can probably remove the question mark since we've checked for null above?

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 9]
```diff
@@ -515,6 +515,40 @@ public bool HasBuildSubmissionLoggedErrors(int submissionId)
...
+        /// If all warnings to be treated as errors should also be treated as messages, return null otherwise
+        /// all warnings will be treated as errors. <see cref="RequestBuilder.ConfigureWarningsAsErrorsAndMessages()"/>
+        /// </summary>
+        /// <param name="context">The build context through which warnings will be logged as errors.</param>
+        /// <returns>A Hashset containing warning codes that should be treated as errors.</returns>
+        public HashSet<string> GetWarningsToBeLoggedAsErrorsByProject(BuildEventContext context)
+        {
+            if(_warningsAsErrorsByProject == null)
+            {
+                return null;
```
Comment (KirillOsenkov) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:531]: Returning null for methods that return collections is unexpected. If you change the return type to `ICollection<string>` you'll be able to also return `Array.Empty<string>()` which is preferable.

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 10]
```diff
@@ -515,6 +515,40 @@ public bool HasBuildSubmissionLoggedErrors(int submissionId)
...
+
+            int key = GetWarningsAsErrorOrMessageKey(context);
+
+            HashSet<string> warningsAsErrorsExcludingMessages = new HashSet<string>(_warningsAsErrorsByProject?[key]);
+
+            if(_warningsAsMessagesByProject != null)
+            {
+                warningsAsErrorsExcludingMessages.ExceptWith(_warningsAsMessagesByProject[key]);
+
+                // A non-null empty set means all warnings are errors. Avoid this.
```
Comment (KirillOsenkov) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:542]: This contract seems unclear. As a rule, null or empty collections shouldn't have different semantic meanings, otherwise it's very confusing. If you need to, perhaps make this explicit and either add a bool out parameter or return a tuple or a data type?

File: src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs [hunk 11]
```diff
@@ -5,6 +5,7 @@
 using Microsoft.Build.Framework;
 using Microsoft.Build.Shared;
 using Microsoft.Build.Execution;
+using System.Collections.Generic;
```
Comment (KirillOsenkov) [inline src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs:8]: Sort System namespaces first?

File: src/Shared/TaskHostConfiguration.cs [hunk 12]
```diff
@@ -103,6 +105,7 @@ internal class TaskHostConfiguration : INodePacket
         /// <param name="taskLocation">Location of the assembly the task is to be loaded from.</param>
         /// <param name="taskParameters">Parameters to apply to the task.</param>
         /// <param name="globalParameters">global properties for the current project.</param>
+        /// <param name="warningsAsErrors">Warning codes to be thrown as errors for the current project.</param>
```
Comment (KirillOsenkov) [inline src/Shared/TaskHostConfiguration.cs:108]: perhaps logged or reported? Throw implies exception I think

File: src/Shared/TaskLoggingHelper.cs [hunk 13]
```diff
@@ -1016,6 +1016,28 @@ public void LogWarning
             // that gives the user something.
             bool fillInLocation = (String.IsNullOrEmpty(file) && (lineNumber == 0) && (columnNumber == 0));
 
+            // This warning will be converted to an error if:
+            // 1. Its code exists within WarningsAsErrors
+            // 2. If WarningsAsErrors is a non-null empty set (treat all warnings as errors)
+            if (BuildEngine is IBuildEngine8 be8 && be8.WarningsAsErrors != null && (be8.WarningsAsErrors.Contains(warningCode) || be8.WarningsAsErrors.Count == 0))
```
Comment (KirillOsenkov) [inline src/Shared/TaskLoggingHelper.cs:1022]: I think it'll be better if we make this contract explicit. An empty collection for all warnings as errors is confusing. 

Do we already have WarningsAsErrors somewhere? If not, we could use a trick and return an implementation of `ICollection<string>` that always returns `true` from the `Contains()` method.

**Comment by KirillOsenkov** [comment]
So I've been having some shower thoughts: do we need to even expose the set/collection of warnings as errors? 

What if we just add `bool LogWarningAsError(string code)` on `IBuildEngine8` instead and then the implementation can return true if you have all warnings as errors, or hit the HashSet for specific ones?

**Comment by Forgind** [comment]
I don't see anything wrong with that.

File: src/Framework/IBuildEngine8.cs (hunk 4 above)
Comment (BenVillalobos) [reply src/Framework/IBuildEngine8.cs:14]: We need an IBuildEngine8 that provides _some way_ of telling tasks that what it is about to log will turn into an error. I like the idea from your other comment suggesting we turn it into a method. I'll comment my thoughts related to that there.

Also, turning this into an ICollection<string> makes sense.

**Comment by BenVillalobos** [comment]
@KirillOsenkov That was the original implementation. One issue with that (at the time) was the OOPTaskHost not having access to a logging service and therefore not knowing what would be converted from warn->err.

I think we've solved that at this point by giving OOPTHN a collection of warnings to be treated as errors. So we can come back to that version of IBE8 and a tasklogginghelper no longer needs to manually check.

**Comment by KirillOsenkov** [comment]
Sounds good. And what do you think about replacing the `HashSet<string>` with `ICollection<string>` type?

Apologies if I'm being pedantic :)

File: src/Build/BackEnd/Components/Logging/LoggingService.cs (hunk 10 above)
Comment (BenVillalobos) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:542]: I generally agree, but this was written with the intent of matching the current implementation (which I'm open to changing).

See these files:
1. [Line 1582 of LoggingService.cs](https://github.com/dotnet/msbuild/blob/master/src/Build/BackEnd/Components/Logging/LoggingService.cs#L1586)
2. [Line 1242 of RequestBuilder.cs](https://github.com/dotnet/msbuild/blob/master/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L1242)

We talked a bit about it in PR review and didn't come to a strong conclusion for any particular side.

It's worth mentioning that if we switch IBE8 from having a hashset to having a method that returns true or false, we can change the underlying implementation with less hassle. Whereas if we merge this and decide to add a type or extra information to determine warningsaserrors, we'd need to add an IBE9 or modify IBE8.

/cc: @jeffkl as the original author

**Comment by jeffkl** [comment]
Sorry I haven't had a chance to look at this sooner, let me dive into it...

**Comment by BenVillalobos** [comment]
@jeffkl To be fair, I should have pinged sooner. Just a heads up, I'm about to change IBE8 to have `bool ShouldLogWarningAsError(string code)` instead of the set containing the warning codes as mentioned above.

File: src/Framework/IBuildEngine8.cs (hunk 4 above)
Comment (cdmihai) [reply src/Framework/IBuildEngine8.cs]: The whole interface could be private :) But that would partition the entire supertype API in a private part and a public part. The public parts keep on revving their number, and the private part can stay constant. So we'd have a private `TheTrueBuildEngineInterface` which would extend two other interfaces: `IBuildEngine{number}`, the public bit of the API and `IPrivateBuildEngine`, the private part. On the other hand this gets way less messy if we had the final abstract class to end all versioned interfaces. The abstract class can have both public and private abstract methods. You could make this PR wait for the abstract class, or go ahead with IBE8, or do the public/private split. I think the public/private split is a bit ugly, I'd rather have a public API than yet another tiny wtf in the code :)

Comment (Forgind) [reply src/Framework/IBuildEngine8.cs]: I'm not sure I understand the value of the private part of the public/private split interfaces? I do like the final abstract class plan, but marcpopMSFT suggested we should wait for rainersigwald before making that kind of decision, so I shelved my planned implementation of that for now.

**Review by jeffkl — APPROVED** [review]
Looks good

File: src/Framework/IBuildEngine8.cs (hunk 4 above)
Comment (cdmihai) [reply src/Framework/IBuildEngine8.cs]: > I'm not sure I understand the value of the private part of the public/private split interfaces

I was assuming it somehow prevents fixing `TaskLoggingHelper.HasLoggedErrors` to return true when logging warnings-as-errors, but it turns out it's not needed. Why do tasks require a new API in addition to the existing `TaskLoggingHelper.HasLoggedErrors`? In order to allow them to inhibit logging a warning if turns out to be an error? That does not sound like safe behaviour :)

Comment (Forgind) [reply src/Framework/IBuildEngine8.cs]: Ah, I see, and you're right. I got so focused on the solution that I forgot about the motivating problem. That sounds reasonable to me, though—@BenVillalobos, could this interface be internal? Maybe have IBuildEngine7 extend WarningsAsErrorsBuildEngine?

File: src/Build/BackEnd/Components/Logging/LoggingService.cs (hunk 9 above)
Comment (BenVillalobos) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:535]: I've changed WarningsAsErrors to generally be of type ICollection, but returning an empty array would change the implementation of warnings as errors. If we want to do that, we should do it in another PR.

File: src/Framework/IBuildEngine8.cs (hunk 4 above)
Comment (BenVillalobos) [reply src/Framework/IBuildEngine8.cs]: > I think the public/private split is a bit ugly, I'd rather have a public API than yet another tiny wtf in the code :)

This is where I'm at with IBuildEngine. IMO we take one more "this is the way we've done it" IBE PR and stop at IBE9 when we implement the abstract class. Otherwise why would we extend private IBE interfaces after we add the abstract class?

It sounds like it would be even messier to have a single private IBE8, all previous IBE's are public, then we make the abstract class and have no use for private IBE's.

**Comment by BenVillalobos** [comment]
@KirillOsenkov (and any other reviewers familiar with the binary formatter) Requesting a specific pass over my last four commits. Having WarningsAsErrors be an ICollection required adding an overload to the ITranslator interface and I'd like to be sure that the way I did it is okay. I mostly looked at how it was done with an IList and went with it. Looks good to me and it passes tests but I'd like to be sure.

**Comment by Forgind** [comment]
Looks good to me.

File: src/Framework/IBuildEngine8.cs (hunk 4 above)
Comment (cdmihai) [reply src/Framework/IBuildEngine8.cs]: Mkay, took another look at the code. So TaskLoggingHelper gets an `IBuildEngine`, and that's how it interacts with the `TaskHost:IBuildEngine{N}` which knows about warnings-as-errors from its TaskLoggingContext. Beyond keeping it public, any solution I can think of is pretty messy. So public it is then :)

File: src/Framework/IBuildEngine8.cs [hunk 14]
```diff
@@ -0,0 +1,22 @@
...
+    /// </summary>
+    public interface IBuildEngine8 : IBuildEngine7
+    {
+        /// <summary>
+        /// Determines whether the logging service will convert the specified
+        /// warning code into an error.
+        /// </summary>
+        /// <param name="warningCode">The warning code to check.</param>
+        /// <returns>A boolean to determine whether the warning should be treated as an error.</returns>
+        public bool ShouldTreatWarningAsError(string warningCode);
```
Comment (KirillOsenkov) [inline src/Framework/IBuildEngine8.cs:20]: the `public` keyword is redundant here, the general convention is to avoid modifiers on interface members

**Review by KirillOsenkov — APPROVED** [review]
👍

File: src/Build.UnitTests/BackEnd/CustomLogAndReturnTask.cs [hunk 15]
```diff
@@ -0,0 +1,39 @@
...
+    public class CustomLogAndReturnTask : Task
+    {
+        public string WarningCode { get; set; }
+
+        public string ErrorCode { get; set; }
+
+        public bool ReturnHasLoggedErrors { get; set; }
+
+        [Required]
+        public bool Return { get; set; }
```
Comment (Forgind) [inline src/Build.UnitTests/BackEnd/CustomLogAndReturnTask.cs:17]: It looks like these are always true?

File: src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs [hunk 16]
```diff
@@ -676,6 +676,38 @@ public void LogTelemetry(string eventName, IDictionary<string, string> propertie
...
+                    return null;
+                }
+
+                return _warningsAsErrors ??= _taskLoggingContext.GetWarningsAsErrors();
+            }
+        }
+
+        public bool ShouldTreatWarningAsError(string warningCode)
+        {
+            if (_taskLoggingContext == null || WarningsAsErrors == null)
```
Comment (Forgind) [inline src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs:702]: nit:
```suggestion
            if (WarningsAsErrors == null)
```

(Should be the same but looks a little cleaner to me.)

File: src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs [hunk 17]
```diff
@@ -676,6 +676,38 @@ public void LogTelemetry(string eventName, IDictionary<string, string> propertie
...
+            {
+                return false;
+            }
+
+            return WarningsAsErrors.Count == 0 || WarningsAsErrors.Contains(warningCode);
```
Comment (Forgind) [inline src/Build/BackEnd/Components/RequestBuilder/TaskHost.cs:707]: Comment?
