### PR TITLE
Fix of OutOfMemoryException when embedding large amount of files to binlog

### LINKED ISSUE #8595: [Bug]: msbuild binary logger generating excessive memory spike at end of build
### Issue Description

When running `msbuild /t:restore /bl` on a large repo we are running out of memory at the end of the build on a 64GB machine. We see a large spike in memory after the console output shows the build as complete, before the process terminates with an out of memory exception.

This is a regression for as we started seeing this behavior in 17.6 preview, but we did not see this behavior in VS 17.5.

### Steps to Reproduce

We have a large repo.

### Expected Behavior

Expect that we can complete restore build with less than 64GB of memory, we do not see a memory spike with VS 17.5.

MSBuild version 17.5.1+f6fdcf537 for .NET Framework
Memory2

### Actual Behavior

We are seeing a huge 30GB memory spike after the build completes and an out of memory exception.

MSBuild version 17.6.0-preview-23164-01+18fe51042 for .NET Framework

Memory1

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:09:43.47
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Throwing from logger shutdown
=============
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent()
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()

 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent()
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()
   at Microsoft.Build.Evaluation.ProjectCollection.Dispose(Boolean disposing)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache, String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Throwing from logger shutdown
=============
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent()
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()

 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent()
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()
   at Microsoft.Build.Evaluation.ProjectCollection.Dispose(Boolean disposing)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache, String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

### Analysis

Passing the additional parameter `/bl:ProjectImports=None` is a workaround for the issue, but not ideal as we prefer to collect complete binlogs from our build agents.

### Versions & Configurations

MSBuild version 17.6.0-preview-23164-01+18fe51042 for .NET Framework
17.6.0.16401

### PR DESCRIPTION
**Pull request by MichalPavlik**
Fixes #8595

### Summary

Embedding of large amount of files to binlog can lead to OutOfMemoryException due to memory pressure. It also causes LOH fragmentation and Gen2 collections. 

### Customer Impact

Large builds cannot use the binary logger due to an OOM crash.

### Regression?

Yes, in 16.8 (#5718).

### Testing

Before:
Screenshot 2023-06-28 102953

After:
Screenshot 2023-06-29 102337

### Risk

Medium--adds new filesystem dependencies which could fail, but is similar to the pre-16.8 mechanism and tries to be tolerant of failures.

### Changes Made
This change reverts in-memory operations and uses temp file for embedded files. The file is now stored in temporary directory (instead of binlog target directory) to avoid problems with file watchers. There might be possible another optimizations, but goal of this PR is to unblock our partners. We can optimize further in separate PR.

### CODE REVIEW

**Comment by MichalPavlik** [comment]
Well, I missed somehow some failed tests on my local machine (presence of asset file in old location, etc. So I will add at least one more commit, but the functionality is ready for review.

File: src/Build/Logging/BinaryLogger/BinaryLogger.cs [hunk 1]
```diff
@@ -226,12 +227,21 @@ public void Shutdown()
...
                 if (CollectProjectImports == ProjectImportsCollectionMode.Embed)
                 {
-                    eventArgsWriter.WriteBlob(BinaryLogRecordKind.ProjectImportArchive, projectImportsCollector.GetAllBytes());
+                    var archiveFilePath = projectImportsCollector.ArchiveFilePath;
+
+                    // It is possible that the archive couldn't be created for some reason.
+                    // Only embed it if it actually exists.
+                    if (FileSystems.Default.FileExists(archiveFilePath))
+                    {
+                        eventArgsWriter.WriteBlob(BinaryLogRecordKind.ProjectImportArchive, File.ReadAllBytes(archiveFilePath));
```
Comment (rainersigwald) [inline src/Build/Logging/BinaryLogger/BinaryLogger.cs:240]: I'm worried that this `ReadAllBytes` will still cause a big memory spike. Can we stream it from the disk into the log stream instead?

File: src/MSBuild.UnitTests/XMake_Tests.cs [hunk 2]
```diff
@@ -2328,7 +2328,7 @@ public void BinaryLogContainsImportedFiles()
             </Project>
             ");
 
-            string binLogLocation = _env.DefaultTestDirectory.Path;
+            string binLogLocation = FileUtilities.TempFileDirectory;
```
Comment (rainersigwald) [inline src/MSBuild.UnitTests/XMake_Tests.cs:2331]: This is a change I don't expect, what's the motivation?

Comment (MichalPavlik) [reply src/MSBuild.UnitTests/XMake_Tests.cs:2331]: The test was failing, because archive file wasn't found on that location. We agreed that we will change the archive location to not interfere with the file watchers (which was motivation of keeping data in memory).

File: src/Build/Logging/BinaryLogger/BinaryLogger.cs (hunk 1 above)
Comment (MichalPavlik) [reply src/Build/Logging/BinaryLogger/BinaryLogger.cs]: Sure. I wanted to do this with more changes, but with proper planning - get rid of the temporary file completely by writing zip stream directly to binlog stream and using single reusable copy buffer for all files.
But removing `ReadAllBytes` required less changes than I expected and the result is pretty good :) I updated profiler result.

Comment (rainersigwald) [reply src/Build/Logging/BinaryLogger/BinaryLogger.cs]: > I updated profiler result.

Oh yeah, that looks beautiful now.

File: src/MSBuild.UnitTests/XMake_Tests.cs (hunk 2 above)
Comment (rainersigwald) [reply src/MSBuild.UnitTests/XMake_Tests.cs:2331]: Ah, thanks! I think this is actually a bug in the new implementation.

When in `ProjectImports=ZipFile` mode, we expect *two* output files:

1. the binlog itself, with no embedded  content files
2. a zip with the extension `.ProjectImports.zip` with the content files

We want that zip to be next to the .binlog _when it is an output of the build_. But when it's an internal implementation detail to avoid memory, we want it somewhere else. Looks like the current code moves it unconditionally, which isn't right.

I see two options:

1. tweak the location based on mode (the old `createFile` argument to the `ProjectImportsCollector` ctor)
2. _move_ the file to the final location instead of deleting it, based on mode

I prefer the former.

File: src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs [hunk 3]
```diff
@@ -53,35 +34,34 @@ public byte[] GetAllBytes()
         // this will form a chain of file write tasks, running sequentially on a background thread
         private Task _currentTask = Task.CompletedTask;
 
-        public ProjectImportsCollector(string logFilePath, bool createFile, string sourcesArchiveExtension = ".ProjectImports.zip")
+        public ProjectImportsCollector(string logFilePath, string sourcesArchiveExtension = ".ProjectImports.zip")
         {
+            // Archive file is stored in MSBuild temp folder with same name as binlog, but with different extension
+            ArchiveFilePath = Path.Combine(
+                FileUtilities.TempFileDirectory,
```
Comment (rainersigwald) [inline src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs:41]: We have a specific method to find the folder to store files just like this that are used to relieve memory pressure (build requests and configurations, today).

```suggestion
                FileUtilities.GetCacheDirectory(),
```

(if you peek behind the scenes that's like one subdirectory deep in TEMP, and disambiguates by PID which is important in case someone builds twice concurrently.)

**Review by rainersigwald — APPROVED** [review]
Looks great! Please retarget to the `vs17.7` branch.

File: src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs [hunk 4]
```diff
@@ -55,33 +36,46 @@ public byte[] GetAllBytes()
...
+                if (!Directory.Exists(cacheDirectory))
                 {
-                    _stream = new MemoryStream();
+                    Directory.CreateDirectory(cacheDirectory);
                 }
-                _zipArchive = new ZipArchive(_stream, ZipArchiveMode.Create, true);
+
+                // Archive file will be temporarily stored in MSBuild cache folder and deleted when no longer needed
+                ArchiveFilePath = Path.Combine(
+                    cacheDirectory,
```
Comment (danmoseley) [inline src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs:54]: This folder is one that is already secured to the current user on Unix?

Comment (rainersigwald) [reply src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs:54]: Yes, it's defined as

https://github.com/dotnet/msbuild/blob/39e20dce0c00a572f1fbd20a0a520d4e941bbc33/src/Shared/FileUtilities.cs#L131

calling our hardened

https://github.com/dotnet/msbuild/blob/39e20dce0c00a572f1fbd20a0a520d4e941bbc33/src/Shared/TempFileUtilities.cs#L37-L68

**Review by KirillOsenkov — APPROVED** [review]

File: eng/Versions.props [hunk 5]
```diff
@@ -2,7 +2,8 @@
 <!-- Copyright (c) .NET Foundation and contributors. All rights reserved. Licensed under the MIT license. See License.txt in the project root for full license information. -->
 <Project>
   <PropertyGroup>
-    <VersionPrefix>17.7.0</VersionPrefix><DotNetFinalVersionKind>release</DotNetFinalVersionKind>
+    <VersionPrefix>17.7.0</VersionPrefix>
```
Comment (Forgind) [inline eng/Versions.props:5]: This looks wrong, both because you need to update the version prefix and because we generally put these two on the same line to force a merge conflict when flowing final version commits to main.

File: src/Build/Logging/BinaryLogger/BinaryLogger.cs [hunk 6]
```diff
@@ -226,12 +227,25 @@ public void Shutdown()
 
             if (projectImportsCollector != null)
             {
+                projectImportsCollector.Close();
```
Comment (Forgind) [inline src/Build/Logging/BinaryLogger/BinaryLogger.cs:230]: Why does this have to be up here instead of where it was before?

Comment (KirillOsenkov) [reply src/Build/Logging/BinaryLogger/BinaryLogger.cs:230]: So that we first flush the remaining archive bits to disk in the temp folder and close the file, so that we can read it later.

File: eng/Versions.props (hunk 5 above)
Comment (rainersigwald) [reply eng/Versions.props:5]: This doesn't matter for this PR because we'll be handling merging to the release branch specially since we have several things to bring.

**Review by JanKrivanek — APPROVED** [review]
Looks good!

Did you perfomr any measurments how this impacts build speed with binlog for small and mid-size projects? (I'd say `dotnet new console`, `dotnet new mvc` and OrchardCore can possibly be seen as representative samples)

If there is any measurable difference we should probably plan followup item where we optimize the approach to keep in-memory stream for sane projects. A sample of very primitive StreamProxy that dynamically uses either memory or fallbacks to file based on the size can be found here: https://github.com/dotnet/templating/blob/main/src/Microsoft.TemplateEngine.Core/Util/StreamProxy.cs

**Comment by MichalPavlik** [comment]
I expressed my concerns regarding to perf regression caused by switching back to tremp file, but Kirill measured it and...

> I measured perf before and after and writing to a memory stream wasn't noticeably better than the temp file. I expect the vast majority of usages will be just fine with writing the embedded files stream to a temp file.

We can do measurements, but I would say that most devs are not collecting binlog by default (during development). Binlogs are collected on dev machines usually when you want to diagnose some issue.

File: eng/Versions.props (hunk 5 above)
Comment (JanKrivanek) [reply eng/Versions.props:5]: I'd suggest to completely remove change to this file from this PR - in order to have a clean merge of all the in-flight 17.7 PRs (Rainer was contemplating single octopus merge of all 17.7 PRs)

**Comment by KirillOsenkov** [comment]
Curious how did we miss https://github.com/dotnet/msbuild/pull/9057?

Were the corrupt binlogs easy to repro? Are we missing a test? Did manual testing all look OK?

**Comment by rainersigwald** [comment]
They are easy to repro but the viewer is pretty tolerant of the problem; it loads without visible error and is just missing the embeds. I think I might have seen a log that was mysteriously missing embeds but I didn't connect it with this and I went back and forth between builds that did and didn't have the bug enough that I didn't see it coming.

We definitely need better regression testing around this scenario, which is high on the list after figuring out how to get the fix out.

**Comment by KirillOsenkov** [comment]
Hmm, I've been thinking about surfacing first-chance exceptions in the viewer and flash some sort of user-visible warning, like a goldbar. This would have caught this.

**Comment by KirillOsenkov** [comment]
I suppose it doesn't help that the embeds archive is the last record in the file, so even if the stream is now corrupted and dis-synchronized the rest of the binlog is already read

**Comment by MichalPavlik** [comment]
I'm focusing on the serialization problem and I will add test at least for the length of the payload. I believe I tried open binlogs in viewer and everything looked OK. Warning in binlog viewer would be nice feature.

**Comment by Forgind** [comment]
> Hmm, I've been thinking about surfacing first-chance exceptions in the viewer and flash some sort of user-visible warning, like a goldbar. This would have caught this.

I think a user-visible warning like this is great from the developer's (i.e., our) perspective but detrimental from a user's perspective. Most users won't know why it's flashing unless they intentionally look for an error afterwards, and even if they do, they probably won't know how to or have the inclination to fix it. I think this sort of things is great in a beta product to help get fast feedback but not ideal in a product as established as the binlog viewer, as most users at this point probably just want to finish their work and don't care if the viewer is broken unless it makes it harder for them to do so.
