### PR TITLE
[BuildCheck] Limit number of emitted messages per rule.

### LINKED ISSUE #10414: [Bug] [BuildCheck]: rebuild with the build-in analyzers hangs
### Issue Description

Rebuild of OC solution with build-in analyzers hangs during clean-up.

### Steps to Reproduce

1. Build the latest MSBuild main with release configuration `.\build.cmd /p:CreateBootstrap=true -c Release`
2. Go to OC solution and rebuild with analyzers with the bootstrap version: 
```...\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\amd64\MSBuild.exe /m /t:rebuild /analyze```
3. kill MSBuild processes `pskill msbuild;`
4. rebuild with analyzers with the bootstrap version: 
```...\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\amd64\MSBuild.exe /m /t:rebuild /analyze```

### Expected Behavior

Solution builds the second time with many warnings.

### Actual Behavior

Rebuild hangs on CoreClean task execution.

### Analysis

_No response_

### Versions & Configurations

commit `01bc39f03488545f57c8b78067e863aa87da138e`

### PR DESCRIPTION
**Pull request by AR-May**
Temporary fixes #10414

### Context
If BuildCheck emits a lot of messages, it is possible that the build will hang. Since the real reason of the hang is yet unclear, we have decided to limit number of messages emitted by build-in checks.

### Changes Made
- Enhanced a wrapper class `CheckWrapper` so that we can limit number of messages per check. 
- Added unit test.

### Testing
unit tests + manual testing

### CODE REVIEW

**Comment by JanKrivanek** [comment]
Let's simplify this - as diuscused, the limit should be very easily addable to `BuildEventsProcessor` - something like:

https://github.com/dotnet/msbuild/compare/main...JanKrivanek-patch-8

File: src/Build/BuildCheck/Infrastructure/CheckWrapper.cs [hunk 1]
```diff
@@ -52,10 +75,37 @@ internal void StartNewProject(
         }
     }
 
+    internal void ReportResult(BuildCheckResult result, ICheckContext checkContext, CheckConfigurationEffective config)
+    {
+        if (_reportsCountPerRule is not null)
+        {
```
Comment (JanKrivanek) [inline src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:81]: Let's limit the number of access to the dictionary.

```
if (!_reportsCountPerRule.TryGetValue(result.CheckRule.Id, out int currentCount))
{
    currentCount = 0;
}

if(currentCount >= MaxReportsNumberPerRule )
{
   return;
}

if(currentCount++ >= MaxReportsNumberPerRule )
{
   // ... Log and dismount
}

// ...

_reportsCountPerRule[result.CheckRule.Id] = currentCount;
```

File: src/Build/BuildCheck/Infrastructure/CheckWrapper.cs [hunk 2]
```diff
@@ -52,10 +75,37 @@ internal void StartNewProject(
...
+            if (!_reportsCountPerRule.ContainsKey(result.CheckRule.Id))
+            {
+                _reportsCountPerRule[result.CheckRule.Id] = 0;
+            }
+            _reportsCountPerRule[result.CheckRule.Id]++;
+
+            if (_reportsCountPerRule[result.CheckRule.Id] == MaxReportsNumberPerRule + 1)
+            {
+                checkContext.DispatchAsCommentFromText(MessageImportance.Normal, $"The check '{Check.FriendlyName}' has exceeded the maximum number of results allowed for the rule '{result.CheckRule.Id}'. Any additional results will not be displayed.");
```
Comment (JanKrivanek) [inline src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:90]: Let's have the message localizable and let's append it to the result.

Otherwise it can get lost (e.g. when users have terminal logger - which is default)

Comment (JanKrivanek) [reply src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:90]: Plus let's dismount the check - so that it doesn't receive and operate on other data (it's fine to dismount even if the check has multiple rules)

Comment (AR-May) [reply src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:90]: You mean to append the message to the latest result that has been shown? I can do that, albeit it would not look very nice in code I am afraid. 

As for localization I suggest given that this will be appended to the latest build check result and they are not localized, not to localize it as well. Otherwise, it would look strange: part of the message is localized, part is not.

File: src/Build/BuildCheck/Infrastructure/CheckWrapper.cs (hunk 1 above)
Comment (AR-May) [reply src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:81]: I can indeed limit accesses to the dictionary. If we want to dismount the check, we will need to limit the number of messages per check rather than per rule. Alternatively, we can have a more detailed check that all the rules reached the report limit and can produce no valuable info, which would be seldom case, and I think not worth code complication.

File: src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs [hunk 3]
```diff
@@ -588,6 +588,7 @@ public CheckWrapper Initialize(Check ba, ConfigurationContext configContext)
                     throw new BuildCheckConfigurationException(
                         $"The Check '{ba.FriendlyName}' failed to initialize: {e.Message}", e);
                 }
+
```
Comment (JanKrivanek) [inline src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs:591]: nit: feels unnecessary

File: src/Build/BuildCheck/Infrastructure/CheckWrapper.cs [hunk 4]
```diff
@@ -52,10 +68,33 @@ internal void StartNewProject(
...
+            {
+                return;
+            }
+
+            if (_reportsCount == MaxReportsNumberPerRule)
+            {
+                checkContext.DispatchAsCommentFromText(MessageImportance.Normal, $"The check '{Check.FriendlyName}' has exceeded the maximum number of results allowed. Any additional results will not be displayed.");
+                _reportsCount++;
+                return;
+            }
```
Comment (JanKrivanek) [inline src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:85]: Let's detect on the last diagnostic we want to emit (so MaxReportsNumberPerRule - 1) - so that the created report is not created unnecessary.
This applies once the dismounting is added (so basically - detect this is last wanted report - report it, report the note that the check will be dismounted and dismount the check)

**Review by JanKrivanek — COMMENTED** [review]
This looks great!
Thanks!

The only thing holding me off the signoff is calling the dismounting

File: src/Build/BuildCheck/Infrastructure/CheckWrapper.cs (hunk 4 above)
Comment (AR-May) [reply src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:85]: I thought about it, but I decided that not writing this message when it is not needed (for example when we have exactly 20 messages) is also a possible good behavior. Without counting dismounting of the check it is better. If we implement dismounting, we will indeed write it before dismount which is better to do during the last message exactly as you stated.

File: src/Build/BuildCheck/Infrastructure/BuildCheckCentralContext.cs [hunk 5]
```diff
@@ -46,6 +49,7 @@ internal void DeregisterCheck(CheckWrapper check)
 
     // In a future we can have callbacks per project as well
     private readonly CallbackRegistry _globalCallbacks = new();
+    private Action<ICheckContext> _removeThrottledChecks;
```
Comment (JanKrivanek) [inline src/Build/BuildCheck/Infrastructure/BuildCheckCentralContext.cs:52]: nit: this can be readonly

File: src/Build/BuildCheck/Infrastructure/CheckWrapper.cs [hunk 6]
```diff
@@ -17,13 +18,34 @@ internal sealed class CheckWrapper
...
+
+    /// <summary>
+    /// Keeps track of number of reports sent per rule.
+    /// </summary>
+    private int _reportsCount = 0;
+
+    /// <summary>
+    /// Flags that this check should no more used and be deregistered.
+    /// </summary>
+    public bool IsThrottled = false;
```
Comment (JanKrivanek) [inline src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:34]:
```suggestion
    public bool IsThrottled { get; private set; } = false;
```

This should rather be autoproperty.
Fields should not be exposed.

File: src/Build/BuildCheck/Infrastructure/CheckWrapper.cs [hunk 7]
```diff
@@ -52,10 +74,27 @@ internal void StartNewProject(
...
 
+    internal void ReportResult(BuildCheckResult result, ICheckContext checkContext, CheckConfigurationEffective config)
+    {
+        if (_limitReportsNumber)
+        {
+            if (_reportsCount >= MaxReportsNumberPerRule)
+            {
+                IsThrottled = true;
+                return;
+            }
```
Comment (JanKrivanek) [inline src/Build/BuildCheck/Infrastructure/CheckWrapper.cs:85]: Let's move this check after the reporting (whit count decreased by 1) - so that we do not have an unneeded report being created and then thrown away.
After the last report we already know the check will be dismounted - we do not have to wait till the other to do that

**Review by JanKrivanek — APPROVED** [review]
This looks great!

I have couple small comments.
The one thing that I'd realy want to see changed before merging - is the dismounting of the check right after the last report that fits into the count.

File: src/Build/BuildCheck/Infrastructure/CheckWrapper.cs (hunk 7 above)
Comment (JanKrivanek) [reply src/Build/BuildCheck/Infrastructure/CheckWrapper.cs]: Thanks for fixing!
