### PR TITLE
Fix stackoverflowexception

### LINKED ISSUE #6925: Crashes due to infinite recursion in Microsoft.Build.Graph.GraphBuilder.AddEdgesFromProjectReferenceItems
### Issue Description

`msbuild -graph -isolate` crashes with a `StackOverflowException`. With a debugger I was able to determine the recursive callstack was within Microsoft.Build.dll.

### Steps to Reproduce

```
git clone https://github.com/AArnott/Library.Template.git
cd Library.Template
git checkout 0b96cc61dea012d86c7bf933aa5830ce35ea22db
dotnet restore
dotnet restore VersionGeneration
msbuild .\src\Library\ -bl -graph -isolate
```

### Expected Behavior

No crash. Similar behavior across quickbuild and `msbuild -graph -isolate`.

### Actual Behavior

```
quickbuild -notest -EnableMsBuildBinLogTracing -eucu -parseroot .\src\Library\
INFO  QuickBuild Version: d0175a7bbe9050197571c4ccffeb998396c001a0
Log file: C:\git\Lib.Template\QuickBuild.log ; Additional log directory: C:\git\Lib.Template\QLogs
INFO  Restoring packages from... .\src\Library\Library.csproj
INFO  Successfully restored packages in 1.45 sec
INFO  Parsing build files...

Process is terminated due to StackOverflowException.
```

The crashing callstack is:

```
[0x0]   clr!COMNlsHashProvider::HashiStringKnownLower80 + 0x40   
[0x1]   clr!COMNlsInfo::InternalGetCaseInsHash + 0xc9   
[0x2]   mscorlib_ni!System.Globalization.TextInfo.GetCaseInsensitiveHashCode(System.String, Boolean, Int64) + 0x42   
[0x3]   mscorlib_ni!System.OrdinalComparer.GetHashCode(System.String) + 0x31   
[0x4]   Microsoft_Build_20a5a280000!Microsoft.Build.BackEnd.ConfigurationMetadata.GetHashCode() + 0x24   
[0x5]   mscorlib_ni!System.Collections.Generic.GenericEqualityComparer`1[[System.Int32, mscorlib]].GetHashCode(Int32) + 0x12b87   
[0x6]   mscorlib_ni!System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].FindEntry(System.__Canon) + 0xffffffffa2978596   
[0x7]   mscorlib_ni!System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].get_Item(System.__Canon) + 0xffffffffa295b1d8   
[0x8]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x13a   
[0x9]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
[0xa]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
[0xb]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
[0xc]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
[0xd]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
[0xe]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
[0xf]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
[0x10]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
[0x11]   Microsoft_Build_20a5a280000!Microsoft.Build.Graph.GraphBuilder.<AddEdgesFromProjectReferenceItems>g__GetTransitiveProjectReferencesExcludingSelf|28_0(Microsoft.Build.Graph.ParsedProject, <>c__DisplayClass28_0 ByRef) + 0x189   
```

### Analysis

It happens while walking P2P edges. This repro only has 2 projects with a P2P between them.

This happened while developing Nerdbank.GitVersioning so that it works in quickbuild, so I may have a bug in how I generate the P2P and would be happy to learn what I was doing wrong. But in any case I think msbuild is supposed to detect and report errors for invalid graphs rather than crash.

### Versions & Configurations

```
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.11.1.47101
```

```
QuickBuild Version: d0175a7bbe9050197571c4ccffeb998396c001a0
```

### Attach a binlog

🗑️  [binlog and dump file](https://microsoft-my.sharepoint.com/:u:/p/andarno/EXl4Nv-cyv9BsEwLou7tKOIBIgQqsmYpLYNAKnnZ5YBj4w?e=nTtOYR).

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #6925

### Context
If you have a cycle in your ProjectReferences, that should be caught and marked as invalid with MSB4251. If you do a graph build, however, it turns into a StackOverflowException, which is much less clear. This handles circular dependencies, giving the nicer exception.

### Changes Made
Ensures that each project "marks" itself as not to be revisited before the recursive call so that you cannot get endless recursion.

### Testing
Tried with the original repro and got MSB4251 as desired.

### Notes
The first commit maintains the previous caching behavior. It isn't obvious to me how much benefit there really is here, and I have yet to test it. In particular, although it could save you a good bit of work, it costs creation and manipulation of a series of intermediate HashSets that are all stored in a Dictionary, so GC can't even get rid of any of them. Without having tested this, I would guess that the first commit would be more efficient for large projects, and the second commit would be more efficient for small projects. I'm happy to hear feedback before I test or just test that hypothesis as reviewers think best.

### CODE REVIEW

File: src/Build/Graph/GraphBuilder.cs [hunk 1]
```diff
@@ -162,27 +160,20 @@ private void AddEdgesFromProjectReferenceItems(Dictionary<ConfigurationMetadata,
...
+            }
 
-                    foreach (var referenceInfo in parsedProject.ReferenceInfos)
+            void GetTransitiveProjectReferencesExcludingSelfHelper(ParsedProject parsedProject, HashSet<ProjectGraphNode> transitiveReferences)
+            {
+                foreach (ProjectInterpretation.ReferenceInfo referenceInfo in parsedProject.ReferenceInfos)
+                {
+                    if (!transitiveReferences.Contains(allParsedProjects[referenceInfo.ReferenceConfiguration].GraphNode))
                     {
                         transitiveReferences.Add(allParsedProjects[referenceInfo.ReferenceConfiguration].GraphNode);
```
Comment (Therzok) [inline src/Build/Graph/GraphBuilder.cs:174]: You can combine both add and contains into one call, by checking the return value on Add. Avoids a hash ode computation and lookupm

**Comment by Forgind** [comment]
NTS: Add tests

**Comment by Forgind** [comment]
From my testing, it seems like it's about 4% faster without caching for a very simple app (a console with a ProjectReference to a classlib). It's about 5% fasting with caching for OrchardCore. That sounds like the cache is doing surprisingly little, but it might make sense given how many wasted intermediate objects it needs. That said, OrchardCore is the more relevant scenario here, so I think we should keep the cache. I updated the code accordingly. Haven't added tests yet.

File: src/Build/Graph/GraphBuilder.cs [hunk 2]
```diff
@@ -161,28 +161,42 @@ private void AddEdgesFromProjectReferenceItems(Dictionary<ConfigurationMetadata,
...
+                GetTransitiveProjectReferencesExcludingSelfHelper(parsedProject, references, null);
+                return references;
+            }
+
+            void GetTransitiveProjectReferencesExcludingSelfHelper(ParsedProject parsedProject, HashSet<ProjectGraphNode> transitiveReferences, HashSet<ProjectGraphNode> referencesFromHere)
             {
                 if (transitiveReferenceCache.TryGetValue(parsedProject.GraphNode, out HashSet<ProjectGraphNode> cachedTransitiveReferences))
                 {
-                    return cachedTransitiveReferences;
+                    transitiveReferences = transitiveReferences.Concat(cachedTransitiveReferences).ToHashSet();
```
Comment (rainersigwald) [inline src/Build/Graph/GraphBuilder.cs:174]:
```suggestion
                    transitiveReferences.UnionWith(cachedTransitiveReferences);
```

?

File: src/Build/Graph/GraphBuilder.cs [hunk 3]
```diff
@@ -161,28 +161,42 @@ private void AddEdgesFromProjectReferenceItems(Dictionary<ConfigurationMetadata,
             }
 
             HashSet<ProjectGraphNode> GetTransitiveProjectReferencesExcludingSelf(ParsedProject parsedProject)
+            {
+                HashSet<ProjectGraphNode> references = new();
+                GetTransitiveProjectReferencesExcludingSelfHelper(parsedProject, references, null);
+                return references;
+            }
+
+            void GetTransitiveProjectReferencesExcludingSelfHelper(ParsedProject parsedProject, HashSet<ProjectGraphNode> transitiveReferences, HashSet<ProjectGraphNode> referencesFromHere)
```
Comment (rainersigwald) [inline src/Build/Graph/GraphBuilder.cs:170]: I don't think I understand what `referencesFromHere` does. Is there another name? Below you call it with `toCache`.

**Review by rainersigwald — COMMENTED** [review]
Where does the actual throw happen?

File: src/Build/Graph/GraphBuilder.cs (hunk 3 above)
Comment (Forgind) [reply src/Build/Graph/GraphBuilder.cs:170]: I'm open to better names.

transitiveReferences holds all references we have found so far.
toCache stores all references (including transitive references) from the project (parsedProject) being considered in one particular recursive call.
referencesFromHere is like toCache but from the parent project.

Let's say project A references project B and project C. Project B references project D, and D references E.
When B is "parsedProject," referencesFromHere contains all of A's references, so it either does (if C were first) or will (if B comes first) contain C, but C is not part of B's transitive reference tree, hence toCache. toCache, at line 183, is passed as referencesFromHere to the recursive call for project D. D will add both its references (through passing toCache in line 183 (transitive references) and adding direct references directly on line 189. At this point, toCache holds all of D's references exluding itself, so we add it to transitiveReferenceCache.

At that point, B's toCache (passed to D as referencesFromHere) has nothing. D's recursive call adds E to it on 195 by adding its own references. Then, in B's recursive call, it adds D on 189. Now it has all of its (direct and indirect) references.

Does that make sense? Recursion can be very confusing (and having a bug didn't help).

**Comment by Forgind** [comment]
> Where does the actual throw happen?

The CircularDependencyException? That comes from the DetectCycles method—not modified in this PR. This is about preventing a Really Bad exception, letting it go through to the correct one.

File: src/Build/Graph/GraphBuilder.cs [hunk 4]
```diff
@@ -161,28 +161,47 @@ private void AddEdgesFromProjectReferenceItems(Dictionary<ConfigurationMetadata,
...
             HashSet<ProjectGraphNode> GetTransitiveProjectReferencesExcludingSelf(ParsedProject parsedProject)
+            {
+                HashSet<ProjectGraphNode> references = new();
+                GetTransitiveProjectReferencesExcludingSelfHelper(parsedProject, references, null);
+                return references;
+            }
+
+            // transitiveReferences contains all of the references we've found so far from the initial GetTransitiveProjectReferencesExcludingSelf call.
+            // referencesFromHere is essentially "reset" at each level of the recursion.
+            // The first is important because if we find a cycle at some point, we need to know not to keep recursing. We wouldn't have added to a cache yet, since we haven't finished
```
Comment (rainersigwald) [inline src/Build/Graph/GraphBuilder.cs:172]:
```suggestion
            // The first is important because if we find a cycle at some point, we need to know not to keep recursing. We wouldn't have added to transitiveReferenceCache yet, since we haven't finished
```

File: src/Build/Graph/GraphBuilder.cs (hunk 3 above)
Comment (rainersigwald) [reply src/Build/Graph/GraphBuilder.cs:178]:
```suggestion
            void GetTransitiveProjectReferencesExcludingSelfHelper(ParsedProject parsedProject, HashSet<ProjectGraphNode> traversedReferences, HashSet<ProjectGraphNode> referencesOfReferencingNode)
```

?

File: src/Build/Graph/GraphBuilder.cs [hunk 5]
```diff
@@ -161,28 +161,47 @@ private void AddEdgesFromProjectReferenceItems(Dictionary<ConfigurationMetadata,
...
+                        toCache.Add(allParsedProjects[referenceInfo.ReferenceConfiguration].GraphNode);
                     }
 
-                    transitiveReferenceCache.Add(parsedProject.GraphNode, transitiveReferences);
-
-                    return transitiveReferences;
+                    transitiveReferenceCache[parsedProject.GraphNode] = toCache;
+                    if (referencesFromHere is not null)
+                    {
+                        referencesFromHere.UnionWith(toCache);
```
Comment (rainersigwald) [inline src/Build/Graph/GraphBuilder.cs:203]: Are these accurate?

```suggestion
                    // We've returned from recursing through all transitive references
                    // of this node, so add that set to the cache
                    transitiveReferenceCache[parsedProject.GraphNode] = toCache;
                    if (referencesFromHere is not null)
                    {
                        // Also add it to the set of transitive dependencies of
                        // the referencing node (which may still be incomplete)
                        referencesFromHere.UnionWith(toCache);
```

File: src/Build/Graph/GraphBuilder.cs [hunk 6]
```diff
@@ -161,28 +161,47 @@ private void AddEdgesFromProjectReferenceItems(Dictionary<ConfigurationMetadata,
...
                 {
-                    return cachedTransitiveReferences;
+                    transitiveReferences.UnionWith(cachedTransitiveReferences);
                 }
                 else
                 {
-                    var transitiveReferences = new HashSet<ProjectGraphNode>();
-
-                    foreach (var referenceInfo in parsedProject.ReferenceInfos)
+                    HashSet<ProjectGraphNode> toCache = new();
```
Comment (rainersigwald) [inline src/Build/Graph/GraphBuilder.cs:186]:
```suggestion
                    HashSet<ProjectGraphNode> referencesFromThisNode = new();
```

**Review by rainersigwald — COMMENTED** [review]
That comment helped a lot, thanks! A few questions/suggestions.

File: src/Build/Graph/GraphBuilder.cs (hunk 3 above)
Comment (Forgind) [reply src/Build/Graph/GraphBuilder.cs:178]: referencesOfDirectlyReferencingNode?

I'm a little unsure about either name because it makes it sound like something the recursive calls could use rather than something incomplete to add to.

incompleteReferencesOfDirectlyReferencingNode?

File: src/Build/Graph/GraphBuilder.cs [hunk 7]
```diff
@@ -169,38 +169,42 @@ HashSet<ProjectGraphNode> GetTransitiveProjectReferencesExcludingSelf(ParsedProj
...
+                    traversedReferences.UnionWith(cachedTransitiveReferences);
                 }
                 else
                 {
-                    HashSet<ProjectGraphNode> toCache = new();
+                    HashSet<ProjectGraphNode> referencesFromThisNode = new();
                     foreach (ProjectInterpretation.ReferenceInfo referenceInfo in parsedProject.ReferenceInfos)
                     {
-                        if (transitiveReferences.Add(allParsedProjects[referenceInfo.ReferenceConfiguration].GraphNode))
+                        if (traversedReferences.Add(allParsedProjects[referenceInfo.ReferenceConfiguration].GraphNode))
```
Comment (rainersigwald) [inline src/Build/Graph/GraphBuilder.cs:189]:
```suggestion
                        ProjectGraphNode referencedNode = allParsedProjects[referenceInfo.ReferenceConfiguration].GraphNode;
                        if (traversedReferences.Add(referencedNode ))
```

? And for the other uses here?

**Review by rainersigwald — APPROVED** [review]
