### PR TITLE
Use Microsoft.IO.Redist in XMake.cs

### LINKED ISSUE #10540: [Bug]: can't find project file in root directory
### Issue Description

When run in root directory such as `C:\`, MSBuild can't find project file

### Steps to Reproduce

1. Create project file `c:\hello.proj`
2. Change directory to `c:\`
3. Run `msbuild` 

### Expected Behavior

MSBuild runs default target in project `c:\hello.proj`

### Actual Behavior

MSBuild shows error:

> MSBUILD : error MSB1003: Specify a project or solution file. **The current working directory does not contain a project or solution file.**

### Versions & Configurations

MSBuild version 17.11.2+c078802d4 for .NET Framework
17.11.2.32701

### PR DESCRIPTION
**Pull request by rainersigwald**
This will fix #10540--it looks like M.IO.Redist has the same fix that .NET 9 has that avoids the failed root enumeration. As a bonus it's generally higher performance/less allocatey (but I don't _know_ that that has a specific positive impact in this file).

### CODE REVIEW

**Review by JanKrivanek — APPROVED** [review]

**Review by maridematte — APPROVED** [review]

**Comment by rainersigwald** [comment]
I'm going to solve the test failure in `Microsoft.Build.UnitTests.CommandLineSwitchesTests.ProcessProfileEvaluationInvalidFilename` by deleting the test. It only worked on .NET Framework, so the new behavior is parity with `dotnet msbuild`, and the functionality is rarely used.

I did, however, fix the error reporting at the end of the build to match the (better) core behavior:

```sh-session
❯ dotnet msbuild /profileevaluation:"|||" .\src\Framework\ -t:asdf   
Microsoft.Build.Framework failed with 1 error(s) (0.0s)     
Q:\src\msbuild\src\Framework\Microsoft.Build.Framework.csproj : error MSB4057: The target "asdf" does not exist in the project.
  Build failed with 1 error(s) in 0.4s
Writing profiler report to '|||'...
MSBUILD : error MSB4239: Error writing profiling report. The filename, directory name, or volume label syntax is incorrect. : 'Q:\src\msbuild\|||'.

❯ msbuild /profileevaluation:"|||" .\src\Framework\ -t:asdf 
MSBuild version 17.13.0-preview-24504-04+c4d51a11b for .NET Framework 
MSBUILD : error MSB1053: Provided filename is not valid. Illegal characters in path. Switch: |||  For switch syntax, type "MSBuild -help"  

❯ artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\amd64\MSBuild.exe /profileevaluation:"|||" .\src\Framework\ -t:asdf MSBuild version 17.12.0-dev-24507-01+71d7380fc for .NET Framework  
Q:\src\msbuild\src\Framework\Microsoft.Build.Framework.csproj : error MSB4057: The target "asdf" does not exist in the project.  Build FAILED.  
Q:\src\msbuild\src\Framework\Microsoft.Build.Framework.csproj : error MSB4057: The target "asdf" does not exist in the project.
     0 Warning(s)
     1 Error(s)
  Time Elapsed 00:00:00.93
Writing profiler report to '|||'...
MSBUILD : error MSB4239: Error writing profiling report. Illegal characters in path.
```

**Comment by rainersigwald** [comment]
A restore problem/race? https://dev.azure.com/dnceng-public/public/_build/results?buildId=830018&view=logs&j=1522e9b9-b859-5e5f-ec86-a68fc9508baf&t=411bab51-4a66-5244-5496-e7735c534dac&l=234

And a crash in tests on macOS? https://dev.azure.com/dnceng-public/public/_build/results?buildId=830018&view=logs&j=0ddb6181-8b1d-5386-35d2-ca21a772cde8&t=a36a8187-bb52-5aa3-80a2-ccc76a822779&l=330 `libc++abi: terminating due to uncaught exception of type PAL_SEHException`

Retrying for both.

**Comment by rainersigwald** [comment]
@JanKrivanek @maridematte I changed this since you reviewed, can you give it a once-over and holler if you hate it?

**Review by MichalPavlik — APPROVED** [review]

File: src/Build/Logging/ProfilerLogger.cs [hunk 1]
```diff
@@ -297,19 +297,12 @@ private void GenerateProfilerReport()
...
-            {
-                Console.WriteLine(ResourceUtilities.FormatResourceStringStripCodeAndKeyword("ErrorWritingProfilerReport", ex.Message));
-            }
-            catch (SecurityException ex)
+            catch (Exception ex) when (ex is
+                DirectoryNotFoundException or
+                IOException or
+                UnauthorizedAccessException or
+                SecurityException or
+                ArgumentException)
```
Comment (JanKrivanek) [inline src/Build/Logging/ProfilerLogger.cs:305]: ❤️
