### PR TITLE
Fix #6750 `SdkResultItem` equality

### LINKED ISSUE #6750: Unreliable equality comparisons in SdkResultItem
### Issue Description

Found some problems when reviewing the SdkResultItem.Equals and SdkResultItem.GetHashCode implementations from <https://github.com/dotnet/msbuild/pull/5269>. I don't know whether these methods can actually be called at all in normal use of the SDK.

### Equals can throw KeyNotFoundException

<https://github.com/dotnet/msbuild/blob/0538acc04cc2c953f220f9ec3f3764db1769defe/src/Framework/Sdk/SdkResultItem.cs#L33-L53>

If this.Metadata.Count == item.Metadata.Count, but the keys are not the same, then `item.Metadata[kvp.Key]` throws System.Collections.Generic.KeyNotFoundException.

If the method is actually used, this could be fixed by using TryGetValue.

#### PowerShell demo

```
PS C:\> Add-Type -Path "C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\Microsoft.Build.Framework.dll"
PS C:\> $a = [Microsoft.Build.Framework.SdkResultItem]::new()
PS C:\> $a.ItemSpec = "abc"
PS C:\> $a.Metadata.Add("Def", "42")
PS C:\> $b = [Microsoft.Build.Framework.SdkResultItem]::new()
PS C:\> $b.ItemSpec = "abc"
PS C:\> $b.Metadata.Add("Ghi", "42")
PS C:\> $a.Equals($b)
MethodInvocationException: Exception calling "Equals" with "1" argument(s): "The given key 'Def' was not present in the dictionary."
```

### GetHashCode depends on Dictionary order

<https://github.com/dotnet/msbuild/blob/0538acc04cc2c953f220f9ec3f3764db1769defe/src/Framework/Sdk/SdkResultItem.cs#L62-L66>

The resulting hash code depends on the order in which Dictionary\<string, string>.GetEnumerator() returns the key-value pairs. This order can differ even if the two metadata dictionaries contain the same keys and the same values.  Thus, GetHashCode() can return a different hash code even if Equals(object) return true.

If the method is actually used, this could be fixed by computing a hash code for each KeyValuePair individually and combining them with `^` or `+` so that the result is the same regardless of order.  Alternatively, omit the metadata from the hash code altogether; I imagine any hash tables where SdkResultItem instances are used as keys would be unlikely to have multiple instances for the same item spec.

#### PowerShell demo

I'm not sure it will happen every time.

```
PS C:\> $a = [Microsoft.Build.Framework.SdkResultItem]::new()
PS C:\> $b = [Microsoft.Build.Framework.SdkResultItem]::new()
PS C:\> $a.Metadata.Add("1", "")
PS C:\> $a.Metadata.Add("2", "")
PS C:\> $a.Metadata.Add("3", "")
PS C:\> $a.Metadata.Add("4", "")
PS C:\> $a.Metadata.Remove("2")
True
PS C:\> $a.Metadata.Remove("3")
True
PS C:\> $b.Metadata.Add("1", "")
PS C:\> $b.Metadata.Add("4", "")
PS C:\> $a.GetHashCode()
-641818147
PS C:\> $b.GetHashCode()
-641818147
PS C:\> $a.Metadata.Add("5", "")
PS C:\> $b.Metadata.Add("5", "")
PS C:\> $a.GetHashCode()
1124618266
PS C:\> $b.GetHashCode()
1418271594
PS C:\> $a.Equals($b)
True
```

### Unnecessary null checks

SdkResultItem.Metadata is a read-only property and assigned non-null in the constructor, so the null checks `Metadata?.Count` and `if (Metadata != null)` are not needed.

### Inconsistent case sensitivity for metadata keys

Described in [this comment](https://github.com/dotnet/msbuild/issues/6750#issuecomment-898233796).

### PR DESCRIPTION
**Pull request by eriawan**
Fixes #6750 

### Context
The issue #6750 describes that implementation of Equals and GetHashCode is still buggy, and it is not reliable. This change ensures that: 

1. Equals won't throw Exception,
2. Equals compare Key and its value between each KeyValues in Metadata's Key and values
3. Remove additional null check on Metadata, because Metadata property will not be null

### Changes Made
Refactor Equals and GetHashCode methods to ensure reliable comparison as suggested in https://github.com/dotnet/msbuild/issues/6750#issue-967522986

### CODE REVIEW

**Comment by eriawan** [comment]
@BenVillalobos 
I think I had fixed the Equals and ensure the GetHashCode uses XOR to ensure returning the same hashcode for dictionary regardless the order of the keys.

Please review 🙂

**Comment by eriawan** [comment]
Looks like there are errors on some unit tests.

I'll try to fix these now.

**Comment by eriawan** [comment]
@BenVillalobos 
It is green now! 

Please revie, thanks in advance!

File: src/Framework/Sdk/SdkResultItem.cs [hunk 1]
```diff
@@ -55,14 +60,14 @@ public override bool Equals(object obj)
         public override int GetHashCode()
         {
             int hashCode = -849885975;
-            hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(ItemSpec);
+            hashCode = hashCode ^ ItemSpec.GetHashCode();
 
-            if (Metadata != null)
+            if (Metadata != null && Metadata.Count > 0)
```
Comment (rainersigwald) [inline src/Framework/Sdk/SdkResultItem.cs:65]: I don't think we really need to check `Count` here; `foreach` over an empty list is fast.

Also, `Metadata` is never null, right?

File: src/Framework/Sdk/SdkResultItem.cs [hunk 2]
```diff
@@ -55,14 +60,14 @@ public override bool Equals(object obj)
...
             {
                 foreach (var kvp in Metadata)
                 {
-                    hashCode = (hashCode * -1521134295) + kvp.Key.GetHashCode();
-                    hashCode = (hashCode * -1521134295) + kvp.Value.GetHashCode();
+                    hashCode = hashCode ^ kvp.Key.GetHashCode();
+                    hashCode = hashCode ^ kvp.Value.GetHashCode();
```
Comment (rainersigwald) [inline src/Framework/Sdk/SdkResultItem.cs:70]: Likewise here make sure the key/value relationship is order-preserving, while making the inclusion in the overall hashcode order-agnostic. That way these two items compare different:

```
ItemSpec = "ItemSpec"
Metadata = {
  ["Key"] = "value"
}
```

and

```
ItemSpec = "ItemSpec"
Metadata = {
  ["value"] = "Key"
}
```

**Review by rainersigwald — CHANGES_REQUESTED** [review]
Looking pretty good, thanks! In addition to the changes I've mentioned can I ask you to add some tests? They can go in `src/Framework.UnitTests`.

File: src/Framework/Sdk/SdkResultItem.cs [hunk 3]
```diff
@@ -34,13 +34,18 @@ public override bool Equals(object obj)
...
                    ItemSpec == item.ItemSpec &&
-                   Metadata?.Count == item.Metadata?.Count)
+                   Metadata.Count == item.Metadata?.Count)
             {
-                if (Metadata != null)
+                foreach (var kvp in Metadata)
                 {
-                    foreach (var kvp in Metadata)
+                    var itemValue = "";
+                    if (!item.Metadata.TryGetValue(kvp.Key, out itemValue))
```
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:42]: Thanks! Suggestion applied.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 2 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:69]: Just to confirm, the order of the Key in the keys are still ignoring the order, right?
Ok, I'll make the GetHashTable order-preserving for Key-Value more granular.
I'm going to update that including the unit test additions.

Comment (rainersigwald) [reply src/Framework/Sdk/SdkResultItem.cs:69]: Correct; the order of the key-value pairs in the enumeration should not matter, but within each one the key vs value should.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 1 above)
Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:64]: It can be if you pass in null as the metadata when constructing it.

**Review by Forgind — CHANGES_REQUESTED** [review]

File: src/Framework/Sdk/SdkResultItem.cs [hunk 4]
```diff
@@ -34,13 +34,17 @@ public override bool Equals(object obj)
...
             if (obj is SdkResultItem item &&
                    ItemSpec == item.ItemSpec &&
-                   Metadata?.Count == item.Metadata?.Count)
+                   Metadata.Count == item.Metadata?.Count)
             {
-                if (Metadata != null)
+                foreach (var kvp in Metadata)
                 {
-                    foreach (var kvp in Metadata)
+                    if (!item.Metadata.TryGetValue(kvp.Key, out var itemValue))
```
Comment (BenVillalobos) [inline src/Framework/Sdk/SdkResultItem.cs:41]: Like @Forgind suggested, `Metadata` here can be null if the second constructor was called on `item` and null was passed for `metadata`.

We should just initialize `Metadata` to an empty set if this happens in the second constructor.

```c#
        public SdkResultItem(string itemSpec, Dictionary<string, string> metadata)
        {
            ItemSpec = itemSpec;
            Metadata = metadata ?? new();
        }
```

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:41]: Thanks! It makes sense. Currently I'm going to add unit tests first as suggested by @rainersigwald

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:41]: Why should we initialize Metadata to null? I haven't seen people complaining about it being null, and it takes up more space as not-null than null.

Comment (rainersigwald) [reply src/Framework/Sdk/SdkResultItem.cs:41]: I think either way we should consider making this file `#nullable enable` to formalize the decision and let the compiler complain if we get it wrong.

Comment (BenVillalobos) [reply src/Framework/Sdk/SdkResultItem.cs:41]: So that we can make the assumption that it isn't null instead of verifying it every time we use it. I figure it's something we've commented on many times at this point, so just initialize it and be done with it.

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:41]: I'm curious if someone has found a way to rely on it being null...if so, it sounds like a bug, so I don't think it would be a big deal to break them. I'd prefer whatever is most performant.

File: src/Framework/Sdk/SdkResultItem.cs [hunk 5]
```diff
@@ -34,13 +34,17 @@ public override bool Equals(object obj)
         {
             if (obj is SdkResultItem item &&
                    ItemSpec == item.ItemSpec &&
-                   Metadata?.Count == item.Metadata?.Count)
+                   Metadata.Count == item.Metadata?.Count)
```
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs]: Done re-adding Metadata null check. Thanks!

File: src/Framework/Sdk/SdkResultItem.cs (hunk 1 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs]: Done removing unnecessary Count check.
I've added null check too, because the other constructor may accept Metadata parameter as null.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 2 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs]: Done fixing the Key-Value of GetHashCode. Currently adding "K" in hash code gen for Key, and adding "V" for hashcode gen for Value. Therefore Key and Value will always be different when we are getting hashcode of key and value of the enumerated Key-Value pair.

https://github.com/eriawan/msbuild/blob/fix-SdkResultItem-equality/src/Framework/Sdk/SdkResultItem.cs#L66-L70

File: src/Framework/Sdk/SdkResultItem.cs (hunk 4 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:41]: @rainersigwald @Forgind 

Done creating new unit test for SdkResolverItem and also done applying PR feedback, including re-adding Metadata null check.
Do we still need to have `#nullable enable` in the SdkResultItem class?

@BenVillalobos 
About this comment https://github.com/dotnet/msbuild/pull/6839#discussion_r707774092
Do we have to ensure internally that if Metadata being passed is null then we should always have a non null Metadata in the constructor?

If we are going to have this:
```
Metadata = metadata ?? new();
```
Then I'm going to change my commit to remove all of the null check for Metadata, because as far as I know previous code before my PR has no check for null then instantiate new Metadata in the constructor. 
Also CMIIW, previous code seems to always check Metadata for null value and everyone else suggesting to check for passed null value in Metadata when calling the second constructor. So I'm a bit confused, which fix I should take whether I keep the null check or having a guarantee for Metadata to be always non-null inside the second constructor.
Please confirm. 

I'm ok to add that too, if it's decided and agreed by all three of you. 🙂

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:41]: > Do we still need to have `#nullable enable` in the SdkResultItem class?

Yes; it will help ensure we don't accidentally remove the null check later if we opt for allowing Metadata to be null.

We can talk about that on Monday. I'll post a response here afterwards. Thanks for all your work on this!

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:41]: Team triage:
Let's keep the null checks (not initialize Metadata to an empty dictionary) and enable nullable. Thanks!

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:41]: @Forgind and teams,

Thanks for the heads up 🙂 
Ok, I think my next code update is just enable nullable, CMIIW.
Going to update this today.

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:41]: Might need to tweak the hashcode, but otherwise sounds right to me!

File: src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs [hunk 6]
```diff
@@ -0,0 +1,57 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+//
```
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs:3]: thanks!

File: src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+            var sdkResultItem1 = new SdkResultItem();
+            sdkResultItem1.ItemSpec = "AnySpec";
+            sdkResultItem1.Metadata.Add("key1", "value1");
+            sdkResultItem1.Metadata.Add("key2", "value2");
+            var sdkResultItem2 = new SdkResultItem();
+            sdkResultItem2.ItemSpec = "AnySpec";
+            sdkResultItem2.Metadata.Add("key2", "value2");
+            sdkResultItem2.Metadata.Add("key1", "value1");
+
+            Assert.True(sdkResultItem1.Equals(sdkResultItem2));
```
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs:25]: thanks for the suggestion!

File: src/Framework/Sdk/SdkResultItem.cs [hunk 8]
```diff
@@ -55,14 +59,14 @@ public override bool Equals(object obj)
...
-            hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(ItemSpec);
+            hashCode = hashCode ^ ItemSpec.GetHashCode();
 
             if (Metadata != null)
             {
                 foreach (var kvp in Metadata)
                 {
-                    hashCode = (hashCode * -1521134295) + kvp.Key.GetHashCode();
-                    hashCode = (hashCode * -1521134295) + kvp.Value.GetHashCode();
+                    hashCode = hashCode ^ $"K{kvp.Key}".GetHashCode();
```
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:68]: CMIIW, I already get the hashcode of the Itemspec in line 62, and the hashcode is reused and xor-ed again when iterating key-value items in Metadata. So I think I already hash them together.

Or do you have other thinking/suggestion about hashing them together? Please elaborate.

File: src/Framework/Sdk/SdkResultItem.cs [hunk 9]
```diff
@@ -55,14 +60,14 @@ public override bool Equals(object obj)
         public override int GetHashCode()
         {
             int hashCode = -849885975;
-            hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(ItemSpec);
+            hashCode = hashCode ^ ItemSpec.GetHashCode();
```
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:62]: CMIIW, I think my latest update now ensure that the key-value in the metadata ignore the orders of the key but still has the same hashcode returned.

Am I still missing something else? I welcome suggestions 🙂

File: src/Framework/Sdk/SdkResultItem.cs [hunk 10]
```diff
@@ -36,11 +36,15 @@ public override bool Equals(object obj)
                    ItemSpec == item.ItemSpec &&
                    Metadata?.Count == item.Metadata?.Count)
             {
-                if (Metadata != null)
+                foreach (var kvp in Metadata)
```
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:39]: Thanks!
Yes, it is a bit slower. Ok, going to apply your suggestion.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:68]: Right, so I think the ItemSpec is included correctly, but xor shouldn't care about order, which could be problematic. Something like:
```C#
foreach (var kvp in Metadata)
{
    hashCode ^= $"{kvp.Key.GetHashCode()}: {(kvp.Value ?? "V").GetHashCode()}";
}
```

might work better.

**Review by Forgind — APPROVED** [review]
Looks good to me! Thanks @eriawan!

**Comment by eriawan** [comment]
@Forgind 

> Looks good to me! Thanks @eriawan!

Thanks! Hang on, there are compile errors caused by having `#nullable enable`
Going to fix these error first.

File: src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs [hunk 11]
```diff
@@ -0,0 +1,56 @@
...
+            sdkResultItem1.ShouldBe(sdkResultItem2);
+        }
+
+        [Fact]
+        public void SdkResultItem_Equal_CtorParam_MetadataNull()
+        {
+            var sdkResultItem1 = new SdkResultItem("anyspec", new Dictionary<string, string>());
+            var sdkResultItem2 = new SdkResultItem("anyspec", null);
+
+            Assert.True(!sdkResultItem1.Equals(sdkResultItem2));
```
Comment (BenVillalobos) [inline src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs:34]: Missing a few `.ShouldBe` calls

File: src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs [hunk 12]
```diff
@@ -0,0 +1,56 @@
...
+            sdkResultItem1.Metadata.Add("key2", "value2");
+            var hashSdkItem1 = sdkResultItem1.GetHashCode();
+
+            var sdkResultItem2 = new SdkResultItem();
+            sdkResultItem2.ItemSpec = "AnySpec";
+            sdkResultItem2.Metadata.Add("key2", "value2");
+            sdkResultItem2.Metadata.Add("key1", "value1");
+            var hashSdkItem2 = sdkResultItem2.GetHashCode();
+
+            Assert.True(hashSdkItem1 == hashSdkItem2);
```
Comment (BenVillalobos) [inline src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs:52]: See above

File: src/Framework/Sdk/SdkResultItem.cs [hunk 13]
```diff
@@ -36,33 +41,21 @@ public override bool Equals(object obj)
...
-                    {
-                        if (item.Metadata[kvp.Key] != kvp.Value)
-                        {
-                            return false;
-                        }
-                    }
-                }
-
-                return true;
+                return Metadata.All(m => item.Metadata.TryGetValue(m.Key, out var itemValue) && itemValue == m.Value);
```
Comment (Forgind) [inline src/Framework/Sdk/SdkResultItem.cs:44]:
```suggestion
                return Metadata.All(m => item.Metadata?.TryGetValue(m.Key, out var itemValue) && itemValue == m.Value);
```

File: src/Framework/Sdk/SdkResultItem.cs [hunk 14]
```diff
@@ -36,33 +41,21 @@ public override bool Equals(object obj)
...
-            hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(ItemSpec);
+            hashCode = hashCode ^ ItemSpec.GetHashCode();
 
             if (Metadata != null)
             {
                 foreach (var kvp in Metadata)
                 {
-                    hashCode = (hashCode * -1521134295) + kvp.Key.GetHashCode();
-                    hashCode = (hashCode * -1521134295) + kvp.Value.GetHashCode();
+                    hashCode ^= $"{kvp.Key.GetHashCode()}: {(kvp.Value ?? "V").GetHashCode()}".GetHashCode();
```
Comment (Forgind) [inline src/Framework/Sdk/SdkResultItem.cs:58]:
```suggestion
                    hashCode ^= $"{kvp.Key}: {kvp.Value ?? "V"}".GetHashCode();
```

File: src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs (hunk 11 above)
Comment (eriawan) [reply src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs]: Done

File: src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs (hunk 12 above)
Comment (eriawan) [reply src/Build.UnitTests/BackEnd/SdkResultItemComparison_Tests.cs]: Done, thanks!

File: src/Framework/Sdk/SdkResultItem.cs (hunk 14 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:59]: Thanks! Applying your suggestion now.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 13 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:45]: @Forgind 

if I apply your suggestion, I get this error compile"
``` 
Operator '&&' cannot be applied to operands of type 'bool?' and 'bool'
```

Because I think this part `item.Metadata?.TryGetValue(m.Key, out var itemValue)` is evaluated to bool? instead of bool.

Please elaborate or confirm...

**Comment by eriawan** [comment]
Strange, CI have build errors about Tests failed but no further information which tests failing:

image

Folks. what is the actual cause of this test failures?

File: src/Framework/Sdk/SdkResultItem.cs (hunk 13 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:45]: @Forgind 

Please review the failing CI build too, if you don't mind..
I have no clue which failing tests causing the error/failures.

**Comment by eriawan** [comment]
Aha, I got the cause!

updating the unit test now, because now passed metadata in the constructor will not be null inside the constructor.

**Comment by eriawan** [comment]
Ok, CI is almost green except Linux Core:

**Comment by eriawan** [comment]
CI is almost green, Linux Core CI is red now:

image

Hmm... I have no clue what caused this...

**Comment by eriawan** [comment]
ok, I'm waiting confirmation and further review from all of you, folks! 🙏 
Thanks in advance!

**Comment by rainersigwald** [comment]
> Linux Core CI is red now:
> 
> image
> 
> Hmm... I have no clue what caused this...

@AR-May is investigating this. I reran that job.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 13 above)
Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:45]: Ah, that's true. You can check if the TryGetValue equals true, and that should resolve it.

File: src/Framework/Sdk/SdkResultItem.cs [hunk 15]
```diff
@@ -27,42 +33,30 @@ public SdkResultItem()
...
-            Metadata = metadata;
+            Metadata = metadata ?? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
         }
 
         public override bool Equals(object obj)
         {
             if (obj is SdkResultItem item &&
                    ItemSpec == item.ItemSpec &&
-                   Metadata?.Count == item.Metadata?.Count)
+                   Metadata?.Count == item.Metadata.Count)
```
Comment (Forgind) [inline src/Framework/Sdk/SdkResultItem.cs:43]:
```suggestion
                   Metadata?.Count == item.Metadata?.Count)
```

You'll presumably need this too before removing the `?? new Dictionary...` part.

File: src/Framework/Sdk/SdkResultItem.cs [hunk 16]
```diff
@@ -16,6 +21,7 @@ public class SdkResultItem
 
         public SdkResultItem()
         {
+            ItemSpec = "";
```
Comment (Forgind) [inline src/Framework/Sdk/SdkResultItem.cs:24]: Hmm...I hadn't noticed this, but it implies that ItemSpec is supposed to be able to be null—in theory, at least. With the #nullable check, that would prevent the second constructor from letting you pass in a null itemspec, right? I don't think anyone is doing that, but theoretically a breaking change? I don't think it's actually something we should really worry about, but tiny nit:
```suggestion
            ItemSpec = string.Empty;
```

doesn't allocate a new string.

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:24]: Thanks! apply this now.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 13 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:45]: Thanks! resolving this now.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 15 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:43]: @Forgind 

Let me see... So do you think Metadata may be passed with null value on the 2nd constructor that has Metadata as parameter?
If this is true, then I have to update the SdkResultItem unit test of this to ShouldNotBe like this (using diff):

``` diff
        [Fact]
        public void SdkResultItem_Equal_CtorParam_MetadataNull()
        {
            var sdkResultItem1 = new SdkResultItem("anyspec", new Dictionary<string, string>());
            var sdkResultItem2 = new SdkResultItem("anyspec", null);

-            // Should bt the same, because passed null metadata will have value of new Dictionnary<String,String> like sdkResultItem1
-            sdkResultItem1.ShouldBe(sdkResultItem2);
+           // Should not be the same, because passing metadata = null is allowed and the Metadata property value allows null.
+           sdkResultItem1.ShouldNotBe(sdkResultItem2);
        }
```

Please confirm. Thanks in advance!

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:43]: Yes, correct. We want to allow Metadata to be null.

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:43]: ok, I have updated the code (but I haven't pushed yet) so now it looks like this:

```
        public override bool Equals(object obj)
        {
            if (obj is SdkResultItem item &&
                   ItemSpec == item.ItemSpec &&
                   Metadata?.Count == item.Metadata?.Count)
            {
                return Metadata.All(m => item.Metadata.TryGetValue(m.Key, out var itemValue) && itemValue == m.Value);
            }
            return false;
        }
```
But now this line: 
```
return Metadata.All(m => item.Metadata.TryGetValue(m.Key, out var itemValue) && itemValue == m.Value);
```
cause this warning: `Dereference of a possibly null reference.` especially on `Item.Metadata.TryGetValue(...` which I think that warning will be treated as Error in the CI.
If I change to `item.Metadata?.TryGetValue(...` then I will get error of can't convert bool? to bool again.

Please confirm. I'm a bit confused now, because now I'm back to previous compile errors I mentioned before (both deference and the bool? error)

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:43]: Ok, so we want Metadata to be able to be null. The compiler (with nullable enabled) looks for anything that can possibly be null and ensures that you verify that it isn't null before you try to dereference it because otherwise you could get an exception at runtime.

If Metadata can be null, then calling `TryGetValue` on item.Metadata is calling a function from something that might be null—it's dereferencing a null value.

When you add the `?`, that checks if it's null and only calls the function afterwards if it isn't. If it is, it skips the function call and replace it with null.

Because we are in a nullable-enabled environment, the compiler is still looking for things that can possibly be null and annotating them as such. TryGetValue normally returns a normal bool, i.e., not null. Because we had item.Metadata?.TryGetValue, it will either return a bool from TryGetValue _or_ skip the TryGetValue and return null because Metadata is null. Returning something that is either null or a bool is returning a bool? or nullable bool.

The && operator cannot take in null because it isn't exactly true but it also isn't exactly false. We need a way to convert a bool? into a bool without possibly throwing an error if it is null.

Normally, it's pointless to say, for instance, `if (<bool value> == True)` because the bool value is already either true or false. However, with a bool?, it can be true, false, or null. Checking explicitly if it == True (or == False) is a check that it is _not_ null _and_ that it is the value you're checking. For them to be equal, we need all the metadata to be the same, which means it cannot be null if our metadata is not null, and it must have the value, so TryGetValue has to return true. Checking item.Metadata?.TryGetValue(m.Key, out var itemValue) == True covers both of those cases at the same time.

If you want to make this easier to understand, you can also explicitly check if either is null at the top, then cast them to non-null Dictionaries and compare them as such.

Does that make more sense?

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:43]: @Forgind 

Many thanks! Makes sense now, and my confusion is gone.

based on this:
> If you want to make this easier to understand, you can also explicitly check if either is null at the top, then cast them to non-null Dictionaries and compare them as such.

I have updated that code to be like this checking of `item.Metadata  == null` is within the if clauses) since this also remove the dereference warning (imho the logic feels cleaner cmiiw)

```
        public override bool Equals(object obj)
        {
            if (obj is SdkResultItem item &&
                   ItemSpec == item.ItemSpec &&
                   item.Metadata != null &&
                   Metadata?.Count == item.Metadata.Count)
            {
                return Metadata.All(m => item.Metadata.TryGetValue(m.Key, out var itemValue) && itemValue == m.Value);
            }
            return false;
        }
```
If you are ok, I will commit that with the updated unit test to use `ShouldNotBe`.

Again, many thanks for the explanation and patience!

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:44]: I think I've committed my proposal now, including the updated unit test in commit https://github.com/dotnet/msbuild/pull/6839/commits/8593b36bec85853bf7234864ded7cee6c92d6c86

So we could quickly examine the change I proposed. Also I need to check the CI so to ensure I have no compile errors.

If you have additional feedback, I'll update them again.

Thanks in advance!

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:44]: It looks like you're still asserting that Metadata is not null by declaring it with:
`public Dictionary<string, string> Metadata { get;}`
instead of
`public Dictionary<string, string>? Metadata { get;}`

If you add that in and don't give it a starting value if it's null, it should break again at the top of equals because you never verify that this.Metadata is not null. (Also, tiny nit: you can technically override the `==` method, so we prefer to use `is null` and `is not null`.)

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:44]: Nice catch! thanks!

I've updated the code.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 2 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs]: @rainersigwald 

Done applying the suggestion and also in sync with feedback from others.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 15 above)
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:44]: @Forgind 

Done updating the code and applying to use `is not null`. CI is green.
Please review.

Hopefully this meet the feedback 🙂 
Thanks!

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:44]: @Forgind 

Done. Thanks

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:44]: Looks good. If this passes CI, I'm happy 🙂

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:44]: CI is all green now 🙂

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:44]: @Forgind 
Now that the CI is all green, is there anything else I should check?

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:44]: just to nudge/remind, 
anything else for me to check? or do I have to wait for other PR to be reviewed and merged before this PR?
sorry to always asking you folks. 🙏 
it's ok if this PR may wait for other PRs or if you're busy. 🙂 
because my team need this fix, so hopefully next week I could use new msbuild that has this fix.

okay, I'm going to step back and check this PR tomorrow. :wave:
many thanks for your guidance and patience, folks!

@Forgind  @rainersigwald @BenVillalobos

Comment (rainersigwald) [reply src/Framework/Sdk/SdkResultItem.cs:44]: > my team need this fix

Can you elaborate on how you're seeing this at all? From the original bug it looked like a code-inspection discovered problem that was purely theoretical.

Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:44]: @rainersigwald 
I need this to compare `SdkResultItem` reliably, because ,my team and I have some scenarios that use comparison of this SdkResultItem. 
Sorry, I could not disclose the further detail of the scenario. 🙏 

I'll use my own msbuild repo while waiting for this to be reviewed further, then. No need to rush, folks.
Thanks again! 👍

Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:44]: I'd wait for rainersigwald to sign off too; if he does, we can merge this.

File: src/Framework/Sdk/SdkResultItem.cs [hunk 17]
```diff
@@ -34,35 +40,24 @@ public override bool Equals(object obj)
...
-            hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(ItemSpec);
+            hashCode = hashCode ^ ItemSpec.GetHashCode();
 
             if (Metadata != null)
             {
                 foreach (var kvp in Metadata)
                 {
-                    hashCode = (hashCode * -1521134295) + kvp.Key.GetHashCode();
-                    hashCode = (hashCode * -1521134295) + kvp.Value.GetHashCode();
+                    hashCode ^= $"{kvp.Key}: {kvp.Value ?? "V"}".GetHashCode();
```
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:60]: @rainersigwald 
Could I use StringBuilder to minimize allocations?

[the remark this answers is not in the document]
Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:60]: You could probably change this to hashCode ^= kvp.Key.GetHashCode() * ((kvp.Value ?? "V").GetHashCode() + 1); and avoid allocations while ignoring order, maintaining association importance, and differentiating between keys and values.

[the remark this answers is not in the document]
Comment (KalleOlaviNiemitalo) [reply src/Framework/Sdk/SdkResultItem.cs:60]: `kvp.Key.GetHashCode()` is wrong. Because the metadata dictionary uses OrdinalIgnoreCase comparison for the keys, GetHashCode() must do the same; please see <https://github.com/dotnet/msbuild/issues/6750#issuecomment-898233796>.

Does this project already reference an assembly that provides [HashCode.Combine](https://docs.microsoft.com/dotnet/api/system.hashcode.combine?view=dotnet-plat-ext-3.1#System_HashCode_Combine__2___0___1_)?

**Review by KalleOlaviNiemitalo — CHANGES_REQUESTED** [review]

File: src/Framework/Sdk/SdkResultItem.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (KalleOlaviNiemitalo) [reply src/Framework/Sdk/SdkResultItem.cs:54]: If GetHashCode() considered only the ItemSpec and ignored the Metadata, would that improve performance (because of simpler computation) or hurt performance (because of more frequent hash collisions)?

File: src/Framework/Sdk/SdkResultItem.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:60]: You're right about the case sensitivity weirdness, and it would be good to fix that, but it wasn't correct before, and eriawan said they planned just to resolve the first few bullets, so I'm assuming we're leaving that for a later PR. Is that correct, @eriawan?

No, I don't think so, though I agree it would be nice here.

[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:60]: @Forgind 

Yes, my initial plan was to leave the case sensitivity for later PR.
Do you want that to be solved too?
We still have allocation problem that needs to be solved, as suggested by @rainersigwald

File: src/Framework/Sdk/SdkResultItem.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs:54]: I think we should consider GetHashCode for Metadata too. 
Now finding the best way to handle this.

File: src/Framework/Sdk/SdkResultItem.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:60]: Apparently you can just say OrdinalIgnoreCase.GetHashCode(<string>), and it will get you a case-insensitive hash.

> hashCode ^= kvp.Key.GetHashCode() * ((kvp.Value ?? "V").GetHashCode() + 1);

This was my suggestion to get away from the allocation.

**Comment by Forgind** [comment]
@eriawan, have you had a chance to get back to this? I think it's almost ready; just have to push a little change with the hashcode, and it should be good. I can do that if you don't have time.

**Comment by eriawan** [comment]
@Forgind 

thanks for the reminder! apologize I was buried with work and personal matters for 2 months.
ok, I'll rebase and update with your latest suggestions above and run the unit test again 
I'm going to visit this today.

**Comment by eriawan** [comment]
@Forgind 

Done updating the `GetHashCode` based on your suggestion https://github.com/dotnet/msbuild/pull/6839#discussion_r721524223

File: src/Framework/Sdk/SdkResultItem.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (eriawan) [reply src/Framework/Sdk/SdkResultItem.cs]: @Forgind 

branch rebased to main, and GetHashCode updated. 
There were failing unit tests, but those failed tests aren't related to my updates at all.
Please review, thanks in advance! 🙏

File: src/Framework/Sdk/SdkResultItem.cs [hunk 18]
```diff
@@ -34,35 +40,24 @@ public override bool Equals(object obj)
...
-            hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(ItemSpec);
+            hashCode = hashCode ^ ItemSpec.GetHashCode();
 
             if (Metadata != null)
             {
                 foreach (var kvp in Metadata)
                 {
-                    hashCode = (hashCode * -1521134295) + kvp.Key.GetHashCode();
-                    hashCode = (hashCode * -1521134295) + kvp.Value.GetHashCode();
+                    hashCode ^= StringComparer.OrdinalIgnoreCase.GetHashCode($"{kvp.Key}: {kvp.Value ?? "V"}");
```
Comment (Forgind) [inline src/Framework/Sdk/SdkResultItem.cs:60]: I think this was the complete suggestion (to avoid the allocation)
```suggestion
                    hashCode ^= StringComparer.OrdinalIgnoreCase.GetHashCode(kvp.Key) * (StringComparer.OrdinalIgnoreCase.GetHashCode(kvp.Value ?? "V") + 1);
```

**Comment by eriawan** [comment]
@Forgind 
code updated as suggested. thanks! 🙂

File: src/Framework/Sdk/SdkResultItem.cs [hunk 19]
```diff
@@ -34,35 +40,24 @@ public override bool Equals(object obj)
...
-            hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(ItemSpec);
+            hashCode = hashCode ^ ItemSpec.GetHashCode();
 
             if (Metadata != null)
             {
                 foreach (var kvp in Metadata)
                 {
-                    hashCode = (hashCode * -1521134295) + kvp.Key.GetHashCode();
-                    hashCode = (hashCode * -1521134295) + kvp.Value.GetHashCode();
+                    hashCode ^= StringComparer.OrdinalIgnoreCase.GetHashCode(kvp.Key) * (StringComparer.OrdinalIgnoreCase.GetHashCode(kvp.Value ?? "V") + 1);
```
Comment (rainersigwald) [inline src/Framework/Sdk/SdkResultItem.cs:60]: Did we discuss whether the value should be IgnoreCase or not? I agree the key should be but I'm less sure on the value.

**Review by rainersigwald — APPROVED** [review]

File: src/Framework/Sdk/SdkResultItem.cs (hunk 19 above)
Comment (Forgind) [reply src/Framework/Sdk/SdkResultItem.cs:60]: I don't think we talked about it. Maybe doesn't matter? I'm not sure.

**Comment by eriawan** [comment]
@Forgind @rainersigwald 

Folks, are there any update on this PR review?

**Comment by Forgind** [comment]
Yes! We agreed it's ready to merge, so probably soon. Thanks for your patience with this!

**Comment by eriawan** [comment]
thanks folks! 👍
