### PR TITLE
Emit NETSDK1057 at most once in -tl

### LINKED ISSUE #9602: [NETSDKE2E]With NET 9 alpha SDK installed, the message that you are using a preview version of .NET should be displayed when building project in CLI.
**Affect build:**
 .NET 9.0.100-alpha.1.24053.14(runtime-9.0.0-alpha.1.24053.1) from [dotnet/installer: .NET SDK Installer (github.com)](https://github.com/dotnet/installer)
Affected Product Language:

Steps to reproduce:

1. in CLI, dotnet new console and then dotnet build
2. Check the message displaying in CLI.

**Expected Result:**
the message that you are using a preview version of .NET should be displayed.
**Actual Result:**
the message that you are using a preview version of .NET has been removed.
image

But in VS(17.9 perview 3 + 9.0.100-alpha.1.24053.14 SDK). create a net9.0 console and build in VS, the message that you are using a preview version of .NET is still displayed.
image

<details><summary>dotnet --info</summary>
```
.NET SDK:
 Version:           9.0.100-alpha.1.24053.14
 Commit:            48543d2076
 Workload version:  9.0.100-manifests.ae1d05f3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20348
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-alpha.1.24053.14\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.9.34502.94
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: VS 17.9.34502.94
   Manifest Version:    17.0.8500/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8500\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.9.34502.94
   Manifest Version:    17.0.8500/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8500\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.9.34502.94
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: VS 17.9.34502.94
   Manifest Version:    8.0.0-preview.1.23557.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0-preview.1.23557.2\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-alpha.1.24053.1
  Architecture: x64
  Commit:       cc26196708

.NET SDKs installed:
  8.0.200-preview.23620.12 [C:\Program Files\dotnet\sdk]
  9.0.100-alpha.1.24053.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-alpha.1.23620.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-alpha.1.24053.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-alpha.1.24053.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info
```
</details>

### PR DESCRIPTION
**Pull request by rainersigwald**
Fixes #9602 by emitting NETSDK1057 as an immediate message at most once in the TerminalLogger.

```sh-session
❯ dotnet build
MSBuild version 17.10.0-dev-24055-01+3500455af for .NET
Restore complete (1.1s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  Lib1 succeeded (3.1s) → Lib1\bin\Debug\net9.0\Lib1.dll
  Lib2 succeeded (3.1s) → Lib2\bin\Debug\net9.0\Lib2.dll
  App succeeded (3.2s) → App\bin\Debug\net9.0\App.dll

Build succeeded in 4.5s
```

It is slightly ugly to do this deduplication at the logger level, but it cleans up a customer annoyance so I think it's worth it.

### CODE REVIEW

**Review by rokonec — APPROVED** [review]

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 1]
```diff
@@ -570,6 +575,16 @@ private void MessageRaised(object sender, BuildMessageEventArgs e)
             {
                 RenderImmediateMessage(message);
             }
+
+            if (e.Code == "NETSDK1057" && !_loggedPreviewMessage)
```
Comment (ladipro) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:579]: super-nit:
```suggestion
            else if (e.Code == "NETSDK1057" && !_loggedPreviewMessage)
```

**Review by ladipro — APPROVED** [review]
