### PR TITLE
LiveLogger v2

### LINKED ISSUE #8370: MSBuild LiveLogger keeps users informed about their build and delights new users
The LiveLogger is an exciting new feature that MSBuild team has planned for .NET 8. Originally spearheaded by @edvilme, the LiveLogger is intended to be a live-updating, data-heavy view of what is happening in your build right now, using features present in modern terminals to help declutter and organize build results. The goal for this logger is to become the new default experience for all interactive build sessions started by the .NET CLI!

This issue will serve as a centralized way to check on the status of the LiveLogger feature.

## Release plan

We are aiming for an initial 'give it a try', opt-in release by the 8.0.100-preview4 time frame. After that, we'll iterate on the logger to meet our goals for user experience and react to user feedback until we're satisfied with the performance and functionality. At that point, we'll enable the live logger by default in the .NET CLI and the feature will be officially released.

## Items to tackle for preview4

Before we can do that, the following items should be addressed:

* [x] The outstanding PRs need to be merged. #8356, #8324, and #8314 all represent the latest work on the logger, and we need to get them integrated to serve as the foundation for further work.
* [x] #8393
* [ ] An announcement blog for the preview2 timeframe needs to be drafted. I'd like to include @edvilme in the authoring of this post to talk about his time working on it.
* [x] https://github.com/dotnet/msbuild/issues/8379 We need to iterate on the display of completed-but-irrelevant projects. 
* [ ] #8428 (Consider adding a message to the console logger output advertising LiveLogger during the preview timeframe)
* [ ] #8391
* [x] #8392
* [x] #8384
* [x] #8429 (LiveLogger should respond to user themes)
* [ ] #8430 (Perform code review of the code and cleanup coding/styling standards miss-steps)
* [ ] #8413
* [ ] #8431 (Ensure LiveLogger has the right opt-in state to get the most modern logging including when combined with `-bl`)
* [ ] #8418
* [ ] #8435
* [ ] Bug bash for preview 2
* [x] #8450 
* [x] #8455 
* [x] #8456
* [x] #8458
* [x] #8460 
* [x] #8463 
* [x] #8464

### LINKED ISSUE #8392: auto-scroll after scrolling after using live logger
Repro on windows 11 console window
- dotnet new console
- dotnet build -ll
- let the build finish
- scroll up with the mouse wheel
- up arrow
On that last step, my command window jumps scrolling back to where it ended the build. I'll see if I can record a gif.
LLautoscrollbug

### LINKED ISSUE #8430: [LiveLogger] Adhere to coding & styling standards.
Perform code review of the code and cleanup coding/styling standards miss-steps.

@baronfel - feel free to extend the description if needed.

### LINKED ISSUE #8456: [LiveLogger] Don't render any yellow or red unless/until there is a warning/error
The cross mark ❌ character is usually rendered in red and it unnecessarily creates the impression that something is wrong even if the build is progressing just fine. Similar for the yellow exclamation point.

image

Suggestion: Add the &lt;number&gt; ℹ️, &lt;number&gt; ⚠️, &lt;number&gt; ❌ output only when &lt;number&gt; is &gt;0 (for each of the three).

### LINKED ISSUE #8458: [LiveLogger] Many exceptions are thrown from the logger
### Issue Description

Throwing and catching exceptions has perf implications and generally makes debugging harder.

### Steps to Reproduce

Run `msbuild /ll` under a debugger.

### Expected Behavior

No exceptions.

### Actual Behavior

Many occurrences of:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Logging.LiveLogger.ProjectNode.Log() in C:\src\msbuild\src\MSBuild\LiveLogger\ProjectNode.cs:line 156
```

With an occasional:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.Build.Logging.LiveLogger.TerminalBuffer.Render() in C:\src\msbuild\src\MSBuild\LiveLogger\TerminalBuffer.cs:line 145
```

### Analysis

_No response_

### Versions & Configurations

Commit dfd8f413a80cd0865f968b2c0ad9b09c0df8c430

### LINKED ISSUE #8460: [LiveLogger] Screen buffer has duplicated lines sometimes
### Issue Description

Instead of overwriting lines (for lack of better words; apologies, I am terminal illiterate) the logger is sometimes adding new ones, leading to broken output. Seems to be timing related, tends to happen more when MSBuild is cold.

### Steps to Reproduce

`msbuild.exe /ll /t:rebuild` in a directory with a single project.

### Expected Behavior

I believe there should be only one line with `SimpleWebApp.csproj` and the progress indicator (`\`, `|`, `/`, `-`) changing in place.

### Actual Behavior

This is what I see:

image

### Analysis

_No response_

### Versions & Configurations

Commit dfd8f413a80cd0865f968b2c0ad9b09c0df8c430

### LINKED ISSUE #8463: [LiveLogger] Plug the logger into minimum message importance checks
As a perf optimization MSBuild can filter out verbose log output very early to speed up the build if no logger interested in low importance messages is enabled. LiveLogger is currently not recognized by this system, making it slower than the default console logger as configured in `dotnet build`.

It should be as simple as adding a case here:
https://github.com/dotnet/msbuild/blob/dfd8f413a80cd0865f968b2c0ad9b09c0df8c430/src/Build/BackEnd/Components/Logging/LoggingService.cs#L1630-L1644

Needless to say, LL must not actually consume any low importance messages for this to work.

### LINKED ISSUE #8464: Improve LiveLogger.Render performance
I profiled the LiveLogger during rebuild of OC repo with /m:1. I found some parts of Render function to consume significant amount of CPU:
image
The total time of build was 62.5 sec, which is 20 sec more than with console logger with normal verbosity.

### LINKED ISSUE #8481: [LiveLogger] Unreliable check for ANSI-capable terminal on Windows
> The Internet seems to think that checking the result of `GetConsoleMode` for `ENABLE_VIRTUAL_TERMINAL_PROCESSING` may be a better way of detecting fancy-capable environments.

this snippet from pwsh looks relevant:

https://github.com/SteveL-MSFT/PowerShell/blob/4c01dcc5d5672f4b0ccbac87fe756de01f487887/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L64-L85

_Originally posted by @rainersigwald in https://github.com/dotnet/msbuild/issues/8467#issuecomment-1439185528_
            
---

We currently use the `WT_SESSION` environment variable, which does not work in all scenarios. See the discussion in #8467 for details.

### PR DESCRIPTION
**Pull request by ladipro**
Fixes #8481, fixes #8464, fixes #8463, fixes #8460, fixes #8458, fixes #8456, fixes #8430, fixes #8370, fixes #8392

### Context

We have decided to change the LiveLogger UX. Instead of the "full screen" or "takes-over-the-screen-buffer" interactive experience, the goal is a more conventional logger with a node-centric live view and no interactivity.

### Changes Made

Re-implemented LiveLogger based on the https://www.github.com/rainersigwald/tortillachip prototype. Since the visual design is not yet finalized, the strings are still hardcoded in source files.

### Testing

Existing and newly introduced tests. Manual smoke test.

### Notes

`LiveLogger.cs` was completely rewritten so please look at the new content instead of the diff.

Here are some of the differences compared to v1:

- The logger is supported only in the .NET build of MSBuild, i.e. not in MSBuild.exe.
- We now use a proper check for ANSI capable terminal on Windows. Interestingly, the classic cmd satisfies the check and LiveLogger works there as well (on Win11 at least).
- The logger is recognized by the minimum message importance optimization for better perf.

### Example build gifs

fsac-build

### CODE REVIEW

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 1]
```diff
@@ -1651,8 +1651,11 @@ private void UpdateMinimumMessageImportance(ILogger logger)
                 // The null logger has no effect on minimum verbosity.
                 Execution.BuildManager.NullLogger => null,
 
-                // If the logger is not on our whitelist, there are no importance guarantees. Fall back to "any importance".
-                _ => MessageImportance.Low
+                // The live logger consumes only high priority messages.
+                _ => innerLogger.GetType().FullName == "Microsoft.Build.Logging.LiveLogger.LiveLogger"
```
Comment (donJoseLuis) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:1655]: minor: consider `typeof(LiveLogger).FullName`, that way if namespaces change the code will remain valid.

File: src/Framework/NativeMethods.cs [hunk 2]
```diff
@@ -1480,6 +1480,69 @@ internal static void VerifyThrowWin32Result(int result)
...
     }
 
+#if !CLR2COMPATIBILITY
+    internal static (bool acceptAnsiColorCodes, bool outputIsScreen, uint? originalConsoleMode) QueryIsScreenAndTryEnableAnsiColorCodes()
+    {
+        bool acceptAnsiColorCodes = false;
+        bool outputIsScreen = false;
+        uint? originalConsoleMode = null;
+
+        if (!Console.IsOutputRedirected)
```
Comment (donJoseLuis) [inline src/Framework/NativeMethods.cs:1490]: minor: Could the if block hierarchy be flattened?

```
if (!Console.IsOutputRedirected && 
IsWindows &&
GetStdHandle(STD_OUTPUT_HANDLE) is IntPtr stdOut &&
GetConsoleMode(stdOut, out uint cnosoleMode){...}
```

File: src/MSBuild.UnitTests/LiveLogger_Tests.cs [hunk 3]
```diff
@@ -0,0 +1,217 @@
...
+        public event BuildStatusEventHandler? StatusEventRaised;
+
+        public event AnyEventHandler? AnyEventRaised;
+#pragma warning restore CS0067
+
+        #endregion
+
+        #region IDisposable implementation
+
+        public void Dispose()
```
Comment (donJoseLuis) [inline src/MSBuild.UnitTests/LiveLogger_Tests.cs:72]: minor: Though it's test code, consider https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern

File: src/MSBuild/LiveLogger/Project.cs [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+    {
+        BuildMessages ??= new List<BuildMessage>();
+        BuildMessages.Add(new BuildMessage(severity, message));
+    }
+}
+
+/// <summary>
+/// Enumerates the supported message severities.
+/// </summary>
+internal enum MessageSeverity { Warning, Error }
```
Comment (donJoseLuis) [inline src/MSBuild/LiveLogger/Project.cs:57]: minor: consider 1 type / file.

File: src/MSBuild/LiveLogger/Terminal.cs [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+        WriteLine(input.Slice(0, Math.Min(input.Length, Width - 1)));
+    }
+
+    /// <inheritdoc/>
+    public void WriteColor(TerminalColor color, string text)
+    {
+        if (_isBuffering)
+        {
+            _outputBuilder
+                .Append("\x1b[")
```
Comment (donJoseLuis) [inline src/MSBuild/LiveLogger/Terminal.cs:116]: minor: Consider constants for these escape sequences.

**Review by donJoseLuis — APPROVED** [review]
minor suggestions

File: src/Build/BackEnd/Components/Logging/LoggingService.cs (hunk 1 above)
Comment (ladipro) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:1655]: This is unfortunately not possible with the current layering. The new logger is in `MSBuild.dll` and this backend code resides in `Microsoft.Build.dll` which is a dependent assembly of `MSBuild.dll`. We are aware of the limitation and if more issues like this arise, we may go ahead and move the logger to the other assembly.

File: src/Framework/NativeMethods.cs (hunk 2 above)
Comment (ladipro) [reply src/Framework/NativeMethods.cs]: Doesn't seem to be possible to go this far. I have removed one level of nesting.

File: src/MSBuild.UnitTests/LiveLogger_Tests.cs (hunk 3 above)
Comment (ladipro) [reply src/MSBuild.UnitTests/LiveLogger_Tests.cs:72]: `IDispose` is just for running code after each test. The full pattern would be an overkill (we don't do it in existing tests either, I've checked).

File: src/MSBuild/LiveLogger/Project.cs (hunk 4 above)
Comment (ladipro) [reply src/MSBuild/LiveLogger/Project.cs]: Thank you, done. All top-level types have their own source file now.

File: src/MSBuild/LiveLogger/Terminal.cs (hunk 5 above)
Comment (ladipro) [reply src/MSBuild/LiveLogger/Terminal.cs]: I've added `AnsiCodes.cs` with the escape sequences used in the logger.

File: src/MSBuild/LiveLogger/LiveLogger.cs [hunk 6]
```diff
@@ -42,302 +129,608 @@ internal class LiveLogger : ILogger
...
+                    double duration = project.Stopwatch.Elapsed.TotalSeconds;
+                    ReadOnlyMemory<char>? outputPath = project.OutputPath;
 
-                    // Rerender projects only when needed
-                    foreach (var project in projects)
+                    Terminal.Write(Indentation);
+
+                    if (e.ProjectFile is not null)
+                    {
+                        string projectFile = Path.GetFileName(e.ProjectFile);
```
Comment (rainersigwald) [inline src/MSBuild/LiveLogger/LiveLogger.cs:328]: The old-school message is `FileNameWithoutExtension`. I think I'd prefer to keep that.

**Review by rainersigwald — APPROVED** [review]

File: src/Directory.BeforeCommon.targets [hunk 7]
```diff
@@ -92,6 +92,7 @@
     <DefineConstants>$(DefineConstants);USE_MSBUILD_DLL_EXTN</DefineConstants>
     <DefineConstants>$(DefineConstants);WORKAROUND_COREFX_19110</DefineConstants>
     <DefineConstants>$(DefineConstants);FEATURE_SYMLINK_TARGET</DefineConstants>
+    <DefineConstants>$(DefineConstants);FEATURE_LIVELOGGER</DefineConstants>
```
[the remark this answers is not in the document]
Comment (ladipro) [reply src/Directory.BeforeCommon.targets:95]: Definitely not dramatic. The motivation for the feature flag was the explicit decision that we want to support the new logger only in .NET SDK, not span or other implementation details. I may have misunderstood, tagging @baronfel to check if he's OK with exposing `/tl` in `MSBuild.exe` as well.

File: src/MSBuild/LiveLogger/LiveLogger.cs [hunk 8]
```diff
@@ -2,36 +2,123 @@
...
+            return string.IsNullOrEmpty(TargetFramework)
+                ? $"{Indentation}{Project} {Target} ({Stopwatch.Elapsed.TotalSeconds:F1}s)"
+                : $"{Indentation}{Project} [{TargetFramework}] {Target} ({Stopwatch.Elapsed.TotalSeconds:F1}s)";
+        }
+    }
+
+    /// <summary>
+    /// The indentation to use for all build output.
+    /// </summary>
+    private const string Indentation = "  ";
```
[the remark this answers is not in the document]
Comment (ladipro) [reply src/MSBuild/LiveLogger/LiveLogger.cs:50]: I think we wanted this for an easier-to-read multiline output (both "project done" and warnings/errors) because it's easier to  tell on which terminal line a logical line starts. Without this the output looks like the proverbial wall of text. Very subjective and I don't feel strongly about it.

File: src/MSBuild/LiveLogger/LiveLogger.cs [hunk 9]
```diff
@@ -42,302 +129,608 @@ internal class LiveLogger : ILogger
...
+        try
         {
-            Parameters = "";
+
+            Terminal.WriteLine("");
+            Terminal.Write("Build ");
+
+            PrintBuildResult(e.Succeeded, _buildHasErrors, _buildHasWarnings);
+
+            double duration = (e.Timestamp - _buildStartTime).TotalSeconds;
```
[the remark this answers is not in the document]
Comment (ladipro) [reply src/MSBuild/LiveLogger/LiveLogger.cs:222]: No mismatch observed so far and console logger uses these too. So I think I'd vote for not a problem.

File: src/MSBuild/LiveLogger/LiveLogger.cs [hunk 10]
```diff
@@ -42,302 +129,608 @@ internal class LiveLogger : ILogger
...
-            // BuildMessageEventHandler event handler below currently process only High importance events. 
-            eventSource.MessageRaised += new BuildMessageEventHandler(eventSource_MessageRaised);
-            eventSource.WarningRaised += new BuildWarningEventHandler(eventSource_WarningRaised);
-            eventSource.ErrorRaised += new BuildErrorEventHandler(eventSource_ErrorRaised);
-
-            // Cancelled
-            Console.CancelKeyPress += new ConsoleCancelEventHandler(console_CancelKeyPressed);
-
-            Task.Run(() =>
+            if (e.GlobalProperties?.TryGetValue("TargetFramework", out string? targetFramework) != true)
```
[the remark this answers is not in the document]
Comment (ladipro) [reply src/MSBuild/LiveLogger/LiveLogger.cs:249]: Filed #8651. What do you mean by right-hand side?

File: src/Directory.BeforeCommon.targets (hunk 7 above)
[the remark this answers is not in the document]
Comment (baronfel) [reply src/Directory.BeforeCommon.targets:95]: I'm perfectly happy to allow it to be exposed in both tools - but our focus should be on the .NET SDK user base as far as final desired UX decisions go.

[the remark this answers is not in the document]
Comment (ladipro) [reply src/Directory.BeforeCommon.targets]: I have removed the ifdef and enabled the logger in `MSBuild.exe` in 6b0a1c0fd.
