### PR TITLE
Avoid building dwproj

### LINKED ISSUE #2064: Build error MSB4067 (UnrecognizedChildElement) when building a solution with rptproj or dwproj projects
When using MSBuild 15.0, cleaning or building a solution which contains rptproj or dwproj projects gives the following error:

> Reports.rptproj(3,3): error MSB4067: The element <State> beneath element <Project> is unrecognized.

When using MSBuild 14.0, the behaviour is better: it logs warnings (MSB4078) about unsupported projects:

> warning MSB4078: The project file "Reports.rptproj" is not supported by MSBuild and cannot be built.

The latter behaviour is more desirable (for me, at least): I would like to able to build a solution in a configuration which includes the .rptproj files. This would allow me to include these projects when building the solution in Visual Studio, and to be able to use the same configuration when building the solution via an MSBuild script.

Is this change of behaviour a bug? The message certainly seems like it is attempting to parse the rptproj file into some structure to which it doesn't belong. If it is not, is there a way to downgrade the error MSB4067 to a warning, or to skip certain projects when building a solution? The `/ignoreprojectextensions:.rptproj` option does not prevent the error.

Note: this issue relates to [this Stack Overflow post](https://stackoverflow.com/questions/43735390/msbuild-15-0-visual-studio-2017-throws-error-msb4067-for-solutions-with-ssdt-p).

### PR DESCRIPTION
**Pull request by Forgind**
Mitigates #2064

### Context
This is an alternate way to fix the same problem. This is incomplete: it would still need to replace "dwproj" with the !projectsKnownToBeMSBuild and add a warning.

### CODE REVIEW

**Comment by Forgind** [comment]
I realized ^ doesn't help. It'd still require changes in other places, and we already know that we "can't directly build" dwproj.

**Comment by Nirmal4G** [comment]
Instead of hard coding un-supported file extensions, we could generally accept the `*.*{0,7}proj` pattern since the longest file extension I came across is `.msbuildproj`! Also, can we also white-list known extensions in `msbuild.exe.config` via settings or maybe a json options file?

File: src/Build/Construction/Solution/ProjectInSolution.cs [hunk 1]
```diff
@@ -342,7 +342,7 @@ internal bool CanBeMSBuildProjectFile(out string errorMessage)
                     // not an MSBuild file. It will however have ToolsVersion="2.0" which is not supported with an empty
                     // schema. This is not a great solution, but it should cover the customer reported issue. See:
                     // https://github.com/dotnet/msbuild/issues/2064
-                    if (emptyNamespace && !projectElementInvalid && mainProjectElement.GetAttribute("ToolsVersion") != "2.0")
+                    if (emptyNamespace && !projectElementInvalid && mainProjectElement.GetAttribute("ToolsVersion") != "2.0" && !Path.GetExtension(AbsolutePath).Equals(".dwproj", StringComparison.OrdinalIgnoreCase))
```
Comment (rainersigwald) [inline src/Build/Construction/Solution/ProjectInSolution.cs:345]: Are there any more robust checks we could apply, like "defines a namespace for `http://schemas.microsoft.com/DataWarehouse/Designer/1.0`"?

Comment (rainersigwald) [reply src/Build/Construction/Solution/ProjectInSolution.cs:345]: Basically I'd like to future-proof against "we have a new version of dwproj tooling and dwproj is an msbuild project now" which has happened with other project types.

Comment (Forgind) [reply src/Build/Construction/Solution/ProjectInSolution.cs:345]: I'm not sure that's really more future-proof. If the format for dwproj changes, and it no longer defines that namespace (or doesn't do whatever else we would do to check if it's msbuild-y), #2064 would come back unexpectedly. Of note, it would come back for a lot of people all at once. If dwproj switches to being msbuild-y, we would be wrong with the check here, but that's more of an expected issue, which should make it easier to debug. If it becomes msbuild-y without changing the thing we look at, we'd have the same issue as with this extension check.

An alternative could be to check for both dwproj _and_ make sure there are at least some unexpected child elements under the project element. That would probably be the most robust, but it would also lead to confusing cases with MSBuild mostly working for dwproj but not always giving proper error messages. This version seems easiest for us to debug and fix if dwproj becomes msbuild-y.

**Comment by Nirmal4G** [comment]
@Forgind What I was saying is that we could allow the pattern as a generic filter in the MSBuild source but blacklist the non-msbuild extensions in app settings so that simple change could easily fix any issues like this, instead of changing the binary.

**Comment by Forgind** [comment]
We already have logic in SolutionProjectGenerator that skips over anything that doesn't look at all like an MSBuild project; dwproj looks just enough like one that that part gets confused. The advantage of an env var approach is that it's easy to implement on our side. Using a user config is harder and seems a bit pointless, since you as the user can add (and check in) a target for your solution that removes any unwanted project types, so if the user has to do anything at all complicated, it's too much.

File: src/Build/Construction/Solution/ProjectInSolution.cs (hunk 1 above)
Comment (rainersigwald) [reply src/Build/Construction/Solution/ProjectInSolution.cs:345]: I do not understand your concern here:

> If the format for dwproj changes, and it no longer defines that namespace (or doesn't do whatever else we would do to check if it's msbuild-y), #2064 would come back unexpectedly. Of note, it would come back for a lot of people all at once.

Yes, there are future changes that could break our detection. But how is that different from today?

> If dwproj switches to being msbuild-y, we would be wrong with the check here, but that's more of an expected issue, which should make it easier to debug.

It would mean though that the owners of dwproj couldn't make forward progress without getting an MSBuild change, and at that time wouldn't the change need to be what I'm asking for here, since there would be the possibility of encountering old and new dwproj files?

> An alternative could be to check for both dwproj _and_ make sure there are at least some unexpected child elements under the project element. That would probably be the most robust, but it would also lead to confusing cases with MSBuild mostly working for dwproj but not always giving proper error messages.

I don't understand this concern, can you please elaborate?

I would be fine scoping the check to only the extension dwproj.

Comment (Forgind) [reply src/Build/Construction/Solution/ProjectInSolution.cs:345]: The two proposals here are:
1. Explicitly check for a dwproj extension
2. Check for something that indicates that this is a dwproj without checking the extension explicitly.

The two problems we want to avoid are:
1. We think something is not an MSBuild project, but it is.
2. We think something is an MSBuild project, but it is not.

If there is a future change to cause one of those problems, I want it to be as obvious as possible. "I upgrade my .dwproj to a new version that can now be built by MSBuild, whereas the previous version could not be" is a place where it's obvious the user should verify that MSBuild can handle that, whereas "I updated from schemas.microsoft.com/.../1.0 to 1.1" (with dwproj still not MSBuild-y) makes it seem like the problem is probably with the new schema, which would lead users down the wrong path.

It is true that with an explicit extension check, there is nothing the user can do to indicate to MSBuild that their dwproj is buildable. On the other hand, if we check for something optional, the user can decide not to set it, and we would be wrong again without dwproj changing anything. If we check for something required, the user can't remove it anyway, so it doesn't help.

If dwproj switches to being MSBuild-y, you are correct that we would have to have something other than the extension we can look at. However, at that point, we would have to talk with the owners to see what they are willing to commit to. Arbitrarily choosing something makes us liable to being broken. Engaging them in a discussion about it now constrains them with no added value unless they decide to make dwproj MSBuild-y. They haven't done that for years, and I see no reason to assume that's about to change.

**Comment by baronfel** [comment]
@Forgind we spoke about this after standup today. The constraints we're balancing are

* ease of implementation
* correctness of dwproj detection
* performance impact on all other MSBuild users

The solution we landed on balances these fairly well: MSBuild should skip the project if the extension is .dwproj AND the contents of the dwproj file contains a Project top-level node with Children that are not valid for MSBuild Projects. Specifically, if the children of the top-level `Project` node are any other than the ones described in [the docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/project-element-msbuild?view=vs-2022#child-elements). In this way we can prevent non-dwproj users from having any perf impact from the check, while not blocking efforts of the dwproj team to potentially msbuildify in the future. This is a bit more effort, but since we're not cramming to make this in for 17.3 we can afford to do it right.

File: src/Build/Xml/ProjectXmlUtilities.cs [hunk 2]
```diff
@@ -68,13 +78,37 @@ internal static void ThrowProjectInvalidChildElement(string name, string parentN
...
+            {
+                if (Path.GetExtension(element.Location.File).Equals(".dwproj", StringComparison.OrdinalIgnoreCase))
+                {
+                    bool validMSBuildProject = true;
+                    foreach (XmlNode child in element.ChildNodes)
+                    {
+                        if (child.Name.Equals("Database", StringComparison.OrdinalIgnoreCase))
+                        {
+                            validMSBuildProject = false;
+                            throw new UnbuildableProjectType(element.Location.File);
```
Comment (rainersigwald) [inline src/Build/Xml/ProjectXmlUtilities.cs:99]: Why throw rather than just returning `false`?

Comment (Forgind) [reply src/Build/Xml/ProjectXmlUtilities.cs:99]: Returning false just make it throw an InvalidProjectFileException without useful information that would let you diagnose it as a dwproj. This is an efficient means for skipping up to a place where we can return a useful warning without getting other, less useful errors.

**Comment by BenVillalobos** [comment]
Thoughts from PR review: I feel like the solution here can be simpler than creating a new exception type to throw. by checking further up the stack "did that fail to parse? is this a dwproj? Log an error for that!"

@forgind mentioned that passing info further up the stack would require changing a lot of function params to include some out param, which isn't great.

**Comment by Forgind** [comment]
RoslynCodeTaskFactory_Tests.InlineTaskWithAssembly failed (presumed flakily). Will watch for future flakiness.

File: src/Build/Construction/Solution/SolutionProjectGenerator.cs [hunk 3]
```diff
@@ -1086,6 +1087,7 @@ private void AddProjectReference(ProjectInstance traversalProject, ProjectInstan
                 item.SetMetadata("ToolsVersion", traversalProject.ToolsVersion);
                 item.SetMetadata("SkipNonexistentProjects", "Build"); // Instruct the MSBuild task to try to build even though the file doesn't exist on disk.
                 item.SetMetadata("AdditionalProperties", GetPropertiesMetadataForProjectReference(traversalProject, SolutionConfigurationAndPlatformProperties));
+                item.SetMetadata("BuildableProject", "False");
```
Comment (rainersigwald) [inline src/Build/Construction/Solution/SolutionProjectGenerator.cs:1090]: This doesn't look right to me. What does it do for metaprojects that are created for solution build order dependencies?

**Review by rainersigwald — APPROVED** [review]

**Review by Nirmal4G — APPROVED** [review]
I still feel like moving these kinds of tweaks to a config file (_we could use `msbuild.config` (`xml`) / `msbuild.json` as app cli config and `global.json` as user config_) but till the need for it arrives, I guess this is okay.
