### PR TITLE
Fix project configuration case-mismatch issue for solution-based graph builds

### LINKED ISSUE #9103: [Bug]: Solution-based graph builds double-build when given a project configuration with mismatched casing
When building a sln with `/p:platform=X64`, non-graph builds will normalize the platform to what's defined in the solution, eg "x64" (lower-case). Graph builds appear not to, leading to a double build:

image

On of them is from the entrypoint (`/p:platform=X64`) and the other is from the p2p (`/p:Platform=x64`).

Minimal repro: [SlnGraphBug.zip](https://github.com/dotnet/msbuild/files/12262052/SlnGraphBug.zip)

Repro command: `msbuild /bl /p:platform=X64 /graph`
Compare with the behavior of `msbuild /bl /p:platform=X64` (non-graph) and `msbuild /bl /p:Platform=x64 /graph` (matching case)

Note: using this issue for tracking. I am planning on fixing it myself.

### PR DESCRIPTION
**Pull request by dfederm**
Fixes #9103

Tested using repro from linked bug.

Only single build for Project2:
image

And it uses the normalized platform value:
image

### CODE REVIEW

File: src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs [hunk 1]
```diff
@@ -724,19 +725,9 @@ private static bool EdgeCompliesWithSolutionDependency((ConfigurationMetadata, C
 
             foreach (var node in graphFromSolution.ProjectNodes)
             {
-                // Project references get duplicated, once as entry points from the solution (handled in the if block) and once as nodes
```
Comment (dfederm) [inline src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs:727]: This comment was all wrong. Because of `AssignProjectConfigurations`, only the configuration/platform defined in the sln should be used so that each project builds exactly once.

**Review by rainersigwald — APPROVED** [review]

File: src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs (hunk 1 above)
Comment (dfederm) [reply src/Build.UnitTests/Graph/GraphLoadedFromSolution_tests.cs:727]: Seems like a reasonable assertion to add

**Review by JanKrivanek — APPROVED** [review]
