### PR TITLE
Intrinsic arithmetic function overloads

### LINKED ISSUE #8698: [Bug]: Long versions of intrinsic functions are unreachable
### Issue Description

Our arithmetic operations treat everything as a double, which means the 'long' version of our intrinsic functions are unavailable. This can induce floating point arithmetic errors, especially at large values where doubles are less precise. We should try to use long and only fall back to double if the input cannot be parsed as a long.

### Steps to Reproduce

Create a simple console app and add this target:

```XML
  <Target Name="BadSubtract">
    <Message Text="$([MSBuild]::Subtract(9223372036854775807, 9223372036854775806)) should be 1" Importance="High" />
  </Target>
```

Then make that target run.

### Expected Behavior

Outputs `1 should be 1`

### Actual Behavior

Outputs `0 should be 1`

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by jrdodds**
Fixes #8698

### Context
The [MSBuild property functions](https://learn.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#msbuild-property-functions) for Add(), Subtract(), Multiply(), Divide(), and Modulo() have overloads for `long` and `double`. The 'fast path' resolution for the functions supports the `double` versions only. Both overloads should be supported.

#### Design
The changes are focused on the 'fast path' for intrinsic functions. To determine which overload to call, the arguments are checked to see if they can be converted to a `long` or, for a `string`, parsed to a `long`. If the arguments can be `long`, the `long` overload is called. Otherwise, the `double` overload is called.

From MSBuild XML, invocation of the `double` overload can be ensured by using a real literal, e.g. `$([MSBuild]::Add(1, 0.0))` invokes the `double` overload.

With the `long` overload an overflow result that wraps is kept, e.g. `-9223372036854775808` is the result of the following function call.

```
$([MSBuild]::Add($([System.Int64]::MaxValue), 1))
```

#### Preserve Existing Behavior for `Equals` and `CompareTo`
The following two code examples currently work because `Add()` always returns a `double` but there is an issue when the `long` override is invoked.

```
$([MSBuild]::Add(1,2).CompareTo(3.0))
```

```
$([MSBuild]::Add(1,2).Equals(3.0))
```

The `Microsoft.Build.Evaluation.Expander<P, I>.Function<T>.Execute()` method has an existing special case for handling `Equals` and `CompareTo` where the type of the argument to `Equals` or `CompareTo` is converted to match the type of the 'lhs' of the comparison. `3.0` can't be converted to a `long`. To preserve the existing behavior, the argument is tested and if it is a real literal the lhs of the comparison is converted to a `double`.

In the MSBuild XML the `double` to `double` comparison can be explicit by using a real literal or by converting to double as in the following examples.

```
$([MSBuild]::Add(1,2.0).CompareTo(3.0))
```

```
$([System.Convert]::ToDouble($([MSBuild]::Add(1,2))).CompareTo(3.0))
```

#### Implementation
Modified the `Microsoft.Build.Evaluation.Expander<P, I>.Function<T>` class:
- Added `TryConvertToLong()`.
- Modified `TryConvertToInt()` and `TryConvertToDouble()`.
- Added `IsFloatingPointRepresentation()`.
- Added a set of `TryExecute*()` methods, e.g. `TryExecuteAdd()`.
- Modified `TryExecuteWellKnownFunction()` to call the appropriate `TryExecute*()` method.
- Modified `Execute()` to support existing behavior for comparisons with `Equals` and `CompareTo`.
- Modified `LateBindExecute()` to support selecting the correct overload to call.
- Added static class `IntrinsicFunctionOverload` to provide cached comparer for sorting candidate overloads.

#### Unit Tests
Modified the `Microsoft.Build.UnitTests.Evaluation.Expander_Tests` class:
- Removed a test from `PropertyFunctionStaticMethodIntrinsicMaths()` that was commented "test for overflow wrapping" but was testing for a `double` result. Overflow wrapping is covered in `PropertyFunctionMSBuildAdd()`.
- Modified `Medley()` to add some tests. The change to `Medley()` are related to the comparison behavior with `Equals` and `CompareTo`.
- Modified `PropertyFunctionMSBuildAdd()` to test `double` and `long` including integer overflow wrapping.
- Modified `PropertyFunctionMSBuildSubtract()`, `PropertyFunctionMSBuildMultiply()`, `PropertyFunctionMSBuildDivide()` to test `long` and `double`.
- Added `PropertyFunctionMSBuildModulo()`.

Added the `ExpanderFunction_Tests` unit test class.

Added the `IntrinsicFunctionOverload_Tests` unit test class.

#### PR #8853
The changes in PR 8853 to use the InvariantCulture with double.TryParse have been included in this PR as well. If this PR is accepted and merged first, then issue #8798 and PR #8853 can also be closed based on this PR. But PR #8853 is smaller and can be accepted ahead of this PR.

### Testing
Tested on Windows 11 and macOS 12.

Added new unit tests, extended existing tests, and ran all unit tests. The existing unit tests revealed the `Equals` / `CompareTo` comparison behavior.

Ran a test MSBuild XML project file. See below.

### Notes
Negates PR #8649.

### Test Project File

```xml
<!-- IntrinsicFunctionsOverload.proj -->
<Project>
  <Target Name="Testing" DependsOnTargets="Add;BadSubtract;Subtract;Multiply;Divide;Modulo;MedleyExamples" />

  <Target Name="Add">
    <!-- long -->
    <Message Text="$([MSBuild]::Add(1, 0)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Add(1, 1)) should be 2" Importance="High" />
    <Message Text="$([MSBuild]::Add(1, 2)) should be 3" Importance="High" />
    <Message Text="$([MSBuild]::Add(-1, 2)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Add($([System.Int32]::MaxValue), 1)) should be 2147483648" Importance="High" />
    <Message Text="$([MSBuild]::Add(2147483648, 1)) should be 2147483649" Importance="High" />
    <Message Text="$([MSBuild]::Add($([System.Int64]::MaxValue), 1)) should be -9223372036854775808" Importance="High" />
    <!-- double -->
    <Message Text="$([MSBuild]::Add(1, 0.0)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Add(1, 0.5)) should be 1.5" Importance="High" />
    <Message Text="$([MSBuild]::Add(1, .5)) should be 1.5" Importance="High" />
    <Message Text="$([MSBuild]::Add(-1.0, 2)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Add(1.0, 2.0)) should be 3" Importance="High" />
    <Message Text="$([MSBuild]::Add($([System.Int32]::MaxValue), 1.0)) should be 2147483648" Importance="High" />
    <!-- Int64 MaxValue is 9223372036854775807 -->
    <Message Text="$([MSBuild]::Add(9223372036854775808, 1)) should be 9.223372036854776E+18" Importance="High" />
  </Target>

  <Target Name="Test">
    <Message Text="$([MSBuild]::Add($([System.Int64]::MaxValue), 1)) should be -9223372036854775808" Importance="High" />
    <Message Text="$([MSBuild]::Add(9223372036854775808, 1)) should be 9.223372036854776E+18" Importance="High" />
    <Message Text="$([MSBuild]::Multiply($([System.Int64]::MaxValue), 2)) should be -2" Importance="High" />
    <Message Text="$([MSBuild]::Divide(65536, 10000)) should be 6" Importance="High" />
    <Message Text="$([MSBuild]::Subtract(9223372036854775807, 9223372036854775806)) should be 1" Importance="High" />
  </Target>

  <!-- From Issue #8698 -->
  <Target Name="BadSubtract">
    <Message Text="$([MSBuild]::Subtract(9223372036854775807, 9223372036854775806)) should be 1" Importance="High" />
  </Target>

  <Target Name="Subtract">
    <Message Text="$([MSBuild]::Subtract(1, 0)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Subtract(1, 1)) should be 0" Importance="High" />
    <Message Text="$([MSBuild]::Subtract(2, 1)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Subtract(1, 0.0)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Subtract(1, 0.5)) should be 0.5" Importance="High" />
    <Message Text="$([MSBuild]::Subtract(2, -1.0)) should be 3" Importance="High" />
    <Message Text="$([MSBuild]::Subtract(1.0, 2.0)) should be 3" Importance="High" />
    <Message Text="$([MSBuild]::Subtract($([System.Int64]::MaxValue), 9223372036854775806)) should be 1" Importance="High" />
  </Target>

  <Target Name="Multiply">
    <Message Text="$([MSBuild]::Multiply(1, 0)) should be 0" Importance="High" />
    <Message Text="$([MSBuild]::Multiply(1, 1)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Multiply(2, 1)) should be 2" Importance="High" />
    <Message Text="$([MSBuild]::Multiply(1, 0.0)) should be 0" Importance="High" />
    <Message Text="$([MSBuild]::Multiply(1, 0.5)) should be 0.5" Importance="High" />
    <Message Text="$([MSBuild]::Multiply(2, -1.0)) should be -2" Importance="High" />
    <Message Text="$([MSBuild]::Multiply(1.0, 2.0)) should be 2" Importance="High" />
    <Message Text="$([MSBuild]::Multiply($([System.Int64]::MaxValue), 1)) should be 9223372036854775807" Importance="High" />
    <Message Text="$([MSBuild]::Multiply($([System.Int64]::MaxValue), 2)) should be -2" Importance="High" />
  </Target>

  <Target Name="Divide">
    <Message Text="$([MSBuild]::Divide(1, 1)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Divide(9, 3)) should be 3" Importance="High" />
    <Message Text="$([MSBuild]::Divide(10, 3)) should be 3" Importance="High" />
    <Message Text="$([MSBuild]::Divide(65536, 10000)) should be 6" Importance="High" />
    <Message Text="$([MSBuild]::Divide(1, 0.5)) should be 2" Importance="High" />
    <Message Text="$([MSBuild]::Divide(10.0, 3)) should be 3.33..." Importance="High" />
  </Target>

  <Target Name="Modulo">
    <Message Text="$([MSBuild]::Modulo(1, 1)) should be 0" Importance="High" />
    <Message Text="$([MSBuild]::Modulo(9, 3)) should be 0" Importance="High" />
    <Message Text="$([MSBuild]::Modulo(9, 2)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Modulo(9, 2.0)) should be 1" Importance="High" />
    <Message Text="$([MSBuild]::Modulo(10.0, 3)) should be 1" Importance="High" />
  </Target>

  <!-- Long versus Double -->
  <Target Name="MedleyFail">
    <Message Text="$([MSBuild]::Add(1,2).CompareTo(3.0))" Importance="High" />
  </Target>

  <!-- Examples from the 'Medley' test -->
  <Target Name="MedleyExamples">
    <Message Text="$([MSBuild]::Add(1,2))" Importance="High" />
    <Message Text="$([MSBuild]::Add(1,2.0))" Importance="High" />
    <Message Text="$([MSBuild]::Add(1,2).CompareTo(3))" Importance="High" />
    <Message Text="$([MSBuild]::Add(1,2).CompareTo('3'))" Importance="High" />
    <Message Text="$([MSBuild]::Add(1,2).CompareTo(3.0))" Importance="High" />
    <Message Text="$([MSBuild]::Add(1,2.0).CompareTo(3.0))" Importance="High" />
    <Message Text="$([System.Convert]::ToDouble($([MSBuild]::Add(1,2))).CompareTo(3.0))" Importance="High" />
  </Target>
</Project>
```

### CODE REVIEW

**Comment by jrdodds** [comment]
When testing with the fast path disabled, the `LateBindExecute` method stops searching when it finds the first method that could support the argument types and it finds the `double` versions of the arithmetic functions first.

Example:
```
$([MSBuild]::Add($([System.Int64]::MaxValue), 1))
```
produces a result of 9.22337203685478E+18 instead of the expected -9223372036854775808.

I'll make a change to `LateBindExecute` to choose methods with types that match over types that can be coerced.

I'll make the ChangeWave cover integer versus real for addition, subtraction, multiplication, and division.

(I also need to add tests for multiplication overflow.)

**Comment by Forgind** [comment]
> When testing with the fast path disabled, the LateBindExecute method stops searching when it finds the first method that could support the argument types and it finds the double versions of the arithmetic functions first.

This was a bit surprising to me, but I can see why it would do that. Rather than any overly complicated logic, can we just reorder the Add methods, for instance, such that it tries to coerce the arguments to integers, then longs, then doubles? I'm trying to minimize the impact of the change while still getting the desired outcome.

**Comment by jrdodds** [comment]
Yes, the methods in the `IntrinsicFunctions` class could be re-ordered. I wasn't keen on doing that. Having functionality depend on the order of the methods in the source code seems brittle. It would need to be well commented or else it could be a very mysterious 'gotcha'. But more importantly there is a non-trivial behavior change that probably should be in a change wave. For the change wave mechanism, there needs to be a way to switch at runtime between the two behaviors.

**Comment by jrdodds** [comment]
The changes are using change wave 17.8 as a placeholder pending discussion.

File: src/Build/Evaluation/Expander.cs [hunk 1]
```diff
@@ -4677,6 +4694,143 @@ private static bool TryGetArgs(object[] args, out string arg0, out int arg1)
...
+                        return true;
+                    }
+                }
+                else if (TryConvertToLong(args[0], out long arg0) && TryConvertToLong(args[1], out long arg1))
+                {
+                    resultValue = IntrinsicFunctions.Add(arg0, arg1);
+                    return true;
+                }
+
+                return false;
```
Comment (JanKrivanek) [inline src/Build/Evaluation/Expander.cs:4727]: I have two asks for this code:

1) can we extract this to prevent repetition?

2) This code doesn't grace handle large integers (no decimals, valua above long max) - e.g. "12345678901234567890123456". How about first trying to convert to long, and fallback to double if that is not possible?

File: src/Build/Evaluation/Expander.cs [hunk 2]
```diff
@@ -4677,6 +4694,143 @@ private static bool TryGetArgs(object[] args, out string arg0, out int arg1)
                 return false;
             }
 
+            private static bool IsFloatingPointRepresentation(object value)
+            {
+                const char numberDecimalSeparator = '.';
```
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs:4699]: I had a question about that myself.

File: src/Build/Evaluation/Expander.cs (hunk 1 above)
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs:4727]: There is a lot of repetition in the handling of the intrinsic functions and there is an idea that has been floated that there should be a code generator for it.

Yes, the `TryExecute[Add|Subtract|Multiply|Divide|Modulo]` methods don't handle large integers and they don't handle mixed arguments of `long` and `double` but both cases are handled elsewhere in the code.

The methods could be changed to extend the `if ... else if ...` to try `double` when `long` fails. Simplifying the code to try `long` first and falling back to `double` imposes a cost on using a `double`. The `IsFloatingPointRepresentation()` method is intended to be a quick test without attempting a full parse.

File: src/Build.UnitTests/Evaluation/Expander_Tests.cs [hunk 3]
```diff
@@ -3394,12 +3396,6 @@ public void PropertyFunctionStaticMethodIntrinsicMaths()
             result = expander.ExpandIntoStringLeaveEscaped(@"$([MSBuild]::Modulo(2345.5, 43))", ExpanderOptions.ExpandProperties, MockElementLocation.Instance);
 
             Assert.Equal((2345.5 % 43).ToString(), result);
-
-            // test for overflow wrapping
-            result = expander.ExpandIntoStringLeaveEscaped(@"$([MSBuild]::Add(9223372036854775807, 20))", ExpanderOptions.ExpandProperties, MockElementLocation.Instance);
-
-            double expectedResult = 9223372036854775807D + 20D;
-            Assert.Equal(expectedResult.ToString(), result);
```
Comment (JanKrivanek) [inline src/Build.UnitTests/Evaluation/Expander_Tests.cs:3402]: FYI @ghogen - if this get's approved and merged in the current proposed functionality, we should probably explicitly document this here https://learn.microsoft.com/en-us/visualstudio/msbuild/property-functions#msbuild-property-functions, with advice to indicate double literal if scale over precision is preferred (as this is now prioritizing precision over scale, by respecting integer literals as longs)

File: src/Build/Evaluation/Expander.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (JanKrivanek) [reply src/Build/Evaluation/Expander.cs:4699]: This is good point. I suppose MSBuild script is treated invariant - but rather summoning @rainersigwald to confirm here.

File: src/Build.UnitTests/Evaluation/Expander_Tests.cs [hunk 4]
```diff
@@ -4176,39 +4180,109 @@ public void PropertyFunctionMathMin()
...
+        }
+
+        [Fact]
+        public void PropertyFunctionMSBuildAddIntegerOverflow()
+        {
+            // Overflow wrapping - result exceeds size of long
+            string expected = IsIntrinsicFunctionOverloadsEnabled ? "-9223372036854775808" : (long.MaxValue + 1.0).ToString();
+            TestPropertyFunction("$([MSBuild]::Add($(X), 1))", "X", long.MaxValue.ToString(), expected);
+        }
+
```
Comment (JanKrivanek) [inline src/Build.UnitTests/Evaluation/Expander_Tests.cs:4201]: We should add an explicit unit tests that uses an argument that is an integer value below and over the bounds.

File: src/Build/Evaluation/Expander.cs (hunk 1 above)
Comment (JanKrivanek) [reply src/Build/Evaluation/Expander.cs]: Thanks for the current extraction of the common code!
As for handling large integers - this is fine now as well, I'd just like to see an explicit unit test for that (to prevent future breaks)

**Review by JanKrivanek — CHANGES_REQUESTED** [review]
This mostly looks good to me. Thanks for the improvements iterations on this!

I'd only like to see the handling of attempts of large doubles to long conversions and explicit unit test(s) for integer literals outside long bounds. Then I'm ready to sign off

File: src/Build/Evaluation/Expander.cs [hunk 5]
```diff
@@ -4677,6 +4694,40 @@ private static bool TryGetArgs(object[] args, out string arg0, out int arg1)
...
+                if (args.Length != 2)
+                {
+                    return false;
+                }
+
+                if (IsIntrinsicFunctionOverloadsEnabled() && !IsFloatingPointRepresentation(args[0]) && !IsFloatingPointRepresentation(args[1]))
+                {
+                    if (TryConvertToLong(args[0], out long argLong0) && TryConvertToLong(args[1], out long argLong1))
+                    {
+                        resultValue = integerOperation(argLong0, argLong1);
```
Comment (Forgind) [inline src/Build/Evaluation/Expander.cs:4717]: Your comment that even without the fast path, we were still only doing double arithmetic made me think hard about problems like this. Specifically, what is the "right" behavior when we would overflow post-operation? So like what is the correct value for Long.MaxValue + 1?

I'm wondering whether it's a better design to prioritize long arithmetic, as we suggest we do in the docs, and say Long.MaxValue + 1 = Long.MinValue or quietly convert it to a double before doing the operation. Sorry if that was already discussed, and I missed it.

File: src/Build/Evaluation/Expander.cs [hunk 6]
```diff
@@ -4534,6 +4533,24 @@ private static bool TryConvertToInt(object value, out int arg0)
                 return false;
             }
 
+            private static bool TryConvertToLong(object value, out long arg0)
+            {
+                switch (value)
+                {
+                    case double d:
+                        arg0 = Convert.ToInt64(d);
```
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs]: Added the min/max check to both TryConvertToLong and TryConvertToInt.

TryConvertToLong  is only used by the arithmetic overloads.

TryConvertToInt is used in many places and the change to add the min/max check is a separate commit in case it needs to be rolled back.

File: src/Build/Evaluation/Expander.cs (hunk 5 above)
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs:4727]: I suspect that converting to `double` on overflow would be adding a feature that may never be used in the field. I expect there is very little arithmetic performed in MSBuild and that most or nearly all of the arithmetic is with integer values that are well within the min and max values of `long`.

Comment (JanKrivanek) [reply src/Build/Evaluation/Expander.cs:4727]: Since there is a workaround for this edge case (explicitly define any operand as double), I'm fine with the behavior. It just should bee properly documented

**Comment by jrdodds** [comment]
@JanKrivanek Was there feedback on the decimal separator?

**Review by ladipro — COMMENTED** [review]
Looks good overall. I've Added a few comments inline.

File: src/Build/Evaluation/Expander.cs [hunk 7]
```diff
@@ -4534,6 +4538,29 @@ private static bool TryConvertToInt(object value, out int arg0)
...
             }
 
+            private static bool TryConvertToLong(object value, out long arg0)
+            {
+                switch (value)
+                {
+                    case double d:
+                        if (d >= long.MinValue && d <= long.MaxValue)
+                        {
+                            arg0 = Convert.ToInt64(d);
```
Comment (JanKrivanek) [inline src/Build/Evaluation/Expander.cs:4548]: Convert will throw for `Convert.ToInt64((double)long.MaxValue)` (credit to @rokonec for discovering this)

Please use `long.CreateTruncating(d)` instead - as it grace handles those boundaries.
Same for the Int32 above.

Comment (JanKrivanek) [reply src/Build/Evaluation/Expander.cs:4548]: Or reuse the code from runtime - so that it works for fullFW as well:

```
arg0 = (d >= long.MaxValue) ? long.MaxValue : (d <= long.MinValue) ? long.MinValue : (long)d;
```

File: src/Build/Evaluation/Expander.cs [hunk 8]
```diff
@@ -4677,6 +4704,40 @@ private static bool TryGetArgs(object[] args, out string arg0, out int arg1)
                 return false;
             }
 
+            private static bool IsFloatingPointRepresentation(object value)
+            {
+                const char numberDecimalSeparator = '.';
+
+                return value is double || (value is string str && str.Contains(numberDecimalSeparator));
```
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs:4711]: `long.TryParse` would always be attempted first and values that are `double` will always have the overhead of trying to parse twice. I was under the impression that parsing twice for `double` would be an issue from a performance perspective. But I think that was probably a premature optimization. The `double` overloads are used much less than the `long` overloads.

The `IsFloatingPointRepresentation` method is not intended to be 'air tight' and a false negative is not an issue in terms of behavior. But in terms of code maintenance, that's an easily missed nuance.

I agree that it would be better to eliminate the `IsFloatingPointRepresentation` method.

File: src/Build/Evaluation/Expander.cs (hunk 7 above)
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs:4548]: The two functions should not throw but also should return false instead of truncating when a `double` can't be narrowed.

File: src/Build/Evaluation/Expander.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (JanKrivanek) [reply src/Build/Evaluation/Expander.cs:4711]: Perf and maintainability is a delicate balance. I wish we had a magic formula to decide :-)
There was a consensus on the advice from @ladipro

File: src/Build/Evaluation/Expander.cs (hunk 7 above)
Comment (JanKrivanek) [reply src/Build/Evaluation/Expander.cs:4548]: They should not (would `Convert` behave to its specification), but unfortunately they do...

```csharp
	try
	{
		TryConvertToLong((double)long.MaxValue, out _);
	}
	catch(OverflowException)
	{
		Console.WriteLine("This should never happen!! Or it might? ;-) ...");
	}
```

Btw. we should add a test that exercise that (then add the fixing check for boundary values). Extracting + exposing functions for easier testability is fine.

File: src/Build/Evaluation/Expander.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (danmoseley) [reply src/Build/Evaluation/Expander.cs:4711]: on the core libraries level we continue to make TryParse faster. I do not think it is possible to do better and still have correctness. I think it is usually best to defer to the libraries and open perf bugs against them if necessary 😄

File: src/Build/Evaluation/Expander.cs (hunk 7 above)
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs:4548]: > Convert will throw for Convert.ToInt64((double)long.MaxValue) (credit to @rokonec for discovering this)

The above quote may have been simplifying but `Convert.ToInt64(double)` will throw an OverflowException for values >= (long.MaxValue - 511) and <= long.MaxValue.

Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs]: New commit for unit tests and changes to TryConvertToInt, TryConvertToLong, TryConvertToDouble functions.

File: src/Build/Evaluation/Expander.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs]: new commit to make changes to use TryParse

File: src/Build/Evaluation/Expander.cs [hunk 9]
```diff
@@ -3463,21 +3463,25 @@ internal object Execute(object objectInstance, IPropertyProvider<T> properties,
...
+                        {
+                            objectInstance = Convert.ChangeType(objectInstance, typeof(double), CultureInfo.InvariantCulture);
+                            _receiverType = objectInstance.GetType();
+                        }
+
                         // change the type of the final unescaped string into the destination
                         args[0] = Convert.ChangeType(args[0], objectInstance.GetType(), CultureInfo.InvariantCulture);
                     }
 
                     if (_receiverType == typeof(IntrinsicFunctions))
```
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs:3477]: marking as resolved because out of scope for this PR but agree that Expander needs to be factored

File: src/Build/Evaluation/Expander.cs [hunk 10]
```diff
@@ -5211,15 +5281,26 @@ private object LateBindExecute(Exception ex, BindingFlags bindingFlags, object o
...
+                        members = _receiverType.GetMethods(bindingFlags).Where(m => string.Equals(m.Name, _methodMethodName, StringComparison.OrdinalIgnoreCase));
+
+                        if (_receiverType == typeof(IntrinsicFunctions))
+                        {
+                            // Order by the TypeCode of the first parameter.
+                            // When change wave is enabled, order long before double.
+                            // Otherwise preserve prior behavior of double before long.
+                            IComparer<TypeCode> comparer = IsIntrinsicFunctionOverloadsEnabled()
+                                ? Comparer<TypeCode>.Create((key0, key1) => key0.CompareTo(key1))
+                                : Comparer<TypeCode>.Create((key0, key1) => key1.CompareTo(key0));
```
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs]: new commit 158e6e6 to cache to the comparer

File: src/Build/Evaluation/Expander.cs [hunk 11]
```diff
@@ -5211,15 +5281,26 @@ private object LateBindExecute(Exception ex, BindingFlags bindingFlags, object o
...
+                            members = members.OrderBy(SelectTypeOfFirstParameter, comparer);
```
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs]: new commit f2cb002 to use `Type.FindMembers` and `Array.Sort`

**Comment by jrdodds** [comment]
New commits to address #8798 within the scope of this work - i.e. code touched or changed by this PR now uses a different overload of `double.Parse`:

```csharp
double.TryParse(str, NumberStyles.Number | NumberStyles.Float, CultureInfo.InvariantCulture.NumberFormat, out arg)
```

This may not close #8798. The issue could be in other places.

**Review by ladipro — COMMENTED** [review]
Apologies for the delay, the changes look great. I've added one question inline. Also, when you get a chance, can you please update the description - I believe that some parts got out of sync with the change.

**Comment by jrdodds** [comment]
The description has been updated.

File: src/Build/Evaluation/Expander.cs [hunk 12]
```diff
@@ -4516,40 +4515,99 @@ private static bool TryConvertToVersion(object value, out Version arg0)
...
                     case double d:
-                        arg0 = Convert.ToInt32(d);
-                        return arg0 == d;
+                        if (d >= int.MinValue && d <= int.MaxValue)
+                        {
+                            arg = Convert.ToInt32(d);
+                            if (Math.Abs(arg - d) == 0)
+                            {
+                                return true;
+                            }
```
[the remark this answers is not in the document]
Comment (ladipro) [reply src/Build/Evaluation/Expander.cs:4532]: Ah, sorry, I remember now. This looks non-obvious enough to deserve a code comment. Not blocking, only if you end up making other changes.

**Review by ladipro — APPROVED** [review]

File: src/Build/Evaluation/Expander.cs (hunk 12 above)
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Build/Evaluation/Expander.cs:4532]: Good point. I'll add a comment if I make other changes. Thanks.
