### PR TITLE
Fix RequestCores/ReleaseCores fallback in OOP TaskHost: throw NotImplementedException instead of logging error

### LINKED ISSUE #13333: [NETSDKE2E][Regression] With 11.0.0-preview. 2.26154.117 sdk installed, publishing Blazor WebAssembly App failed after installing wasm-tools.
### REGRESSION INFO
Worked well on 11.0.100-preview.2.26122.107

### INSTALL STEPS
Install latest NET11 P2 SDK: 11.0.100-preview.2.26154.117 on clean machine

### REPRO STEPS
1. Run `dotnet workload install wasm-tools`
2. Create a new blazorwasm app by run `dotnet new blazorwasm`
3. Run `dotnet publish`

### ACTUAL
Publishing failed
Image

Image

### Expected
Publishing works well.

### Note
Blazorwasm app can be published successfully without install wasm-tools.

dotnet --info
.NET SDK:
 Version:           11.0.100-preview.2.26154.117
 Commit:            6dbf4ee311
 Workload version:  11.0.100-preview.2.26155.13
 MSBuild version:   18.6.0-preview-26154-117+6dbf4ee31

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26200
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\11.0.100-preview.2.26154.117\

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.

Host:
  Version:      11.0.0-preview.2.26154.117
  Architecture: x64
  Commit:       6dbf4ee311

.NET SDKs installed:
  11.0.100-preview.2.26154.117 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 11.0.0-preview.2.26154.117 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 11.0.0-preview.2.26154.117 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 11.0.0-preview.2.26154.117 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### PR DESCRIPTION
**Pull request by JanProvaznik**
### Context

Fixes #13333

PR #13306 added RequestCores/ReleaseCores IPC callback support to OutOfProcTaskHostNode, correctly gating the new callback path behind CallbacksSupported. However, it also changed the **fallback behavior** (when callbacks are not supported) from 	hrow NotImplementedException() to LogErrorFromResource() + return 0.

This broke all callers. All known consumers (MonoAOTCompiler, EmccCompile, ILStrip, EmitBundleBase in dotnet/runtime) use this pattern:

```csharp
try {
    allowedParallelism = be9.RequestCores(N);
} catch (NotImplementedException) {
    be9 = null; // fall back to own parallelism estimate
}
// ...
finally { be9?.ReleaseCores(allowedParallelism); }
```

After #13306, no exception is thrown, so the \catch\ block never fires. Instead:
1. **\LogErrorFromResource\** silently pushes a \BuildErrorEventArgs\ — the build is doomed to fail and the task can't prevent it
2. **\
eturn 0\** violates the API contract (\RequestCores\ guarantees return ∈ [1, requestedCores])

### Changes Made

**\OutOfProcTaskHostNode.cs\**: Restore \	hrow NotImplementedException()\ in both \RequestCores\ and \ReleaseCores\ fallback paths (CLR2 and \!CallbacksSupported\). This preserves the pre-#13306 behavior until the packet version is bumped to enable callbacks.

**\TaskHostTask.cs\**: Default \grantedCores\ to \1\ (not \

### CODE REVIEW

File: src/MSBuild/OutOfProcTaskHostNode.cs [hunk 1]
```diff
@@ -565,15 +565,17 @@ public IReadOnlyDictionary<string, string> GetGlobalProperties()
         public int RequestCores(int requestedCores)
         {
 #if CLR2COMPATIBILITY
-            LogErrorFromResource("BuildEngineCallbacksInTaskHostUnsupported");
-            return 0;
+            // CLR2 task host doesn't support resource management.
+            // Callers catch NotImplementedException and fall back to their own parallelism estimate.
```
Comment (rainersigwald) [inline src/MSBuild/OutOfProcTaskHostNode.cs]: There's no CLR2 caller that calls this API. Update the comment to avoid implying that there is.
```suggestion
            // If they somehow get here, throw.
```

**Comment by rainersigwald** [comment]
fyi @lewing, this should be the durable fix for p3.
