### PR TITLE
Fix vs tools path error when condition is false

### LINKED ISSUE #8167: Failure to import from $(VSToolsPath) in 17.5
Errors like

```
MSB4226 The imported project "$(VSToolsPath)\TeamTest\Microsoft.TestTools.targets" was not found. Also, tried to find "$(VSToolsPath)\TeamTest\Microsoft.TestTools.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v17.0" . Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
```

```
The imported project "$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" was not found. Also, tried to find "$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v17.0" . These search paths are defined in "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\MSBuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
```

### LINKED ISSUE #8168: Conditional imports including VSToolsPath will throw an exception even if the condition is false
### Issue Description
See title. This has hit multiple internal customers.

### Steps to Reproduce
```
<Project>
  <Import Project="$(VSToolsPath)\Foo.targets" Condition="Exists('$(VSToolsPath)\Foo.targets')" />
  <Target Name="Build" />
</Project>
```

### Expected Behavior
No error

### Actual Behavior
`MSB4226 The imported project "$(VSToolsPath)\Foo.targets" was not found. Also, tried to find "$(VSToolsPath)\Foo.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v17.0" . Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.`

### Analysis
This error was added in #8095, but it should respect conditions.

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #8167 and Fixes #8168

### Context
The VS tools path "directory does not exist" error check did not take into account a condition on the import element. This resolves that issue.

### Changes Made
Move the condition check earlier and have it suppress the error.

### Testing
Manual testing with repro from #8168.

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]

File: src/Build.UnitTests/Evaluation/Evaluator_Tests.cs [hunk 1]
```diff
@@ -50,6 +50,62 @@ public void Dispose()
...
+
+                yield return new object[] { $@"Project=""{Path.Combine("realFolder", "projectThatDoesNotExist.csproj")}"" Condition=""Exists('{Path.Combine("realFolder", "projectThatDoesNotExist.csproj")}')""", true };
+                yield return new object[] { $@"Project=""{Path.Combine("realFolder", "projectThatDoesNotExist.csproj")}"" Condition=""'true'""", false };
+                yield return new object[] { $@"Project=""{Path.Combine("realFolder", "projectThatDoesNotExist.csproj")}""", false };
+                yield return new object[] { $@"Project=""{Path.Combine("realFolder", "*.*proj")}""", true };
+
+                yield return new object[] { $@"Project=""{Path.Combine("realFolder", "realFile.csproj")}"" Condition=""Exists('{Path.Combine("realFolder", "realFile.csproj")}')""", true };
+                yield return new object[] { $@"Project=""{Path.Combine("realFolder", "realFile.csproj")}"" Condition=""'true'""", true };
+                yield return new object[] { $@"Project=""{Path.Combine("realFolder", "realFile.csproj")}""", true };
+                yield return new object[] { $@"Project=""{Path.Combine("realFolder", "*.*proj")}""", true };
```
Comment (rainersigwald) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs:99]: Was there no test coverage for these non-fallback scenarios before?

File: src/Build.UnitTests/Evaluation/Evaluator_Tests.cs [hunk 2]
```diff
@@ -50,6 +50,62 @@ public void Dispose()
...
+
+                yield return new object[] { $@"Project=""{Path.Combine("$(VSToolsPath)", "nonexistentDirectory", "projectThatDoesNotExist.csproj")}"" Condition=""'false'""", true };
```
Comment (rainersigwald) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs:101]: Comment to explain why VSToolsPath is special and worth testing explicitly here, please.

Comment (rainersigwald) [inline src/Build.UnitTests/Evaluation/Evaluator_Tests.cs:101]: Worth the same thing but with an exists check instead of just hardcoded false?

File: src/Build/Evaluation/Evaluator.cs [hunk 3]
```diff
@@ -1651,15 +1652,17 @@ private List<ProjectRootElement> ExpandAndLoadImports(string directoryOfImportin
...
+                if (!EvaluateConditionCollectingConditionedProperties(importElement, newExpandedCondition, ExpanderOptions.ExpandProperties, ParserOptions.AllowProperties,
+                            _projectRootElementCache))
                 {
                     continue;
                 }
 
-                var newExpandedCondition = importElement.Condition.Replace(extensionPropertyRefAsString, extensionPathExpanded, StringComparison.OrdinalIgnoreCase);
-                if (!EvaluateConditionCollectingConditionedProperties(importElement, newExpandedCondition, ExpanderOptions.ExpandProperties, ParserOptions.AllowProperties,
-                            _projectRootElementCache))
+                if (!_fallbackSearchPathsCache.DirectoryExists(extensionPathExpanded))
```
Comment (rainersigwald) [inline src/Build/Evaluation/Evaluator.cs:1662]: I have had to read this and the old version . . . too many times . . . to get to this understanding so I think a comment here would be helpful:

```suggestion
                // If the whole fallback folder doesn't exist, short-circuit and don't
                // bother constructing an exact file path.
                if (!_fallbackSearchPathsCache.DirectoryExists(extensionPathExpanded))
```

**Review by rainersigwald — APPROVED** [review]

File: src/Build.UnitTests/Evaluation/Evaluator_Tests.cs (hunk 1 above)
Comment (Forgind) [reply src/Build.UnitTests/Evaluation/Evaluator_Tests.cs:99]: I haven't checked for every one of these scenarios, but I checked for a few, and they weren't there. (Like my first attempt at introducing the error did pass CI but included undesirable behavior.)

Comment (Forgind) [reply src/Build.UnitTests/Evaluation/Evaluator_Tests.cs:99]: I'll check a couple others now; if some are duplicates, that doesn't bother me too much.

Comment (Forgind) [reply src/Build.UnitTests/Evaluation/Evaluator_Tests.cs:99]: Ok, so some of them are definitely duplicates of things tested elsewhere, and some are new. Some are also only relevant to constraining the error to the relevant scenario. Do you want me to try to figure out which we don't need, or are you ok with some extras?
