### PR TITLE
Fix lock contention in ProjectRootElementCache.Get

### LINKED ISSUE #3039: Perf: potential lock contention in ProjectRootElementCache.Get
When we look into performance traces of parallel project loading work, we noticed some lock contentions in ProjectRootElementCache.Get method.  In one trace we noticed it was blocked 60ms.

The code is using a single lock to control to access the cache, and also read file into XmlDocument, when it does not exist.  The later one can be slow on a slow disk.  When PPL is enabled, multiple projects are evaluated, and this becomes more a problem. 

If the code can pull out the logic to load a project file out of the lock region, it will allow other threads to access the cache for other files in the same project collection.

### PR DESCRIPTION
**Pull request by AR-May**
Fixes #3039

### Context
There is significant amount of lock contentions in ProjectRootElementCache.Get method. 
(For OrchardCore project, for example, the total time spent waiting to take a lock ~1sec.)
Reason: the code is using a single lock to control to access the cache, and also read file into XmlDocument, when it does not exist. The later one can be slow on a slow disk.

### Changes Made
The ProjectRootElementCache.Get function is rewritten to exclude IO operations from the locked sections.
For this goal we also had to separate logic of loading from logic of adding the element to the cache.

### Testing
Unit tests + manual testing.

### CODE REVIEW

File: src/Build/Evaluation/ProjectRootElementCache.cs [hunk 1]
```diff
@@ -131,15 +131,69 @@ internal ProjectRootElementCache(bool autoReloadFromDisk, bool loadProjectsReadO
...
+                        {
+                            // QA tests run too fast for the timestamp check to work. This environment variable is for their
+                            // use: it checks the file content as well as the timestamp. That's better than completely disabling
+                            // the cache as we get test coverage of the rest of the cache code.
+                            XmlDocument document = new XmlDocument();
+                            document.PreserveWhitespace = projectRootElement.XmlDocument.PreserveWhitespace;
+
+                            using (var xtr = XmlReaderExtension.Create(projectRootElement.FullPath, projectRootElement.ProjectRootElementCache.LoadProjectsReadOnly))
+                            {
+                                document.Load(xtr.Reader);
```
Comment (rainersigwald) [inline src/Build/Evaluation/ProjectRootElementCache.cs:170]: This is inside the lock, right? Is that ok since it's a "test-only" codepath, or can this be avoided too?

File: src/Build/Evaluation/ProjectRootElementCache.cs [hunk 2]
```diff
@@ -158,91 +212,91 @@ internal ProjectRootElementCache(bool autoReloadFromDisk, bool loadProjectsReadO
...
+            }
 
-                if (projectRootElement == null && openProjectRootElement != null)
-                {
-                    projectRootElement = openProjectRootElement(projectFile, this);
+            // Use openProjectRootElement to reload the element if the cache element does not exist or need to be reloaded.
+            if (projectRootElement == null || projectRootElementIsInvalid)
+            {
+                // We do not lock loading with common _locker of the cache, to avoid lock contention.
+                // Decided also not to lock this section with the key specific locker to avoid the overhead and code overcomplification, as
```
Comment (rainersigwald) [inline src/Build/Evaluation/ProjectRootElementCache.cs:271]:
```suggestion
                // Decided also not to lock this section with the key specific locker to avoid the overhead and code overcomplication, as
```

**Review by rainersigwald — APPROVED** [review]

File: src/Build/Evaluation/ProjectRootElementCache.cs (hunk 1 above)
Comment (rokonec) [reply src/Build/Evaluation/ProjectRootElementCache.cs:170]: Since it is really used only in QA tests we haven't give it much thinking as for optimization. Shall we?

Comment (rokonec) [reply src/Build/Evaluation/ProjectRootElementCache.cs:170]: This section is thread safe and the lock could be omitted here. This could result in multiple tests concurrently loading project XML in readonly fashion. This shall be OK and we should consider it. Worst could happen some test fails or become flaky in which situation we can put the lock back. What do you think @AR-May ?

File: src/Build/Evaluation/SimpleProjectRootElementCache.cs [hunk 3]
```diff
@@ -63,6 +63,9 @@ private ProjectRootElement GetFromOrAddToCache(string projectFile, OpenProjectRo
                 ErrorUtilities.VerifyThrowInternalNull(rootElement, "projectRootElement");
                 ErrorUtilities.VerifyThrow(rootElement.FullPath.Equals(key, StringComparison.OrdinalIgnoreCase),
                     "Got project back with incorrect path");
+
+                AddEntry(rootElement);
+
                 ErrorUtilities.VerifyThrow(_cache.TryGetValue(key, out _),
                     "Open should have renamed into cache and boosted");
```
Comment (rokonec) [inline src/Build/Evaluation/SimpleProjectRootElementCache.cs:70]: This message is now outdated. I'd recommend something like "ProjectRootElement should have been added into cache"

**Review by rokonec — APPROVED** [review]

File: src/Build/Evaluation/ProjectRootElementCache.cs (hunk 1 above)
Comment (AR-May) [reply src/Build/Evaluation/ProjectRootElementCache.cs:170]: Yes, I think we can try to unlock this section, I suppose.

**Comment by AR-May** [comment]
Experimental insertion in VS showed problems with these changes. Converting this PR to draft while I investigate and fix.

File: src/Build/Evaluation/ProjectRootElementCache.cs (hunk 1 above)
Comment (rainersigwald) [reply src/Build/Evaluation/ProjectRootElementCache.cs:170]: If it's test only I think a bit of lock contention is fine to save development effort. Just wanted to make sure that was the case.

**Comment by AR-May** [comment]
Ready for review now, the errors does not seem to be related to the changes after investigation.

File: src/Build/Evaluation/SimpleProjectRootElementCache.cs [hunk 4]
```diff
@@ -63,8 +63,11 @@ private ProjectRootElement GetFromOrAddToCache(string projectFile, OpenProjectRo
                 ErrorUtilities.VerifyThrowInternalNull(rootElement, "projectRootElement");
                 ErrorUtilities.VerifyThrow(rootElement.FullPath.Equals(key, StringComparison.OrdinalIgnoreCase),
                     "Got project back with incorrect path");
+
+                AddEntry(rootElement);
```
Comment (ladipro) [inline src/Build/Evaluation/SimpleProjectRootElementCache.cs:67]: May I ask you to explain this statement? We're inside the `GetOrAdd` callback so `rootElement` will be added to the cache with the key of `projectFile`. Why are we calling another add?

File: src/Build/Evaluation/ProjectRootElementCache.cs [hunk 5]
```diff
@@ -158,91 +209,91 @@ internal ProjectRootElementCache(bool autoReloadFromDisk, bool loadProjectsReadO
...
+                }
+                else
+                {
+                    DebugTraceCache("Not found in cache: ", projectFile);
+                }
+
                 if (preserveFormatting != null && projectRootElement != null && projectRootElement.XmlDocument.PreserveWhitespace != preserveFormatting)
                 {
                     //  Cached project doesn't match preserveFormatting setting, so reload it
                     projectRootElement.Reload(true, preserveFormatting);
```
Comment (ladipro) [inline src/Build/Evaluation/ProjectRootElementCache.cs:235]: We're still loading XML under the lock here. Intentional?

File: src/Build/Evaluation/ProjectRootElementCache.cs [hunk 6]
```diff
@@ -158,91 +209,91 @@ internal ProjectRootElementCache(bool autoReloadFromDisk, bool loadProjectsReadO
...
-                    ErrorUtilities.VerifyThrowInternalNull(projectRootElement, "projectRootElement");
-                    ErrorUtilities.VerifyThrow(projectRootElement.FullPath == projectFile, "Got project back with incorrect path");
-                    ErrorUtilities.VerifyThrow(_weakCache.Contains(projectFile), "Open should have renamed into cache and boosted");
-                }
-                else if (projectRootElement != null)
-                {
-                    DebugTraceCache("Satisfied from XML cache: ", projectFile);
-                    BoostEntryInStrongCache(projectRootElement);
-                }
+                ProjectRootElement newProjectRootElement = openProjectRootElement(projectFile, this);
```
Comment (ladipro) [inline src/Build/Evaluation/ProjectRootElementCache.cs:271]: nit: You could assign to `projectRootElement` here, the new local is not needed.

File: src/Build/Evaluation/ProjectRootElementCache.cs [hunk 7]
```diff
@@ -158,91 +209,91 @@ internal ProjectRootElementCache(bool autoReloadFromDisk, bool loadProjectsReadO
...
-                return projectRootElement;
+                lock (_locker)
+                {
+                    // Update cache element.
+                    // It is unlikely, but it might be that while without the lock, the projectRootElement in cache was updated by another thread.
+                    // And here its entry will be replaced with newProjectRootElement. This is fine:
+                    // if newProjectRootElement is out of date (so, it changed since the time we loaded it), it will be updated the next time some thread calls Get function.
+                    AddEntry(newProjectRootElement);
+                    projectRootElement = newProjectRootElement;
+                }
```
Comment (ladipro) [inline src/Build/Evaluation/ProjectRootElementCache.cs:289]: nit: `projectRootElement = newProjectRootElement` doesn't have to run under the lock and `AddEntry` takes the lock internally, so this can be simplified to only call `AddEntry`.

File: src/Build/Evaluation/ProjectRootElementCache.cs [hunk 8]
```diff
@@ -131,15 +131,66 @@ internal ProjectRootElementCache(bool autoReloadFromDisk, bool loadProjectsReadO
...
+                    {
+                        // File was changed on disk by external means. Cached version is no longer valid.
+                        // We could throw here or ignore the problem, but it is a common and reasonable pattern to change a file
+                        // externally and load a new project over it to see the new content. So we dump it from the cache
+                        // to force a load from disk. There might then exist more than one ProjectRootElement with the same path,
+                        // but clients ought not get themselves into such a state - and unless they save them to disk,
+                        // it may not be a problem.
+                        return true;
+                    }
+                    else if (!String.IsNullOrEmpty(Environment.GetEnvironmentVariable("MSBUILDCACHECHECKFILECONTENT")))
```
Comment (ladipro) [inline src/Build/Evaluation/ProjectRootElementCache.cs:158]: nit: This environment variable check may be worth caching. Looking at the tests using it, it's unlikely they set it after this code has run.

File: src/Build/Evaluation/ProjectRootElementCache.cs [hunk 9]
```diff
@@ -158,91 +209,91 @@ internal ProjectRootElementCache(bool autoReloadFromDisk, bool loadProjectsReadO
...
-
-                            DebugTraceCache("Out of date dropped from XML cache: ", projectFile);
-                            projectRootElement = null;
-                        }
+                        return null;
+                    }
+                    else
+                    {
+                        DebugTraceCache("Satisfied from XML cache: ", projectFile);
+                        return projectRootElement;
```
Comment (ladipro) [inline src/Build/Evaluation/ProjectRootElementCache.cs:259]: nit: Only `ForgetEntryIfExists` needs to run under the lock, the rest of the statements do not. They are trivial or debug-only so it's a readability rather than perf suggestion. Since this is the only place calling `ForgetEntryIfExists`, you could also move the locking there or inline the method here. No strong opinion, though.

File: src/Build/Evaluation/ProjectRootElementCache.cs (hunk 5 above)
Comment (AR-May) [reply src/Build/Evaluation/ProjectRootElementCache.cs:235]: Yes, intentional. 
This if section fixes a rare bug, and this code path uses it's own code for reloading. 
To refactor it such that we can divide the actual download and updating the element of the cache which has to be under the lock is not worth it, so we decided.

File: src/Build/Evaluation/SimpleProjectRootElementCache.cs (hunk 4 above)
Comment (AR-May) [reply src/Build/Evaluation/SimpleProjectRootElementCache.cs:67]: Yes, I removed AddEntry from the end of all the open functions in order to divide downloading and adding to the cache code. So, now everywhere else where I used open functions, I now need to do AddEntry exactly afterwards, so that behavior is exactly the same as before.
Here, in case of SimpleProjectRootElementCache, AddEntry does a bit more than just adding to _cache (it raises an event additionally).

Comment (ladipro) [reply src/Build/Evaluation/SimpleProjectRootElementCache.cs:67]: Thank you, yes, it does what it was doing before. It doesn't look right, though, to be adding inside the `GetOrAdd` callback. It means that the item will be added twice - by `AddEntry` and then attempted another add by `GetOrAdd` after the callback returns. It looks as though this should be a `TryGetValue` instead of `GetOrAdd`.

Just a perf nit, really, and OK to ignore.

**Review by ladipro — APPROVED** [review]
