### PR TITLE
Fix TL failure on MSBUILDNOINPROCNODE env variable

### LINKED ISSUE #9322: [Bug]: Terminal logger crashes in TargetStarted coming from OOP node
### Issue Description

I hit a TL crash when building a repro for #9320.

### Steps to Reproduce

Build the following with the `MSBUILDNOINPROCNODE` environment variable set to `1`:

```xml
<Project>
  <Target Name='Build'>
    <RegisterAssembly Assemblies="nonexistent.dll" />
  </Target>
</Project>
```

### Expected Behavior

The build fails as it cannot find `nonexistent.dll`.

### Actual Behavior

```
Unhandled Exception: Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Build.Logging.TerminalLogger.TerminalLogger.TargetStarted(Object sender, TargetStartedEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseTargetStartedEvent(Object sender, TargetStartedEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseTargetStartedEvent(Object sender, TargetStartedEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(KeyValuePair`2 nodeEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ProcessLoggingEvent(Object buildEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.PacketReceived(Int32 node, INodePacket packet)
   at Microsoft.Build.BackEnd.NodePacketFactory.PacketFactoryRecord.DeserializeAndRoutePacket(Int32 nodeId, ITranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, ITranslator translator)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.NodeContext.ReadAndRoutePacket(NodePacketType packetType, Byte[] packetData, Int32 packetLength)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.NodeContext.BodyReadComplete(IAsyncResult result)
   at System.IO.Pipes.PipeStream.AsyncPSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

### Analysis

_No response_

### Versions & Configurations

MSBuild version 17.8.1+585e09762 for .NET Framework

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes #9322

### Context
In an attempt to build an invalid project with MSBUILDNOINPROCNODE=1, the exception "Out of boundary" was thrown.

### Changes Made
Add a check before accessing the array element by index.

### Testing
UTs are added

### CODE REVIEW

**Review by ladipro — CHANGES_REQUESTED** [review]
I don't think this fix is addressing the root cause of the issue. It rather hides it by suppressing the live output.

The crash is caused by the fact that single-process build passes 1 as `nodeCount` to the logger's `Initialize` method, but the out-of-proc node created with `MSBUILDNOINPROCNODE=1` has `NodeId` of 2.

It may be reasonable to simply use `nodeIndex = Math.Min(nodeIndex, _nodes.Length - 1)` but we should be sure that it only kicks in in this scenario, i.e. that we don't end up with two nodes using the same `_nodes` slot. Another safe option would be to create the `_nodes` array one bigger than what's indicated by `nodeCount`.

To see why the current fix does not fully work, please try a long-running build with `MSBUILDNOINPROCNODE=1` and see if live output is working.

**Comment by ladipro** [comment]
Another option: Make `_nodes` a `List<NodeStatus>` and resize to accommodate the highest node ID seen. That would break the reliance of internal node numbering with no/negligible perf impact.

**Comment by YuliiaKovalova** [comment]
> I don't think this fix is addressing the root cause of the issue. It rather hides it by suppressing the live output.
> 
> The crash is caused by the fact that single-process build passes 1 as `nodeCount` to the logger's `Initialize` method, but the out-of-proc node created with `MSBUILDNOINPROCNODE=1` has `NodeId` of 2.
> 
> It may be reasonable to simply use `nodeIndex = Math.Min(nodeIndex, _nodes.Length - 1)` but we should be sure that it only kicks in in this scenario, i.e. that we don't end up with two nodes using the same `_nodes` slot. Another safe option would be to create the `_nodes` array one bigger than what's indicated by `nodeCount`.
> 
> To see why the current fix does not fully work, please try a long-running build with `MSBUILDNOINPROCNODE=1` and see if live output is working.

Oh, I see! thank you for letting me know.

File: src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs [hunk 1]
```diff
@@ -232,6 +231,30 @@ public void TerminalLoggerDefaultOff(string defaultValue)
...
+    [InlineData("1")]
+    [InlineData("0")]
+    public void TerminalLoggerOnInvalidProjectBuild(string msbuildinprocnodeState)
+    {
+        var projectFile = _env.CreateFile(_env.CreateFolder(createFolder: true), "myProjBroken.proj", $"""
+            <Project>
+              <Target Name='Build'>
+                <RegisterAssembly Assemblies="nonexistent.dll" />
+              </Target>
+            </Project>
```
Comment (ladipro) [inline src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs:244]: I suspect the repro project can be simplified to:

```xml
            <Project>
              <Target Name='Build' />
            </Project>
```

**Review by ladipro — APPROVED** [review]
Looks good to me, thank you.

File: src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs [hunk 2]
```diff
@@ -232,6 +231,30 @@ public void TerminalLoggerDefaultOff(string defaultValue)
         ShouldNotBeTerminalLog(output);
     }
 
+    [WindowsFullFrameworkOnlyTheory]
```
Comment (rainersigwald) [inline src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs:234]: Why restrict to Windows/full framework only?

**Review by rainersigwald — APPROVED** [review]

File: src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs (hunk 2 above)
Comment (ladipro) [reply src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs:234]: I guess it's because the bug doesn't reproduce with `dotnet build`. Not sure why, may be worth investigating.

Comment (YuliiaKovalova) [reply src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs:234]: The reason is more trivial:
"The task "RegisterAssembly" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild."

File: src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs (hunk 1 above)
Comment (YuliiaKovalova) [reply src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs:244]: It reports a successful build for this case.

File: src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs (hunk 2 above)
Comment (ladipro) [reply src/Build.UnitTests/TerminalLoggerConfiguration_Tests.cs:234]: Does it really require the RegisterAssembly task to reproduce though? https://github.com/dotnet/msbuild/pull/9388#discussion_r1380379337
