### PR TITLE
Fix /warnaserror false positive overall success

### LINKED ISSUE #8735: [Bug]: /warnaserror false positive overall success
### Issue Description

I'm not sure if this is an msbuild issue or an issue with GitHub Actions OSX agents. The problem is unique to OSX though.

As you can see from the following GitHub Actions run, all 3 jobs experienced the same build errors (which were warnings-as-errors, BTW), but only Windows and Ubuntu reported failure. The Mac OSX agent went on and reported overall success, defeating the point of my setting `MSBuildTreatWarningsAsErrors` to `true` as an environment variable.

https://github.com/AArnott/Nerdbank.Cryptocurrencies/actions/runs/4905363640/jobs/8759094126?pr=5

### Steps to Reproduce

```
git clone https://github.com/AArnott/Nerdbank.Cryptocurrencies
cd Nerdbank.Cryptocurrencies
git checkout 52b604bdd0ed2239ca491118ee7a886ab60963d1
```

Then push this commit to some branch and run github actions on your fork and observe the results.

### Expected Behavior

I expect all jobs to fail.

### Actual Behavior

The OSX job reports success, despite its own build log reporting several errors.

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by rokonec**
Fixes #8735, possibly #5689, #2845

### Context
There were race condition when `ProjectFinished` log message has been processed after `BuildResult` event. Even though `ProjectFinished` log message event is always send before `BuildResult` event from Node, because `ProjectFinished` is asyncronously routed by `LoggingService` reversing order can and do often happen.

### Changes Made
Updating `_overallBuildSuccess` in one place when submission is considered to be done and assumed its final state.

### Testing
Can't local repro.

### CODE REVIEW

**Review by AR-May — APPROVED** [review]
LGTM

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 1]
```diff
@@ -2628,6 +2622,7 @@ private void CheckSubmissionCompletenessAndRemove(BuildSubmission submission)
                 // If the submission has completed or never started, remove it.
                 if (submission.IsCompleted || submission.BuildRequest == null)
                 {
+                    _overallBuildSuccess &= (submission.BuildResult?.OverallResult == BuildResultCode.Success);
```
Comment (JanKrivanek) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:2625]: The `submission.BuildRequest == null` seems to be a difference from previous behavior - when this can happen? And is that expected to be a build failure indicator?

**Review by JanKrivanek — APPROVED** [review]
Looks good

File: src/Build/BackEnd/BuildManager/BuildManager.cs (hunk 1 above)
Comment (rokonec) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:2625]: Normally one call `submission = Build.ManagerPendBuildReuest(); ... ; submission.Execute();` If for any reason code check submission for completness even though it has not yet started, cancel scenarios mostly I guess, submission is removed from list of submissions. 
I believe report failure of overall build manager i n such scenarios looks reasonable to me.
If we, however, receive reports from field, we can fix it easily by not changing _overallBuildSuccess if build submission has not started yet.
