### PR TITLE
load inline task code file relatively to project instead of CWD

### LINKED ISSUE #12680: Multithreaded inline task factories should work with relative paths to code files
### Issue Description

when building MSBuild in -mt mode there is this inline task definition in `MSBuild.csproj`

```xml
  <UsingTask TaskName="ValidateMSBuildPackageDependencyVersions" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <Task>
      <Code Source="ValidateMSBuildPackageDependencyVersions.cs" Language="cs" />
    </Task>
  </UsingTask>

  <Target Name="ValidateMSBuildPackageDependencyVersions" BeforeTargets="AfterBuild" Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <ValidateMSBuildPackageDependencyVersions AppConfig="@(AppConfigWithTargetPath)" AssemblyPath="$(OutputPath)" />
  </Target>
```

it does not work because the taskfactory resolves the Code file ValidateMSBuildPackageDependencyVersions.cs relatively to -mt process instead of relatively to the project file which defines it.

### Steps to Reproduce

build with -mt mode in MSBuild https://github.com/AR-May/msbuild/commit/16b9c4d91b09c6ab2e8711e966dfcd1581750e78

### Expected Behavior

it compiles the file resolved relatively to the project file where it's used

### Actual Behavior

it resolves the file with cwd of multithreaded process, which is different than the file path

crash in the taskfactory initialization when it does not find the file

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by JanProvaznik**
Fixes #12680

### Context
When code file for `RoslynCodeTaskFactory`/`CodeTaskFactory` is specified, it is fetched relative to cwd which in multiprocess is equal to project directory but in multithreaded this is no longer the case.

### Changes Made
Get Project path from buildengine in taskfactory initialization

change only in mt mode to align mt behavior with multiproc

### Testing
integration and unit test

### CODE REVIEW

File: src/Shared/TaskFactoryUtilities.cs [hunk 1]
```diff
@@ -256,6 +256,29 @@ public static bool ShouldCompileForOutOfProcess(IBuildEngine taskFactoryEngineCo
...
+        /// This method only modifies path resolution in multithreaded builds to maintain
+        /// backward compatibility with existing multi-process build behavior.
+        /// </remarks>
+        public static string ResolveTaskSourceCodePath(string path, bool isMultiThreadedBuild, string projectDirectory)
+        {
+            if (!isMultiThreadedBuild || Path.IsPathRooted(path))
+            {
+                return path;
+            }
+
```
[the remark this answers is not in the document]
Comment (JanProvaznik) [reply src/Shared/TaskFactoryUtilities.cs]: I take as invariant that this is set.

File: src/Tasks/CodeTaskFactory.cs [hunk 2]
```diff
@@ -776,7 +782,10 @@ private Assembly CompileAssembly()
                 // If our code is in a separate file, then read it in here
                 if (_sourcePath != null)
                 {
-                    _sourceCode = FileSystems.Default.ReadFileAllText(_sourcePath);
+                    bool isMultiThreaded = _taskFactoryLoggingHost is ITaskFactoryBuildParameterProvider hostContext && hostContext.IsMultiThreadedBuild;
+                    string projectDirectory = Path.GetDirectoryName(_taskFactoryLoggingHost.ProjectFileOfTaskNode);
```
[the remark this answers is not in the document]
Comment (JanProvaznik) [reply src/Tasks/CodeTaskFactory.cs]: in that case it should fail

**Comment by JanProvaznik** [comment]
validated it resolves the problem for MSBuild-building-MSBuild with -mt on the commit from the original issue.

File: src/Shared/TaskFactoryUtilities.cs [hunk 3]
```diff
@@ -267,5 +267,28 @@ public static bool ShouldCompileForOutOfProcess(IBuildEngine taskFactoryEngineCo
...
+        /// <param name="isMultiThreadedBuild">Whether the build is running in multithreaded mode.</param>
+        /// <param name="projectDirectory">The directory of the project file.</param>
+        /// <returns>The resolved absolute path in multithreaded mode, or the original path otherwise.</returns>
+        /// <remarks>
+        /// This method only modifies path resolution in multithreaded builds to maintain
+        /// backward compatibility with existing multi-process build behavior.
+        /// </remarks>
+        public static string ResolveTaskSourceCodePath(string path, bool isMultiThreadedBuild, string projectDirectory)
+        {
+            if (!isMultiThreadedBuild || Path.IsPathRooted(path))
```
Comment (SimaTian) [inline src/Shared/TaskFactoryUtilities.cs]: Is there any possibility of an error happening if the rooted path is relative and the process for some reason changes its working directory to another **disk** ?

**Review by SimaTian — APPROVED** [review]

File: src/Shared/TaskFactoryUtilities.cs (hunk 3 above)
Comment (rainersigwald) [reply src/Shared/TaskFactoryUtilities.cs]: We should have [`Path.IsPathFullyQualified`](https://learn.microsoft.com/dotnet/api/system.io.path.ispathfullyqualified) everywhere (via `Microsoft.IO.Redist` on net472).

Comment (JanProvaznik) [reply src/Shared/TaskFactoryUtilities.cs]: So `Path.IsPathFullyQualified` does not exist in `netstandard2.0` (Microsoft.Build.Tasks.csproj targets that) and `Microsoft.IO.Redist` does not target it to provide it.
What would be a reasonable solution: 
1. leave this edge case unfixed in netstandard?
  - I'm struggling to imagine someone hitting it - they have to use the netstandard task package, but in that case they'd want to do builds by API and that always happens in net10/net472, right?, but I can think longer on if it's problematic.
2. port what is in runtime repo?

Comment (rainersigwald) [reply src/Shared/TaskFactoryUtilities.cs]: Our `netstandard2.0` target should be interface-only, so I'd be fine breaking implementation there.
