### PR TITLE
Fix Mac ARM64 unit tests.

### LINKED ISSUE #7576: Build Issue: Failing Unit Tests on macOS ARM64
### Issue Description
On macOS with Apple Silicon (ARM64) unit tests fail. The issues starts with the commit for PR #7550 on April 19.

On macOS with Intel the issue doesn't occur which is why the PR checks passed.

### Steps to Reproduce
Clone the repo to a host running macOS on an Apple Silicon processor.
Run
```
./build.sh --test
```

The build will fail. The log shows 8 unit tests are failing in Microsoft.Build.Engine.UnitTests.dll.

### Expected Behavior
All unit tests are expected to pass. And if the main branch is reverted to the commit before the PR commit, all unit tests do pass

### Actual Behavior
8 unit tests fail in Microsoft.Build.Engine.UnitTests.dll

### Analysis
The issues starts with the commit for PR #7550 on April 19.

### Versions & Configurations
```
% dotnet --version                                                     
6.0.202
```
Build with HEAD set to 67deba37
```
% dotnet ./artifacts/bin/bootstrap/net6.0/MSBuild/MSBuild.dll --version
Microsoft (R) Build Engine version 17.3.0-dev-22225-01+67deba370 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

17.3.0.22501
```
Build with HEAD set to cff0b1f2 (current as of creating this issue)
```
% dotnet ./artifacts/bin/bootstrap/net6.0/MSBuild/MSBuild.dll --version
Microsoft (R) Build Engine version 17.3.0-dev-22226-01+cff0b1f26 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

17.3.0.22601
```

### Summary of Failed Unit Tests ###

1. Microsoft.Build.Engine.UnitTests.BackEnd.TaskHostFactory_Tests.TaskNodesDieAfterBuild
   - Shouldly.ShouldAssertException : False\n    should be\nTrue\n    but was not
2. Microsoft.Build.UnitTests.BackEnd.BuildManager_Tests.TaskInputLoggingIsExposedToTasks(taskFactory: \"TaskHostFactory\", taskInputLoggingEnabled: False)
   - Assert.Equal() Failure\nExpected: Success\nActual:   Failure
3. Microsoft.Build.UnitTests.BackEnd.BuildManager_Tests.TaskInputLoggingIsExposedToTasks(taskFactory: \"TaskHostFactory\", taskInputLoggingEnabled: True)
   - Assert.Equal() Failure\nExpected: Success\nActual:   Failure
4. Microsoft.Build.UnitTests.EscapingInProjects_Tests.SimpleScenarios.EscapedWildcardsShouldNotBeExpanded_InTaskHost
   - Shouldly.ShouldAssertException : False\n    should be\nTrue\n    but was not\n\nAdditional Info:\n    Build failed.  See test output (Attachments in Azure Pipelines) for details
5. Microsoft.Build.UnitTests.EscapingInProjects_Tests.SimpleScenarios.ItemTransformContainingSemicolon_InTaskHost
   - Assert.True() Failure\nExpected: True\nActual:   False
6. Microsoft.Build.UnitTests.EscapingInProjects_Tests.SimpleScenarios.SemicolonInPropertyPassedIntoStringParam_UsingTaskHost
   - Assert.True() Failure\nExpected: True\nActual:   False
7. Microsoft.Build.UnitTests.XmakeAttributesTest.TestArchitectureValuesMatch
   - Assert.True() Failure\nExpected: True\nActual:   False
8. Microsoft.Build.UnitTests.XmakeAttributesTest.TestMergeArchitectureValues
   - Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: x64\nActual:   arm64\n          ↑ (pos 0)

### PR DESCRIPTION
**Pull request by AR-May**
Fixes #7576

### Context
Unit tests on MAC M1 machine fails. More precisely, those are unit tests related to task host. 
It happens because unit tests do not use bootstrap version of MSBuild to perform tests. So, there is no "arm64" folder and path `MSBuildToolsDirectoryArm64` ends up being null. 

### Changes Made
Defaulted `MSBuildToolsDirectoryArm64` to `CurrentMSBuildToolsDirectory`, as it is done in case of amd64 machine.

### Testing
Unit tests

### CODE REVIEW

**Review by JanKrivanek — APPROVED** [review]

**Comment by ladipro** [comment]
We always ship the amd64 subdirectory but arm64 is present only on ARM64 machines, which kind of justifies the two cases being different. Are you sure that this change has no product impact?

**Comment by ladipro** [comment]
I've tried building the following on a regular Intel machine and while it fails spectacularly, this change doesn't seem to make a difference.

```xml
<Project>
  <UsingTask TaskName="Message" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" Architecture="arm64" />
  <Target Name="Build">
    <Message />
  </Target>
</Project>
```

**Comment by rainersigwald** [comment]
> We always ship the amd64 subdirectory but arm64 is present only on ARM64 machines, which kind of justifies the two cases being different. Are you sure that this change has no product impact?

That was the intention here.

I'm a bit surprised we're hitting this case on macOS netcore tests, since we don't generally support cross-arch anything on netcore. What's the proximate cause of the failures?

**Comment by AR-May** [comment]
> I've tried building the following on a regular Intel machine and while it fails spectacularly, this change doesn't seem to make a difference.
> 
> ```
> <Project>
>   <UsingTask TaskName="Message" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" Architecture="arm64" />
>   <Target Name="Build">
>     <Message />
>   </Target>
> </Project>
> ```

Yes, it currently should not make a difference indeed. We do not have any null checks on the variable that I changed, and it is used when we already determined that we are on arm64 machine.

**Comment by AR-May** [comment]
> We always ship the amd64 subdirectory but arm64 is present only on ARM64 machines, which kind of justifies the two cases being different. Are you sure that this change has no product impact?

Well, the question I asked myself here is "if the amd64 folder always there, why we even need the default on the previous line for amd64 case? We will hit only one case in this if statement, don't it?". 

And one answer that I found is the case of unit tests. When we build unit test assemblies, we do not form any folders in the output folder and do not put binaries accordingly to them. It is just common bin folder and every binary there. And for arm64 case the problem is the same - we have arm64 binaries in a common bin folder, not in a separate "arm64" folder.  

So, i do not think this change will change the behavior. But to make it even safer, I might put my change in ifdef that triggers only when we build unit tests.

**Review by rainersigwald — APPROVED** [review]
I was worried that this might cause problems on core when there is no taskhost, but it's the same as the x86 case which works:

```
S:\msbuild\foo2.proj(13,9): error MSB4216: Could not run the "Message" task because MSBuild
could not create or connect to a task host with runtime "NET" and architecture "x86".  Pleas
e ensure that (1) the requested runtime and/or architecture are available on the machine, an
d (2) that the required executable "C:\Program Files\dotnet\sdk\7.0.200\MSBuild.dll" exists
and can be run.
```

So lgtm.

File: src/Shared/BuildEnvironmentHelper.cs [hunk 1]
```diff
@@ -599,7 +599,7 @@ public BuildEnvironment(BuildEnvironmentMode mode, string currentMSBuildExePath,
 
                 MSBuildToolsDirectory32 = MSBuildToolsDirectoryRoot;
                 MSBuildToolsDirectory64 = existsCheck(potentialAmd64FromX86) ? Path.Combine(MSBuildToolsDirectoryRoot, "amd64") : CurrentMSBuildToolsDirectory;
-                MSBuildToolsDirectoryArm64 = existsCheck(potentialARM64FromX86) ? Path.Combine(MSBuildToolsDirectoryRoot, "arm64") : null;
+                MSBuildToolsDirectoryArm64 = existsCheck(potentialARM64FromX86) ? Path.Combine(MSBuildToolsDirectoryRoot, "arm64") : CurrentMSBuildToolsDirectory;
```
Comment (rainersigwald) [inline src/Shared/BuildEnvironmentHelper.cs:602]: I think this change should apply only to .NET Core MSBuild, to prevent a problem where:

1. On an amd64 VS installation (no arm64 folder)
2. UsingTask specifies that a task should run in arm64

With this, I'm worried that we will silently run the task in amd64 instead of correctly failing with a "we don't have arm64" error.

**Review by rainersigwald — CHANGES_REQUESTED** [review]

File: src/Shared/BuildEnvironmentHelper.cs (hunk 1 above)
Comment (rainersigwald) [reply src/Shared/BuildEnvironmentHelper.cs:602]: This wouldn't apply the same way to x86, because that's "always" available in a VS installation.

File: src/Shared/BuildEnvironmentHelper.cs [hunk 2]
```diff
@@ -599,7 +599,11 @@ public BuildEnvironment(BuildEnvironmentMode mode, string currentMSBuildExePath,
 
                 MSBuildToolsDirectory32 = MSBuildToolsDirectoryRoot;
                 MSBuildToolsDirectory64 = existsCheck(potentialAmd64FromX86) ? Path.Combine(MSBuildToolsDirectoryRoot, "amd64") : CurrentMSBuildToolsDirectory;
+#if RUNTIME_TYPE_NETCORE
+                MSBuildToolsDirectoryArm64 = existsCheck(potentialARM64FromX86) ? Path.Combine(MSBuildToolsDirectoryRoot, "arm64") : CurrentMSBuildToolsDirectory;
```
Comment (rainersigwald) [inline src/Shared/BuildEnvironmentHelper.cs:603]: Seem reasonable?

```suggestion
                // Fall back to "current" for any architecture since .NET SDK doesn't
                // support cross-arch task invocations.
                MSBuildToolsDirectoryArm64 = existsCheck(potentialARM64FromX86) ? Path.Combine(MSBuildToolsDirectoryRoot, "arm64") : CurrentMSBuildToolsDirectory;
```

**Review by rainersigwald — APPROVED** [review]
