### PR TITLE
Fix race conditions in AssemblyTaskFactory class.

### LINKED ISSUE #12867: ProjectTelemetry subclass tracking is not thread safe
### Issue Description

There is a chance this one has already been resolved (I'm working with the prototype, although rebased onto main). However to not lose the error if that is not the case:   

 

### Steps to Reproduce

Run a hot build on the roslyn repository.

### Expected Behavior

build works

### Actual Behavior

build fails with the reported error message

### Analysis

E:\sdk\artifacts\bin\redist\Release\dotnet\sdk\11.0.100-dev\Microsoft.Common.CurrentVersion.targets(2012,5): error MSB4061: The "CombineTargetFrameworkInfoProperties" task could not be instantiated from "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
    E:\sdk\artifacts\bin\redist\Release\dotnet\sdk\11.0.100-dev\Microsoft.Common.CurrentVersion.targets(2012,5): error MSB4060: The "CombineTargetFrameworkInfoProperties" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
  Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler netstandard2.0 failed with 2 error(s) (0.0s)
    E:\sdk\artifacts\bin\redist\Release\dotnet\sdk\11.0.100-dev\Microsoft.Common.CurrentVersion.targets(2012,5): error MSB4061: The "CombineTargetFrameworkInfoProperties" task could not be instantiated from "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
    E:\sdk\artifacts\bin\redist\Release\dotnet\sdk\11.0.100-dev\Microsoft.Common.CurrentVersion.targets(2012,5): error MSB4060: The "CombineTargetFrameworkInfoProperties" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
  Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost net6.0 succeeded with 1 warning(s) (0.3s)
    

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by AR-May**
Fixes #12867

### Context
Building large repos (e.g., Roslyn) in multi-threaded mode crashes intermittently:

error MSB4061: The "CombineTargetFrameworkInfoProperties" task could not be instantiated...
Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state.

Root Cause
`AssemblyTaskFactory` instances are shared across thread nodes — they're cached in `TaskRegistry._taskFactoryWrapperInstance`. `TaskRegistry` itself is shared across thread nodes by design. In mt builds, multiple projects call `CreateTaskInstance()` on the same `AssemblyTaskFactory` instance concurrently from different threads. This exposed two thread-safety issues:

 1. `_taskLoggingContext` field race (crash-causing)

Race condition example: When Thread A (Project A) and Thread B (Project B) concurrently call `CreateTaskInstance()`:
   1. Thread A sets `_taskLoggingContext = contextA`
   2. Thread B overwrites `_taskLoggingContext = contextB`
   3. Thread A reads `_taskLoggingContext` for `TrackTaskSubclassing` → gets `contextB` → writes to Project B's ProjectTelemetry
   4. Thread B also writes to Project B's ProjectTelemetry
   5. Two threads mutate the same Dictionary<string, int> → crash

The `ProjectTelemetry` in turn is not supposed to be accessed from multiple threads - only one thread node should build a project. It does not need to be thread-safe.

`_taskLoggingContext` field existed so that `ErrorLoggingDelegate` (a named method passed as a callback to `TaskLoader.CreateTask()`) could access the logging context, but it is not really required. For mt mode support, there should not be mutable fields in `AssemblyTaskFactory` that relate to a specific task.

  2. `_tasksAndAppDomains` dictionary (in .NET Framework)

`Dictionary<ITask, AppDomain>` is not safe for concurrent structural mutations. While each thread operates on different keys (unique ITask instances), concurrent add/remove on different keys still corrupts a plain Dictionary.

### Changes Made
- Removed `_taskLoggingContext` field entirely. 
- Changed `_tasksAndAppDomains` from `Dictionary<ITask, AppDomain>` to `ConcurrentDictionary<ITask, AppDomain>`
Note that lock contention should be negligible, as each thread would add and clean-up its own set of keys.

### Testing
Existing unit tests

### CODE REVIEW

**Comment by AR-May** [comment]
It seems the original issue it is not reproducible for us, most probably because of the small number of enlightened tasks compared to the prototype where it was detected, which had more enlightened tasks.

File: src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs [hunk 1]
```diff
@@ -355,7 +348,7 @@ internal ITask CreateTaskInstance(
                 }
             }
 
-            _taskLoggingContext?.TargetLoggingContext?.ProjectLoggingContext?.ProjectTelemetry?.AddTaskExecution(GetType().FullName, isTaskHost: useTaskFactory);
+            taskLoggingContext?.TargetLoggingContext?.ProjectLoggingContext?.ProjectTelemetry?.AddTaskExecution(GetType().FullName, isTaskHost: useTaskFactory);
```
[the remark this answers is not in the document]
Comment (AR-May) [reply src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs:351]: This unit test is highly unreliable and not managing to hit the race.

File: src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs [hunk 2]
```diff
@@ -54,19 +55,14 @@ internal class AssemblyTaskFactory : ITaskFactory3
         /// <summary>
         /// A cache of tasks and the AppDomains they are loaded in.
         /// </summary>
-        private Dictionary<ITask, AppDomain> _tasksAndAppDomains = new Dictionary<ITask, AppDomain>();
+        private readonly ConcurrentDictionary<ITask, AppDomain> _tasksAndAppDomains = new ConcurrentDictionary<ITask, AppDomain>();
```
Comment (JanProvaznik) [inline src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs:58]: you mention it's negligible contention overhead. do you have proof of that from debugging/trace?

File: src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs [hunk 3]
```diff
@@ -400,7 +393,8 @@ internal ITask CreateTaskInstance(
                     taskLocation.File,
                     taskLocation.Line,
                     taskLocation.Column,
-                    new TaskLoader.LogError(ErrorLoggingDelegate),
+                    new TaskLoader.LogError((taskLoc, taskLine, taskColumn, message, messageArgs) =>
```
Comment (JanProvaznik) [inline src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs:396]: so this creates a new closure for for each task, right? is that concerning in for perf?

File: src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs (hunk 2 above)
Comment (AR-May) [reply src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs:58]: I did not profile that, but the amount of the keys presenting simultaneously in the dictionary would not that big (compared to number of nodes) and most importantly, only one thread at a time works with each key, which together with the fact that `ConcurrentDictionary` has a fine-grained locking should result in minimal lock contention.

File: src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs (hunk 3 above)
Comment (AR-May) [reply src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs:396]: Yes, it will create it for each task, but it is very small object. But it is not concerning, task instantiation and execution is way more expensive. Even before, there was allocation of the delegate object, while it could have been actually cached.
