### PR TITLE
Change WriteCodeFragment task to create directory

### LINKED ISSUE #8516: [Feature]: WriteCodeFragment creates relevant directory structure
### Issue Description

WriteCodeFragment pretty directly calls File.WriteAllText, which fails if you pass in a folder structure that does not exist. We should consider calling Directory.CreateDirectory first.

### Steps to Reproduce

Take any project and add a call to the WriteCodeFragment task, passing in `OutputDirectory=<path on computer that does not exist>`

### Expected Behavior

Creates folders as necessary

### Actual Behavior

Fails

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by jrdodds**
Fixes #8516

### Context
Setting an `OutputDirectory` where the directory does not exist, and setting an `OutputFile` would fail.

(Setting an `OutputDirectory` where the directory does not exist, and not providing an `OutputFile` value would succeed because `FileUtilities.GetTemporaryFile` calls `Directory.CreateDirectory`.)

#### WriteCodeFragment_Tests.cs
- Added new unit tests:
  - `CombineFileDirectoryAndDirectoryDoesNotExist` (pairs with `CombineFileDirectory`)
  - `ToDirectoryAndDirectoryDoesNotExist` (pairs with `ToDirectory`)
- Added overload of `CreateTask`

#### WriteCodeFragment.cs
- Changed task to call `FileUtilities.EnsureDirectoryExists`.

### Testing
Added unit tests first and confirmed failure.

Ran all unit tests on Windows 11 and macOS 12 (Monterey).

### CODE REVIEW

File: src/Tasks/WriteCodeFragment.cs [hunk 1]
```diff
@@ -106,6 +106,11 @@ public override bool Execute()
 
             try
             {
+                if (OutputDirectory != null && !Path.IsPathRooted(OutputFile?.ItemSpec))
+                {
+                    FileUtilities.EnsureDirectoryExists(OutputDirectory.ItemSpec);
+                }
+
```
Comment (rainersigwald) [inline src/Tasks/WriteCodeFragment.cs:113]: My instinct is to move this to after `OutputFile` is guaranteed to be defined, so the task will still create the required folder(s) for a fully-specified `OutputFile` when there's no `OutputDirectory`. Sound reasonable?

File: src/Tasks.UnitTests/WriteCodeFragment_Tests.cs [hunk 2]
```diff
@@ -90,6 +90,33 @@ public void CombineFileDirectory()
...
             Assert.True(File.Exists(file));
+
+            File.Delete(task.OutputFile.ItemSpec);
+        }
+
+        /// <summary>
+        /// Combine file and directory where the directory does not already exist
+        /// </summary>
+        [Fact]
+        public void CombineFileDirectoryAndDirectoryDoesNotExist()
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/WriteCodeFragment_Tests.cs:101]: Using our `TestEnvironment` class will help streamline this even without going to a full modernization of the test logic. I'll push a small change.

File: src/Tasks/WriteCodeFragment.cs (hunk 1 above)
Comment (jrdodds) [reply src/Tasks/WriteCodeFragment.cs:113]: You mean where no `OutputDirectory` is provided and the `OutputFile` is a path and filename? Yes, I missed that case. There should be a unit test added to cover that.

Comment (jrdodds) [reply src/Tasks/WriteCodeFragment.cs]: committed a change

File: src/Tasks.UnitTests/WriteCodeFragment_Tests.cs [hunk 3]
```diff
@@ -176,7 +221,7 @@ public void NoAttributesShouldEmitNoFile2()
         /// <summary>
         /// Bad file path
         /// </summary>
-        [Fact]
+        [WindowsOnlyFact(additionalMessage: "No invalid characters on Unix.")]
```
Comment (Forgind) [inline src/Tasks.UnitTests/WriteCodeFragment_Tests.cs:224]: Why did this test work on Unix before?

**Review by Forgind — APPROVED** [review]
Looks good to me!

File: src/Tasks.UnitTests/WriteCodeFragment_Tests.cs (hunk 3 above)
Comment (jrdodds) [reply src/Tasks.UnitTests/WriteCodeFragment_Tests.cs:224]: It worked before because the path didn't exist. Now that we ensure that the path is created, the test fails because there is not an `MSB3713` error. :grinning:

**Review by rainersigwald — APPROVED** [review]
Awesome, thanks!

File: src/Tasks.UnitTests/WriteCodeFragment_Tests.cs (hunk 3 above)
Comment (Forgind) [reply src/Tasks.UnitTests/WriteCodeFragment_Tests.cs:224]: Ah, looks like 3713 is a very generic error for any failure. Makes sense, thanks!
