### PR TITLE
Log warnings for skipped STR resource keys instead of failing the build

### LINKED ISSUE #13061: GenerateResource task fails with a resource string key/name containing an equals or back tick character in a resources file (resx)
### Issue Description

Hi.

The `GenerateResource` task fails with a resource string key/name containing an equals or back tick character in a resources file (resx).

Building the same resources file works when using `ResXFileCodeGenerator` or `PublicResXFileCodeGenerator`.

### Steps to Reproduce

1. Create a new C# project (ex. "MSTest Test project").
2. Add a new resources file (ex. "Resource1.resx").
3. Add a new resource with the name `equals` and value `=`.
4. Notice the project builds successfully.
5. Right-click on the resx file and select "Open With..." and select "XML (Text) Editor".
6. Change the name from `equals` to `=`.
7. Notice the project builds successfully.
8. Open the csproj file and replace this:
```xml
  <ItemGroup>
    <Compile Update="Resource1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource1.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
```

With this:
```xml
  <ItemGroup>
    <EmbeddedResource Update="Resource1.resx" Type="Resx">
      <Generator>MSBuild:Compile</Generator>
      <StronglyTypedLanguage>$(Language)</StronglyTypedLanguage>
    </EmbeddedResource>
  </ItemGroup>
```
9. Notice the build fails with the following errors:
```
1>C:\Program Files\Microsoft Visual Studio\18\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3442,5): error MSB3557: Error(s) generating strongly typed resources for file "Resource1.resx".
1>C:\Program Files\Microsoft Visual Studio\18\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3442,5): error MSB3567: Could not generate property on class "=".
```

### Expected Behavior

I expected the build to succeed and a strongly typed class generated for the resources file.

In production, my string resource key is not actually one character, but more like:
```
'User name' contains invalid characters. The following characters are not allowed: &quot;/[]:|&lt;&gt;+=;,?%@`
```

And the error is
```
Could not generate property on class "'User name' contains invalid characters. The following characters are not allowed: "/[]:|<>+=;,?%@`"
```

So it was not exactly clear why the property on the class was not generated (which characters caused the issue).

If I remove the equals sign (`=`) and back tick (`) characters, the build succeeds and the strongly typed class is generated successfully.

The name of the property that is created has underscore characters instead of some of the other symbols, so I expected the `GenerateResource` task to do the same for the equals and back tick characters.

### Actual Behavior

The build fails with the following errors:
```
1>C:\Program Files\Microsoft Visual Studio\18\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3442,5): error MSB3557: Error(s) generating strongly typed resources for file "Resource1.resx".
1>C:\Program Files\Microsoft Visual Studio\18\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3442,5): error MSB3567: Could not generate property on class "=".
```

A strongly typed class is not generated.

### Analysis

_No response_

### Versions & Configurations

Windows 11 Version 25H2 (OS Build 26200.7171)
Visual Studio 2026 Version 18.1.1
MSBuild version 18.0.5+e22287bf1 for .NET Framework 18.0.5.56406

### PR DESCRIPTION
**Pull request by OvesN**
Fixes #13061

### Context
The `GenerateResource` task with `MSBuild:Compile` failed the entire build when a resource key (e.g. containing = or \`) could not be converted to a valid C# identifier. In contrast, `ResXFileCodeGenerator` silently skipped such entries. This aligns the behavior by skipping invalid keys with warnings instead of failing.

### Changes Made
- Added warning messages MSB3827–MSB3830 for resource keys that are skipped during STR property generation.
- STR files are now still generated even when some keys cannot produce valid identifiers.

### Testing
Added unit tests verifying that invalid resource keys emit the expected warnings and valid keys still generate STR properties.

### Notes
`ResXFileCodeGenerator `in VS silently skips invalid keys with no diagnostic. A separate VS [issue ](https://developercommunity.visualstudio.com/t/ResXFileCodeGenerator-silently-skips-res/11049047?) has been created to add warnings there as well.

### CODE REVIEW

**Comment by OvesN** [comment]
@dotnet-policy-service agree company="Microsoft"

File: src/Tasks/GenerateResource.cs [hunk 1]
```diff
@@ -3443,7 +3443,7 @@ private void CreateStronglyTypedResources(ReaderInfo reader, String outFile, Str
                 _logger.LogMessageFromResources("GenerateResource.CreatingSTR", _stronglyTypedFilename);
 
                 // Generate the STR class
-                String[] errors;
+                (string key, string reason, string extraArg)[] warnings;
```
Comment (JanProvaznik) [inline src/Tasks/GenerateResource.cs]: create a `record` for this instead of named tuple

File: src/Tasks/Resources/Strings.resx [hunk 2]
```diff
@@ -1179,6 +1179,23 @@
...
+  <data name="GenerateResource.STRPropertySkippedInvalidIdentifier">
+    <value>MSB3828: Skipping strongly typed resource property generation for resource "{0}": the name cannot be converted to a valid identifier.</value>
+    <comment>{StrBegin="MSB3828: "}</comment>
+  </data>
+  <data name="GenerateResource.STRPropertySkippedNameCollision">
+    <value>MSB3829: Skipping strongly typed resource property generation for resource "{0}": a name collision exists with resource "{1}" after identifier normalization.</value>
+    <comment>{StrBegin="MSB3829: "}</comment>
+  </data>
+  <data name="GenerateResource.STRPropertySkippedVoidType">
+    <value>MSB3830: Skipping strongly typed resource property generation for resource "{0}": the resource value type is void, which cannot be used as a property type.</value>
```
Comment (JanProvaznik) [inline src/Tasks/Resources/Strings.resx:1195]: good descriptions of the situations 👍

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 3]
```diff
@@ -731,11 +731,15 @@ private static SortedList<string, ResourceData> VerifyResourceNames(
...
                 // those.  (Any other properties we add also must be listed here)
                 // Also disallow resource values of type Void.
-                if (String.Equals(key, ResMgrPropertyName) ||
-                    String.Equals(key, CultureInfoPropertyName) ||
-                    typeof(void) == entry.Value.Type)
+                string reservedNames = String.Join(", ", ResMgrPropertyName, CultureInfoPropertyName);
+                if (String.Equals(key, ResMgrPropertyName) || String.Equals(key, CultureInfoPropertyName))
                 {
-                    errors.Add(key);
+                    errors.Add((key, "GenerateResource.STRPropertySkippedReservedName", reservedNames));
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: I think having these names of string resources here is the wrong architecture. 
I think it should be that the builder class constructs a `record` that describes why it skipped a resource. Then the Task class decides how to use that record to log this information with the string.

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 4]
```diff
@@ -731,11 +731,15 @@ private static SortedList<string, ResourceData> VerifyResourceNames(
                 // Disallow a property named ResourceManager or Culture - we add
                 // those.  (Any other properties we add also must be listed here)
                 // Also disallow resource values of type Void.
-                if (String.Equals(key, ResMgrPropertyName) ||
-                    String.Equals(key, CultureInfoPropertyName) ||
-                    typeof(void) == entry.Value.Type)
+                string reservedNames = String.Join(", ", ResMgrPropertyName, CultureInfoPropertyName);
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: this is wasteful to compute each time in the loop, it is effectively a constant, right?

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 5]
```diff
@@ -764,12 +768,12 @@ private static SortedList<string, ResourceData> VerifyResourceNames(
                     {
                         // We can't handle this key nor the previous one.
                         // Remove the old one.
-                        if (!errors.Contains(oldDuplicateKey))
+                        if (!errors.Exists(e => e.key == oldDuplicateKey))
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: this was slow before, but now it also allocates a delegate, consider having a hashset for the keys so we can check duplicates fast

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 6]
```diff
@@ -785,15 +789,28 @@ private static SortedList<string, ResourceData> VerifyResourceNames(
                     // There was a case-insensitive conflict between two keys.
                     // Or possibly one key was fixed up in a way that conflicts
                     // with another key (ie, "A B" and "A_B").
+                    string existingOriginalKey;
                     if (reverseFixupTable.TryGetValue(key, out string fixedUp))
                     {
-                        if (!errors.Contains(fixedUp))
+                        existingOriginalKey = fixedUp;
+                        if (!errors.Exists(e => e.key == fixedUp))
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: same as above

File: src/Tasks/GenerateResource.cs [hunk 7]
```diff
@@ -3454,28 +3454,22 @@ private void CreateStronglyTypedResources(ReaderInfo reader, String outFile, Str
                         _stronglyTypedResourcesNamespace,
                         provider,
                         generateInternalClass,
-                        out errors);
+                        out warnings);
```
Comment (JanProvaznik) [inline src/Tasks/GenerateResource.cs]: This seems very suspicious, are you sure these 4 skip scenarios are the only reasons for failure of the builder?

there might need to be 2 `out` params: skipreasons and errors. The logic of the task would be to log warning for skipreasons and fail on errors.

File: src/Tasks/GenerateResource.cs [hunk 8]
```diff
@@ -3454,28 +3454,22 @@ private void CreateStronglyTypedResources(ReaderInfo reader, String outFile, Str
...
-                    {
-                        _logger.LogErrorWithCodeFromResources("GenerateResource.CodeDomError", error);
-                    }
-                }
-                else
-                {
-                    // No errors, and no exceptions - we presumably did create the STR class file
-                    // and it should get added to FilesWritten. So set a flag to indicate this.
-                    _stronglyTypedResourceSuccessfullyCreated = true;
+                        _logger.LogWarningWithCodeFromResources(reason, key, extraArg);
```
Comment (JanProvaznik) [inline src/Tasks/GenerateResource.cs]: nit: this has wrong indentation, format changed files before commiting

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 9]
```diff
@@ -785,15 +789,28 @@ private static SortedList<string, ResourceData> VerifyResourceNames(
...
+                        // Pure case-insensitive collision — retrieve the actual stored key.
+                        int idx = cleanedResourceList.IndexOfKey(key);
+                        existingOriginalKey = cleanedResourceList.Keys[idx];
+                        if (!errors.Exists(e => e.key == existingOriginalKey))
+                        {
+                            errors.Add((existingOriginalKey, "GenerateResource.STRPropertySkippedNameCollision", entry.Key));
+                        }
+                    }
+
+                    errors.Add((entry.Key, "GenerateResource.STRPropertySkippedNameCollision", existingOriginalKey));
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: why do you need to add this case?

Comment (OvesN) [reply src/Tasks/system.design/stronglytypedresourcebuilder.cs]: Actually, that was my mistake - we don't need this case because the input dictionary uses StringComparer.InvariantCultureIgnoreCase, so it will never contain entries with names like "myKey" and "mykey" together. I've deleted this branch.

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs (hunk 3 above)
Comment (OvesN) [reply src/Tasks/system.design/stronglytypedresourcebuilder.cs]: Done, now task class resolves message keys

File: src/Tasks/GenerateResource.cs (hunk 7 above)
Comment (OvesN) [reply src/Tasks/GenerateResource.cs]: In every case where errors.Add was used in the original code, I now create a warning about which entry was skipped during generation of the STR file.

File: src/Tasks/GenerateResource.cs [hunk 10]
```diff
@@ -3454,28 +3454,31 @@ private void CreateStronglyTypedResources(ReaderInfo reader, String outFile, Str
...
-                    // and it should get added to FilesWritten. So set a flag to indicate this.
-                    _stronglyTypedResourceSuccessfullyCreated = true;
+                        StronglyTypedResourceBuilder.ResourceWarningReason.CodeDomError => "GenerateResource.CodeDomError",
+                        StronglyTypedResourceBuilder.ResourceWarningReason.ReservedName => "GenerateResource.STRPropertySkippedReservedName",
+                        StronglyTypedResourceBuilder.ResourceWarningReason.VoidType => "GenerateResource.STRPropertySkippedVoidType",
+                        StronglyTypedResourceBuilder.ResourceWarningReason.InvalidIdentifier => "GenerateResource.STRPropertySkippedInvalidIdentifier",
+                        StronglyTypedResourceBuilder.ResourceWarningReason.NameCollision => "GenerateResource.STRPropertySkippedNameCollision",
+                        _ => throw new InvalidOperationException(),
+                    };
+                    _logger.LogWarningWithCodeFromResources(messageKey, warning.Key, warning.ExtraArg);
```
Comment (JanProvaznik) [inline src/Tasks/GenerateResource.cs]: don't pass the second argument to those resources that don't take it

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 11]
```diff
@@ -83,6 +84,34 @@ internal static class StronglyTypedResourceBuilder
         // Maximum size of a String resource to show in the doc comment for its property
         private const int DocCommentLengthThreshold = 512;
 
+        // Describes a resource key that could not be converted to a valid STR property.
+        internal enum ResourceWarningReason
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: I'm not a fan of the "Warning" naming in general, that we warn about this is concern of the presentation layer (the Task), can it be something like KeySkippedReason/unmatchable something? because that's what happens, no?

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 12]
```diff
@@ -68,6 +68,7 @@ internal static class StronglyTypedResourceBuilder
         private const String ResMgrPropertyName = "ResourceManager";
         private const String CultureInfoFieldName = "resourceCulture";
         private const String CultureInfoPropertyName = "Culture";
+        private static readonly String reservedNames = String.Join(", ", ResMgrPropertyName, CultureInfoPropertyName);
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: why not const?
nit: i'd write just $"{ResMgrPropertyName}, {CultureInfoPropertyName}"

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 13]
```diff
@@ -83,6 +84,34 @@ internal static class StronglyTypedResourceBuilder
...
+        internal enum ResourceWarningReason
+        {
+            CodeDomError,
+            ReservedName,
+            VoidType,
+            InvalidIdentifier,
+            NameCollision,
+        }
+
+        internal sealed record ResourceWarning(string Key, ResourceWarningReason Reason, string ExtraArg);
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: ExtraArg is not clear, name it more clearly what is stored there

feel free to have multiple properties and fill the one that's relevant,
use `string?` to express the intent that `null` is valid

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 14]
```diff
@@ -785,18 +821,24 @@ private static SortedList<string, ResourceData> VerifyResourceNames(
...
-                            errors.Add(fixedUp);
+                            warnings.Add(new ResourceWarning(alreadyAddedOriginalName, ResourceWarningReason.NameCollision, entry.Key));
                         }
+
                         reverseFixupTable.Remove(key);
                     }
-                    errors.Add(entry.Key);
+
+                    // Warn about the current entry.
+                    warnings.Add(new ResourceWarning(entry.Key, ResourceWarningReason.NameCollision, alreadyAddedOriginalName));
```
Comment (JanProvaznik) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs]: alreadyAddedOriginalName is null when two valid identifiers
  collide only by case (e.g. "MyRes" vs "myRes") — neither goes through fixup,
  so reverseFixupTable has no entry and TryGetValue on line 824 doesn't set it.
  The warning renders as a name collision exists with resource "". Restore the
  IndexOfKey lookup from the earlier revision to retrieve the actual stored key
  name

File: src/Tasks/GenerateResource.cs (hunk 10 above)
Comment (JanProvaznik) [reply src/Tasks/GenerateResource.cs]: I suppose that requires switching what logging method is called instead of switching to retrive key

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs (hunk 14 above)
Comment (OvesN) [reply src/Tasks/system.design/stronglytypedresourcebuilder.cs]: With the code as it is, this cannot happen because keys like "MyRes" and "myRes" would cause an ArgumentException inside the Create function in StronglyTypedResourceBuilder when adding them to the dictionary with StringComparer.InvariantCultureIgnoreCase. This doesn't happen now because StronglyTypedResourceBuilder is only called from the GenerateResource task, and GenerateResource already removes duplicate keys in its AddResource function, emitting the warning "MSB3568: Duplicate resource name '{0}' is not allowed, ignored."

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs (hunk 13 above)
Comment (OvesN) [reply src/Tasks/system.design/stronglytypedresourcebuilder.cs]: I don't think separate properties are the right fit here. After the warning is returned to the task class, we don't interpret the extra args individually - we only pass them as format arguments to the logging method. All that matters is that they're in the correct order to match the message's placeholders.

About naming - I renamed it to AdditionalMessageArgs.

File: src/Tasks/GenerateResource.cs (hunk 10 above)
Comment (OvesN) [reply src/Tasks/GenerateResource.cs]: I changed ExtraArg from a single string to a list and now pass all arguments to LogWarningWithCodeFromResources within that list, so each message receives exactly the args it needs.

File: src/Tasks/GenerateResource.cs [hunk 15]
```diff
@@ -3454,28 +3454,31 @@ private void CreateStronglyTypedResources(ReaderInfo reader, String outFile, Str
...
-                    // and it should get added to FilesWritten. So set a flag to indicate this.
-                    _stronglyTypedResourceSuccessfullyCreated = true;
+                        StronglyTypedResourceBuilder.SkipReason.CodeDomError => "GenerateResource.CodeDomError",
+                        StronglyTypedResourceBuilder.SkipReason.ReservedName => "GenerateResource.STRPropertySkippedReservedName",
+                        StronglyTypedResourceBuilder.SkipReason.VoidType => "GenerateResource.STRPropertySkippedVoidType",
+                        StronglyTypedResourceBuilder.SkipReason.InvalidIdentifier => "GenerateResource.STRPropertySkippedInvalidIdentifier",
+                        StronglyTypedResourceBuilder.SkipReason.NameCollision => "GenerateResource.STRPropertySkippedNameCollision",
+                        _ => throw new InvalidOperationException($"Unknown SkipReason {skipped.Reason}"),
+                    };
+                    _logger.LogWarningWithCodeFromResources(messageKey, [skipped.Key, .. skipped.AdditionalMessageArgs]);
```
Comment (JanProvaznik) [inline src/Tasks/GenerateResource.cs]: this is actually elegant, cool

but note the performance considerations:
never do this in a hot path, it allocates an extra array

this is not a hot path so elegance is valid

Comment (rainersigwald) [inline src/Tasks/GenerateResource.cs]: This is way better than it was!

```
  13061 net10.0 succeeded with 1 warning(s) (0.3s) → bin\Debug\net10.0\13061.dll
    S:\work\msbuild3\artifacts\bin\bootstrap\core\sdk\10.0.103\Microsoft.Common.CurrentVersion.targets(3456,5): warning MSB3828: Skipping strongly typed resource property generation for resource "=": the name cannot be converted to a valid identifier.
```

However, _ideally_ we'd report the `.resx` file path instead of the location of the `GenerateResource` task invocation. As a follow-up task (in this PR or separately), can you look at how hard it would be to pass that information through to the warning call?

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs [hunk 16]
```diff
@@ -144,16 +173,16 @@ private static CodeCompileUnit InternalCreate(Dictionary<String, ResourceData> r
...
 
-            // Keep a list of errors describing known strings that couldn't be
-            // fixed up (like "4"), as well as listing all duplicate resources that
-            // were fixed up to the same name (like "A B" and "A-B" both going to
-            // "A_B").
-            var errors = new List<string>();
+            // Keep a list of resources that couldn't be converted to valid
+            // STR properties (like "4"), as well as listing all duplicate resources
+            // that were fixed up to the same name (like "A B" and "A-B" both going
+            // to "A_B").
```
Comment (rainersigwald) [inline src/Tasks/system.design/stronglytypedresourcebuilder.cs:179]: Does the "skip both resources" behavior on the "fixed up to the same name" case match the VS generator?

File: src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs [hunk 17]
```diff
@@ -1665,6 +1665,227 @@ public void STRWithResourcesNamespaceAndSTRNamespaceVB()
...
+                File.Delete(t.Sources[0].ItemSpec);
+                if (t.StronglyTypedFileName != null)
+                {
+                    FileUtilities.DeleteNoThrow(t.StronglyTypedFileName);
+                }
+
+                foreach (ITaskItem item in t.FilesWritten)
+                {
+                    FileUtilities.DeleteNoThrow(item.ItemSpec);
+                }
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs:1726]: In general, we prefer to use our `TestEnvironment` to handle cleanup, but looking at the details here it'd be pretty annoying to use. So no need to change these but something to consider next time.

File: src/Tasks/system.design/stronglytypedresourcebuilder.cs (hunk 16 above)
Comment (OvesN) [reply src/Tasks/system.design/stronglytypedresourcebuilder.cs:179]: Yes, it does. I tried to generate these resources with VS generator
```
 <data name="A B" xml:space="preserve">
    <value>First variant (hyphen)</value>
  </data>
	<data name="A-B" xml:space="preserve">
    <value>Second variant</value>
  </data>
 ```
 And none STR was generated.

File: src/Tasks/GenerateResource.cs (hunk 15 above)
Comment (OvesN) [reply src/Tasks/GenerateResource.cs]: Sure, I used the correct overload of LogWarningWithCodeFromResources and now it logs the .resx file path.

```
Resource1.resx : warning MSB3829: Skipping strongly typed resource property generation for resource "foo_bar": a name collision exists with resource "foo-bar" after identifier normalization.
```

File: src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs (hunk 17 above)
Comment (OvesN) [reply src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs:1726]: Okay, I’ll use it next time. I did a manual cleanup because this approach is used in the tests in this file

File: src/Tasks/GenerateResource.cs (hunk 15 above)
Comment (baronfel) [reply src/Tasks/GenerateResource.cs]: Does the task know the line number and/or column number? If so, we can point right to the erroring resource.

Comment (rainersigwald) [reply src/Tasks/GenerateResource.cs]: I suspect that's surprisingly annoying in this case @baronfel (based on wanting the same thing in the past).

File: src/Tasks/GenerateResource.cs [hunk 18]
```diff
@@ -3454,28 +3454,31 @@ private void CreateStronglyTypedResources(ReaderInfo reader, String outFile, Str
...
-                    // and it should get added to FilesWritten. So set a flag to indicate this.
-                    _stronglyTypedResourceSuccessfullyCreated = true;
+                        StronglyTypedResourceBuilder.SkipReason.CodeDomError => "GenerateResource.CodeDomError",
+                        StronglyTypedResourceBuilder.SkipReason.ReservedName => "GenerateResource.STRPropertySkippedReservedName",
+                        StronglyTypedResourceBuilder.SkipReason.VoidType => "GenerateResource.STRPropertySkippedVoidType",
+                        StronglyTypedResourceBuilder.SkipReason.InvalidIdentifier => "GenerateResource.STRPropertySkippedInvalidIdentifier",
+                        StronglyTypedResourceBuilder.SkipReason.NameCollision => "GenerateResource.STRPropertySkippedNameCollision",
+                        _ => throw new InvalidOperationException($"Unknown SkipReason {skipped.Reason}"),
+                    };
+                    _logger.LogWarningWithCodeFromResources(null, inputFileName, 0, 0, 0, 0, messageKey, [skipped.Key, .. skipped.AdditionalMessageArgs]);
```
Comment (rainersigwald) [inline src/Tasks/GenerateResource.cs]: I think this is better than it was before, since it was logging only the filename before,  but _ideally_ we'd use the full path to the resx file here.

**Comment by JanProvaznik** [comment]
:shipit:
