### PR TITLE
Respect response files (ignoreProjectExtensions) property

### LINKED ISSUE #9507: [Bug]: ignoreProjectExtensions flag doesn't work when specified from an RSP file
### Issue Description

Looks like ignoreProjectExtensions is used before reading the rsp file, so it can only come from command line args.

https://github.com/dotnet/msbuild/blob/f914c9bfb613d32edb658b803c7fe046f9ee3c37/src/MSBuild/XMake.cs#L2918

### Steps to Reproduce

Create a `.sln` and `dirs.proj` in the same folder. Add `-ignoreProjectExtensions:.sln` to your `Directory.Build.rsp` file.

### Expected Behavior

```
F:\src\repo>msbuild.exe -ignoreProjectExtensions:.sln
MSBuild version 17.8.3+195e7f5a3 for .NET Framework
Restore complete (2.0s)
  F:\src\repo\dirs.proj Restore (2.0s)
...
```

### Actual Behavior

```
F:\src\repo>msbuild.exe
MSBuild version 17.8.3+195e7f5a3 for .NET Framework
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by f-alizada**
Fixes #9507

### Context
The ignoreProjectExtensions are not respected if specidified in response file on project level. 
The exception will be thrown in case there are ambiguous files identified in provided directory. Example:
Directiory contains: 
>     1.sln 
>     2.csproj 

The build fails since there are multiple files identified to build. 
IgnoreProjectExtensions: .sln solves the situation but when specified in response file on project level the error will raise before the usage of the response file. 

### Changes Made
Identifying projectFile was extracted from CheckAndGatherProjectAutoResponseFile, and moved to ProcessCommandLineSwitches. 

### Testing
Added specific to the case test case
All existing tests should pass

### CODE REVIEW

File: src/MSBuild/XMake.cs [hunk 1]
```diff
@@ -2556,6 +2556,9 @@ private static bool GatherAutoResponseFileSwitchesFromFullPath(string autoRespon
                                                            commandLine);
                     }
 
+                    // why not process the project parameter here?
```
[the remark this answers is not in the document]
Comment (f-alizada) [reply src/MSBuild/XMake.cs:2559]: 100% agree, this was my initial idea to move the logic one level up from inner methods, will remove the comment thank you for noticing!

[the remark this answers is not in the document]
Comment (f-alizada) [reply src/MSBuild/XMake.cs]: Removed, thanks one more time.

File: src/MSBuild.UnitTests/XMake_Tests.cs [hunk 2]
```diff
@@ -1524,6 +1524,44 @@ public void ResponseFileInProjectDirectoryButCommandLineNoAutoResponseSwitch()
...
+        /// <summary>
+        /// Directory.Build.rsp in the directory of the specified project/solution should be respected when searching the files (solution/proj) to build.
+        /// </summary>
+        [Fact]
+        public void ResponseFileInProjectDirectoryWithSolutionProjectDifferentNamesShouldBeRespected()
+        {
+            string directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
+            string projectPath = Path.Combine(directory, "projectFile.proj");
+            string solutionPath = Path.Combine(directory, "solutionFile.sln");
+            string rspPath = Path.Combine(directory, "Directory.Build.rsp");
```
[the remark this answers is not in the document]
Comment (f-alizada) [reply src/MSBuild.UnitTests/XMake_Tests.cs]: Thank you for pointing out, updated

[the remark this answers is not in the document]
Comment (f-alizada) [reply src/MSBuild.UnitTests/XMake_Tests.cs]: @JanKrivanek The pr #9682  tries to resolve the possible future comments like that. At least for this file :)

**Review by JanKrivanek — APPROVED** [review]
Looks good! Thanks for addressign comments!

File: src/MSBuild/XMake.cs [hunk 3]
```diff
@@ -2912,18 +2914,43 @@ private static CommandLineSwitches CombineSwitchesRespectingPriority(CommandLine
...
         {
-            bool found = false;
+            string projectDirectory = ".";
+            ErrorUtilities.VerifyThrow(projectSwitchParameters.Length <= 1, "It should not be possible to specify more than 1 project at a time.");
 
-            // figure out what project we are building
-            projectFile = ProcessProjectSwitch(commandLineSwitches[CommandLineSwitches.ParameterizedSwitch.Project], commandLineSwitches[CommandLineSwitches.ParameterizedSwitch.IgnoreProjectExtensions], Directory.GetFiles);
+            if (projectSwitchParameters.Length == 1)
+            {
+                var projectFile = FileUtilities.FixFilePath(projectSwitchParameters[0]);
```
Comment (rainersigwald) [inline src/MSBuild/XMake.cs:2924]: What's the motivation for `FixFilePath` here?

File: src/MSBuild/XMake.cs [hunk 4]
```diff
@@ -2912,18 +2914,43 @@ private static CommandLineSwitches CombineSwitchesRespectingPriority(CommandLine
             return commandLineSwitches;
         }
 
-        private static bool CheckAndGatherProjectAutoResponseFile(CommandLineSwitches switchesFromAutoResponseFile, CommandLineSwitches commandLineSwitches, bool recursing, string commandLine, out string projectFile)
+        private static string GetProjectDirectory(string[] projectSwitchParameters)
         {
-            bool found = false;
+            string projectDirectory = ".";
+            ErrorUtilities.VerifyThrow(projectSwitchParameters.Length <= 1, "It should not be possible to specify more than 1 project at a time.");
```
Comment (rainersigwald) [inline src/MSBuild/XMake.cs:2920]: It isn't now, so this assert is good, but I'd change the comment since some users have asked for this (though I can't find an issue).
```suggestion
            ErrorUtilities.VerifyThrow(projectSwitchParameters.Length <= 1, "Expect exactly one project at a time.");
```

File: src/MSBuild/XMake.cs [hunk 5]
```diff
@@ -2912,18 +2914,43 @@ private static CommandLineSwitches CombineSwitchesRespectingPriority(CommandLine
...
+
+                if (FileSystems.Default.DirectoryExists(projectFile))
+                {
+                    // the provided argument value is actually the directory
+                    projectDirectory = projectFile;
+                }
+                else
+                {
+                    InitializationException.VerifyThrow(FileSystems.Default.FileExists(projectFile), "ProjectNotFoundError", projectFile);
+                    projectDirectory = Path.GetDirectoryName(Path.GetFullPath(projectFile));
```
Comment (rainersigwald) [inline src/MSBuild/XMake.cs:2934]: This combination of calls reads slightly oddly to me. Should you normalize the path before passing it to FileExists?

**Review by rainersigwald — APPROVED** [review]

File: src/MSBuild/XMake.cs (hunk 4 above)
Comment (f-alizada) [reply src/MSBuild/XMake.cs]: Updated the text, thank you!

File: src/MSBuild/XMake.cs (hunk 5 above)
Comment (f-alizada) [reply src/MSBuild/XMake.cs:2934]: May I clarify which scenarios it should cover? (normalizing the path before verification)

File: src/MSBuild/XMake.cs (hunk 3 above)
Comment (f-alizada) [reply src/MSBuild/XMake.cs:2924]: To properly handle the path provided in case we are running in unix like os.

Comment (rainersigwald) [reply src/MSBuild/XMake.cs:2924]: I don't think I fully understand why `ProcessProjectSwitch` has it but "it's just like that" is plenty of justification.
