### PR TITLE
Bypass logcontext validity check

### LINKED ISSUE #10342: [Bug]: MSBuild crashes with "MSB0001: Internal MSBuild Error: must be valid"
### Issue Description

Copied from https://github.com/dotnet/dnceng/issues/3304

I queried Kusto and it seems we started seeing this more often after we bumped the VMR build to use a bleeding-edge preview 7 SDK. I see one hit in the last 60 days but since we bumped to P7 SDK about 10 hours ago we already hit this three times.

```
    MSBUILD : error MSB4166: Child node "3" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTemproot/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
    MSBUILD : error MSB4166: /tmp/MSBuildTemproot/MSBuild_pid-14914_ef532437860e4947b63c7a07fa167972.failure.txt:
    MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 14914:
    MSBUILD : error MSB4166: =====================
    MSBUILD : error MSB4166: 07/08/2024 11:37:54
    MSBUILD : error MSB4166: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: must be valid
    MSBUILD : error MSB4166:    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
    MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Logging.LoggingContext.LogBuildEvent(BuildEventArgs buildEvent)
    MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args)
    MSBUILD : error MSB4166: ===================
    MSBUILD : error MSB4166: 
```

### Steps to Reproduce

Build the VMR repo. The failure only happens occasionally.

### Expected Behavior

No crash.

### Actual Behavior

There is a crash.

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by JanKrivanek**
Fixes #10342

### Context
This change workarounds the attempts to log assembly loads via LoggingContext that was invalidated

### Theory for rootcause
The `AssemblyLoad` is AppDomain wide - and doesn't 'respect' current thread nor async context. So if we mount it in one execution context and concurrently executing code leads to assembly loading - it'll still be reported. The handler is executed synchronously - meaning the originally mounting code can be continuing execution and eventually invalidating the passed LoggingContext.

### Analysis Details
The added diagnostic showed the context tha was invalid was `TaskLoggingContext`, it as well showed that it was happening in msbuild within sdk (hence core version).

The `TaskLoggingContext` is passed to Tracker in 2 locations:

https://github.com/dotnet/msbuild/blob/486dbb4a9a7885b8fdcb1f8affd4d63444d8d8e4/src/Build/Instance/TaskFactories/AssemblyTaskFactory.cs#L389-L392

This is not part of core version - so out of question for us

And

https://github.com/dotnet/msbuild/blob/486dbb4a9a7885b8fdcb1f8affd4d63444d8d8e4/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs#L648-L671

Here the tracker is wrapped in using - so the LoggingContex would need to be invalidated in this scope (or passed already invalid).

`TaskLoggingContext` is allways created valid (`IsValid` set to `true` in constructor) and only invalidated in

https://github.com/dotnet/msbuild/blob/486dbb4a9a7885b8fdcb1f8affd4d63444d8d8e4/src/Build/BackEnd/Components/Logging/TaskLoggingContext.cs#L125-L136

which is called in a single place - in `ExecuteBucket`, which is outer scope for `InitializeAndExecuteTask` that contains the tracker call. The `InitializeAndExecuteTask` is async - but it doesn't influence the Dispose scope.

BUT - the fact that the mounting method (`InitializeAndExecuteTask`) is async suggest that there likely might be concurrently executing code.

This points to tracker actually logging an assembly load event from unrelated thread - supported by the fact that the AssemblyLoadsTracker seems to be on the very 'bottom' of the stack:

image

While the handler should be executed synchronously - so we'd expect the `TaskBuilder` frames below the tracker frames.

Simple unrelated test of trying to mount `AssemblyLoad` event in main function with simple console output, shows that the assembly loads can be reported from unrelated threads (while those 'hide' their frames, as they are not considered 'user code'):

image

Based on the stats from builds - this was happening as well in the past - just not that often. So it's not a new regression, just some change (our or arcade) increased parallel execution or loading of assemblies on other threads.

In ideal situation we'd 'somehow' filter out the assembly load events that are from different `AsyncContext`/`ExecutionContext`/`SynchronizationContext` than the one requesting the tracking - but it is currently not worth the efforts.

### CODE REVIEW

File: src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs [hunk 1]
```diff
@@ -171,7 +171,8 @@ private void CurrentDomainOnAssemblyLoad(object? sender, AssemblyLoadEventArgs a
             if (_loggingContext?.BuildEventContext != null)
             {
                 buildArgs.BuildEventContext = _loggingContext.BuildEventContext;
-                _loggingContext.LogBuildEvent(buildArgs);
+                // bypass the logging context validity check
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs:174]:
```suggestion
                // bypass the logging context validity check: it's possible that the load happened
                // on a thread unrelated to the context we're tracking loads in
```

**Review by rainersigwald — APPROVED** [review]

**Review by maridematte — APPROVED** [review]
