### PR TITLE
Fix for Build Requests with Different Flags Not Correctly Scheduled

### LINKED ISSUE #11701: VS DTB Hangs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2347204/

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2357615/

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
### Context
When two build requests with the same configuration ID and targets arrive in the scheduler, the second one is expected to be satisfied from the cache with results from the first request. However, the current implementation doesn't properly account for differing `BuildRequestDataFlags` between these requests, leading to potential deadlocks.

### Problem
If the first request builds successfully but isn't cached (due to exceptions or skipped targets), the second request can get "orphaned" in the scheduler - it's not executed and doesn't send a proper completion callback. This causes Visual Studio to hang indefinitely waiting for a response that never comes.

### Changes Made
- Modified the scheduler to properly handle cases where a request's results should be in the cache but aren't
- Added detailed comments explaining the previously problematic behavior that caused VS deadlocks
- Ensured that when cache misses occur, the unscheduled request remains in the queue and gets picked up in the next scheduling pass for proper rebuilding

### Testing
- Added unit tests that verify correct handling of build requests with different flags

### CODE REVIEW

File: src/Build.UnitTests/BackEnd/Scheduler_Tests.cs [hunk 1]
```diff
@@ -768,12 +773,13 @@ private BuildResult CacheBuildResult(BuildRequest request, string target, WorkUn
         }
 
         /// <summary>
-        /// Creates a build result for a request
+        /// Creates a build result for a request.
         /// </summary>
         private BuildResult CreateBuildResult(BuildRequest request, string target, WorkUnitResult workUnitResult)
```
Comment (SimaTian) [inline src/Build.UnitTests/BackEnd/Scheduler_Tests.cs:778]: Somewhat unrelated, but as good place as any to ask:
isn't there a saner way of doing these sort of overloads?
I get what these are meant to achieve, but when something goes wrong, stepping through 3+ levels of overloaded wrappers that just call another wrapper is a pain.

Comment (SimaTian) [reply src/Build.UnitTests/BackEnd/Scheduler_Tests.cs:778]: Something like default values where possible to limit the overload layering.

**Review by SimaTian — APPROVED** [review]

**Review by rainersigwald — APPROVED** [review]
