### PR TITLE
Fix flaky test  CanShutdownServerProcess

### LINKED ISSUE #8631: [Infra]: CanShutdownServerProcess test is fleaky
### Issue Description

The `CanShutdownServerProcess` fails every now an then:

image

not too often to be easily caught, but often enough to fail considerable number of PRs (hence already worth a dedicated item)

### Details

```
Error message
Shouldly.ShouldAssertException : False\n    should be\nTrue\n    but was not

Stack trace
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual)
   at Microsoft.Build.Engine.UnitTests.MSBuildServer_Tests.CanShutdownServerProcess(Boolean byBuildManager) in /home/vsts/work/1/s/src/MSBuild.UnitTests/MSBuildServer_Tests.cs:line 247
   at InvokeStub_MSBuildServer_Tests.CanShutdownServerProcess(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Sample run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=227421&view=ms.vss-test-web.build-test-results-tab&runId=4282826&resultId=100005&paneView=debug

### PR DESCRIPTION
**Pull request by rokonec**
Fixes #8631

### Context
We have got him!
There was eluding low freq flaky test. It was caused by race condition between finishing build server client and server releasing its `I am busy` mutex.

### Changes Made
Wait and retry when it was detected busy for 500 ms.
Clean additional logging from test.

### Testing
Local, PR

### CODE REVIEW

File: src/Build/BackEnd/Client/MSBuildClient.cs [hunk 1]
```diff
@@ -291,6 +292,20 @@ private bool TryShutdownServer(CancellationToken cancellationToken)
             return _exitResult.MSBuildClientExitType == MSBuildClientExitType.Success;
         }
 
+        private bool ServerIsBusyWithWaitAndRetry(int milliseconds)
+        {
+            bool isBusy = ServerWasBusy();
+            Stopwatch sw = Stopwatch.StartNew();
+            while (isBusy && sw.Elapsed < TimeSpan.FromMilliseconds(milliseconds))
```
Comment (rainersigwald) [inline src/Build/BackEnd/Client/MSBuildClient.cs:299]:
```suggestion
            while (isBusy && sw.ElapsedMilliseconds < milliseconds)
```

?

File: src/Build/BackEnd/Client/MSBuildClient.cs [hunk 2]
```diff
@@ -265,9 +265,10 @@ private bool TryShutdownServer(CancellationToken cancellationToken)
                 return true;
             }
 
-            // Check that server is not busy.
-            bool serverWasBusy = ServerWasBusy();
-            if (serverWasBusy)
+            // Check and wait for server to be not busy for some short time to avoid race condition when server reports build is finished but had not released ServerBusy mutex yet.
```
Comment (rainersigwald) [inline src/Build/BackEnd/Client/MSBuildClient.cs:268]: Would it make sense to ensure this never happens by releasing ServerBusy before reporting the finish? Or does that violate other invariants?

**Review by rainersigwald — APPROVED** [review]

File: src/Build/BackEnd/Client/MSBuildClient.cs (hunk 2 above)
Comment (rokonec) [reply src/Build/BackEnd/Client/MSBuildClient.cs:268]: I thought about it. It is hard to me to identify and understand all consequences. In theory it shall be fine, report server not busy when its namedpipe connection still sending data to finishing client shall be fine, since worst case we fall back to non server because namedpipe could not be opened. But is sending final build result to client part of being busy? I think it is? So declaring not busy while still doing something related with just finished build is a little bit laying :-)

All in all, I just consider my changes slightly less risky.

File: src/MSBuild.UnitTests/MSBuildServer_Tests.cs [hunk 3]
```diff
@@ -221,10 +221,6 @@ public void CanShutdownServerProcess(bool byBuildManager)
         {
             _env.SetEnvironmentVariable("MSBUILDUSESERVER", "1");
 
-            // This test seems to be flaky, lets enable better logging to investigate it next time
-            // TODO: delete after investigated its flakiness
-            _env.WithTransientDebugEngineForNewProcesses(true);
```
[the remark this answers is not in the document]
Comment (rokonec) [reply src/MSBuild.UnitTests/MSBuildServer_Tests.cs:226]: I am confident, but also I was wrongly confident in past few times, but we can easily put it back with, hopefully not happening, next failure.

**Review by ladipro — APPROVED** [review]
