### PR TITLE
Make matching case insensitive regardless of OS Fixes #5749

### LINKED ISSUE #5749: CopyToOutputDirectory is suddenly case sensitive as of 3.1.401
### Issue Description

As of SDK 3.1.401 the CopyToOutputDirectory task seems to be case sensitive when running in Linux. This makes sense, but I couldn't find any mention of it in the release notes, and it's a breaking change. Given this is a _build_ version release increment, I'm assuming the breaking change isn't intentional - so thought I'd report it. Feel free to close if this isn't the case.

I've attached an example project in a zip, which shows this issue which can be run with Docker. Note at the top of the `Dockerfile` I have two lines specifying different versions of the SDK...

```Dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.401 AS build
#FROM mcr.microsoft.com/dotnet/core/sdk:3.1.302 AS build
```

The docker file just does an `ls` after the build...

```Dockerfile
RUN ls -l /src/bin/Release/netcoreapp3.1/
```

Doing a `docker build .` using 3.1.401 fails to copy testsettings.json (as you can see in the `ls` output). Doing it with 3.1.302 works.

This broke one of our builds because we were using `mcr.microsoft.com/dotnet/core/sdk:3.1` as the base image, so as soon as 3.1.401 got released, our builds started breaking. Obviously an easy fix once we knew what it was - but it's wasn't immediately obvious why this had suddenly broken.

[dotnetbug.zip](https://github.com/dotnet/msbuild/files/5260475/dotnetbug.zip)

### PR DESCRIPTION
**Pull request by Forgind**
First commit: update a test such that it passes only if matching is case insensitive.
Second commit: modify FileUtilities.ComparePathsNoThrow such that it can be made to be always case sensitive or case insensitive. Note that this was changed about seven months ago in [#4997](https://github.com/dotnet/msbuild/pull/4997) where it had previously been a todo to make case sensitivity depend on OS but that implemented it.
Third commit: fix a test that theoretically ensured case insensitivity but in practice did not, changed to care about case in the same PR.

The second commit fixes #5749.

### CODE REVIEW

File: src/Build/Utilities/FileSpecMatchTester.cs [hunk 1]
```diff
@@ -42,7 +43,7 @@ public bool IsMatch(string fileToMatch)
                 return _regex.IsMatch(normalizedFileToMatch);
```
Comment (BenVillalobos) [inline src/Build/Utilities/FileSpecMatchTester.cs:43]: Shouldn't we account for ignoring case here as well?

**Review by BenVillalobos — COMMENTED** [review]
What exactly regressed #5749?

Should we consider leaving relevant operating systems case sensitive under a change wave?

**Comment by Forgind** [comment]
https://github.com/dotnet/msbuild/pull/4997/files#diff-b62db5f7e7f90841af8ef58195eb4318cabc0742747ba3f2e97f10cfa21d6658L56-R80 was the change that brought it in. Totally reasonable, but it changed behavior from "todo: choose case-sensitivity based on OS" to actually doing that.

File: src/Shared/FileUtilities.cs [hunk 2]
```diff
@@ -735,19 +735,21 @@ internal static string GetFullPathNoThrow(string path)
         /// <param name="first"></param>
         /// <param name="second"></param>
         /// <param name="currentDirectory"></param>
+        /// <param name="alwaysIgnoreCase"></param>
         /// <returns></returns>
-        internal static bool ComparePathsNoThrow(string first, string second, string currentDirectory)
+        internal static bool ComparePathsNoThrow(string first, string second, string currentDirectory, bool alwaysIgnoreCase = false)
```
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Shared/FileUtilities.cs:740]: I prefer alwaysIgnoreCase because putting `false` here doesn't mean that you're case sensitive but that it depends on the OS.

File: src/Build/Utilities/FileSpecMatchTester.cs (hunk 1 above)
Comment (Forgind) [reply src/Build/Utilities/FileSpecMatchTester.cs:43]: Absolutely. The beautiful (terrible?) part is that it already ignored case:
https://github.com/dotnet/msbuild/blob/master/src/Shared/FileMatcher.cs#L51

I can add a test for that, though.

**Comment by BenVillalobos** [comment]
@marcpopMSFT we'd like your thoughts on retroactively putting this behind a changewave.

**Comment by marcpopMSFT** [comment]
Putting it in a change waves means that once 17 releases, this would no longer be controllable.  Is the customer open to changing by then and is that the ultimate behavior we want to drive towards?  We could put a flag in just for this customer to opt out but that'll complicate our testing.  I don't think we'd want to go back to the way we were before since it's already been two releases this way and going back could break other customers (though is admittedly less likely to break customers than switching to be case-sensitive)

**Comment by Forgind** [comment]
@marcpopMSFT, we haven't asked, and I don't think it's obvious that that's what we should drive towards. It's probably the best way, but it's hard to take advantage of that in our case, so I'd consider it only slightly beneficial and slightly more of a breaking change.

For clarity, for going back to break someone, they would have had to:
1) Be developing on Linux,
2) Have two files with the same path but different casings,
3) Have item operations that apply to one but not the other of them, and
4) Have added that very recently.

**Comment by marcpopMSFT** [comment]
@Forgind , I wasn't that worried about the impact of reversing this as you pointed out, it's more likely for folks to have been impacted by the original change than the revert. The question comes back to what is the right long term behavior? Do customers want it to be case sensitive or insensitive or OS dependent? Reverting solves the current problem.

**Comment by rainersigwald** [comment]
Let's just go with "updates are case insensitive, period".

1. It's hard to know whether a system is case sensitive.
2. It was always this way until very recently, which surprised and broke people.
3. This is the most Windowsy thing, and we have a long Windows heritage (even if we now wish many aspects of our behavior are more UNIXy).

**Comment by Forgind** [comment]
In that case, this and #5853 are good to go, as far as I know.

**Review by rainersigwald — APPROVED** [review]
