### PR TITLE
Don't hang builds on BuildManager internal errors

### LINKED ISSUE #5911: Build hangs with MSBUILDNODECONNECTIONTIMEOUT=0
### Issue Description
MSBuild hangs when attempting to build with the `MSBUILDNODECONNECTIONTIMEOUT` environment variable set to 0.

### Steps to Reproduce
```
set MSBUILDNODECONNECTIONTIMEOUT=0
msbuild repro.proj
```

repro.proj:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Build">
    <Message Text="Hello world!" />
  </Target>
</Project>
```

### Expected Behavior
The build fails with an internal error like "In-proc node failed to start up within 0ms".

### Actual Behavior
The build hangs.

### Analysis
Caused by the `BuildSubmission` not getting completed if an exception categorized as "critical" is thrown.

The exception is thrown here:
https://github.com/dotnet/msbuild/blob/f762c3942e78bdb1d0ba60f88641133a3a512734/src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs#L370

And caught here:
https://github.com/dotnet/msbuild/blob/f762c3942e78bdb1d0ba60f88641133a3a512734/src/Build/BackEnd/BuildManager/BuildManager.cs#L1216

### Versions & Configurations
Version 16.8.2+25e4d540b

### PR DESCRIPTION
**Pull request by ladipro**
The logic to handle exceptions thrown on logging and communication threads was trying to make the build submission fail with the exception but it didn't always complete it. This manifested as the build hanging, for example when building with `MSBUILDNODECONNECTIONTIMEOUT = 0`, which is almost guaranteed to throw `InternalErrorException` in `InstantiateNode`.

This PR fixes it by making sure that all submissions are completed in `OnThreadException`. Unlike the original code, proper care is taken to avoid race conditions - i.e. the build result is mutated only if hasn't already been passed to the completion handler.

Fixes #5911

### CODE REVIEW

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 1]
```diff
@@ -2184,20 +2184,13 @@ private void OnThreadException(Exception e)
                             continue;
                         }
 
-                        submission.CompleteLogging(false);
```
Comment (ladipro) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:2187]: Note that this call could have completed the submission and mutating the build result a few lines below could have run in parallel with the completion handler and cause grief.

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 2]
```diff
@@ -2184,20 +2184,13 @@ private void OnThreadException(Exception e)
...
-                                submission.BuildResult = new BuildResult(submission.BuildRequest, e);
-                            }
-                            else
-                            {
-                                submission.BuildResult.Exception = _threadException.SourceException;
-                            }
+                            submission.BuildResult.Exception = e;
                         }
+                        submission.CompleteLogging(false);
+                        submission.CompleteResults(new BuildResult(submission.BuildRequest, e));
```
Comment (ladipro) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:2193]: `CompleteResults` doesn't change the result if already non-null so this matches the old behavior.

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 3]
```diff
@@ -2211,17 +2204,11 @@ private void OnThreadException(Exception e)
...
                         {
-                            if (submission.BuildResult == null)
-                            {
-                                submission.BuildResult = new GraphBuildResult(submission.SubmissionId, e);
-                            }
-                            else
-                            {
-                                submission.BuildResult.Exception = _threadException.SourceException;
-                            }
+                            submission.BuildResult.Exception = e;
```
Comment (ladipro) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:2209]: Note that `e` is the same as `_threadException.SourceException` in the old code.

File: src/Build.UnitTests/BackEnd/BuildManager_Tests.cs [hunk 4]
```diff
@@ -4093,6 +4093,32 @@ public void IdenticalSubmissionsShouldCompleteAndNotHangTheBuildOnMissingTargetE
             }
         }
 
+        [Fact]
+        public void BuildWithZeroConnectionTimeout()
+        {
+            string contents = CleanupFileContents(@"
```
Comment (Forgind) [inline src/Build.UnitTests/BackEnd/BuildManager_Tests.cs:4099]: I'm a little confused why this works. If _env is reused, shouldn't this affect other tests? And why doesn't this build in-proc, avoiding the node connection timeout? (I saw that _env had set MSBUILDINPROCENVCHECK to 1, but I didn't really understand what that was doing.)

Comment (ladipro) [reply src/Build.UnitTests/BackEnd/BuildManager_Tests.cs:4099]: > If _env is reused, shouldn't this affect other tests?

No, `_env` is an instance field on the test and a new instance is created for each test case. I believe that this is a relevant reference: https://xunit.net/docs/shared-context

> And why doesn't this build in-proc, avoiding the node connection timeout?

It does build in-proc. The bug actually reproduces with single-proc builds. It threw me off as well until I realized that `NodeProviderInProc` starting a new thread in the current process and waiting for it to get initialized is where the env var is used.

Comment (Forgind) [reply src/Build.UnitTests/BackEnd/BuildManager_Tests.cs:4099]: Neat, thanks!

**Review by Forgind — APPROVED** [review]

File: src/Build.UnitTests/BackEnd/BuildManager_Tests.cs [hunk 5]
```diff
@@ -4093,6 +4093,32 @@ public void IdenticalSubmissionsShouldCompleteAndNotHangTheBuildOnMissingTargetE
...
+            {
+                BuildResult result = _buildManager.Build(_parameters, data);
+
+                // The build should either finish successfully (very unlikely).
+                result.OverallResult.ShouldBe(BuildResultCode.Success);
+            }
+            catch (InternalErrorException)
+            {
+                // Or it should throw InternalErrorException because the node didn't get connected within 0ms.
+            }
```
Comment (rainersigwald) [inline src/Build.UnitTests/BackEnd/BuildManager_Tests.cs:4119]:
```suggestion
            catch (Exception e)
            {
                // Or it should throw InternalErrorException because the node didn't get connected within 0ms.
                e.ShouldBeOfType<InternalErrorException>();
            }
```

?

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 6]
```diff
@@ -2184,20 +2184,13 @@ private void OnThreadException(Exception e)
                             continue;
                         }
 
-                        submission.CompleteLogging(false);
-
                         // Attach the exception to this submission if it does not already have an exception associated with it
-                        if (submission.BuildResult?.Exception == null)
+                        if (!submission.IsCompleted && submission.BuildResult != null && submission.BuildResult.Exception == null)
```
Comment (rainersigwald) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:2188]: Doesn't `submission.BuildResult?.Exception == null` mean the same thing as `submission.BuildResult != null && submission.BuildResult.Exception == null`? [SharpLab](https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYGYAE9MGFMDeqmJ2WMALJgLIAUAlIcaSwMoCuARgLZgDOfMAHsAdpj5deA4WIC8mEQFMA7pg49+g0QwDczFiX0GwAM0y0AhBI3TRAOgCSfXEO4AHCIuCKAJpgBk/uKSmjJ2AELskD4ASooSEMCYFvIi7BAQAUHWUloiEVEQsfHpwHYAogAeAMaKbsAymLKp6RD0RiwA9J2YpuZWIbb5Ti7unt5+gcE2eQXRcQnAAPwVNXUNok0tGe0oBqREe/uYAL5GZygXGNhwaoN5qIcs15xCQpkjrh5evnpHJNdIvMSolMECigtSn8ruRbuDiotHkZrlVavVGqj1jJoaggA==) shows an IL difference but it appears to just not be loading the `BuildResult` field twice in the `?.` version.

**Review by rainersigwald — APPROVED** [review]

File: src/Build/BackEnd/BuildManager/BuildManager.cs (hunk 6 above)
Comment (Forgind) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:2188]: If submission.BuildResult is null, submission.BuildResult?.Exception is null; `?` is like `<thing before> == null ? null : <thing before>.<thing after>`.

(I ran [this](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcDMACR2DC2A3utmbggsaebXEgAzYAO2AvNlBADbcDcNWmXoBOABTMA/ADoAcgHswAWwCG3AJYAvAKZiAlOw5deegWloBfdFbRA).)

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 7]
```diff
@@ -2184,20 +2184,13 @@ private void OnThreadException(Exception e)
...
-                            {
-                                submission.BuildResult = new BuildResult(submission.BuildRequest, e);
-                            }
-                            else
-                            {
-                                submission.BuildResult.Exception = _threadException.SourceException;
-                            }
+                            submission.BuildResult.Exception = e;
                         }
+                        submission.CompleteLogging(false);
```
Comment (danmosemsft) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:2192]: Nit, for readability, consider named parameters for passing literals? ie `submission.CompleteLogging(waitForLoggingThread:false)`

File: src/Build.UnitTests/BackEnd/BuildManager_Tests.cs [hunk 8]
```diff
@@ -4093,6 +4093,32 @@ public void IdenticalSubmissionsShouldCompleteAndNotHangTheBuildOnMissingTargetE
             }
         }
 
+        [Fact]
+        public void BuildWithZeroConnectionTimeout()
+        {
+            string contents = CleanupFileContents(@"
+<Project xmlns='msbuildnamespace' ToolsVersion='msbuilddefaulttoolsversion'>
```
[the remark this answers is not in the document]
Comment (ladipro) [reply src/Build.UnitTests/BackEnd/BuildManager_Tests.cs]: Done, thanks!

File: src/Build/BackEnd/BuildManager/BuildManager.cs (hunk 7 above)
Comment (ladipro) [reply src/Build/BackEnd/BuildManager/BuildManager.cs]: Done!

File: src/Build/BackEnd/BuildManager/BuildManager.cs (hunk 6 above)
Comment (ladipro) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:2188]: With value type fields, one can write something like `submission.BuildResult?.SomeFlag == false` and this is equivalent to `submission.BuildResult != null && submission.BuildResult.SomeFlag == false`. But it doesn't work with reference type fields as the type of `submission.BuildResult?.Exception` is just `Exception` and if it evaluates to `null`, you can't tell which of the two is `null`.

Comment (rainersigwald) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:2188]: You're right; it's the null-to-bool comparison that saves the former case which doesn't apply here.
