### PR TITLE
Find dotnet.exe instead of <name>.exe when building out-of-proc using MSBuildLocator

### LINKED ISSUE #6782: Out-of-proc builds in a custom .NET Core process are not possible
### Issue Description
If you write a custom application in .NET Core, use MSBuildLocator to find .NET Core MSBuild, and attempt to do an out-of-process build, then the MSBuild BuildManager will attempt to launch the node as the user's custom application.

### Steps to Reproduce
* Create a custom .NET Core application named `Foo.exe`
* Use MSBuildLocator to find MSBuild in .NET Core
* Build a project with `DisableInProcNode` set to `true`

### Expected Behavior
MSBuild APIs correctly build project out-of-proc

### Actual Behavior
MSBuild APIs attempt to launch an out-of-proc node with `Foo.exe` instead of `MSBuild.exe`

### Analysis
This is happening because this call:

https://github.com/dotnet/msbuild/blob/aac64bbabfcea279aa34875563848003887e8c84/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L483

But GetCurrentHost assumes that MSBuild.exe is the entry application which is not always correct:

https://github.com/dotnet/msbuild/blob/aac64bbabfcea279aa34875563848003887e8c84/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L594-L608

In some cases, the current process is not MSBuild.exe.

Instead, this code should use the current `dotnet.exe` that is running that application and use the MSBuild location which is already done here:

https://github.com/dotnet/msbuild/blob/aac64bbabfcea279aa34875563848003887e8c84/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L435-L437

There is another bug where we prepend the path to MSBuild.dll twice:

https://github.com/dotnet/msbuild/blob/aac64bbabfcea279aa34875563848003887e8c84/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L484

But that doesn't seem to break anything as dotnet.exe correctly ignores that it was given two applications to run!

### Versions & Configurations
Any version of .NET Core MSBuild

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #6782

### Context
When using MSBuildLocator, the first process you start is named after your app, not dotnet or msbuild, yet it still loads MSBuild assemblies. When it then starts an out-of-proc build on core, it tries to use the current host, which is normally dotnet.exe, but in this case is <yourApp>.exe. MSBuild can't find it to connect, so it assumes it launches another node. It should stop after that, but it just keeps going and makes hundreds or thousands of nodes until your computer crashes. That is bad. This defaults to looking for a nearby dotnet.exe (if you're on core) and uses that instead, falling back to <yourApp>.exe only on failure. This should handle any case in which you find MSBuild in an sdk installation.

### Changes Made
Look for a dotnet.exe instead of your current host.

### Testing
Broke repro.

### Notes
Do not try to reproduce this naively. Your computer will be unhappy.

Also, I suspect this may have been the cause of my 9/10 comment [here (internal link)](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1371725).

### CODE REVIEW

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 1]
```diff
@@ -480,8 +479,8 @@ private Process LaunchNode(string msbuildLocation, string commandLineArgs)
             if (!NativeMethodsShared.IsMono)
             {
                 // Run the child process with the same host as the currently-running process.
-                exeName = GetCurrentHost();
-                commandLineArgs = "\"" + msbuildLocation + "\" " + commandLineArgs;
+                string dotnetExe = Path.Combine(FileUtilities.GetFolderAbove(exeName, 2), "dotnet.exe");
+                exeName = File.Exists(dotnetExe) ? dotnetExe : GetCurrentHost();
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:483]: Would it make sense to push this into `GetCurrentHost()` so we only have to do the file-exists check once?

**Review by rainersigwald — APPROVED** [review]

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 2]
```diff
@@ -480,8 +479,8 @@ private Process LaunchNode(string msbuildLocation, string commandLineArgs)
             if (!NativeMethodsShared.IsMono)
             {
                 // Run the child process with the same host as the currently-running process.
-                exeName = GetCurrentHost();
-                commandLineArgs = "\"" + msbuildLocation + "\" " + commandLineArgs;
+                string dotnetExe = Path.Combine(FileUtilities.GetFolderAbove(exeName, 2), "dotnet.exe");
```
Comment (jeffkl) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:482]: There is a lot going on in this method:

* On Windows, it uses native methods to launch the process so the path to `MSBuild.exe` needs to be prepended to the command-line arguments.  @rainersigwald do you know why we use a different method to launch the process?  The code doesn't seem to need to as far as I can tell.  Maybe we can get rid of it?
* For .NET Core, the command-line arguments must be prepended with the the path to `MSBuild.dll` and the EXE is `dotnet`.

I see some missing logic in the current implementation:

* On Windows, its `dotnet.exe`, on non-Windows its just `dotnet`
* The path to `MSBuild.dll` is prepended twice on Windows (which technically works but sees dirty)
* `GetCurrentHost()` is only ever correct if you run `dotnet` directly so using it as a fallback seems not great
* 

I would do the following:

1. Make a method like `GetNodeExe()` that has all of the logic to find the path to the executable that represents the node, so `MSBuild.exe` on .NET Framework, `dotnet.exe` or `dotnet` for .NET Core.
2. Make a method like `GetNodeArguments()` that adjusts the command-line arguments
  Prepend `MSBuild.exe` on Windows since its using native APIs
  Prepend `MSBuild.dll` on .NET Core

In my opinion that would simplify this method and make it easier to rationalize what its doing.  You could also make these two methods `internal` and write a unit test to verify they return the correct values.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 3]
```diff
@@ -466,8 +465,8 @@ private Process LaunchNode(string msbuildLocation, string commandLineArgs)
                 creationFlags |= BackendNativeMethods.CREATE_NEW_CONSOLE;
             }
 
-            BackendNativeMethods.SECURITY_ATTRIBUTES processSecurityAttributes = new BackendNativeMethods.SECURITY_ATTRIBUTES();
-            BackendNativeMethods.SECURITY_ATTRIBUTES threadSecurityAttributes = new BackendNativeMethods.SECURITY_ATTRIBUTES();
+            BackendNativeMethods.SECURITY_ATTRIBUTES processSecurityAttributes = new();
```
Comment (jeffkl) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:468]: These could be moved into the `else` block below where its actually used, unless we get rid of the different ways of launching the process in which case this can just go away.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 2 above)
Comment (Forgind) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:482]: As far as falling back to GetCurrentHost, I agree it isn't terribly likely to succeed, but I don't think we have a better option. There's a chance someone has fancy logic in their project to make it work, and if we don't fall back to GetCurrentHost, we would break that.

Comment (rainersigwald) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs]: I'm pretty sure if you don't fall back to current-host our own dogfood builds will fail (they're invoked via `dotnet.exe path\to\some\msbuild.dll`).

Comment (jeffkl) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs]: > GetCurrentHost() is only ever correct if you run dotnet directly so using it as a fallback seems not great

Sorry what I meant was having this method here only to use as a fallback, when the entirety of the logic could live inside of it.  I did not mean to get rid of the fallback all together.  To have a solid logic here that then falls back to a method seems clunky is all.
