### PR TITLE
Prioritize building .sln if a .sln and .slnf are in the same folder Fixes #5739

### LINKED ISSUE #5739: The build without specifiying *.sln file will fail with error MSB1011 even if it contains only one sln file and an slnf file in the working directory
* .NET Core Version:
    * ❌ 3.1.400 (included in VS 16.7 release)
    * ✔️ 3.1.302 and older
* Visual Studio Version:
    * 16.7.0+b89cb5fde

My working directory contains an sln file and an slnf file. With SDK version 3.1.400, and msbuild command the compilation fails with this error message below which doesn't fail with older versions.

```powershell
> msbuild
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file
```

| .NET SDK Version | Command      | Works or not |
| ---------------- | ------------ | ------------ |
| 3.1.302          | msbuild      | ✔️            |
| 3.1.302          | dotnet build | ✔️            |
| 3.1.400          | msbuild      | ❌            |
| 3.1.400          | dotnet build | ✔️            |

Note: This update (3.1.400) introduces two issues to breaks my project compilation. This one and another https://github.com/dotnet/wpf/issues/2320 .

### PR DESCRIPTION
**Pull request by Forgind**
This occurs because .slnf was treated as a .sln. This resolves #5739 by separating the two at this stage.

### CODE REVIEW

File: src/MSBuild/XMake.cs [hunk 1]
```diff
@@ -2765,62 +2765,21 @@ DirectoryGetFiles getFiles
             // We need to look in a directory for a project file...
             if (projectFile == null)
             {
+                ValidateExtensions(projectsExtensionsToIgnore);
+                HashSet<string> extensionsToIgnore = new HashSet<string>(projectsExtensionsToIgnore ?? Array.Empty<string>(), StringComparer.OrdinalIgnoreCase);
                 // Get all files in the current directory that have a proj-like extension
-                string[] potentialProjectFiles = getFiles(projectDirectory ?? ".", "*.*proj");
+                string[] potentialProjectFiles = (getFiles(projectDirectory ?? ".", "*.*proj") ?? Array.Empty<string>()).Where(s =>
+                    !extensionsToIgnore.Contains(Path.GetExtension(s)) && !s.EndsWith("~", StringComparison.CurrentCultureIgnoreCase)).ToArray();
```
Comment (rainersigwald) [inline src/MSBuild/XMake.cs:2772]: I would rather avoid using LINQ here, since startup time is perf-sensitive and the manual loops are already written. Does this provide some benefit?

Comment (Forgind) [reply src/MSBuild/XMake.cs:2772]: I find this more straightforward and readable. It also involves adding fewer strings to the Dictionary/HashSet, which both reduces its size and reduces time looking through it. That being said, I can convert this back to for loops if you'd prefer with the same benefits. A little more verbose and possibly harder to read but still an improvement in my opinion.

File: src/MSBuild/XMake.cs [hunk 2]
```diff
@@ -2765,62 +2765,53 @@ DirectoryGetFiles getFiles
...
+                                actualSolutionFilterFiles.Add(s);
+                            }
+                            else if (FileUtilities.IsSolutionFilename(s))
+                            {
+                                actualSolutionFiles.Add(s);
+                            }
                         }
                     }
+                    potentialSolutionFiles = actualSolutionFiles.ToArray();
+                    solutionFilterFiles = actualSolutionFiles.ToArray();
```
Comment (rainersigwald) [inline src/MSBuild/XMake.cs:2807]: Do you need to array-ify these? Since they were accumulated as a list and are short-lived local variables (so they can be GCed at return), I don't think there's a big benefit.

File: src/MSBuild/XMake.cs [hunk 3]
```diff
@@ -2765,62 +2765,53 @@ DirectoryGetFiles getFiles
...
-
-                    // No point removing extensions if we have no solutions
-                    if (potentialSolutionFiles?.Length > 0)
-                    {
-                        potentialSolutionFiles = RemoveFilesWithExtensionsToIgnore(potentialSolutionFiles, extensionsToIgnoreDictionary);
-                    }
-                }
                 // If there is exactly 1 project file and exactly 1 solution file
-                if ((potentialProjectFiles.Length == 1) && (potentialSolutionFiles.Length == 1))
+                if (potentialProjectFiles.Length == 1 && (potentialSolutionFiles.Length == 1 || solutionFilterFiles.Length == 1))
```
Comment (rainersigwald) [inline src/MSBuild/XMake.cs:2811]: does this make sense for the filter case?

**Review by rainersigwald — COMMENTED** [review]
Tests?

File: src/MSBuild/XMake.cs (hunk 3 above)
Comment (Forgind) [reply src/MSBuild/XMake.cs:2811]: I'm not 100% sure what's right here. This makes sense to me as it provides a convenient way for you to make it automatically notice the .slnf—just don't have a .sln—but it does technically mean a change in behavior from before we started supporting .slnf, since you could have a .slnf in a folder without a .sln and with a .proj, and it would fall to the check if projectFiles.Length > 1.This would also make it a little harder to notice if you have two .sln files in the folder, since 2 .sln with one .slnf would (with this change) not throw an error but build the .slnf.

The second part is especially problematic in my mind. Do you think I should just revert this change? Revert it then add another check later?

**Comment by Forgind** [comment]
I added one test and the ability to add a lot more tests very fast for when we have decided what the correct behavior should be.

File: src/MSBuild.UnitTests/XMake_Tests.cs [hunk 4]
```diff
@@ -1259,7 +1259,38 @@ private void RunPriorityBuildTest(ProcessPriorityClass expectedPrority, params s
...
+        [InlineData("my.proj my.sln my.slnf my.sln")]
+        [InlineData("abc.proj bcd.csproj slnf.slnf other.slnf abc.proj")]
+        [InlineData("abc.sln slnf.slnf abc.slnf abc.sln")]
+        [InlineData("abc.csproj abc.slnf not.slnf abc.csproj")]
+        [InlineData("abc.slnf abc.slnf")]
+        public void TestDefaultBuildWithSolutionFilter(string projectData)
+        {
+            string[] projects = projectData.Split(' ');
+            string answer = projects[projects.Length - 1];
+            projects = projects.Take(projects.Length - 1).ToArray();
```
Comment (rainersigwald) [inline src/MSBuild.UnitTests/XMake_Tests.cs:1287]: Fun new (C# 8.0) language feature for you:

```suggestion
            string answer = projects[^1];
            projects = projects[..^1].ToArray();
```

[example](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQiAM7EGYAEA3uvqfogkSWTQMIAWAhmANoC6+ANgJYDOw+ALxEA5IxEAafCIBGk6QGMRAXwDc1GqThIAnAAoe/FgD0kbAJTq0mstv2HgLAHRPTFqzWXplQA=)

File: src/MSBuild/XMake.cs [hunk 5]
```diff
@@ -2848,123 +2836,66 @@ DirectoryGetFiles getFiles
...
-
-                // We are down to only one project or solution.
-                // If only 1 solution build the solution.  If only 1 project build the project
-                // If 1 solution and 1 project and they are of the same name build the solution
-                projectFile = (potentialSolutionFiles.Length == 1) ? potentialSolutionFiles[0] : potentialProjectFiles[0];
+                else
+                {
+                    // We are down to only one project, solution filter, or solution.
+                    // If only 1 solution build the solution.  If only 1 project build the project
+                    // If 1 solution and 1 project and they are of the same name build the solution
```
Comment (rainersigwald) [inline src/MSBuild/XMake.cs:2865]:
```suggestion
                    // We are down to only one project, solution filter, or solution.
                    // If only 1 solution or filter build it.  If only 1 project build the project
                    // If 1 solution and 1 project and they are of the same name build the solution
```

**Review by rainersigwald — APPROVED** [review]

File: src/MSBuild.UnitTests/XMake_Tests.cs (hunk 4 above)
Comment (Forgind) [reply src/MSBuild.UnitTests/XMake_Tests.cs:1287]: Cool feature! VS doesn't seem to like it:
image
Does that mean I need to add something to the csproj?

Comment (rainersigwald) [reply src/MSBuild.UnitTests/XMake_Tests.cs:1287]: Looks like we'd need a reference to `System.Runtime` since it's built in only on .NET Core 3+: https://docs.microsoft.com/dotnet/api/system.index

So leave it I guess. Sorry to mislead!

File: src/MSBuild.UnitTests/XMake_Tests.cs [hunk 6]
```diff
@@ -1259,7 +1259,38 @@ private void RunPriorityBuildTest(ProcessPriorityClass expectedPrority, params s
             logContents.ShouldContain(expected, () => logContents);
         }
 
-#region IgnoreProjectExtensionTests
+        /// <summary>
+        /// Test the case where there is one solution file, one solution filter file, and one project file.
+        /// </summary>
+        [Fact]
+        public void TestOneProjectOneSolutionFileOneSolutionFilterFile()
```
Comment (cdmihai) [inline src/MSBuild.UnitTests/XMake_Tests.cs:1266]: I'd prefer a better name. Make it simple, concise, meaningrul. "BlahShouldBlahBlahWhenBlahBlahBlah"

Comment (Forgind) [reply src/MSBuild.UnitTests/XMake_Tests.cs:1266]: Tbh, I should probably just delete this. There's an identical test just below it...

File: src/MSBuild.UnitTests/XMake_Tests.cs [hunk 7]
```diff
@@ -1259,7 +1259,38 @@ private void RunPriorityBuildTest(ProcessPriorityClass expectedPrority, params s
...
+        /// <summary>
+        /// Test the default file to build in cases involving at least one solution filter file.
+        /// </summary>
+        [Theory]
+        [InlineData("my.proj my.sln my.slnf my.sln")]
+        [InlineData("abc.proj bcd.csproj slnf.slnf other.slnf abc.proj")]
+        [InlineData("abc.sln slnf.slnf abc.slnf abc.sln")]
+        [InlineData("abc.csproj abc.slnf not.slnf abc.csproj")]
+        [InlineData("abc.slnf abc.slnf")]
+        public void TestDefaultBuildWithSolutionFilter(string projectData)
```
Comment (cdmihai) [inline src/MSBuild.UnitTests/XMake_Tests.cs:1283]: nit: you can use a string array for the input and another string for the expected output and have them as two separate parameters to the test method to avoid splitting and inferring what the last split means.

Comment (Forgind) [reply src/MSBuild.UnitTests/XMake_Tests.cs:1283]: I actually poked at that a little but had trouble. Is there a good example of that syntax? It didn't like:
`[InlineData(new string[] { ... })]`

Comment (cdmihai) [reply src/MSBuild.UnitTests/XMake_Tests.cs:1283]: Found an example: [https://github.com/dotnet/msbuild/blob/master/src/Build.UnitTests/Evaluation/SemiColonTokenizer_Tests.cs#L24](https://github.com/dotnet/msbuild/blob/master/src/Build.UnitTests/Evaluation/SemiColonTokenizer_Tests.cs#L24)

---
In reply to: [494614444](https://github.com/dotnet/msbuild/pull/5740#discussion_r494614444) [](ancestors = 494614444)

File: src/MSBuild/XMake.cs [hunk 8]
```diff
@@ -2765,206 +2765,137 @@ DirectoryGetFiles getFiles
...
+                    // There has to be more than a . passed in as the extension
+                    InitializationException.VerifyThrow(extension?.Length >= 2, "InvalidExtensionToIgnore", extension);
+
                     try
                     {
-                        // Use GetExtension to parse the extension from the extensionToIgnore
-                        extension = Path.GetExtension(extensionToIgnore);
+                        if (!String.Equals(extension, Path.GetExtension(extension), StringComparison.OrdinalIgnoreCase))
+                        {
+                            throw new ArgumentException();
```
Comment (cdmihai) [inline src/MSBuild/XMake.cs:2886]: Add message for exception if user facing. ErrorUtilities for assertion checks.

Comment (cdmihai) [inline src/MSBuild/XMake.cs:2886]: >throw [](start = 28, length = 5)

This logic of throwing an exception and immediately catching it seems convoluted, unnecessary. Try and simply it.

**Review by cdmihai — APPROVED** [review]
LGTM, pending simplifying the convoluted logic in the ValidateExtension method.
