### PR TITLE
Fix dotnet/msbuild#5884: Add EnsureSingleQuoted and EnsureDoubleQuoted

### LINKED ISSUE #5884: Add `EnsurePathHasOneSetOfQuotes` function to FileUtilies.cs
Related: https://github.com/dotnet/msbuild/issues/4682 and https://github.com/dotnet/msbuild/pull/5871

In `FileUtiliies.cs` we have `RemoveQuotes` and `TrimAndStripAnyQuotes`. We should consider adding some sort of `Ensure-This-Path-Is-Single-Quoted` function.

Possible names:
- EnsurePathIsSingleQuoted
- That's all I got!

### PR DESCRIPTION
**Pull request by jrdodds**
Fixes #5884

### Context
Changes to FileUtilies to add methods to support quoting.

### Changes Made
Add `EnsureSingleQuoted` and `EnsureDoubleQuoted` methods to FileUtilies. (`EnsureSingleQuoted` and `EnsureDoubleQuoted` are implemented by a common `EnsureQuoted` method.) Add unit tests for both methods.

### Testing
Ran `./build.sh --test`

### Notes
At the time of creating this pull request there is an ongoing discussion in the issue about the appropriate behavior for these methods. My hope is that working code will add constructively to the discussion.

### CODE REVIEW

File: src/Shared/FileUtilities.cs [hunk 1]
```diff
@@ -243,6 +243,58 @@ internal static string EnsureNoTrailingSlash(string path)
...
+
+            if (!string.IsNullOrEmpty(path))
+            {
+                // Special case: convert the quotes.
+                if (path.Length > 1 && path[0] == convertQuote && path[path.Length - 1] == convertQuote)
+                {
+                    path = $"{targetQuote}{path.Substring(1, path.Length - 2)}{targetQuote}";
+                }
+                // Enclose the path in a set of the 'target' quote unless the string is already quoted with the 'target' quotes.
+                else if (path.Length == 1 || (path.Length > 1 && (path[0] != targetQuote || path[path.Length - 1] != targetQuote)))
```
Comment (Forgind) [inline src/Shared/FileUtilities.cs:289]: nit:
```suggestion
                else if (path.Length == 1 || (path[0] != targetQuote || path[path.Length - 1] != targetQuote))
```

We'd already verified that path.Length was > 1, and this makes it a bit cleaner

File: src/Shared/FileUtilities.cs [hunk 2]
```diff
@@ -243,6 +243,58 @@ internal static string EnsureNoTrailingSlash(string path)
             return path;
         }
 
+        /// <summary>
+        /// Ensures the path is enclosed within single quotes.
+        /// </summary>
+        /// <param name="path"></param>
+        /// <returns></returns>
+        internal static string EnsureSingleQuoted(string path)
```
Comment (Forgind) [inline src/Shared/FileUtilities.cs:251]: I know there was some confusion around names for this. I'll throw out EnsureSingleQuotes/EnsureDoubleQuotes but won't block on it.

**Review by Forgind — APPROVED** [review]
Looks good to me, thanks!

File: src/Shared/FileUtilities.cs (hunk 1 above)
Comment (jrdodds) [reply src/Shared/FileUtilities.cs:289]: @Forgind Alternatively I could remove the enclosing `if (!string.IsNullOrEmpty(path))` test.

File: src/Shared/FileUtilities.cs (hunk 2 above)
Comment (jrdodds) [reply src/Shared/FileUtilities.cs:251]: I'll make the name change. `Quotes` is more consistent with the other methods than 'Quoted'. Thanks

File: src/Shared/FileUtilities.cs (hunk 1 above)
Comment (Forgind) [reply src/Shared/FileUtilities.cs:289]: That'd work for me, but make sure you handle null correctly.

Comment (jrdodds) [reply src/Shared/FileUtilities.cs:289]: oh - right. Was thinking of the empty string case.

File: src/Shared/FileUtilities.cs [hunk 3]
```diff
@@ -243,6 +243,58 @@ internal static string EnsureNoTrailingSlash(string path)
...
+        /// Ensures the path is enclosed within quotes.
+        /// </summary>
+        /// <param name="path"></param>
+        /// <param name="isSingleQuote">indicates if single or double quotes should be used</param>
+        /// <returns></returns>
+        internal static string EnsureQuotes(string path, bool isSingleQuote = true)
+        {
+            path = FixFilePath(path);
+
+            const char singleQuote = '\'';
```
Comment (BenVillalobos) [inline src/Shared/FileUtilities.cs:276]: We can avoid this char if we use `MSBuildConstants.SingleQuoteChar[0]`. Though it apparently doesn't have a `doubleQuoteChar`? We can add one in `Shared/Constants.cs` in this PR and use it in Evaluator since it creates a  `private static readonly char[] s_doubleQuoteChar = { '"' };`

If you'd rather avoid that, I can create an `up-for-grabs` issue for it.

**Review by BenVillalobos — APPROVED** [review]
Thinking about where to place this helper method:

Some of the XMake_Tests could use this helper method. See https://github.com/dotnet/msbuild/blob/9cb0441e12879e7a70fe7c0de8ab6d5131b62c63/src/MSBuild.UnitTests/XMake_Tests.cs#L827 (there are A LOT so maybe avoid changing all of them)

https://github.com/dotnet/msbuild/blob/main/src/UnitTests.Shared/RunnerUtilities.cs#L34 modifying this helper method would be a good catch for many tests.

File: src/Shared/FileUtilities.cs (hunk 3 above)
Comment (jrdodds) [reply src/Shared/FileUtilities.cs:276]: The fields in `MSBuildConstants` are char arrays. The comment says `// One-time allocations to avoid implicit allocations for Split(), Trim().` which makes sense. There is a memory and performance cost to recreating a char array on every use. But that isn't true for a char literal. I don't think that it makes sense to make a change to use `MSBuildConstants.SingleQuoteChar[0]`. Additionally there are char literals all over the codebase.

Comment (jrdodds) [reply src/Shared/FileUtilities.cs:276]: Yes, the code in `ExecMSBuild`:
```
    msbuildParameters = "\"" + pathToMsBuildExe + "\"" + " " + msbuildParameters;
```
could be changed to:
```
    msbuildParameters = FileUtilities.EnsureDoubleQuotes(pathToMsBuildExe) + " " + msbuildParameters;
```

I'l add that change.

Comment (jrdodds) [reply src/Shared/FileUtilities.cs:276]: Done

File: src/Shared/FileUtilities.cs [hunk 4]
```diff
@@ -243,6 +243,58 @@ internal static string EnsureNoTrailingSlash(string path)
             return path;
         }
 
+        /// <summary>
+        /// Ensures the path is enclosed within single quotes.
+        /// </summary>
+        /// <param name="path"></param>
```
Comment (danmoseley) [inline src/Shared/FileUtilities.cs:249]: Avoid param and returns tags with no content?

File: src/Shared/FileUtilities.cs [hunk 5]
```diff
@@ -243,6 +243,58 @@ internal static string EnsureNoTrailingSlash(string path)
...
+        internal static string EnsureQuotes(string path, bool isSingleQuote = true)
+        {
+            path = FixFilePath(path);
+
+            const char singleQuote = '\'';
+            const char doubleQuote = '\"';
+            var targetQuote = isSingleQuote ? singleQuote : doubleQuote;
+            var convertQuote = isSingleQuote ? doubleQuote : singleQuote;
+
+            if (!string.IsNullOrEmpty(path))
```
Comment (danmoseley) [inline src/Shared/FileUtilities.cs:281]: This check could perhaps be omitted.

File: src/Shared/FileUtilities.cs (hunk 4 above)
Comment (jrdodds) [reply src/Shared/FileUtilities.cs:249]: I'll make a change to add content to the tags.

File: src/Shared/FileUtilities.cs (hunk 5 above)
Comment (jrdodds) [reply src/Shared/FileUtilities.cs:281]: The `string.IsNullOrEmpty` test? This check can't be omitted without rewriting the enclosed `if` statements. Both `if` statements depend on the null check and the second `if` statement depends on the empty check.

File: src/Shared/FileUtilities.cs (hunk 4 above)
Comment (jrdodds) [reply src/Shared/FileUtilities.cs]: Done

File: src/Shared/FileUtilities.cs [hunk 6]
```diff
@@ -243,6 +243,58 @@ internal static string EnsureNoTrailingSlash(string path)
...
+            {
+                // Special case: convert the quotes.
+                if (path.Length > 1 && path[0] == convertQuote && path[path.Length - 1] == convertQuote)
+                {
+                    path = $"{targetQuote}{path.Substring(1, path.Length - 2)}{targetQuote}";
+                }
+                // Enclose the path in a set of the 'target' quote unless the string is already quoted with the 'target' quotes.
+                else if (path.Length == 1 || (path[0] != targetQuote || path[path.Length - 1] != targetQuote))
```
[the remark this answers is not in the document]
Comment (jrdodds) [reply src/Shared/FileUtilities.cs]: Made the change. Thanks

**Comment by BenVillalobos** [comment]
https://github.com/dotnet/msbuild/blob/main/src/Utilities/CommandLineBuilder.cs#L289 looks to be a worthwhile place to use this new method. If only to have at least one non-test path that runs this logic. cc @jrdodds

**Comment by Forgind** [comment]
Thanks @jrdodds!
