### PR TITLE
Use ToolTask.TaskProcessTerminationTimeout correctly

### LINKED ISSUE #8545: [Bug]: ToolTask TaskProcessTerminationTimeout propery initialized but never used
### Issue Description

Protected property `ToolTask.TaskProcessTerminationTimeout` has been initialized but never used. Looks like it meant to be used as the default time-out for terminating external tool.

### Steps to Reproduce

Looks like `timeout` on the following line meant to be `ToolTask.TaskProcessTerminationTimeout` instead of hard-coding:
https://github.com/dotnet/msbuild/blob/18fe510422c6cf65533add0c82b9d4d190e5df28/src/Utilities/ToolTask.cs#L940

Time-out set by derived class won't work in the current implementation.

### Expected Behavior

`TaskProcessTerminationTimeout` set by derived classes of `ToolTask` should work.

### Actual Behavior

`TaskProcessTerminationTimeout` set by derived classes of `ToolTask` does not work.

### Analysis

Protected property `ToolTask.TaskProcessTerminationTimeout` has been initialized but never used. It should be applied as time-out when terminating external tool.

### Versions & Configurations

MSBuild version 17.4.1.60106
MSBuild latest

### PR DESCRIPTION
**Pull request by gpwen**
Use `ToolTask.TaskProcessTerminationTimeout` as termination time-out to kill external tool when it was cancelled or timed out.

Fixes #8545 

### Context

The protected property `ToolTask.TaskProcessTerminationTimeout` has been initialized but never used. Looks like it should be used as `timeout` on the following line when killing external tool on time-out or cancellation:
https://github.com/dotnet/msbuild/blob/main/src/Utilities/ToolTask.cs#L940

### Changes Made

Use `ToolTask.TaskProcessTerminationTimeout` as termination time-out to kill external tool when it was cancelled or timed out.

### Testing

All `ToolTask` unit test passed.

### Notes

No new unit test created.

### CODE REVIEW

**Review by JanKrivanek — CHANGES_REQUESTED** [review]
Thank you for the contribution!
Looks good!

It would be nice to have this more defensive and explicitly error out on disallowed values (negative, other then -1 - https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=net-7.0#system-diagnostics-process-waitforexit(system-int32)). Either in the `TaskProcessTerminationTimeout` setter or in `KillToolProcessOnTimeout`

**Comment by Forgind** [comment]
> Thank you for the contribution! Looks good!
> 
> It would be nice to have this more defensive and explicitly error out on disallowed values (negative, other then -1 - https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=net-7.0#system-diagnostics-process-waitforexit(system-int32)). Either in the `TaskProcessTerminationTimeout` setter or in `KillToolProcessOnTimeout`

I vote setter 🙂 If KillToolProcessOnTimeout fails, I'd assume I'd called that wrong—perhaps the process had already exited, or I didn't have access to it—rather than that the timeout was improperly set.

**Review by Forgind — APPROVED** [review]
Thanks for the change!

**Comment by danmoseley** [comment]
What is the difference between this and `public virtual int Timeout` ? 

Would it be possible to add a unit test?

**Comment by gpwen** [comment]
> It would be nice to have this more defensive and explicitly error out on disallowed values (negative, other then -1)

Hi @JanKrivanek, you're absolutely right. There must be some checking since that's meant to be used by derived class. However, I'm not sure how to report error. It feels like the correct way is checking that in ValidateParameters() and log build errors. But that would confuse end user (they didn't set anything).

How about exception? Or silently reject invalid setting in setter? Like what's been done with the "MSBUILDTOOLTASKCANCELPROCESSWAITTIMEOUT" environment string. Or silent clipping? What's the official way to do such derived class setting validation in MSBuild tasks?

**Comment by gpwen** [comment]
> What is the difference between this and `public virtual int Timeout` ?
`Timeout` is the time-out for external tool execution; `TaskProcessTerminationTimeout` is the time-out for killing the tool process when it needs to be terminated.

> Would it be possible to add a unit test?
I've considered that, but it's well in the process manipulation territory. I'm not even sure if I can create an effective one to verify the effect of that parameter. It would look like some unit tests for `Process.KillTree()`.

**Comment by gpwen** [comment]
More thoughts about `ToolTask.TaskProcessTerminationTimeout` validation: Looks like "silent rejection" in setter is the most backward-compatible way, considering the property was originally ignored. That way, derived classes that currently set the parameter to invalid value won't be suddenly broken.

Besides, we have the prior art of the `MSBUILDTOOLTASKCANCELPROCESSWAITTIMEOUT` environment setting handling.

**Comment by Forgind** [comment]
> More thoughts about `ToolTask.TaskProcessTerminationTimeout` validation: Looks like "silent rejection" in setter is the most backward-compatible way, considering the property was originally ignored. That way, derived classes that currently set the parameter to invalid value won't be suddenly broken.
> 
> Besides, we have the prior art of the `MSBUILDTOOLTASKCANCELPROCESSWAITTIMEOUT` environment setting handling.

This sounds reasonable, but I do like the idea of an explicit error as JanKrivanek suggested. If we want a compromise, perhaps we could have a user-visible error behind a change wave if they set it to an invalid value? Then we could gather data as to how many people are actually setting it to something invalid; if it's common, we can switch to the silent rejection, and if no one complains, it'll eventually become the default. How does that sound?

**Comment by gpwen** [comment]
In fact I like the idea of failing early and failing loudly, just a little bit concerned about breaking existing code.

I pushed an update. The setter will now throw `ArgumentOutOfRangeException`, and unit tests have been added to test the validation logic. Please have a check.

File: src/Utilities/ToolTask.cs [hunk 1]
```diff
@@ -134,10 +134,30 @@ protected ToolTask(ResourceManager taskResources, string helpKeywordPrefix)
...
         /// A timeout to wait for a task to terminate before killing it.  In milliseconds.
         /// </summary>
-        protected int TaskProcessTerminationTimeout { get; set; }
+        /// <exception cref="ArgumentOutOfRangeException">Thrown if the property is set to a negative value other than -1.</exception>
+        protected int TaskProcessTerminationTimeout
+        {
+            get => _taskProcessTerminationTimeout;
+            set
+            {
+                if (value < -1)
```
Comment (Forgind) [inline src/Utilities/ToolTask.cs:151]:
```suggestion
                if (value < -1 && ChangeWaves.AreFeaturesEnabled(ChangeWaves.Wave17_6))
```

**Review by Forgind — COMMENTED** [review]
Often in tasks, we have custom messages with error codes rather than throwing ArgumentOutOfRangeException or the equivalent. It means that if a user hits that exception, they can search for the error code (even if it's in another language, and the rest of the message is confusing) and find relevant documentation. I suspect this particular error won't be hit too much, so I'm ok with leaving it as-is but don't feel strongly.

File: src/Utilities/ToolTask.cs (hunk 1 above)
Comment (Forgind) [reply src/Utilities/ToolTask.cs:151]: Could also simplify a bit with VerifyThrow...

But that should be equivalent from the user's perspective.

Comment (JanKrivanek) [reply src/Utilities/ToolTask.cs:151]: @gpwen sorry for not giving precise guidance and then missing this PR.
`ValidateParameters()` is the best location for this validation - it'll ensure clean comunication of the issue to the user. Ideally error is logged there and `false` returned.

For simplicity - if change wave is not on (it is on by default - opting-out means somebody willingly wants legacy behavior) - I'd just set the value to the legacy one (`5000`) - regardless of validity of the value.

Other than that - it looks good.

**Review by JanKrivanek — CHANGES_REQUESTED** [review]

**Comment by JanKrivanek** [comment]
@gpwen thank you for this contribution - do you plan to contribute the suggested changes (legacy timeout when opted-out via changewave, and validation within `ValidateParameters()`)?

File: src/Utilities/ToolTask.cs (hunk 1 above)
Comment (JanKrivanek) [reply src/Utilities/ToolTask.cs]: Implemented

**Review by JanKrivanek — APPROVED** [review]

**Review by Forgind — APPROVED** [review]
