### PR TITLE
Skip results transfer in MT mode to fix ResultsNodeId race

### LINKED ISSUE #13188: [Unhandled Exception]: -mt mode intermittent crash "Results for configuration X were not retrieved from node Y"
## Issue Description

When building with MSBuild's `-mt` (multithreaded) mode enabled, builds intermittently crash with an internal MSBuild error indicating that results for a project configuration were not transferred between nodes correctly. This appears to be a race condition in the scheduler when a project is moved from one node to another.

The issue is intermittent - it does not reproduce consistently on local machines but falied on VMR CI

## Steps to Reproduce

1. Build the dotnet/dotnet VMR (or F# repo) with `-mt` mode enabled
2. patch build scripts to use -mt mode

3. Run build:
```
build.cmd -pack -noVisualStudio -ci -configuration Release -bl
```

**Note:** The issue is intermittent and may require multiple runs or high-parallelism environment to reproduce. CI machines with many cores reproduce it more frequently than local developer machines.

binlog:
[Build.Microsoft.FSharp.Compiler.sln.binlog.zip](https://github.com/user-attachments/files/25044574/Build.Microsoft.FSharp.Compiler.sln.binlog.zip)

## Actual Behavior

Multiple projects fail simultaneously with unhandled exceptions:

```
##[error]This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled
    Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Results for configuration 27 were not retrieved from node 8
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Int32 arg0, Int32 arg1)
   at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()
   at Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(Boolean setThreadParameters)
```

Multiple projects fail with similar errors (configurations 25, 26, 27 all referencing node 8), suggesting a systemic issue when that node becomes unavailable or slow to respond.

## Analysis

The failure occurs at `RequestBuilder.cs` lines 1197-1208:

```csharp
if ((_requestEntry.RequestConfiguration.ResultsNodeId != Scheduler.InvalidNodeId) &&
    (_requestEntry.RequestConfiguration.ResultsNodeId != _componentHost.BuildParameters.NodeId))
{
    // Block waiting for results transfer
    await BlockOnTargetInProgress(Microsoft.Build.BackEnd.BuildRequest.InvalidGlobalRequestId, null);

    // Assertion fails here - ResultsNodeId was not updated
    ErrorUtilities.VerifyThrow(
        _requestEntry.RequestConfiguration.ResultsNodeId == _componentHost.BuildParameters.NodeId,
        "Results for configuration {0} were not retrieved from node {1}",
        _requestEntry.RequestConfiguration.ConfigurationId,
        _requestEntry.RequestConfiguration.ResultsNodeId);
}
```

**Hypothesis:** 
- A project configuration was originally built on node 8
- The scheduler moves it to run on a different node  
- `BlockOnTargetInProgress` is called to wait for results transfer
- The await completes but `ResultsNodeId` was not updated to the current node
- The assertion fails

This suggests either:
- `BlockOnTargetInProgress` returns before the transfer is actually complete
- The results transfer message is lost or not processed
- `ResultsNodeId` update has a race with the completion signal

## Versions & Configurations

- MSBuild: 18.4 netsdk11.0.100-p1 (via dotnet/dotnet VMR)
- OS: Windows Server (Azure DevOps hosted agents)
- Architecture: x64
- Build tool: dotnet CLI with `-mt` flag enabled
- Parallelism: High (CI machine with many cores)

**Local reproduction attempted:** Built F# repo locally with `-mt` twice, both succeeded. The issue appears timing/load dependent.

### PR DESCRIPTION
**Pull request by JanProvaznik**
### Problem
In MT (multi-threaded) mode, builds intermittently crash with:
\\\
InternalErrorException: MSB0001: Internal MSBuild Error: Results for configuration X were not retrieved from node Y
\\\

### Root Cause
\BuildRequestConfiguration.ResultsNodeId\ is a single \int\ field shared by all in-proc nodes via the shared \ConfigCache\. When multiple in-proc nodes simultaneously need a configuration's results, they race through \HandleRequestBlockedOnResultsTransfer\, which unconditionally overwrites \ResultsNodeId\ to the requesting node's ID. The last writer wins, causing other waiters to find a mismatched value when they wake up, failing the assertion in \RequestBuilder.BuildProject()\.

### Key Insight
**In MT mode, the entire results transfer mechanism is unnecessary.** All in-proc nodes share the same \ConfigCache\ and \ResultsCache\ by reference. When a config is built on any node, the results are immediately accessible to all other in-proc nodes through the shared cache. MT mode also disallows out-of-proc nodes (\Scheduler.cs\ sets OOP node count to 0 when \MultiThreaded=true\), so there are no cross-process transfers to worry about.

### Fix
Extracted the transfer-needed check into a testable \NeedsResultsTransfer\ method that returns \alse\ when \MultiThreaded\ mode is active, skipping the entire transfer block.

### Tests
- **Unit test (red/green validated)**: \NeedsResultsTransfer_SkipsInMultiThreadedMode\ — 6 Theory cases covering all MT/ST × node ID combinations. Confirmed: fails without fix, passes with fix.
- **Integration test**: \MultiThreadedBuild_SharedConfiguration_DoesNotCrash\ — 8 parallel projects referencing same dependency with different target sets, forcing cache misses that exercise the transfer code path.

### No ChangeWave Needed
This is a crash fix, not a behavioral change. The transfer was already a no-op in MT mode (copying data between shared references). Skipping it produces identical build results while preventing the race condition crash.

Fixes #13188

### CODE REVIEW

**Comment by JanProvaznik** [comment]
expert reviewer passe, ready to review

File: src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs [hunk 1]
```diff
@@ -1057,6 +1057,38 @@ private void RaiseBuildRequestCompleted(BuildRequestEntry entryToComplete)
...
+        /// ResultsNodeId with their own node ID.
+        /// </para>
+        /// </summary>
+        /// <param name="resultsNodeId">The node ID where results currently reside.</param>
+        /// <param name="currentNodeId">The node ID of the current node.</param>
+        /// <param name="isMultiThreaded">Whether MT mode is active.</param>
+        /// <returns>True if results must be transferred from another node before building.</returns>
+        internal static bool NeedsResultsTransfer(int resultsNodeId, int currentNodeId, bool isMultiThreaded)
+        {
+            if (isMultiThreaded)
```
Comment (AR-May) [inline src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:1084]: Looks reasonable, however I am worried that if in future for any reason we might have both out-of-proc and in-proc nodes, then this condition would break the results transfer between processes. Can we instead of this condition keep track which nodes are in-proc and which are not (basically nodes association to processes) and check against that information?

Comment (JanProvaznik) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:1084]: I think that's a design consideration for the future "mixed nodes" feature which is not urgent. Doing that now seems to increase the complexity without benefit and since it's an internal implementation can be changed. I'll update the comment to clearly document that there is this conceptual coupling which may change in future features.

Comment (AR-May) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:1084]: We need not to miss this place if we further will go for mixed nodes. Maybe add a note to the spec about it?

Comment (JanProvaznik) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:1084]: made the comment more explicit
