### PR TITLE
Fix MakeRelative regression in v16.10 (rebased to vs16.10 branch)

### LINKED ISSUE #6493: $([MSBuild]::MakeRelative()) returns different values on 16.10 than older version
### Issue Description
Newest version of VisualStudio (MSBuild 16.10) return different values on msbuild property function MakeRelative() with paths ending backslash.

### Steps to Reproduce
code: $([MSBuild]::MakeRelative('c:\windows\\', 'c:\windows\system32\\'))
MSBuild 16.10 returns:  'system32'
MSBuild 16.9 and older returns: 'system32\\'

### Expected Behavior
according to https://docs.microsoft.com/en-us/dotnet/api/system.uri.makerelativeuri?view=net-5.0
it should returns 'system32\\'

### Actual Behavior
returns 'system32'

### Analysis
MSBuild unittests does not contains paths ending backslash
https://github.com/dotnet/msbuild/blob/main/src/Shared/UnitTests/FileUtilities_Tests.cs#L86

### Versions & Configurations
16.10.0.26302

### PR DESCRIPTION
**Pull request by dsparkplug**
Fixes #6493

Summary
MSBuild's MakeRelative function does not fit the spec for how that function should work. 

Customer impact
Customers who use our MakeRelative function expect the relative path produced to end in a slash if and only if the input path ends in a slash. It currently does not end in a slash whether or not the input path ended in a slash. Users can invoke this function directly, and it can lead to dlls not being found, among other problems.

Regression?
Yes, from #6311 (16.10 Preview 2). The URI-based function that had existed prior failed in another scenario, and the new form is also faster. This PR resolves a bug associated with that change.

Changes Made
Only removes the ending slash if the input path did not end in a slash.

Testing
Extensive unit test coverage. This is a community contribution, and I imagine it was also tested locally. (Please correct me if I'm wrong, @dsparkplug.)

Risk
Low. Rather than always removing the final slash, this conditionally removes it, reverting to prior behavior. No other (non-test) parts of the code base were altered.

### CODE REVIEW

**Comment by dsparkplug** [comment]
I'll leave it to someone else to figure out why the build is failing and what's wrong with `Microsoft.Build.cs`

**Comment by Forgind** [comment]
The MSBuild team agreed we would try to take this for 16.10 as you suggested. We will need internal approval, so I'm modifying your opening message to fit the template.

File: src/Shared/FileUtilities.cs [hunk 1]
```diff
@@ -1078,7 +1078,12 @@ internal static string MakeRelative(string basePath, string path)
             {
                 sb.Append(splitPath[i]).Append(Path.DirectorySeparatorChar);
             }
-            sb.Length--;
+
+            if (fullPath[fullPath.Length - 1] != Path.DirectorySeparatorChar)
```
Comment (danmoseley) [inline src/Shared/FileUtilities.cs:1082]: should it also check Path.AlternateDirectorySeparatorChar?

Comment (dsparkplug) [reply src/Shared/FileUtilities.cs:1082]: My understanding is that the `fullPath` has already been normalised within the `Path.GetFullPath` function so should only contain `Path.DirectorySeparatorChar`?

Comment (Forgind) [reply src/Shared/FileUtilities.cs:1082]: Looks like that's true for [unix](https://github.com/dotnet/runtime/blob/8709d595f7105cbf73774ec762266bc56f99cf04/src/libraries/System.Private.CoreLib/src/System/IO/PathInternal.cs#L196-L200). [Windows](https://github.com/dotnet/runtime/blob/8709d595f7105cbf73774ec762266bc56f99cf04/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.GetFullPathNameW.cs#L15) calls down into the kernel, but I'm assuming it's the same.

**Review by Forgind — APPROVED** [review]
Thank you for fixing this!

File: src/Shared/FileUtilities.cs (hunk 1 above)
Comment (dsparkplug) [reply src/Shared/FileUtilities.cs:1082]: Sure is:

```csharp
Microsoft (R) Visual C# Interactive Compiler version 3.10.0-4.21269.26 ()
Loading context from 'CSharpInteractive.rsp'.
Type "#help" for more information.
> System.Console.WriteLine(System.IO.Path.GetFullPath("C:/abc/def/"));
C:\abc\def\
> System.Console.WriteLine(System.IO.Path.GetFullPath("C:/abc/def"));
C:\abc\def
> 
```

**Review by rainersigwald — APPROVED** [review]
