### PR TITLE
LoggingService log contention

### LINKED ISSUE #7364: LoggingService.LogComment causes large amounts of contention between unrelated evaluation threads.
### Issue Description
LoggingService.LogComment causes large amounts of contention between unrelated evaluation threads.
image

### Steps to Reproduce
- clean solution VS temp files (.vs)
- clean solution (msbuild /t:clean)
- track in perfview: open solution with large number of projects

### Data
TBD

### Analysis
TBD

### Versions & Configurations
VS 17.2

### Regression?
TBD

### PR DESCRIPTION
**Pull request by rokonec**
Fixes #7364 

### Context
[](https://user-images.githubusercontent.com/25249058/152361351-ff5d51a9-5630-4aaf-8178-4597d5bf9773.png)LoggingService.LogComment causes large amounts of contention between unrelated evaluation threads.
image

### Changes Made
- Reducing lock statements
  - using Interlock.Add as oppose to lock { n+=x; }
  - replace `Dictionary` with `ConcurrentDictionary` and remove related `lock`s
  - review  `lock`s and remove unnecessary
- Replacing `DataFlow` by `ConcurrentQueue` for event processing
- Fixing unit tests

### Testing
- local run unit testst
- micro benchmark comparing `DataFlow` by `ConcurrentQueue`
- exp insertion - currently failing on infrastructure - will update
- Compiled Boost.Hana as described in #3577 - no OOM exception

### Notes
It has surprisingly good perf results. Maybe because I tested it on 24 core machine where lock contention in LoggingService could be a bigger issue.

|command|Duration|RAM|
|-|-|-|
|`msbuild /m /bl OrchardCore.sln`|-25%|-4%|
|`msbuild /m OrchardCore.sln`|-13%|-3%|

Microbenchmark comparing DataFlow vs ConcurrentQueue processing 1E6 messages showed ~2 seconds  saving (-85%) and about ~250MB allocations less (-92%). I was also considering to use `BlockingCollection` but for this we do not have support in net3.5 and also I have seen weird huge perf degradation for my use case in `net472`.

|Method|Mean|Allocated|
|-|-:|-:|
|DataFlow| 2,558,860.6 us |  297,286,352 B |
|CocurrentQueue| 371,877.9 us | 26,304,552 B |

### CODE REVIEW

**Comment by drewnoakes** [comment]
Tagging @lifengl and @arkalyanms who may be interested in the Dataflow performance analysis here.

**Comment by rokonec** [comment]
> Will the changes to the logger change timing on the evaluation messages for VS?
@arkalyanms If I understand the meaning of 'timing' here correctly then NO. Evaluation still uses sync message logging, AFAIK, so messages will be delivered to VS in the same order related to end of Evaluation.
However, I'd like if we could discuss, at some point, how VS uses evaluations, and change it into async logging as that could have quite a perf gain for VS concurrent evaluations scenarios.
That being said, I have changed  mode of `GlobalProjectCollection` and if VS uses this for evaluation than answer is yes, timing of messages of evaluation could be altered, and messages could be delivered to VS way after evaluations ends.

**Comment by arkalyanms** [comment]
MSBuild evaluates the projects inside the [constructor](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=/src/Microsoft.VisualStudio.ProjectSystem.Implementation/Projects/ConfiguredProjectImpl.cs&version=GBmain&line=784&lineEnd=784&lineStartColumn=43&lineEndColumn=81&lineStyle=plain&_a=contents), which makes it difficult to bind an evaluation and its artifacts to the new project as a part of the evaluation. So in a backfill step, CPS captures evaluations for unknown projects matching the project path and binds to it after the construction. Evalution messages are no different and we use those to determine if user needs to receive actionable info bars to check the SDK or reload solutions in case of evaluation errors. I wonder in a concurrent evaluation environment it's now possible to lose/ask too early for the error message from the message factory, after the evaluation.

This may be a non concern if the logger factory creations are bound internally to an evaluation in queue and wait for the corresponding message logger to arrive. If not, should be done so. @lifengl would you know if this will require a design change on our end?

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 1]
```diff
@@ -1202,20 +1172,21 @@ public void LogBuildEvent(BuildEventArgs buildEvent)
...
         {
             ErrorUtilities.VerifyThrow(buildEvent != null, "buildEvent is null");
             if (_logMode == LoggerMode.Asynchronous)
             {
-                // If the queue is at capacity, this call will block - the task returned by SendAsync only completes 
-                // when the message is actually consumed or rejected (permanently) by the buffer.
-                var task = _loggingQueue.SendAsync(buildEvent);
-                if (allowThrottling)
+                // Block until queue is not full.
+                while (_eventQueue.Count >= _queueCapacity)
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:1182]: Should we have a check for whether _enqueueEvent is set?

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 2]
```diff
@@ -1305,55 +1252,77 @@ private static int GetWarningsAsErrorOrMessageKey(BuildEventArgs buildEventArgs)
...
+                do
+                {
+                    // We peak message first in order to not have _eventQueue.IsEmpty before we actually process event
+                    //   as this could be interpreted like "every message has been already processed" otherwise.
+                    if (_eventQueue.TryPeek(out object ev))
+                    {
+                        LoggingEventProcessor(ev);
+                        _eventQueue.TryDequeue(out _);
+                        _dequeueEvent.Set();
+                    }
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:1283]: If you have multiple competing TryPeeks, that would mean you could process a single event twice, right? Should this be:
```suggestion
                   if (_eventQueue.TryDequeue(out object ev) {
                        LoggingEventProcessor(ev);
                        _dequeueEvent.Set();
                    }
```

?

**Review by Forgind — APPROVED** [review]

File: src/Build/BackEnd/Components/Logging/LoggingService.cs (hunk 2 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:1283]: That is true. But we don't have multiple competing `TryPeek` and chance we will need it in future is slim to none.
As stated in comment with TryPeek, process, Dequeue wee achieve that queue is empty only after all messages has been processed by listeners/loggers. 
Method `WaitForLoggingToProcessEvents` is used in places where logic requires all messages to be fully handled before continue and its implementation cosider job to be done when `queue.IsEmpty`.

File: src/Build/BackEnd/Components/Logging/LoggingService.cs (hunk 1 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:1182]: Only role of `_enqueueEvent` is to unblock pumping thread when new message arrives.
It is perfectly safe to set `AutoResetEvent` which is already in set state.
There is race condition by design and when it happens pumping thread will do one unnecessary empty loop which has negligible perf cost.

File: src/Build/BackEnd/Components/Logging/LoggingService.cs (hunk 2 above)
Comment (Forgind) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:1283]: Ok; I think that makes sense.

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 3]
```diff
@@ -1202,20 +1172,21 @@ public void LogBuildEvent(BuildEventArgs buildEvent)
...
             {
-                // If the queue is at capacity, this call will block - the task returned by SendAsync only completes 
-                // when the message is actually consumed or rejected (permanently) by the buffer.
-                var task = _loggingQueue.SendAsync(buildEvent);
-                if (allowThrottling)
+                // Block until queue is not full.
+                while (_eventQueue.Count >= _queueCapacity)
                 {
-                    task.Wait();
+                    // Block and wait for dequeue event.
```
[the remark this answers is not in the document]
Comment (rainersigwald) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:1187]: Indeed the lack of throttling was the cause of the OOM in #3577. I am very happy to actually have the backpressure system we have allegedly had for a long time. Agreed on the possiblity of queue tuning.

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 4]
```diff
@@ -1227,41 +1202,21 @@ internal virtual void ProcessLoggingEvent(object buildEvent, bool allowThrottlin
...
-
-                    loggingQueue.Complete();
-                    loggingQueueProcessor.Completion.Wait();
-                }
+                _emptyQueueEvent?.Wait();
             }
+            // To avoid race condition when last message has been removed from queue but
+            //   not yet fully processed (handled by loggers), we need to make sure _emptyQueueEvent
+            //   is set as it is guaranteed to be in set state no sooner than after event has been processed.
+            _emptyQueueEvent?.Wait();
```
[the remark this answers is not in the document]
Comment (rokonec) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:1219]: Lets suppose `WaitForLoggingToProcessEvents` is called right at the time another thread is processing last message from queue `LoggingEventProcessor(ev);` at line #1287. At this time queue is already empty and without line #1219 `_emptyQueueEvent?.Wait();` method `WaitForLoggingToProcessEvents` would ends immediately event though the last message from queue is still processing.
Because `_emptyQueueEvent` is never in set state while message is processing but will enter set state after last message from queue is processed this line is necessary to avoid above race condition.

Probability of this race condition is very small, however there is a unit test which were consistently failing on this RC.

**Comment by rokonec** [comment]
> This looks great but I'm not confident I understand the ManualResetEvent flow. Could you expand on that a bit?

I have had version using `_dequeueEvent` and `_enqueueEvent` as AutoResetEvent, but when micro benchmarking, `ManualResetEventSlim` have measurable difference, while not introducing much more complexity (just calling `Reset` after `Wait` just like `AutoResetEvent` "do").

`_emptyQueueEvent` has to be manual event in current logic because it is tested multiple time. Its meaning is actually `in set state while not-in-deque-aka-processing-loop`.
