### PR TITLE
Fix restore handling in Terminal Logger

### LINKED ISSUE #9323: [Bug]: Terminal logger crashes when building the SDK repo
### Issue Description

Building the SDK on the command line results in a `KeyNotFoundException` in TL.

### Steps to Reproduce

1. Clone https://github.com/dotnet/sdk on Windows, checkout commit c0389b12154e290d7722d220e0e8928531c03e2d.
2. Set `MSBUILDLIVELOGGER=auto`.
3. Run `restore.cmd`.
4. Run `build.cmd`.

### Expected Behavior

Build runs to completion.

### Actual Behavior

Build hangs due to:

```
  C:\src\sdk\src\Tests\Microsoft.DotNet.PackageInstall.Tests\SampleGlobalTool\consoledemo.csproj Restore (7.0s)
  redist PublishNETAnalyzers (13.5s)
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
System.Collections.Generic.KeyNotFoundException: The given key 'ProjectContext { Id = 1906 }' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Build.Logging.LiveLogger.LiveLogger.ProjectStarted(Object sender, ProjectStartedEventArgs 337.7s)
   at Microsoft.Build.BackEnd.344.2s).EventSourceSink.RaiseProjectStartedEvent(Object sender, ProjectStartedEventArgs buildEvent)
```

### Analysis

_No response_

### Versions & Configurations

8.0.100-preview.7.23376.3

### PR DESCRIPTION
**Pull request by AR-May**
Fixes #9323

### Context
There are 4 related problems that occur in the issue #9323:

1. The logger fails and throws an internal logger exception because of the wrong assumptions about restore target appearance in the build. 
2. The internal logger exception is caught and causes the build to shut down all loggers, including terminal logger. Because it happens before the build finished event is produced or processed by terminal logger, the rendering thread is not finished, and it leads to an infinite hang.
3. The errors during restore are not logged.
4. There is inconsistency with showing the message error MSB4017. If the internal logger exception is thrown from one place it shows, from another - not. In the current situation the build and logger are shut downed, but the message did not appear, which is confusing. (see #9455)

### Changes Made
Fixed first 2 errors: 
1. Improved the handling of the restore such that there should not be throws. Only first restore that happens would be specially treated.  
2. I added shutting down of the render thread when shutting down the logger. 

### Testing
locally tested, unit tests

### Notes
Compatible with PR #9424, which covers the problem 3.

### CODE REVIEW

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 1]
```diff
@@ -229,6 +234,8 @@ public void Initialize(IEventSource eventSource)
     /// <inheritdoc/>
     public void Shutdown()
     {
+        _cts.Cancel();
+        _refresher?.Join();
```
Comment (JanKrivanek) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:238]: In ideal case there'd as well be some signalization and `ThreadProc` would bail out immediately: https://github.com/dotnet/msbuild/blob/main/src/MSBuild/TerminalLogger/TerminalLogger.cs#L670 (e.g. `_cts.WaitHandle.WaitOne(1_000 / 30)`). And unless the `lock` wait is time limited as well - the `Join` here should probably have timeout ro prevent deadlock. Reasonably long wait - e.g. a second - is fine in both cases.

**Review by JanKrivanek — CHANGES_REQUESTED** [review]
Looks good!

Let's make sure we do not make it possible for future changes to introduce deadlock on shutdown

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 1 above)
Comment (ladipro) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:238]: That's a great point. The build currently spends ~16 ms on average waiting for the `Sleep` to finish.

**Review by ladipro — APPROVED** [review]
> Let's make sure we do not make it possible for future changes to introduce deadlock on shutdown

I'd be OK doing it in a separate PR as this is a pre-existing pattern - `Cancel` and `Join` are already used in `BuildFinished`. What would be the deadlock here? Calling `Join` while holding `_lock`? I would discourage from using timeout instead of proper deadlock prevention. The `Join` exiting early on timeout would make the code less reliable.

(Also, we should add disposing of _cts while we're at it.)

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 1 above)
Comment (AR-May) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:238]: I agree that avoiding the extra waiting would be great, let's use the wait handle. As for the deadlock prevention, I here agree with Ladi that I do not like uncertainty of timeout in the Join. I do not yet see any opportunities for the deadlock here as well: the shutdown (and regular termination of TL) does not have a lock at all, since at this moment we are ok with possible race conditions that absence of lock may introduce. If the locked section is indefinitely long (because of the deadlock with something else for example), that is not a problem of introduced code, that is a problem we need to address for the rendering thread.

Comment (JanKrivanek) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:238]: I lack the knowledge of actual TL details - so I was just setting my eyes on seeing `Shutdown` waiting for a thread that can be waiting for a lock.
As soon as we know our locking is properly handled and hence `Shutdown` is guaranteed to finish - I'm not insisting on timeout.

I still feel bit strongly opinionated about replacing the `Sleep` with `WaitOne` though :-) - so waiting with sign-off for that one (or other contra-arguments)

Comment (AR-May) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:238]: The WaitOne change is on its way. I will commit it soon :)

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 2]
```diff
@@ -667,7 +678,7 @@ private void ThreadProc()
     {
         while (!_cts.IsCancellationRequested)
```
Comment (ladipro) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:679]:
```suggestion
        while (!_cts.Token.WaitHandle.WaitOne(1_000 / 30))
```

Less code and avoids the last `DisplayNodes` call when the waithandle is signaled.
