### PR TITLE
Fix oversharing of build results in ResultsCache

### LINKED ISSUE #9458: [Bug]: ResultsCache ignores some of the BuildRequest data, may return incorrect results
### Issue Description

`ResultsCache` ignores `BuildRequestDataFlags.ProvideProjectStateAfterBuild` and `RequestedProjectState`, which may lead to incorrect over-sharing and returning incomplete results. `BuildResult.ProjectStateAfterBuild` is used by design-time builds in Visual Studio where this issue was discovered.

### Steps to Reproduce

The repro is provided as a private MSBuildLocator branch:
https://github.com/microsoft/MSBuildLocator/compare/main...ladipro:MSBuildLocator:results-cache-bug

Build and run the BuilderApp project to reproduce.

### Expected Behavior

Build succeeds.

### Actual Behavior

Build fails because the second submission returns null `ProjectStateAfterBuild` despite having constructed the build request with `BuildRequestDataFlags.ProvideProjectStateAfterBuild`.

### Analysis

The two build requests appear to be treated as identical by the results cache. The cached results of the first build request are returned when the second build request is submitted.

### Versions & Configurations

Visual Studio 17.9.34322.171

### PR DESCRIPTION
**Pull request by ladipro**
Fixes #9458

### Context

#9565 had to be reverted because the assumption that results with `BuildRequestDataFlags.ProvideSubsetOfStateAfterBuild` don't have to be cached broke design-time builds in Visual Studio.

### Changes Made

Re-did the change, now with full handling of `BuildRequestDataFlags.ProvideSubsetOfStateAfterBuild`.

### Testing

New and existing unit tests, experimental insertion, manual testing with the problematic design-time build scenario.

### Notes

Compared to #9565, we now:
- Copy the flags from the original `BuildResult` in the `BuildResult` copy constructor.
- Have `ProjectInstance` remember the project state filter it was created from.
- Implement `IsSubsetOf` operator on `RequestedProjectState`.
- Use the `IsSubsetOf` to determine if a request with `ProvideSubsetOfStateAfterBuild` can be satisfied by the cache.
- Don't consider `SkipNonexistentTargets` to be a flag affecting build results.

### CODE REVIEW

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs [hunk 1]
```diff
@@ -328,6 +344,50 @@ private static bool CheckResults(BuildResult result, List<string> targets, HashS
...
+            BuildRequestDataFlags buildRequestDataFlags = buildRequest.BuildRequestDataFlags;
+            BuildRequestDataFlags buildResultDataFlags = buildResult.BuildRequestDataFlags;
+
+            if ((buildRequestDataFlags & FlagsAffectingBuildResults) != (buildResultDataFlags & FlagsAffectingBuildResults))
+            {
+                // Mismatch in flags that can affect build results -> not compatible.
+                return false;
+            }
+
+            if (buildRequestDataFlags.HasFlag(BuildRequestDataFlags.ProvideProjectStateAfterBuild))
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Caching/ResultsCache.cs:364]: Doesn't HasFlag box on Framework? I vaguely remember that it's suprisingly better to do the boolean operations.

**Review by rainersigwald — APPROVED** [review]

**Review by YuliiaKovalova — APPROVED** [review]

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs (hunk 1 above)
Comment (ladipro) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs]: Indeed, seems to box on Core as well. Fixed, thank you.
