### PR TITLE
Restore console mode after server build

### LINKED ISSUE #8008: Breaking change in linebreak handling in 7.0 RC1
### Description

I'm unsure if this is an issue in `dotnet run` or in the underlying runtime/libraries, so please redirect elsewhere if needed. Also, I don't know if this is a deliberate change.

### Customer impact

The impact of this change is that existing code that renders to the console produces corrupt output. It seems to be that, in the past, a Unix-style `\n` was enough to produce normal newline behaviors, whereas this has changed and now it only works on Windows if you output `\r\n`. Our cross-platform compatibility has been reduced.

### Reproduction Steps

1. Create a new console app (`dotnet new console`)
2. Change the contents of `Program.cs` to be `Console.WriteLine("Line1\nLine2");`
3. Run it on Windows in either the *Terminal* app or the old-school console (i.e., `cmd.exe`) using the command `dotnet run`

### Expected behavior

In 7.0 preview 7 (I tried 7.0.100-preview.7.22377.5) and earlier, the output is:

```
Line1
Line2
```

This is the expected and desired output

### Actual behavior

Starting from 7.0 RC1 and still happening with RC2 builds, you get:

```
Line1
     Line2
```

### Regression?

Yes, worked in 7.0.100-preview.7.22377.5

### Known Workarounds

None

### Configuration

Windows 11 x64
Works in 7.0.100-preview.7.22377.5
Fails in 7.0.100-rc.1.22431.12 and 7.0.100-rc.2.22463.6

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #8008

### Context
With MSBuild server, we adjust the console mode to be able to handle VT100 codes. We should undo that after each build to make it obvious to users mistakenly emitting VT100 codes that they should add code to properly handle them.

### Customer Impact
Console settings we enable while building with MSBuild server persist after the build. In particular, if a customer is outputting raw VT100 codes, they  will be properly formatted if their code is run using `dotnet run`, but their customers will see the raw codes because they will not inherit anything from MSBuild.

### Testing
Verified that building the project from #8008 no longer had unexpected spacing when these private bits were deployed to an SDK.
Verified that the bug motivating our original support for VT100 codes is still resolved.
Unit tests.

### Code Reviewers
rainersigwald, rokonec

### Description of the fix
Reset VT100 codes after each build.

### CODE REVIEW

File: src/Build/BackEnd/Client/MSBuildClient.cs [hunk 1]
```diff
@@ -207,6 +218,12 @@ public MSBuildClientExitResult Execute(CancellationToken cancellationToken)
 
             MSBuildEventSource.Log.MSBuildServerBuildStop(descriptiveCommandLine, _numConsoleWritePackets, _sizeOfConsoleWritePackets, _exitResult.MSBuildClientExitType.ToString(), _exitResult.MSBuildAppExitTypeString);
             CommunicationsUtilities.Trace("Build finished.");
+
+            if (_originalConsoleMode is not null)
+            {
+                NativeMethodsShared.SetConsoleMode(stdOut, _originalConsoleMode.Value);
```
Comment (rainersigwald) [inline src/Build/BackEnd/Client/MSBuildClient.cs:224]: Since identical cleanup code is required for multiple exit code paths should it be in a try/finally?

**Review by rainersigwald — APPROVED** [review]

File: src/Build/BackEnd/Client/MSBuildClient.cs [hunk 2]
```diff
@@ -353,6 +363,7 @@ private void ConfigureAndQueryConsoleProperties()
                     IntPtr stdOut = NativeMethodsShared.GetStdHandle(NativeMethodsShared.STD_OUTPUT_HANDLE);
                     if (NativeMethodsShared.GetConsoleMode(stdOut, out uint consoleMode))
                     {
+                        _originalConsoleMode = consoleMode;
```
Comment (rokonec) [inline src/Build/BackEnd/Client/MSBuildClient.cs:366]: If we moved this line before line `consoleMode |= NativeMethodsShared.ENABLE_VIRTUAL_TERMINAL_PROCESSING | NativeMethodsShared.DISABLE_NEWLINE_AUTO_RETURN;` nr 376 we would revert it to original only when we have had actually changed it. We most probably change it all the time, but still :-)

**Review by rokonec — APPROVED** [review]
