### PR TITLE
Don't hang on cycles in AfterTargets

### LINKED ISSUE #5662: Hang when a project has a cycle in AfterTargets dependencies
[This was reported internally by a Microsoft development team]

#5195 made failures in `AfterTargets` fail the build in all cases by introducing checks when constructing results. However, it is susceptible to cycles in the `AfterTargets` relation.

This project hangs:

```xml
<Project>
  <Target Name="Build" AfterTargets="After" />
  <Target Name="After" AfterTargets="Build" />
</Project>
```

It endlessly cycles between enqueuing `After` and `Build` in `targetsToCheckForAfterTargets` here:

https://github.com/dotnet/msbuild/blob/f2c4bfd563f559daca27ea1cd8ae40db24e2e7cd/src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs#L780-L799

### PR DESCRIPTION
**Pull request by rainersigwald**
Fixes #5662 by keeping track of visited targets and avoiding an infinite loop when encountering an already-visited target.

### CODE REVIEW

File: src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs [hunk 1]
```diff
@@ -777,6 +777,12 @@ private void ComputeAfterTargetFailures(string[] targetNames)
                     var targetsToCheckForAfterTargets = new Queue<string>();
                     targetsToCheckForAfterTargets.Enqueue(targetName);
 
+                    // Set of targets already processed, to break cycles of AfterTargets
+                    var targetsChecked = new HashSet<string>(MSBuildNameIgnoreCaseComparer.Default)
```
Comment (ladipro) [inline src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs:781]: nit: The `HashSet` could be constructed lazily when first needed inside the `foreach` below. It would eliminate the allocation in cases where the target has no AfterTargets (true for most targets?) I believe perf-wise it's still OK the way it is now as this is not a super hot path. Thank you!

**Review by ladipro — APPROVED** [review]
