### PR TITLE
Fix concurrency issue in PropertyDictionary

### LINKED ISSUE #12234: intermittent bug on build
On MSBuild repo build sometimes it breaks with 

```
Unhandled Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Build.Collections.RetrievableEntryHashSet`1.Enumerator.MoveNext()
   at Microsoft.Build.BackEnd.TranslatorExtensions.TranslateProjectPropertyInstanceDictionary(ITranslator translator, PropertyDictionary`1& value)
   at Microsoft.Build.Execution.BuildParameters.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
   at Microsoft.Build.BackEnd.TranslatorHelpers.Translate[T](ITranslator translator, T& instance, NodePacketValueFactory`1 valueFactory)
   at Microsoft.Build.BackEnd.NodeConfiguration.Translate(ITranslator translator)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.NodeContext.DrainPacketQueue(Object state)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Build failed with exit code -532462766. Check errors above.
```

It's the second occurrence of the bug, the first was reported by MSTest team internally.

Analyze codebase and fix what can cause it.

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes #12234

### Context
Fixed a race condition in `PropertyDictionary<T>` that was causing `InvalidOperationException: Operation is not valid due to the current state of the object` during MSBuild's multi-threaded serialization process.

**Root Cause**: The `GetEnumerator()` methods in `PropertyDictionary<T>` had a lock inconsistency issue:
1. They would acquire a lock on `_properties`
2. Get an enumerator from the underlying collection
3. **Immediately release the lock**
4. Return the enumerator for use outside the lock

This meant that while one thread was enumerating the collection (e.g., during serialization in `TranslateProjectPropertyInstanceDictionary`), another thread could modify the collection, causing the `RetrievableEntryHashSet<T>.Enumerator` to detect concurrent modification and throw an exception.

### Changes Made
added `ReaderWriterLockSlim` and foreach + yield return that will also hold the lock until the enumeration is done

### CODE REVIEW

**Comment by YuliiaKovalova** [comment]
@Erarndt  and @ccastanedaucf , could you please take a look and advice if you have a better idea for this?

File: src/Build/Collections/PropertyDictionary.cs
Comment (sgreenmsft) [inline src/Build/Collections/PropertyDictionary.cs:1]: CPS has special case scenarios where the collections are read only (because they come from an immutable evaluation cache). I'd suggest only copying the property collection if _properties.IsReadOnly != true. (Also, PropertyDictionary's implementation of IsReadOnly is wrong, as it should just forward to the underlying _properties.IsReadOnly).

In the case of PropertyDictionary instances that aren't read only, this approach to addressing concurrent changes seems a bit unusual. Developers don't normally anticipate that foreach will result in a size-of-data allocation. For example, the Equals method in this class does a foreach (T property in this), which is now unnecessarily a size-of-data allocation. (It's unnecessary because the foreach occurs within lock(_properties).) Similar issue applies to other methods in the class (e.g. ToDictionary). I've seen different strategies for addressing this sort of problem (e.g. a GetSnapshot method or a mechanism for acquiring Read or Write access to the collection).

File: src/Build/Collections/PropertyDictionary.cs [hunk 1]
```diff
@@ -241,21 +241,24 @@ public IEnumerator<T> GetEnumerator()
         {
             lock (_properties)
             {
-                return _properties.Values.GetEnumerator();
+                var snapshot = new List<T>(_properties.Values);
```
Comment (ccastanedaucf) [inline src/Build/Collections/PropertyDictionary.cs]: Generating an iterator under the lock (`foreach + yield return`) will also hold the lock until the enumeration is done + avoid the snapshot allocations, which I expect could be significant for areas like `Lookup` which enumerate `PropertyDictionary` a bunch in a single-threaded context.

Comment (sgreenmsft) [reply src/Build/Collections/PropertyDictionary.cs]: By itself holding the lock while iterating is okay, but if another collection starts doing that, then you can have fun deadlocks where Thread1 is iterating Properties and needs to get a value from OtherCollection, but must wait because Thread2 is iterating OtherCollection, but Thread2 is unable to make progress because it's waiting to retrieve a value from Properties. So I'd suggest switching to reader/writer locks if going down this route.

Comment (YuliiaKovalova) [reply src/Build/Collections/PropertyDictionary.cs]: done, please take a look

File: src/Build/Collections/PropertyDictionary.cs
Comment (sgreenmsft) [inline src/Build/Collections/PropertyDictionary.cs:1]: This mixes two different concurrency control mechanisms -- the standard lock and the ReaderWriterLockSlim. That'll not work out, because Thread1 can be holding a read lock from the ReaderWriterLockSlim when Thread2 calls Clear and immediately gets the lock(_properties). A general guideline for concurrency control mechanisms like this is to use just one, and to always use it for absolutely every access to the controlled state. In other words, if switching to ReaderWriterLockSlim, use that everywhere instead of lock(_properties).

Comment (sgreenmsft) [inline src/Build/Collections/PropertyDictionary.cs:1]: This line:
bool ICollection<KeyValuePair<string, T>>.IsReadOnly => false;

Should read like so:
bool ICollection<KeyValuePair<string, T>>.IsReadOnly => _properties.IsReadOnly;

Comment (YuliiaKovalova) [reply src/Build/Collections/PropertyDictionary.cs:1]: thank you for explanation, done

Comment (sgreenmsft) [reply src/Build/Collections/PropertyDictionary.cs:1]: Thanks! Looks good to me.

**Review by SimaTian — APPROVED** [review]
