### PR TITLE
Fix deadlock in BuildManager vs LoggingService

### LINKED ISSUE #6823: Hang in EndToEndMinimumMessageImportance
From a hung Windows Core job in https://dev.azure.com/dnceng/public/_build/results?buildId=1344731&view=results:

```
Executing [D:\a\1\s\artifacts\bin\Microsoft.Build.CommandLine.UnitTests\Debug\net472\MSBuild.exe /v:quiet /bl "C:\Users\VssAdministrator\AppData\Local\Temp\dcnuzjfp.his\Temporary3ff04b4277934e0ca805852f46be703e\build.proj"]
   Microsoft.Build.CommandLine.UnitTests: [Long Running Test] 'Microsoft.Build.UnitTests.XMakeAppTests.EndToEndMinimumMessageImportance', Elapsed: 00:01:01
...
   Microsoft.Build.CommandLine.UnitTests: [Long Running Test] 'Microsoft.Build.UnitTests.XMakeAppTests.EndToEndMinimumMessageImportance', Elapsed: 00:48:01
```

Looking at the test, nothing jumps out at me. Looks like we should at least make sure we're logging everything we can and maybe wrap a timeout around the test so that it fails instead of hanging (and hopefully provides some debugging information).

### PR DESCRIPTION
**Pull request by rokonec**
Fixes #6823

### Context
There is possible deadlock in BuildManager vs LoggingService when:
- verbosity=diagnostic or higher or /bl
- LoggingService works in `LoggerMode.Synchronous`

### Changes Made
LoggingService callbacks (OnProjectStarted, OnProjectFinished and OnThreadException) has been modified into async by leveraging existing workQueue.

### Testing
Compiled Orchardcore in CLI and VS2022.

### Notes
If these changes are considered safe, we can optionally revert PR #6717

### CODE REVIEW

**Review by Forgind — APPROVED** [review]
Seems safe enough to me. I'm a little curious about failing cases.

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 1]
```diff
@@ -832,10 +832,11 @@ public void EndBuild()
                 ShutdownConnectedNodes(false /* normal termination */);
                 _noNodesActiveEvent.WaitOne();
 
-                // Wait for all of the actions in the work queue to drain.  Wait() could throw here if there was an unhandled exception
+                // Wait for all of the actions in the work queue to drain.  _workQueue.Completion.Wait() could throw here if there was an unhandled exception
                 // in the work queue, but the top level exception handler there should catch everything and have forwarded it to the
                 // OnThreadException method in this class already.
                 _workQueue.Complete();
+                Task.WaitAny(_workQueue.Completion);
```
Comment (ladipro) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:839]: Why `WaitAny` when you're passing only one task?

Comment (rokonec) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:839]: Because `WaitAny` is only `Task.WaitXX` I am aware of which does not throw Exception if awaited task ends up in a Failed state. Exceptions during _workQueue DataFlow processing are handled in `ProcessWorkQueue` the only exceptions left this could throw, AFAIK, is `OperationCanceledException` which we shall swallow anyway.

Comment (ladipro) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:839]: Interesting! And very unobvious. Would an explicit try/catch with a comment be more appropriate? Or at least a comment.

(Perf super nit: `WaitAny` takes `params Task[]` so the call allocates an array.)

Comment (rainersigwald) [reply src/Build/BackEnd/BuildManager/BuildManager.cs]: > at least a comment

Yes, please.

**Review by rainersigwald — APPROVED** [review]

File: src/Build/BackEnd/BuildManager/BuildManager.cs (hunk 1 above)
Comment (rokonec) [reply src/Build/BackEnd/BuildManager/BuildManager.cs]: I have though about it more, and it looks like it shall never throws. It will be better it that unexpected exception will surface by `_workQueue.Completion.Wait();`.

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 2]
```diff
@@ -832,10 +832,12 @@ public void EndBuild()
...
                 _noNodesActiveEvent.WaitOne();
 
-                // Wait for all of the actions in the work queue to drain.  Wait() could throw here if there was an unhandled exception
-                // in the work queue, but the top level exception handler there should catch everything and have forwarded it to the
+                // Wait for all of the actions in the work queue to drain.
+                // _workQueue.Completion.Wait() could throw here if there was an unhandled exception in the work queue,
+                // but the top level exception handler there should catch everything and have forwarded it to the
                 // OnThreadException method in this class already.
                 _workQueue.Complete();
+                _workQueue.Completion.Wait();
```
Comment (ladipro) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:840]: Should this statement also be behind the changewave check? (Apologies for not adding this comment earlier.)

**Review by ladipro — APPROVED** [review]

File: src/Build/BackEnd/BuildManager/BuildManager.cs (hunk 2 above)
Comment (rokonec) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:845]: It is a good point. It was actually bug, I think, `_workQueue.Complete()` do not wait. But it could have, low probability, chance for regresion. Lets put it under ChangeWave.

**Review by ladipro — APPROVED** [review]
