### PR TITLE
Find assemblies by path from RoslynCodeTaskFactory Fixes #5106

### LINKED ISSUE #5106: RoslynCodeTaskFactory doesn't load external assemblies
### Steps to reproduce

When using an inline task that references an assembly by full path outside of a standard load directory, `RoslynCodeTaskFactory` is able to compile the snippet properly but not execute it.

This is a difference from `CodeTaskFactory` [which installs a custom assembly resolve handler](https://github.com/microsoft/msbuild/blob/1105f6db2fca58a45920ffb953a00aad2e93d794/src/Tasks/CodeTaskFactory.cs#L30-L55) to cope with this case.

As a workaround you can create a dummy inline task that uses `CodeTaskFactory` for the sole purpose of leveraging that assembly resolve handler:

```xml
<UsingTask
	TaskName="MyInlineTask"
	TaskFactory="RoslynCodeTaskFactory"
	AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
	<Task>
		<Reference Include="$(PathToMyInlineTaskDependency)" />
<!-- ... -->
	</Task>
</UsingTask>

<UsingTask
	TaskName="LoadMyDependencies"
	TaskFactory="CodeTaskFactory"
	AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
	<Task>
		<Reference Include="$(PathToMyInlineTaskDependency)" />
		<Code Type="Fragment" Language="cs"></Code>
	</Task>
</UsingTask>
```

### Expected behavior

`RoslynCodeTaskFactory` should be able to run inline tasks equally as well than `CodeTaskFactory`.

### Actual behavior

It doesn't support assemblies that are not on a standard loading path.

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #5106

### Context
When using an inline task with CodeTaskFactory (Framework-specific), it automatically adds resolving information to AppDomain.CurrentDomain if necessary. That didn't happen with RoslynCodeTaskFactory. This adds it.

### Changes Made
Added referenced assemblies for inline tasks using RoslynCodeTaskFactory to the current AppDomain/AssemblyLoadContext.

### Testing
Not enough yet, but the repro no longer repros.

### CODE REVIEW

File: src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs [hunk 1]
```diff
@@ -539,7 +542,14 @@ internal static bool TryResolveAssemblyReferences(TaskLoggingHelper log, RoslynC
...
                 {
                     // The path could be relative like ..\Assembly.dll so we need to get the full path
-                    resolvedAssemblyReferences.Add(Path.GetFullPath(reference));
+                    string fullPath = Path.GetFullPath(reference);
+                    string directory = Path.GetDirectoryName(fullPath);
+                    resolvedAssemblyReferences.Add(fullPath);
+#if NETFRAMEWORK
+                    AppDomain.CurrentDomain.AssemblyResolve += (_, eventArgs) => TryLoadAssembly(directory, new AssemblyName(eventArgs.Name).Name);
+#else
+                    AssemblyLoadContext.Default.Resolving += (_, assemblyName) => TryLoadAssembly(directory, assemblyName.Name);
```
Comment (rainersigwald) [inline src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:551]: Can we attach this to the plugin ALC that we're in, instead of `Default`?

Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:551]: So I _think_ that would be AssemblyLoadContext.GetLoadContext(typeof(RoslynCodeTaskFactory).Assembly)...

Is that right? I vaguely remember that we started make a separate load context for every task a couple years ago, but I never had a solid understanding of all that was going on.

Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:551]: Current version works for dotnet build scenarios; changing to Default to GetLoadContext(typeof(RoslynCodeTaskFactory).Assembly) did not work. Is it something else?

Comment (rainersigwald) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:551]: What does `CodeTaskFactory` do for .NET Framework? Does it just add it to the default appdomain?

Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:551]: Yes:
https://github.com/dotnet/msbuild/blob/9476453a935b612482332633abc4b1c144e1e483/src/Tasks/CodeTaskFactory.cs#L54
(Though it has to flesh out that function.)

**Comment by Forgind** [comment]
I've been working on a test. My current issue is that I have a simple project:
```XML
<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

that builds perfectly fine from the command line with `msbuild /p:OutDir={folder} /restore` but not using RunnerUtilities.ExeMSBuild(pathToProject + $" /p:OutDir={folder} /restore", out bool success);

If you have quick thoughts as to what might be going wrong, I'm happy to hear them. Otherwise, I might look a little more tomorrow.

**Comment by Forgind** [comment]
I was essentially embedding my repro into a unit test:
Make a project
Build it
Make a second project with an inline task that relies on the newly-built assembly and uses a RoslynCodeTaskFactory
Build that

I skipped the first build step and did that from a command line, and the rest of the test passed. So I guess I need a project that compiles C# code? So maybe import some .targets file (which?), add the C# file to <Compile Include= />, and call CoreCompile?

**Comment by rainersigwald** [comment]
It's usually much easier to compile a type into an existing assembly, like the test assembly. That seems like it'd be an option here.

**Comment by Forgind** [comment]
If I remember correctly, it was looking for the assembly next to MSBuild, so it would find the test assembly, just not a custom assembly or an assembly in a weird spot.

**Comment by Forgind** [comment]
Got it to work 🙂

File: src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs (hunk 1 above)
Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:551]: Team triage:
Try just using AppDomain.CurrentDomain.AssemblyResolve even on Core

Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:551]: And remove the new assembly resolving behavior

File: src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs [hunk 2]
```diff
@@ -573,6 +590,12 @@ internal static bool TryResolveAssemblyReferences(TaskLoggingHelper log, RoslynC
             items = hasInvalidReference ? null : resolvedAssemblyReferences.Select(i => (ITaskItem)new TaskItem(i)).ToArray();
 
             return !hasInvalidReference;
+
+            static Assembly TryLoadAssembly(string directory, string name)
```
Comment (rainersigwald) [inline src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:594]: Is it possible to have a single method that looks at the list? That feels more robust to me.

File: eng/Packages.props [hunk 3]
```diff
@@ -25,6 +25,7 @@
     <PackageReference Update="System.Reflection.Metadata" Version="1.6.0" />
     <PackageReference Update="System.Resources.Extensions" Version="$(SystemResourcesExtensionsPackageVersion)" />
     <PackageReference Update="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
+    <PackageReference Update="System.Runtime.Loader" Version="4.3.0" />
```
[the remark this answers is not in the document]
Comment (Forgind) [reply eng/Packages.props:28]: That was for ALC, and that's completely gone now, so yes. Thanks!

File: src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs [hunk 4]
```diff
@@ -19,6 +26,70 @@ public class RoslynCodeTaskFactory_Tests
     {
         private const string TaskName = "MyInlineTask";
 
+        [Fact]
+        [SkipOnPlatform(TestPlatforms.AnyUnix, ".NETFramework 4.0 isn't on unix machines.")]
```
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:30]: Did we? All I remember is the comment you had above. I had a series of commits in which I tried to make 5106.csproj build on core; building a project on its own was easy but making it also compile a C# file stymied my progress for a bit. (We don't currently have any other tests that use RunnerUtilities.ExecMSBuild with a project that has a C# file to compile, and if we do it some other way (without relying on framework), I didn't see it.) Ultimately, I think it matters that it works on both core and framework, and this still verifies that it works on both, just not on other platforms.

If it's a dependency built as a normal part of build, I'd worry that we aren't testing anything; if it's already loaded into the current appdomain, the test could pass without this change. (And even if I have a test that currently fails without the change and passes with it, I'd worry that we'd start loading it at some point before this test just by introducing a new unit test, and then we could break this without noticing.

File: src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs (hunk 2 above)
Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:594]: I thought about that, and I think the answer is "not cleanly." As I currently understand this, the fact that RoslynCodeTaskFactory is your TaskFactory is essentially a detail as part of execute a particular task. It notices that you said you wanted that, and some RoslynCodeTaskFactory code runs to set up the task for execution, but when it's finished, the task hasn't yet executed, so we can't remove the ResolveEventHandler yet. Then it executes the task in code not associated with RoslynCodeTaskFactory and comes back at the end to call a generic "cleanup" that calls this. If I want it all to be in one method as would be ideal, I think I'd have to first make all TaskFactories return a list of ResolveEventHandlers at some point (though most of them would return null), then check if it's non-null just before actually executing the task and add them to the AssemblyResolve if so and remove them afterwards. CleanupTask should always run even if the task's execution throws an exception (it's in a finally block) and briefly returns control back to the RoslynCodeTaskFactory with the relevant information, so it seemed like the best option. I did verify in a debugger that it got to that point and found a list with the expected number of ResolveEventHandlers in it and removed them all without exceptions. (I don't remember if I verified they were attached beforehand—either I did or I didn't see how to.)

Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:591]: NTS: Condense various handlers into one handler

File: src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (rainersigwald) [reply src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:30]: > If it's a dependency built as a normal part of build, I'd worry that we aren't testing anything; if it's already loaded into the current appdomain, the test could pass without this change.

That won't be the case if you continue to use ExecMSBuild and push it into its own process, and it's also the sort of thing that you could validate in the test. I think it's worth doing this to avoid OS-specific tests where possible.

File: src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs [hunk 5]
```diff
@@ -19,6 +27,101 @@ public class RoslynCodeTaskFactory_Tests
...
+        {
+            using (TestEnvironment env = TestEnvironment.Create())
+            {
+                TransientTestFolder folder = env.CreateFolder(createFolder: true);
+                TransientTestFile inlineTask = env.CreateFile(folder, "5106.proj", @$"
+<Project>
+
+  <UsingTask TaskName=""MyInlineTask"" TaskFactory=""RoslynCodeTaskFactory"" AssemblyFile=""$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll"">
+    <Task>
+      <Reference Include=""{Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)}\..\..\..\Samples\Dependency\Debug\net472\Dependency.dll"" />
```
Comment (Forgind) [inline src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:41]:
```suggestion
      <Reference Include=""{ Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)}, "..", "..", "..", "Samples", "Dependency", "Debug", "net472", "Dependency.dll") }"" />
```

File: src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs [hunk 6]
```diff
@@ -19,6 +27,101 @@ public class RoslynCodeTaskFactory_Tests
...
+        {
+            using (TestEnvironment env = TestEnvironment.Create())
+            {
+                TransientTestFolder folder = env.CreateFolder(createFolder: true);
+                TransientTestFile inlineTask = env.CreateFile(folder, "5106.proj", @$"
+<Project>
+
+  <UsingTask TaskName=""MyInlineTask"" TaskFactory=""RoslynCodeTaskFactory"" AssemblyFile=""$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll"">
+    <Task>
+      <Reference Include=""{ Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)}, "..", "..", "..", "Samples", "Dependency", "Debug", "net472", "Dependency.dll") }"" />
```
Comment (Forgind) [inline src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:41]:
```suggestion
      <Reference Include=""{ Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "..", "..", "..", "Samples", "Dependency", "Debug", "net472", "Dependency.dll") }"" />
```

File: src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs [hunk 7]
```diff
@@ -19,6 +27,102 @@ public class RoslynCodeTaskFactory_Tests
...
+");
+                string output = RunnerUtilities.ExecMSBuild(inlineTask.Path, out bool success);
+                success.ShouldBeTrue(output);
+                output.ShouldContain("Alpha.GetString");
+            }
+        }
+
+        [Fact]
+        [SkipOnPlatform(TestPlatforms.AnyUnix, ".NETFramework 4.0 isn't on unix machines.")]
+        public void InlineTaskWithAssembly()
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:66]: Does this add anything over the cross-plat version now?

File: src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs [hunk 8]
```diff
@@ -19,6 +27,102 @@ public class RoslynCodeTaskFactory_Tests
...
+            using (TestEnvironment env = TestEnvironment.Create())
+            {
+                TransientTestFolder folder = env.CreateFolder(createFolder: true);
+                string location = Assembly.GetExecutingAssembly().Location;
+                TransientTestFile inlineTask = env.CreateFile(folder, "5106.proj", @$"
+<Project>
+
+  <UsingTask TaskName=""MyInlineTask"" TaskFactory=""RoslynCodeTaskFactory"" AssemblyFile=""$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll"">
+    <Task>
+      <Reference Include=""{ Path.Combine(Path.GetDirectoryName(location), "..", "..", "..", "Samples", "Dependency", location.Contains("Debug") ? "Debug" : "Release", "net472", "Dependency.dll") }"" />
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:42]: I think I'd do `#if DEBUG` instead of the path-contains check (it's more reliable in the case that e.g. some dev has all their source in `Q:\Debug\msbuild`) but that's pretty nitpicky.

File: src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs [hunk 9]
```diff
@@ -572,7 +585,24 @@ internal static bool TryResolveAssemblyReferences(TaskLoggingHelper log, RoslynC
...
+            handlerAddedToAppDomain = (_, eventArgs) => TryLoadAssembly(directoriesToAddToAppDomain, new AssemblyName(eventArgs.Name).Name);
+            AppDomain.CurrentDomain.AssemblyResolve += handlerAddedToAppDomain;
+
             return !hasInvalidReference;
+
+            static Assembly TryLoadAssembly(List<string> directories, string name)
+            {
+                foreach (string directory in directories)
+                {
+                    string path = Path.Combine(directory, name + ".dll");
```
Comment (rainersigwald) [inline src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:597]: This is different and less complicated than what we have in `CoreCLRAssemblyLoader`. Do we need the culture-subdirectory lookup and the check-that-name-actually-matches stuff here, too?

File: src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs (hunk 8 above)
Comment (Forgind) [reply src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:42]: This is doable but a bit fiddly because I don't think you can put a #if in the middle of a string. I can make it three strings and concat them, I guess.

File: src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs (hunk 9 above)
Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:597]: I don't think so. As I understand RoslynCodeTaskFactory, for this case, you have to pass it the exact path to your assembly, in which case it isn't in a subfolder, or you would've had to provide that. I only turned it into a directory and back into a file here to prevent a search for (unrelated) Foo to match Bar.dll just because I was too permissive.

Comment (rainersigwald) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:597]: That's true for the assembly you directly reference, but what about _its_ dependencies and satellites?

File: src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs (hunk 7 above)
Comment (rainersigwald) [reply src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:66]: I regard this method of building an assembly during tests as unreliable and suspect, because it's so different from "normal" projects. I don't understand the "start loading Dependency" comments--we're starting a fresh process for the test so how would it have loaded Dependency?

Comment (Forgind) [reply src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:66]: If it turns out to be a flaky test, we can remove it. Good enough?

Comment (Forgind) [reply src/Tasks.UnitTests/RoslynCodeTaskFactory_Tests.cs:66]: It's a fresh process, but it's a fresh MSBuild process, so it automatically knows about things next to itself. If we start including Dependency.dll next to MSBuild for some reason.

File: src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs (hunk 9 above)
Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:597]: It'll silently work as long as its dependencies are next to it. If you have dependencies that you don't copy to your output directory, we don't have a great way of finding them anyway.

Comment (Forgind) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:597]: And if you're thinking I should use an AssemblyDependencyResolver to read a deps.json file, that feels like overkill here 🙂

Comment (rainersigwald) [reply src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:597]: I am not suggesting that, I am suggesting this:

https://github.com/dotnet/msbuild/blob/18fc0b3dd9dfd7cbb83272f13de4a89e8aa30531/src/Shared/CoreCLRAssemblyLoader.cs#L148-L175

Note specifically the culture-subdirectory stuff, which breaks the "next-to-it" rule but is predictable.

File: src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs [hunk 10]
```diff
@@ -572,7 +585,33 @@ internal static bool TryResolveAssemblyReferences(TaskLoggingHelper log, RoslynC
...
+            {
+                foreach (string directory in directories)
+                {
+                    string path = Path.Combine(directory, name.Name + ".dll");
+                    if (File.Exists(path))
+                    {
+                        return Assembly.LoadFrom(path);
+                    }
+
+                    if (!string.IsNullOrEmpty(name.CultureName))
```
Comment (rainersigwald) [inline src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs:603]: Can you swap this to be first?

**Review by rainersigwald — APPROVED** [review]
