### PR TITLE
Workaround for "MSB4166: Child node "1" exited prematurely"

### LINKED ISSUE #11326: Enabling BuildCheck causes  error MSB4166: Child node "1" exited prematurely
### Issue Description

Enabling BuildCheck on runtime and other repos caused

```
 error MSB4166: Child node "1" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\cloudtest\AppData\Local\Temp\MSBuildTemp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 415 should have been in the ID-to-project file mapping but wasn't!
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.BackEnd.Logging.LoggingService.GetAndVerifyProjectFileFromContext(BuildEventContext context)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogBuildEvent(BuildEventArgs buildEvent)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildCheckManagerProvider.BuildCheckManager.StartProjectRequest(ICheckContext checkContext, String projectFullPath)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildCheckBuildEventHandler.HandleProjectStartedRequest(ProjectStartedEventArgs eventArgs)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildCheckConnectorLogger.EventSource_AnyEventRaised(Object sender, BuildEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.<Consume>b__81_9(ProjectStartedEventArgs args)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.<Consume>b__81_9(ProjectStartedEventArgs args)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)
```

or

```
##[error]Child node "1" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTempcloudtest/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 61 should have been in the ID-to-project file mapping but wasn't!
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.BackEnd.Logging.LoggingService.GetAndVerifyProjectFileFromContext(BuildEventContext context)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogBuildEvent(BuildEventArgs buildEvent)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildCheckManagerProvider.BuildCheckManager.Microsoft.Build.Experimental.BuildCheck.Infrastructure.IResultReporter.ReportResult(BuildEventArgs eventArgs, ICheckContext checkContext)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.CheckWrapper.ReportResult(BuildCheckResult result, ICheckContext checkContext, CheckConfigurationEffective config)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildEventsProcessor.ReportResult(CheckWrapper checkWrapper, ICheckContext checkContext, CheckConfigurationEffective[] configPerRule, BuildCheckResult result)
   at Microsoft.Build.Experimental.BuildCheck.Checks.PropertiesUsageCheck.DoneWithProject(BuildCheckDataContext`1 context)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildCheckCentralContext.<>c__DisplayClass25_0`1.<RegisterAction>g__WrappedHandler|0(BuildCheckDataContext`1 context)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildCheckCentralContext.RunRegisteredActions[T](List`1 registeredCallbacks, T checkData, ICheckContext checkContext, Action`4 resultHandler)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildEventsProcessor.ProcessProjectDone(ICheckContext checkContext, String projectFullPath)
   at Microsoft.Build.Experimental.BuildCheck.Infrastructure.BuildCheckBuildEventHandler.HandleBuildEvent(BuildEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)

```

It fails randomly but for sure caused by the feature.

### Steps to Reproduce

navigate to the repo and observe the issue https://github.com/dotnet/extensions/pull/5810/checks?check_run_id=35940423010 or check the binlog attached (change .zip -> .binlog)

[Build_runtime_windows.zip](https://github.com/user-attachments/files/18522252/Build_runtime_windows.zip)

### Expected Behavior

BuildCheck runs smootly.

### Actual Behavior

enabling the feature causes build crash.

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes #11326

### Context
BuildCheck can still emit some LogBuildEvent(s) after `ProjectFinishedEventArgs` was reported and entries from `_projectFileMap` were cleaned up.
Due to `GetAndVerifyProjectFileFromContext` validation, these checks break the build.

### Changes Made
If `BuildCheck` is enabled, `_projectFileMap` won't be cleaned up. If it brings significant perf overhead , this approach will be reconsidered.

### Testing
n/a

### CODE REVIEW

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 1]
```diff
@@ -473,6 +473,11 @@ public int MaxCPUCount
         /// </summary>
         public bool Question { get; set; }
 
+        /// <summary>
+        /// Gets or sets a value if BuildCheck is enabled. The presence of this flag influences the logging logic.
+        /// </summary>
+        internal bool BuildCheckEnabled { get; set; }
```
Comment (JanKrivanek) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:479]: No need for this to be exposed outside of this class - private field is fine.
Or we can just check `this._componentHost.BuildParameters.IsBuildCheckEnabled` in the logging method

**Review by JanKrivanek — APPROVED** [review]
Looks good!

Please reconsider exposing state that is not used outside of the class - it's generally better to avoid this.

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 2]
```diff
@@ -871,6 +876,8 @@ public void InitializeComponent(IBuildComponentHost buildComponentHost)
                 _serviceState = LoggingServiceState.Initialized;
 
                 _buildEngineDataRouter = (buildComponentHost.GetComponent(BuildComponentType.BuildCheckManagerProvider) as IBuildCheckManagerProvider)?.BuildEngineDataRouter;
+
+                _buildCheckEnabled = buildComponentHost.BuildParameters!.IsBuildCheckEnabled;
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:880]: This `!` looks fishy (we're dereferencing `buildComponentHost.BuildParameters` above) and it builds successfully on my machine without it. Is it needed for you?

**Review by rainersigwald — APPROVED** [review]
