### PR TITLE
Fix TerminalLogger node status restoration after MSBuild task yields

### LINKED ISSUE #12819: TerminalLogger node status is lost after MSBuild task yields and resumes
## Issue Description

When a project uses the `<MSBuild>` task to build another project (e.g., using `BuildInParallel="true"` or just calling another project), the current node "yields" execution to the other project. `TerminalLogger` correctly handles the start of this yield by clearing the node status in `TaskStarted("MSBuild")` to indicate the node is waiting.

However, `TerminalLogger` fails to **restore** the node status when the `<MSBuild>` task finishes and the node resumes execution. This results in the node's status remaining `null` for the rest of the project's execution.

This causes:

1. "Invisible" nodes in the terminal output (nodes doing work but not showing up in the status bar).
2. Potential `NullReferenceException`s or missing data in other loggers/handlers that rely on the current node status (as seen in the related VSTest reporting issue).

## Steps to Reproduce

1. Download and extract the attached [Project.zip](https://github.com/user-attachments/files/23713587/Project.zip)
2. Run the build using the following command:

   ```cmd
   msbuild Repro\Main.proj /t:Build /m /tl:on
   ```

## Expected Behavior

When `Leaf.proj` finishes and `Worker.proj` resumes (during the sleep), the terminal status bar should show the Worker node as active (e.g., `Worker (Build) (x.xs)`).

## Actual Behavior

The terminal status bar does not show the Worker node during the sleep phase. The node slot appears empty or is not updated, because the internal state is `null`.

## Analysis

The issue is in `TerminalLogger.cs`. There is a handler for `TaskStarted` that clears the node status when `e.TaskName == "MSBuild"`, but there is no corresponding logic in `TaskFinished` to restore the status from the `TerminalProjectInfo`.

### PR DESCRIPTION
**Pull request by JanProvaznik**
Fixes #12819 

## Context

This PR addresses the root cause of `TerminalNodeStatus` becoming null unexpectedly during builds. This was identified as the underlying cause for issues where test summaries were missing because the logger couldn't attribute events to an active node (discussed in [related PR/Issue]).

When the `<MSBuild>` task runs, the node yields. `TerminalLogger` correctly cleared the status on yield but failed to restore it upon resume.

## Changes Made

* Implemented `TaskFinished` handler in `TerminalLogger.cs`.
* Added logic to detect when the `MSBuild` task finishes.
* Restores the `TerminalNodeStatus` using the preserved `TerminalProjectInfo` (ProjectFile, TargetFramework, etc.) and the `CurrentTarget`.
* Restarts the stopwatch for the project to accurately track the resumed duration.

## Testing

* **Unit Test:** Added `DisplayNodesRestoresStatusAfterMSBuildTaskYields` to `TerminalLogger_Tests.cs`. This test simulates the `TaskStarted("MSBuild")` -> `TaskFinished("MSBuild")` sequence and asserts that `DisplayNodes()` renders the project status correctly after the task finishes.
* **Manual Verification:** Verified using a multi-process reproduction project where worker nodes yield to leaf projects. Confirmed that worker nodes reappear in the terminal status bar after the leaf projects complete.

## Notes

This ensures that long-running tasks occurring *after* an MSBuild task call are correctly visualized in the terminal, and that any logic depending on `_nodes[index]` being non-null works as expected.

### CODE REVIEW

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs [hunk 1]
```diff
@@ -1042,6 +1044,25 @@ private void TaskStarted(object sender, TaskStartedEventArgs e)
...
+        if (_restoreContext is null && buildEventContext is not null && e.TaskName == "MSBuild")
+        {
+            if (_projects.TryGetValue(new ProjectContext(buildEventContext), out TerminalProjectInfo? project))
+            {
+                project.Stopwatch.Start();
+
+                string projectFile = Path.GetFileNameWithoutExtension(e.ProjectFile);
+                TerminalNodeStatus nodeStatus = new(projectFile, project.TargetFramework, project.RuntimeIdentifier, project.CurrentTarget ?? "", project.Stopwatch);
+                UpdateNodeStatus(buildEventContext, nodeStatus);
+            }
```
[the remark this answers is not in the document]
Comment (JanProvaznik) [reply src/Build/Logging/TerminalLogger/TerminalLogger.cs]: overwhelming, I prefer the if with `out` being separate

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs [hunk 2]
```diff
@@ -1042,6 +1044,25 @@ private void TaskStarted(object sender, TaskStartedEventArgs e)
...
+    {
+        var buildEventContext = e.BuildEventContext;
+        if (_restoreContext is null && buildEventContext is not null && e.TaskName == "MSBuild")
+        {
+            if (_projects.TryGetValue(new ProjectContext(buildEventContext), out TerminalProjectInfo? project))
+            {
+                project.Stopwatch.Start();
+
+                string projectFile = Path.GetFileNameWithoutExtension(e.ProjectFile);
+                TerminalNodeStatus nodeStatus = new(projectFile, project.TargetFramework, project.RuntimeIdentifier, project.CurrentTarget ?? "", project.Stopwatch);
```
[the remark this answers is not in the document]
Comment (JanProvaznik) [reply src/Build/Logging/TerminalLogger/TerminalLogger.cs]: addressed

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs [hunk 3]
```diff
@@ -1042,6 +1042,27 @@ private void TaskStarted(object sender, TaskStartedEventArgs e)
         }
     }
 
+    /// <summary>
+    /// The <see cref="IEventSource.TaskFinished"/> callback.
+    /// </summary>
```
Comment (baronfel) [inline src/Build/Logging/TerminalLogger/TerminalLogger.cs:1048]: I think this will work for single node builds, but for multi node builds you will need to add a forwarder for the TaskFinished message to the matching forwarding loggers that are running on each node so that the central node gets those messages and can process them.

Comment (JanProvaznik) [reply src/Build/Logging/TerminalLogger/TerminalLogger.cs:1048]: So you're thinking that there would be the same issue when there are 3 layers:
```
Root
  middle1
    leaf1
  middle2
    leaf2
  middle3
    leaf3
```

so that middle would not show up after leaf finishes?

I can't repro that (I suspect msbuild task is somehow special and the worker nodes don't really run it this way, since it's a task that interacts with scheduling), but it makes sense to include the forwarding anyway, so I pushed a commit

Comment (baronfel) [reply src/Build/Logging/TerminalLogger/TerminalLogger.cs:1048]: You'd need enough 'work units' (schedulable projects) for the scheduler to realize that it needs more nodes - then it would create more nodes to do the work and those nodes would get instances of the forwarding loggers attached. 

I think you can force this with the NOINPROCNODE trait flag (it has a slightly different name that I can't remember right now)

File: src/Build.UnitTests/TerminalLogger_Tests.cs [hunk 4]
```diff
@@ -58,12 +169,15 @@ public TerminalLogger_Tests(ITestOutputHelper outputHelper)
...
             _terminallogger = new TerminalLogger(_mockTerminal);
-
-            _terminallogger.Initialize(this, _nodeCount);
-
+            _terminallogger.Initialize(_centralNodeEventSource, _nodeCount);
             _terminallogger.CreateStopwatch = () => new MockStopwatch();
 
+            _remoteTerminalLogger = new ForwardingTerminalLogger();
+            _remoteTerminalLogger.BuildEventRedirector = new EventRedirectorToSink(0, _centralNodeEventSource);
+            _remoteTerminalLogger.Initialize(_remoteNodeEventSource, 1);
```
Comment (baronfel) [inline src/Build.UnitTests/TerminalLogger_Tests.cs:179]: @JanProvaznik here's the main set of changes I did to enable the remote-node testing:
* extracted out the fake event source
* made an eventsource for the central and remote nodes
* configured the remote node to forward to the central node

File: src/Build.UnitTests/TerminalLogger_Tests.cs [hunk 5]
```diff
@@ -938,9 +1013,106 @@ public async Task ProjectFinishedReportsTargetFrameworkAndRuntimeIdentifier()
...
+        public async Task DisplayNodesRestoresStatusAfterMSBuildTaskYields_TestProject(bool runOnCentralNode)
+        {
+            // 1. Start Build
+            _centralNodeEventSource.InvokeBuildStarted(MakeBuildStartedEventArgs());
+
+            // the project can be evaluated and built either locally or remotely - so the actual innards should happen on either the central or remote event source
+
+            var targetNodeEventSource = runOnCentralNode ? _centralNodeEventSource : _remoteNodeEventSource;
+            // default build context is for the 'central' node
+            var buildContext = runOnCentralNode ? null : MakeBuildEventContext(nodeId: 1);
```
Comment (baronfel) [inline src/Build.UnitTests/TerminalLogger_Tests.cs:1033]: then when we do the test, we can pick which node it should report through - in either case the output should be the same (because there's only one project building, but choosing the 'remote' node tests the forwarding/filtering mechanism.

If you go comment out your forwarding and run this test it'll fail on the `runOnCentralNode: false` case, as we hoped!

File: src/Build/Logging/TerminalLogger/ForwardingTerminalLogger.cs [hunk 6]
```diff
@@ -99,6 +100,16 @@ public void TaskStarted(object sender, TaskStartedEventArgs e)
         }
     }
 
+    public void TaskFinished(object sender, TaskFinishedEventArgs e)
+    {
+        // The central node updates the 'in-flight' node status on the terminal
+        // when a node finishes the MSBuild task, so we need to forward these along so that behavior still works.
+        if (e.BuildEventContext is not null && e.TaskName == "MSBuild")
```
Comment (MichalPavlik) [inline src/Build/Logging/TerminalLogger/ForwardingTerminalLogger.cs]: Would it be possible to use `nameof(T)` instead of hardcoded string?

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs [hunk 7]
```diff
@@ -1042,6 +1042,27 @@ private void TaskStarted(object sender, TaskStartedEventArgs e)
...
+    private void TaskFinished(object sender, TaskFinishedEventArgs e)
+    {
+        var buildEventContext = e.BuildEventContext;
+        if (_restoreContext is null && buildEventContext is not null && e.TaskName == "MSBuild")
+        {
+            if (_projects.TryGetValue(new ProjectContext(buildEventContext), out TerminalProjectInfo? project))
```
Comment (MichalPavlik) [inline src/Build/Logging/TerminalLogger/TerminalLogger.cs]: It seems this check could be added to the parent `if` statement.

File: src/Build/Logging/TerminalLogger/ForwardingTerminalLogger.cs (hunk 6 above)
Comment (JanProvaznik) [reply src/Build/Logging/TerminalLogger/ForwardingTerminalLogger.cs]: extracted to constants, I don't like adding using backend namespace to this file

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs (hunk 7 above)
Comment (JanProvaznik) [reply src/Build/Logging/TerminalLogger/TerminalLogger.cs]: ok
