### PR TITLE
Fix System.IO.File/Directory property functions with relative paths in -mt mode

### LINKED ISSUE #13237: Property functions using System.IO.File with relative paths break in -mt mode due to shared Environment.CurrentDirectory
### Description

MSBuild property functions that invoke System.IO.File methods (e.g., ReadAllText, Exists, ReadAllLines) with **relative paths** produce incorrect results or fail in multi-threaded (-mt) mode. This is because these calls are dispatched via reflection and resolve relative paths using Environment.CurrentDirectory, which is a process-global shared state — unsafe when multiple worker nodes are evaluating projects concurrently.

### Repro

**Project file** (e.g., src/Containers/packaging/package.csproj in dotnet/sdk):
`xml
<Target Name="PreparePackageReleaseNotesFromFile" BeforeTargets="GenerateNuspec">
    <PropertyGroup>
        <PackageReleaseNotesFile>../docs/ReleaseNotes/v8.0.300.md</PackageReleaseNotesFile>
        <PackageReleaseNotes>$([System.IO.File]::ReadAllText($(PackageReleaseNotesFile)))</PackageReleaseNotes>
    </PropertyGroup>
</Target>
`

**Without -mt**: Works correctly. ../docs/ReleaseNotes/v8.0.300.md resolves relative to the project directory.

**With -mt**: Fails with:
`
error MSB4184: The expression "[System.IO.File]::ReadAllText(../docs/ReleaseNotes/v8.0.300.md)" cannot be evaluated. 
Could not find a part of the path '/home/builder/dotnet/src/docs/ReleaseNotes/v8.0.300.md'.
`

The relative path resolved from the **wrong directory** — another project's directory that happened to be the current Environment.CurrentDirectory on a different worker node.

### Root Cause

MSBuild's property function evaluation has two paths:

1. **Well-known functions** (WellKnownFunctions.cs) — intercepted and handled with proper working directory context. For example, Path.GetFullPath correctly uses FileUtilities.CurrentThreadWorkingDirectory (line 108):
   `csharp
   returnVal = !string.IsNullOrEmpty(FileUtilities.CurrentThreadWorkingDirectory)
       ? Path.GetFullPath(Path.Combine(FileUtilities.CurrentThreadWorkingDirectory, arg0))
       : Path.GetFullPath(arg0);
   `

2. **Everything else** — falls through to reflection-based InvokeMember (Expander.cs line 4108):
   `csharp
   functionResult = _receiverType.InvokeMember(_methodMethodName, _bindingFlags, 
       Type.DefaultBinder, objectInstance, args, CultureInfo.InvariantCulture);
   `

System.IO.File.ReadAllText is **not** a well-known function, so it takes path (2). When called with a relative path, the CLR resolves it using Environment.CurrentDirectory — a process-global that is concurrently modified by other MSBuild worker nodes.

### Impact

This is a **compatibility bug** — any project file that uses [System.IO.File]::ReadAllText(relative-path) (or similar System.IO.File methods with relative paths) works correctly in single-threaded mode but silently produces wrong results or fails in -mt mode.

Found in VMR source-build testing: dotnet/sdk's src/Containers/packaging/package.csproj fails with this pattern. A grep of the VMR shows **37 usages** of [System.IO.File] in project files — any using relative paths are potentially affected.

### Expected Behavior

Property functions that accept file paths should resolve relative paths consistently using the project directory (MSBuildProjectDirectory) regardless of -mt mode, the same way Path.GetFullPath does.

### Suggested Fix

Either:
1. **Intercept System.IO.File methods** in WellKnownFunctions.cs and resolve relative paths using FileUtilities.CurrentThreadWorkingDirectory before delegating, or
2. **Set Environment.CurrentDirectory** per-thread before invoking any property function via reflection (not feasible — it's process-global), or
3. **Resolve relative path arguments** in the generic InvokeMember fallback path — for any System.IO.File method argument that is a relative path, prepend FileUtilities.CurrentThreadWorkingDirectory before invoking.

Option (1) is the most reliable and consistent with the existing Path.GetFullPath interception pattern.

### Environment
- MSBuild 18.5.0 (main branch, preview 2)
- Ubuntu 24.04, -mt mode
- Discovered during VMR 2-stage source-build with MSBuild -mt validation

### PR DESCRIPTION
**Pull request by JanProvaznik**
## Summary

Property functions like `$([System.IO.File]::Exists('relative.txt'))` and `$([System.IO.File]::ReadAllText('data.txt'))` resolved relative paths against `Environment.CurrentDirectory` (process-global), which produces wrong results in `-mt` mode where multiple projects build concurrently on different threads sharing the same process.

This change resolves relative path arguments for `System.IO.File` and `System.IO.Directory` property functions against `FrameworkFileUtilities.CurrentThreadWorkingDirectory` (the thread-local working directory set by `MultiThreadedTaskEnvironmentDriver`), matching the existing behavior of `Path.GetFullPath` which was already intercepted in `WellKnownFunctions`.

In multiprocess mode, `CurrentThreadWorkingDirectory` is null and the resolution is a no-op — zero behavior change.

### `src/Framework/FileUtilities.cs`
- Add `MakeFullPathFromThreadWorkingDirectory(string path)` helper next to other `AbsolutePath` helpers (`NormalizePath`, `FixFilePath`).
- Uses `Path.IsPathFullyQualified` to skip already-absolute paths and `Path.GetFullPath(path, basePath)` (2-arg overload) for correct handling of drive-relative paths (`\foo`, `C:foo`) on Windows.
- Falls back to `Path.Combine` for invalid paths (wildcards, illegal chars) to preserve the non-throwing behavior of `File.Exists`/`Directory.Exists`.
- Callers must call `FixFilePath` before passing paths (documented in XML doc).

### `src/Build/Evaluation/Expander.cs`
- Add `IsFileOrDirectoryPathArgument(string methodName, int argIndex)` to identify which arguments are file/directory paths (arg0 = always a path, arg1 = dest for Copy/Move/Replace, arg2 = backup for Replace). `CreateSymbolicLink` arg1 is intentionally excluded — its target path is semantically relative.
- Add path resolution in `Function.Execute()` arg assembly loop for `System.IO.File` and `System.IO.Directory` receiver types. Resolution happens **after** `UnescapeAll` so that the working directory path (a real filesystem path) is not corrupted by MSBuild `%xx` unescape processing.
- **Fix pre-existing bug**: Type comparisons used `typeof(Directory)` which resolves to `Microsoft.IO.Directory` on net472 due to `FEATURE_MSIOREDIST` alias, but `_receiverType` from `AvailableStaticMethods` is always `System.IO.Directory`. Changed to fully-qualified `typeof(System.IO.Directory)` etc.

### `src/Shared/FileUtilities.cs`
- Removed duplicate `CurrentThreadWorkingDirectory` and `MakeFullPathFromThreadWorkingDirectory` that were incorrectly added here. Shared files are compiled into multiple binaries, creating separate static fields — the canonical `AsyncLocal` lives in `FrameworkFileUtilities`.

### `src/Build.UnitTests/Evaluation/Expander_Tests.cs`
- 30 unit tests covering File methods, Directory methods, extended methods (`MSBUILDENABLEALLPROPERTYFUNCTIONS=1`), absolute path passthrough, multi-path methods (Copy, Move), parent traversal, and regular (non-mt) mode.
- Wired `ITestOutputHelper` to all `TestEnvironment.Create(_output)` calls per repo conventions.
- `FileGetAttributes` test marked `[WindowsOnlyFact]` (`Archive` attribute is Windows-specific).

## Design Notes

- `Path.GetFullPath` was already handled for -mt mode in `WellKnownFunctions.cs` — this PR extends the same pattern to all `File`/`Directory` property functions.
- The guard `string.IsNullOrEmpty(CurrentThreadWorkingDirectory)` ensures zero cost in multiprocess mode (one AsyncLocal read + null check -> return null -> skip).
- Item functions share the same `Function.Execute()` codepath, so they are covered automatically.

Fixes #13237

### CODE REVIEW

File: src/Shared/FileUtilities.cs [hunk 1]
```diff
@@ -48,6 +48,84 @@ internal static partial class FileUtilities
...
         internal static string cacheDirectory = null;
 
+#if !CLR2COMPATIBILITY
+        /// <summary>
+        /// AsyncLocal working directory for use during property/item expansion in multithreaded mode.
+        /// Set by MultiThreadedTaskEnvironmentDriver when building projects. null in multiprocess mode.
+        /// Using AsyncLocal ensures the value flows to child threads/tasks spawned during execution of tasks.
+        /// </summary>
+        private static readonly AsyncLocal<string> s_currentThreadWorkingDirectory = new();
+        internal static string CurrentThreadWorkingDirectory
```
Comment (DustinCampbell) [inline src/Shared/FileUtilities.cs]: ❗ Please do not add this to `src/Shared/FileUtilities.cs`. This. property was moved to `FrameworkFileUtilities` so the state is shared across all MSBuild binaries.

https://github.com/dotnet/msbuild/blob/6a4c26f403d07cadd207d027005e7f5f74fd3830/src/Framework/FileUtilities.cs#L30-L43

Shared state shouldn't be added to `src/Shared/FileUtilities.cs` since that file is compiled into several binaries.

File: src/Shared/FileUtilities.cs [hunk 2]
```diff
@@ -48,6 +48,84 @@ internal static partial class FileUtilities
...
+        /// normalized to forward slashes.
+        /// </para>
+        /// <para>
+        /// NormalizePath (which uses Path.GetFullPath) can throw for inputs with illegal path characters
+        /// (e.g., wildcards). In that case we fall back to a simple Path.Combine, which preserves the
+        /// non-throwing behavior of APIs like File.Exists and Directory.Exists.
+        /// </para>
+        /// </remarks>
+#if !CLR2COMPATIBILITY
+        internal static AbsolutePath? MakeFullPathFromThreadWorkingDirectory(string path)
```
Comment (DustinCampbell) [inline src/Shared/FileUtilities.cs]: Why is this added here instead of in `FrameworkFileUtilities` (i.e. `src/Framework/FileUtilities.cs`) with other helper methods that expose `AbsolutePath`?

File: src/Shared/FileUtilities.cs [hunk 3]
```diff
@@ -48,6 +48,84 @@ internal static partial class FileUtilities
         /// </summary>
         internal static string cacheDirectory = null;
 
+#if !CLR2COMPATIBILITY
```
Comment (DustinCampbell) [inline src/Shared/FileUtilities.cs]: `#if` directives for `CLRCOMPATIBILITY` are no longer needed. `src/Shared/FileUtilities.cs` is no longer compiled into `MSBuildTaskHost`.

File: src/Framework/FileUtilities.cs [hunk 4]
```diff
@@ -228,6 +228,53 @@ internal static AbsolutePath FixFilePath(AbsolutePath path)
...
+            }
+
+            // Use the 2-argument GetFullPath overload — it correctly handles drive-relative
+            // ("\foo") and current-directory-relative ("C:foo") paths on Windows by resolving
+            // them against the specified base directory, not the process CWD.
+            try
+            {
+                return new AbsolutePath(Path.GetFullPath(path, workingDir!));
+            }
+            catch (System.Exception ex) when (ex is System.ArgumentException or System.NotSupportedException or System.IO.PathTooLongException)
```
Comment (DustinCampbell) [inline src/Framework/FileUtilities.cs]: Consider adding using directives for `System` and `System.IO` rather than fully qualifying each exception type. Note that this require removing `using System.IO;` from the `#else` block in the usings at the top of the file.

File: src/Build/Evaluation/Expander.cs [hunk 5]
```diff
@@ -3940,6 +3945,39 @@ internal static Function<T> ExtractPropertyFunction(
...
+                }
+
+                // Second argument is a destination path for Copy, Move, Replace.
+                // CreateSymbolicLink is intentionally excluded — its arg1 (pathToTarget) is the
+                // symlink target and relative values are semantically meaningful (stored as-is).
+                if (argIndex == 1)
+                {
+                    return string.Equals(methodName, "Copy", StringComparison.OrdinalIgnoreCase)
+                        || string.Equals(methodName, "Move", StringComparison.OrdinalIgnoreCase)
+                        || string.Equals(methodName, "Replace", StringComparison.OrdinalIgnoreCase);
```
Comment (rainersigwald) [inline src/Build/Evaluation/Expander.cs:3968]: nit: Consider using a `FrozenSet` here to get optimized lookups (but 3 string comparisons is not expensive)

File: src/Build/Evaluation/Expander.cs [hunk 6]
```diff
@@ -3940,6 +3945,39 @@ internal static Function<T> ExtractPropertyFunction(
                 return functionBuilder.Build();
             }
 
+            /// <summary>
+            /// Determines whether the argument at <paramref name="argIndex"/> for a System.IO.File
+            /// or System.IO.Directory method is a file/directory path that should be resolved
+            /// against the thread-local working directory.
+            /// </summary>
+            [MethodImpl(MethodImplOptions.AggressiveInlining)]
```
Comment (rainersigwald) [inline src/Build/Evaluation/Expander.cs]: Nit: the runtime is usually pretty good about making its own inlining decisions and this method isn't trivial, so I'm a bit skeptical about `AggressiveInlining` being right. What did you do to validate?

File: src/Build/Evaluation/Expander.cs (hunk 5 above)
Comment (JanProvaznik) [reply src/Build/Evaluation/Expander.cs:3968]: this could go either way, frozen set has high init cost
