### PR TITLE
Fix missed build data on BuildRequestDataFlags provided

### LINKED ISSUE #9458: [Bug]: ResultsCache ignores some of the BuildRequest data, may return incorrect results
### Issue Description

`ResultsCache` ignores `BuildRequestDataFlags.ProvideProjectStateAfterBuild` and `RequestedProjectState`, which may lead to incorrect over-sharing and returning incomplete results. `BuildResult.ProjectStateAfterBuild` is used by design-time builds in Visual Studio where this issue was discovered.

### Steps to Reproduce

The repro is provided as a private MSBuildLocator branch:
https://github.com/microsoft/MSBuildLocator/compare/main...ladipro:MSBuildLocator:results-cache-bug

Build and run the BuilderApp project to reproduce.

### Expected Behavior

Build succeeds.

### Actual Behavior

Build fails because the second submission returns null `ProjectStateAfterBuild` despite having constructed the build request with `BuildRequestDataFlags.ProvideProjectStateAfterBuild`.

### Analysis

The two build requests appear to be treated as identical by the results cache. The cached results of the first build request are returned when the second build request is submitted.

### Versions & Configurations

Visual Studio 17.9.34322.171

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes #9458

### Context
The two build requests appear to be treated as identical by the results cache even when different BuildRequestDataFlags were provided .

### Changes Made
Before returning cache results, check the cached BuildRequestDataFlags for the previous BuildResult. 

### Testing
Manual + UT

### CODE REVIEW

File: src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs [hunk 1]
```diff
@@ -331,7 +331,10 @@ public void SubmitBuildRequest(BuildRequest request)
                         // Grab the results from the requested configuration
                         IResultsCache cache = (IResultsCache)_componentHost.GetComponent(BuildComponentType.ResultsCache);
                         BuildResult result = cache.GetResultsForConfiguration(request.ConfigurationId);
-                        BuildResult resultToReport = new BuildResult(request, result, null);
+                        BuildResult resultToReport = new BuildResult(request, result, null)
+                        {
+                            BuildRequestDataFlags = request.BuildRequestDataFlags,
```
Comment (Forgind) [inline src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs:336]: This seems like something that should be set in the constructor, not manually here.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs [hunk 2]
```diff
@@ -163,15 +163,15 @@ public ResultsCacheResponse SatisfyRequest(BuildRequest request, List<string> co
                 if (_resultsByConfiguration.TryGetValue(request.ConfigurationId, out BuildResult allResults))
                 {
                     // Check for targets explicitly specified.
-                    bool explicitTargetsSatisfied = CheckResults(allResults, request.Targets, response.ExplicitTargetsToBuild, skippedResultsDoNotCauseCacheMiss);
+                    bool explicitTargetsSatisfied = CheckResults(request.BuildRequestDataFlags, allResults, request.Targets, response.ExplicitTargetsToBuild, skippedResultsDoNotCauseCacheMiss);
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Caching/ResultsCache.cs:166]: This check (along with the other two you changed) are specific to targets; I don't think it makes sense to check BuildRequestDataFlags here as well. I'd have a separate check either above or below this if block for that.

**Review by Forgind — COMMENTED** [review]
This seems like it should work, but it's also a big more aggressive than I think is necessary. Specifically, BuildRequestDataFlags have a number of options, some of which seem like they'd make it invalid to use the same result for another project but some of which seem like they wouldn't affect the result. Can we be more precise in this comparison than just a straight comparison?

**Review by ladipro — CHANGES_REQUESTED** [review]
I agree with @Forgind's comments.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs (hunk 2 above)
Comment (YuliiaKovalova) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs]: @ladipro , I put it in CheckResults method because I wanted to report it as a part of [targetsMissingResults](https://github.com/dotnet/msbuild/blob/995ca63dbd7104208e33a6ff8dffacab5daa44d2/src/Build/BackEnd/Components/Caching/ResultsCache.cs#L312)
Do I need to track it in my separate method?

File: src/Build/BackEnd/Shared/BuildResult.cs [hunk 3]
```diff
@@ -380,6 +381,12 @@ public ProjectInstance ProjectStateAfterBuild
             set => _projectStateAfterBuild = value;
         }
 
+        /// <summary>
+        /// Gets or sets the flags that provide additional control over the build request.
+        /// See <see cref="Execution.BuildRequestDataFlags"/> for examples of the available flags.
+        /// </summary>
+        public BuildRequestDataFlags BuildRequestDataFlags { get; }
```
Comment (ladipro) [inline src/Build/BackEnd/Shared/BuildResult.cs:388]: This will need to have an explicit field and the field should be handled in the `Translate` method.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs [hunk 4]
```diff
@@ -332,6 +333,15 @@ private static bool CheckResults(BuildResult result, List<string> targets, HashS
...
         }
 
+        /// <summary>
+        /// Checks results for the specified build flags.
+        /// </summary>
+        /// <param name="buildRequestDataFlags">The current request build flags.</param>
+        /// <param name="buildResultDataFlags">The existing build result data flags.</param>
+        /// <returns>False if there is any difference in the data flags that can cause missed build data, true otherwise.</returns>
+        private static bool CheckBuildDataFlagsResults(BuildRequestDataFlags buildRequestDataFlags, BuildRequestDataFlags buildResultDataFlags) =>
+            buildRequestDataFlags != BuildRequestDataFlags.ProvideProjectStateAfterBuild || buildResultDataFlags == buildRequestDataFlags;
```
Comment (ladipro) [inline src/Build/BackEnd/Components/Caching/ResultsCache.cs:343]: `BuildRequestDataFlags` are flags so this should look something like

```suggestion
            buildRequestDataFlags.HasFlag(BuildRequestDataFlags.ProvideProjectStateAfterBuild) == buildResultDataFlags.HasFLag(BuildRequestDataFlags.ProvideProjectStateAfterBuild);
```

but we will probably want to test for more flags, basically everything that can affect the results.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs [hunk 5]
```diff
@@ -164,8 +164,9 @@ public ResultsCacheResponse SatisfyRequest(BuildRequest request, List<string> co
                 {
                     // Check for targets explicitly specified.
                     bool explicitTargetsSatisfied = CheckResults(allResults, request.Targets, response.ExplicitTargetsToBuild, skippedResultsDoNotCauseCacheMiss);
+                    bool buildDataFlagsSatisfied = CheckBuildDataFlagsResults(request.BuildRequestDataFlags, allResults.BuildRequestDataFlags);
 
-                    if (explicitTargetsSatisfied)
+                    if (explicitTargetsSatisfied && buildDataFlagsSatisfied)
```
Comment (ladipro) [inline src/Build/BackEnd/Components/Caching/ResultsCache.cs:169]: nit: This should be added to the method comment about ~20 lines up.

**Review by ladipro — CHANGES_REQUESTED** [review]
I've left a few comments inline. I think we need to split `BuildRequestDataFlags` into those that affect the result and those that don't to make the right check in `CheckBuildDataFlagsResults`.

Also, please take a look at `ProvideSubsetOfStateAfterBuild`. This is similar to `ProvideProjectStateAfterBuild` but the returned state goes through a user-specified filter. If the filtered `ProjectInstance` is stored in the cache, we will likely need to use the filter (as defined in `RequestedProjectState`) as an additional cache key.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs (hunk 2 above)
Comment (ladipro) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs]: [targetsMissingResults](https://github.com/dotnet/msbuild/blob/995ca63dbd7104208e33a6ff8dffacab5daa44d2/src/Build/BackEnd/Components/Caching/ResultsCache.cs#L312) is unused and should be possible to eliminate together with `ExplicitTargetsToBuild`.

I think it makes sense to check the flags first and only if they match proceed to checking targets, just as a tiny perf optimization.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs (hunk 4 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs:343]: @ladipro I believe the logic is that every flag other than `ProvideProjectStateAfterBuild` is considering as possible to affect results. 
However, by looking at existing flags, please consider it we shall test for `ProvideSubsetOfStateAfterBuild` as well. I mean only when both flags are not set we can consider this request cache satisfied as no results.
I am not sure if I understand it correctly, but to me check can be 
```C#
(!buildRequestDataFlags.HasFlag(BuildRequestDataFlags.ProvideProjectStateAfterBuild)  && 
 !buildRequestDataFlags.HasFlag(BuildRequestDataFlags.ProvideSubsetOfStateAfterBuild)) 
||
(buildResultDataFlags & 
 ~BuildRequestDataFlags.ProvideProjectStateAfterBuild  & 
 ~BuildRequestDataFlags.ProvideSubsetOfStateAfterBuild)  == 
(buildRequestDataFlags & 
 ~BuildRequestDataFlags.ProvideProjectStateAfterBuild & 
 ~BuildRequestDataFlags.ProvideSubsetOfStateAfterBuild)
 ```
 So changes in `Provide*StateAfterBuild` are ignored as those do not affect result.
 Additionally if no project or subset of project is going to be reported we can satisfy it by cache, but I do not understand this particular logic, as other changes in build request could affect resulting build artifacts or overall build success/failure (for example `IgnoreMissingEmptyAndInvalidImports` flag).

**Review by rokonec — APPROVED** [review]
Had not found other defects than Ladi review.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs (hunk 4 above)
Comment (YuliiaKovalova) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs]: @rainersigwald , are you aware of any other flags that we have to respect before extracting cache results?

File: src/Build/BackEnd/Shared/BuildResult.cs [hunk 6]
```diff
@@ -116,6 +116,8 @@ public class BuildResult : INodePacket, IBuildResults
         /// </summary>
         private ProjectInstance _projectStateAfterBuild;
 
+        private BuildRequestDataFlags _buildRequestDataFlags;
```
Comment (ladipro) [inline src/Build/BackEnd/Shared/BuildResult.cs:119]: Please don't forget adding `translator.TranslateEnum(ref _buildRequestDataFlags, (int)_buildRequestDataFlags)` to the `Translate` method.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs (hunk 4 above)
Comment (ladipro) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs]: > @ladipro I believe the logic is that every flag other than ProvideProjectStateAfterBuild is considering as possible to affect results.

`ClearCachesAfterBuild` looks like an example of a "meta flag" which does not affect the results.

`ProvideSubsetOfStateAfterBuild` will likely need a slightly more sophisticated handling. Note that we never check for this flag in product code. We instead use non-null `RequestedProjectState` as the indicator that `ProjectStateAfterBuild` should be set. https://github.com/dotnet/msbuild/blob/5d7f5723223b823c9ed62ad52cc04e4c17a5848b/src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs#L190-L200

Comment (YuliiaKovalova) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs]: > > @ladipro I believe the logic is that every flag other than ProvideProjectStateAfterBuild is considering as possible to affect results.
> 
> `ClearCachesAfterBuild` looks like an example of a "meta flag" which does not affect the results.
> 
> `ProvideSubsetOfStateAfterBuild` will likely need a slightly more sophisticated handling. Note that we never check for this flag in product code. We instead use non-null `RequestedProjectState` as the indicator that `ProjectStateAfterBuild` should be set.
> 
> https://github.com/dotnet/msbuild/blob/5d7f5723223b823c9ed62ad52cc04e4c17a5848b/src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs#L190-L200

Ladi, I made an attempt to add this flag explicitly if RequestedProjectState is passed. 
Is it wrong?

Comment (ladipro) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs]: It looks reasonable. Requiring API users to set this flag would be a breaking change so we can at least make the data consistent internally.

However, I'm not sure if this is enough to handle `ProvideSubsetOfStateAfterBuild` properly. If one build request asks for a certain subset of state and then another one for a different subset, then they both have the flag set but the expected build results are not the same and the cached entry should not be used.

Comment (YuliiaKovalova) [reply src/Build/BackEnd/Components/Caching/ResultsCache.cs]: done

File: src/Build/BackEnd/Shared/BuildResult.cs [hunk 7]
```diff
@@ -380,6 +383,16 @@ public ProjectInstance ProjectStateAfterBuild
...
         }
 
+        /// <summary>
+        /// Gets or sets the flags that provide additional control over the build request.
+        /// See <see cref="Execution.BuildRequestDataFlags"/> for examples of the available flags.
+        /// </summary>
+        public BuildRequestDataFlags BuildRequestDataFlags
+        {
+            get => _buildRequestDataFlags;
+            set => _buildRequestDataFlags = value;
```
Comment (ladipro) [inline src/Build/BackEnd/Shared/BuildResult.cs:393]: nit: Do we need the setter?

File: src/Build/BackEnd/Shared/BuildResult.cs (hunk 6 above)
Comment (ladipro) [inline src/Build/BackEnd/Shared/BuildResult.cs:119]: nit: Can you please add a comment explaining what this field represents?

File: src/Build/BackEnd/Shared/BuildResult.cs [hunk 8]
```diff
@@ -380,6 +383,16 @@ public ProjectInstance ProjectStateAfterBuild
             set => _projectStateAfterBuild = value;
         }
 
+        /// <summary>
+        /// Gets or sets the flags that provide additional control over the build request.
```
Comment (ladipro) [inline src/Build/BackEnd/Shared/BuildResult.cs:387]: nit:

```suggestion
        /// Gets the flags that were used in the build request to which these results are associated.
```

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs [hunk 9]
```diff
@@ -17,6 +18,11 @@ namespace Microsoft.Build.BackEnd
     /// </summary>
     internal class ResultsCache : IResultsCache
     {
+        /// <summary>
+        /// The presence of any of these flags affects build result for the specified request.
+        /// </summary>
+        private readonly BuildRequestDataFlags _flagsAffectingBuildResults = BuildRequestDataFlags.ProvideProjectStateAfterBuild;
```
Comment (ladipro) [inline src/Build/BackEnd/Components/Caching/ResultsCache.cs:24]: nit: Can be `static` or even `const`.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs [hunk 10]
```diff
@@ -332,6 +340,20 @@ private static bool CheckResults(BuildResult result, List<string> targets, HashS
             return returnValue;
         }
 
+        /// <summary>
+        /// Checks results for the specified build flags.
+        /// </summary>
+        /// <param name="buildRequestDataFlags">The current request build flags.</param>
+        /// <param name="buildResultDataFlags">The existing build result data flags.</param>
+        /// <returns>False if there is any difference in the data flags that can cause missed build data, true otherwise.</returns>
+        private bool CheckBuildDataFlagsResults(BuildRequestDataFlags buildRequestDataFlags, BuildRequestDataFlags buildResultDataFlags) =>
```
Comment (ladipro) [inline src/Build/BackEnd/Components/Caching/ResultsCache.cs:349]: nit: Method can be `static` if the field is changed to static or const.

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs [hunk 11]
```diff
@@ -332,6 +340,20 @@ private static bool CheckResults(BuildResult result, List<string> targets, HashS
...
+
+            // Even if both buildRequestDataFlags and buildResultDataFlags have ProvideSubsetOfStateAfterBuild flag,
+            // the underlying RequestedProjectState may have different user filters defined.
+            // It is more reliable to ignore the cached value. 
+            !buildRequestDataFlags.HasFlag(BuildRequestDataFlags.ProvideSubsetOfStateAfterBuild)
+            & (buildRequestDataFlags & _flagsAffectingBuildResults) == (buildResultDataFlags & _flagsAffectingBuildResults);
```
Comment (ladipro) [inline src/Build/BackEnd/Components/Caching/ResultsCache.cs:355]: nit: Is the bitwise `&` intentional? Not incorrect but somewhat unusual.

```suggestion
            && (buildRequestDataFlags & _flagsAffectingBuildResults) == (buildResultDataFlags & _flagsAffectingBuildResults);
```

**Review by ladipro — COMMENTED** [review]
I've added a few minor comments. Please add an entry to the [ChangeWave document](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/ChangeWaves.md).

File: src/Build/BackEnd/Components/Caching/ResultsCache.cs [hunk 12]
```diff
@@ -17,6 +18,11 @@ namespace Microsoft.Build.BackEnd
     /// </summary>
     internal class ResultsCache : IResultsCache
     {
+        /// <summary>
+        /// The presence of any of these flags affects build result for the specified request.
+        /// </summary>
+        private const BuildRequestDataFlags FlagsAffectingBuildResults = BuildRequestDataFlags.ProvideProjectStateAfterBuild;
```
Comment (ladipro) [inline src/Build/BackEnd/Components/Caching/ResultsCache.cs:24]: `SkipNonexistentTargets`
`IgnoreMissingEmptyAndInvalidImports`
`FailOnUnresolvedSdk`

also look like flags affecting the build result. Since the check is now behind a changewave, giving us a bit of extra safety, I would consider adding them here.

**Review by ladipro — APPROVED** [review]
