### PR TITLE
Send AssemblyLoadBuildEventArgs only for valid LoggingContext

### LINKED ISSUE #8816: AssemblyLoadsTracker should only turn on for msbuild.exe and dotnet build
When hosting MSBuild inside a .NET desktop application, we saw this exception:

```
Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: must be valid
   at void Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(string message, Exception innerException, params object[] args)
   at void Microsoft.Build.BackEnd.Logging.LoggingContext.LogBuildEvent(BuildEventArgs buildEvent)
   at void Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(object sender, AssemblyLoadEventArgs args)
   at void AssemblyLoadEventHandler.Invoke(object sender, AssemblyLoadEventArgs args)
   at void AppDomain.OnAssemblyLoadEvent(RuntimeAssembly LoadedAssembly)
   at RuntimeAssembly System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, string codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, ref StackCrawlMark stackMark, IntPtr pPrivHostBinder, bool throwOnFileNotFound, bool forIntrospection, bool suppressSecurityChecks)
   at RuntimeAssembly System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, string codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, ref StackCrawlMark stackMark, IntPtr pPrivHostBinder, bool throwOnFileNotFound, bool forIntrospection, bool suppressSecurityChecks)
   at RuntimeAssembly System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, ref StackCrawlMark stackMark, IntPtr pPrivHostBinder, bool throwOnFileNotFound, bool forIntrospection, bool suppressSecurityChecks)
   at Assembly System.Reflection.Assembly.Load(AssemblyName assemblyRef)
```

Our guess is that since our app hosts MSBuild, the AssemblyLoadsTracker is installed. 

It should probably only get activated when it detects that it's running in msbuild.exe or dotnet.exe. We probably don't want this functionality when running inside third-party apps hosting MSBuild (for example Visual Studio!). Since VS can load a ton of third-party assemblies too.

### PR DESCRIPTION
**Pull request by rokonec**
Fixes #8816

### Context
As discussed in #8816 we are trying the simplest solution, i.e. do not fail when LoggingContext is not yet properly initialized.

### Changes Made
Simple IF

### Testing
Local.

### Notes
@KirillOsenkov Can you please test if this PR addresses #8816 issue properly?

### CODE REVIEW

**Review by JanKrivanek — APPROVED** [review]
Simple and effective - thanks!

File: src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs [hunk 1]
```diff
@@ -157,11 +157,14 @@ private void CurrentDomainOnAssemblyLoad(object? sender, AssemblyLoadEventArgs a
...
+            // Fix #8816 - when LoggingContext does not have BuildEventContext it is unable to log anything
+            if (_loggingContext?.BuildEventContext != null)
             {
-                BuildEventContext = _loggingContext?.BuildEventContext ?? BuildEventContext.Invalid
-            };
-            _loggingContext?.LogBuildEvent(buildArgs);
+                buildArgs.BuildEventContext = _loggingContext.BuildEventContext;
+                _loggingContext.LogBuildEvent(buildArgs);
+            }
             _loggingService?.LogBuildEvent(buildArgs);
```
Comment (KirillOsenkov) [inline src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs:168]: do you need to remove this line now?

Comment (rokonec) [reply src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs:168]: It has not been removed, only moved to `if` at line 166

Comment (KirillOsenkov) [reply src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs:168]: so, do we need both LoggingContext.LogBuildEvent() as well as LoggingService.LogBuildEvent()? sorry I don't know what exactly these two methods do and what is the difference.

Comment (rokonec) [reply src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs:168]: Only one of those is set. If we have LoggingContext than we use it, in cases where LoggingContext is unknown, for example logger intialization, we do use LoggingService instead.

**Review by KirillOsenkov — APPROVED** [review]
