### PR TITLE
Change Copy task LogDiagnostics Warning so it is suppressible

### LINKED ISSUE #9210: [Bug]: Copy.DoCopyWithRetries logs warnings without a diagnostic code
### Issue Description

See #9190 CI builds frequently fail with MSB3021: Access to the path xxx.dll is denied

I'm using the secret MSBUILDALWAYSRETRY environmental variable to mitigate lots of Copy conflicts that unexpectedly started occurring last month.

However, when this retry happens, a warning is logged without a diagnostic code.
This means that I cannot exclude this warning in our "strict" build that treats warnings as errors:
https://github.com/dotnet/msbuild/blob/971bf70db73ebd5d5e1dde5eb27b8265be9f3169/src/Tasks/Copy.cs#L817

I'm currently giving these arguments to MSBuild:
`/WarnAsError /nowarn:"MSB3270;MSB3026;MSB3021" /maxcpucount:1`
I'd like to add "LogDiagnostic" warnings to the `/nowarn` list, but without a diagnostic code, I cannot see how to do so.

We are building to a single directory, so nuget packages that are referenced by multiple projects tend to get written multiple times. But even building single threaded, I cannot seem to avoid conflicts. 

```
Microsoft.Common.CurrentVersion.targets(5167,5): error : Got System.IO.IOException: The process cannot access the file 'F:\build\bin\AnyCPU\Release\net472\libcef.dll' because it is being used by another process.
Microsoft.Common.CurrentVersion.targets(5167,5): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
Microsoft.Common.CurrentVersion.targets(5167,5): error :    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
Microsoft.Common.CurrentVersion.targets(5167,5): error :    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
Microsoft.Common.CurrentVersion.targets(5167,5): error :    at Microsoft.Build.Tasks.Copy.CopyFileWithLogging(FileState sourceFileState, FileState destinationFileState)
Microsoft.Common.CurrentVersion.targets(5167,5): error :    at Microsoft.Build.Tasks.Copy.DoCopyWithRetries(FileState sourceFileState, FileState destinationFileState, CopyFileWithState copyFile) copying d:\Nuget\packages\cef.redist.x64\103.0.9\CEF\libcef.dll to F:\build\bin\AnyCPU\Release\net472\libcef.dll and HR is -2147024864
```

### Steps to Reproduce

Unable to provide steps to reproduce, as I don't know what changed in our build environment (around the 10th August) that causes so many Copy File conflicts.

### Expected Behavior

Ideally, warnings should include a diagnostic code.

### Actual Behavior

Warning does not currently include a diagnostic code.

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by rokonec**
Fixes #9210 

### Context
Copy task implement `LogDiagnostics` as warnings. This is causing issues for `/WarnAsError` use cases.

### Changes Made
Change Copy task `LogDiagnostics` from Warning to low importance Message.
``` C#
/// <summary>
/// If MSBUILDALWAYSRETRY is set, also log useful diagnostic information -- as 
/// a warning, so it's easily visible. 
/// </summary>
private void LogDiagnostic(string message, params object[] messageArgs)
{
    if (s_alwaysRetryCopy)
    {
        Log.LogMessage(MessageImportance.Low, message, messageArgs);
    }
}
```
The reasoning for Warning level "so it's easily visible" is, IMO, not strong enough.

### Testing
Unit tests.
Locally.

### Notes
@rainersigwald  Since we see increasing number of people reporting issues with Copy conflicts, I believe it is candidate for 17.8

### CODE REVIEW

File: src/Tasks/Copy.cs [hunk 1]
```diff
@@ -215,7 +215,7 @@ private void LogDiagnostic(string message, params object[] messageArgs)
         {
             if (s_alwaysRetryCopy)
             {
-                Log.LogWarning(message, messageArgs);
+                Log.LogMessage(MessageImportance.Low, message, messageArgs);
```
Comment (JanKrivanek) [inline src/Tasks/Copy.cs:218]: Pls adjust or remove the comment - as now it's out of sync with actual code.

Btw. can a `MessageImportance.High` be a better way to satisfy the need for visibility? Low importance message would not be sent to common loggers (Output windw, console) and hence it can confuse users that were used to see it there in case of problems.

**Review by JanKrivanek — APPROVED** [review]
Please remove/alter the existing comment (it's confusing now) - than I'm OK with change. As soon as the `MessageImportance.High` was considered and there are reasons not to use it.

File: src/Tasks/Copy.cs (hunk 1 above)
Comment (rokonec) [reply src/Tasks/Copy.cs:218]: I am questioning the need for visibility. I don't think it has a value for people. They just need this file to be copied to destination.

Comment (JanKrivanek) [reply src/Tasks/Copy.cs:218]: I do not have opinion here :-)
Sounds like you thought a bit about that - so I'm fine with your conclusion.
Let's remove the comment then.

Comment (baronfel) [reply src/Tasks/Copy.cs:218]: Low seems a reasonable default here - it will appear in binlogs and other locations, but not in a 'normal' `dotnet build` scenario.

Comment (rainersigwald) [reply src/Tasks/Copy.cs:218]: I am less sure about that. There are cases where copies need retries to work around infrastructure flakiness (copying to a network release share, for instance), but often retries are indicative of a bug in your build (overbuilding or racing to a file write). "Warning" seems like a pretty reasonable place to me (though I can empathize with wanting the warning to be suppressible).

Comment (rokonec) [reply src/Tasks/Copy.cs:217]: Now I have conflicting opinions from two most respected authorities in msbuild. I am fine with either, this is pros and cons:

a) low warning (as is ATM)
- pros: 
  - simple implementation
  - people would not see non translated slightly cryptic messages "Got {0} copying {1} to {2} and HR is {3}"
- cons: 
  -- might hide infrastructure flaky issues and/or bug in project or sln files causing these flakiness (mostly race conditions or redundant multi copies)

b) warnings (as was), but translated and suppressible. 
- pros: 
  - less probability of regression (it was this way for ages)
  - more visibly pointing on infrastructure flakiness or project files bugs
- cons: 
  - if we have some system problem which is causing those copy issues, people will have it more difficult to workaround it (MSBUILDALWAYSRETRY + nowarn:MSBXXXX)
  - when MSBUILDALWAYSRETRY and /WarnAsError infrastructure flakiness cascade into build flakiness

@baronfel  @rainersigwald please advise...

Comment (baronfel) [reply src/Tasks/Copy.cs:217]: I'm happy to keep warnings _as long as they get a code_ - we basically should never make a warning-level message without a suppressible code.

**Comment by rokonec** [comment]
Not closed actually, but hard reset + force push have confused github

File: src/Tasks/Copy.cs (hunk 1 above)
Comment (rokonec) [reply src/Tasks/Copy.cs]: Reworked into warnings. Ready for review

File: src/Tasks/Resources/Strings.resx [hunk 2]
```diff
@@ -2781,6 +2781,14 @@
...
     <comment>{StrBegin="MSB3893: "} LOCALIZATION: {0} and {1} are paths.</comment>
   </data>
+  <data name="Copy.IOException">
+    <value>MSB3094: "Got {0} copying {1} to {2} and HR is {3}"</value>
+    <comment>{StrBegin="MSB3094: "} LOCALIZATION: {0} is exception.ToString(), {1} and {2} are paths, {3} is a number")</comment>
+  </data>
+  <data name="Copy.RetryingOnAccessDenied">
+    <value>"MSB3095: Retrying on ERROR_ACCESS_DENIED because environment variable MSBUILDALWAYSRETRY = 1"</value>
+    <comment>{StrBegin="MSB3095: "} LOCALIZATION: Do NOT translate MSBUILDALWAYSRETRY")</comment>
+  </data>
```
Comment (JanKrivanek) [inline src/Tasks/Resources/Strings.resx:2791]: Codes seem to be taken already: https://github.com/search?q=repo%3Adotnet%2Fmsbuild+MSB3094+MSB3095&type=code

**Review by JanKrivanek — CHANGES_REQUESTED** [review]
Looks good!

We just need to pick unique error codes

File: src/Tasks/Resources/Strings.resx (hunk 2 above)
Comment (rokonec) [reply src/Tasks/Resources/Strings.resx:2791]: Good catch. TLDR: Should have used glasses when coding at night. Mistaken 0 and 8, with my font they are similar:
image
Fixed.

**Review by JanKrivanek — APPROVED** [review]

**Review by rainersigwald — APPROVED** [review]
