### PR TITLE
Optionally output unresolved assembly conflicts

### LINKED ISSUE #5934: Support generating errors for unresolved assembly conflicts from ResolveAssemblyReference
The Windows CSWinRT API targeting packs are going to be updating regularly.  This means that libraries compiled with newer versions of the .NET SDK will have an assembly reference to higher versions of Microsoft.Windows.SDK.NET.dll.  If a project that is using an older version of the .NET SDK consumes an updated library (ie via a NuGet package), then there will be an MSB3277 warning from ResolveAssemblyReferences, and a FileLoadException at runtime.  (Depending on how types are shared, the build may also fail with a CS1705 compiler error.)

It would be better if an error would be consistently generated at build time that would be more helpful about what the problem is and how to resolve it (usually updating to a newer .NET SDK).

A way to support this could be to update the ResolveAssemblyReference task to optionally generate output items that describe the unresolved assembly conflicts.  The .NET SDK would check for any such conflicts for the appropriate DLL and generate an appropriate error message.

Related links:

- https://github.com/microsoft/CsWinRT/issues/521
- https://github.com/microsoft/CsWinRT/blob/master/docs/versioning.md#scenarios

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #5934.

@dsplaisted, does this look how you expected?

### CODE REVIEW

**Comment by dsplaisted** [comment]
The additional parameter / output to the task look like what we need.  The common targets would also need to be updated to use those when calling the ResolveAssemblyReference task.

For the implementation, it should do the following.  I wasn't sure but it looked like it wasn't:

- Warnings should still be generated even if OutputUnresolvedAssemblyConflicts is true
- The output items should use the assembly name (possibly with `.dll` on the end, possibly not) as the ItemSpec, not the full log message.  That will allow code to check whether (for example) there is a conflict for the `Microsoft.Windows.SDK.NET.dll` assembly.

Thanks!

**Comment by Forgind** [comment]
Does that look better? The extra information you'd want in metadata is the conflicting versions and how each was (directly or indirectly) referenced?

File: src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs [hunk 1]
```diff
@@ -1001,6 +1020,11 @@ List<Exception> generalResolutionExceptions
                                 Log.LogMessage(ChooseReferenceLoggingImportance(conflictCandidate), StringBuilderCache.GetStringAndRelease(logConflict));
                                 Log.LogMessage(MessageImportance.Low, StringBuilderCache.GetStringAndRelease(logDependencies));
                             }
+
+                            if (OutputUnresolvedAssemblyConflicts)
+                            {
+                                _unresolvedConflicts.Add(new TaskItem(assemblyName.Name));
```
Comment (dsplaisted) [inline src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs:1026]: I would include the log message with the human-readable details in the metadata for this item.

We don't currently have a use case for programmatically processing data such as conflicting version numbers, how the assembly was referenced, etc.  I would say if it's straightforward to include, then go ahead and do so.  But if not, then skip it for now.

File: src/Tasks/Microsoft.Common.CurrentVersion.targets [hunk 2]
```diff
@@ -2233,6 +2235,7 @@ Copyright (C) Microsoft Corporation. All rights reserved.
       <Output TaskParameter="FilesWritten" ItemName="FileWrites"/>
       <Output TaskParameter="DependsOnSystemRuntime" PropertyName="DependsOnSystemRuntime"/>
       <Output TaskParameter="DependsOnNETStandard" PropertyName="_DependsOnNETStandard"/>
+      <Output TaskParameter="UnresolvedAssemblyConflicts" ItemName="UnresolvedAssemblyConflicts"/>
```
Comment (dsplaisted) [inline src/Tasks/Microsoft.Common.CurrentVersion.targets:2238]: We might want to use a name that's more likely to be unique.  Similar to the pattern for the input property, that could be `ResolveAssemblyReferenceUnresolvedAssemblyConflicts`.

**Review by dsplaisted — COMMENTED** [review]
This looks like what we wanted, as far as I can tell.

File: src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs (hunk 1 above)
Comment (Forgind) [reply src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs]: Conflicting version numbers is easy, so I included that. How it's referenced is doable, but it's a little verbose, since there could be multiple levels of dependencies (A depends on B depends on C depends on D depends on the conflicting dll). I can add it later if we decide we need it, though.

File: src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs [hunk 3]
```diff
@@ -990,16 +1009,36 @@ List<Exception> generalResolutionExceptions
                             // Log the reference which lost the conflict and the dependencies and source items which caused it.
                             LogReferenceDependenciesAndSourceItemsToStringBuilder(fusionName, conflictCandidate, logDependencies.AppendLine());
 
+                            string toOutput;
```
Comment (ladipro) [inline src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs:1012]:
```suggestion
                            string toOutput = StringBuilderCache.GetStringAndRelease(logConflict);
```

Both `if` and `else` do this as their first statement.

File: src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs [hunk 4]
```diff
@@ -915,6 +922,18 @@ public String DependsOnNETStandard
...
+        /// If OutputUnresolvedAssemblyConflicts then a list of information about unresolved conflicts that normally would have
+        /// been outputted in MSB3277. Otherwise empty.
+        /// </summary>
+        [Output]
+        public ITaskItem[] UnresolvedAssemblyConflicts {
+            get
+            {
+                return _unresolvedConflicts.ToArray();
+            }
+            }
```
Comment (ladipro) [inline src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs:935]: nit:

```suggestion
        public ITaskItem[] UnresolvedAssemblyConflicts => _unresolvedConflicts.ToArray();
```

File: src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs [hunk 5]
```diff
@@ -990,16 +1009,36 @@ List<Exception> generalResolutionExceptions
...
+                                }
+                            }
+
+                            if (OutputUnresolvedAssemblyConflicts)
+                            {
+                                _unresolvedConflicts.Add(new TaskItem(assemblyName.Name, new Dictionary<string, string>()
+                                {
+                                    { "logMessage", toOutput },
+                                    {"victorVersionNumber", victor.ReferenceVersion.ToString() },
+                                    {"victimVersionNumber", conflictCandidate.ReferenceVersion.ToString() }
```
Comment (ladipro) [inline src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs:1040]: super-nit: Missing space after `{`.

File: src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs [hunk 6]
```diff
@@ -990,16 +1009,36 @@ List<Exception> generalResolutionExceptions
...
-                                Log.LogMessage(MessageImportance.Low, StringBuilderCache.GetStringAndRelease(logDependencies));
+                                toOutput = StringBuilderCache.GetStringAndRelease(logConflict);
+                                string extra = StringBuilderCache.GetStringAndRelease(logDependencies);
+                                Log.LogMessage(ChooseReferenceLoggingImportance(conflictCandidate), toOutput);
+                                Log.LogMessage(MessageImportance.Low, extra);
+
+                                // This does an extra allocation, so only do it when necessary.
+                                if (OutputUnresolvedAssemblyConflicts)
+                                {
+                                    toOutput += '\n' + extra;
```
Comment (ladipro) [inline src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs:1030]: Why not be more structured add `extra` in its own metadatum? Something like:
```C#
{ "logMessage", toOutput },
{ "logMessageDetails", extra }
```

File: src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs [hunk 7]
```diff
@@ -214,6 +215,12 @@ public bool IgnoreTargetFrameworkAttributeVersionMismatch
         /// </remarks>
         public bool FindDependenciesOfExternallyResolvedReferences { get; set; }
 
+        /// <summary>
+        /// If true, outputs any unresolved assembly conflicts (MSB3277) in UnresolvedAssemblyConflicts
+        /// instead of logging them.
```
Comment (BenVillalobos) [inline src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs:220]: > instead of logging them.

doesn't it do both?

File: src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs [hunk 8]
```diff
@@ -3686,6 +3686,37 @@ public void ConflictGeneratesMessageReferencingAssemblyName()
             warningMessage.ShouldContain(ResourceUtilities.FormatResourceStringIgnoreCodeAndKeyword("ResolveAssemblyReference.FourSpaceIndent", ResourceUtilities.FormatResourceStringIgnoreCodeAndKeyword("ResolveAssemblyReference.ReferenceDependsOn", "D, Version=1.0.0.0, CulTUre=neutral, PublicKeyToken=aaaaaaaaaaaaaaaa", Path.Combine(s_myLibraries_V1Path, "D.dll"))));
         }
 
+        [Fact]
+        public void ConflictOutputsExtraInformationOnDemand()
```
Comment (BenVillalobos) [inline src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs:3690]: Should we make this a theory and test what happens when the item has the `.dll` extension? @dsplaisted is there a concrete answer for including `.dll` in the assembly name? Or did your comment, "possibly with .dll possibly not," refer to the fact that `assemblyName.Name` may not have the extension along with it?

**Review by BenVillalobos — COMMENTED** [review]
LGTM, pending 2 comments.

File: src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs (hunk 7 above)
Comment (Forgind) [reply src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs:220]: Yep! Fixed. That was a holdover from how I'd originally designed it.

File: src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs (hunk 8 above)
Comment (Forgind) [reply src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs:3690]: I understood him to mean that the SDK can handle the output having the .dll extension or not having it—it's the same information, just presented slightly differently. Since I'm creating the item, and I went with no .dll extension, that shouldn't be an issue.

Comment (dsplaisted) [reply src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs:3690]: I wasn't sure whether the assembly name processed by ResolveAssemblyReference would have the .dll extension on it.  If it consistently does not have the extension, then I would leave it out.  It's also theoretically possible to reference an .exe, I believe.

Comment (BenVillalobos) [reply src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs:3690]: The summary behind `assemblyName.Name`:
> Gets or sets the simple name of the assembly. This is usually, but not necessarily,
the file name of the manifest file of the assembly, minus its extension.

Looks like the SDK will have to account for both scenarios, unless there's a preference on how we handle it here. I'm okay with either scenario.

Comment (dsplaisted) [reply src/Tasks.UnitTests/AssemblyDependency/Miscellaneous.cs:3690]: Sounds like MSBuild shouldn't do anything special here then (ie don't add the .dll extension).

**Review by ladipro — APPROVED** [review]

**Review by BenVillalobos — APPROVED** [review]
