### PR TITLE
Fix console mode

### LINKED ISSUE #9079: Inspect ConsoleMode before sending control codes on Windows
Per https://learn.microsoft.com/windows/console/console-virtual-terminal-sequences, on Windows an application should not assume VT compatibility but should call [`SetConsoleMode`](https://learn.microsoft.com/windows/console/setconsolemode) with `ENABLE_VIRTUAL_TERMINAL_PROCESSING`.

We should do this for TerminalLogger and for stderr results from #8792.

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #9079

### Context
First stab at taking into account console mode when writing error messages as part of a user asking for a particular property/item/target result. If we can't verify that the console is VT-compatible, we fall back to just printing things out with their default coloration. (Though not perfect, I think this is an unimportant enough scenario, that I don't think it's worth worrying about.)

### CODE REVIEW

File: src/Build/Logging/SimpleErrorLogger.cs [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+    /// </summary>
+    public class SimpleErrorLogger : INodeLogger
+    {
+        public bool hasLoggedErrors = false;
+        private bool acceptAnsiColorCodes;
+        private uint? originalConsoleMode;
+        public SimpleErrorLogger()
+        {
+            int STD_ERROR_HANDLE = -12;
+            (acceptAnsiColorCodes, _, originalConsoleMode) = NativeMethods.QueryIsScreenAndTryEnableAnsiColorCodes(STD_ERROR_HANDLE);
```
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Build/Logging/SimpleErrorLogger.cs:28]: Good call; will fix. Thanks!

**Comment by rainersigwald** [comment]
Since the other PR is still open, do you want to fix this problem in there?

**Comment by Forgind** [comment]
> Since the other PR is still open, do you want to fix this problem in there?

My personal preference is to fix it in a separate (i.e., this) PR, mostly because if I move these changes to that PR, it'd need to be reviewed more and probably need at least one or two more changes, and I'd rather it go in 🙂

**Comment by Forgind** [comment]
I can move it over there if you want me to, though.

File: src/Build/BackEnd/Client/MSBuildClient.cs [hunk 2]
```diff
@@ -229,7 +229,8 @@ public MSBuildClientExitResult Execute(CancellationToken cancellationToken)
                 CommunicationsUtilities.Trace("Build finished.");
             }
 
-            NativeMethodsShared.RestoreConsoleMode(_originalConsoleMode);
+            int STD_OUTPUT_HANDLE = -11;
```
Comment (JanKrivanek) [inline src/Build/BackEnd/Client/MSBuildClient.cs:232]: Can we reference the constant defined in Framework?
Or possibly make the usage of `STD_OUTPUT_HANDLE` default there

File: src/Build/Logging/SimpleErrorLogger.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (JanKrivanek) [reply src/Build/Logging/SimpleErrorLogger.cs:28]: I'd say the parameter should an enum (or alternatively boolean), the actual handle ids should be implementation detail within `NativeMethods` (means - `STD_OUTPUT_HANDLE` and `STD_ERROR_HANDLE` should live only there and not spill out)

File: src/Build/Logging/SimpleErrorLogger.cs [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+    ///
+    /// It is currently used only when the user requests information about specific
+    /// properties, items, or target results. In that case, we write the desired output
+    /// to standard out, but we do not want it polluted with any other kinds of information.
+    /// Users still might want diagnostic information if something goes wrong, so still
+    /// output that as necessary.
+    /// </summary>
+    public class SimpleErrorLogger : INodeLogger
+    {
+        public bool hasLoggedErrors = false;
```
Comment (JanKrivanek) [inline src/Build/Logging/SimpleErrorLogger.cs:22]: Readonly property

File: src/Framework/NativeMethods.cs [hunk 4]
```diff
@@ -1537,11 +1537,11 @@ internal static (bool acceptAnsiColorCodes, bool outputIsScreen, uint? originalC
         return (acceptAnsiColorCodes, outputIsScreen, originalConsoleMode);
     }
 
-    internal static void RestoreConsoleMode(uint? originalConsoleMode)
+    internal static void RestoreConsoleMode(uint? originalConsoleMode, int outputStreamHandle)
```
Comment (JanKrivanek) [inline src/Framework/NativeMethods.cs:1540]: int --> enum (e.g. `internal enum StreamHandleType { StdOut = -11; StdErr = -12;}` and `internal static void RestoreConsoleMode(uint? originalConsoleMode, StreamHandleType streamHandleType )`)

File: src/Build/Logging/SimpleErrorLogger.cs [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+{
+    /// <summary>
+    /// This logger ignores all message-level output, writing errors and warnings to
+    /// standard error, colored red and yellow respectively.
+    ///
+    /// It is currently used only when the user requests information about specific
+    /// properties, items, or target results. In that case, we write the desired output
+    /// to standard out, but we do not want it polluted with any other kinds of information.
+    /// Users still might want diagnostic information if something goes wrong, so still
+    /// output that as necessary.
```
Comment (JanKrivanek) [inline src/Build/Logging/SimpleErrorLogger.cs:18]: What is the motivation for introducig new single purpose logger for this, while leaving the existing `ConsoleLogger` have the unfixed behavior?
Shil this be actualy made part of the existing `ConsoleLogger`?

Comment (JanKrivanek) [reply src/Build/Logging/SimpleErrorLogger.cs:18]: Oh I see - this is intended for the https://github.com/dotnet/msbuild/pull/8792 that already uses the logger. That's a bit confusing. If you want to have 2 separate PRs (I understand that) - how about making this PR push into that branch then (you'd need to first push it into this repo though, so that such PR occurs here)?

In any case - do we actually still want to fix the same thing for the other loggers that uses the VT? Otherwise this PR probably should not be marked as fixing https://github.com/dotnet/msbuild/issues/9079

**Comment by Forgind** [comment]
> Member



> I have couple minor comments for consideration.
> 
> The main things I'd like to see addressed:
> 
> * Prevent merge mess, by either basing this on your other branch, or by first waiting for that other PR to go in (and then resolving here)

100% agree. My plan is to wait until the other PR is in, then restart the merge, and I believe it will drop all the prior commits (and make your life a lot easier!)

> * I believe the same issue should be addressed in other affected loggers as well (or otherwise the [Inspect ConsoleMode before sending control codes on Windows #9079](https://github.com/dotnet/msbuild/issues/9079) should be left open)

Which loggers are you thinking of? The only loggers that I think are potentially susceptible to this sort of problem are this new logger (fixed in this PR), the terminal logger (fixed in one of my previous PRs), and the console logger, but I asked about fixing the console logger in #9079, and rainersigwald [suggested it doesn't need fixing](https://github.com/dotnet/msbuild/issues/9079#issuecomment-1661127724). I'm fine with trying to fix it or not fix it as the two of you agree 🙂

File: src/Build/Logging/SimpleErrorLogger.cs (hunk 3 above)
Comment (Forgind) [reply src/Build/Logging/SimpleErrorLogger.cs:22]: I write to hasLoggedErrors in HandleErrorEvent. Should this have been on a different line? I can make the other two readonly.

File: src/Build/Logging/SimpleErrorLogger.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Build/Logging/SimpleErrorLogger.cs:28]: This parameter is passed pretty directly to GetStdHandle, a p/invoke in kernel32.dll, which takes an int. They're kinda the same thing, but I think it's more confusing to turn it into an enum then turn it back into an int. (I do think using the STD_OUTPUT_HANDLE in NativeMethods will make this clearer, however!)

[the remark this answers is not in the document]
Comment (JanKrivanek) [reply src/Build/Logging/SimpleErrorLogger.cs]: Any encapsulation ideally should not spill the implementation details and by extension making it possible to be easily misunderstood or misused. Why would NativeMethods be different in this regard?

An integer argument makes it harder to understand what should be passed and easier to misuse (e.g. `RestoreConsoleMode(_originalConsoleMode, NativeMethodsShared.S_OK)`).

File: src/Build/Logging/SimpleErrorLogger.cs (hunk 3 above)
Comment (Forgind) [reply src/Build/Logging/SimpleErrorLogger.cs:22]: Oh, that makes more sense. Coincidentally, ladipro made a similar comment in my other PR. I should be able to pull in that change to cover this 🙂

**Comment by Forgind** [comment]
> Please reconsider what win32 api details needs to be exposed beyond boundaries of the NativeMethods

That's fair. I guess I was thinking about if a user happens to be familiar with the wind32 API already...but how many people actually are? I added an enum.

**Comment by Forgind** [comment]
@JanKrivanek, diff looks a lot cleaner now, so I removed the do-not-merge label.

**Review by rokonec — APPROVED** [review]
LGTM. I have few opinionated/nit comments.

**Comment by Forgind** [comment]
@rokonec, I resolved your first and third comments but left your second one because you fixed that in your PR. As I said there, we can merge one of the PRs and resolve conflicts then, or I can pull your changes into my branch, and we can merge them as one change. I'm ok with either way.
