### PR TITLE
Fix indentation of multiline messages in Terminal Logger.

### LINKED ISSUE #9996: Fix indentation of multiline messages in Terminal Logger with quiet verbosity.
The multiline messages indentation processing implies that the message will appear in the structured view under the related project. 
That is not correct for the Quiet verbosity and for couple of other places, such as rendering the immediate message and cases when the project is not determined.

### PR DESCRIPTION
**Pull request by AR-May**
Fixes #9996

### Context
The multiline messages indentation processing implies that the message will appear in the structured view under the related project. That is not correct for the Quiet verbosity and for couple of other places, such as rendering the immediate message and cases when the project is not determined.

### Changes Made
Make the indentation dependent on where the message would be shown.

### Testing
Unit tests

### CODE REVIEW

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 1]
```diff
@@ -906,27 +896,17 @@ private void WarningRaised(object sender, BuildWarningEventArgs e)
...
-                columnNumber: e.ColumnNumber,
-                endColumnNumber: e.EndColumnNumber);
-
+        
         if (buildEventContext is not null
             && _projects.TryGetValue(new ProjectContext(buildEventContext), out Project? project)
             && Verbosity > LoggerVerbosity.Quiet)
         {
-            project.AddBuildMessage(MessageSeverity.Error, message);
+            project.AddBuildMessage(MessageSeverity.Error, FormatErrorMessage(e, $"{Indentation}{Indentation}{Indentation}"));
```
Comment (MichalPavlik) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:904]: nit: This indentation could be declared as constant.

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 2]
```diff
@@ -858,32 +858,22 @@ private void MessageRaised(object sender, BuildMessageEventArgs e)
...
         {
-            if (IsImmediateMessage(message))
+            if (!String.IsNullOrEmpty(e.Message) && IsImmediateMessage(e.Message))
             {
-                RenderImmediateMessage(message);
+                RenderImmediateMessage(FormatWarningMessage(e, Indentation));
             }
 
-            project.AddBuildMessage(MessageSeverity.Warning, message);
+            project.AddBuildMessage(MessageSeverity.Warning, FormatWarningMessage(e, $"{Indentation}{Indentation}{Indentation}"));
```
Comment (MichalPavlik) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:871]: nit: This indentation could be declared as constant

**Review by MichalPavlik — APPROVED** [review]
LGTM overall

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 3]
```diff
@@ -858,32 +858,22 @@ private void MessageRaised(object sender, BuildMessageEventArgs e)
...
         }
         else
         {
             // It is necessary to display warning messages reported by MSBuild, even if it's not tracked in _projects collection or the verbosity is Quiet.
-            RenderImmediateMessage(message);
+            RenderImmediateMessage(FormatWarningMessage(e, Indentation));
```
Comment (JanKrivanek) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:876]: Should those be colored as warning? Even if verbosity is set to e.g. diag?

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 4]
```diff
@@ -1070,6 +1050,36 @@ private int NodeIndexForContext(BuildEventContext context)
...
+                subcategory: e.Subcategory,
+                message: e.Message,
+                code: AnsiCodes.Colorize(e.Code, TerminalColor.Red),
+                file: HighlightFileName(e.File),
+                lineNumber: e.LineNumber,
+                endLineNumber: e.EndLineNumber,
+                columnNumber: e.ColumnNumber,
+                endColumnNumber: e.EndColumnNumber,
+                indent);
+    }
```
Comment (JanKrivanek) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:1081]: Can the common code be extracted here (as they differ only by category)?

Comment (AR-May) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:1081]: They differ by category, by color, but that we can also pass as a parameter to a single function, together with the category. And they also differ by the type - one is `BuildWarningEventArgs` and another is `BuildErrorEventArgs`. You would think that they have a common parent class with Subcategory and other properties for me to use in a common code, but no... So, I guess there is no simplification for that code.

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 3 above)
Comment (AR-May) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:876]: Why wouldn't we want warning not to be formatted (including the coloring) as a warning in any verbosity?

To clarify, just in case, I did not change any behavior besides the indentation in this PR. this `message` was formatted as warning above as well.

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 4 above)
Comment (JanKrivanek) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:1085]: Makes sense then

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 3 above)
Comment (JanKrivanek) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:880]: Sorry - I mixed verbosity and severity here 🤦 
All is good!
