### PR TITLE
Have ProjectInSolution.AbsolutePath return a normalized path

### LINKED ISSUE #5949: ProjectInSolution.AbsolutePath should return a normalized full path
### Issue Description
`ProjectInSolution.AbsolutePath` currently returns the result of `Path.Combine()` which leaves in relative path segments like `..\`.  When parsing a solution and getting the paths to projects, this places the burden on the caller to normalize the path.

https://github.com/dotnet/msbuild/blob/1ff34e830630ff7c4b6cb008e85ece4f263ace52/src/Build/Construction/Solution/ProjectInSolution.cs#L165

### Steps to Reproduce
Create a solution with relative paths containing `..\` 
Parse the solution with the `SolutionFile` API
Call the `AbsolutePath` property on one of the `ProjectInSolution` objects.

### Expected Behavior
`AbsolutePath` property returns a normalized full path.

### Actual Behavior
`AbsolutePath` property returns a path containing `..\` segments.

### Versions & Configurations
All versions of MSBuild

This manifested into this bug: https://github.com/NuGet/Home/issues/10307

And its worked around in MSBuild's own codebase:
https://github.com/dotnet/msbuild/blob/1ff34e830630ff7c4b6cb008e85ece4f263ace52/src/Build/Graph/GraphBuilder.cs#L293-L298

### PR DESCRIPTION
**Pull request by jeffkl**
This change updates `ProjectInSolution.AbsolutePath` to return a normalized path.  At the moment it simply returns the result of a `Path.Combine()` which leaves `..\` path segments in place and does not contain OS-specific path separators.

Fixes #5949 and https://github.com/NuGet/Home/issues/10307

### CODE REVIEW

File: src/Build/Construction/Solution/ProjectInSolution.cs [hunk 1]
```diff
@@ -162,7 +162,18 @@ internal set
...
+        public string AbsolutePath
+        {
+            get
+            {
+                if (string.IsNullOrWhiteSpace(ParentSolution?.SolutionFileDirectory))
+                {
+                    return RelativePath;
+                }
+
+                return FileUtilities.NormalizePath(Path.Combine(ParentSolution.SolutionFileDirectory, RelativePath));
```
Comment (rainersigwald) [inline src/Build/Construction/Solution/ProjectInSolution.cs:174]: We have an overload to do this 
```suggestion
                return FileUtilities.NormalizePath(ParentSolution.SolutionFileDirectory, RelativePath);
```

Comment (jeffkl) [reply src/Build/Construction/Solution/ProjectInSolution.cs:174]: Thanks will call that.  This adds some protection from an exception in Path.Combine() in some cases ParentSolution.SolutionFileDirectory is null, specifically in our unit tests.  I figured I'd add this new protection as part of this fix.  Do you think I should leave it as-is?

Comment (rainersigwald) [reply src/Build/Construction/Solution/ProjectInSolution.cs:174]: Adding protection for that case makes sense to me--not sure if the public API makes it easy to pass an in-memory sln but don't see why that couldn't be done, so guarding against it makes sense, especially if we already hit it in tests.

Comment (jeffkl) [reply src/Build/Construction/Solution/ProjectInSolution.cs]: I'll show up to tomorrow's PR review meeting to discuss, there's some weirdness going on :/

File: src/Build/Construction/Solution/SolutionFile.cs [hunk 2]
```diff
@@ -475,8 +482,6 @@ internal void ParseSolutionFile()
             {
                 // Open the file
                 fileStream = File.OpenRead(_solutionFile);
-                // Store the directory of the file as the current directory may change while we are processes the file
-                SolutionFileDirectory = Path.GetDirectoryName(_solutionFile);
```
Comment (Forgind) [inline src/Build/Construction/Solution/SolutionFile.cs:479]: Have you found cases when the current directory changes while processing the solution file? I couldn't find a public-facing way to change directory between where it is current set and where you are now setting it.

File: src/Build.UnitTests/Construction/SolutionFile_Tests.cs [hunk 3]
```diff
@@ -2400,5 +2400,42 @@ public void ParseSolutionFileContainingProjectsWithSimilarNames_FourProjects_One
...
+                        {0ABED153-9451-483C-8140-9E8D7306B216}.Release|AnyCPU.Build.0 = Release|AnyCPU
+                    EndGlobalSection
+                    GlobalSection(SolutionProperties) = preSolution
+                        HideSolutionNode = FALSE
+                    EndGlobalSection
+                EndGlobal
+                ";
+
+            SolutionFile solution = ParseSolutionHelper(solutionFileContents);
+            string expectedRelativePath = NativeMethodsShared.IsWindows ? @"..\ProjectA\ProjectA.csproj" : @"../ProjectA/ProjectA.csproj";
```
Comment (Forgind) [inline src/Build.UnitTests/Construction/SolutionFile_Tests.cs:2434]: nit:
```suggestion
            string expectedRelativePath = Path.Combine("..", "ProjectA", "ProjectA.csproj");
```

File: src/Build.UnitTests/Construction/SolutionFile_Tests.cs [hunk 4]
```diff
@@ -2400,5 +2400,42 @@ public void ParseSolutionFileContainingProjectsWithSimilarNames_FourProjects_One
...
+            Assert.Equal("ProjectA", solution.ProjectsInOrder[0].ProjectName);
```
Comment (Forgind) [inline src/Build.UnitTests/Construction/SolutionFile_Tests.cs:2435]: nit: Shouldly?
```suggestion
            solution.ProjectsInOrder[0].ProjectName.ShouldBe("ProjectA");
```
etc.

File: src/Build/Construction/Solution/SolutionFile.cs [hunk 5]
```diff
@@ -210,6 +210,9 @@ internal string FullPath
                 {
                     _solutionFile = value;
                     _solutionFilter = null;
+
+                    // Store the directory of the file as the current directory may change while we are processes the file
```
[the remark this answers is not in the document]
Comment (jeffkl) [reply src/Build/Construction/Solution/SolutionFile.cs:214]: Sorry I just copied this from here: https://github.com/dotnet/msbuild/blob/master/src/Build/Construction/Solution/SolutionFile.cs#L477-L478

The problem with the unit tests hitting NullRefs was because the SolutionFileDirectory is only set during parse.  But our unit tests don't always parse an entire solution as some of them only parse single lines so the SolutionFileDirectory property doesn't get set.  So I replicated setting this property here and copied the comment along with the line.  Should I just delete the comment?

File: src/Build/Construction/Solution/ProjectInSolution.cs [hunk 6]
```diff
@@ -152,17 +152,20 @@ internal set
...
                 // cases. It caused https://github.com/NuGet/Home/issues/6918.
                 _relativePath = value;
+
+                AbsolutePath = Path.GetFullPath(Path.Combine(ParentSolution.SolutionFileDirectory, _relativePath));
 #else
-                _relativePath = FileUtilities.MaybeAdjustFilePath(value,
-                                                    baseDirectory:ParentSolution.SolutionFileDirectory ?? String.Empty);
+                _relativePath = FileUtilities.MaybeAdjustFilePath(value, ParentSolution.SolutionFileDirectory);
+
+                AbsolutePath = FileUtilities.NormalizePath(Path.Combine(ParentSolution.SolutionFileDirectory, _relativePath));
```
[the remark this answers is not in the document]
Comment (jeffkl) [reply src/Build/Construction/Solution/ProjectInSolution.cs:160]: Yeah I might as well.  Especially if it throws an exception for whatever reason it would be confusing to be accessing the RelativePath property and get an exception about AbsolutePath

File: src/Build/Construction/Solution/SolutionFile.cs (hunk 2 above)
Comment (jeffkl) [reply src/Build/Construction/Solution/SolutionFile.cs:479]: I have no idea, this comment has been here since the dawn of time.

Comment (rainersigwald) [reply src/Build/Construction/Solution/SolutionFile.cs:479]: > 2006-04-07 18:38:15
> Initial multiproc code

🤷🏻‍♂️

File: src/Build.UnitTests/Construction/SolutionFile_Tests.cs (hunk 4 above)
Comment (jeffkl) [reply src/Build.UnitTests/Construction/SolutionFile_Tests.cs:2435]: Should I convert this whole file to Shouldly so its consistent?

File: src/Build/Construction/Solution/SolutionFile.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Build/Construction/Solution/SolutionFile.cs:214]: ¯\_(ツ)_/¯

I didn't find anything that validated the comment, but that doesn't mean there was nothing to find. It's probably just out-of-date, so yes?

File: src/Build.UnitTests/Construction/SolutionFile_Tests.cs (hunk 4 above)
Comment (Forgind) [reply src/Build.UnitTests/Construction/SolutionFile_Tests.cs:2435]: I wouldn't push for it. My thought is: Shouldly on new tests and when modifying tests --> it will eventually be used in all tests in the MSBuild repo that have the possibility of failing. If you want to convert the whole file, though, I certainly wouldn't stop you. (I did that at one point when I was frustrated and wanted something easy and monotonous.)

**Review by Forgind — APPROVED** [review]

File: src/Build.UnitTests/Construction/SolutionFile_Tests.cs (hunk 4 above)
Comment (jeffkl) [reply src/Build.UnitTests/Construction/SolutionFile_Tests.cs:2435]: I'll take a stab at converting the whole file.  I personally like consistency so I'd rather have all older Asserts or Shouldly, no mix...

Comment (jeffkl) [reply src/Build.UnitTests/Construction/SolutionFile_Tests.cs]: Done, soooooo much better!

File: src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs [hunk 7]
```diff
@@ -740,10 +740,10 @@ public void SolutionConfigurationWithDependencies()
             string solutionConfigurationContents = msbuildProject.GetPropertyValue("CurrentSolutionConfigurationContents");
 
             // Only the specified solution configuration is represented in THE BLOB: nothing for x64 in this case
-            string expected = @"<SolutionConfiguration>
-  <ProjectConfiguration Project=`{786E302A-96CE-43DC-B640-D6B6CC9BF6C0}` AbsolutePath=`##temp##Project1\A.csproj` BuildProjectInSolution=`True`>Debug|AnyCPU</ProjectConfiguration>
-  <ProjectConfiguration Project=`{881C1674-4ECA-451D-85B6-D7C59B7F16FA}` AbsolutePath=`##temp##Project2\B.csproj` BuildProjectInSolution=`True`>Debug|AnyCPU<ProjectDependency Project=`{4A727FF8-65F2-401E-95AD-7C8BBFBE3167}` /></ProjectConfiguration>
-  <ProjectConfiguration Project=`{4A727FF8-65F2-401E-95AD-7C8BBFBE3167}` AbsolutePath=`##temp##Project3\C.csproj` BuildProjectInSolution=`True`>Debug|AnyCPU</ProjectConfiguration>
```
Comment (rainersigwald) [inline src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs:746]: Isn't the content of the solution _always_ backslashed? Was this change necessary?

**Review by rainersigwald — APPROVED** [review]
Ideally I'd like it interactive rebased to have a commit for the shouldly migration and a separate commit for the actual change.

File: src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs (hunk 7 above)
Comment (jeffkl) [reply src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs:746]: This isn't the solution, this is the metaproj which has OS-specific path separators

Comment (jeffkl) [reply src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs:746]: Or it will now because I'm normalizing AbsolutePath

Comment (rainersigwald) [reply src/Build.UnitTests/Construction/SolutionProjectGenerator_Tests.cs:746]: 😮 got it.
