### PR TITLE
Buildcheck - ProjectImported OM fixes

### LINKED ISSUE #10960: ProjectImported OM should only exist in logger thread context
### Context

https://github.com/dotnet/msbuild/pull/10959#discussion_r1834738830

The `_deferredProjectEvalIdToImportedProjects` should be ensured to be called only from the `BuildEventArgs` handlers - so in a synchronized context. Then we can gt rid of any synchronization on it

### What needs to be done

The handler of `BuildCheckBuildEventHandler.HandleProjectEvaluationStartedEvent` and `ProcessProjectEvaluationStarted` needs to be separated, as currently we cannot distinguish the situation "ProjectEvaluationStartedEvent occured, but it was received through logging infrastructure".

The reason for the 2 possible sources of the event (through the logging or directly from engine) is due to the fact that the BuildCheckManager can live in the worker node as well.

The `ProjectImported` data are to be received only via the logging infrastructure - so it should be handled only in the handler of `BuildCheckBuildEventHandler.HandleProjectEvaluationStartedEvent`. Since the logging infra guarantees synchronized (single threaded) delivery of events - we can then be sure that all handling of the `ProjectImported` data happens without concurrency risks and any synchronization (or usage of ConcurrentDictionary) can be removed. This should significantly simplify the code

### PR DESCRIPTION
**Pull request by JanKrivanek**
Fixes #10960, #10935

### Context
 * ProjectImported OM wasn't properly propagated if binlog wasn't specified
 * ProjectImported OM should only be handled in single threaded context of main node logger

### Testing
Preexisting tests

### CODE REVIEW

File: src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs [hunk 1]
```diff
@@ -620,15 +628,10 @@ public void StartProjectRequest(ICheckContext checkContext, string projectFullPa
...
+                    out HashSet<string>? importedProjects))
             {
-                lock (importedProjects)
-                {
-                    if (importedProjects.Contains(originalProjectFile))
-                    {
-                        importedProjects.Add(newImportedProjectFile);
-                    }
-                }
+                importedProjects.Add(newImportedProjectFile);
```
Comment (SimaTian) [inline src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs:634]: Why are we removing the `if (importedProjects.Contains(originalProjectFile))` check please?
If we always add to the imported projects, we don't need the originalProjectsFile and the method almost loses it's meaning.

File: src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs [hunk 2]
```diff
@@ -503,8 +501,8 @@ public void FinalizeProcessing(LoggingContext loggingContext)
 
         private readonly ConcurrentDictionary<int, string> _projectsByInstanceId = new();
         private readonly ConcurrentDictionary<int, string> _projectsByEvaluationId = new();
-
-        private readonly ConcurrentDictionary<int, HashSet<string>> _deferredProjectEvalIdToImportedProjects = new();
+        // We are receiving project imported data only from the logger events - hence always in a single threaded context
```
Comment (SimaTian) [inline src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs:504]: I couldn't find my answer in the infrastructure so I'm sorry but I will go ahead and ask.
Where do we guarantee that our events are synchronous please? Can't the logger get hit by two separate events, that will require handling at the same time? Or are these enqueued so the synchronization is guaranteed?
(The core of my question is that I see event, I think async. So this sentence goes against my intuition.)

File: src/Build/BuildCheck/Infrastructure/NullBuildCheckManager.cs [hunk 3]
```diff
@@ -61,6 +61,10 @@ public void ProjectFirstEncountered(BuildCheckDataSource buildCheckDataSource, I
     }
 
     public void ProcessProjectEvaluationStarted(ICheckContext checkContext, string projectFullPath)
```
Comment (maridematte) [inline src/Build/BuildCheck/Infrastructure/NullBuildCheckManager.cs:63]: Same as befor, do we need this extra function when it does not exist in the interface.

File: src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs (hunk 1 above)
Comment (JanKrivanek) [reply src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs:634]: The method had just quite confusing pre-existing naming and comment - I've fixed that.

In short - we are just adding to a lookup of all imported logic, that is keyed by the project file that is importing the logic

File: src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs [hunk 4]
```diff
@@ -571,12 +569,22 @@ public void ProjectFirstEncountered(
             SetupChecksForNewProject(projectFullPath, checkContext);
         }
 
+        public void ProcessProjectEvaluationStarted(ICheckContext checkContext, string projectFullPath)
```
[the remark this answers is not in the document]
Comment (JanKrivanek) [reply src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs:572]: Good question! The `BuildCheckManagerProvider` implements `IBuildCheckManager`, but as well `IBuildEngineDataRouter` - the two methods come from the to interfaces -> later is for 'worker node inproc' events delivery, former for 'via logging service' events delivery

File: src/Build/BuildCheck/Infrastructure/NullBuildCheckManager.cs (hunk 3 above)
Comment (JanKrivanek) [reply src/Build/BuildCheck/Infrastructure/NullBuildCheckManager.cs:63]: Same as above

File: src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs (hunk 2 above)
Comment (JanKrivanek) [reply src/Build/BuildCheck/Infrastructure/BuildCheckManagerProvider.cs:504]: Added to the comment.

**Review by maridematte — APPROVED** [review]
