### PR TITLE
Attribute custom task OOM (and other critical exceptions) to the task

### LINKED ISSUE #9928: OutOfMemory exception on a task not reported for a particular task.
### Context

Inspired by: https://stackoverflow.microsoft.com/questions/394371

Experience of having a task experiencing OOM:

```
Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:19:29.61
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at Newtonsoft.Json.Linq.JToken.ToString(Formatting formatting, JsonConverter[] converters)
   at Microsoft.Portal.Framework.ContentPackageGenerator.ContentPackageWriter.WriteDocument[T](PackageEntryPath documentPath, T newDocument, T existingDocument)
   at Microsoft.Portal.Framework.ContentPackageGenerator.ContentPackageWriter.WriteProjectsDocument(EffectiveContentPackageProject projects)
   at Microsoft.Portal.Framework.ContentPackageGenerator.PopulatePackage(ContentPackageWriter contentPackage)
   at Microsoft.Portal.Framework.ContentPackageGenerator.GeneratePackage(IContentStore contentStore, Action`2 logger)
   at Microsoft.Portal.Framework.GenerateContentPackageCore.Generate(ContentPackageGeneratorParameters parameters, Action`2 logger)
   at Microsoft.Portal.Pdc.Core.DxBuild.GenerateContentPackage(DxBuildArgs args, ITaskLoggingHelper loggingHelper, String ContentPackageProjectFileWriterResult)
   at Microsoft.Portal.Pdc.Core.DxBuild.Compile(DxBuildArgs args, ITaskLoggingHelper loggingHelper)
   at Microsoft.Portal.Pdc.Core.DxBuildTask.ExecuteCore()
   at Microsoft.Portal.Framework.PortalTaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

```

Experience of a task experiencing 'traditional exception':

```
error MSB4018: The "TaskThatReturnsDictionaryTaskItem" task failed unexpectedly.
This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
System.Exception: Hello there!
   at Microsoft.Build.Engine.UnitTests.TaskThatReturnsDictionaryTaskItem.Execute() in C:\src\msbuild\src\Build.UnitTests\BackEnd\TaskThatReturnsDictionaryTaskItem.cs:line 24
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in C:\src\msbuild\src\Build\BackEnd\TaskExecutionHost\TaskExecutionHost.cs:line 561
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() in C:\src\msbuild\src\Build\BackEnd\Components\RequestBuilder\TaskBuilder.cs:line 813
Done executing task "TaskThatReturnsDictionaryTaskItem" -- FAILED.
Done building target "Build" in project "Temporary45a7acefae06435d83657c9bcf06a0df.csproj" -- FAILED.
Done building project "Temporary45a7acefae06435d83657c9bcf06a0df.csproj" -- FAILED.
Build FAILED.
```

The case 2 is much more informative and actionable

### Repro steps

 * Edit [`TaskThatReturnsDictionaryTaskItem`](https://github.com/dotnet/msbuild/blob/main/src/Build.UnitTests/BackEnd/TaskThatReturnsDictionaryTaskItem.cs)
 * Add `throw new Exception("Hello there!");` into the Execute() method
 * Execute/Debug one of the unit tests in [`TaskExecutionHost_Tests`](https://github.com/dotnet/msbuild/blob/main/src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs) (e.g. `TestTaskDictionaryOutputItems`)
 * Change the exception in Execution method to `OutOfMemoryException`
 * Execute the test again and compare log outputs

### Details

We handle OOM with special care (see https://github.com/dotnet/msbuild/blob/bf82a1313390df2692c23206e0846b205398188b/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L861) as it might be dangerous to try to perform some nontrivial processing. Though we should inspect the code and reevaluate - I believe we should be able to log more descritpive error with a low risk (as the mere fact of throwin OOM leads to GC and usually to nontrivial freed-up space)

### PR DESCRIPTION
**Pull request by JanKrivanek**
Fixes #9928

### Context
OOM in custom tasks is rethrown to RequestBuilder, where it is logged as an MSBuild bug.
We might try - on best effort basis - to log an error for the task little more up the stack and then continue in unrolling as before. If we succeed - we get better logging experience for the case; if we fail - we get the same experience as before.

### Changes Made
* The exception is attempted to be logged in `TaskBuilder`
* `RequestThreadProc` and `BuildAndReport` methods merged into single one - so that writing the 'error dump' file (MSBuild***.failure.txt) is deterministically written before reporting the result back
* Exposing an internal option to re-initialize `DebugUtils.DebugPath` - as this was set before any unit test was given chance to start, so injecting altering env var was not possible.

### Testing
Added test with dummy OOM (not a real CLR OOM - in order to have deterministic test outputs)

### Notes
Discussed the OOM handling with @janvorli (for a perspective from the Runtime PoV) - we should not make no expectations that anything can succeed after OOM catching (though this migh get more successful in single threaded processing - which MSBuild currently is), but if we are fine with the handler possibly failing (which basically leads to pre-existing behavior) - than there should not be any security nor corectness concerns.

### CODE REVIEW

File: src/Framework/CriticalTaskException.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using Microsoft.Build.Framework.BuildException;
+
+namespace Microsoft.Build.Framework
+{
+    internal sealed class CriticalTaskException : BuildExceptionBase
```
Comment (rainersigwald) [inline src/Framework/CriticalTaskException.cs:13]: Doc comment please

File: src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs [hunk 2]
```diff
@@ -1050,6 +1050,46 @@ public void TestTaskDictionaryOutputItems()
...
+            // 'This is an unhandled error in MSBuild'
+            ml.AssertLogDoesntContain(ResourceUtilities.FormatResourceStringIgnoreCodeAndKeyword("UnhandledMSBuildError", string.Empty));
+            ml.AssertLogContains(testExceptionMessage);
+
+            File.Exists(ExceptionHandling.DumpFilePath).ShouldBe(isCritical,
+                $"{ExceptionHandling.DumpFilePath} expected to exist: {isCritical}");
+            if (isCritical)
+            {
+                FileUtilities.DeleteNoThrow(ExceptionHandling.DumpFilePath);
+            }
```
Comment (rainersigwald) [inline src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs:1090]: `TestEnvironment` cleans up so you don't have to.

File: src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs [hunk 3]
```diff
@@ -814,8 +814,18 @@ private async Task<WorkUnitResult> ExecuteInstantiatedTask(ITaskExecutionHost ta
...
+                catch (Exception ex)
                 {
+                    if (ExceptionHandling.IsCriticalException(ex) || Environment.GetEnvironmentVariable("MSBUILDDONOTCATCHTASKEXCEPTIONS") == "1")
+                    {
+                        taskLoggingContext.LogFatalTaskError(
+                            ex,
+                            new BuildEventFileInfo(_targetChildInstance.Location),
+                            _taskNode.Name);
+
+                        throw new CriticalTaskException(ex);
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:826]: Is there not a potential problem allocating this on the OOM path?

**Review by rainersigwald — APPROVED** [review]

File: src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs (hunk 2 above)
Comment (JanKrivanek) [reply src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs:1095]: There are couple TestEnvironment injected automatically (mainly via `MSBuildTestEnvironmentFixture`), that do not allow setting `AllowTaskCrashes` to `true` and those would fail the test during cleanup phase

File: src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs (hunk 3 above)
Comment (JanKrivanek) [reply src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:826]: Yes - it can lead to crash with uncatchable OOM.
But that is same to the situation where we logged this exception in `RequestBuilder` - as the logging itself here is more costly (needs to fetch the resource string and format the error message). So technically we are not changing the odds of that eventuality much. 

In optimistic (and hopefully typical) scenario the OOM in a custom task is caused by allocations within that task - either by bigger blocks allocations (where the last block will lead to OOM, but will leave smaller chunks still available) or by smaller chunks allocations that will became unrooted after the stack unrolling, GC will free up that memory. So those two allocations (logging and wrapping exceptions) should be accomodable.
We do not have other greedy threads running - so the available memory should not get depleted asynchronously.

cc @janvorli for runtime perspective - in case I'm wrong in my takeaways from our offline discussion

Comment (janvorli) [reply src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:826]: To make the odds a bit better, you could preallocate the `BuildEventFileInfo` and `CriticalTaskException` instances. But there are possibilities of other allocations occurring in the runtime under the hoods, possibly even for jitting the code. So in general, after the OOM exception is thrown, all you do is just a best effort.

File: src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs (hunk 2 above)
Comment (rainersigwald) [reply src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs:1095]: Ah, sure--comment please then :)
