### PR TITLE
Fix race conditions in task host path resolution

### LINKED ISSUE #13484: Race condition in GetTaskHostNameFromHostContext causes ArgumentNullException in multithreaded builds
## Summary

Multithreaded (`/mt`) builds that launch out-of-process task hosts crash with `ArgumentNullException: Value cannot be null. Parameter name: path2` in `Path.Combine` when multiple `RequestBuilder` threads simultaneously resolve the task host executable name. Happens approximately 2 times out of 1000 runs.

## Error

```
error MSB4018: The "GetReferenceAssemblyPaths" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcTaskHost.GetMSBuildExecutablePathForNonNETRuntimes(HandshakeOptions hostContext)
   at ...CreateNode > ResolveNodeLaunchConfiguration
   at ...AcquireAndSetUpHost
   at Microsoft.Build.BackEnd.TaskHostTask.Execute()
```

## Root cause

`GetTaskHostNameFromHostContext` in `NodeProviderOutOfProcTaskHost.cs` has an unsafe read-modify-write sequence on the static field `s_msbuildName`:

```csharp
if (string.IsNullOrEmpty(s_msbuildName))            // (1) check
{
    s_msbuildName = Environment.GetEnvironmentVariable("MSBUILD_EXE_NAME"); // (2) write — may be null
    if (!string.IsNullOrEmpty(s_msbuildName))
    {
        return s_msbuildName;
    }
    s_msbuildName = Constants.MSBuildExecutableName;  // (3) write — always non-null
}
return s_msbuildName;                                // (4) read
```

When `MSBUILD_EXE_NAME` is not set, step (2) writes `null` into `s_msbuildName`. Between steps (2) and (3), another thread can read `s_msbuildName` at step (4)** and get `null`.

The returned `null` is passed as `toolName` into `Path.Combine(basePath, toolName)`, which throws `ArgumentNullException` on .NET Framework (where `Path.Combine` does not accept null arguments).

### PR DESCRIPTION
**Pull request by AR-May**
# Fixes #13484

### Context
Multithreaded (`/mt`) builds that launch out-of-process task hosts crash with `ArgumentNullException: Value cannot be null. Parameter name: path2` in `Path.Combine` when multiple `RequestBuilder` threads simultaneously resolve the task host executable name.

### Root cause

`GetTaskHostNameFromHostContext` in `NodeProviderOutOfProcTaskHost.cs` has an unsafe read-modify-write sequence on the static field `s_msbuildName`:

```csharp
if (string.IsNullOrEmpty(s_msbuildName))            // (1) check
{
    s_msbuildName = Environment.GetEnvironmentVariable("MSBUILD_EXE_NAME"); // (2) write — may be null
    if (!string.IsNullOrEmpty(s_msbuildName))
    {
        return s_msbuildName;
    }
    s_msbuildName = Constants.MSBuildExecutableName;  // (3) write — always non-null
}
return s_msbuildName;                                // (4) read
```

When `MSBUILD_EXE_NAME` is not set, step (2) writes `null` into `s_msbuildName`. Between steps (2) and (3), another thread can read `s_msbuildName` at step (4)** and get `null`.

The returned `null` is passed as `toolName` into `Path.Combine(basePath, toolName)`, which throws `ArgumentNullException` on .NET Framework (where `Path.Combine` does not accept null arguments).

### Changes Made
 Since all computations are deterministic (environment variables + constants), we use the local-variable snapshot pattern
  — read the static into a local, compute if null, write back, return the local. This is lock-free and safe because reference writes are atomic in .NET. Applied the same fix to similar patterns in nearby code in NodeProviderOutOfProcTaskHost.cs and CurrentHost.cs

### Testing
No extra testing. There is no stable local repro.

### CODE REVIEW

File: src/Build/BackEnd/Components/Communications/CurrentHost.cs [hunk 1]
```diff
@@ -52,17 +53,19 @@ internal static class CurrentHost
...
+                        host = dotnetExe;
                     }
                     else
                     {
                         ErrorUtilities.ThrowInternalErrorUnreachable();
                     }
                 }
             }
+
+            s_currentHost = host;
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Communications/CurrentHost.cs:65]: Should we do another null check, or a `Interlocked.CompareExchange`?

Comment (JanProvaznik) [reply src/Build/BackEnd/Components/Communications/CurrentHost.cs:65]: That does not seem necessary. If multiple threads call this it would resolve the same path twice and that is not dangerous to write twice.
