### PR TITLE
TL: Fix logs appearance from nuget client/credential provider

### LINKED ISSUE #9068: TerminalLogger hides NuGet device-flow prompts
When building a project that uses a NuGet feed with required credentials, I got no indication that I needed to log in until this error

```
MSBuild version 17.8.0-preview-23369-01+a9034a279 for .NET Framework
    ❌ C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :     [CredentialProvider]Device flow authentication failed. User was presented with device flow, but didn't react within 90 seconds.

Restore failed with errors in 553.8s
```

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes #9068

### Context
Before this change we were showing specific messages in TL that matched a selected pattern + all the build warnings were displayed at the final build stage.

### Changes Made
Introduce immediate print functionality for blocking messages from nuget client/credential provider

### Testing
Manual + UTs

### Notes
The implementation will be reconsidered after introducing TL API

### CODE REVIEW

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 1]
```diff
@@ -25,6 +25,9 @@ namespace Microsoft.Build.Logging.TerminalLogger;
 /// </remarks>
 internal sealed class TerminalLogger : INodeLogger
 {
+    private const string FilePathPattern = " -> ";
+    private readonly string[] _immediateMessageMarkers = new[] { "[CredentialProvider]", "--interactive" };
```
Comment (baronfel) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:29]: nit: .NET 8 provides a SearchValues<T> structure that, when used in `IndexOfAny` gives massive perf speedups. can you see if that works, since we'll be doing this on every message?

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 2]
```diff
@@ -561,6 +564,12 @@ private void MessageRaised(object sender, BuildMessageEventArgs e)
                     project.OutputPath = outputPath;
                 }
             }
+
+            // Detect markers that require special attention from a customer.
+            if (_immediateMessageMarkers.Any(marker => message.IndexOf(marker, StringComparison.Ordinal) > 0))
```
Comment (baronfel) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:569]: I _think_ if you can convert the string to a span/memory, then `Memory.IndexOfAny(StringValues)` will be much more performant here and on 598 below.

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 1 above)
Comment (YuliiaKovalova) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:29]: we compile for .net framework too, is it ok to use `IndexOfAny`for .net only?

Comment (rainersigwald) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:29]: Can you comment these? Is it that if you're not in interactive, the message will say "add --interactive`, and if you are in interactive, the message has `[CredentialProvider]`?

Comment (rainersigwald) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:29]: SearchValues only applies to sets of individual characters, as far as I can tell.

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 2 above)
Comment (rainersigwald) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:569]: I think a regex might actually be the best path forward here (😱). I don't know another way to  do an equivalent of `IndexOfAny(string[])`. We can use the .NET 8 source-generated ones though!

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 1 above)
Comment (YuliiaKovalova) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:29]: "add --interactive" falls in `WarningRaised`, and "[CredentialProvider]" goes to `MessageRaised`.
If any of these substrings appears we put it in output immediately:
image
image

Comment (baronfel) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:29]: Man I hate that formatting, but it's probably the best we can reasonably do given the free-form nature of the Messages. My ideal long-term fix for this would have different formatting for sure :)

Side question - do more advanced terminals (iTerm2, Windows Terminal, etc?) make the devicelogin url clickable?

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 2 above)
Comment (YuliiaKovalova) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:569]: so should I switch to regex here?

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 1 above)
Comment (YuliiaKovalova) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:29]: Windows Terminal +
iTerm2 -
bash -

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 2 above)
Comment (rainersigwald) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:569]: I think so. Since it's scanning lots of messages I think it's worth pursuing the perf improvements we'd get there.

File: src/MSBuild/TerminalLogger/TerminalLogger.cs (hunk 1 above)
Comment (YuliiaKovalova) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs]: @baronfel , I removed the coloring, let me know if you desperately want it back ;)

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 3]
```diff
@@ -595,15 +596,27 @@ private void WarningRaised(object sender, BuildWarningEventArgs e)
...
             project.AddBuildMessage(MessageSeverity.Warning, message);
         }
     }
 
+    /// <summary>
+    /// Detectw markers that require special attention from a customer.
+    /// </summary>
+    /// <param name="message">Raised event</param>
+    /// <returns>true if marker is detected.</returns>
+    private bool ImmeidateMessageRaised(string message)
```
Comment (baronfel) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:613]: typo here: `Immediate`

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 4]
```diff
@@ -595,15 +596,27 @@ private void WarningRaised(object sender, BuildWarningEventArgs e)
...
+    {
+        Regex regex = new Regex($"({_immediateMessagePattern})");
```
Comment (baronfel) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs]: we shouldn't re-create this Regex for each call to this method - we should precompute it once as a class-local value and reuse that precomputed value here.

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 5]
```diff
@@ -28,7 +28,7 @@ internal sealed class TerminalLogger : INodeLogger
 {
     private const string FilePathPattern = " -> ";
     private const char PatternSeparator = '|';
-    private readonly string _immediateMessagePattern = $@"\[CredentialProvider\]{PatternSeparator}--interactive";
+    private readonly Regex _immediateMessageRegex = new Regex($@"\[CredentialProvider\]{PatternSeparator}--interactive");
```
Comment (rainersigwald) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:31]: Consider doing the full source-generator thing for .NET 8. Example in #9411.

Comment (YuliiaKovalova) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs]: done

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 6]
```diff
@@ -586,10 +613,22 @@ private void WarningRaised(object sender, BuildWarningEventArgs e)
...
             project.AddBuildMessage(MessageSeverity.Warning, message);
         }
     }
 
+    /// <summary>
+    /// Detect markers that require special attention from a customer.
+    /// </summary>
+    /// <param name="message">Raised event.</param>
+    /// <returns>true if marker is detected.</returns>
+    private bool ImmediateMessageRaised(string message) => ImmediateMessageRegex().IsMatch(message);
```
Comment (rainersigwald) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:630]: Naming nit: I'd prefer something like `IsImmediateMessage`; `ImmediateMessageRaised` sounds like an event handler to me.

File: src/MSBuild.UnitTests/TerminalLogger_Tests.cs [hunk 7]
```diff
@@ -229,6 +237,39 @@ public Task PrintBuildSummary_SucceededWithWarnings()
             return Verify(_outputWriter.ToString(), _settings).UniqueForOSPlatform();
         }
 
+        [Fact]
+        public Task PrintImmediateWarningMessage_Succeeded()
+        {
+            InvokeLoggerCallbacksForSimpleProject(succeeded: true, () =>
+            {
+                WarningRaised?.Invoke(_eventSender, MakeWarningEventArgs("[CredentialProvider]"));
```
Comment (rainersigwald) [inline src/MSBuild.UnitTests/TerminalLogger_Tests.cs:245]: Can the example string be an exact match for one of the NuGet strings?

I also considered pulling a resource from the NuGet assemblies but that seems very heavyweight.

**Review by rainersigwald — COMMENTED** [review]
Looking good, just a couple more tweaks!

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 8]
```diff
@@ -586,10 +613,22 @@ private void WarningRaised(object sender, BuildWarningEventArgs e)
                 threadId: e.ThreadId,
                 logOutputProperties: null);
 
+            if (ImmediateMessageRaised(message))
+            {
+                RenderImmediateMessage(message);
+            }
+
             project.AddBuildMessage(MessageSeverity.Warning, message);
```
[the remark this answers is not in the document]
Comment (YuliiaKovalova) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs:621]: If I don't include it in warning messages, the build result will be different - it is reported as "success". 
Is it ok?

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 9]
```diff
@@ -23,8 +27,26 @@ namespace Microsoft.Build.Logging.TerminalLogger;
...
+
+    private const RegexOptions Options = RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.ExplicitCapture;
+
+#if NET7_0_OR_GREATER
+    [GeneratedRegex(ImmediateMessagePattern, Options)]
+    private static partial Regex ImmediateMessageRegex();
+#else
+    private static Regex ImmediateMessageRegex() => immediateMessageRegex;
+
+    private static readonly Regex immediateMessageRegex = new(ImmediateMessagePattern, RegexOptions.Compiled | Options);
```
Comment (ladipro) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:47]: Regex matching on .NET Framework tends to be much slower than on .NET, even with `RegexOptions.Compiled`. For the particular pattern used here I see a pair of `IndexOf` calls being about 2x faster than the regex (on amd64). Please consider keeping the regex only for NET7+.

File: src/MSBuild/TerminalLogger/TerminalLogger.cs [hunk 10]
```diff
@@ -23,8 +27,21 @@ namespace Microsoft.Build.Logging.TerminalLogger;
...
+
+#if NET7_0_OR_GREATER
+    [StringSyntax(StringSyntaxAttribute.Regex)]
+    private const string ImmediateMessagePattern = @"\[CredentialProvider\]|--interactive";
+    private const RegexOptions Options = RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.ExplicitCapture;
+
+    [GeneratedRegex(ImmediateMessagePattern, Options)]
+    private static partial Regex ImmediateMessageRegex();
+#else
+    private readonly string[] _immediateMessageKeywords = { @"\[CredentialProvider\]", "--interactive" };
```
Comment (ladipro) [inline src/MSBuild/TerminalLogger/TerminalLogger.cs:42]: The backslashes are not interpreted as escape markers here, the strings will have literally `\[` in it. Also nit: `static`.

Comment (rainersigwald) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs]: This was correct before: the `\` in this case is a *regex* special character escaping `[`. Without the `\[\]` this collapses to "any character from the character class `[CredntialPov]`", instead of "the literal string `[CredentialProvider]`".

(it would have been valid to do `"\\[CredentialProvider\\]"` instead of `@"\[CredentialProvider\]"`)

Comment (rainersigwald) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs]: Oh wait I'm sorry, @ladipro was right because you switched to `IndexOf`. I'm surprised by the perf results there though, I see Regex being faster all the time (see https://github.com/dotnet/msbuild/pull/9411#discussion_r1392968936)

Comment (ladipro) [reply src/MSBuild/TerminalLogger/TerminalLogger.cs]: I'm trying to understand the different perf results we got. It is quite intriguing.

**Review by rainersigwald — APPROVED** [review]

**Review by ladipro — APPROVED** [review]
Looks great, thank you. From UX perspective I wonder if the output shouldn't contain the name of the project because it looks like we're currently printing just the bare message which is going to land at a random line. It may be mistakenly attributed to the last project that finished building.
cc @baronfel

**Comment by YuliiaKovalova** [comment]
> Looks great, thank you. From UX perspective I wonder if the output shouldn't contain the name of the project because it looks like we're currently printing just the bare message which is going to land at a random line. It may be mistakenly attributed to the last project that finished building. cc @baronfel

I see what you mean, but just for illustration:
The example of output for DeviceFlow
image
and warning message
image

Since it's a part of the Restore target that contains the ProjectName, I am not fully confident we need to include this information in the immediate messages.

**Comment by ladipro** [comment]
I see, it's always restore-only. In that case, please ignore me!

**Comment by YuliiaKovalova** [comment]
> I see, it's always restore-only. In that case, please ignore me!

Let's wait for @baronfel anyway :)

**Comment by baronfel** [comment]
I agree with @YuliiaKovalova's finding here 👍
