### PR TITLE
﻿Fix TerminalLogger assert failure for metaproj files and cached project eval ID

### LINKED ISSUE #13095: Multithreaded build for roslyn crashes in TerminalLogger
### Issue Description

After resolving issue with WPF build which block it from building with the current main msbuild, the Roslyn build still crashes with terminal logger enabled

### Steps to Reproduce

use a patched MSBuild with https://github.com/dotnet/msbuild/pull/12991

```
git clone https://github.com/dotnet/roslyn
dotnet build Roslyn.slnx /mt
```

### Expected Behavior

builds roslyn correctly
(this works with TL disabled)

### Actual Behavior
```
PS C:\Users\janprovaznik\dev\testing\roslyn> ..\..\msbuilds\msb1\artifacts\bin\bootstrap\core\dotnet.exe build .\Roslyn.slnx /mt /bl
Restore complete (31.4s)
  RulesetToEditorconfigConverter net472 win-x86 succeeded (22.6s) → artifacts\bin\RulesetToEditorconfigConverter\Debug\net472\RulesetToEditorconfigConverter.exe
  GenerateAnalyzerNuspec net10.0 succeeded (22.7s) → artifacts\bin\GenerateAnalyzerNuspec\Debug\net10.0\GenerateAnalyzerNuspec.dll
  TestReferenceAssembly netstandard2.0 succeeded (4.8s) → artifacts\bin\TestReferenceAssembly\Debug\netstandard2.0\TestReferenceAssembly.dll
  CSharpSyntaxGenerator netstandard2.0 succeeded (17.5s) → artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll
  Microsoft.Build.Tasks.CodeAnalysis.Sdk net472 succeeded (20.1s) → artifacts\bin\Microsoft.Build.Tasks.CodeAnalysis.Sdk\Debug\net472\Microsoft.Build.Tasks.CodeAnalysis.Sdk.dll
  Metrics net472 win-x86 succeeded (37.6s) → artifacts\bin\Metrics\Debug\net472\Metrics.exe
  Microsoft.CodeAnalysis.PublicApiAnalyzers netstandard2.0 succeeded (39.9s) → artifacts\bin\Microsoft.CodeAnalysis.PublicApiAnalyzers\Debug\netstandard2.0\Microsoft.CodeAnalysis.PublicApiAnalyzers.dll
  Microsoft.CodeAnalysis.Analyzers netstandard2.0 succeeded (44.7s) → artifacts\bin\Microsoft.CodeAnalysis.Analyzers\Debug\netstandard2.0\Microsoft.CodeAnalysis.Analyzers.dll
  Microsoft.CodeAnalysis.ResxSourceGenerator netstandard2.0 succeeded (40.2s) → artifacts\bin\Microsoft.CodeAnalysis.ResxSourceGenerator\Debug\netstandard2.0\Microsoft.CodeAnalysis.ResxSourceGenerator.dll
  Microsoft.CodeAnalysis.BannedApiAnalyzers netstandard2.0 succeeded (45.0s) → artifacts\bin\Microsoft.CodeAnalysis.BannedApiAnalyzers\Debug\netstandard2.0\Microsoft.CodeAnalysis.BannedApiAnalyzers.dll
  Microsoft.CodeAnalysis.AnalyzerUtilities netstandard2.0 succeeded (38.8s) → artifacts\bin\Microsoft.CodeAnalysis.AnalyzerUtilities\Debug\netstandard2.0\Microsoft.CodeAnalysis.AnalyzerUtilities.dll
  Roslyn.Diagnostics.Analyzers netstandard2.0 succeeded (42.0s) → artifacts\bin\Roslyn.Diagnostics.Analyzers\Debug\netstandard2.0\Roslyn.Diagnostics.Analyzers.dll
  Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers netstandard2.0 succeeded (41.6s) → artifacts\bin\Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers\Debug\netstandard2.0\Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.dll
  Text.Analyzers netstandard2.0 succeeded (43.3s) → artifacts\bin\Text.Analyzers\Debug\netstandard2.0\Text.Analyzers.dll
  Microsoft.Build.Tasks.CodeAnalysis net472 succeeded (20.2s) → artifacts\bin\Microsoft.Build.Tasks.CodeAnalysis\Debug\net472\Microsoft.Build.Tasks.CodeAnalysis.dll
  Microsoft.CodeAnalysis.Debugging.Package netstandard2.0 succeeded (7.1s) → artifacts\bin\Microsoft.CodeAnalysis.Debugging.Package\Debug\netstandard2.0\Microsoft.CodeAnalysis.Debugging.Package.dll
  Microsoft.CodeAnalysis.PooledObjects.Package netstandard2.0 succeeded (7.2s) → artifacts\bin\Microsoft.CodeAnalysis.PooledObjects.Package\Debug\netstandard2.0\Microsoft.CodeAnalysis.PooledObjects.Package.dll
  Microsoft.CodeAnalysis.CSharp.BannedApiAnalyzers netstandard2.0 succeeded (9.8s) → artifacts\bin\Microsoft.CodeAnalysis.CSharp.BannedApiAnalyzers\Debug\netstandard2.0\Microsoft.CodeAnalysis.CSharp.BannedApiAnalyzers.dll
  Microsoft.CodeAnalysis netstandard2.0 succeeded (40.3s) → artifacts\bin\Microsoft.CodeAnalysis\Debug\netstandard2.0\Microsoft.CodeAnalysis.dll
  GenerateDocumentationAndConfigFiles net10.0 succeeded (52.0s) → artifacts\bin\GenerateDocumentationAndConfigFiles\Debug\net10.0\GenerateDocumentationAndConfigFiles.dll
  Microsoft.CodeAnalysis.Contracts.Package net8.0 succeeded (9.0s) → artifacts\bin\Microsoft.CodeAnalysis.Contracts.Package\Debug\net8.0\Microsoft.CodeAnalysis.Contracts.Package.dll
  Microsoft.CodeAnalysis.ResxSourceGenerator.VisualBasic netstandard2.0 succeeded (9.4s) → artifacts\bin\Microsoft.CodeAnalysis.ResxSourceGenerator.VisualBasic\Debug\netstandard2.0\Microsoft.CodeAnalysis.ResxSourceGenerator.VisualBasic.dll
  Microsoft.CodeAnalysis.Collections.Package net10.0 succeeded (10.4s) → artifacts\bin\Microsoft.CodeAnalysis.Collections.Package\Debug\net10.0\Microsoft.CodeAnalysis.Collections.Package.dll
  Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp netstandard2.0 succeeded (10.8s) → artifacts\bin\Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp\Debug\netstandard2.0\Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp.dll
  Microsoft.CodeAnalysis net10.0 succeeded (40.1s) → artifacts\bin\Microsoft.CodeAnalysis\Debug\net10.0\Microsoft.CodeAnalysis.dll
  Roslyn.Diagnostics.VisualBasic.Analyzers netstandard2.0                                           CoreCompile (14.5s)
  Microsoft.CodeAnalysis.CodeStyle.UnitTestUtilities net472                                      PrepareForBuild (1.8s)
  Roslyn.Diagnostics.CSharp.Analyzers netstandard2.0                                                CoreCompile (12.7s)
  Microsoft.CodeAnalysis.Features.DiagnosticsTests.Utilities net10.0                      CheckForDuplicateItems (2.5s)
  Test.Utilities net10.0                                                            GenerateBuildDependencyFile (27.4s)
  Microsoft.CodeAnalysis.VisualBasic.BannedApiAnalyzers netstandard2.0                              CoreCompile (21.1s)
  Microsoft.CodeAnalysis.Contracts.Package net10.0                                     ResolveAssemblyReferences (6.3s)
  Text.VisualBasic.Analyzers netstandard2.0                                                          CoreCompile (8.6s)
  Text.CSharp.Analyzers netstandard2.0                                                               CoreCompile (7.5s)
  Microsoft.CodeAnalysis.Workspaces.Test.Utilities net472                              ResolveLockFileReferences (1.9s)
  Microsoft.CodeAnalysis net8.0                                                 CoreGenerateSatelliteAssemblies (41.9s)
  Microsoft.CodeAnalysis.Remote.Workspaces netstandard2.0                                        PrepareForBuild (2.0s)
  Microsoft.CodeAnalysis.VisualBasic netstandard2.0                                  BatchTranslateSourceFromXlf (6.7s)
  Microsoft.CodeAnalysis.Threading.Package netstandard2.0                                            CoreCompile (8.2s)
  Microsoft.CodeAnalysis.PublicApiAnalyzers.CodeFixes netstandard2.0                                 CoreCompile (8.8s)
  Microsoft.CodeAnalysis.Collections.Package netstandard2.0                                          CoreCompile (5.2s)
  Microsoft.CodeAnalysis.CodeStyle netstandard2.0                                    BatchTranslateSourceFromXlf (3.6s)
  Microsoft.CodeAnalysis.CodeStyle.Fixes netstandard2.0                                ResolveLockFileReferences (3.6s)
Process terminated.
Assertion failed.
EvalProjectInfo should have been captured before ProjectStarted
   at Microsoft.Build.Logging.TerminalLogger.ProjectStarted(Object sender, ProjectStartedEventArgs e) in C:\Users\janprovaznik\dev\msbuilds\msb1\src\Build\Logging\TerminalLogger\TerminalLogger.cs:line 725
   at Microsoft.Build.Logging.ReusableLogger.ProjectStartedHandler(Object sender, ProjectStartedEventArgs e) in C:\Users\janprovaznik\dev\msbuilds\msb1\src\Build\Logging\ReusableLogger.cs:line 538
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent) in C:\Users\janprovaznik\dev\msbuilds\msb1\src\Build\BackEnd\Components\Logging\EventSourceSink.cs:line 261
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent, Int32 sinkId) in C:\Users\janprovaznik\dev\msbuilds\msb1\src\Build\BackEnd\Components\Logging\EventSourceSink.cs:line 224
   at Microsoft.Build.BackEnd.Logging.EventRedirectorToSink.Microsoft.Build.Framework.IEventRedirector.ForwardEvent(BuildEventArgs buildEvent) in C:\Users\janprovaznik\dev\msbuilds\msb1\src\Build\BackEnd\Components\Logging\EventRedirectorToSink.cs:line 57
   at Microsoft.Build.BackEnd.Logging.CentralForwardingLogger.EventSource_AnyEventRaised(Object sender, BuildEve(14.8s)b
uildEvent) in C:\Users\janprovaznik\dev\msbuilds\msb1\src\Build\BackEnd\Components\Logging\CentralForwardingLogge(2.1s)i
ne 121                                                                                                          (13.0s)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(BuildEventArgs buildEvent) in C:\Users\janpro(2.8s)\
dev\msbuilds\msb1\src\Build\BackEnd\Components\Logging\EventSourceSink.cs:line 410                              (27.7s)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent) in C:\Users\janprovazni(21.4s)s
builds\msb1\src\Build\BackEnd\Components\Logging\EventSourceSink.cs:line 347                                     (6.6s)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg) in C:\Users\janprov(8.9s)d
ev\msbuilds\msb1\src\Build\BackEnd\Components\Logging\LoggingService.cs:line 1724                                (7.9s)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent) in C:\Users\janprovazni(2.2s)m
sbuilds\msb1\src\Build\BackEnd\Components\Logging\LoggingService.cs:line 1679                                   (42.2s)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent) in C:\Users\janpr(2.3s)k
\dev\msbuilds\msb1\src\Build\BackEnd\Components\Logging\LoggingService.cs:line 1512                              (7.0s)
   at Microsoft.Build.BackEnd.Logging.LoggingService.<StartLoggingEventProcessing>g__LoggingEventProc|155_0() in (8.6s)r
s\janprovaznik\dev\msbuilds\msb1\src\Build\BackEnd\Components\Logging\LoggingService.cs:line 1392                (9.2s)
   at System.Threading.Thread.StartHelper.Callback(Object state)                                                 (5.5s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, (3.9s)
state)                                                                                                           (4.0s)
```
[msbuild.zip](https://github.com/user-attachments/files/24820517/msbuild.zip) binlog

### Analysis

https://github.com/dotnet/msbuild/blob/f5dba4f02a84401e82864c54fc5f3c73e98d8360/src/Build/Logging/TerminalLogger/TerminalLogger.cs#L725

### Versions & Configurations

18.0.4

### PR DESCRIPTION
**Pull request by OvesN**
Fixes #13095

## Context

These metaproj files are never evaluated — they have `EvaluationId = -1`. The TerminalLogger's `Debug.Assert` assumes every `ProjectStarted` has a prior `ProjectEvaluationFinished`, which fails for metaproj files and crashes the build.

Additionally, a pre-existing bug (#12953) causes real projects to lose their evaluation IDs when their `ProjectInstance` is cached (released from memory), and when `BuildResult` packets are sent from worker nodes to the central node without carrying the eval ID.

## Changes Made

**TerminalLogger metaproj fix:**
- `TerminalLogger.cs`: Assert "EvalProjectInfo should have been captured before ProjectStarted"); will not fail now for metaproj files
 
**Evaluation ID fixes (adapted from PR #12946):**
- `BuildRequestConfiguration.cs`: Added `_projectEvaluationId` field that persists through caching + IPC serialization in both `Translate()` and `TranslateForFutureUse()`
- `NodeLoggingContext.cs`: Use `config.ProjectEvaluationId` instead of `config.Project.EvaluationId` (which is inaccessible when cached)
- `BuildResult.cs`: Added `_evaluationId` field with version 2 serialization
- `RequestBuilder.cs`: Populate `result.EvaluationId` at success, exception, and abort paths
- `BuildManager.cs`: Update `config.ProjectEvaluationId` from worker node results

## Testing

**Unit tests**
- `BuildRequestConfiguration_Tests`
- `BuildResult_Tests`

**Integration testing:**
- Verified by building Roslyn and Aspire with Debug bootstrap MSBuild with and without /mt.

## Notes

- The evaluation ID fixes are adapted from PR #12946.

### CODE REVIEW

File: src/Build/BackEnd/Shared/BuildResult.cs [hunk 1]
```diff
@@ -695,6 +711,12 @@ void ITranslatable.Translate(ITranslator translator)
             {
                 translator.TranslateEnum(ref _buildRequestDataFlags, (int)_buildRequestDataFlags);
             }
+
+            // Starting version 2 the _evaluationId field is present.
+            if (_version >= 2)
```
Comment (JanProvaznik) [inline src/Build/BackEnd/Shared/BuildResult.cs:716]: why is this versioned?

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs [hunk 2]
```diff
@@ -725,12 +725,18 @@ private void ProjectStarted(object sender, ProjectStartedEventArgs e)
...
             if (_projectEvaluations.TryGetValue(evalContext, out EvalProjectInfo evalInfo))
             {
                 targetFramework = evalInfo.TargetFramework;
                 runtimeIdentifier = evalInfo.RuntimeIdentifier;
             }
-            System.Diagnostics.Debug.Assert(evalInfo != default, "EvalProjectInfo should have been captured before ProjectStarted");
+
+            // Metaproj files (generated for multi-targeting and solution builds) are never evaluated,
+            // so they won't have a matching ProjectEvaluationFinished event. Only assert for real projects.
+            System.Diagnostics.Debug.Assert(
```
Comment (JanProvaznik) [inline src/Build/Logging/TerminalLogger/TerminalLogger.cs:737]: just so I understand: this is the sufficient fix for the reported issue and the rest is adopting part of #12946 ?

**Review by JanProvaznik — APPROVED** [review]

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs (hunk 2 above)
Comment (OvesN) [reply src/Build/Logging/TerminalLogger/TerminalLogger.cs:737]: Yep, this fix is sufficient.
I tested the Roslyn build in the following ways:

1. Clean build with and without /mt.
2. Incremental build with and without /mt.
3. Incremental build with /m:4 and /m:1.

File: src/Build/BackEnd/Shared/BuildResult.cs (hunk 1 above)
Comment (OvesN) [reply src/Build/BackEnd/Shared/BuildResult.cs:716]: It follows the existing pattern for _buildRequestDataFlag.

File: src/Build/BackEnd/Shared/BuildResult.cs [hunk 3]
```diff
@@ -145,6 +145,11 @@ public class BuildResult : BuildResultBase, INodePacket, IBuildResults
         /// </remarks>
         private BuildRequestDataFlags _buildRequestDataFlags;
 
+        /// <summary>
+        /// The evaluation ID of the project used for this build.
+        /// </summary>
+        private int _evaluationId = BuildEventContext.InvalidEvaluationId;
+
```
[the remark this answers is not in the document]
Comment (OvesN) [reply src/Build/BackEnd/Shared/BuildResult.cs:152]: This is not needed for this fix.

**Review by SimaTian — APPROVED** [review]

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs [hunk 4]
```diff
@@ -725,12 +725,18 @@ private void ProjectStarted(object sender, ProjectStartedEventArgs e)
...
             string? runtimeIdentifier = null;
+            
             if (_projectEvaluations.TryGetValue(evalContext, out EvalProjectInfo evalInfo))
             {
                 targetFramework = evalInfo.TargetFramework;
                 runtimeIdentifier = evalInfo.RuntimeIdentifier;
             }
-            System.Diagnostics.Debug.Assert(evalInfo != default, "EvalProjectInfo should have been captured before ProjectStarted");
+
+            // Metaproj files (generated for multi-targeting and solution builds) are never evaluated,
```
Comment (rainersigwald) [inline src/Build/Logging/TerminalLogger/TerminalLogger.cs]: I don't think this is the right fix because metaproj files do evaluate and raise the `ProjectEvaluationFinished` event:

```
>	Microsoft.Build.Framework.dll!Microsoft.Build.Framework.ProjectEvaluationFinishedEventArgs.ProjectEvaluationFinishedEventArgs(string message, object[] messageArgs) Line 27	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.Logging.LoggingService.LogProjectEvaluationFinished(Microsoft.Build.Framework.BuildEventContext projectEvaluationEventContext, string projectFile, System.Collections.IEnumerable globalProperties, System.Collections.IEnumerable properties, System.Collections.IEnumerable items, Microsoft.Build.Framework.Profiler.ProfilerResult? profilerResult) Line 460	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.Components.Logging.EvaluationLoggingContext.LogProjectEvaluationFinished(System.Collections.IEnumerable globalProperties, System.Collections.IEnumerable properties, System.Collections.IEnumerable items, Microsoft.Build.Framework.Profiler.ProfilerResult? profilerResult) Line 46	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Execution.ProjectPropertyInstance, Microsoft.Build.Execution.ProjectItemInstance, Microsoft.Build.Execution.ProjectMetadataInstance, Microsoft.Build.Execution.ProjectItemDefinitionInstance>.Evaluate(Microsoft.Build.Evaluation.IEvaluatorData<Microsoft.Build.Execution.ProjectPropertyInstance, Microsoft.Build.Execution.ProjectItemInstance, Microsoft.Build.Execution.ProjectMetadataInstance, Microsoft.Build.Execution.ProjectItemDefinitionInstance> data, Microsoft.Build.Evaluation.Project project, Microsoft.Build.Construction.ProjectRootElement root, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, int maxNodeCount, Microsoft.Build.Collections.PropertyDictionary<Microsoft.Build.Execution.ProjectPropertyInstance> environmentProperties, System.Collections.Generic.ICollection<string> propertiesFromCommandLine, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Evaluation.IItemFactory<Microsoft.Build.Execution.ProjectItemInstance, Microsoft.Build.Execution.ProjectItemInstance> itemFactory, Microsoft.Build.Evaluation.IToolsetProvider toolsetProvider, Microsoft.Build.FileSystem.IDirectoryCacheFactory directoryCacheFactory, Microsoft.Build.Evaluation.ProjectRootElementCacheBase projectRootElementCache, Microsoft.Build.Framework.BuildEventContext buildEventContext, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, int submissionId, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext, bool interactive) Line 366	C#
 	Microsoft.Build.dll!Microsoft.Build.Execution.ProjectInstance.Initialize(Microsoft.Build.Construction.ProjectRootElement xml, System.Collections.Generic.IDictionary<string, string> globalProperties, string explicitToolsVersion, string explicitSubToolsetVersion, int visualStudioVersionFromSolution, Microsoft.Build.Execution.BuildParameters buildParameters, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Framework.BuildEventContext buildEventContext, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, int submissionId, Microsoft.Build.Evaluation.ProjectLoadSettings? projectLoadSettings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext, Microsoft.Build.FileSystem.IDirectoryCacheFactory directoryCacheFactory) Line 3275	C#
 	Microsoft.Build.dll!Microsoft.Build.Execution.ProjectInstance.ProjectInstance(Microsoft.Build.Construction.ProjectRootElement xml, System.Collections.Generic.IDictionary<string, string> globalProperties, string toolsVersion, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, int visualStudioVersionFromSolution, Microsoft.Build.Evaluation.ProjectCollection projectCollection, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, int submissionId) Line 637	C#
 	Microsoft.Build.dll!Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(string wrapperProjectToolsVersion, bool explicitToolsVersionSpecified, System.Collections.Generic.List<Microsoft.Build.Construction.ProjectInSolution> projectsInOrder) Line 990	C#
 	Microsoft.Build.dll!Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(string wrapperProjectToolsVersion, bool explicitToolsVersionSpecified) Line 750	C#
 	Microsoft.Build.dll!Microsoft.Build.Construction.SolutionProjectGenerator.Generate() Line 712	C#
 	Microsoft.Build.dll!Microsoft.Build.Construction.SolutionProjectGenerator.Generate(Microsoft.Build.Construction.SolutionFile solution, System.Collections.Generic.IDictionary<string, string> globalProperties, string toolsVersionOverride, Microsoft.Build.Framework.BuildEventContext projectBuildEventContext, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, System.Collections.Generic.IReadOnlyCollection<string> targetNames, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, int submissionId) Line 229	C#
 	Microsoft.Build.dll!Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(string projectFile, System.Collections.Generic.IDictionary<string, string> globalProperties, string toolsVersion, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Framework.BuildEventContext projectBuildEventContext, System.Collections.Generic.IReadOnlyCollection<string> targetNames, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, int submissionId) Line 3003	C#
 	Microsoft.Build.dll!Microsoft.Build.Execution.ProjectInstance.CalculateToolsVersionAndGenerateSolutionWrapper(string projectFile, Microsoft.Build.Execution.BuildParameters buildParameters, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Framework.BuildEventContext projectBuildEventContext, System.Collections.Generic.Dictionary<string, string> globalProperties, bool isExplicitlyLoaded, System.Collections.Generic.IReadOnlyCollection<string> targetNames, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, int submissionId) Line 2707	C#
 	Microsoft.Build.dll!Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(string projectFile, Microsoft.Build.Collections.PropertyDictionary<Microsoft.Build.Execution.ProjectPropertyInstance> globalPropertiesInstances, string toolsVersion, Microsoft.Build.Execution.BuildParameters buildParameters, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Framework.BuildEventContext projectBuildEventContext, bool isExplicitlyLoaded, System.Collections.Generic.IReadOnlyCollection<string> targetNames, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, int submissionId) Line 2671	C#
 	Microsoft.Build.dll!Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(Microsoft.Build.BackEnd.BuildRequestConfiguration config, Microsoft.Build.BackEnd.BuildRequest request) Line 1738	C#
 	Microsoft.Build.dll!Microsoft.Build.Execution.BuildManager.HandleNewRequest(int node, Microsoft.Build.BackEnd.BuildRequestBlocker blocker) Line 2607	C#
```

File: src/Build/BackEnd/Shared/BuildResult.cs (hunk 1 above)
Comment (rainersigwald) [reply src/Build/BackEnd/Shared/BuildResult.cs:716]: Should we be deprecating some of the older versions? That's what the comment suggests

https://github.com/OvesN/msbuild/blob/e8163763277f67f201dbe5553e5ee447f1a70718/src/Build/BackEnd/Shared/BuildResult.cs#L656-L668

@dfederm do you have a sense on `BuildResult` staleness here?

**Review by rainersigwald — COMMENTED** [review]
#13489 should improve the test that flaked out on the current run. I'm not rerunning because I'm not convinced this is the right solution to the problem thouh.

File: src/Build/Logging/TerminalLogger/TerminalLogger.cs (hunk 4 above)
Comment (OvesN) [reply src/Build/Logging/TerminalLogger/TerminalLogger.cs]: The comment I wrote about all metaproj files never being evaluated was wrong. There are actually two kinds of
 metaproj files, and one of them is evaluated.
 
  1. The solution metaproj (.sln.metaproj) is evaluated and has a valid evaluation ID, so the assertion passes.
  2. Per-project metaprojs (.csproj.metaproj, .vbproj.metaproj) are not evaluated and they fail the assertion.
 
 I've fixed the comment

**Comment by OvesN** [comment]
@rainersigwald 
Regarding your comment about deprecating older versions: the comment says "backwards compatible with at least 2
previous releases." We are now on version 2 and have two previous versions, 0 and 1. So I guess we do not need to
deprecate anything.

**Comment by rainersigwald** [comment]
> @rainersigwald Regarding your comment about deprecating older versions: the comment says "backwards compatible with at least 2 previous releases." We are now on version 2 and have two previous versions, 0 and 1. So I guess we do not need to deprecate anything.

I interpreted "releases" there as _MSBuild_ releases, not this specific version that changes rarely. But this is not blocking.

**Comment by rainersigwald** [comment]
Hit rerun after putting up #13546 to hopefully stabilize the test that flaked.
