### PR TITLE
Parallelize Node Spawning

### LINKED ISSUE #7379: Out of Proc Node creation takes too long, very noticeable with many cores.
### Issue Description
Node creation takes a long time to start a 32 core build.  It took ~12s to start up 32 nodes.  An average of 0.375s per node of single threaded time, and blocking other activity from starting in parallel.  This adds up fast as today's machines are easily 16 threads CPU (~5s 16*0.375s).  5s on a 5 mins build isn't a lot, but an incremental build of 15s is a lot of time.

See internal teams thread for SS.

### Steps to Reproduce
Build a large solution with many parallelizable projects.  I used binlog and viewer with tracing to see the start time behavior.

Thanks.

### PR DESCRIPTION
**Pull request by yuehuang010**
Fixes #7379

### Context
MSBuild builds with Out Of Proc nodes which requires spawning processes.  Each node takes time to spawn and is serial.  This can lead to a slow start on machine with many cores.  

### Changes Made
Parallelize Node spawn.
Changed interface in `INodeProvider` to specify number of nodes to be created and let particular implementation of `INodeProvider` decide if it does it concurrently. This way the scope of thread safety is limited and manageable.

I tried to keep current logic as much in tact as possible. For example old logic allowed to call `INodeManager` to spawn multiple in-proc nodes but then it fails anyway. That does not make much sense to me, and if we want to address it please let me know.

### Testing
Various manual testing including scenarios with TaskHost.

### Notes
When nodereuse and nodes are still running the difference is not significant about 20ms per node as connecting to existing processes is quite fast.
In cold scenarios, either /nr=false or nodes have had terminated after 15 minutes of idling, the difference is 150ms per node.
So on my 24 cores machine, incremental building of orchard code in cold scenario were about 20% faster, in hot scenarios (reusing still running nodes) about 4% faster.

### CODE REVIEW

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 1]
```diff
@@ -2602,17 +2602,29 @@ private void PerformSchedulingActions(IEnumerable<ScheduleResponse> responses)
...
                         for (int i = 0; i < response.NumberOfNodesToCreate; i++)
                         {
-                            NodeInfo createdNode = _nodeManager.CreateNode(GetNodeConfiguration(), response.RequiredNodeType);
+                            if (response.RequiredNodeType != NodeAffinity.OutOfProc || _buildParameters.EnableNodeReuse)
+                            {
+                                newNodes[i] = _nodeManager.CreateNode(nodeConfig, response.RequiredNodeType);
+                            }
 
-                            if (createdNode != null)
+                            if (newNodes[i] != null)
```
Comment (Forgind) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:2624]: Can we move any of this into the parallel part? Make it a helper function?

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 2]
```diff
@@ -275,7 +275,10 @@ protected NodeContext GetNode(string msbuildLocation, string commandLineArgs, in
 
                 // Create the node process
                 Process msbuildProcess = LaunchNode(msbuildLocation, commandLineArgs);
-                _processesToIgnore.Add(GetProcessesToIgnoreKey(hostHandshake, msbuildProcess.Id));
+                if (_componentHost.BuildParameters.EnableNodeReuse)
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:278]: Is this important for the change?

**Review by Forgind — APPROVED** [review]

**Comment by Forgind** [comment]
I'm wondering about making this work for situations with node reuse. Maybe worth trying to connect to some, and if you run out of nodes to connect to, make the rest in parallel?

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 2 above)
Comment (yuehuang010) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:278]: I couldn't prove it, but document says Hashset is not threadsafe.

File: src/Build/BackEnd/BuildManager/BuildManager.cs (hunk 1 above)
Comment (yuehuang010) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:2624]: No need.  The results are just added to final data structure and is thus fast.  Trying to make this parallel safe is more refactoring and risk.

**Comment by yuehuang010** [comment]
> I'm wondering about making this work for situations with node reuse. Maybe worth trying to connect to some, and if you run out of nodes to connect to, make the rest in parallel?

Ideally, Yes.  However, that would require more refactoring than I am comfortable with.  Node reuse when "reusing" is already fast.    Plus, the risk and reward is lower.

**Comment by Forgind** [comment]
Note: earlier work:
https://github.com/dotnet/msbuild/pull/4905

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 3]
```diff
@@ -275,7 +275,10 @@ protected NodeContext GetNode(string msbuildLocation, string commandLineArgs, in
...
+                {
+                    _processesToIgnore.Add(GetProcessesToIgnoreKey(hostHandshake, msbuildProcess.Id));
```
[the remark this answers is not in the document]
Comment (yuehuang010) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:280]: > Please fix those few concurrency bugs I have mentioned in comments.
> 
> Why is this change isolated to `/nr:false` path only? Since `nodeReuse` is on by default, we are missing a big customer segment with this optimization.

I have tried those changes and hit threading issues, so I have scoped down the feature to /nr:false.  Our development environment has /nr:false in the build scripts so to us, it is the default.  @Forgind PR #4905 is more comprehensive to address nodeReuse.

**Review by rokonec — APPROVED** [review]

**Comment by rokonec** [comment]
It was reworked and it now support also `node reuse` scenarios.

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 4]
```diff
@@ -2602,27 +2602,22 @@ private void PerformSchedulingActions(IEnumerable<ScheduleResponse> responses)
                         break;
 
                     case ScheduleActionType.CreateNode:
-                        var newNodes = new List<NodeInfo>();
+                        IList<NodeInfo> newNodes = _nodeManager.CreateNodes(GetNodeConfiguration(), response.RequiredNodeType, response.NumberOfNodesToCreate);
 
-                        for (int i = 0; i < response.NumberOfNodesToCreate; i++)
+                        if (newNodes?.Count != response.NumberOfNodesToCreate || newNodes.Any(n => n == null))
```
Comment (yuehuang010) [inline src/Build/BackEnd/BuildManager/BuildManager.cs:2607]: Could there be a case where multiple requester ask for max nodes, but only a subset would spawn?

Comment (rokonec) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:2607]: In previous code, when it was called in for loop, if any of loop iteration had failed to acquire node, whole build have had failed on `BuildAbortedException`. From this I have drawn logical conclusion that if not all nodes has been crated new code is supposed to failed same way.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 5]
```diff
@@ -323,9 +382,9 @@ protected NodeContext GetNode(string msbuildLocation, string commandLineArgs, in
         /// <param name="msbuildLocation"></param>
         /// <returns>
         /// Item 1 is the name of the process being searched for.
-        /// Item 2 is the list of processes themselves.
+        /// Item 2 is the ConcurrentQueue of ordered processes themselves.
         /// </returns>
-        private (string expectedProcessName, List<Process> nodeProcesses) GetPossibleRunningNodes(string msbuildLocation = null)
+        private (string expectedProcessName, ConcurrentQueue<Process> nodeProcesses) GetPossibleRunningNodes(string msbuildLocation = null)
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:387]: Nit:
If I counted right, this is used once as a queue and once as a list. Since you're sorting it as a list anyway, return a list and make it into a queue in the case you need a queue? Otherwise you're turning a list into a queue into a list for no reason.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 6]
```diff
@@ -206,115 +218,162 @@ protected NodeContext GetNode(string msbuildLocation, string commandLineArgs, in
...
-                CommunicationsUtilities.Trace("Attempting to connect to each existing {1} process in turn to establish node {0}...", nodeId, runningNodesTuple.expectedProcessName);
-                foreach (Process nodeProcess in runningNodesTuple.processes)
+            return nodeContexts.ToList();
+
+            bool TryReuseAnyFromPossibleRunningNodes(int nodeId)
+            {
+                while (possibleRunningNodes != null && possibleRunningNodes.TryDequeue(out var nodeToReuse))
                 {
-                    if (nodeProcess.Id == Process.GetCurrentProcess().Id)
+                    CommunicationsUtilities.Trace("Try to connect to each existing {0} process candidate to establish node {1}...", expectedProcessName, nodeId);
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:263]:
```suggestion
                    CommunicationsUtilities.Trace("Trying to connect to existing {0} process to establish node {1}...", expectedProcessName, nodeId);
```

Though this seems a bit verbose. Previously, it announced that it was trying to connect to a process once for all processes. This means it's announcing it for all the wrong processes in addition to the reasonable guesses that fail and the right guesses. That's a lot.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 7]
```diff
@@ -206,115 +218,162 @@ protected NodeContext GetNode(string msbuildLocation, string commandLineArgs, in
                 }
             }
 
+            // Get all process of possible running node processes for reuse and put them into ConcurrentQueue.
+            // Processes from this queue will be concurrently consumed by TryReusePossibleRunningNodes while
+            //    trying to connect to them and reuse them. When queue is empty, no process to reuse left
+            //    new node process will be started.
+            string expectedProcessName = null;
+            ConcurrentQueue<Process> possibleRunningNodes = null;
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: Is there any reason you're using ConcurrentQueue as opposed to some other concurrent data structure? It has tighter constraints that ConcurrentBag, so I'd imagine that's faster? (Haven't tested that.)

**Review by Forgind — APPROVED** [review]
I didn't see anything that looked like a probable race, though those are always tricky to find.

File: src/Build/BackEnd/BuildManager/BuildManager.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (rokonec) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:2607]: It is not supposed to be null on current code state. It is there however to cover possible future deviation/bug in code.

File: src/Build/BackEnd/BuildManager/BuildManager.cs [hunk 8]
```diff
@@ -2602,27 +2602,22 @@ private void PerformSchedulingActions(IEnumerable<ScheduleResponse> responses)
...
+                        }
 
-                                throw new BuildAbortedException(ResourceUtilities.FormatResourceStringStripCodeAndKeyword("UnableToCreateNode", response.RequiredNodeType.ToString("G")));
-                            }
+                        foreach (var node in newNodes)
+                        {
+                            _noNodesActiveEvent.Reset();
+                            _activeNodes.Add(node.NodeId);
                         }
+                        ErrorUtilities.VerifyThrow(_activeNodes.Count != 0, "Still 0 nodes after asking for a new node.  Build cannot proceed.");
```
[the remark this answers is not in the document]
Comment (rokonec) [reply src/Build/BackEnd/BuildManager/BuildManager.cs:2620]: I was strictly following logic of former code. Check former line 2616. There is a test even though couple of lines above we add to the tested collection so it is guaranteed that test be always true.
In my code this line will could possible throw if `NumberOfNodesToCreate` == 0. 
But it is nonsense. I will remove it.

**Review by rokonec — APPROVED** [review]

File: src/Build/BackEnd/Components/Communications/NodeManager.cs [hunk 9]
```diff
@@ -92,32 +86,31 @@ private NodeManager()
...
             // We will prefer to make nodes on the "closest" providers first; in-proc, then
             // out-of-proc, then remote.
             // When we support distributed build, we will also consider the remote provider.
-            int nodeId = InvalidNodeId;
-            if ((nodeAffinity == NodeAffinity.Any || nodeAffinity == NodeAffinity.InProc) && !_componentHost.BuildParameters.DisableInProcNode)
+            List<NodeInfo> nodes = new();
+            if ((nodeAffinity == NodeAffinity.Any || nodeAffinity == NodeAffinity.InProc) && !_componentHost!.BuildParameters.DisableInProcNode)
             {
-                nodeId = AttemptCreateNode(_inProcNodeProvider, configuration);
+                nodes.AddRange(AttemptCreateNode(_inProcNodeProvider!, configuration, numberOfNodesToCreate));
```
[the remark this answers is not in the document]
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeManager.cs:99]: Yes. In current implementation it does. However I wanted to make this method to be agnostic to the current rule `only-on-inproc-node`.  Since `AttemptCreateNode` uses passed `INodeProvider` which now supports multiple node creation, this code seems to be both readable and future proof.

File: src/Build/BackEnd/Components/Communications/NodeManager.cs [hunk 10]
```diff
@@ -176,7 +169,7 @@ public void InitializeComponent(IBuildComponentHost host)
         {
             ErrorUtilities.VerifyThrow(_componentHost == null, "NodeManager already initialized.");
             ErrorUtilities.VerifyThrow(host != null, "We can't create a NodeManager with a null componentHost");
-            _componentHost = host;
+            _componentHost = host!;
```
[the remark this answers is not in the document]
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeManager.cs:172]: For one reason or another, I was getting compiler warning here:
image
Seem to me like bug in analyzer. However, until we remove condition in:
image
I can't take analyzer results seriously.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs [hunk 11]
```diff
@@ -73,44 +74,56 @@ internal static Handshake GetHandshake(bool enableNodeReuse, bool enableLowPrior
...
+                    .ToList();
+            }
+
+            throw new BuildAbortedException(ResourceUtilities.FormatResourceStringStripCodeAndKeyword("CouldNotConnectToMSBuildExe", ComponentHost.BuildParameters.NodeExeLocation));
+
+            void NodeContextCreated(NodeContext context)
+            {
+                NodeInfo nodeInfo = new NodeInfo(context.NodeId, ProviderType);
+
+                _nodeContexts[context.NodeId] = context;
```
[the remark this answers is not in the document]
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs:119]: After we fix some info code like ThrowInternalError and anotate it I would like to revisit those classes and turn them into nullable enable. 
For now with limited scope of invoking `NodeContextCreatedDelegate`, just one place, I believe null check here would not make code any better. Maybe in future with those !! operators which hinder readability less.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 7 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: I thought about it, I liked Q better as it preserver order of creation which could help with troubleshooting. Since there is no `Concurrent ordered collection` I am using `ConcurrentQueue` whenever I need ordered concurrent collection.
In this context when we are spending 100ms spawning process the difference between queue and bag would be insignificant. I have not measured it yet but I expect it will be < 1ns.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 6 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:263]: This is good catch. The verbosity is not an issue here as it will be just one log per process candidate.
I have changed it to include more information;  specifically process id and its arguments.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 5 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:387]: Good point. Changed.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs [hunk 12]
```diff
@@ -522,30 +522,35 @@ internal bool CreateNode(HandshakeOptions hostContext, INodePacketFactory factor
...
-                                        (int)hostContext,
-                                        this,
-                                        new Handshake(hostContext),
-                                        NodeContextTerminated
-                                    );
-
-            if (context != null)
-            {
-                _nodeContexts[hostContext] = context;
+            int nodeId = (int)hostContext;
```
[the remark this answers is not in the document]
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcTaskHost.cs:525]: Commented...

File: src/Build/BackEnd/Components/Communications/NodeManager.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Build/BackEnd/Components/Communications/NodeManager.cs:172]: Gotcha and fair 😄

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 6 above)
Comment (Forgind) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs]: I was more worried about claiming that you're trying to connect to processes explicitly excluded when you're really not, as that might be a bit confusing. Not too big a deal to me, though, since it'd presumably be mostly just us looking at this.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 7 above)
Comment (Forgind) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: I'm thinking about the limit as number of processors approaches infinity. It should get progressively harder to use the queue concurrently, which isn't true for a bag. No computer actually has infinite processors of course, but people doing C++ seem to have a lot. Might be reasonable?

Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: When in doubt I call DotNetBenchmark for a help. Surprisingly, ConcurrentQueue is faster that ConcurrentBag.
image
Result of my benchmark is consitent with this article: https://minidump.net/performance-best-practices-in-c-b85a47bdd93a

Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: Also please note that for 1000 items (1000 processes which match our process name) it is ~1ns while connecting to ONE node is 20ms which  is 0.005% :-)

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 6 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs]: It is valid point, on the other hand listing all candidates (even those already rejected) might have some debug value.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 7 above)
Comment (Forgind) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: What code did you use for your benchmark? I was partially surprised because I'd run my own benchmark and got very different results:
| Method | NumCases |         Mean |      Error |       StdDev |       Median |     Gen 0 |     Gen 1 |     Gen 2 |   Allocated |
|------- |--------- |-------------:|-----------:|-------------:|-------------:|----------:|----------:|----------:|------------:|
|    Bag |      100 |     17.26 us |   0.336 us |     0.588 us |     17.14 us |    0.7629 |    0.3662 |         - |     4.67 KB |
|  Queue |      100 |     13.44 us |   0.150 us |     0.133 us |     13.43 us |    0.8545 |         - |         - |     5.23 KB |
|    Bag |    10000 |    262.59 us |   8.581 us |    24.758 us |    253.76 us |   31.7383 |   15.6250 |    2.9297 |   155.39 KB |
|  Queue |    10000 |    692.55 us |  13.848 us |    39.510 us |    679.86 us |   23.4375 |    5.8594 |         - |   134.14 KB |
|    Bag |  1000000 | 12,165.84 us | 335.746 us |   989.955 us | 12,124.86 us | 1359.3750 | 1281.2500 | 1046.8750 | 16686.98 KB |
|  Queue |  1000000 | 40,737.60 us | 808.214 us | 1,857.007 us | 40,433.64 us |  666.6667 |  666.6667 |  666.6667 |   8215.2 KB |

The article mentioned that ConcurrentBag is optimized for the process that uses something (normally) being the same as the one that added it to the bag. My code essentially looked like this:
```C#
ConcurrentContainer<int> container = new();
Parallel.For(0, NumCases, i =>
{
    container.Add(i);
});
foreach (int i in container);
```

Comment (Forgind) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: Most noteworthy, I think, is that for larger numbers of threads adding, the Bag starts to be much faster than the queue, but its allocations also get to be much larger.

Comment (Forgind) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: (To be clear, I think it's reasonable/fine to use a queue; I'm just curious why your numbers would be so unexpected.)

Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: But this is not how we use it in this code. Your benchmark have concurrent producers and one thread consumer. Our usage is one thread producer - get processes -  and multi thread competing consumers.
Try to measure it with something like this:
```
ConcurrentContainer<int> container = new();
for (int i = 0; i < NumCases; i++)
   container.Add(i);
Parallel.For(0, NumCases, _ =>
{
    container.TryTake(out _);
});
```

Comment (Forgind) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:226]: I added one little tweak to your version: rather than initializing a concurrent collection then adding to it, I initialized a normal List, added to it, then used the concurrent constructor taking a list.

| Method | NumCases |         Mean |        Error |       StdDev |     Gen 0 |     Gen 1 |     Gen 2 |   Allocated |
|------- |--------- |-------------:|-------------:|-------------:|----------:|----------:|----------:|------------:|
|    Bag |      100 |     23.07 us |     0.455 us |     0.447 us |    0.8545 |    0.4272 |         - |     5.29 KB |
|  Queue |      100 |     13.97 us |     0.278 us |     0.285 us |    0.8240 |         - |         - |     5.02 KB |
|    Bag |    10000 |  1,467.20 us |    41.087 us |   119.854 us |   42.9688 |   21.4844 |    3.9063 |   266.05 KB |
|  Queue |    10000 |    966.75 us |    26.234 us |    77.350 us |   41.0156 |   41.0156 |   41.0156 |   260.71 KB |
|    Bag |  1000000 | 86,002.80 us | 1,717.738 us | 4,403.219 us | 1800.0000 | 1800.0000 | 1800.0000 |  16397.6 KB |
|  Queue |  1000000 | 81,010.31 us | 2,224.135 us | 6,200.000 us |  625.0000 |  625.0000 |  625.0000 | 16398.53 KB |

What I think is most interesting here is that Queue trounces Bag for small input sizes, but they approach the same for larger inputs. I'd wager that if I went for even NumCases == 10,000,000, Bag would be strictly more performant than Queue. That said, if someone has millions of MSBuild processes running on one computer all at once, I think we have a more fundamental problem...

File: src/Build/BackEnd/Components/Communications/NodeManager.cs [hunk 13]
```diff
@@ -92,32 +86,31 @@ private NodeManager()
...
         /// <returns>A NodeInfo describing the node created, or null if none could be created.</returns>
-        public NodeInfo CreateNode(NodeConfiguration configuration, NodeAffinity nodeAffinity)
+        public IList<NodeInfo> CreateNodes(NodeConfiguration configuration, NodeAffinity nodeAffinity, int numberOfNodesToCreate)
         {
             // We will prefer to make nodes on the "closest" providers first; in-proc, then
             // out-of-proc, then remote.
             // When we support distributed build, we will also consider the remote provider.
-            int nodeId = InvalidNodeId;
-            if ((nodeAffinity == NodeAffinity.Any || nodeAffinity == NodeAffinity.InProc) && !_componentHost.BuildParameters.DisableInProcNode)
+            List<NodeInfo> nodes = new();
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Communications/NodeManager.cs:96]: nit:

```suggestion
            List<NodeInfo> nodes = new(numberOfNodesToCreate);
```

?

File: src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs [hunk 14]
```diff
@@ -184,13 +185,34 @@ public void ShutdownAllNodes()
...
+            var nodes = new List<NodeInfo>(numberOfNodesToCreate);
+
+            for (int i = 0; i < numberOfNodesToCreate; i++)
+            {
+                int nodeId = nextNodeId + i;
+
+                NodeInfo nodeInfo = new(nodeId, ProviderType);
+                if (!CreateNode(nodeId, factory, configurationFactory(nodeInfo)))
+                {
+                    // If it fails let it return what we have crated so far to so caller can somehow acquire missing nodes.
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs:199]:
```suggestion
                    // If it fails let it return what we have created so far so caller can somehow acquire missing nodes.
```

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs [hunk 15]
```diff
@@ -132,12 +144,7 @@ public void SendData(int nodeId, INodePacket packet)
         public void ShutdownConnectedNodes(bool enableReuse)
         {
             // Send the build completion message to the nodes, causing them to shutdown or reset.
-            List<NodeContext> contextsToShutDown;
-
-            lock (_nodeContexts)
-            {
-                contextsToShutDown = new List<NodeContext>(_nodeContexts.Values);
-            }
+            var contextsToShutDown = new List<NodeContext>(_nodeContexts.Values);
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs:147]: Does this introduce a possible race between a call to ShutdownConnectedNodes and a call to create new nodes? Though it doesn't look like adding to `_nodeContexts` was locked before when adding so I guess that's not new.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 16]
```diff
@@ -206,115 +218,169 @@ protected NodeContext GetNode(string msbuildLocation, string commandLineArgs, in
...
-                    if (_processesToIgnore.Contains(nodeLookupKey))
+                    string nodeLookupKey = GetProcessesToIgnoreKey(hostHandshake, nodeToReuse.Id);
+                    if (_processesToIgnore.ContainsKey(nodeLookupKey))
                     {
                         continue;
                     }
 
                     // We don't need to check this again
-                    _processesToIgnore.Add(nodeLookupKey);
+                    _processesToIgnore.TryAdd(nodeLookupKey, default);
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:284]: Should we assert that this returns `true`?

**Review by rainersigwald — APPROVED** [review]

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs (hunk 15 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs:147]: It is hard to find all possible race conditions here along with their probablility and consequences. I have found at least one race conditions: `ShutdownConnectedNodes` is in call stack of CTRL+C console cancellation so it can indeed happen anytime.

However, these changes did not it any worse than it was before. It is slightly better as  `_nodeContexts` is `ConcurentDictionary` now so it is guaranteed to be in consistent state when race condition happen, as oppose to former code when we could have read Values while it was in middle of adding.

I recommend to NOT invest more into this race condition.

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs (hunk 16 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:284]: Do you mean `Debug.Assert` or `VerifyThrow`? 
This should never happen if there is no bug in our code as that `ConcurerentQueue` guarantee only one thread will handle particular process which makes `nodeLookupKey` unique and we test key absence ay line 278. Since we use underlying `ConcurrentDictionary` as `ConcurrentHashSet` the `TryAdd` actually has same meaning as `ISet.Add`.
I believe original decision to use `HashSet` for `_processesToIgnore` was not to assure uniqueness but for algorithmically fast lookup.

File: src/Build/BackEnd/Components/Communications/INodeProvider.cs [hunk 17]
```diff
@@ -1,7 +1,8 @@
 ﻿// Copyright (c) Microsoft. All rights reserved.
 // Licensed under the MIT license. See LICENSE file in the project root for full license information.
 
-#nullable disable
+using System;
+using System.Collections.Generic;
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/INodeProvider.cs:5]:
```suggestion
```

File: src/Build/BackEnd/Components/Communications/NodeManager.cs [hunk 18]
```diff
@@ -5,11 +5,10 @@
 using System.Collections.Generic;
 using Microsoft.Build.Shared;
 using Microsoft.Build.Execution;
+using System.Threading;
 using System.Diagnostics;
 using System.Linq;
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/NodeManager.cs:10]:
```suggestion
using System.Linq;

#nullable disable
```

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs [hunk 19]
```diff
@@ -1,9 +1,11 @@
 ﻿// Copyright (c) Microsoft. All rights reserved.
 // Licensed under the MIT license. See LICENSE file in the project root for full license information.
 
+using System;
+using System.Collections.Concurrent;
 using System.Collections.Generic;
 using System.Diagnostics;
-
+using System.Linq;
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs:8]:
```suggestion
```

File: src/Build/BackEnd/Components/Communications/TaskHostNodeManager.cs [hunk 20]
```diff
@@ -2,6 +2,7 @@
 // Licensed under the MIT license. See LICENSE file in the project root for full license information.
 
 using System;
+using System.Collections.Generic;
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/TaskHostNodeManager.cs:5]:
```suggestion
```

**Review by Forgind — COMMENTED** [review]
My merge was bad. Sorry for the spam.

File: src/Build/BackEnd/Components/Communications/NodeManager.cs [hunk 21]
```diff
@@ -352,7 +349,7 @@ NodeConfiguration AcquiredNodeConfigurationFactory(NodeInfo nodeInfo)
 
         public IEnumerable<Process> GetProcesses()
         {
-            return _outOfProcNodeProvider.GetProcesses();
+            return _outOfProcNodeProvider?.GetProcesses() ?? new List<Process>(0);
```
Comment (yuehuang010) [inline src/Build/BackEnd/Components/Communications/NodeManager.cs:352]: IEnumerable.Empty<Process>()

File: src/Build/BackEnd/Components/Communications/NodeManager.cs [hunk 22]
```diff
@@ -307,52 +299,57 @@ private void RemoveNodeFromMapping(int nodeId)
...
+                var config = nodeConfiguration.Clone();
+                config.NodeId = nodeInfo.NodeId;
+                return config;
+            }
         }
 
         public IEnumerable<Process> GetProcesses()
         {
-            return _outOfProcNodeProvider.GetProcesses();
+            return _outOfProcNodeProvider?.GetProcesses() ?? new List<Process>(0);
```
Comment (Forgind) [inline src/Build/BackEnd/Components/Communications/NodeManager.cs:352]:
```suggestion
            return _outOfProcNodeProvider?.GetProcesses() ?? IEnumerable.Empty();
```

File: src/Build/BackEnd/Components/Communications/NodeManager.cs (hunk 21 above)
Comment (rokonec) [reply src/Build/BackEnd/Components/Communications/NodeManager.cs]: It is dead path of code. _outOfProcNodeProvider is supposed to be always set in all codepaths calling this method. However, because of `nullable` we need to eliminate warning by `?`. I would actually recommend ` return _outOfProcNodeProvider?.GetProcesses()!`

File: src/Build/BackEnd/Components/Communications/NodeManager.cs [hunk 23]
```diff
@@ -307,52 +299,57 @@ private void RemoveNodeFromMapping(int nodeId)
...
+                var config = nodeConfiguration.Clone();
+                config.NodeId = nodeInfo.NodeId;
+                return config;
+            }
         }
 
         public IEnumerable<Process> GetProcesses()
         {
-            return _outOfProcNodeProvider.GetProcesses();
+            return _outOfProcNodeProvider?.GetProcesses() ?? IEnumerable.Empty();
```
Comment (rokonec) [inline src/Build/BackEnd/Components/Communications/NodeManager.cs:352]:
```suggestion
            return _outOfProcNodeProvider?.GetProcesses()!;
```

**Comment by yuehuang010** [comment]
Yes, I am super happy!
