### PR TITLE
Fix solution-based graph builds when non 'well-known' project types are used

### LINKED ISSUE #9375: [Bug]: Hang and/or MSB0001 when building `terminal` repo with `/graph`
### Issue Description

```
Microsoft.Build.Framework.InternalErrorException
  HResult=0x80131500
  Message=MSB0001: Internal MSBuild Error: nodes should include solution projects
  Source=Microsoft.Build
  StackTrace:
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)

 	Microsoft.Build.dll!Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(string message, System.Exception innerException, object[] args)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Graph.GraphBuilder.AddEdgesFromSolution(System.Collections.Generic.IReadOnlyDictionary<Microsoft.Build.BackEnd.ConfigurationMetadata, Microsoft.Build.Graph.ParsedProject> allParsedProjects, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyCollection<string>> solutionDependencies, Microsoft.Build.Graph.GraphBuilder.GraphEdges edges)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Graph.GraphBuilder.AddEdges(System.Collections.Generic.Dictionary<Microsoft.Build.BackEnd.ConfigurationMetadata, Microsoft.Build.Graph.ParsedProject> allParsedProjects)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Graph.GraphBuilder.BuildGraph()	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Graph.ProjectGraph.ProjectGraph(System.Collections.Generic.IEnumerable<Microsoft.Build.Graph.ProjectGraphEntryPoint> entryPoints, Microsoft.Build.Evaluation.ProjectCollection projectCollection, Microsoft.Build.Graph.ProjectGraph.ProjectInstanceFactoryFunc projectInstanceFactory, int degreeOfParallelism, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Execution.BuildManager.ExecuteGraphBuildScheduler(Microsoft.Build.Graph.GraphBuildSubmission submission)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Execution.BuildManager.ExecuteSubmission.AnonymousMethod__0()	Unknown
```

### Steps to Reproduce

1. Clone `https://github.com/johnterickson/terminal/commit/1f7018c5071fcb5bc3d86870c21c8cfe65540a91`
2. `tools\razzle.cmd`
3. `bcz`

### Expected Behavior

Build 1) succeeds or 2) fails with useful info

### Actual Behavior

MsBuild.exe hangs

### Analysis

I hooked up a debugger to capture the above stack trace.

### Versions & Configurations

using msbuild version '17.7.2.37605' from 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64'

### PR DESCRIPTION
**Pull request by dfederm**
Fixes #9375

Previously, only projects which were `SolutionProjectType.KnownToBeMSBuildFormat` (handful of project type guids) would be considered. This would cause some projects in a sln to not be in the graph at all.

This change removes that check and in general brings solution-based graph construction slightly more aligned with how non-graph builds construct the metaproj (`SolutionProjectGenerator`). My ideal scenario would be that the graph would just directly call into `SolutionProjectGenerator` to create a metaproj and then use that as the entry point into the graph construction, but we would need to teach the metaproj the p2p protocol used for graph which is a bit more work. Maybe one day though :)

Change details:
* Removed the check for `SolutionProjectType.KnownToBeMSBuildFormat`
* Replaced the check for non-zero `ProjectConfigurations` with a call to `SolutionFile.IsBuildableProject`, which does that and also filters out `SolutionProjectType.SolutionFolder`
* Replaced the check for `projectConfiguration.IncludeInBuild` and `SolutionFile.ProjectShouldBuild` with a call to `SolutionProjectGenerator.WouldProjectBuild`, which does both those checks.

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]
> My ideal scenario would be that the graph would just directly call into `SolutionProjectGenerator` to create a metaproj and then use that as the entry point into the graph construction, but we would need to teach the metaproj the p2p protocol used for graph which is a bit more work.

Agreed on both the ideal behavior and the decision to not do it right now.

File: src/Build/Graph/GraphBuilder.cs [hunk 1]
```diff
@@ -307,41 +305,39 @@ private static void AddEdgesFromSolution(IReadOnlyDictionary<ConfigurationMetada
...
-                if (project.ProjectConfigurations.Count == 0)
+                if (!SolutionFile.IsBuildableProject(project))
                 {
                     continue;
                 }
 
                 ProjectConfigurationInSolution projectConfiguration = SelectProjectConfiguration(currentSolutionConfiguration, project.ProjectConfigurations);
 
-                if (projectConfiguration.IncludeInBuild)
+                if (!SolutionProjectGenerator.WouldProjectBuild(solution, currentSolutionConfiguration.FullName, project, projectConfiguration))
```
Comment (Forgind) [inline src/Build/Graph/GraphBuilder.cs:320]: I actually like using this method for slnf support. I don't think you currently support that anyway, but it'd be a nice future scenario to consider.

**Review by Forgind — APPROVED** [review]

**Review by rokonec — APPROVED** [review]

File: src/Build/Graph/GraphBuilder.cs (hunk 1 above)
Comment (dfederm) [reply src/Build/Graph/GraphBuilder.cs:320]: Yep, I'll look into slnf in the future.
