### PR TITLE
issue-12415 increase stack size

### LINKED ISSUE #12415: Stack overflow on DrainPacketQueue thread from NodeProviderOutOfProc
### Issue Description

When attempting to test diagnostic tests using a private build of the runtime, I encounter a stack overflow upon a nuget restore in the process of building the SymbolTestApp debuggee. 

### Steps to Reproduce

Follow the steps outlined here:
https://github.com/dotnet/diagnostics/blob/main/documentation/privatebuildtesting.md

Then run  ```dotnet test --no-build --logger "console;verbosity=detailed" SOS\SOS.UnitTests\SOS.UnitTests.csproj --filter "SOS.StackAndOtherTests"```

### Expected Behavior

SymbolTestApp debugee builds

### Actual Behavior

[SOS.StackAndOtherTests.projectk.cli.10.0.0-preview.7.25351.106.log](https://github.com/user-attachments/files/21974186/SOS.StackAndOtherTests.projectk.cli.10.0.0-preview.7.25351.106.log)

### Analysis

The following stack trace points to a stack overflow in a thread created in NodeProviderOutOfProcBase. By looking at the TEB, as well as by reading the code, we see that threads created in this context are allocated a stack size of 64 KB. If in my private build of the runtime I increase the minimum stack size to 0x30000, the stack overflow issue is resolved. 
https://github.com/dotnet/msbuild/blob/98fe1859f5bef8f4add8a31cc09e13ce08391a73/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L684

Image
Image
Image

This issue may have been caused by https://github.com/dotnet/msbuild/commit/4c1d0950a2b5bfb15e63c74d9ec620e487e05cc2; we should consider increasing the stack size allocated for these threads.

### Versions & Configurations

MSBuild version 17.15.0-preview-25306-09+a2c72650e for .NET Framework
17.15.0.30609

dotnet: 10.0.100-preview.7.25351.106
OS/Arch: Windows x64

### PR DESCRIPTION
**Pull request by SimaTian**
Fixes #12415

### Context
During one of our recent optimization runs we reduced stack size of the DrainPacketQueue times.
While this is fine in a normal scenario, it sometimes results in a StackOverflow during debugging or performance runs.

### Changes Made
Increased the stack size.

### Notes
@Erarndt is planning to refactor this away in the near future so I hope this is a sufficient hotfix for the interim.
This doesn't affect production, only custom builds.

### CODE REVIEW

**Review by MichalPavlik — APPROVED** [review]

File: src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs [hunk 1]
```diff
@@ -681,7 +681,7 @@ public NodeContext(
                 _packetQueueDrainDelayCancellation = new CancellationTokenSource();
 
                 // specify the smallest stack size - 64kb
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs]: Update comment with an explanation of how the number was derived.

**Review by JanProvaznik — APPROVED** [review]
