### PR TITLE
Set BuildParameters.StartupDirectory upon build command

### LINKED ISSUE #8094: MSBuildStartupDirectory wrong values for .NET 7 dotnet build (blocker for Sonar analysis)
### Issue Description

When analyzing a project using SonarScanner for .NET (integration tool for [SonarQube](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube)), and we use the .NET 7 runtime the analysis fails ([related issue](https://github.com/SonarSource/sonar-scanner-msbuild/issues/1333)).

After digging around we found that the problem lies with `MSBuildStartupDirectory` property that we use (see [here](https://github.com/SonarSource/sonar-scanner-msbuild/blob/5.8.0.52797/src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.ImportBefore.targets#L12)) to get the absolute path from which `dotnet build` command or MSBuild is called. 

The issue can be summarized as follows:

If one builds two consecutive projects with .NET7, the value of `MSBuildStartupDirectory` keeps the value of the first project that was built.

### Steps to Reproduce

Clone https://github.com/mary-georgiou-sonarsource/net7Repro
```bash
cd Project1
dotnet build /target:DisplayMessages
cd ../Project2
dotnet build /target:DisplayMessages
```
### Expected Behavior
`MSBuildStartupDirectory` should have as a value the path of the root folder from which is invoked.

### Actual Behavior
After building `Project1` the output is:
```
  MSBuildStartupDirectory = Dir\Project1
  Project File Name = Project1.csproj
```

After building `Project2`:
```
  MSBuildStartupDirectory = Dir\Project1
  Project File Name = Project2.csproj
```
Notice that the `MSBuildStartupDirectory` is not updated to `Dir\Project2`. 

I did the same test, but with targetting `dotnet 6.0.305`, and the behavior, in that case, was correct - `MSBuildStartupDirectory` had the correct value.

### Versions & Configurations
* MSBuild version 17.4.0-preview-22470-08+6521b1591
* dotnet 7.0.100-rc.2.22477.23
* OS:  Microsoft Windows 10 Pro 10.0.19044 Build 19044

This is a blocker for the .NET project analysis with SonarQube.
It seems that a workaround is to use `msbuild /t:rebuild -v:d`.
Is there a workaround for the dotnet CLI?

Thanks a lot!

### PR DESCRIPTION
**Pull request by rokonec**
Fixes #8094

### Context
Server have cached `BuildParameters.StartupDirectory` in static variable. When consequent builds starts from different directory, this value will have incorrect value of previous builds.
`BuildParameters.StartupDirectory` was also used for creating build-in `MSBuildStartupDirectory` property.

### Changes Made
Set `BuildParameters.StartupDirectory` when `ServerNodeBuildCommand` is received by server.

### Testing
After fixes, cant repro issues from #8094

### Notes
Changes can possible affect only server behavior.

### CODE REVIEW

File: src/Build/BackEnd/BuildManager/BuildParameters.cs [hunk 1]
```diff
@@ -630,8 +630,16 @@ public bool ShutdownInProcNodeOnBuildFinish
 
         /// <summary>
         /// Gets the startup directory.
+        /// It is current directory from which MSBuild command line was recently invoked.
+        /// It is communicated to working nodes as part NodeConfiguration deserialization once node manager acquire particular node.
```
Comment (rainersigwald) [inline src/Build/BackEnd/BuildManager/BuildParameters.cs:634]:
```suggestion
        /// It is communicated to working nodes as part of NodeConfiguration deserialization once the node manager acquires a particular node.
```

**Review by rainersigwald — COMMENTED** [review]
Could you write a regression test?

**Review by Forgind — APPROVED** [review]

**Comment by rokonec** [comment]
@rainersigwald  
> Culd you write a regression test?

Good point. I wrote the regression test. It is failing when line `BuildParameters.StartupDirectory = command.StartupDirectory;` is commented out - otherwise passing.

**Review by rainersigwald — APPROVED** [review]

**Review by AR-May — APPROVED** [review]
