### PR TITLE
Permit comments and trailing commas in solution filter files

### LINKED ISSUE #6317: Allow trailing commas in solution filters
Have a slnf with trailing comma and try to restore, you get the following error:

```
Solution file error MSB5025: Json in solution filter file "path\to\filter.slnf" is incorrectly formatted.
```

See https://github.com/dotnet/aspnetcore/pull/31438

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #6317

We previously added support for building solution filter files. With that support, we did not allow them to contain lists of projects with a trailing comma or comments. These are both permitted by VS, so this PR updates our handling of solution filter files to permit building with trailing commas or comments.

Also adds a test.

### CODE REVIEW

File: src/Build/Construction/Solution/SolutionFile.cs [hunk 1]
```diff
@@ -415,7 +415,7 @@ internal static string ParseSolutionFromSolutionFilter(string solutionFilterFile
         {
             try
             {
-                JsonDocument text = JsonDocument.Parse(File.ReadAllText(solutionFilterFile));
+                JsonDocument text = JsonDocument.Parse(File.ReadAllText(solutionFilterFile), new JsonDocumentOptions() { AllowTrailingCommas = true, CommentHandling = JsonCommentHandling.Skip});
```
Comment (rainersigwald) [inline src/Build/Construction/Solution/SolutionFile.cs:418]: I'd go ahead and create a variable for `JsonDocumentOptions` so that you can comment that it should match the VS behavior.

**Review by rainersigwald — APPROVED** [review]
LGTM with an added comment.

**Review by BenVillalobos — APPROVED** [review]
