### PR TITLE
Make the cancelation can be executed before the task is done

### LINKED ISSUE #11018: Flaky test - Microsoft.Build.Tasks.UnitTests.DownloadFile_Tests.CanBeCanceled
### Context

Based on the History it fails about once a day in our PR queue: https://dev.azure.com/dnceng-public/public/_build/results?buildId=875750&view=ms.vss-test-web.build-test-results-tab&runId=22853194&resultId=106411&paneView=history

```
Shouldly.ShouldAssertException : task.Result\r\n    should be\r\nFalse\r\n    but was\r\nTrue
```

```
at Microsoft.Build.Tasks.UnitTests.DownloadFile_Tests.CanBeCanceled() in D:\a\1\s\src\Tasks.UnitTests\DownloadFile_Tests.cs:line 52
```

### PR DESCRIPTION
**Pull request by GangWang01**
Fixes #11018

### Context
Test result `Shouldly.ShouldAssertException : task.Result\r\n    should be\r\nFalse\r\n    but was\r\nTrue` indicates that the task is done quickly before the cancelation is executed, though the test cancels it right after it is started. 
 
### Changes Made
Make a fake stream that provides a single character A~Z per a couple of milliseconds infinitely without high memory cost as the content of http response message and increase the task timeout a little so that the cancellation can be executed.

### Testing
N/A

### CODE REVIEW

File: src/Tasks.UnitTests/DownloadFile_Tests.cs [hunk 1]
```diff
@@ -37,7 +37,7 @@ public void CanBeCanceled()
                     DestinationFolder = new TaskItem(folder.Path),
                     HttpMessageHandler = new MockHttpMessageHandler((message, token) => new HttpResponseMessage(HttpStatusCode.OK)
                     {
-                        Content = new StringContent(new String('!', 10000000)),
+                        Content = new StringContent(new String('!', 0xfffffff)),
```
[the remark this answers is not in the document]
Comment (JanKrivanek) [reply src/Tasks.UnitTests/DownloadFile_Tests.cs]: The idea is not to require extreme resources for the test to proceed, but rather create a custom implementation of content, that would behave as if it'd be indefinite, but rather than being backed by real memory, it would just keep returning artifical data.

Lm know if code sample would be helpful here to clarify.

**Review by SimaTian — DISMISSED** [review]

File: src/Tasks.UnitTests/DownloadFile_Tests.cs [hunk 2]
```diff
@@ -47,7 +47,7 @@ public void CanBeCanceled()
 
                 downloadFile.Cancel();
 
-                task.Wait(TimeSpan.FromSeconds(1)).ShouldBeTrue();
+                task.Wait(TimeSpan.FromSeconds(1500)).ShouldBeTrue();
```
Comment (SimaTian) [inline src/Tasks.UnitTests/DownloadFile_Tests.cs:50]: Do we want to wait here for almost half of an hour?
What is supposed to happen here please?

Comment (GangWang01) [reply src/Tasks.UnitTests/DownloadFile_Tests.cs]: Oh, that was a miss. It should be Milliseconds.

**Review by SimaTian — APPROVED** [review]

File: src/Tasks.UnitTests/DownloadFile_Tests.cs [hunk 3]
```diff
@@ -401,4 +401,38 @@ protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage reques
...
+
+        public override bool CanRead => true;
+        public override bool CanSeek => true;
+        public override bool CanWrite => false;
+        public override long Length => long.MaxValue;
+        public override long Position { get; set; }
+
+        public override int Read(byte[] buffer, int offset, int count)
+        {
+            buffer[Position % count] = (byte)('A' + Position % 26);
```
Comment (JanKrivanek) [inline src/Tasks.UnitTests/DownloadFile_Tests.cs:424]: Please comment what is this doing and why (especially why it doesn't write at requested offset).

Should it just be?
```
// Writes next char in alphabet into the begining of requested destination
buffer[offset] = (byte)('A' + Position % 26);
...
```

**Review by JanKrivanek — APPROVED** [review]
Looks good!

Please just make sure the code is understandable to anyone without context as well.

File: src/Tasks.UnitTests/DownloadFile_Tests.cs (hunk 3 above)
Comment (SimaTian) [reply src/Tasks.UnitTests/DownloadFile_Tests.cs:424]: it doesn't do that though. It keeps internal position and ignores both offset and count, though count only partially (it uses count to check for boundaries)
so overall it will work in this case, but the returned data is kind of weird. 
But we don't care about the data so for the test alone it's fine-ish, but comment would be appreciated.

**Review by maridematte — APPROVED** [review]
