### PR TITLE
Warnings-as-errors fail BuildSubmission results

### LINKED ISSUE #5837: dotnet build fails, but exit code is still 0
Example code: https://github.com/aaron-tyler-ds/-MSB3245

We have a chunk of code where we're forcing several msbuild warnings to be promoted to errors. We're seeing that this inconsistently causes `dotnet build` to return a exit code of 0 even though the build failed. I've distilled an example down to the repo mentioned at the start of this issue.

Example output. Note that the MSB3245 hit shows up as an error, and the summary view correctly lists 1 error, but the process exit code was still 0.
```
C:\repos\MSB3277\src\exe>dotnet build
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\repos\MSB3277\src\classlib1\classlib1.csproj (in 124 ms).
  Restored C:\repos\MSB3277\src\classlib2\classlib2.csproj (in 124 ms).
  Restored C:\repos\MSB3277\src\classlib3\classlib3.csproj (in 124 ms).
  Restored C:\repos\MSB3277\src\exe\exe.csproj (in 124 ms).
  classlib1 -> C:\repos\MSB3277\src\classlib1\bin\Debug\net47\classlib1.dll
  classlib2 -> C:\repos\MSB3277\src\classlib2\bin\Debug\net47\classlib2.dll
  classlib3 -> C:\repos\MSB3277\src\classlib3\bin\Debug\net47\classlib3.dll
C:\Program Files\dotnet\sdk\3.1.403\Microsoft.Common.CurrentVersion.targets(2084,5): error MSB3245: Could not resolve this reference. Could not locate the assembly "FooBar.Baz". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\repos\MSB3277\src\exe\exe.csproj]
  exe -> C:\repos\MSB3277\src\exe\bin\Debug\net47\exe.exe

Build succeeded.

C:\Program Files\dotnet\sdk\3.1.403\Microsoft.Common.CurrentVersion.targets(2084,5): error MSB3245: Could not resolve this reference. Could not locate the assembly "FooBar.Baz". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\repos\MSB3277\src\exe\exe.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.06

C:\repos\MSB3277\src\exe>echo %errorlevel%
0
```
Interestingly, when this project doesn't have `ProjectReferences` to other projects this occurs much less frequently.

The nonzero exit code breaks our automated build process. We've also seen other versions of this, where the process exit code is 1 but there are no errors listed, however I don't have a consistent repro of this behavior but it feels related.

### PR DESCRIPTION
**Pull request by rainersigwald**
Fix #5837 by moving the promotion of warnings to build failures to the `BuildSubmission` level instead of doing it in `BuildManager` (where the result change happened at `EndBuild()` time and thus wasn't visible when checking the result after the submission completed:

https://github.com/dotnet/msbuild/blob/c70d520b5b8df990f651f0d00cd186a68cb277c6/src/MSBuild/XMake.cs#L1256-L1268

### CODE REVIEW

**Review by ladipro — APPROVED** [review]
Looks good!

**Review by jeffkl — APPROVED** [review]

File: src/MSBuild.UnitTests/XMake_Tests.cs [hunk 1]
```diff
@@ -2215,6 +2215,26 @@ public void BinaryLogContainsImportedFiles()
...
+
+  <Target Name=""IssueWarning"">
+    <Warning Text=""Warning!"" />
+  </Target>
+  
+</Project>");
+
+            TransientTestProjectWithFiles testProject = testEnvironment.CreateTestProjectWithFiles(projectContents);
+
+            string output = RunnerUtilities.ExecMSBuild($"\"{testProject.ProjectFile}\" -warnaserror", out bool success, _output);
```
Comment (Forgind) [inline src/MSBuild.UnitTests/XMake_Tests.cs:2233]: nit:
```suggestion
            RunnerUtilities.ExecMSBuild($"\"{testProject.ProjectFile}\" -warnaserror", out bool success, _output);
```

File: src/Build/BackEnd/BuildManager/BuildSubmission.cs [hunk 2]
```diff
@@ -198,6 +198,13 @@ private void CheckForCompletion()
                 bool hasCompleted = (Interlocked.Exchange(ref _completionInvoked, 1) == 1);
                 if (!hasCompleted)
                 {
+                    // Did this submission have warnings elevated to errors? If so, mark it as
+                    // failed even though it succeeded (with warnings--but they're errors).
+                    if (((IBuildComponentHost)BuildManager).LoggingService.HasBuildSubmissionLoggedErrors(BuildResult.SubmissionId))
```
Comment (Forgind) [inline src/Build/BackEnd/BuildManager/BuildSubmission.cs:203]: Check for understanding:
The build is "completed" only after _completionEvent is set, so this is called before any build displays whether it has been completed. _completionInvoked is initially set to 0, so if the build has completed, checked via line 196, then it checks if we already knew the build was completed with the Interlocked.Exchange check, and if we hadn't already done completion-related things, we trigger them by setting _completionEvent. This check to see if we had logged errors without failing comes immediately before that, so before any BuildSubmission can be marked complete, it has to check whether it has logged any errors (or warnings converted to errors), hence fixing the bug. Is that right?

**Review by Forgind — APPROVED** [review]

File: src/Build/BackEnd/BuildManager/BuildSubmission.cs (hunk 2 above)
Comment (rainersigwald) [reply src/Build/BackEnd/BuildManager/BuildSubmission.cs:203]: To be a bit pedantic, you say "build" several times when it would be more correct to say "BuildSubmission". You can have multiple submissions in a single Begin/EndBuild pair, and that's done in practice in, e.g., the VS solution build--so that all of the different projects share project state across a VS build operation, but have their own Submissions (and so the project system can know when each project individually finishes and schedule the ones that depend on it).

**Comment by roaladje** [comment]
Hi, which dotnet cli version this should be taken into effect?
Thanks!

**Comment by rainersigwald** [comment]
@roaladje .NET SDK 5.0.200 and higher should have it.

**Comment by roaladje** [comment]
> @roaladje .NET SDK 5.0.200 and higher should have it.

Thanks! works!
