### PR TITLE
Removing dead code unit tests and BinFmt enablement

### LINKED ISSUE #8925: [BinFmt] Rework/Remove unit tests using BinaryFormatter
### Background 
 #6215
 Similar (and can be taken together with) https://github.com/dotnet/msbuild/issues/8924
 This subitem is focused on unit tests calling using BinaryFormatter:
 * Build.UnitTests - testing deserializing exceptions
 * Framework.UnitTests - testing deserialization of EventArgs, AssemblyNameEx, CopyOnWriteDictionary
 * Removing `EnableUnsafeBinaryFormatterSerialization` requried bacause of the above unit tests - https://github.com/dotnet/msbuild/blob/main/Directory.Build.props#L46-L52
 
Since this is non-shipping code, it's not a priority. However it should be easy to get rid of those and hence make usages of `BinaryFormatter` in our code base scope to the necessary places (e.g. `GenerateResource` task)`

### Suggested approach
Unit tests testing exceptions and EventArgs serialization should be moved to the new serialization mechanisms for those (https://github.com/dotnet/msbuild/issues/8786, https://github.com/dotnet/msbuild/pull/8917), or delete if duplicate with unittests introduced as part of those new serialization mechanisms, or removed if serializing other types (as those should not currently use BinaryFormatter for de/serialization).

### PR DESCRIPTION
**Pull request by JanKrivanek**
Fixes #8925

### Context
Following types serialization is no more facilitated by BinFmt - so removing associated unit tests:
* `InvalidProjectFileException` - all `BuildExceptionBase` exceptions tested via [`TestSerializationOfBuildExceptions`](https://github.com/dotnet/msbuild/blob/0cf89d3b27af71d0e065e4c69ee030cfe26b90c5/src/Build.UnitTests/BackEnd/BinaryTranslator_Tests.cs#L259); plus `InvalidProjectFileException` has it's own test: [`TestInvalidProjectFileException_NestedWithStack`](https://github.com/dotnet/msbuild/blob/0cf89d3b27af71d0e065e4c69ee030cfe26b90c5/src/Build.UnitTests/BackEnd/BinaryTranslator_Tests.cs#L282)
* `LoggerException` - same as above
* `ProjectStartedEventArgs` - serialized via translatable only
* `AssemblyName_Ex` - serialized via translatable only. The edited test file already contained tests for both types of serialization
* `CopyOnWriteDictionary` - not custom serialized on any codepath (possibly only via `TranslateDictionary` taking `IDictionary`)

### Changes Made
Appart from removing serialization tests of above mentioned types - removed the `EnableUnsafeBinaryFormatterSerialization` which was needed just because of those tests

### CODE REVIEW

**Comment by JanKrivanek** [comment]
@rokonec - can you have a look on fail of `Build_WithCustomBuildArgs_NetCore`? 

```
System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application.
```

I thought this should have been caught - correct?

**Comment by JanKrivanek** [comment]
> @rokonec - can you have a look on fail of `Build_WithCustomBuildArgs_NetCore`?
> 
> ```
> System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application.
> ```
> 
> I thought this should have been caught - correct?

Discussed offline - this is actually a wrong test (as it explicitly opts out from the checking functionality but do not assert on the BinFmt exception)

**Review by YuliiaKovalova — APPROVED** [review]

File: src/Build.UnitTests/BackEnd/TaskHostFactory_Tests.cs [hunk 1]
```diff
@@ -61,10 +61,21 @@ public void TaskNodesDieAfterBuild()
             }
         }
 
-        [Theory]
+        [DotNetOnlyTheory]
+        [InlineData(false)]
+        // [InlineData(true)] <-- explicitly opting out on core will lead to node crash
+        public void VariousParameterTypesCanBeTransmittedToAndReceivedFromTaskHost_NetCore(
```
Comment (rokonec) [inline src/Build.UnitTests/BackEnd/TaskHostFactory_Tests.cs:67]: NIT: Is it still Theory with just one InlineData

**Review by rokonec — APPROVED** [review]

File: src/Build.UnitTests/BackEnd/TaskHostFactory_Tests.cs (hunk 1 above)
Comment (JanKrivanek) [reply src/Build.UnitTests/BackEnd/TaskHostFactory_Tests.cs:67]: Good point.
I wanted to preserve the argument (ond overall the same signature as for the FulFw test) to make it explicit that we do not want to test the legacy behavior for core (to prevent anyone from attempting to reverse add-it).
