### PR TITLE
Cache Embedded Resources during compilation task

### LINKED ISSUE #10644: [Bug]: Deleted embedded resources dont cause rebuild
### Issue Description

`dotnet build` does not detect deleted EmbeddedResources.

### Steps to Reproduce

1. Download example project from https://github.com/innominateAtWork/NoRebuildWhenDeleteEmbeddedResource
2. `dotnet run` it outputs all files included as EmbeddedResources in MyApp.csproj and their content
3. Change the text in File1.txt
4. `dotnet run` the project rebuilds and includes the updated text
5.  Delete File1.txt
6. `dotnet run` the project does NOT rebuild the run looks identical to the prior run

### Expected Behavior

MyApp rebuilds because an EmbeddedResources has been deleted.

### Actual Behavior

MyApp does NOT rebuild.

### Analysis

_No response_

### Versions & Configurations

MSBuild version 17.11.3+0c8610977 for .NET
17.11.3.35201

### PR DESCRIPTION
**Pull request by JaynieBai**
Fixes #10644 and [#5334 ](https://github.com/dotnet/msbuild/issues/5334)

### Context
Fast up-to-date check with SDK project doesn't see new embedded resources!

### Changes Made
Add @(_CoreCompileResourceInputs) to CoreCompileCache item, to include them in the cache file which gets
included in the CoreCompile target.

### Testing
EmbeddedResourcesFileCompileCache()

### Notes
See https://github.com/dotnet/project-system/issues/5794 for more details.

### CODE REVIEW

**Comment by YuliiaKovalova** [comment]
@JanKrivanek  please help with this test failure

File: src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs [hunk 1]
```diff
@@ -1656,5 +1659,73 @@ private void SetEnvironmentForErrorLocations(ErrorLocations errorLocations, Erro
                 }
             }
         }
+
+        [DotNetOnlyFact("The netfx bootstrap layout created with 'dotnet build' is incomplete")]
```
Comment (JanKrivanek) [inline src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs:1663]: Is this still true?
What happens with the test when run for core?

**Review by JanKrivanek — APPROVED** [review]

**Review by SimaTian — APPROVED** [review]

File: src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs (hunk 1 above)
Comment (JaynieBai) [reply src/Build.UnitTests/ProjectCache/ProjectCacheTests.cs:1663]: Yes, the case failed with error 
_C:\Users\VssAdministrator\AppData\Local\Temp\ic12eptb.spp\MSBuildTemp\Temporaryd3b90dac326b4ce7bfb136f3617deafb\app.csproj : error MSB4246: SDK Resolver folder exists but without an SDK Resolver DLL or manifest file. This may indicate a corrupt or invalid installation of MSBuild. SDK resolver path: D:\a\1\s\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver\r\nDone Building Project_
