### PR TITLE
Issue8273 corrupt nu get cache

### LINKED ISSUE #8273: Usage of hard or symbolic linking leads to NuGet cache corruption
### Issue Description

MSBuild can use hard or symbolic links to avoid excessive file copies on disk. It is a good method to speed-up builds but at the same time, it is very easy to silently corrupt the NuGet cache. 
I have seen that this issue has been mentioned several times already, but it was never explained how and when exactly the NuGet cache gets corrupted:

Related issues:
- https://github.com/dotnet/msbuild/issues/1407
- https://github.com/dotnet/msbuild/issues/3788
- https://github.com/dotnet/msbuild/issues/7014
- https://github.com/NuGet/Home/issues/12047

### Steps to Reproduce

1. Build an executable project with hard or symbolic links enabled
2. Update the version of referenced NuGet package
3. Build the application again, but this time, without using hard/symbolic links.
MSBuild will try to update dependencies in the application's output folder. Sadly, instead of replacing existing links, it replaces actual files in NuGet cache (thus corrupting it).

- hard-links
```
dotnet nuget locals --clear all
dotnet new console
dotnet add package newtonsoft.json -v 13.0.1
dotnet build /p:CreateHardLinksForCopyLocalIfPossible=true
dotnet add package newtonsoft.json -v 13.0.2
dotnet build
```

- symbolic-links
```
dotnet nuget locals --clear all
dotnet new console
dotnet add package newtonsoft.json -v 13.0.1
dotnet build /p:CreateSymbolicLinksForCopyLocalIfPossible=true
dotnet add package newtonsoft.json -v 13.0.2
dotnet build
```

In both cases file `newtonsoft.json\13.0.1\lib\netstandard2.0\Newtonsoft.Json.dll` is silently replaced with `newtonsoft.json\13.0.2\lib\net6.0\Newtonsoft.Json.dll`:

### Expected Behavior

Files in the NuGet cache remain untouched.

### Actual Behavior

Files in a NuGet package are silently replaced with files from another version.

### Analysis

Both Windows and Linux systems are affected, also it doesn't matter whether hard or symbolic links are used. The problem is that `File.Copy` operation, instead of replacing the link, replaces the file that the link is linking to. To safely replace a link with a different file or link, `File.Delete` needs to be called first. Unfortunately, MSBuild calls [File.Delete](https://github.com/dotnet/msbuild/blob/a6f6699d1f70bf79db82030938d2c5e52d1e4d2e/src/Tasks/Copy.cs#L355-L360) only when the usage of hard or symbolic links is requested. When the build doesn't use hard or symbolic links, then the `File.Delete` is not called.

### PR DESCRIPTION
**Pull request by manfred-brands**
Fixes #8273 

### Context
Prevent overwriting the source of a hard/symbolic link.

### Changes Made
Always delete the destination file (unless readonly and OverwriteReadOnlyFiles is false)

### Testing
Added unit test.

### CODE REVIEW

**Comment by Forgind** [comment]
I opened https://github.com/dotnet/runtime/issues/80832

Jozkee labeled it 'bug', so I'm guessing this is a runtime bug rather than an MSBuild bug. He also noted that File.Move does not have the same issue. People using MSBuild's Copy often don't care whether the source file exists afterwards, but we can't guarantee that, so I don't think that helps, unfortunately.

We're still talking internally about whether we want to:
1. Take this
2. Close this in favor of the runtime fixing it
3. Take this but consider reverting it if the runtime changes File.Copy's behavior
4. Possible other option?

What happens on .NET Framework (and older .NET Core) may be an important question, but I haven't tested that yet.

Sorry we're being a bit slow; I just wanted to give you something of an update 🙂

File: src/Tasks/Copy.cs [hunk 1]
```diff
@@ -324,41 +329,28 @@ private void LogDiagnostic(string message, params object[] messageArgs)
                 Log.LogMessage(MessageImportance.Normal, FileComment, sourceFilePath, destinationFilePath);
 
                 File.Copy(sourceFileState.Name, destinationFileState.Name, true);
```
Comment (marcin-krystianc) [inline src/Tasks/Copy.cs:331]: Given that the destination is always deleted, I think it would be a good idea to set the `overwrite` flag to `false` to protect us from accidental overwrites.

Comment (manfred-brands) [reply src/Tasks/Copy.cs:331]: Yes, it is probably better to fail in case someone gets in between than overwriting a link. I will update the PR.

**Comment by Forgind** [comment]
Ping @rokonec

**Comment by marcin-krystianc** [comment]
> It looks like runtime isn't planning to change anything in the immediate future.
> 
> We're thinking we will likely take this, but our primary concern is performance. @rokonec volunteered to take a quick look into that to see if he can find anything problematic. Additionally, would you mind putting this behind a [change wave](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/ChangeWaves.md)? That will turn it on by default for all users but provide a way for users to opt out should they hit perf problems.

FWIW, I've run some benchmarks (building a large solution, with and without a change from this PR), and here are my conclusions:
- When building on Windows, the variant with forced `FileUtilities.DeleteNoThrow` is actually faster (2m 25s vs 2m 35s). Unfortunately, I cannot share the tested solution here as it contains IP. I attribute this difference to AntiVirus software as I suspect that it handles file deletes and file overwrites differently.
- On Linux I didn't notice any real difference, in both cases, the build time was around 4 minutes:
```
Case 1 (forced `FileUtilities.DeleteNoThrow`)
Time Elapsed 00:03:59.28
Time Elapsed 00:03:58.44
Time Elapsed 00:04:01.78
Time Elapsed 00:03:57.04
Time Elapsed 00:04:02.73

Case 2:
Time Elapsed 00:03:59.87
Time Elapsed 00:03:56.23
Time Elapsed 00:03:58.41
Time Elapsed 00:03:58.95
Time Elapsed 00:04:01.58
```
Tested solution: 
[LargeAppWithPrivatePackagesCentralisedNGBVRemoved.zip](https://github.com/dotnet/msbuild/files/10897827/LargeAppWithPrivatePackagesCentralisedNGBVRemoved.zip)
Test command: 
- `cd ~/LargeAppWithPrivatePackagesCentralisedNGBVRemoved/solution$` 
- `echo "" >> Directory.Build.props && ~/dotnet/dotnet build -clp:summary --no-restore /bl /p:UseLinks=false`

File: src/Tasks/Copy.cs [hunk 2]
```diff
@@ -273,7 +271,14 @@ private void LogDiagnostic(string message, params object[] messageArgs)
             if (OverwriteReadOnlyFiles)
             {
                 MakeFileWriteable(destinationFileState, true);
-                destinationFileExists = destinationFileState.FileExists;
+            }
+
+            // If the destination file is a hard or symbolic link, File.Copy would overwrite the source.
+            // To prevent this, we need to delete the existing entry before we Copy or create a link.
+            // We could try to figure out if the file is a link, but I can't think of a reason to not simply delete it always.
+            if (destinationFileState.FileExists && !destinationFileState.IsReadOnly)
```
Comment (rokonec) [inline src/Tasks/Copy.cs:279]: This should be under ChangeWave to be able to deal with unexpected bugs

**Review by rokonec — APPROVED** [review]
I have spent some time to measure it and although it is very slightly slower, it is, IMO, acceptable.
I went away and fixed comments I have raised in this review.
Good job.

**Review by rokonec — APPROVED** [review]
I have spent some time to measure it and although it is very slightly slower, it is, IMO, acceptable. It took less then 0.1 % on my tests.
I went away and created some minor suggestions...
Good job.

File: src/Tasks/Copy.cs (hunk 1 above)
Comment (rokonec) [reply src/Tasks/Copy.cs:331]: I do not believe it is necessary. Sometimes logic might change to not delete it, or new Copy task argument will be introduced, or some weird concurrent logic is relaying with last win. I would recommend to keep it as is, but if you decide to change it, it has to go under same ChangeWave or same conditions as deleting files.

**Comment by manfred-brands** [comment]
@rokonec I have applied your changes and rebased the branch on current main branch.

File: src/Tasks/Copy.cs [hunk 3]
```diff
@@ -269,7 +267,14 @@ private void LogDiagnostic(string message, params object[] messageArgs)
             if (OverwriteReadOnlyFiles)
             {
                 MakeFileWriteable(destinationFileState, true);
-                destinationFileExists = destinationFileState.FileExists;
+            }
+
+            // If the destination file is a hard or symbolic link, File.Copy would overwrite the source.
+            // To prevent this, we need to delete the existing entry before we Copy or create a link.
+            // We could try to figure out if the file is a link, but I can't think of a reason to not simply delete it always.
+            if (ChangeWaves.AreFeaturesEnabled(ChangeWaves.Wave17_6) && destinationFileState.FileExists && !destinationFileState.IsReadOnly)
```
Comment (Forgind) [inline src/Tasks/Copy.cs:275]: Should we also take into account OverwriteReadOnlyFiles and also delete them in that case?

**Review by Forgind — APPROVED** [review]
Thanks!

File: src/Tasks/Copy.cs (hunk 3 above)
Comment (manfred-brands) [reply src/Tasks/Copy.cs:275]: if `OverwriteReadOnlyFiles ` is set, the file is made writable and hence deleted here.

Comment (Forgind) [reply src/Tasks/Copy.cs:275]: ...and now I see it 6 lines up. Stupid question, thanks!
