### PR TITLE
Log before unregistering Fixes #9455

### LINKED ISSUE #9455: [Bug]: error MSB4017 is not shown consistently when the internal logger exception occurs.
### Issue Description

The MSB4017 error is not consistently shown when a logger fails.

### Steps to Reproduce

1. Update the BuildStartedHandler of ParallelConsoleLogger such that it thows an exception. For example, add a throw in [that line](https://github.com/dotnet/msbuild/blob/7b37a280a13c01bbaeeb39b9c018a5ac7a728898/src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs#L242). 
2. Run a build of some project. Console app will do. You will see the message along with details: stack trace and exception message.
```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
This is an unhandled exception from a logger -- PLEASE OPEN A BUG AGAINST THE LOGGER OWNER.
```
3. Remove the previous code change and update instead the ProjectStartedHandler of ParallelConsoleLogger with some throw ([this line](https://github.com/dotnet/msbuild/blob/7b37a280a13c01bbaeeb39b9c018a5ac7a728898/src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs#L585)). 
4. Run build again. You will see only
```
MSBuild version 17.9.0-dev-23574-01+f4b2350ac for .NET Framework
Build started 11/24/2023 3:59:10 PM.
```
### 

### Expected Behavior

I expect to see the error MSB4017 for any logger failure.

### Actual Behavior

No error MSB4017 in the second build. The log does not indicate anything about what happened and is confusing.

### Analysis

Here is the place where the error was considered benign, and the exception is not thrown up further: https://github.com/dotnet/msbuild/blob/7b37a280a13c01bbaeeb39b9c018a5ac7a728898/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L854

Since customers may write their own logs, including ones that throw exceptions during events handlers, I would suggest address all exceptions that the loggers throw and, in all times, report the logger failure. 

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #9455

### Context
If we crash very early—like in the midst of setting up the ProjectLoggingContext—we have all the machinery set up to log information like that the build started, but then we unregister the relevant handlers before we actually log that we'd failed.

### Changes Made
Do not unregister handlers until shutdown

### Testing
I tested with the repro from #9455, and it now looks like this:
```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
MSBUILD : error MSB4017:     Exception of type 'System.Exception' was thrown.
MSBUILD : error MSB4017:        at Microsoft.Build.BackEnd.Logging.ParallelConsoleLogger.ProjectStartedHandler(Object s
ender, ProjectStartedEventArgs e) in C:\GitHub\msbuild\src\Build\Logging\ParallelLogger\ParallelConsoleLogger.cs:line 5
86
MSBUILD : error MSB4017:    at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.ProjectStartedHandler(Object
 sender, ProjectStartedEventArgs e) in C:\GitHub\msbuild\src\Build\Definition\ProjectCollection.cs:line 2342
MSBUILD : error MSB4017:    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseProjectStartedEvent(Object sender,
ProjectStartedEventArgs buildEvent) in C:\GitHub\msbuild\src\Build\BackEnd\Components\Logging\EventSourceSink.cs:line 5
33
```

(with a full stack trace).

Notice that it finds the real exception—just an ordinary System.Exception with no message in this case.

### Notes
I went directly against the advice of a comment to make this change. I tried to see what motivated that comment, but it came with the initial commit along with all the code next to it. Regardless, it does not make me feel good to do so. I don't understand why the comment should be true, but please do read it and let me know if this is a horrible idea.

I also intentionally reused MSB4017 because this feels like the same exception, and I didn't want to confuse people. I just added some extra formatting around it. Like with going against the comment, I can find a new number if reviewers don't like that idea.

### CODE REVIEW

File: src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs [hunk 1]
```diff
@@ -842,13 +842,25 @@ private async Task BuildAndReport()
...
+                else if (ex is InternalLoggerException)
                 {
-                    _nodeLoggingContext.LogError(BuildEventFileInfo.Empty, "UnhandledMSBuildError", ex.ToString());
+                    string realMessage = ex.Message;
+                    Exception realEx = ex;
+                    while (realEx.InnerException is not null)
+                    {
+                        realEx = realEx.InnerException;
+                        realMessage = realEx.Message;
+                    }
```
Comment (JanKrivanek) [inline src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:853]: Are we interrested in the innermost exception here? Or can we reuse https://github.com/dotnet/msbuild/blob/main/src/Shared/TaskLoggingHelper.cs#L511 ?

**Review by JanKrivanek — APPROVED** [review]
Unexpected order of messages seems less harm then losing the exception info - so the change looks good to me.

I'm just wondering whether the rethrowing info wouldn't be helpful as well

File: src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs (hunk 1 above)
Comment (Forgind) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:853]: I was originally thinking I could use its stack trace, too, but reusing code is very tempting...

I'm fine with using the outermost exception's stack trace and the message from TaskLoggingHelper or keeping it as-is. Do you have a preference?

Comment (Forgind) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:853]: Option 3 is modifying TaskLoggingHelper.GetInnerExceptionMessageString to also return the innermost exception's call stack. Then I could use both from that?

Comment (JanKrivanek) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:853]: I personally prefer as much diagnostic info as possible - so we should have `Exception.ToString` somewhere.

Users can sometime got scared by seeing stack traces - that's the reason why the current helper unwraps the messages only and the full `ToString()` version is logged just as a low-pri message. So you can probably follow that pattern. Though - in this specific case - when someone explicitly attaches additional log that has issues - I personaly wouldn't mind even if the full `ToString()` is logged as error. Your choice then :-)

**Review by YuliiaKovalova — APPROVED** [review]

File: src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs (hunk 1 above)
Comment (JanKrivanek) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:853]: @Forgind Just a ping to see if you are aware and plan to make changes.

Comment (Forgind) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:853]: Thanks for the ping—I think I like reusing TaskLoggingHelper.GetInnerExceptionMessageString. I don't think the error should be super verbose, so I'm satisfied with leaving it there and logging a low-pri message afterwards with the full ToString.

Comment (JanKrivanek) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs]: Thank you @Forgind for the update
