### PR TITLE
Don't compile globbing regexes on .NET Framework

### LINKED ISSUE #6599: Glob matching has bad first-call performance on .NET Framework 64-bit
### Issue Description
Glob matching exposed via the `IMSBuildGlob.IsMatch` call internally uses compiled regular expressions. Generating and JITting these is significantly slower on 64-bit .NET Framework compared to 32-bit Framework (likely due to a different JIT implementation). The cumulative cost could be as high as seconds in common Visual Studio scenarios.

### Steps to Reproduce
Call [Project.GetAllGlobs()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.project.getallglobs?view=msbuild-16-netcore#Microsoft_Build_Evaluation_Project_GetAllGlobs), then call [IsMatch](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.globbing.imsbuildglob.ismatch?view=msbuild-16-netcore) on the globs extracted from the result.

Expected:
Matching globs against strings is near instantaneous for first- as well following calls.

Actual:
First call is slow, measured at ~26 ms on my setup.

### Data
Use the following sample regular expression:
```
^(?<FIXEDDIR>C:[/\\]+src[/\\]+_test[/\\]+aa[/\\]+bin[/\\]+Debug[/\\]+)(?<WILDCARDDIR>((.*/)|(.*\\)|()))(?<FILENAME>[^/\\]*)$
```

### Analysis
First call of Regex.Match() on the above compiled regex costs:
- ~8 ms on .NET Framework x86
- ~26 ms on .NET Framework x64
- ~0.2 ms on .NET Core x64

### Versions & Configurations
Reproduced with 17.0.0-preview-21317-11+c579afe9c but has been in MSBuild for several major releases.

### Regression?
Yes from Visual Studio point of view because the product now runs on 64-bit Framework (previously 32-bit Framework). More details in this [internal bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1338419).

### Attach a binlog
N/A

### PR DESCRIPTION
**Pull request by ladipro**
Fixes #6599

### Context

Compiled regular expressions have a high first-call cost on .NET Framework, especially when running in a 64-bit process. At best, they need to be used thousands of times to make up for the compilation cost. In some cases compiled regexes are even slower than interpreted ones.

### Changes Made

Switched regexes used in `MSBuildGlob` to interpreted on .NET Framework. Also optimized capture groups as suggested by @ToddGrun and removed a couple of unused fields.

### Testing

- Existing unit tests with added coverage for `MSBuildGlob.MatchInfoResult`.
- Experimental insertion to confirm the CPU time win.

### CODE REVIEW

File: src/Shared/FileMatcher.cs [hunk 1]
```diff
@@ -1869,20 +1864,17 @@ out matchResult.isLegalFileSpec
...
-            out string fixedDirectoryPart,
             out string wildcardDirectoryPart,
             out string filenamePart)
         {
             Match match = fileSpecRegex.Match(fileToMatch);
 
             isMatch = match.Success;
-            fixedDirectoryPart = string.Empty;
             wildcardDirectoryPart = String.Empty;
-            filenamePart = string.Empty;
```
Comment (rainersigwald) [inline src/Shared/FileMatcher.cs:1881]: Don't we generally prefer lower-case `string`, since it always refers to the right type while `String` might be some other type?

File: src/Build/Globbing/MSBuildGlob.cs [hunk 2]
```diff
@@ -202,8 +206,20 @@ public static MSBuildGlob Parse(string globRoot, string fileSpec)
...
                     if (regex == null)
                     {
+                        RegexOptions regexOptions = FileMatcher.DefaultRegexOptions;
                         // compile the regex since it's expected to be used multiple times
-                        Regex newRegex = new Regex(matchFileExpression, FileMatcher.DefaultRegexOptions | RegexOptions.Compiled);
+                        // For the kind of regexes used here, compilation on .NET Framework tends to be expensive and not worth the small
+                        // run-time boost so it's enabled only on .NET Core by default.
+#if RUNTIME_TYPE_NETCORE
+                        bool compileRegex = true;
+#else
```
Comment (Forgind) [inline src/Build/Globbing/MSBuildGlob.cs:215]: These aren't things I would expect to change in the middle of a build. Should we save off the RegexOptions earlier and use it multiple times?

**Review by rainersigwald — APPROVED** [review]

**Review by Forgind — APPROVED** [review]
LGTM!

**Review by BenVillalobos — APPROVED** [review]

File: src/Shared/FileMatcher.cs (hunk 1 above)
Comment (ladipro) [reply src/Shared/FileMatcher.cs:1881]: Fixed, thank you.

File: src/Build/Globbing/MSBuildGlob.cs (hunk 2 above)
Comment (ladipro) [reply src/Build/Globbing/MSBuildGlob.cs:215]: Checking the changewave and OR'ing two integers is very cheap. Unless I am misunderstanding I would argue that it's not worth adding a cache for this.

**Comment by BenVillalobos** [comment]
As a change in this PR, can you modify the list in https://github.com/dotnet/msbuild/blob/main/documentation/wiki/ChangeWaves.md?

File: src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs [hunk 3]
```diff
@@ -326,20 +326,39 @@ public void GlobMatchingShouldWorkWithComplexRelativeLiterals()
...
 
             Assert.True(glob.IsMatch(stringToMatch));
+
+            MSBuildGlob.MatchInfoResult result = glob.MatchInfo(stringToMatch);
+            Assert.True(result.IsMatch);
+
+            string NormalizeSlashes(string path)
+            {
+                string normalizedPath = path.Replace(Path.DirectorySeparatorChar == '/' ? '\\' : '/', Path.DirectorySeparatorChar);
+                return NativeMethodsShared.IsWindows ? normalizedPath.Replace("\\\\", "\\") : normalizedPath;
```
Comment (drewnoakes) [inline src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs:354]: Is there any chance this would be a `\\server\share` style (UNC) path? If so, this would break it.

Comment (ladipro) [reply src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs:354]: Yep, this is test code. I just wanted to add something for `FixedDirectoryPartMatchGroup`, `WildcardDirectoryPartMatchGroup`, and `FilenamePartMatchGroup` because they had no coverage at all. The platform-specific path normalization logic makes this somewhat less elegant. Oh, and I made sure the test case passes without my changes, too.

Btw, I took a cursory look at CPS and project-system sources and don't see these properties used. Do you happen to know if they ever were used or maybe about some other component calling `IMSBuildGlob.MatchInfo`? Thank you!

Comment (drewnoakes) [reply src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs:354]: I see no reference to any of those three properties in the history of CPS or dotnet/project-system. I also see no reference to `MSBuildGlob.MatchInfoResult` (is that the type you meant?).

Comment (ladipro) [reply src/Build.UnitTests/Globbing/MSBuildGlob_Tests.cs:354]: Thank you for confirming! (Yes, that's the type, it is available only on `MSBuildGlob` not on `IMSBuildGlob`, sorry for the confusion.)
