### PR TITLE
Do not allow GetType and compare ignoring case

### LINKED ISSUE #9967: [Bug]: GetType can still be called as property function, due to case-sensitive comparison
### Issue Description

<https://github.com/dotnet/msbuild/pull/6769> supposedly prevented calling GetType() as a property function, but it does not recognize the name if written with different letter case, e.g. `gettype`.

### Steps to Reproduce

demo.proj:

```XML
<Project>
  <PropertyGroup>
    <foo>aa</foo>
  </PropertyGroup>

  <Target Name="bb">
    <Message Importance="high" Text="$(foo.gettype().FullName)"/>
  </Target>
</Project>
```

dotnet msbuild demo.proj

### Expected Behavior

```
$ dotnet msbuild demo.proj
MSBuild version 17.9.6+a4ecab324 for .NET
demo.proj(7,32): error MSB4185: The function "GetType" on type "System.String" is not available for execution as an MSBuild property function.
```

### Actual Behavior

```
$ dotnet msbuild demo.proj
MSBuild version 17.9.6+a4ecab324 for .NET
  System.String
```

### Analysis

Perhaps a case-insensitive comparison here would fix it: <https://github.com/dotnet/msbuild/blob/a4ecab324c0586fe69b6bdcc062264b244dd8cd0/src/Build/Evaluation/Expander.cs#L5287>

Alternatively, compare the MemberInfo.Name string after the lookup, rather than the user-specified string.  That might be a larger change, though.

### Versions & Configurations

MSBuild version 17.9.6+a4ecab324 in .NET SDK 8.0.202

### PR DESCRIPTION
**Pull request by f-alizada**
Fixes #9967

### Context
The GetType method is still available if called like "gettype" 

### Changes Made
Compare the method name ignoring the case

### Testing
Added two tests
- Cover when it is not allowed
- Cover when GetType is enabled using env variable "MSBUILDENABLEALLPROPERTYFUNCTIONS"

### CODE REVIEW

**Review by rokonec — APPROVED** [review]
It is however functional change which can break someone. 
Please consider to put it under change wave.

**Comment by f-alizada** [comment]
> Please consider to put it under change wave.

Thank you @rokonec for the review, the possible breaking change was discussed in the issue. 
There is a documentation stating that GetType is not supported: https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/calling-gettype-property-functions
I'm not against putting the change begind the changewave however, there is a already a flag that will allow to do that: 
https://github.com/dotnet/msbuild/blob/c820d6be9da35ff71afdf3caf8a25b0ee34c3281/src/Build/Evaluation/Expander.cs#L5302-L5311
What do you think? 
FYI @baronfel

**Comment by rokonec** [comment]
> there is a already a flag that will allow to do that

@f-alizada in this case it is not a big deal. However, if I understand it correctly, we try to make it easier for customer by putting ALL functional changes into changewave and using escapehatches for long term (infinite) support of some optional features. in this particular case it make sense to me that it will be under both opt-in escape hatch and changewave.

What is your take on it @rainersigwald

**Review by rainersigwald — APPROVED** [review]
As an extension to an already-documented breaking change with an existing documented escape hatch I'm comfortable _not_ putting this behind a changewave (for once!).

File: src/Build.UnitTests/Evaluation/Expander_Tests.cs [hunk 1]
```diff
@@ -4978,6 +4978,56 @@ public void ExpandItem_ConvertToStringUsingInvariantCultureForNumberData_Respect
...
+    <PropertyGroup>
+        <foo>aa</foo>
+        <typeval>$(foo.{methodName}().FullName)</typeval>
+    </PropertyGroup>
+</Project>");
+                var exception = Should.Throw<InvalidProjectFileException>(() =>
+                {
+                    new ProjectInstance(projectFile.Path);
+                });
+                exception.BaseMessage.ShouldContain($"The function \"{methodName}\" on type \"System.String\" is not available for execution as an MSBuild property function.");
```
Comment (ladipro) [inline src/Build.UnitTests/Evaluation/Expander_Tests.cs:5002]: nit: Wouldn't this assertion fail with non-English locale? Would it be enough to look for `MSB4185`?

Comment (f-alizada) [reply src/Build.UnitTests/Evaluation/Expander_Tests.cs:5002]: Thank you for pointing out. 
In my opinion verifying that code exists in the message does not provide 100% certainty that the message is correct , + it has additinal protection on message error change 
what do you think if before the test to set the currentCultureInfo?  
```
currentThread.CurrentCulture = new CultureInfo("en");
currentThread.CurrentUICulture = new CultureInfo("en");
```

Comment (ladipro) [reply src/Build.UnitTests/Evaluation/Expander_Tests.cs:5002]: Thank you for the quick response. I don't have a strong opinion. Setting the culture (and restoring it after the test) looks like a good approach. Or maybe asserting that the code and `methodName` are both present would also provide reasonable coverage.

**Review by ladipro — APPROVED** [review]
