### PR TITLE
Fix TaskHostTask to pass request-level global properties to TaskHost

### LINKED ISSUE #13153: validate -mt works with static graph restore
### Summary

When MSBuild runs with `-mt` (multithreaded) mode AND `RestoreUseStaticGraphEvaluation=true`, conditional `ProjectReference` items that depend on `MSBuildRestoreSessionId` are not properly evaluated during graph construction, causing those projects to be excluded from restore.

### Reproduction

**Environment:** dotnet/runtime repo with `RestoreUseStaticGraphEvaluation=true` (default)

**Problematic pattern in `src/libraries/pretest.proj`:**
```xml
<ExternalsProject Include="externals.csproj" ... />
<ProjectReference Include="@(ExternalsProject)" Condition="'$(MSBuildRestoreSessionId)' != ''" />
```

This pattern is intended to include `externals.csproj` as a `ProjectReference` only during restore (when `MSBuildRestoreSessionId` is set).

### Test Results

| Test | `-mt` mode | Static Graph Restore | `externals.csproj` Restored | NETSDK1004 Error |
|------|-----------|---------------------|---------------------------|------------------|
| **1** | ✅ Yes | ✅ Yes | ❌ **No** | ✅ **Yes** (BUG) |
| **2** | ✅ Yes | ❌ No | ✅ Yes | ❌ No |
| **3** | ❌ No | ✅ Yes | ✅ Yes | ❌ No |

### Commands Used

```powershell
# Test 1: FAILS - externals.csproj not restored
dotnet msbuild Build.proj -restore -t:Build -p:Subset=libs.pretest -p:Configuration=Release -mt -m

# Test 2: WORKS - externals.csproj restored
dotnet msbuild Build.proj -restore -t:Build -p:Subset=libs.pretest -p:Configuration=Release -p:RestoreUseStaticGraphEvaluation=false -mt -m

# Test 3: WORKS - externals.csproj restored  
dotnet msbuild Build.proj -restore -t:Build -p:Subset=libs.pretest -p:Configuration=Release -m
```

### Root Cause Analysis

NuGet's static graph restore uses an out-of-process tool (`NuGet.Build.Tasks.Console`) to evaluate projects and build the dependency graph. This tool receives global properties via `IBuildEngine6.GetGlobalProperties()`.

When `-mt` mode is enabled, the `MSBuildRestoreSessionId` property appears to not be properly passed to the static graph evaluation, causing the condition `'$(MSBuildRestoreSessionId)' != ''` to evaluate as `false` during graph construction. This excludes the conditional `ProjectReference` from the restore graph.

### Affected Code Paths

- `NuGet.Build.Tasks.RestoreTaskEx` → `StaticGraphRestoreTaskBase`
- `NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.GetDependencyGraphSpec()`
- Global property serialization between MSBuild and the out-of-proc NuGet console

### Workarounds

1. **Disable `-mt` for affected repos:** Set `<UseMSBuildMT>false</UseMSBuildMT>` (current VMR approach)
2. **Disable static graph restore:** Set `RestoreUseStaticGraphEvaluation=false` (slower)
3. **Change project pattern:** Remove the `MSBuildRestoreSessionId` condition and always include the `ProjectReference`

### Recommendation

This appears to be a bug in NuGet's static graph restore implementation when combined with MSBuild `-mt` mode. The fix likely needs to be in `NuGet.Build.Tasks` to ensure global properties (including `MSBuildRestoreSessionId`) are properly passed to the out-of-process evaluation in all modes.

### PR DESCRIPTION
**Pull request by JanProvaznik**
## Summary

Fixes #13153 — -mt mode breaks NuGet static graph restore for conditional ProjectReference items that depend on MSBuildRestoreSessionId.

## Root Cause

When -mt mode routes tasks to an out-of-process TaskHost (via TaskRouter.NeedsTaskHostInMultiThreadedMode()), TaskHostTask.Execute() was sending BuildParameters.GlobalProperties (build-level) to the TaskHostConfiguration. These build-level properties **do not include** per-request properties like MSBuildRestoreSessionId that are added by ExecuteRestore() in XMake.cs.

This caused NuGet's RestoreTaskEx (which lacks MSBuildMultiThreadableTaskAttribute and thus gets routed to TaskHost in -mt mode) to receive an empty MSBuildRestoreSessionId via IBuildEngine6.GetGlobalProperties(). The NuGet static graph restore then excluded conditional ProjectReference items, breaking restore for projects like xternals.csproj in dotnet/runtime.

**Without -mt**: TaskHost.GetGlobalProperties() returns _requestEntry.RequestConfiguration.GlobalProperties → ✅ includes MSBuildRestoreSessionId

**With -mt**: OutOfProcTaskHostNode.GetGlobalProperties() returns _currentConfiguration.GlobalProperties (from TaskHostConfiguration) → ❌ only has build-level properties from BuildParameters.GlobalProperties

## Fix

New method `GetGlobalPropertiesForTaskHost()` in TaskHostTask that:
1. Uses `BuildEngine.GetGlobalProperties()` via `IBuildEngine6` (returns correct request-level properties from RequestConfiguration)
2. Falls back to `BuildParameters.GlobalProperties` if `IBuildEngine6` is not available
3. Works on both `net10.0` and `net472` targets

## Validation

- Built MSBuild (Release, net10.0 + net472) — ✅ compiles clean
- Built dotnet/runtime with `-mt -m -restore` using fixed MSBuild
  - `externals.csproj` **correctly restored** (was excluded before fix)
  - Binlog confirms: `-mt` in command line, `MSBuildRestoreSessionId` set with GUID, `RestoreUseStaticGraphEvaluation=true`, `RestoreTaskEx` executed

### CODE REVIEW

File: src/Build/Instance/TaskFactories/TaskHostTask.cs [hunk 1]
```diff
@@ -412,6 +412,31 @@ public bool Execute()
...
+                var result = new Dictionary<string, string>(requestProperties.Count, StringComparer.OrdinalIgnoreCase);
+                foreach (KeyValuePair<string, string> kvp in requestProperties)
+                {
+                    result[kvp.Key] = kvp.Value;
+                }
+
+                return result;
+            }
+
+            return new Dictionary<string, string>(_buildComponentHost.BuildParameters.GlobalProperties);
```
Comment (JanProvaznik) [inline src/Build/Instance/TaskFactories/TaskHostTask.cs:436]: 🟠 **MODERATE — Fallback path uses case-sensitive comparer**

`BuildParameters.GlobalProperties` returns a `ReadOnlyConvertingDictionary`, so the `Dictionary` copy constructor defaults to `EqualityComparer<string>.Default` (case-sensitive). MSBuild property names are case-insensitive, and `TaskHostConfiguration` serializes with `OrdinalIgnoreCase` (line 517).

```suggestion
            return new Dictionary<string, string>(_buildComponentHost.BuildParameters.GlobalProperties, StringComparer.OrdinalIgnoreCase);
```

Comment (JanProvaznik) [reply src/Build/Instance/TaskFactories/TaskHostTask.cs:436]: existing behavior while incorrect should be preserved under changewave

**Comment by JanProvaznik** [comment]
validation on runtime running https://dev.azure.com/dnceng-public/public/_build?definitionId=334
runtime passed (in first run, though both failed overall on a race condition that's fixed in main but this branch started too early)

File: src/Build.UnitTests/BackEnd/GetGlobalPropertiesTask.cs [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+    /// Used by TaskHostCallback_Tests to verify that request-level global properties
+    /// (not just build-level properties) are forwarded through TaskHostTask to the out-of-proc TaskHost.
+    /// </summary>
+    public class GetGlobalPropertiesTask : Task
+    {
+        [Output]
+        public int GlobalPropertyCount { get; set; }
+
+        [Output]
+        public string GlobalPropertyLog { get; set; } = string.Empty;
```
Comment (AR-May) [inline src/Build.UnitTests/BackEnd/GetGlobalPropertiesTask.cs]: Nit: this does not seem to be used anywhere.

**Review by AR-May — APPROVED** [review]
LGTM, but I’d like to double‑check with @rainersigwald in case there are any hidden issues with fixing this behavior.

File: src/Build.UnitTests/BackEnd/GetGlobalPropertiesTask.cs (hunk 2 above)
Comment (JanProvaznik) [inline src/Build.UnitTests/BackEnd/GetGlobalPropertiesTask.cs]:
```suggestion
```

File: documentation/wiki/ChangeWaves.md [hunk 3]
```diff
@@ -31,6 +31,7 @@ Change wave checks around features will be removed in the release that accompani
 
 ### 18.6
 - [AbsolutePath.GetCanonicalForm optimization - avoid expensive Path.GetFullPath calls when paths don't need canonicalization](https://github.com/dotnet/msbuild/pull/13369)
+- [TaskHostTask forwards request-level global properties (e.g. MSBuildRestoreSessionId) to out-of-proc TaskHost in -mt mode](https://github.com/dotnet/msbuild/pull/13443)
```
Comment (rainersigwald) [inline documentation/wiki/ChangeWaves.md:34]: This PR refers to it as "request-level" everywhere but is that right? It's instance level, right?

**Comment by JanProvaznik** [comment]
It didn't break other stuff such as msbuild because it does not use this pattern:
- https://github.com/dotnet/runtime/blob/7602c30b43e12e3ced08087cc1503f017ac4206e/src/libraries/pretest.proj#L18

File: documentation/wiki/ChangeWaves.md (hunk 3 above)
Comment (JanProvaznik) [reply documentation/wiki/ChangeWaves.md:34]: there are 3 possible words for this distinction from `_buildComponentHost.BuildParameters.GlobalProperties` (let's call that build level)

"Request, Project, Instance"

I think `Request` or `BuildRequest` is the cleanest terminology.

See this taskhost code that bridges those concepts
```csharp
       /// <summary>
        /// Gets the global properties for the current project.
        /// </summary>
        /// <returns>An <see cref="IReadOnlyDictionary{String, String}" /> containing the global properties of the current project.</returns>
        public IReadOnlyDictionary<string, string> GetGlobalProperties()
        {
            return _requestEntry.RequestConfiguration.GlobalProperties.ToDictionary();
        }
```

Also it's a bit confusing that you may create a request either from ProjectInstance (that also has globalproperties field) or dictionary, and in that case the Instance terminology would not make sense in the codepath

Comment (rainersigwald) [reply documentation/wiki/ChangeWaves.md:34]: Our terminology for this is so confusing. You can pass a `BuildParameters` to `BeginBuild`, and you can also  _call_ `BuildManager.BuildRequest()` with the public API that takes a `BuildRequestData` that has a `GlobalProperties` field. Or you can do that async with `PendBuildRequest()` that returns a `BuildSubmission`.

Then, internally, the scheduler has `BuildRequest` objects, which are a configured (i.e. global properties set) project + list of targets. And running one may hit a task that causes a new `BuildRequest` to be created.

So I agree request/`BuildRequest` is reasonable. Ideally it'd be maybe something more like that `RequestConfiguration`, since there may be many `BuildRequest`s for a single configured project . . . but that's not a concept that is widely understood. I always refer to it as a "project instance" but of course that's confusing because `ProjectInstance` is yet another thing. . .

Anyway yeah: lgtm
