### PR TITLE
Fix incorrect and confusing slnf error Fixes #5712

### LINKED ISSUE #5712: MSB5028 error message has "System.Collections.Generic.HashSet`1[System.String]" as solution filter name
### Issue Description
1. Solution filter file at "System.Collections.Generic.HashSet\`1[System.String]" indicates a wrong file location.
2. C:\Users\hadri\source\repos\CSharpMath\Csproj2\Csproj2.csproj does not indicate the correct project location.
3. Error message is seen twice.

### Steps to Reproduce

[SlnfAndShproj.zip](https://github.com/dotnet/msbuild/files/5175226/SlnfAndShproj.zip)
```
hadri@Home MINGW64 ~/source/repos/CSharpMath (Benchmark)
$ dotnet build ../SlnfAndShproj/ErrorMSB5028.slnf
Microsoft (R) Build Engine version 16.8.0-preview-20414-02+a55ce4fbb for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\hadri\source\repos\CSharpMath\Csproj2\Csproj2.csproj : Solution file error MSB5028: Solution filter file at "System.Collections.Generic.HashSet`1[System.String]" includes project "Csproj2\Csproj2.csproj" that is not in the solution file at "C:\Users\hadri\source\repos\SlnfAndShproj\SlnfAndShproj.sln".

Build FAILED.

C:\Users\hadri\source\repos\CSharpMath\Csproj2\Csproj2.csproj : Solution file error MSB5028: Solution filter file at "System.Collections.Generic.HashSet`1[System.String]" includes project "Csproj2\Csproj2.csproj" that is not in the solution file at "C:\Users\hadri\source\repos\SlnfAndShproj\SlnfAndShproj.sln".
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.19

```

### Expected Behavior
1. Solution filter file at "C:\Users\hadri\source\repos\SlnfAndShproj\ErrorMSB5028.slnf"
2. C:\Users\hadri\source\repos\SlnfAndShproj\Csproj2\Csproj2.csproj
3. Error message is seen once.

### Actual Behavior
1. Solution filter file at "System.Collections.Generic.HashSet\`1[System.String]"
2. C:\Users\hadri\source\repos\CSharpMath\Csproj2\Csproj2.csproj
3. Error message is seen twice.

### Analysis
1. Probably used the wrong object in string formatting.
2. Project file path should take relative paths into account instead of relying on the current directory.
3. I have no idea

### Versions & Configurations
```
hadri@Home MINGW64 ~/source/repos/CSharpMath (Benchmark)
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by Forgind**
The error displayed a hashset instead of the path to the filter file used to create the hash set and extended a relative path into a full path using the current working directory instead of the directory containing the .sln.

### CODE REVIEW

File: src/Build/Construction/Solution/SolutionFile.cs [hunk 1]
```diff
@@ -202,6 +203,7 @@ internal string FullPath
                 ErrorUtilities.VerifyThrowInternalRooted(value);
                 if (FileUtilities.IsSolutionFilterFilename(value))
                 {
+                    _solutionFilterFile = value;
```
Comment (ladipro) [inline src/Build/Construction/Solution/SolutionFile.cs:206]: nit: I would move the assignment to `ParseSolutionFilter`, just for cosmetic readability reasons. The way it's written now, it makes the reader wonder why the property reads from `_solutionFile` and writes to `_solutionFilterFile`.

**Review by ladipro — APPROVED** [review]

**Review by rainersigwald — APPROVED** [review]
