### PR TITLE
Account for ARM64 in ProcessorArchitecture Tests

### LINKED ISSUE #7292: Unit Tests Fail for ProcessorArchitecture.ARM64 on Apple Silicon
### Issue Description

Tested on macOS Monterey v12.1 with Apple M1 Pro and .Net SDK Arm64. 

Running unit tests fails because test methods [ValidateConvertDotNetFrameworkArchitectureToProcessorArchitecture](https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs#L47) and [ValidateCurrentProcessorArchitectureCall](https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs#L41) fail when the value of `ProcessorArchitecture.CurrentProcessArchitecture` is `ProcessorArchitecture.ARM64`.

### Steps to Reproduce

Follow the instructions for building on [macOS](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md#unix). Use a machine with an Apple Silicon chip. Run the command `./build.sh --test` as in the instructions.

### Expected Behavior

Tests are expected to complete with no errors.

### Actual Behavior

The test run fails:
```
XUnit : error : Tests failed: [...]/msbuild/artifacts/TestResults/Debug/Microsoft.Build.Utilities.UnitTests_net6.0_x64.html [net6.0|x64] [[...]/msbuild/src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj]
    0 Warning(s)
    1 Error(s)
```

The log shows 2 failures for the Microsoft.Build.Utilities.UnitTests.csproj project:
```
BuildUtilities.ProcessorArchitecture.CurrentProcessArchitecture is: ARM64
  Microsoft.Build.UnitTests.ProcessorArchitectureTests.ValidateConvertDotNetFrameworkArchitectureToProcessorArchitecture [FAIL]
    System.InvalidOperationException : Untested or new ProcessorArchitecture type
      Stack Trace:
      [...]/msbuild/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs(93,0): at Microsoft.Build.UnitTests.ProcessorArchitectureTests.ValidateConvertDotNetFrameworkArchitectureToProcessorArchitecture()
  Microsoft.Build.UnitTests.ProcessorArchitectureTests.ValidateCurrentProcessorArchitectureCall [FAIL]
    Shouldly.ShouldAssertException : "ARM64"
        should be
    null
        but was not
        difference
    Difference     |  |    |    |    |    |   
                   | \|/  \|/  \|/  \|/  \|/  
    Index          | 0    1    2    3    4    
    Expected Value | n    u    l    l         
    Actual Value   | A    R    M    6    4    
    Expected Code  | 110  117  108  108       
    Actual Code    | 65   82   77   54   52   
      Stack Trace:
         at Shouldly.ShouldBeStringTestExtensions.ExecuteAssertion(IAssertion assertion, Func`1 customMessage)
         at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected, Func`1 customMessage, StringCompareShould options)
         at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected, StringCompareShould options)
         at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected)
      [...]/msbuild/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs(43,0): at Microsoft.Build.UnitTests.ProcessorArchitectureTests.ValidateCurrentProcessorArchitectureCall()
```

(I have removed part of the paths for privacy.)

### Analysis

The ARM64 const (defined in ProcessorArchitecture.cs) is not handled by the [ProcessorArchitectureTests](https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs) unit test class.

https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Utilities/ProcessorArchitecture.cs#L43-L48

### Versions & Configurations

```
% dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

```
% dotnet msbuild -version
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

17.0.0.52104
```

### PR DESCRIPTION
**Pull request by BenVillalobos**
Fixes #7292

### Context
ProcessorArchitecture unit tests needed to be updated to account for arm64 machines.

### Changes Made
Accounts for arm64 as a valid processor architecture

### Testing
Tested locally on an m1 mac.

### CODE REVIEW

**Comment by BenVillalobos** [comment]
Tested this on my m1 mac and got a successful `./build.sh --test`

**Review by rainersigwald — APPROVED** [review]

File: src/Utilities/ToolLocationHelper.cs [hunk 1]
```diff
@@ -3399,7 +3399,8 @@ internal static string ConvertDotNetFrameworkArchitectureToProcessorArchitecture
             switch (architecture)
             {
                 case DotNetFrameworkArchitecture.Bitness32:
-                    if (ProcessorArchitecture.CurrentProcessArchitecture == ProcessorArchitecture.ARM)
+                    if (ProcessorArchitecture.CurrentProcessArchitecture == ProcessorArchitecture.ARM ||
+                        ProcessorArchitecture.CurrentProcessArchitecture == ProcessorArchitecture.ARM64)
```
Comment (ladipro) [inline src/Utilities/ToolLocationHelper.cs:3403]: It looks like the original purpose of `ConvertDotNetFrameworkArchitectureToProcessorArchitecture` was to make it possible to compose 32-bit paths on AMD64. The AMD64 .NET Framework environment is special in that it guarantees the presence of the x86 version of .NET Framework + SDKs.

I don't believe this applies to ARM, be it Core or Framework. In fact, `ProcessorArchitectures.ARM` is not a supported architecture at all and should be removed. Together with `IA64` 😉 

No harm in the way it is written now as the scenarios just don't exist but high-level I don't think the code makes sense. If you look at where the result of this method is used (outside of tests), you'll see it's very AMD64 / x86 centric. I wonder if other architectures (so only `ARM64` as everything else is dead) shouldn't be handled differently in the top-level ToolLocationHelper methods.

Just a nit/rant, totally OK to leave it as is.

**Review by ladipro — APPROVED** [review]
