### PR TITLE
Fix building slnf with @ in the path

### LINKED ISSUE #11050: Fatal crash if solution filter is built from within a path that contains an `@` sign
### Issue Description

I downloaded source code from some hosting site, which produces a zipfile "`project@commithash.zip`". Extracting and building that using "dotnet build/msbuild" works fine, if it's a solution, but not if it's a solution filter.

### Steps to Reproduce

1) download [bugtest@commithash.zip](https://github.com/user-attachments/files/17956782/bugtest%40commithash.zip)
2) extract to some location such that it still contains "`@`"
3) cd to `\bugtest@commithash\Solution`
4) run `dotnet build Test.slnf`

### Expected Behavior

The project is built successfully.

### Actual Behavior

```
D:\Projects\bugtest@commithash\Solution
❯ dotnet build Test.slnf
D:\Projects\bugtest@commithash\Solution\Test.slnf : error MSB4014:
  The build stopped unexpectedly because of an internal failure.
  System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Projects\bugtest%40commithash\Solution\Solution.sln'.
     at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
     at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
     at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
     at System.IO.File.OpenRead(String path)
     at Microsoft.Build.Construction.SolutionFile.GetSolutionFileAndVisualStudioMajorVersions(String solutionFile, Int32& solutionVersion, Int32& visualStudioMajorVersion)
     at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, B
  oolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
     at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
     at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
     at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass99_0.<IssueBuildRequestForBuildSubmission>g__IssueBuildSubmissionToSchedulerImpl|1(BuildSubmission submission, Boolean allowMainThreadBuild)

Build failed with 1 error(s) in 0,0s
```

### Analysis

Notice `%40` (which is `@`) in the path mentioned in the error message. It seems that when resolving the path to the solution file from the slnf JSON file, a URL is constructed at some point and is not properly unescaped when converting it back to a filesystem path.

### Versions & Configurations

❯ dotnet build --version
17.12.0.47303

❯ dotnet --info
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.4872d5d5
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\

### PR DESCRIPTION
**Pull request by surayya-MS**
### Context

Fixes #11050

If the path to the solution file contains `@`, it builds normally. But, if solution filter references this solution then the build fails:
```
{my-path-to}/bugtest%40commithash/Solution/Solution.sln : Solution file error MSB5026: The solution filter file at "{my-path-to}/bugtest@commithash/Solution/Test.slnf" specifies there will be a solution file at "{my-path-to}/bugtest%40commithash/Solution/Solution.sln", but that file does not exist.
```

same happens with other symbols like `%` and `$`.

See the issue description for more details.

### Details

The problem occurs on this line:
https://github.com/dotnet/msbuild/blob/a1c2e7402ef0abe36bf493e395b04dd2cb1b3540/src/Build/Construction/Solution/SolutionFile.cs#L661

`FileUtilities.GetFullPath` changes `@` to `%40`. 

Specifically this happens here:
https://github.com/dotnet/msbuild/blob/18c6b2ec5b07674c153f49aea990ab44f7209690/src/Shared/FileUtilities.cs#L762

### Changes
Added `bool escape` param to `FileUtilities.GetFullPath` to be able to skip escape for getting solution path from solution filter (.slnf) json

### Testing
Added new test to cover this scenario

### CODE REVIEW

File: src/Build/Construction/Solution/SolutionFile.cs [hunk 1]
```diff
@@ -658,7 +658,7 @@ internal static string ParseSolutionFromSolutionFilter(string solutionFilterFile
                 JsonDocumentOptions options = new JsonDocumentOptions() { AllowTrailingCommas = true, CommentHandling = JsonCommentHandling.Skip };
                 JsonDocument text = JsonDocument.Parse(File.ReadAllText(solutionFilterFile), options);
                 solution = text.RootElement.GetProperty("solution");
-                return FileUtilities.GetFullPath(solution.GetProperty("path").GetString(), Path.GetDirectoryName(solutionFilterFile));
+                return FileUtilities.GetFullPath(solution.GetProperty("path").GetString(), Path.GetDirectoryName(solutionFilterFile), escape: false);
```
Comment (rainersigwald) [inline src/Build/Construction/Solution/SolutionFile.cs:661]: Could this be

```suggestion
                return FileUtilities.NormalizePath(Path.GetDirectoryName(solutionFilterFile), solution.GetProperty("path").GetString());
```

without changing `GetFullPath`?

File: src/Shared/FileUtilities.cs [hunk 2]
```diff
@@ -752,14 +752,19 @@ internal static bool HasExtension(string fileName, string[] allowedExtensions)
         /// </summary>
         /// <param name="fileSpec">The file spec to get the full path of.</param>
         /// <param name="currentDirectory"></param>
+        /// <param name="escape">Whether to escape the path after getting the full path.</param>
         /// <returns>full path</returns>
```
Comment (rainersigwald) [inline src/Shared/FileUtilities.cs:756]:
```suggestion
        /// <returns>Full path to the file, escaped.</returns>
```

File: src/Build/Construction/Solution/SolutionFile.cs (hunk 1 above)
Comment (surayya-MS) [reply src/Build/Construction/Solution/SolutionFile.cs:661]: no, this won't work because in  GetFullPath before normalization the solution path that is provided in slnf needs to be fixed for the current machine. 

https://github.com/dotnet/msbuild/blob/04b6e1b59df1004aeedc4703757a5c407c06c139/src/Shared/FileUtilities.cs#L759

I can create new function GetFullPathUnescaped and duplicate the code there. What do you think?

Comment (YuliiaKovalova) [reply src/Build/Construction/Solution/SolutionFile.cs:661]: is it possible to do here

`string fullPath = NormalizePath(Path.Combine(currentDirectory, FileUtilities.FixFilePath(EscapingUtilities.UnescapeAll(fileSpec)));`
 instead of making modification of `FileUtilities.cs`?

**Comment by Mik4sa** [comment]
Could this PR maybe also fix #972148?

**Comment by surayya-MS** [comment]
> Could this PR maybe also fix #11442?

This is probably not related. The bug that this PR fixes is not recent and existed before. The one you described looks like a regression. Nevertheless, we will fix it soon. Thanks for reporting!

File: src/Build/Construction/Solution/SolutionFile.cs (hunk 1 above)
Comment (surayya-MS) [reply src/Build/Construction/Solution/SolutionFile.cs:661]: there is also adding trailing slash at the end of the full path
https://github.com/dotnet/msbuild/blob/aff54559404d31214c71aa2ea6d2caa6003b0334/src/Shared/FileUtilities.cs#L764-L772

Not modifying the `FileUtilities.GetFullPath` by adding extra check makes sense because it is on a hot path. Adding a new method `FileUtilities.GetFullPathUnescaped` that will duplicate most of the code except escaping would be a compromise for that reason.

Is there other reason not to modify `FileUtilities.cs` that I miss?

**Comment by Mik4sa** [comment]
hmm too bad but thank you for your time and feedback :)
I'm looking forward to a fix :)

File: src/Build/Construction/Solution/SolutionFile.cs (hunk 1 above)
Comment (YuliiaKovalova) [reply src/Build/Construction/Solution/SolutionFile.cs:661]: let's add more info on when path can be not escaped and it looks ok for me.

**Review by YuliiaKovalova — APPROVED** [review]

File: src/Build/Construction/Solution/SolutionFile.cs (hunk 1 above)
Comment (surayya-MS) [reply src/Build/Construction/Solution/SolutionFile.cs:662]: thanks! added explanatory comments for not escaping

**Review by maridematte — APPROVED** [review]
