### PR TITLE
Fix issue with SHA256 instantiation

### LINKED ISSUE #9248: [Bug]: SecurityUtilities.SignFile is broken in Microsoft.Build.Tasks.Core >= 17.1.0
### Issue Description

Hi, I am using SecurityUtilities.SignFile to sign a ClickOnce manifest files but it fails with a `System.Security.Cryptography.CryptographicException`.

### Steps to Reproduce

The easiest way to reproduce the issue is to check out [deployment-tools](https://github.com/dotnet/deployment-tools) and to update `Microsoft.Build.Tasks.Core` to version **17.7.2**. This will break ClickOnce signing with `dotnet-mage`.

### Expected Behavior

Signing the ClickOnce manifest file succeeds.

### Actual Behavior

Signing the manifest fails with the following exception:
```
System.Security.Cryptography.CryptographicException: Could not create hash algorithm object.
   at System.Security.Cryptography.Xml.Reference.CalculateHashValue(XmlDocument document, CanonicalXmlNodeList refList)
   at System.Security.Cryptography.Xml.SignedXml.BuildDigestedReferences()
   at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()
   at System.Deployment.Internal.CodeSigning.SignedCmiManifest2.AuthenticodeSignLicenseDom(XmlDocument licenseDom, CmiManifestSigner2 signer, String timeStampUrl, Boolean useSha256, Boolean disallowMansignTimestampFallback) in /_/src/Tasks/ManifestUtil/mansign2.cs:line 767
   at System.Deployment.Internal.CodeSigning.SignedCmiManifest2.Sign(CmiManifestSigner2 signer, String timeStampUrl, Boolean disallowMansignTimestampFallback) in /_/src/Tasks/ManifestUtil/mansign2.cs:line 356
   at Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFileInternal(X509Certificate2 cert, Uri timestampUrl, String path, Boolean targetFrameworkSupportsSha256, ResourceManager resources, Boolean disallowMansignTimestampFallback) in /_/src/Tasks/ManifestUtil/SecurityUtil.cs:line 736
```

### Analysis

Reverting to _Microsoft.Build.Tasks.Core_ **17.0.1** fixes the issue.
I concluded that the problem occurs because of a change in `ManifestSignedXml2.init`, where `SHA256Managed` was replaced by `SHA256`. [See this changeset](https://github.com/dotnet/msbuild/commit/9c173296404f9c365cc524569766f16d7cfcf308#diff-3c1eaefe9ec91bbe29a841a9ad84b3618f1ccde584f8dee15b8d8f78d3103367).
`System.Security.Cryptography.Xml.Reference.CalculateHashValue` internally uses `CryptoConfig.CreateFromName` to instantiate the hash algorithm which then attempts to resolve the constructor for `SHA256` which fails because `SHA256` is an abstract class.

### Versions & Configurations

MSBuild version 17.7.2+d6990bcfa for .NET Framework
17.7.2.37605
dotnet --version
7.0.401

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes #9248

### Context
After the change from SHA256Managed -> SHA256 the instantiation was broken. SHA256 is an abstract class.

### Changes Made
Get back to SHA256Managed usage

### Testing
Manual + UT for guarding the changes in signing.
Before:
image

After:
image

### CODE REVIEW

File: src/Tasks/ManifestUtil/mansign2.cs [hunk 1]
```diff
@@ -270,10 +270,14 @@ private void init()
                                Sha256SignatureMethodUri);
 
 #if RUNTIME_TYPE_NETCORE
-            CryptoConfig.AddAlgorithm(typeof(SHA256),
+#pragma warning disable SYSLIB0021 // Type or member is obsolete
+            // SHA256 can not be used since it is an abstract class.
+            // CalculateHashValue internally calls CryptoConfig.CreateFromName and it causes instantiation problems.
+            CryptoConfig.AddAlgorithm(typeof(SHA256Managed),
                                Sha256DigestMethod);
+#pragma warning restore SYSLIB0021 // Type or member is obsolete
```
Comment (rainersigwald) [inline src/Tasks/ManifestUtil/mansign2.cs:278]: These suppressions bug me. Should we instead

```suggestion
            CryptoConfig.AddOID(Win32.szOID_NIST_sha256,
                               Sha256DigestMethod);
```

?

File: src/Tasks.UnitTests/SecurityUtil_Tests.cs [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+        {
+            Uri timestampUrl = new("http://timestamp.comodoca.com/rfc3161");
+            string clickOnceManifest = Path.Combine(TestAssembliesPaths, "ClickOnceProfile.pubxml");
+            string targetFrameworkVersion = Constants.TargetFrameworkVersion40;
+            string targetFrameworkIdentifier = Constants.DotNetFrameworkIdentifier;
+            bool disallowMansignTimestampFallback = false;
+
+            // the certificate was generated locally and does not contain any sensitive information
+            string pathToCertificate = Path.Combine(TestAssembliesPaths, "mycert.pfx");
+            X509Certificate2 cerfiticate = TestCertHelper.MockCertificate(pathToCertificate);
```
Comment (rainersigwald) [inline src/Tasks.UnitTests/SecurityUtil_Tests.cs:36]: spelling nit:

```suggestion
            X509Certificate2 certificate = TestCertHelper.MockCertificate(pathToCertificate);
```

**Review by rainersigwald — APPROVED** [review]
LGTM.

@sujitnayak if you have a minute could you take a look at this change to `mansign2`?

File: src/Tasks/ManifestUtil/mansign2.cs (hunk 1 above)
Comment (sujitnayak) [reply src/Tasks/ManifestUtil/mansign2.cs:278]: According to the finder, Reference.CalculateHashValue ends up calling CryptoConfig.CreateFromName to create the Algorith object. From what I can tell, CreateFromName uses the mapping written to by AddAlgorithm [appNameHT dict] to create the Algorithm object. The AddOID writes to appOidHT mapping table which does not appear to be used by CreateFromName.

It would be good to try and confirm this though.

File: src/Tasks.UnitTests/SecurityUtil_Tests.cs [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+        private static string TestAssembliesPaths { get; } = Path.Combine(AppContext.BaseDirectory, "TestResources");
+
+        [WindowsOnlyFact]
+        [SupportedOSPlatform("windows")]
+        public void SignFile_Success()
+        {
+            Uri timestampUrl = new("http://timestamp.comodoca.com/rfc3161");
+            string clickOnceManifest = Path.Combine(TestAssembliesPaths, "ClickOnceProfile.pubxml");
+            string targetFrameworkVersion = Constants.TargetFrameworkVersion40;
+            string targetFrameworkIdentifier = Constants.DotNetFrameworkIdentifier;
```
Comment (sujitnayak) [inline src/Tasks.UnitTests/SecurityUtil_Tests.cs:31]: If we're testing for .NET Core, I think target framework identifier should be DotNetCoreAppIdentifier.
If this test is for full FX, TargetFrameworkVersion 4.5 & higher only use SHA256.  TargetVersion40 will use SHA1 I think.

File: src/Tasks.UnitTests/SecurityUtil_Tests.cs [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+        private static string TestAssembliesPaths { get; } = Path.Combine(AppContext.BaseDirectory, "TestResources");
+
+        [WindowsOnlyFact]
+        [SupportedOSPlatform("windows")]
+        public void SignFile_Success()
+        {
+            Uri timestampUrl = new("http://timestamp.comodoca.com/rfc3161");
+            string clickOnceManifest = Path.Combine(TestAssembliesPaths, "ClickOnceProfile.pubxml");
+            string targetFrameworkVersion = "v4.0";
+            string targetFrameworkIdentifier = Constants.DotNetFrameworkIdentifier;
```
Comment (sujitnayak) [inline src/Tasks.UnitTests/SecurityUtil_Tests.cs:31]: targetFrameworkIDentifier should be Constants.DotNetCoreAppIdentifier for .NET Core Apps.

Comment (YuliiaKovalova) [reply src/Tasks.UnitTests/SecurityUtil_Tests.cs]: Fixed. I hope I got you right; just wanted to cover .net framework case too.

File: src/Tasks/ManifestUtil/mansign2.cs (hunk 1 above)
Comment (YuliiaKovalova) [reply src/Tasks/ManifestUtil/mansign2.cs]: It didn't work, I have just noticed it.
Falling back to 
```
CryptoConfig.AddAlgorithm(typeof(SHA256Managed),	
                               Sha256DigestMethod); 
```
usage

**Review by sujitnayak — APPROVED** [review]

File: src/Tasks/ManifestUtil/mansign2.cs (hunk 1 above)
Comment (YuliiaKovalova) [reply src/Tasks/ManifestUtil/mansign2.cs:278]: @rainersigwald fyi

**Review by rainersigwald — APPROVED** [review]
"I tried that and it doesn't work" is a pretty good reason to keep it as you had it :) Looks good.
