### PR TITLE
Optimize exclude computation on ItemGroupIntrinsicTask target call

### LINKED ISSUE #8984: [Performance]: Glob expansion inside targets is missing important Exclude optimization
### Issue Description

When glob expansion runs in a target via `ItemGroupIntrinsicTask`, it separately enumerates includes and excludes, then does the subtraction of their results. This may be prohibitively slow when excludes refer to large subdirectories.

### Steps to Reproduce

```xml
<Project>
  <Target Name="Build">
    <ItemGroup>
      <MyResources Include="**\*.png;**\*.jpg" Exclude="bin\**\*.*;obj\**\*.*" />
    </ItemGroup>
    <Message Text="MyResources.Count: @(MyResources->Count())" />
  </Target>
</Project>
```

When evaluating the glob, there is no need to recurse into `bin` or `obj` at all. MSBuild can simply skip these directories when it enumerates all `.png` and `.jpg` files.

### Data

An internal project is seeing >10 minutes spent running the `ItemGroupIntrinsicTask` due to this issue.

### Analysis

These are the problematic calls: https://github.com/dotnet/msbuild/blob/39e20dce0c00a572f1fbd20a0a520d4e941bbc33/src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs#L469-L481

### Versions & Configurations

_No response_

### Regression

- [ ] yes
- [X] no

### Regression Details

_No response_

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes #8984

### Context
When glob expansion runs in a target via ItemGroupIntrinsicTask, it implicitly invokes `EngineFileUtilities.GetFileListEscaped` for Excludes evaluation.

### Changes Made
Traverse Exclude only if EngineFileUtilities.GetFileListEscaped wasn't called in order to avoid double traversal.

### Testing
Existing cases cover this change.

### CODE REVIEW

File: src/Build/Utilities/EngineFileUtilities.cs [hunk 1]
```diff
@@ -191,10 +191,11 @@ internal static bool FilespecHasWildcards(string filespecEscaped)
             FileMatcher.SearchAction action = FileMatcher.SearchAction.None;
             string excludeFileSpec = string.Empty;
 
-            if (!FilespecHasWildcards(filespecEscaped) ||
-                FilespecMatchesLazyWildcard(filespecEscaped, forceEvaluateWildCards))
+            var noWildcards = !FilespecHasWildcards(filespecEscaped) || FilespecMatchesLazyWildcard(filespecEscaped, forceEvaluateWildCards);
+            var noExcludeSpecs = excludeSpecsEscaped == null || !excludeSpecsEscaped.Any();
+            // It is possible to return original string if no entries in Exclude set and no wildcard matches. 
+            if (noWildcards && noExcludeSpecs)
```
Comment (ladipro) [inline src/Build/Utilities/EngineFileUtilities.cs:197]: super-nit: Please consider taking advantage of short-circuit evaluation of conditions wherever practical. In this case `excludeSpecsEscaped.Any()` doesn't have to run if the filespec has wildcards.

File: src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs [hunk 2]
```diff
@@ -413,27 +413,28 @@ private void GetBatchableValuesFromBuildItemGroupChild(List<string> parameterVal
...
                     originalItem.IncludeLocation);
 
                 if (itemsFromSplit != null)
                 {
                     // Expression is in form "@(X)", so add these items directly.
-                    foreach (ProjectItemInstance item in itemsFromSplit)
-                    {
-                        items.Add(item);
-                    }
+                    items.AddRange(itemsFromSplit);
```
Comment (ladipro) [inline src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs:436]: ❤️

**Review by ladipro — APPROVED** [review]
Looks great, thank you!

File: src/Build/Utilities/EngineFileUtilities.cs [hunk 3]
```diff
@@ -191,8 +191,10 @@ internal static bool FilespecHasWildcards(string filespecEscaped)
             FileMatcher.SearchAction action = FileMatcher.SearchAction.None;
             string excludeFileSpec = string.Empty;
 
-            if (!FilespecHasWildcards(filespecEscaped) ||
-                FilespecMatchesLazyWildcard(filespecEscaped, forceEvaluateWildCards))
+            var noWildcards = !FilespecHasWildcards(filespecEscaped) || FilespecMatchesLazyWildcard(filespecEscaped, forceEvaluateWildCards);
+
+            // It is possible to return original string if no wildcard matches and no entries in Exclude set. 
+            if (noWildcards && excludeSpecsEscaped?.Any() == false)
```
Comment (ladipro) [inline src/Build/Utilities/EngineFileUtilities.cs:197]: This should be:

```suggestion
            if (noWildcards && excludeSpecsEscaped?.Any() != true)
```

to cover both null and and empty `excludeSpecsEscaped`.

**Review by maridematte — APPROVED** [review]
