### PR TITLE
OnlyCheckWhitespaceInsideParenthesis Fixes #5863

### LINKED ISSUE #5863: .NET 6: error MSB4259: Unexpected space at position N Did you forget to remove a space?
### Issue Description

I'm guessing this was introduced in: https://github.com/dotnet/msbuild/pull/5672

Our build fails with:

```
error MSB4259: Unexpected space at position "47" of condition "$(RestoreTaskAssemblyFile.EndsWith('NuGet.exe', StringComparison.InvariantCultureIgnoreCase))". Did you forget to remove a space?
```

The property in question, I can fix by doing:

```diff
-<_IsRunningNuGetRestore Condition="$(RestoreTaskAssemblyFile.EndsWith('NuGet.exe', StringComparison.InvariantCultureIgnoreCase))">True</_IsRunningNuGetRestore>
+<_IsRunningNuGetRestore Condition="$(RestoreTaskAssemblyFile.EndsWith('NuGet.exe',StringComparison.InvariantCultureIgnoreCase))">True</_IsRunningNuGetRestore>
```

But then I just hit the next location:

```diff
-<AndroidSupportedHostJitAbisForConditionalChecks Condition=" !$(AndroidSupportedHostJitAbisForConditionalChecks.EndsWith (':')) "   >$(AndroidSupportedHostJitAbisForConditionalChecks):</AndroidSupportedHostJitAbisForConditionalChecks>
+<AndroidSupportedHostJitAbisForConditionalChecks Condition=" !$(AndroidSupportedHostJitAbisForConditionalChecks.EndsWith(':')) "   >$(AndroidSupportedHostJitAbisForConditionalChecks):</AndroidSupportedHostJitAbisForConditionalChecks>
```

I'm thinking these should be valid, as lots of our existing MSBuild targets would probably break.

### Steps to Reproduce

1. Use: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-alpha.1.20554.10/dotnet-sdk-6.0.100-alpha.1.20554.10-win-x64.exe
2. `dotnet build` this `foo.proj` file:

```xml
<Project>
  <PropertyGroup>
    <Foo>ABCD</Foo>
  </PropertyGroup>
  <ItemGroup Condition="$(Foo.StartsWith ('A'))">
    <Bar Include="True" />
  </ItemGroup>
  <Target Name="Build">
    <Message Importance="High" Text="Foo: $(Foo) Bar: @(Bar)" />
  </Target>
</Project>
```

### Expected Behavior

Build succeeds.

### Actual Behavior

Build fails with:

```
foo.proj(5,14): error MSB4259: Unexpected space at position "16" of condition "$(Foo.StartsWith ('A'))". Did you forget to remove a space?
```

### Analysis

Only guess is something in: https://github.com/dotnet/msbuild/pull/5672

### Versions & Configurations

```
> dotnet --version
6.0.100-alpha.1.20554.10
```

### Attach a binlog

[msbuild.zip](https://github.com/dotnet/msbuild/files/5497384/msbuild.zip)

### PR DESCRIPTION
**Pull request by Forgind**
This weakens the check somewhat, since it only checks just inside parentheses, but that allows people to put spaces in, say, property conditions after a comma.

Fixes #5863

### CODE REVIEW

File: src/Build/Evaluation/Conditionals/Scanner.cs [hunk 1]
```diff
@@ -333,17 +331,20 @@ private static bool ScanForPropertyExpressionEnd(string expression, int index, o
                         if (character == '(')
                         {
                             nestLevel++;
-                            whitespaceCheck = true;
+                            if (index + 1 < expression.Length && char.IsWhiteSpace(pchar[index + 1]) && ChangeWaves.AreFeaturesEnabled(ChangeWaves.Wave16_10))
```
Comment (BenVillalobos) [inline src/Build/Evaluation/Conditionals/Scanner.cs:334]: we only care about a space between the parentheses? What about before / after each one? That's the case here: https://github.com/dotnet/msbuild/issues/5863
`<ItemGroup Condition="$(Foo.StartsWith ('A'))">`

**Review by BenVillalobos — COMMENTED** [review]
You mentioned you wanted this out quick, but definitely needs a few tests before merging.

File: src/Build/Evaluation/Conditionals/Scanner.cs (hunk 1 above)
Comment (Forgind) [reply src/Build/Evaluation/Conditionals/Scanner.cs:334]: Right, so we should ignore cases like that because we don't want them to fail.

File: src/Build/Evaluation/Conditionals/Scanner.cs [hunk 2]
```diff
@@ -325,33 +325,35 @@ private static bool ScanForPropertyExpressionEnd(string expression, int index, o
             {
                 fixed (char* pchar = expression)
                 {
+                    if (expression.Length > 1 && pchar[0] == '(' && char.IsWhiteSpace(pchar[1]) && ChangeWaves.AreFeaturesEnabled(ChangeWaves.Wave16_10))
```
Comment (BenVillalobos) [inline src/Build/Evaluation/Conditionals/Scanner.cs:328]: is the first character in the expression guaranteed to be a '('?

Should this maybe move under the `if (character == '(')?

Something like:
```c#
                        if (character == '(')
                        {
                             if (nestLevel == 0 && index + 1 > expression.Length && pchar[index + 1] == '(' && char.IsWhiteSpace(pchar[1]) && ChangeWaves.AreFeaturesEnabled(ChangeWaves.Wave16_10))
                              {
                                    indexResult = 1;
                                     return false;
                              }
                            nestLevel++;
                        }
```

File: src/Build.UnitTests/Scanner_Tests.cs [hunk 3]
```diff
@@ -104,16 +105,27 @@ public void IllFormedProperty()
...
             Assert.Equal("IllFormedPropertySpaceInCondition", lexer.GetErrorResource());
+        }
 
-            lexer = new Scanner("$( x)", ParserOptions.AllowProperties);
+        /// <summary>
+        /// Tests the space not next to end so no errors case
+        /// </summary>
+        [Theory]
+        [InlineData("$(x x)")]
+        [InlineData("$(y d f  ( hi ) sx)")]
```
Comment (rainersigwald) [inline src/Build.UnitTests/Scanner_Tests.cs:123]: These are examples of things we wish we could catch but we can't with current limitations. Can you instead use examples we want to work like
```suggestion
        [InlineData("$(x.StartsWith( 'y' ))")]
        [InlineData("$(x.StartsWith ('y'))")]
```
?

Comment (rainersigwald) [reply src/Build.UnitTests/Scanner_Tests.cs:123]: Actually, looking at this, I think even starts/ends with space is too aggressive. `$( x.StartsWith ( y ) )` is a bit ugly but works just fine today. Maybe it has to be "has a space _and_ is otherwise only identifier characters"? That would correctly reject `$(x x)` from your examples here.

**Review by rainersigwald — CHANGES_REQUESTED** [review]
fyi, @mfkl

File: src/Build/Evaluation/Conditionals/Scanner.cs (hunk 2 above)
Comment (Forgind) [reply src/Build/Evaluation/Conditionals/Scanner.cs]: Yes

File: src/Build/Evaluation/Conditionals/Scanner.cs [hunk 4]
```diff
@@ -333,24 +334,40 @@ private static bool ScanForPropertyExpressionEnd(string expression, int index, o
...
-                            return false;
+                        }
+                        else if (!XmlUtilities.IsValidSubsequentElementNameCharacter(character))
+                        {
+                            nonIdentifierCharacterFound = true;
+                        }
+
+                        if (character == '$')
+                        {
+                            if (!ScanForPropertyExpressionEnd(expression, index + 1, out index))
```
Comment (rainersigwald) [inline src/Build/Evaluation/Conditionals/Scanner.cs:354]: Adding recursion makes me nervous but I suspect it's cheaper than keeping track of a list of bools for each `nestLevel`.

File: src/Build.UnitTests/Scanner_Tests.cs [hunk 5]
```diff
@@ -104,16 +101,31 @@ public void IllFormedProperty()
...
             Assert.Equal("IllFormedPropertySpaceInCondition", lexer.GetErrorResource());
+        }
 
-            lexer = new Scanner("$( x)", ParserOptions.AllowProperties);
+        /// <summary>
+        /// Tests the space not next to end so no errors case
+        /// </summary>
+        [Theory]
+        [InlineData("$(x.StartsWith( 'y' ))")]
+        [InlineData("$(x.StartsWith ('y'))")]
```
Comment (rainersigwald) [inline src/Build.UnitTests/Scanner_Tests.cs:121]:
```suggestion
        [InlineData("$(x.StartsWith ('y'))")]
        [InlineData("$(x.StartsWith('$('))")]
```

File: src/Build/Evaluation/Conditionals/Scanner.cs [hunk 6]
```diff
@@ -333,24 +334,40 @@ private static bool ScanForPropertyExpressionEnd(string expression, int index, o
...
+                            whitespaceFound = true;
                             indexResult = index;
-                            return false;
+                        }
+                        else if (!XmlUtilities.IsValidSubsequentElementNameCharacter(character))
+                        {
+                            nonIdentifierCharacterFound = true;
+                        }
+
+                        if (character == '$')
```
Comment (rainersigwald) [inline src/Build/Evaluation/Conditionals/Scanner.cs:352]: I think you need to add this lookahead to handle the test case with a literal `$(` in it.

```suggestion
                        if (character == '$' && index < expression.Length - 1 && pchar[index + 1] == '(')
```

File: src/Build.UnitTests/Scanner_Tests.cs (hunk 5 above)
Comment (Forgind) [reply src/Build.UnitTests/Scanner_Tests.cs:121]: The second case doesn't have any spaces, so it would pass this check trivially. Would it be more interesting to add a space?

File: src/Build.UnitTests/Scanner_Tests.cs [hunk 7]
```diff
@@ -104,16 +101,31 @@ public void IllFormedProperty()
...
+        [InlineData("$( x.StartsWith( $(SpacelessProperty) ) )")]
+        [InlineData("$( x.StartsWith( $(_SpacelessProperty) ) )")]
```
Comment (jonathanpeppers) [inline src/Build.UnitTests/Scanner_Tests.cs:123]: One case I ran into was something like:
```csharp
[InlineData("$(x.StartsWith('Foo', StringComparison.InvariantCultureIgnoreCase))")]
```
It might already work with the changes here, but might be good to add this case.

File: src/Build.UnitTests/Scanner_Tests.cs (hunk 5 above)
Comment (rainersigwald) [reply src/Build.UnitTests/Scanner_Tests.cs:121]: It looks like we already fail the `$(` case because the condition expander can't handle that as a literal, so adding it wouldn't be helpful.

File: src/Build.UnitTests/Scanner_Tests.cs (hunk 7 above)
Comment (rainersigwald) [reply src/Build.UnitTests/Scanner_Tests.cs:123]: Do please add this multiple-argument case before merging.

**Review by rainersigwald — APPROVED** [review]
