### PR TITLE
Fix logging context validity check

### LINKED ISSUE #10342: [Bug]: MSBuild crashes with "MSB0001: Internal MSBuild Error: must be valid"
### Issue Description

Copied from https://github.com/dotnet/dnceng/issues/3304

I queried Kusto and it seems we started seeing this more often after we bumped the VMR build to use a bleeding-edge preview 7 SDK. I see one hit in the last 60 days but since we bumped to P7 SDK about 10 hours ago we already hit this three times.

```
    MSBUILD : error MSB4166: Child node "3" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTemproot/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
    MSBUILD : error MSB4166: /tmp/MSBuildTemproot/MSBuild_pid-14914_ef532437860e4947b63c7a07fa167972.failure.txt:
    MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 14914:
    MSBUILD : error MSB4166: =====================
    MSBUILD : error MSB4166: 07/08/2024 11:37:54
    MSBUILD : error MSB4166: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: must be valid
    MSBUILD : error MSB4166:    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
    MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Logging.LoggingContext.LogBuildEvent(BuildEventArgs buildEvent)
    MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args)
    MSBUILD : error MSB4166: ===================
    MSBUILD : error MSB4166: 
```

### Steps to Reproduce

Build the VMR repo. The failure only happens occasionally.

### Expected Behavior

No crash.

### Actual Behavior

There is a crash.

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by JanKrivanek**
Adds diagnostics for #10342

### Context
Attempted logging with invalid context had cryptic error message. It could happen on AssemblyLoadTracker which should be just a transient error.

The exception can be found in the telemetry even in the past - the recent changes only increased likelyhood.

### Changes Made
* Improved logging
* Added resiliency to AssemblyLoadTracker

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

File: src/Build/BackEnd/Components/Logging/LoggingContext.cs [hunk 1]
```diff
@@ -309,8 +309,17 @@ internal void LogFatalBuildError(Exception exception, BuildEventFileInfo file)
...
             _loggingService.LogIncludeFile(BuildEventContext, filePath);
         }
+
+        private protected void CheckValidity()
+        {
+            if (!_isValid)
+            {
+                ErrorUtilities.VerifyThrow(_isValid, "LoggingContext (type: {0}) was not valid during logging attempt.",
+                    this.GetType());
+            }
```
Comment (akoeplinger) [inline src/Build/BackEnd/Components/Logging/LoggingContext.cs:322]: can be simplified since ErrorUtilities.VerifyThrow already checks the value of _isValid.
```suggestion

            ErrorUtilities.VerifyThrow(_isValid, "LoggingContext (type: {0}) was not valid during logging attempt.",
                this.GetType());
```

Comment (rainersigwald) [reply src/Build/BackEnd/Components/Logging/LoggingContext.cs:322]: This requires always materializing the string before the call (we don't have interpolated string handlers in our ErrorUtilities at the moment), so I'd fix it the other way

```suggestion
            if (!_isValid)
            {
                ErrorUtilities.ThrowInternalError("LoggingContext (type: {0}) was not valid during logging attempt.",
                    this.GetType());
            }
```

File: src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs [hunk 2]
```diff
@@ -171,7 +171,8 @@ private void CurrentDomainOnAssemblyLoad(object? sender, AssemblyLoadEventArgs a
             if (_loggingContext?.BuildEventContext != null)
             {
                 buildArgs.BuildEventContext = _loggingContext.BuildEventContext;
-                _loggingContext.LogBuildEvent(buildArgs);
+                // Circumvent the logging context validity check since this can happen asynchronously, when the context is being invalidated.
```
Comment (rainersigwald) [inline src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs:174]: Can you clarify _why_ the context doesn't have to be valid though? I'm afraid I don't understand.

Comment (JanKrivanek) [reply src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs:174]: Let's split this from the actuall diag improvement - as then we'll have more info (hopefully) to validate/negate the theory.

So I'll remove this change, merge this, remove fixing indication (as bug will remain) and hpefully very soon we'll have more data to support fix or further investigation.

**Comment by JanKrivanek** [comment]
@akoeplinger please not that the bug is not fixed. It'd be nice to see updated evidence once this flows into sdk and that sdk is being applied to VMR build. How often do you update the sdk there?

**Review by f-alizada — APPROVED** [review]

**Comment by akoeplinger** [comment]
@JanKrivanek we can do it on demand as needed. I can also patch/replace any dll in the SDK which used to build as part of a PR.
