### PR TITLE
Handle solution traversal targets in graph builds

### LINKED ISSUE #9952: [Bug]: Sln-based graph builds don't support the special targets with project names
### Issue Description

By default if you do somethign like `msbuild PowerToysSetup.sln -t:PowerToysInstaller`, where the project is named "PowerToysInstaller" in the sln, it will build that one project (and its dependencies) with the default targets, but also with the sln configuration.

If you add `-graph` as well though, you get errors like `Error MSB4057: The target "PowerToysInstaller" does not exist in the project.`.

The graph behavior should match the non-graph behavior.

### Steps to Reproduce

```cmd
dotnet new classlib -o Project1
dotnet new classlib -o Project2
dotnet new sln
dotnet sln add Project1
dotnet sln add Project2

# Passes
msbuild /t:Project1

# Fails
msbuild /t:Project1 /graph
```

### Expected Behavior

See description

### Actual Behavior

See description

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by dfederm**
Fixes #9952

This change adds understanding of "solution traversal" targets to graph builds. The special targets are like "ProjectName" or "ProjectName:TargetName" and can be used to build specific projects in a sln or specific targets on specific projects in a sln.

Also added some missing UTs for `SolutionProjectGenerator` to help my understanding for how these kinds of targets work.

### CODE REVIEW

File: src/Build/Graph/ProjectGraph.cs [hunk 1]
```diff
@@ -604,14 +608,92 @@ private string DebuggerDisplayString()
...
+                            if (!SolutionFile.IsBuildableProject(project))
+                            {
+                                continue;
+                            }
+
+                            string baseProjectName = ProjectInSolution.DisambiguateProjectTargetName(project.GetUniqueProjectName());
+
+                            // Solutions generate target names to build individual projects. Map these to "real" targets on the relevant projects.
+                            // This logic should match SolutionProjectGenerator's behavior
+                            if (targetName.Equals(baseProjectName, StringComparison.OrdinalIgnoreCase))
```
Comment (JanKrivanek) [inline src/Build/Graph/ProjectGraph.cs:654]: nit: `MSBuildNameIgnoreCaseComparer.Default` can be used here (but this is not a tight loop - so no big gain from it)

File: src/Build.UnitTests/Graph/ProjectGraph_Tests.cs [hunk 2]
```diff
@@ -2808,6 +2808,119 @@ public void MultitargettingTargetsWithBuildProjectReferencesFalse()
...
+
+                IReadOnlyDictionary<ProjectGraphNode, ImmutableList<string>> targetLists = projectGraph.GetTargetLists(entryTargets);
+                targetLists.Count.ShouldBe(projectGraph.ProjectNodes.Count);
+                targetLists[project1Node].ShouldBe(expectedProject1Targets);
+                targetLists[project2Node].ShouldBe(expectedProject2Targets);
+            }
+        }
+
+        [Theory]
+        [InlineData("Project1:Build")]
```
Comment (JanKrivanek) [inline src/Build.UnitTests/Graph/ProjectGraph_Tests.cs:2883]: Why is explicit `Build` target not supported?

**Review by JanKrivanek — APPROVED** [review]
Overall looks good.

I just was confused about `/t:ProjectName:Build` - why is that not supported?

File: src/Build/Graph/ProjectGraph.cs [hunk 3]
```diff
@@ -604,14 +608,92 @@ private string DebuggerDisplayString()
...
+
+                    if (!isSolutionTraversalTarget)
+                    {
+                        foreach (ProjectGraphNode entryPointNode in EntryPointNodes)
+                        {
+                            ProjectGraphBuildRequest entryEdge = new(entryPointNode,[targetName]);
+                            encounteredEdges.Add(entryEdge);
+                            edgesToVisit.Enqueue(entryEdge);
+                        }
+                    }
```
Comment (f-alizada) [inline src/Build/Graph/ProjectGraph.cs:695]: Out of curiosity: Could you please clarify if it is expected that this mentioned code block could be executed multiple times and populate the nodes to visit with the EntryPointNodes (which could result duplicate nodes to visit?)

File: src/Build/Graph/ProjectGraph.cs [hunk 4]
```diff
@@ -604,14 +608,92 @@ private string DebuggerDisplayString()
...
+                        {
+                            if (!SolutionFile.IsBuildableProject(project))
+                            {
+                                continue;
+                            }
+
+                            string baseProjectName = ProjectInSolution.DisambiguateProjectTargetName(project.GetUniqueProjectName());
+
+                            // Solutions generate target names to build individual projects. Map these to "real" targets on the relevant projects.
+                            // This logic should match SolutionProjectGenerator's behavior
```
Comment (f-alizada) [inline src/Build/Graph/ProjectGraph.cs:653]: nit: Could you please add the link to which exactly logic it should match?

**Review by f-alizada — APPROVED** [review]

File: src/Build.UnitTests/Graph/ProjectGraph_Tests.cs (hunk 2 above)
Comment (dfederm) [reply src/Build.UnitTests/Graph/ProjectGraph_Tests.cs:2883]: Not sure, it just isn't :). I'm matching the behavior of what the metaproj has today.

`SolutionProjectGenerator.EvaluateAndAddProjects` does `null` ("Project" only, no ":"), `"Clean"`, `"Rebuild"`, and `"Publish"`. So "Build" doesn't get generated there.

There is also logic there to just generate a target for whatever is provided (eg "Project:CustomTarget"), but that doesn't happen for "Build" because in `SolutionProjectGenerator.EvaluateAndAddProjects` has `_targetNames.Where(i => !traversalInstance.Targets.ContainsKey(i))`, and `CreateTraversalInstance` adds "dummy targets" apparently which does include "Build", so the previously mentioned filtering will filter it out.

File: src/Build/Graph/ProjectGraph.cs (hunk 3 above)
Comment (dfederm) [reply src/Build/Graph/ProjectGraph.cs:695]: Yep, it's expected because it needs to visit once per entry target. I considered doing the loops nested the other way, but the complexity inside the loop would be increased by doing it that way.

File: src/Build/Graph/ProjectGraph.cs (hunk 4 above)
Comment (dfederm) [reply src/Build/Graph/ProjectGraph.cs:653]: It's kinda all over that class, but I'll be a bit more targetted.
