### PR TITLE
Log glob failures

### LINKED ISSUE #9609: Log when glob expansion fails and falls back to literal
> Is there some kind of switch to turn on logging for globbing failures?

_Originally posted by @alexrp in https://github.com/dotnet/msbuild/issues/9606#issuecomment-1878918278_

### PR DESCRIPTION
**Pull request by JanProvaznik**
Fixes #9609

### Context
Logging when glob expansions fail is useful for debugging.
Log it quietly (as a message with low priority).

### Changes Made
FileMatcher.GetFiles returns a message if an exception occurs when matching files, it's callers log it.

### Testing
Covered by existing tests.
Failures which would be logged are rare.
Tested manually triggering an exception in the critical section and the message displays in binlog:
image

### Notes
Figuring out how to log is a bit tricky with some of the code being in static, some in singleton contexts and there are multiple logging mechanisms.

### CODE REVIEW

File: src/Shared/FileMatcher.cs [hunk 1]
```diff
@@ -2362,7 +2363,7 @@ private static string[] CreateArrayWithSingleItemIfNotExcluded(string filespecUn
         /// <param name="filespecUnescaped">Get files that match the given file spec.</param>
         /// <param name="excludeSpecsUnescaped">Exclude files that match this file spec.</param>
         /// <returns>The search action, array of files, and Exclude file spec (if applicable).</returns>
```
Comment (YuliiaKovalova) [inline src/Shared/FileMatcher.cs:2365]: please extend the comment to include new returning data

File: src/Shared/FileMatcher.cs [hunk 2]
```diff
@@ -2594,14 +2595,23 @@ private static string[] CreateArrayWithSingleItemIfNotExcluded(string filespecUn
                 // Flatten to get exceptions than are thrown inside a nested Parallel.ForEach
                 if (ex.Flatten().InnerExceptions.All(ExceptionHandling.IsIoRelatedException))
                 {
-                    return (CreateArrayWithSingleItemIfNotExcluded(filespecUnescaped, excludeSpecsUnescaped), trackSearchAction, trackExcludeFileSpec);
+                    return (
+                        CreateArrayWithSingleItemIfNotExcluded(filespecUnescaped, excludeSpecsUnescaped),
+                        trackSearchAction,
+                        trackExcludeFileSpec,
+                        ResourceUtilities.FormatResourceStringIgnoreCodeAndKeyword("GlobExpansionFailed", filespecUnescaped, ex.ToString()));
```
Comment (YuliiaKovalova) [inline src/Shared/FileMatcher.cs:2602]: I am wondering what ex.ToString() returns here if any inner exceptions are thrown?
Check the comment on the line 2595

File: src/Build/Utilities/EngineFileUtilities.cs [hunk 3]
```diff
@@ -332,7 +332,27 @@ private static string[] GetFileList(
...
+                                targetLoggingContext.LogCommentFromText(MessageImportance.Low, globFailure);
+                                break;
+                            case ILoggingService loggingService:
+                                loggingService.LogCommentFromText(buildEventContext, MessageImportance.Low, globFailure);
+                                break;
+                            case EvaluationLoggingContext evaluationLoggingContext:
+                                evaluationLoggingContext.LogCommentFromText(MessageImportance.Low, globFailure);
+                                break;
+                            default:
+                                throw new InternalErrorException($"Logging type {loggingMechanism.GetType()} is not understood by {nameof(GetFileList)}.");
```
Comment (YuliiaKovalova) [inline src/Build/Utilities/EngineFileUtilities.cs:352]: I believe this exception should be localized too.

File: src/Build/Utilities/EngineFileUtilities.cs [hunk 4]
```diff
@@ -332,7 +332,27 @@ private static string[] GetFileList(
                     // as a relative path, we will get back a bunch of relative paths.
                     // If the filespec started out as an absolute path, we will get
                     // back a bunch of absolute paths
-                    (fileList, _, _) = fileMatcher.GetFiles(directoryUnescaped, filespecUnescaped, excludeSpecsUnescaped);
+                    (fileList, _, _, string globFailure) = fileMatcher.GetFiles(directoryUnescaped, filespecUnescaped, excludeSpecsUnescaped);
```
Comment (YuliiaKovalova) [inline src/Build/Utilities/EngineFileUtilities.cs:335]: It looks concerning to have this tuple growing.
Should we wrap it with readable struct? @JanKrivanek ?

File: src/Shared/FileMatcher.cs [hunk 5]
```diff
@@ -1903,16 +1903,16 @@ public TaskOptions(int maxTasks)
         /// <param name="projectDirectoryUnescaped">The project directory.</param>
         /// <param name="filespecUnescaped">Get files that match the given file spec.</param>
         /// <param name="excludeSpecsUnescaped">Exclude files that match this file spec.</param>
-        /// <returns>The search action, array of files, and Exclude file spec (if applicable).</returns>
-        internal (string[] FileList, SearchAction Action, string ExcludeFileSpec) GetFiles(
+        /// <returns>The search action, array of files, Exclude file spec (if applicable), and glob failure message (if applicable) .</returns>
+        internal (string[] FileList, SearchAction Action, string ExcludeFileSpec, string GlobFailure) GetFiles(
```
Comment (YuliiaKovalova) [inline src/Shared/FileMatcher.cs:1907]: can we return nullable here?

File: src/Shared/FileMatcher.cs [hunk 6]
```diff
@@ -2377,15 +2378,15 @@ private static string[] CreateArrayWithSingleItemIfNotExcluded(string filespecUn
 
             if (action == SearchAction.ReturnEmptyList)
             {
-                return ([], action, string.Empty);
+                return ([], action, string.Empty, null);
```
Comment (YuliiaKovalova) [inline src/Shared/FileMatcher.cs:2381]: if we have this tuple wrapped with a class/structure, we would avoid having these nulls exposed, but let's hear from others @maridematte / @SimaTian / @JanKrivanek

File: src/Utilities/TrackedDependencies/TrackedDependencies.cs [hunk 7]
```diff
@@ -20,11 +20,12 @@ public static class TrackedDependencies
...
         #region Methods
         /// <summary>
-        /// Expand wildcards in the item list.
+        /// Expand wildcards in the item list and log glob failures.
         /// </summary>
         /// <param name="expand"></param>
+        /// <param name="log">For logging glob failures.</param>
         /// <returns>Array of items expanded</returns>
-        public static ITaskItem[] ExpandWildcards(ITaskItem[] expand)
+        public static ITaskItem[] ExpandWildcards(ITaskItem[] expand, TaskLoggingHelper log)
```
Comment (YuliiaKovalova) [inline src/Utilities/TrackedDependencies/TrackedDependencies.cs:28]: can be internal?

File: src/Utilities/TrackedDependencies/TrackedDependencies.cs [hunk 8]
```diff
@@ -20,11 +20,12 @@ public static class TrackedDependencies
 #pragma warning disable format // region formatting is different in net7.0 and net472, and cannot be fixed for both
         #region Methods
         /// <summary>
-        /// Expand wildcards in the item list.
+        /// Expand wildcards in the item list and log glob failures.
         /// </summary>
         /// <param name="expand"></param>
+        /// <param name="log">For logging glob failures.</param>
```
Comment (YuliiaKovalova) [inline src/Utilities/TrackedDependencies/TrackedDependencies.cs:26]: please explain when log can be null

File: src/Utilities/TrackedDependencies/TrackedDependencies.cs (hunk 7 above)
Comment (YuliiaKovalova) [inline src/Utilities/TrackedDependencies/TrackedDependencies.cs:28]: please make nullable if possible

**Comment by YuliiaKovalova** [comment]
It looks good, I have several nit comments  and a point for discussion for the tuple usage.

File: src/Shared/FileMatcher.cs (hunk 2 above)
Comment (JanProvaznik) [reply src/Shared/FileMatcher.cs:2602]: The string representation of AggregateException contains stack traces and names of all inner exceptions.

File: src/Build/Utilities/EngineFileUtilities.cs (hunk 4 above)
Comment (JanProvaznik) [reply src/Build/Utilities/EngineFileUtilities.cs:335]: We could also get rid of the 2nd and 3rd parameter altogether from the internal API. FileMatcher is `internal` and they're not used anywhere. Any reason not to do that?

Comment (JanProvaznik) [reply src/Build/Utilities/EngineFileUtilities.cs:341]: There in fact is a reason: tests use them and there is no easy way to refactor if we want to test inner behavior of file matching, we need an `internal` method returning this information. Unsure if struct would be helpful.

File: src/Shared/FileMatcher.cs (hunk 6 above)
Comment (JanKrivanek) [reply src/Shared/FileMatcher.cs:2384]: `readonly record struct` would be nice, but I do not see it as a big deal

**Review by JanKrivanek — APPROVED** [review]
Looks good

File: src/Build/Utilities/EngineFileUtilities.cs (hunk 4 above)
Comment (maridematte) [reply src/Build/Utilities/EngineFileUtilities.cs:341]: Since this is a private function and it is used on testing I think we can let this be as it is right and and maybe make an issue to improve / refactor this area with the tests in mind.

File: src/Shared/FileMatcher.cs [hunk 9]
```diff
@@ -1896,23 +1896,24 @@ public TaskOptions(int maxTasks)
...
         /// </summary>
         /// <param name="projectDirectoryUnescaped">The project directory.</param>
         /// <param name="filespecUnescaped">Get files that match the given file spec.</param>
         /// <param name="excludeSpecsUnescaped">Exclude files that match this file spec.</param>
-        /// <returns>The search action, array of files, and Exclude file spec (if applicable).</returns>
-        internal (string[] FileList, SearchAction Action, string ExcludeFileSpec) GetFiles(
-            string projectDirectoryUnescaped,
+        /// <returns>The search action, array of files, Exclude file spec (if applicable), and glob failure message (if applicable) .</returns>
+        internal (string[] FileList, SearchAction Action, string ExcludeFileSpec, string? GlobFailure) GetFiles(
+            string? projectDirectoryUnescaped,
```
Comment (maridematte) [inline src/Shared/FileMatcher.cs:1909]: If we add nullable here I think it is a good idea to add a null check so we don't fail weirdly on this one.

File: src/Shared/FileMatcher.cs [hunk 10]
```diff
@@ -2354,18 +2357,19 @@ private static string[] CreateArrayWithSingleItemIfNotExcluded(string filespecUn
...
         /// Will never throw IO exceptions: if there is no match, returns the input verbatim.
         /// </summary>
         /// <param name="projectDirectoryUnescaped">The project directory.</param>
         /// <param name="filespecUnescaped">Get files that match the given file spec.</param>
         /// <param name="excludeSpecsUnescaped">Exclude files that match this file spec.</param>
-        /// <returns>The search action, array of files, and Exclude file spec (if applicable).</returns>
-        private (string[] FileList, SearchAction Action, string ExcludeFileSpec) GetFilesImplementation(
-            string projectDirectoryUnescaped,
+        /// <returns>The search action, array of files, Exclude file spec (if applicable), and glob failure message (if applicable).</returns>
+        private (string[] FileList, SearchAction Action, string ExcludeFileSpec, string? globFailureEvent) GetFilesImplementation(
```
Comment (maridematte) [inline src/Shared/FileMatcher.cs:2369]: Same as previous ones, nullable with a null check since we do not expect things to actually be null here.

File: src/Shared/FileMatcher.cs (hunk 6 above)
Comment (maridematte) [reply src/Shared/FileMatcher.cs:2384]: I'd like to avoid the `#enable nullable` if possible. If I remember correctly there were a few PRs that were trying to remove those from the code.

File: src/Tasks/CreateItem.cs [hunk 11]
```diff
@@ -137,11 +138,10 @@ private List<ITaskItem> CreateOutputItems(Dictionary<string, string> metadataTab
         /// <summary>
         /// Expand wildcards in the item list.
         /// </summary>
-        private (ITaskItem[] Element, bool NoLoggedErrors) TryExpandWildcards(ITaskItem[] expand, string attributeType)
+        private (ITaskItem[]? Element, bool NoLoggedErrors) TryExpandWildcards(ITaskItem[]? expand, string attributeType)
         {
             // Used to detect and log drive enumerating wildcard patterns.
             string[] files;
-            FileMatcher.SearchAction action = FileMatcher.SearchAction.None;
```
Comment (maridematte) [inline src/Tasks/CreateItem.cs:144]: Is this action just never used anywhere?

File: src/Shared/FileMatcher.cs (hunk 9 above)
Comment (JanProvaznik) [reply src/Shared/FileMatcher.cs:1909]: Do you mean null check for projectDirectoryUnescaped? It is validly called with null in 2 places, that's why I annotated it.

File: src/Tasks/CreateItem.cs (hunk 11 above)
Comment (JanProvaznik) [reply src/Tasks/CreateItem.cs:144]: Yes.
