### PR TITLE
Fix processor count on Windows for multiple processor groups

### LINKED ISSUE #7943: MSBuild detects wrong processor count on Windows when debugging processor groups
### Issue Description

MSBuild detects the wrong processor count on Windows when debugging processor groups and the bug was introduced with PR: https://github.com/dotnet/msbuild/pull/5625

### Analysis

The comments in PR 5625 mentioned various ongoing issues testing processor group support on Windows due to the lack of hardware:
> I don't have a machine with > 32 cores to actually test this.
> I'm trying to pull some strings internally to borrow a machine big enough to test it on

The lack of hardware should never have been an issue. Windows has special boot parameters to enable virtual processor groups specially designed for developers to write and debug processor group support on Windows without requiring physical hardware with >64 processors. 😋

The MSDN documentation is aimed at driver developers however the same steps are required for testing and debugging usermode applications: https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-parameters-to-test-drivers-for-multiple-processor-group-support

For example:
`bcdedit.exe /set groupsize 2`

If you have 16 processors this will create 8 processor groups with 2 processors in each group and simulate a machine with > 64 processors. Usermode functions such as GetSystemInfo (and the .NET framework which is not group aware) will now only report 2 processors and this includes MSBuild because of two issues:

1) This check for `>= 32` is incompatible with the groupsize boot paramater and must be removed:
https://github.com/dotnet/msbuild/blob/65c50fb73faefec0ef2ce8256b802f50cc8236f0/src/Framework/NativeMethods.cs#L516

2) MSBuild is using a custom enumerator with GetLogicalProcessorInformationEx which is incorrect:
https://github.com/dotnet/msbuild/blob/65c50fb73faefec0ef2ce8256b802f50cc8236f0/src/Framework/NativeMethods.cs#L538-L575

Starting Windows 7 usermode applications are supposed to call [GetActiveProcessorCount](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getactiveprocessorcount) and kernel drivers [KeQueryActiveProcessorCountEx](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kequeryactiveprocessorcountex)

The `GetLogicalCoreCountOnWindows` function MSBuild is using should be removed and all the code be replaced with a single line: 
```csharp
int numberOfProcessors = GetActiveProcessorCount(ALL_PROCESSOR_GROUPS);
```
Typedefs:
```csharp
const ushort ALL_PROCESSOR_GROUPS = 0xFFFF;

[DllImport("kernel32.dll")]
public static extern int GetActiveProcessorCount(ushort GroupNumber);
```

### Steps to Reproduce
1) Open command prompt as Administrator
2) Execute `bcdedit.exe /set groupsize 2`
3) Reboot
4) MsBuild is now limited to 2 processors (on a 16 processor machine).

### Expected Behavior
MSBuild support for multiple processor groups.

### Actual Behavior
MSBuild is limited to 2 processors making testing/debugging applications significantly slower.

### PR DESCRIPTION
**Pull request by dmex**
Fixes #7943

### Context
MSBuild detects the wrong processor count on Windows when debugging processor groups

### Changes Made
Replaces GetLogicalProcessorInformationEx with GetActiveProcessorCount and removes an incorrect check for >32 processors which is incompatible with Windows boot parameters for debugging processor groups.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=7945) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=7945) before we can accept your contribution.<br/><br/>:x: dmex [sign now](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=7945)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/msbuild?pullRequest=7945) it.</sub>

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=7945) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=7945) before we can accept your contribution.<br/><br/>:x: dmex [sign now](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=7945)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/msbuild?pullRequest=7945) it.</sub>

File: src/Framework/NativeMethods.cs [hunk 1]
```diff
@@ -895,9 +822,11 @@ private static SystemInformationData SystemInformation
     [SupportedOSPlatform("windows")]
     internal static extern void GetNativeSystemInfo(ref SYSTEM_INFO lpSystemInfo);
 
-    [DllImport("kernel32.dll", SetLastError = true)]
+    const ushort ALL_PROCESSOR_GROUPS = 0xFFFF;
+
+    [DllImport("kernel32.dll")]
```
Comment (elachlan) [inline src/Framework/NativeMethods.cs:827]: No `SetLastError = true`?

Comment (dmex) [reply src/Framework/NativeMethods.cs:833]: No because when I disassembled the function it only sets 2 error codes for either passing a value > maximum groups (doesn't apply in our case because we're using ALL_PROCESSOR_GROUPS) and out-of-memory (not possible with paging).

I've never seen the function fail in production but just to be sure I partially reverted the changes so when it returns 0 for failure we fallback to Environment.ProcessorCount 👍

**Comment by rainersigwald** [comment]
This certainly looks a lot simpler! However, the previous solution was developed in consultation with devs on the Windows team, so we'll want to consult with them again. There may be some subtle behaviors that are different, or (it sure looks like) we just missed this.

**Comment by yuehuang010** [comment]
Could you verify that the count is correct on 32bit and 64bit msbuild?

**Comment by dmex** [comment]
> Could you verify that the count is correct on 32bit and 64bit msbuild?

@yuehuang010 

The count is correct for both 32bit and 64bit (32bit will only return a maximum of 32 due to limitations of the architecture).

You can test this per the documentation here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-parameters-to-test-drivers-for-multiple-processor-group-support

1) Execute `bcdedit.exe /set groupsize 2`
2) Reboot
3) GetSystemInfo() will return 2 processors and GetActiveProcessorCount returns 16 (both 32bit and 64bit)

Remember to restore the original groupsize using `bcdedit /deletevalue groupsize`

> the previous solution was developed in consultation with devs on the Windows team

@rainersigwald 

Are you able to go into details or elaborate on this solution?

I couldn't find anything in the source or any comments/PRs about the current implementation. MSBuild doesn't assign child processes or threads onto specific processors or specific groups and the current implementation basically just spawns X processes (nodes) for X processors - this PR doesn't make any changes to that design?

I did find some other problems completely unrelated to this PR... Querying the affinity/group/ideal processor for 16 MSBuild processes returned results where 7 MSBuild processes were running on the same processor: 
1,1,1,1,1,1,1,3,3,7,9,12,13,14,15,16

Windows, Linux and others essentially assign processes to processors using a round-robin type algorithm. MSBuild isn't the only program on the machine creating processes/threads and as a consequence of the current MSBuild design not having configured the processor/group; the processes (nodes) spawned by MSBuild are basically only running 1-3 processors on average instead of all 16 processors.

The lack of any processor/group assignment is also a major problem with Intel's 12th generation processors that include hybrid P-cores/E-cores because MSBuild ends up executing on the very slow/low power E-core processors instead of the fast P-core processors.

**Comment by elachlan** [comment]
Stumbled upon this change in .NET that was supposed to fix `Environment.ProcessorCount`: https://github.com/dotnet/runtime/pull/68639

**Comment by rainersigwald** [comment]
> The count is correct for both 32bit and 64bit (32bit will only return a maximum of 32 due to limitations of the architecture).

If this is the case, this is not an acceptable approach--the previous implementation was designed explicitly to avoid that limitation. It's not that unusual to run >32 32-bit MSBuild.exe processes on a big machine.

**Comment by yuehuang010** [comment]
> The count is correct for both 32bit and 64bit (32bit will only return a maximum of 32 due to limitations of the architecture).

I do think this point is dulled as most people will use 64bit msbuild.  For completeness, the OS can be 64bit running a 32bit MSBuild.  If the API caps at 32, then it wouldn't fully utilize the machine.

**Comment by rainersigwald** [comment]
> Are you able to go into details or elaborate on this solution?

The solution is what was checked in with #5625; comments there starting with https://github.com/dotnet/msbuild/pull/5625#issuecomment-686797187 describe the various problems we ran into.

**Comment by rainersigwald** [comment]
> I do think this point is dulled as most people will use 64bit msbuild.

This is less true than I wish it was--many build processes never moved to 64-bit, and often you can get away with it indefinitely, especially if tools moved to 64-bit transparently.

**Comment by yuehuang010** [comment]
Nit. I used System.Environment.GetEnvironmentVariables(), then envs["NUMBER_OF_PROCESSORS"].  This returned the correct value in all of my cases.

**Comment by dmex** [comment]
> If this is the case, this is not an acceptable approach

I can revert the changes back to `RelationProcessorCore`? The GetActiveProcessorCount changes are optional but the check for `(numberOfCpus >= 32)` needs to be removed.

> the previous implementation was designed explicitly to avoid that limitation. 

There are two severe issues with that implementation:
1) MSBuild is executing on E-Core processors instead of P-Core processors.
2) MSBuild does not assign nodes (child processes) to specific groups/processors.

Both of these issues are introducing a significant performance issues and preventing MSBuild from utilizing the available hardware.

> It's not that unusual to run >32 32-bit MSBuild.exe processes on a big machine.

The benefits of using RelationProcessorCore in this case are highly suspect because Windows doesn't automatically spread MSBuild evenly across all processors and processor groups unless you're manually assigning specific groups/processors (at least prior to Windows 11) - which MSBuild doesn't implement.

If you have 128 processors then yeah MSBuild is creating 128 processes... However, MSBuild never gets assigned to all processors and groups because other programs and services are created/destroyed and were assigned those processors/groups by Windows instead of MSBuild. Just opening Edge/Chrome (or even notepad) is enough to push MSBuild onto the wrong processor/group and introduce performance issues.

What MSBuild should be doing:
64 processes are executing on group 0 using processors 0-64
64 processes are executing on group 1 using processors 64-128

What's actually happening at the moment (at least every XYZ number of builds):
90 processes are executing on group 0 
38 processes are executing on group 1


26 processes were incorrectly assigned the same processor group leaving 26 processors from the other group completely underutilized. 

The best way to fix this would be passing the specific processor/group to the node via commandline and then call SetThreadGroupAffinity from the child otherwise whatever value you're getting from RelationProcessorCore is almost completely useless and is causing performance issues from creating way too many processes on the one group instead of across multiple groups.

> This is less true than I wish it was--many build processes never moved to 64-bit, and often you can get away with it indefinitely, especially if tools moved to 64-bit transparently.

Visual Studio 2022 discontinued 32-bit kernels and drivers. 32-bit Windows was also discontinued a few years ago and can't be downloaded. The last version of MSBuild that can be used to compile 32-bit in our case is `16.11.2.50704`

The large majority still needing 32-bit are going to be using VS2019 almost indefinitely because of the changes with VS2022. Is it still the case 32bit must be the default or can 64-bit MSBuild be the default going forward?

**Comment by rainersigwald** [comment]
> * MSBuild is executing on E-Core processors instead of P-Core processors.

My understanding is that the standard guidance for multicore/multiprocess systems is to completely disregard core type and let the OS handle pulling hot processes to better cores, and that in an "I can completely saturate all cores" situation, it's best to run on all types of cores. Do you know otherwise?

> 2\. MSBuild does not assign nodes (child processes) to specific groups/processors.

This is by design. The OS can handle this, and it is very likely to be optimal to allow MSBuild.exe processes to wander across cores/groups, since the nature of MSBuild work is I/O intensive and involves a lot of blocking waits on other tools (like compilers).

> 26 processes were incorrectly assigned the same processor group leaving 26 processors from the other group completely underutilized.

Do you see concrete performance implications of this? As mentioned, I would not expect this to be a concrete problem.

> Is it still the case 32bit must be the default or can 64-bit MSBuild be the default going forward?

It is already the case (as of VS 2022) that 64-bit MSBuild is the default on `PATH` and the only way to build using the Visual Studio UI, but Azure DevOps build definitions generally hardcode the x86 implementation (unless overridden) and thus many "official builds" are still on 32-bit MSBuild. Those builds can and often do run tasks that aren't run in developer-desktop builds, so they may not "just work" with a switch.

Note that OS architecture isn't relevant here: we're talking about 32-bit MSBuild running on 64-bit Windows.

**Review by rainersigwald — APPROVED** [review]

**Review by Forgind — APPROVED** [review]
