### PR TITLE
[Graph] Emit NoTargetSpecified when an entry point project doesn't have any targets

### LINKED ISSUE #9502: [Bug]: /graph builds succeed when there is not target in project file
### Issue Description

When the project file has no target and no type of build (no `sdk=...` or anything else) and you try to build it fails with `error MSB4040: There is no target in the project.` which is expected. If you try to build the same project but with the `/graph` argument the build succeeds.

This is true with `dotnet build` and with `MSBuild.exe` from VS 2022.

### Steps to Reproduce

1. Create a new console app (dotnet new console)
2. From the project file, delete the `sdk` definition in `<Project>`
3. Try to build the project with `/graph` option

### Expected Behavior

Build fails with `error MSB4040: There is no target in the project.`

### Actual Behavior

Builds says it succeeded when it did not.

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by dfederm**
Fixes #9502

This change checks the entry point nodes in a graph to see if any targets are specified. This will error similarly to non-graph builds when the project has no targets.

Tested using a project with the content: `<Project />`.

Non-graph behavior:

image

Current graph behavior (incorrect):

image

New graph behavior (corrected):

image

Note: Non-entry points without targets actually are not a problem. In the non-graph scenario, the (valid) referencing project will execute `_GetProjectReferenceTargetFrameworkProperties` which calls `GetTargetFrameworks` on the referenced project. If the target doesn't exist (or in this case, *no* targets exist), then the call no-ops (due to `SkipNonexistentTargets="true"` being set) and the `ProjectReference` is essentially filtered out.

### CODE REVIEW

**Review by jeffkl — APPROVED** [review]

File: src/Build.UnitTests/BackEnd/BuildManager_Tests.cs [hunk 1]
```diff
@@ -4408,5 +4408,29 @@ public void TaskInputLoggingIsExposedToTasks(string taskFactory, bool taskInputL
...
+
+            _logger.AssertLogContains("MSB4040");
+        }
+
+        [Fact]
+        public void ProjectWithNoTargetsGraph()
+        {
+            string contents = @"<Project />";
+
+            GraphBuildRequestData data = GetGraphBuildRequestData(contents);
```
Comment (JanKrivanek) [inline src/Build.UnitTests/BackEnd/BuildManager_Tests.cs:4429]: Not related to this PR - just wondering why BuildRequestData and GraphBuildRequestData doesn't have a common ancestor (interface or abstract class) so that we do not have to have that much code duplication (The `Build` methods are otherwise identical, the calls to `Build` - as e.g. here seems identical as well). Do you know about any strong reasons why they are kept copletely separate? (I'm contemplating creating a refactoring item for that)

**Review by JanKrivanek — APPROVED** [review]
Looks good

**Review by ladipro — APPROVED** [review]
Looks good! @dfederm, can you please resolve the conflict?

File: src/Build.UnitTests/BackEnd/BuildManager_Tests.cs (hunk 1 above)
Comment (dfederm) [reply src/Build.UnitTests/BackEnd/BuildManager_Tests.cs:4367]: No particular reason. Might help reduce some of the code duplicate in fact.
