### PR TITLE
Fix NRE in target batching

### LINKED ISSUE #10180: [Bug]: NRE in at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext()
### Issue Description

MSBUILD : error : This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices
.UnitTests\MSTestAdapter.PlatformServices.UnitTests.csproj]
MSBUILD : error :     System.NullReferenceException: Object reference not set to an instance of an object. [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.
UnitTests.csproj]
MSBUILD : error :    at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext() [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.cspro
j]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.cs
proj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests
.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.Platf
ormServices.UnitTests.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.csproj
]
MSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext() [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTest
s.csproj]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.cs
proj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests
.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.Platf
ormServices.UnitTests.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.csproj
]
MSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext() [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.cspr
oj]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.cs
proj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests
.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.Platf
ormServices.UnitTests.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.csproj
]
MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__67.MoveNext() [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.csp
roj]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests.cs
proj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTests
.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.Platf
ormServices.UnitTests.csproj]
MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext() [C:\src\testfx\test\UnitTests\MSTestAdapter.PlatformServices.UnitTests\MSTestAdapter.PlatformServices.UnitTest
s.csproj]

### Steps to Reproduce

Checkout https://github.com/microsoft/testfx/pull/2973 and run `.\Build.cmd /p:NuGetInteractive=true -pack -test -integrationTest`

### Expected Behavior

No error

### Actual Behavior

NRE

### Analysis

_No response_

### Versions & Configurations

_No response_

### PR DESCRIPTION
**Pull request by ladipro**
Fixes #10180

### Context

#10102 made certain batching scenarios fail with a null-ref exception.

### Changes Made

Moved the call to `LogTargetBatchFinished` to make sure that the loop doesn't exit with null `targetLoggingContext`.

### Testing

New unit test with a repro project.

### CODE REVIEW

**Review by maridematte — APPROVED** [review]

File: src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs [hunk 1]
```diff
@@ -452,6 +452,10 @@ internal async Task ExecuteTarget(ITaskBuilder taskBuilder, BuildRequestEntry re
                         break;
                     }
 
+                    // Don't log the last target finished event until we can process the target outputs as we want to attach them to the
+                    // last target batch. The following statement logs the event for the bucket processed in the previous iteration.
+                    targetLoggingContext?.LogTargetBatchFinished(projectFullPath, targetSuccess, null);
```
Comment (YuliiaKovalova) [inline src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs:457]: But is it ok, that we log "Finish" event, before "Start" ?
Can we place it under LogTargetBatchStarted?

Comment (ladipro) [reply src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs:457]: Actually, no, I would prefer to keep these two calls together so we never reset `targetLoggingContext` to null and we finish the previous bucket just before we start the new one. But I'll add an extra `if` to make the logic clearer.

**Review by YuliiaKovalova — APPROVED** [review]

**Review by AR-May — APPROVED** [review]
