### PR TITLE
Fix GenerateResource to track all ResXFileRef linked files for incremental builds

### LINKED ISSUE #13158: GenerateResource Task for EmbeddedResource with Linked Files Does not Detect Changes for Text Files
### Issue Description

I have files linked into my Resx file which is getting built into my project. When I change the contents of a text file and then save the resource is not regenerated when I build. However, something like an image file linked into my Resx will trigger resource generation upon changes.

### Steps to Reproduce

demo-project.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>bug_demo_resgen</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.2" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.2" />
  </ItemGroup>

</Project>
```

TestResource.resx:
```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="MyResourceText" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>MyResourceText.txt;System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="TestImage" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>TestImage.bmp;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</value>
  </data>
</root>
```

Referenced resources:
- [MyResourceText.txt](https://github.com/user-attachments/files/24983089/MyResourceText.txt)
- [TestImage.bmp](https://github.com/user-attachments/files/24983088/TestImage.bmp)

To reproduce the error:
1. Build the project
2. Change the contents of MyResourceText.txt and save, then build the project (NOT rebuild). Notice that the resource is not regenerated
3. Change the contents of TestImage.bmp and save, then build the project (NOT rebuild). Notice that the resource IS regenerated

### Expected Behavior

My expectation is that changes to any `System.Resources.ResXFileRef` should cause the resource to be regenerated in the build.

### Actual Behavior

Instead, only changes to certain linked file types are causing the resource to be regenerated.

### Analysis

I believe this is caused by [ResXFile.GetLinkedFile](https://github.com/dotnet/msbuild/blob/main/src/Tasks/ResGenDependencies.cs#L268) here checking only for the type `FileStreamResource`. Looking at [MSBuildResXReader.GetResourcesFromFile](https://github.com/dotnet/msbuild/blob/main/src/Tasks/ResourceHandling/MSBuildResXReader.cs#L285) the only way to get a `FileStreamResource` returned from that is for it NOT to be a `String` or a `Byte[]` or a `MemoryStream`.

Logically, I would like for everything which is a `type="System.Resources.ResXFileRef"` to be considered for triggering a regeneration of the resource file and not just the things which are NOT `String`/`Byte[]`/`MemoryStream`. Is the current implemented some kind of build optimization or speedup? If so, are there any switches I could use to turn it off?

### Versions & Configurations

```
> msbuild -version
MSBuild version 17.14.23+b0019275e for .NET Framework
17.14.23.42201
```

```
> dotnet -version
10.0.102
```

### PR DESCRIPTION
**Pull request by OvesN**
Fixes #13158

### Context

`ResGenDependencies.GetResXFileReferenceDependencies` tracked linked file dependencies for incremental builds by checking `resource is FileStreamResource`. However, `MSBuildResXReader.AddLinkedResource` only produces a `FileStreamResource` for types that are **not** `String`, `Byte[]`, or `MemoryStream`. Those three common cases were returned as `StringResource` / `LiveObjectResource` instead, meaning their linked file paths were invisible to the dependency tracker.

As a result, modifying a text file or byte-array file linked via `ResXFileRef` did not trigger resource regeneration on incremental build, while modifying an image (e.g., `.bmp` linked as `System.Drawing.Bitmap`) did.

### Changes Made

- **New interface `ILinkedFileResource : IResource`** with a nullable `LinkedFilePath` property, representing any resource that originated from a `ResXFileRef` entry. This interface is implemented by the following classes: **`LiveObjectResource`**,  **`StringResource`**,**`FileStreamResource`**
- **`ResGenDependencies`** checks `resource is ILinkedFileResource linked && linked.LinkedFilePath is not null` instead of `resource is FileStreamResource`, so all `ResXFileRef` types are tracked.

### Testing

- Added `InlineStringIsNotLinkedFileResource` — verifies inline string resources have `LinkedFilePath == null`.
- Added `FileRefStringIsLinkedFileResource` — verifies string file refs have non-null `LinkedFilePath`.
- Added `LinkedFilesTrackedForAllResourceTypes` — verifies that `GetResXFileInfo` with `useMSBuildResXReader: true` tracks linked files for all resource types (`System.String`, `System.Byte[]`, `System.IO.MemoryStream`, and `System.Drawing.Bitmap`), not just `FileStreamResource`.
- -Added `ForceOutOfDateLinkedTextFile` — regression test that exercises the full `GenerateResource` task: creates a resx with a linked text file (`System.String`), runs the task, touches the text file, runs again, and asserts the `.resources` output was regenerated (this scenario previously failed because text-linked files weren't tracked).
- Manual end-to-end verification: built a project with linked text and image resources, modified the text file, confirmed incremental build regenerates the `.resources` file (previously skipped).

### CODE REVIEW

File: src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs [hunk 1]
```diff
@@ -4040,6 +4089,24 @@ public static void AssertLogNotContains(GenerateResource t, string message)
...
+            {
+                if ((string)enumerator.Key == resourceName)
+                {
+                    return enumerator.Value;
+                }
+            }
+
+            throw new KeyNotFoundException($"Resource '{resourceName}' not found in '{resourcesFilePath}'.");
+        }
+
```
Comment (JanProvaznik) [inline src/Tasks.UnitTests/ResourceHandling/GenerateResource_Tests.cs]: docstrings are broken (doubled summary in first function, no summary in the second)

File: src/Tasks/ResourceHandling/FileStreamResource.cs [hunk 2]
```diff
@@ -8,15 +8,15 @@
 
 namespace Microsoft.Build.Tasks.ResourceHandling
 {
-    internal class FileStreamResource : IResource
+    internal class FileStreamResource : ILinkedFileResource
```
Comment (JanProvaznik) [inline src/Tasks/ResourceHandling/FileStreamResource.cs:11]: I like this naming 👍

File: src/Tasks/ResourceHandling/ILinkedFileResource.cs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+    internal interface ILinkedFileResource : IResource
+    {
+        /// <summary>
+        /// The path of the file this resource was read from. This may be an absolute
+        /// or relative path depending on how the resource was resolved (for example,
+        /// whether paths were made relative to a base path). A value of
+        /// <see langword="null"/> indicates that this resource is not linked
+        /// to an external file.
+        /// </summary>
+        string? LinkedFilePath { get; }
```
Comment (JanProvaznik) [inline src/Tasks/ResourceHandling/ILinkedFileResource.cs]: when does the `null` case happen? 

I am confused what does it mean for an object to implement an interface indicating "I have a linked file" but then not have the linked file.

File: src/Tasks/ResourceHandling/LiveObjectResource.cs [hunk 4]
```diff
@@ -10,16 +10,18 @@ namespace Microsoft.Build.Tasks.ResourceHandling
     /// <summary>
     /// Name value resource pair to go in resources list
     /// </summary>
-    internal class LiveObjectResource : IResource
+    internal class LiveObjectResource : ILinkedFileResource
     {
-        public LiveObjectResource(string name, object value)
+        public LiveObjectResource(string name, object value, string linkedFilePath = null)
```
Comment (JanProvaznik) [inline src/Tasks/ResourceHandling/LiveObjectResource.cs]: I hate default values in method/constructor parameters. It makes it confusing how the nulls get in
1. when is it expected to be null?
2. could you refactor to explicitly pass null if that's necessary?

File: src/Tasks/ResourceHandling/ILinkedFileResource.cs (hunk 3 above)
Comment (OvesN) [reply src/Tasks/ResourceHandling/ILinkedFileResource.cs]: Yeah, this is because of LiveObjectResource, which can be constructed either from a file or without a file (StringResource inherits from this class).
So I was torn between three solutions:

1. The one I implemented: add a new interface with an optional linkedFilePath. Only resources that can have a linked file would implement it.
Cons: because of LiveObjectResource, linkedFilePath still has to be nullable.

2. Make linkedFilePath a nullable field directly on IResource, so every resource would have it and only fill it in when needed.
Cons: unnecessary declaration for resources that can never have a linked file.

3. To guarantee that ILinkedFileResource always has a linked file, introduce new classes like LiveObjectLinkedFileResource and StringLinkedFileResource.
This would allow linkedFilePath to be non‑nullable.

I’m not really a fan of any of these solutions, but I chose the first one. Do you think we should consider implementing the third option so that linkedFilePath is truly always non‑null?

File: src/Tasks/ResourceHandling/LiveObjectResource.cs (hunk 4 above)
Comment (OvesN) [reply src/Tasks/ResourceHandling/LiveObjectResource.cs]: It is non‑null only when we construct LiveObjectResource from System.Resources.ResXFileRef (byte array, MemoryStream).
It is expected to be null when we construct LiveObjectResource:

1. From System.Resources.ResXNullRef
2. When MimeType is null and the value is a byte array
3. When we use ResXResourceReader

OK, I will explicitly pass null.

File: src/Tasks/ResourceHandling/ILinkedFileResource.cs (hunk 3 above)
Comment (JanProvaznik) [reply src/Tasks/ResourceHandling/ILinkedFileResource.cs]: I am a fan of 3. so the type hiearchy would be
```
   IResource
   ├── LiveObjectResource                      
   │   ├── StringResource                      
   │   │   └── LinkedStringResource : ILinkedFileResource    ← NEW
   │   └── LinkedLiveObjectResource : ILinkedFileResource    ← NEW
   ├── FileStreamResource : ILinkedFileResource   (already always linked)
   ├── TypeConverterStringResource
   ├── TypeConverterByteArrayResource
   └── BinaryFormatterByteArrayResource
```

File: src/Tasks/ResourceHandling/StringResource.cs [hunk 5]
```diff
@@ -13,8 +13,8 @@ internal class StringResource : LiveObjectResource
 
         public new string TypeFullName => typeof(string).FullName;
 
-        public StringResource(string name, string value, string filename) :
-            base(name, value)
+        public StringResource(string name, string value, string filename, string linkedFilePath = null) :
```
Comment (JanProvaznik) [inline src/Tasks/ResourceHandling/StringResource.cs]: I suppose with the refactor 3. this default value won't be needed :)

File: src/Tasks/ResourceHandling/ILinkedFileResource.cs (hunk 3 above)
Comment (OvesN) [reply src/Tasks/ResourceHandling/ILinkedFileResource.cs]: Ok I implemented the third option

File: src/Tasks/ResourceHandling/LinkedLiveObjectResource.cs [hunk 6]
```diff
@@ -0,0 +1,22 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+#nullable disable
```
Comment (baronfel) [inline src/Tasks/ResourceHandling/LinkedLiveObjectResource.cs]: New code shouldn't disable nullable without a good reason IMO
