### PR TITLE
Use CopyOnWritePropertyDictionary.ImportProperties for batching

### LINKED ISSUE #8673: [Performance]: High memory allocations in CopyOnWritePropertyDictionary ImmutableDictionary
### Issue Description

While investigating [this OOP memory allocation OrchardCore speedometer bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1782426), I noticed a large amount of [allocations here](https://github.com/dotnet/msbuild/blob/cc55017f88688cbe3f9aa810cdf44273adea76ea/src/Build/Instance/ProjectItemInstance.cs#L1702) due to not batch updating the immutable dictionary. 

### Steps to Reproduce

Speedoemeter test opens OrchardCore solution, waits for quite a while, does a bit of solution navigation, closes the solution.

### Data

Traces available through speedometer bug.

753986f7-0108-4881-9bb2-9f5f5ebd4132

### Analysis

_No response_

### Versions & Configurations

_No response_

### Regression

- [ ] yes
- [ ] no

### Regression Details

_No response_

### PR DESCRIPTION
**Pull request by rokonec**
Fixes #8673

### Context
High memory allocations in CopyOnWritePropertyDictionary ImmutableDictionary was reported by partners.

### Changes Made
Use `CopyOnWritePropertyDictionary.ImportProperties` in obvious places as oppose to `CopyOnWritePropertyDictionary.Set` in loop.

### Testing
Unit tests. Local. Perf measure.

### CODE REVIEW

File: src/Build/Instance/ProjectItemInstance.cs [hunk 1]
```diff
@@ -1695,11 +1697,21 @@ internal void TranslateWithInterning(ITranslator translator, LookasideStringInte
                     {
                         int count = translator.Reader.ReadInt32();
                         _directMetadata = (count == 0) ? null : new CopyOnWritePropertyDictionary<ProjectMetadataInstance>();
```
Comment (rainersigwald) [inline src/Build/Instance/ProjectItemInstance.cs:1699]: Is this line redundant now?

**Review by rainersigwald — APPROVED** [review]

File: src/Build/Instance/ProjectItemInstance.cs (hunk 1 above)
Comment (rokonec) [reply src/Build/Instance/ProjectItemInstance.cs:1699]: Yes, it is leftover. Good catch. Deleted.

File: src/Build/Instance/ProjectItemInstance.cs [hunk 2]
```diff
@@ -1096,40 +1093,45 @@ internal CopyOnWritePropertyDictionary<ProjectMetadataInstance> MetadataCollecti
...
                     CopyOnWritePropertyDictionary<ProjectMetadataInstance> allMetadata = new CopyOnWritePropertyDictionary<ProjectMetadataInstance>();
 
-                    // Next, any inherited item definitions. Front of the list is highest priority,
-                    // so walk backwards.
-                    for (int i = _itemDefinitions.Count - 1; i >= 0; i--)
+                    allMetadata.ImportProperties(metaData());
+
+                    return allMetadata;
+
+                    IEnumerable<ProjectMetadataInstance> metaData()
```
Comment (JanKrivanek) [inline src/Build/Instance/ProjectItemInstance.cs:1100]: Weird casing and naming.
GetOrderedMetadata/OrderMetadata/GetMetadata?

File: src/Build/Instance/ProjectItemInstance.cs [hunk 3]
```diff
@@ -1096,40 +1093,45 @@ internal CopyOnWritePropertyDictionary<ProjectMetadataInstance> MetadataCollecti
...
                         {
-                            if (metadatum != null)
-                            {
-                                allMetadata.Set(metadatum);
-                            }
-                            else
+                            foreach (ProjectMetadataInstance metadatum in _itemDefinitions[i].Metadata)
                             {
-                                Debug.Fail($"metadatum from {_itemDefinitions[i]} is null, see https://github.com/dotnet/msbuild/issues/5267");
+                                if (metadatum != null)
```
Comment (JanKrivanek) [inline src/Build/Instance/ProjectItemInstance.cs:1108]: Should this check be pushed to `CopyOnWritePropertyDictionary.ImportProperties` to avoid double iteration?

**Review by JanKrivanek — APPROVED** [review]
Overal looks good. I have just 2 minor points for consideration

File: src/Build/Instance/ProjectItemInstance.cs (hunk 2 above)
Comment (rokonec) [reply src/Build/Instance/ProjectItemInstance.cs:1100]: I kinda like localFunction naming schema. Have seen it in Roslyn and use it since.

File: src/Build/Instance/ProjectItemInstance.cs (hunk 3 above)
Comment (rokonec) [reply src/Build/Instance/ProjectItemInstance.cs:1108]: What check in particular?

File: src/Build/Instance/ProjectItemInstance.cs (hunk 2 above)
Comment (JanKrivanek) [reply src/Build/Instance/ProjectItemInstance.cs:1100]: I was rather refering to treating metadata as 2 words (metaData) and absence of verb in the function name.
First letter casing - my opinion - whatever is already used in our code... and if nothing - feel free to set the convention :-)

Comment (rokonec) [reply src/Build/Instance/ProjectItemInstance.cs:1100]: These days I personally prefer not to include redundant information into naming. I tend to consider Get verb prefix as implicit. I mean if function name is just `nouns()` is is implicit that it will somehow GET me `nouns`. Given the small scope and close locality of this method, more describing names like `GetAllMetaDataOrderedAsLastWinForClonePurpose` is maybe not needed .
But It is matter of taste and I don't mind to change it though.

**Review by ladipro — APPROVED** [review]
super-nit: Would it make sense to add a constructor to `CopyOnWritePropertyDictionary<T>` taking `IEnumerable<T>`?

**Comment by rokonec** [comment]
@ladipro 
>  Would it make sense to add a constructor to CopyOnWritePropertyDictionary<T> taking IEnumerable<T>

I would make sense for code readability, but since the constructor `CopyOnWritePropertyDictionary<T>` use `static Empty` pattern,  it should result in same amount of allocations as current code. I was trying not to change API of CopyOnWritePropertyDictionary.

File: src/Build/Instance/ProjectInstance.cs [hunk 4]
```diff
@@ -2942,11 +2942,9 @@ private void CreateEvaluatedIncludeSnapshotIfRequested(bool keepEvaluationCache,
                 if (item.DirectMetadata != null)
                 {
                     directMetadata = new CopyOnWritePropertyDictionary<ProjectMetadataInstance>();
-                    foreach (ProjectMetadata directMetadatum in item.DirectMetadata)
-                    {
-                        ProjectMetadataInstance directMetadatumInstance = new ProjectMetadataInstance(directMetadatum);
-                        directMetadata.Set(directMetadatumInstance);
-                    }
+
+                    IEnumerable<ProjectMetadataInstance> projectMetadataInstances = item.DirectMetadata.Select(directMetadatum => new ProjectMetadataInstance(directMetadatum));
```
Comment (danmoseley) [inline src/Build/Instance/ProjectInstance.cs:2946]: Is Select and delegate here as efficient as a plain loop?

The core libraries would not use this, I think (@stephentoub?)

Comment (stephentoub) [reply src/Build/Instance/ProjectInstance.cs:2946]: > Is Select and delegate here as efficient as a plain loop?

It depends on several factors, including what DirectMetadata is.

> The core libraries would not use this, I think (@stephentoub?)

It also depends :) but generally we avoid use of `IEnumerable<T>` manipulation on hot paths.

Comment (rokonec) [reply src/Build/Instance/ProjectInstance.cs:2946]: Purpose of this changes was to eliminate generation of `ImmutableDictionary` in a loop which has very very bad  CPU and memory allocation consequences. 
To do that I decided to use prior existing `internal void ImportProperties(IEnumerable<T> other)` method which calls  `public ImmutableDictionary<TKey, TValue> SetItems(IEnumerable<KeyValuePair<TKey, TValue>> items)` internally.
I do not see how to avoid `IEnumerable<T>` here, unless we would change `CopyOnWritePropertyDictionary` API to somehow expose immutable builder. I don't think this path is that hot though.
