### PR TITLE
Exempt our env var Fixes #7922

### LINKED ISSUE #7922: DOTNET/COMPlus/MSBUILD environment variables should be logged by default
> At the moment, I don't have a good guess because `DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER` isn't mentioned in any .binlog from the build that I checked. It feels like environment variables that aren't directly used in the build (e.g. `COMPlus_DbgEnableMiniDump` in our other jobs) aren't logged anymore. That leaves me w/ insufficient information to debug the problem.
> 
> The suggestion in Structured Log viewer is to
> 
> ```
> Define a value for MSBUILDLOGALLENVIRONMENTVARIABLES to log all environment variables. Only those used in evaluating properties are currently logged.
> ```
> 
> but that's very time-consuming when it takes a CI build to reproduce the problem. This feels like a regression @rainersigwald.
> 
> Should we unconditionally add `MSBUILDLOGALLENVIRONMENTVARIABLES: true` in all CI jobs that may produce binary logs❔

We should add an allowlist for `MSBUILD*`, `COMPlus_*`, and `DOTNET_*` variables at the bare minimum. (`DOTNET_*` is a synonym for `COMPLUS_*` now).

_Originally posted by @rainersigwald in https://github.com/dotnet/aspnetcore/issues/43028#issuecomment-1230617069_

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #7922

### Context
Although it's good to hide environment variables that may contain sensitive information, some variables seldom do and can be quite helpful in diagnosing build issues. This exempts environment variables that start with MSBUILD, COMPLUS_, and DOTNET_ from the normal filtering, even in the absence of MSBUILDLOGALLENVIRONMENTVARIABLES.

### Changes Made
Exempted certain environment variables. Also prevented any EnvironmentVariableReadEvents from firing if MSBUILDLOGALLENVIRONMENTVARIABLES is set.

### Testing
I built MSBuild.Dev.slnf and checked what its environment node contained.

### Notes
This will need a structured log viewer update to make it less confusing.

~Confusing to me, this only almost works. Specifically, it filtered out all environment variables except the intended ones _plus_ OS, LOCALAPPDATA, and USERPROFILE. I don't know what made those special.~

### CODE REVIEW

**Comment by dougbu** [comment]
> &hellip; _plus_ OS, LOCALAPPDATA, and USERPROFILE. I don't know what made those special.

Naively, aren't those properties almost always used in `msbuild` evaluation❔ For example, `UserProfile` is normally evaluated to determine `LocalAppData`, that's normally evaluated to determine `$(MSBuildUserExtensionsPath)`, and that's evaluated to look for default files to import.

**Comment by Forgind** [comment]
I think you're right; this was just the viewer displaying things differently than I'd expected. I tried grabbing a diagnostic text log, and it looks good. I also tried replaying a binlog into a text log, and that looks good, too.

File: src/Build/Logging/BinaryLogger/BinaryLogger.cs [hunk 1]
```diff
@@ -53,7 +53,9 @@ public sealed class BinaryLogger : ILogger
         //   - TargetSkippedEventArgs: added OriginallySucceeded, Condition, EvaluatedCondition
         // version 14:
         //   - TargetSkippedEventArgs: added SkipReason, OriginalBuildEventContext
-        internal const int FileFormatVersion = 14;
+        // version 15:
+        //   - Log our own environment variables by default. (This affects the message in the structured log viewer.)
```
Comment (rainersigwald) [inline src/Build/Logging/BinaryLogger/BinaryLogger.cs:57]: I don't understand this. There's no actual change, but you want a marker to change things in the viewer?

File: src/Build/Evaluation/Evaluator.cs [hunk 2]
```diff
@@ -824,8 +824,9 @@ private IEnumerable FilterOutEnvironmentDerivedProperties(PropertyDictionary<P>
             List<P> list = new(dictionary.Count);
             foreach (P p in dictionary)
             {
-                if (p is EnvironmentDerivedProjectPropertyInstance ||
-                    (p is ProjectProperty pp && pp.IsEnvironmentProperty))
+                if ((p is EnvironmentDerivedProjectPropertyInstance ||
+                    (p is ProjectProperty pp && pp.IsEnvironmentProperty)) &&
+                    !EnvironmentUtilities.IsReservedProperty(p.Name))
```
Comment (rainersigwald) [inline src/Build/Evaluation/Evaluator.cs:829]: This logic is pretty complicated even in the context of this PR where I know what you're trying to do. Comment?

**Review by rainersigwald — COMMENTED** [review]
Overall this is larger than I expected. I anticipated something like "when handling build started events, log again". Can you explain why so many parts of the code have to be touched?

File: src/Shared/EnvironmentUtilities.cs [hunk 3]
```diff
@@ -12,5 +12,12 @@ internal static partial class EnvironmentUtilities
 
         public static bool Is64BitOperatingSystem =>
             Environment.Is64BitOperatingSystem;
+
+        public static bool IsReservedProperty(string propertyName)
```
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Shared/EnvironmentUtilities.cs:16]: I'm paralleling our many uses of "reserved" in other places in MSBuild like:
https://github.com/dotnet/msbuild/blob/main/src/Build/Resources/Constants.cs#L102
https://github.com/dotnet/msbuild/blob/main/src/Build/Definition/ProjectProperty.cs#L146
https://github.com/dotnet/msbuild/blob/main/src/Build/ObjectModelRemoting/LinkedObjectFactory.cs#L305

Those are "reserved" in that they are normal properties except that Microsoft specifically recognizes them as special, just as keywords are normal tokens treated as special in programming languages. MSBUILD*, COMPLUS_*, and DOTNET_* are being treated as special, so it makes sense to me that they are also "reserved."

ShouldAlwaysBeLogged makes sense in the context of this PR but does not make sense if you don't know what they are or why they should be logged—what is being explicitly excluded from this?

[the remark this answers is not in the document]
Comment (rainersigwald) [reply src/Shared/EnvironmentUtilities.cs:16]: Reserved properties are not normal properties. If you try to set them, you get an error like

```
error MSB4004: The "MSBuildProjectDirectory" property is reserved, and cannot be modified.
```

Since this isn't like that, I don't think it should use the same name.

File: src/Build/Logging/BinaryLogger/BinaryLogger.cs (hunk 1 above)
Comment (Forgind) [reply src/Build/Logging/BinaryLogger/BinaryLogger.cs:57]: This may end up reverted.

My original scheme was to use this to indicate we should change the string displayed when the user did not specify that they want all environment variables logged—it would say something like "we don't log env vars unless you set x," and it would now say "this list of env vars was truncated to just include y; set x to include them all." Sounds like KirillOsenkov thinks we can word it to make sense in either case. I owe him a reply.

File: src/Shared/EnvironmentUtilities.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Shared/EnvironmentUtilities.cs:16]: Properties prefixed with an underscore are private but not really. If you try to use one of these as a normal variable, you may get unexpected behavior at some point.

Compromise on IsWellKnownEnvironmentDerivedProperty?

[the remark this answers is not in the document]
Comment (rainersigwald) [reply src/Shared/EnvironmentUtilities.cs]: `IsWellKnownEnvironmentDerivedProperty` sounds fine to me.

File: src/Build/Logging/BinaryLogger/BinaryLogger.cs (hunk 1 above)
Comment (Forgind) [reply src/Build/Logging/BinaryLogger/BinaryLogger.cs]: I was convinced, so I reverted this. To prevent version weirdness, I think we should make sure this makes it into 17.4.

Comment (rainersigwald) [reply src/Build/Logging/BinaryLogger/BinaryLogger.cs]: It's a tweak to alleviate a behavior difference in 17.4 so I think that's appropriate.
