### PR TITLE
Recognize direct properties access in ProjectInstance

### LINKED ISSUE #10604: Unused Property Check false positive - MSBuild special properties
### Context

There are special MSBuild recognized properties (e.g. https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties) that are being interpreted by the runtime without calling expander. For such we miss the usage in the `BC0203` check and flag the definitions.

### Repro steps

Add `<MSBuildTreatWarningsAsErrors>true</MSBuildTreatWarningsAsErrors>` to your project file and build with `/check`

**Observed:**
```
    MSBUILD : error BC0203: C:\repro\TestProj.csproj (12,7): https://aka.ms/buildcheck/codes#BC0203 - Property: [MSBuildTreatWarningsAsErrors] was declared/initialized, but it was never used.
```
**Expected:**

No error is logged

### More info

The `MSBuildTreatWarningsAsErrors` is dereferenced here: https://github.com/dotnet/msbuild/blob/4dc5611154bf8988de16b5173f64cb5758d53c17/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L1372

We should try to see how couple other well known props are dereferenced and route the info from those reads to the check.
Other option is to add a listof well known properties to the check itself - but that is prone to regressions.

### Loosely related

https://github.com/dotnet/msbuild/issues/10597

### PR DESCRIPTION
**Pull request by JanKrivanek**
Fixes #10604

### Context
`MSBuildTreatWarningsAsErrors` access was not recognized by PropertiesCheck - since it was bypassing Expander.

### Changes Made
Added routing of properties access to `ProjectInstance`

### Testing
Added unit test case specifically for `MSBuildTreatWarningsAsErrors` (fails without fix)

### Notes
Not handling accesses via `Project` - as that would get much more involved and is specific for API calls and VS - which are both currently unsupported scenarios

### CODE REVIEW

File: src/Build/Instance/ProjectInstance.cs [hunk 1]
```diff
@@ -1894,6 +1895,11 @@ public string GetPropertyValue(string name)
             {
                 unescapedValue = String.Empty;
             }
+            else
+            {
+                _loggingContext?.ProcessPropertyRead(
+                    new PropertyReadInfo(name, ElementLocation.EmptyLocation, false, PropertyReadContext.Other));
```
Comment (rainersigwald) [inline src/Build/Instance/ProjectInstance.cs:1901]: Why `EmptyLocation`?

Comment (rainersigwald) [reply src/Build/Instance/ProjectInstance.cs:1901]: Oh, I see: because it's the engine itself that's reading it.

**Review by rainersigwald — COMMENTED** [review]
I think in my head I was envisioning this being a new wrapper around `ProjectInstance.GetPropertyValue()` that had tracking, used only in the parts of the engine that pay special attention to magic properties. Is that something you considered?

**Review by maridematte — APPROVED** [review]

**Review by AR-May — APPROVED** [review]

**Comment by JanKrivanek** [comment]
> I think in my head I was envisioning this being a new wrapper around `ProjectInstance.GetPropertyValue()` that had tracking, used only in the parts of the engine that pay special attention to magic properties. Is that something you considered?

I thought about it, then dismissed it and now on the second thought I decided to follow it :-)

Originaly I wanted to have it more universal for cases where msbuild might be called through API (as prep for VS integration). However that will anyway need much more other work (especially as evaluation is separated) - so let's handle the case that is problematic now
