### PR TITLE
[Graph] Fix target list when there are multiple ProjectReferences with different Targets metadata

### LINKED ISSUE #7694: Static graph respect only first ProjectReference for same project
### Issue Description
Only first ProjectReference for same project respected by isolated build.

### Steps to Reproduce
I try to play with static graph and isolated build using example from https://github.com/dotnet/msbuild/blob/main/documentation/specs/static-graph.md#examples

`Referenced\Referenced.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UnusualOutput>Configuration\Unusual.txt</UnusualOutput>
  </PropertyGroup>

  <Target Name="UnusualThing" Returns="$(UnusualOutput)" />
</Project>
```

`Referencing\Referencing.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Referenced\Referenced.csproj" />
  </ItemGroup>

  <Target Name="GetUnusualThing" BeforeTargets="BeforeBuild">
    <MSBuild Projects="..\Referenced\Referenced.csproj"
             Targets="UnusualThing">
      <Output TaskParameter="TargetOutputs"
              ItemName="Content" />
    </MSBuild>
  </Target>
</Project>
```

As example does not suggest steps to fix it to be compatible with isolated builds, let's do it. Let's suppose that `Referencing.csproj` need assembly reference to `Referenced.csproj` .

First we need add:
```
  <ItemGroup>
    <ProjectReferenceTargets Include="GetUnusualThing" Targets="UnusualThing"/>
  </ItemGroup>
```
We also need to duplicate ProjectReference, one will be used for reference output assembly, another one should provide dependency for static graph on UnusualThing:
```
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="UnusualThing" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Referenced\Referenced.csproj"  />
```

It will fail (`dotnet msbuild Referencing\Referencing.csproj -graph -isolate`). It is possible to fix if we express it in next form:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="Build;UnusualThing" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="Build"  />
    <ProjectReferenceTargets Include="GetUnusualThing" Targets="UnusualThing"/>
  </ItemGroup>

  <Target Name="GetUnusualThing" BeforeTargets="BeforeBuild">
    <MSBuild Projects="..\Referenced\Referenced.csproj"
             Targets="UnusualThing">
      <Output TaskParameter="TargetOutputs"
              ItemName="None" />
    </MSBuild>
  </Target>
</Project>
```
### Expected Behavior
Next should work:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="UnusualThing" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Referenced\Referenced.csproj" />
    <ProjectReferenceTargets Include="GetUnusualThing" Targets="UnusualThing"/>
  </ItemGroup>

  <Target Name="GetUnusualThing" BeforeTargets="BeforeBuild">
    <MSBuild Projects="..\Referenced\Referenced.csproj"
             Targets="UnusualThing">
      <Output TaskParameter="TargetOutputs"
              ItemName="None" />
    </MSBuild>
  </Target>
</Project>
```

### PR DESCRIPTION
**Pull request by dfederm**
Fixes #7694

Today the first project reference wins and the targets from additional project references are ignored. There is a comment saying that behavior is "in accordance with vanilla msbuild behaviour when multiple msbuild tasks call into the same logical project", but that doesn't seem to be the case.

This change changes the `TryAdd` to an `AddOrUpdate` so that multiple sets of targets are considered from multiple project references.

## Simple repro:

Referenced\Referenced.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UnusualOutput>Configuration\Unusual.txt</UnusualOutput>
  </PropertyGroup>
  <Target Name="UnusualThing" Returns="$(UnusualOutput)" />
</Project>
```

Referencing\Referencing.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="UnusualThing" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Referenced\Referenced.csproj"  />
  </ItemGroup>
</Project>
```

Run: `msbuild Referencing\Referencing.csproj -graph -isolate`

Note that the repro uses `-isolate` to point out the issue more strongly, but the issue exists with any graph build.

### CODE REVIEW

File: src/Build/Graph/GraphBuilder.cs [hunk 1]
```diff
@@ -621,9 +621,42 @@ internal class GraphEdges
...
+                ReferenceItems.AddOrUpdate(
+                    key,
+                    addValueFactory: static ((ProjectGraphNode node, ProjectGraphNode reference) key, ProjectItemInstance referenceItem) => referenceItem,
+                    updateValueFactory: static ((ProjectGraphNode node, ProjectGraphNode reference) key, ProjectItemInstance existingItem, ProjectItemInstance newItem) =>
+                    {
+                        string existingTargetsMetadata = existingItem.GetMetadataValue(ItemMetadataNames.ProjectReferenceTargetsMetadataName);
+                        string newTargetsMetadata = newItem.GetMetadataValue(ItemMetadataNames.ProjectReferenceTargetsMetadataName);
+
+                        // Bail out of the targets are the same.
+                        if (existingTargetsMetadata.Equals(newTargetsMetadata, StringComparison.OrdinalIgnoreCase))
```
[the remark this answers is not in the document]
Comment (dfederm) [reply src/Build/Graph/GraphBuilder.cs:637]: Looks like MSBuild isn't case sensitive for Target names. Here's what it looks like for a non-graph build:

image

So I think using `StringComparison.OrdinalIgnoreCase` is fine here.

Also duplicate targets in the list should be handled just fine anyway; this was more of an optimization to avoid allocating when merging things which clearly are equivalent.

File: src/Build/Graph/GraphBuilder.cs [hunk 2]
```diff
@@ -621,9 +621,42 @@ internal class GraphEdges
...
+                        {
+                            return existingItem;
+                        }
 
-                // First edge wins, in accordance with vanilla msbuild behaviour when multiple msbuild tasks call into the same logical project
-                set => ReferenceItems.TryAdd(key, value);
+                        existingTargetsMetadata = GetEffectiveTargets(existingItem, existingTargetsMetadata);
+                        newTargetsMetadata = GetEffectiveTargets(newItem, newTargetsMetadata);
+
+                        ProjectItemInstance mergedItem = existingItem.DeepClone();
```
[the remark this answers is not in the document]
Comment (dfederm) [reply src/Build/Graph/GraphBuilder.cs:645]: In some (but not all :( ) cases, this is one of the objects returned from a `ProjectInstance.GetItems(...)` call, so I'm wanting to avoid mutating the value.

It's kinda weird to hold onto the `ProjectItemInstance` in the first place when we need very little from it, but I suppose it's a perf optimization to avoid allocating yet another object to hold a mutable subset of the `ProjectItemInstance`.

**Review by Forgind — APPROVED** [review]

File: src/Build/Graph/GraphBuilder.cs [hunk 3]
```diff
@@ -621,9 +621,42 @@ internal class GraphEdges
...
+                        mergedItem.SetMetadata(ItemMetadataNames.ProjectReferenceTargetsMetadataName, $"{existingTargetsMetadata};{newTargetsMetadata}");
```
Comment (BenVillalobos) [inline src/Build/Graph/GraphBuilder.cs:646]: Do we need to worry about default targets here? Or is that handled automatically somewhere. I ask because default targets can be returned from `GetEffectiveTargets`.

My main concern is if default targets aren't returned from `GetEffectiveTargets`, and aren't set here.

File: src/Build/Graph/ProjectInterpretation.cs [hunk 4]
```diff
@@ -191,8 +191,6 @@ public void ReparentInnerBuilds(Dictionary<ConfigurationMetadata, ParsedProject>
 
                             if (outerBuildReferencingProject.ProjectReferences.Contains(innerBuild))
                             {
-                                graphBuilder.Edges.TryGetEdge((outerBuildReferencingProject, innerBuild), out var existingEdge);
```
Comment (BenVillalobos) [inline src/Build/Graph/ProjectInterpretation.cs:194]: Not entirely sure how this is related, why was this needed?

**Review by BenVillalobos — APPROVED** [review]
LGTM barring two questions, but there's a regression test and it passed some local tests of my own so 👍

File: src/Build/Graph/GraphBuilder.cs (hunk 3 above)
Comment (dfederm) [reply src/Build/Graph/GraphBuilder.cs:646]: `GetEffectiveTargets` does return the default targets if the `Targets` metadata is unspecified.

HOWEVER you bring up a great point since I'm accidentally using the current project's default targets, not the referenced project's.

I'll add a UT and fix...

File: src/Build/Graph/ProjectInterpretation.cs (hunk 4 above)
Comment (dfederm) [reply src/Build/Graph/ProjectInterpretation.cs:194]: It's unused :). The lines below just call `graphBuilder.Edges[]` directly so `existingEdge` isn't used at all.
