### PR TITLE
Disable MotW check on core in GenerateResource

### LINKED ISSUE #7946: Windows container build error on .Net 6.0.8
My WebAPI project that contains an embedded RESX. The windows container build failed with the following error. This error started when using .Net 6.0.8 as base.

```
Step 12/18 : RUN dotnet build "WebAPI.csproj" -c Release -o /app/build
 ---> Running in 426a4e2a3a0e
MSBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018: The "GenerateResource" task failed unexpectedly. [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018: System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {7B8A2D94-0AC9-11D1-896C-00C04FB6BFC4} failed due to the following error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)). [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018:    at System.RuntimeTypeHandle.AllocateComObject(Void* pClassFactory) [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018:    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions) [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018:    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions) [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018:    at System.Activator.CreateInstance(Type type) [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018:    at Microsoft.Build.Tasks.GenerateResource.IsDangerous(String filename) [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018:    at Microsoft.Build.Tasks.GenerateResource.Execute() [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\src\WebAPI\WebAPI.csproj]
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(3262,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\src\WebAPI\WebAPI.csproj]

Build FAILED
```
Docker file is attached.
[Dockerfile.txt](https://github.com/dotnet/core/files/9336095/Dockerfile.txt)
.

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #7946

### Context
The GenerateResource task previously would deserialize and reserialize resource files. It used BinaryFormatter, which is known to be unsafe; to mitigate that security risk, we added a check for the mark of the web on resource files; files with that mark are considered unsafe, and those without are considered safe to be deserialized. On core, we have a separate solution: don't deserialize and reserialize them.

More recently, in work to unify code paths, we effectively enabled the check on core. There remains a check that we're on windows, so it only affected windows computers, and most windows devices could accomplish that fine. Nanoservices, however, did not have the COM API that we called as part of the "IsDangerous" check. This led it to crash.

### Customer Impact
Using a (windows nanoserver) container, customers cannot build projects that include certain resource files. They instead see a confusing error about a missing COM API.

### Risk
Low

### Testing
I verified that setting the registry key resolved the issue. Though that's a different change, it leads to the same code path.

### Code Reviewers
rainersigwald

### Description of the fix
I added an early return on core to get away from the error.

### Notes
The Mark of the Web check was originally introduced as a security measure, but this code path did not initially have it and doesn't need it. This change passed a security review.

Thanks to @asalvo for finding the problematic change!

### CODE REVIEW

File: src/Tasks/GenerateResource.cs [hunk 1]
```diff
@@ -905,24 +905,29 @@ public override bool Execute()
             return !Log.HasLoggedErrors && outOfProcExecutionSucceeded;
         }
 
+#if FEATURE_APPDOMAIN
```
Comment (Forgind) [inline src/Tasks/GenerateResource.cs:908]: Add comment

Comment (rainersigwald) [reply src/Tasks/GenerateResource.cs:908]:
```suggestion
#if FEATURE_RESXREADER_LIVEDESERIALIZATION
```

File: src/Tasks/GenerateResource.cs [hunk 2]
```diff
@@ -905,24 +905,33 @@ public override bool Execute()
...
 
         // Resources can have arbitrarily serialized objects in them which can execute arbitrary code
         // so check to see if we should trust them before analyzing them
         private bool IsDangerous(String filename)
         {
+            // On Framework, we deserialize BinaryFormatter blobs in the main MSBuild process then serialize them again. On Core, we put them as-is into the .resources file,
+            // which eliminates the deserialization attack surface from MSBuild's perspective.
+            //
+            // Even on Framework, we only need to (dangerously) deserialize the .resx file if we think we might need a separate AppDomain, so FEATURE_APPDOMAIN makes sense here.
+#if !FEATURE_APPDOMAIN
```
Comment (rainersigwald) [inline src/Tasks/GenerateResource.cs:924]:
```suggestion
#if !FEATURE_RESXREADER_LIVEDESERIALIZATION
```

**Review by rainersigwald — COMMENTED** [review]
Sorry, I know we discussed this and decided to leave `FEATURE_APPDOMAIN` and add the comment but as I was double-checking the reasoning in the comment I found `FEATURE_RESXREADER_LIVEDESERIALIZATION` which is self-describing and provides better consistency, I think.

**Review by rainersigwald — APPROVED** [review]
