### PR TITLE
Fix RecursiveDir metadata loss in multithreaded builds

### LINKED ISSUE #13140: -mt pack does not work on dotnet/arcade repository
### Issue Description

uncovered during https://github.com/dotnet/dotnet/pull/4487

### Steps to Reproduce
```pwsh
git clone https://github.com/dotnet/msbuild
git clone https://github.com/dotnet/arcade
.\msbuild\build.cmd
.\msbuild\artifacts\bin\bootstrap\core\dotnet.exe pack .\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\ /mt
```

### Expected Behavior

packs correctly same as without the -mt switch

### Actual Behavior

PS C:\Users\janprovaznik\dev> .\msbuild\artifacts\bin\bootstrap\core\dotnet.exe pack .\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\ /mt
Restore complete (1.0s)
  Microsoft.DotNet.Build.Tasks.Installers net472 succeeded (0.7s) → arcade\artifacts\bin\Microsoft.DotNet.Build.Tasks.Installers\Release\net472\Microsoft.DotNet.Build.Tasks.Installers.dll
  Microsoft.DotNet.Build.Tasks.Installers failed with 15 error(s) (0.5s)
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\rpm_templates\changelog' is not added because the package already contains file 'build\changelog'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\rpm_templates\copyright' is not added because the package already contains file 'build\copyright'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\bundle\bundle.wxs' is not added because the package already contains file 'build\bundle.wxs'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\bundle\dummyEula.rtf' is not added because the package already contains file 'build\dummyEula.rtf'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\bundle\upgradePolicies.wxs' is not added because the package already contains file 'build\upgradePolicies.wxs'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\eula.rtf' is not added because the package already contains file 'build\eula.rtf'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\product\breadcrumbstorefolder.wxs' is not added because the package already contains file 'build\breadcrumbstorefolder.wxs'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\product\product.common.wxi' is not added because the package already contains file 'build\product.common.wxi'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\product\product.wxs' is not added because the package already contains file 'build\product.wxs'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\product\provider.wxs' is not added because the package already contains file 'build\provider.wxs'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\product\registrykeys.wxs' is not added because the package already contains file 'build\registrykeys.wxs'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\product\werrelatedkeys.wxs' is not added because the package already contains file 'build\werrelatedkeys.wxs'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\variables.wxi' is not added because the package already contains file 'build\variables.wxi'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\vs\VS.Redist.Common.Component.nuspec.txt' is not added because the package already contains file 'build\VS.Redist.Common.Component.nuspec.txt'
    C:\Users\janprovaznik\dev\msbuild\artifacts\bin\bootstrap\core\sdk\10.0.101\NuGet.Build.Tasks.Pack.targets(222,5): error NU5118: Warning As Error: File 'C:\Users\janprovaznik\dev\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\wix\wix.targets' is not added because the package already contains file 'build\wix.targets'

[arcade.tasks.installers.binlog.zip](https://github.com/user-attachments/files/24933850/arcade.tasks.installers.binlog.zip)

### Analysis

_No response_

### Versions & Configurations

msbuild main january 18.4

### PR DESCRIPTION
**Pull request by JanProvaznik**
When using MSBuild's multithreaded mode (-mt / /maxcpucount), the %(RecursiveDir) built-in metadata was lost when items crossed process boundaries to the TaskHost. This caused NuGet pack to flatten directory structures (e.g., build\wix\bundle\bundle.wxs became build\bundle.wxs).

Root cause: TaskParameterTaskItem only copied custom metadata when wrapping ITaskItem for TaskHost serialization. RecursiveDir is a built-in metadata that cannot be derived from just the item spec - it requires the original wildcard pattern (_includeBeforeWildcardExpansionEscaped).

Fix: Explicitly copy RecursiveDir to custom metadata in TaskParameterTaskItem constructor before serialization, so it survives the cross-process boundary.

Also includes related fixes to ProjectItemInstance.cs:
- Preserve _projectDirectory in copy constructor and serialization
- Fix CreateItem(string, string, string) to use includeBeforeWildcardExpansionEscaped

related: #3121
fixes #13140

### CODE REVIEW

**Comment by baronfel** [comment]
Oh wow - I think I got this in the RID-specific tool packaging work and worked around it without understanding what was happening. Really great identification of the problem here!

File: src/Shared/TaskParameter.cs [hunk 1]
```diff
@@ -587,6 +587,20 @@ internal TaskParameterTaskItem(ITaskItem copyFrom)
                             _customEscapedMetadata[(string)entry.Key] = (string)entry.Value ?? string.Empty;
                         }
                     }
+
+                    // RecursiveDir is a built-in metadata that cannot be derived from the item spec alone -
+                    // it requires the original wildcard pattern. When crossing process boundaries (e.g., to TaskHost),
+                    // this information is lost. Copy it to custom metadata so it survives serialization.
+                    // See https://github.com/Microsoft/msbuild/issues/3121
```
Comment (JanProvaznik) [inline src/Shared/TaskParameter.cs]:
```suggestion
                    // See https://github.com/dotnet/msbuild/issues/3121
```

File: src/Shared/UnitTests/TaskParameter_Tests.cs [hunk 2]
```diff
@@ -538,5 +538,67 @@ public void ITaskItemParameter_CopyMetadataFromRemoteTaskItem()
             }
         }
 #endif
+
+        /// <summary>
+        /// Verifies that RecursiveDir built-in metadata survives serialization.
+        /// RecursiveDir cannot be derived from the item spec alone - it requires the original
+        /// wildcard pattern. This test ensures it is copied to custom metadata during serialization.
+        /// See https://github.com/Microsoft/msbuild/issues/3121
```
Comment (JanProvaznik) [inline src/Shared/UnitTests/TaskParameter_Tests.cs]:
```suggestion
        /// See https://github.com/dotnet/msbuild/issues/3121
```

**Comment by JanProvaznik** [comment]
looking for 2 reviewers here

File: src/Shared/TaskParameter.cs [hunk 3]
```diff
@@ -587,6 +587,20 @@ internal TaskParameterTaskItem(ITaskItem copyFrom)
                             _customEscapedMetadata[(string)entry.Key] = (string)entry.Value ?? string.Empty;
                         }
                     }
+
+                    // RecursiveDir is a built-in metadata that cannot be derived from the item spec alone -
+                    // it requires the original wildcard pattern. When crossing process boundaries (e.g., to TaskHost),
+                    // this information is lost. Copy it to custom metadata so it survives serialization.
+                    // See https://github.com/dotnet/msbuild/issues/3121
+                    // Check ContainsKey first to avoid expensive FileMatcher call when not needed.
```
Comment (ViktorHofer) [inline src/Shared/TaskParameter.cs:595]: Which FileMatcher call?

Comment (JanProvaznik) [reply src/Shared/TaskParameter.cs:595]: 1. ITaskItem2.GetMetadataValueEscaped("RecursiveDir") — src/Build/Instance/ProjectItemInstance.cs:1370
   2. → TaskItem.GetMetadataEscaped() — src/Build/Instance/ProjectItemInstance.cs:1416
   3. → GetBuiltInMetadataEscaped() — src/Build/Instance/ProjectItemInstance.cs:2083
   4. → BuiltInMetadata.GetMetadataValueEscaped() — src/Build/Definition/BuiltInMetadata.cs:73
   5. → GetRecursiveDirValue() — src/Build/Definition/BuiltInMetadata.cs:98
   6. → FileMatcher.Default.FileMatch() — src/Build/Definition/BuiltInMetadata.cs:110

and then there are some regex and string and IO operations in filematcher, which is why this is nice to avoid

**Review by rainersigwald — APPROVED** [review]
Feels like we should have an end-to-end test pinning the fix too.
