### PR TITLE
Better evaluator errors Fixes #6460

### LINKED ISSUE #6460: A crash in evaluator causes MSBuild to fail the build with 0 errors 0 warnings
We should harden MSBuild against crashes in various places to ensure that we get a decent behavior and report the original stack.

A sample exception I'm seeing here causes these symptoms:

```
Path.CheckInvalidPathChars Line 1394
Path.Combine Line 1204
FileUtilities.GetFullPath Line 667
LazyItemEvaluator`4.LazyItemList.ProcessNonWildCardItemUpdates Line 431
LazyItemEvaluator`4.LazyItemList.ComputeItems Line 402
LazyItemEvaluator`4.LazyItemList.GetItemData Line 290
LazyItemEvaluator`4.<>c.<GetAllItemsDeferred>b__26_0 Line 489
Enumerable.<SelectManyIterator>d__17`2.MoveNext
Buffer`1..ctor
OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext
Evaluator`4.Evaluate Line 665
Evaluator`4.Evaluate Line 320
ProjectInstance.Initialize Line 2752
ProjectInstance..ctor Line 484
BuildRequestConfiguration.<>c__DisplayClass61_0.<LoadProjectIntoConfiguration>b__0 Line 474
BuildRequestConfiguration.InitializeProject Line 500
BuildRequestConfiguration.LoadProjectIntoConfiguration Line 433
RequestBuilder.<BuildProject>d__67.MoveNext Line 1118
AsyncTaskMethodBuilder`1.Start Line 472
RequestBuilder.BuildProject
RequestBuilder.<BuildAndReport>d__58.MoveNext Line 812
AsyncTaskMethodBuilder.Start Line 317
RequestBuilder.BuildAndReport
RequestBuilder.<RequestThreadProc>d__57.MoveNext Line 777
AsyncTaskMethodBuilder.Start Line 317
RequestBuilder.RequestThreadProc
RequestBuilder.<StartBuilderThread>b__52_2 Line 702
Task`1.InnerInvoke Line 680
Task.Execute Line 2499
Task.ExecutionContextCallback Line 2861
ExecutionContext.RunInternal Line 981
ExecutionContext.Run Line 928
Task.ExecuteWithThreadLocal Line 2827
Task.ExecuteEntry Line 2757
TaskScheduler.TryExecuteTask Line 458
RequestBuilder.DedicatedThreadsTaskScheduler.<InjectThread>b__6_0 Line 1411
ThreadHelper.ThreadStart_Context Line 69
ExecutionContext.RunInternal Line 981
ExecutionContext.Run Line 928
ExecutionContext.Run Line 917
ThreadHelper.ThreadStart Line 106
```

In the Path.Combine, the first argument is:
`C:\A\src\Shims`
and the second one is:
`\Users\kirill\AppData\Local\Microsoft\A\Temp\WebTooling\Schemas\JSON\Catalog\https`

Throwing this ArgumentException from this location causes the problem:
https://github.com/dotnet/msbuild/blob/d07c47adec8d5cf40718ef9a618b0b959cc8be0d/src/Build/Evaluation/LazyItemEvaluator.cs#L431

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #6460

### Context
Errors from Evaluate could appear as just BUILD FAILED 0 Warnings 0 Errors, which is no good. This makes the errors appear in a fairly generic way.

It also fixes the motivating issue.

### Changes Made
Logs an error including a full stack and the original error message with errors in Evaluate.
Fixes a bug with GetFullPath being passed an unescaped string instead of an escaped string.
Changes the error formatting such that only the first line gets reformatted.

### Testing
Tried it out before and after the changes. It now prints:

```
Build FAILED.

"C:\Users\forgind\Desktop\Archives\Bug-specific\6460\1.csproj" (default target) (1) ->
"C:\Users\forgind\Desktop\Archives\Bug-specific\6460\1.csproj" (Inner target) (1:2) ->
  MSBUILD : error : "This is an unhandled exception in MSBuild -- PLEASE FILE AN ISSUE AT https://github.com/dotnet/msb
uild/issues/new. [C:\Users\forgind\Desktop\Archives\Bug-specific\6460\1.csproj]    Message:
    Illegal characters in path.
    Stack:
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Build.Shared.FileUtilities.GetFullPath(String fileSpec, String currentDirectory) in C:\Users\forgind\D
ocuments\GitHub\msbuild\src\Shared\FileUtilities.cs:line 669
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.ProcessNonWildCardItemUpdates(Dictionary`2 itemsWithN
oWildcards, Builder items) in C:\Users\forgind\Documents\GitHub\msbuild\src\Build\Evaluation\LazyItemEvaluator.cs:line
 453
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.ComputeItems(LazyItemList lazyItemList, ImmutableHash
Set`1 globsToIgnore) in C:\Users\forgind\Documents\GitHub\msbuild\src\Build\Evaluation\LazyItemEvaluator.cs:line 439
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.GetItemData(ImmutableHashSet`1 globsToIgnore) in C:\U
sers\forgind\Documents\GitHub\msbuild\src\Build\Evaluation\LazyItemEvaluator.cs:line 312
   at Microsoft.Build.Evaluation.LazyItemEvaluator`4.<>c.<GetAllItemsDeferred>b__27_0(LazyItemList itemList) in C:\User
s\forgind\Documents\GitHub\msbuild\src\Build\Evaluation\LazyItemEvaluator.cs:line 511
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate() in C:\Users\forgind\Documents\GitHub\msbuild\src\Build\Evaluat
ion\Evaluator.cs:line 681
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root,
ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggi
ngService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElement
Cache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationConte
xt evaluationContext, Boolean interactive) in C:\Users\forgind\Documents\GitHub\msbuild\src\Build\Evaluation\Evaluator
.cs:line 336
   at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, Stri
ng explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters build
Parameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService
, Int32 submissionId, Nullable`1 projectLoadSettings, EvaluationContext evaluationContext) in C:\Users\forgind\Documen
ts\GitHub\msbuild\src\Build\Instance\ProjectInstance.cs:line 2771
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsV
ersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResol
verService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings) in C:\Users\forgind\Documents\GitHu
b\msbuild\src\Build\Instance\ProjectInstance.cs:line 486
   at Microsoft.Build.BackEnd.BuildRequestConfiguration.<>c__DisplayClass60_0.<LoadProjectIntoConfiguration>b__0() in C
:\Users\forgind\Documents\GitHub\msbuild\src\Build\BackEnd\Shared\BuildRequestConfiguration.cs:line 469
   at Microsoft.Build.BackEnd.BuildRequestConfiguration.InitializeProject(BuildParameters buildParameters, Func`1 loadP
rojectFromFile) in C:\Users\forgind\Documents\GitHub\msbuild\src\Build\BackEnd\Shared\BuildRequestConfiguration.cs:lin
e 495
   at Microsoft.Build.BackEnd.BuildRequestConfiguration.LoadProjectIntoConfiguration(IBuildComponentHost componentHost,
 BuildRequestDataFlags buildRequestDataFlags, Int32 submissionId, Int32 nodeId) in C:\Users\forgind\Documents\GitHub\m
sbuild\src\Build\BackEnd\Shared\BuildRequestConfiguration.cs:line 429
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext() in C:\Users\forgind\Documents\GitHub\msbui
ld\src\Build\BackEnd\Components\RequestBuilder\RequestBuilder.cs:line 1117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext() in C:\Users\forgind\Documents\GitHub\msb
uild\src\Build\BackEnd\Components\RequestBuilder\RequestBuilder.cs:line 808"

    0 Warning(s)
    1 Error(s)
```

### CODE REVIEW

File: src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs [hunk 1]
```diff
@@ -823,14 +823,17 @@ private async Task BuildAndReport()
...
+                {
+                    _nodeLoggingContext.LogError(BuildEventFileInfo.Empty, "UnhandledMSBuildError", ex.Message, ex.StackTrace);
+                }
+                else
                 {
-                    // This includes InternalErrorException, which we definitely want a callstack for.
-                    // Fortunately the default console UnhandledExceptionHandler will log the callstack even
-                    // for unhandled exceptions thrown from threads other than the main thread, like here.
-                    // Less fortunately NUnit doesn't.
-                    throw;
```
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:833]: It never crashed very hard—even with critical exceptions, we still weren't seeing a stack or anything if it happened at the wrong time. It basically just jumped up the stack a little faster.

File: src/Build/Resources/Strings.resx [hunk 2]
```diff
@@ -463,6 +463,13 @@
     <value>MSB4187: Failed to receive a response from the task thread in the timeout period "{0}" ms. Shutting down.</value>
     <comment>{StrBegin="MSB4187: "}</comment>
   </data>
+  <data name="UnhandledMSBuildError" xml:space="preserve">
+    <value>"This is an unhandled exception in MSBuild -- PLEASE FILE AN ISSUE AT https://github.com/dotnet/msbuild/issues/new.
+    Message:
```
Comment (BenVillalobos) [inline src/Build/Resources/Strings.resx:468]: Can we add a newline just before message? The current error looks like this:

```
uild/issues/new. [C:\Users\forgind\Desktop\Archives\Bug-specific\6460\1.csproj]    Message:
    Illegal characters in path.
    Stack:
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
```
I didn't even notice the word "Message" at first. It'd be clearer if it looked like this:

```
uild/issues/new. [C:\Users\forgind\Desktop\Archives\Bug-specific\6460\1.csproj]    
		Message: Illegal characters in path.
    Stack:
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
```

File: src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (BenVillalobos) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:833]: My MSBuild senses are tingling with this change, but I have no evidence to push against it. It'll fail in the same way as an InvalidProjectFileException, which can't be that bad right?

**Review by BenVillalobos — COMMENTED** [review]
Overall LGTM, pending a bit more discussion on whether to throw (previous behavior) or not.

File: src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (rainersigwald) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:833]: I think we should filter the catch on `IsCriticalException()`, as we do elsewhere. If we've hit an OOM or something the best thing we can do is crash immediately and let Watson tell us about it; ideally we could log but we want to see the crash in the place it came from, rather than in logging.

[the remark this answers is not in the document]
Comment (Forgind) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:833]: How would Watson get anything? I walked through this case with KirillOsenkov and showed him that even before, a critical exception just disappeared without a trace.

[the remark this answers is not in the document]
Comment (rainersigwald) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:833]: Ok, then that's bad and we should fix it. Why isn't our UnhandledException handler firing? Is it getting correctly instantiated?

[the remark this answers is not in the document]
Comment (Forgind) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:833]: I inserted an OutOfMemoryException in LazyItemEvaluator with this change, and it logged it properly. That seems good.

[the remark this answers is not in the document]
Comment (Forgind) [reply src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs:833]: How would an UnhandledException handler know about the exception? I'm slightly hazy on this, but it seems like crash the thread hard, and essentially nothing escapes. I should clarify that there's a point when it writes to a debug file in Temp, but it never says what that file is, so there's a 0.01% chance that I'd find it randomly without having paused the debugger to see exactly which file it is.

File: src/Build/Resources/Strings.resx [hunk 3]
```diff
@@ -463,6 +463,10 @@
     <value>MSB4187: Failed to receive a response from the task thread in the timeout period "{0}" ms. Shutting down.</value>
     <comment>{StrBegin="MSB4187: "}</comment>
   </data>
+  <data name="UnhandledMSBuildError" xml:space="preserve">
+    <value>This is an unhandled exception in MSBuild -- PLEASE FILE AN ISSUE AT https://github.com/dotnet/msbuild/issues/new.
```
Comment (rainersigwald) [inline src/Build/Resources/Strings.resx:467]: Let's make an aka.ms link for this so we can easily retarget it if necessary

```suggestion
    <value>This is an unhandled exception in MSBuild -- PLEASE FILE AN ISSUE AT https://aka.ms/msbuild/unhandled.
```

I also think we might want to change the wording from "please file an issue" to "please search for and upvote an issue or if there isn't one file a new one" if we can figure out a way to say that that is less mean.

**Review by rainersigwald — APPROVED** [review]

File: src/Build/Resources/Strings.resx (hunk 3 above)
Comment (Forgind) [reply src/Build/Resources/Strings.resx:467]: So should that aka.ms/ link point [here](https://github.com/dotnet/msbuild/issues) instead?

I would definitely prefer they search for existing issues first, but telling them to search first might deter people from filing issues at all, which biases me a little towards the current wording. How about:
PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT...
?

Comment (baronfel) [reply src/Build/Resources/Strings.resx:467]: We should make a specific issue template for this error in this repo, and have the link point to issue create with that particular issue template preselected.  The SDK does this:

* [here's where the 'new issue' button takes you](https://github.com/dotnet/sdk/issues/new/choose)
* [specific classes of issues have their own templates](https://github.com/dotnet/sdk/issues/new?assignees=&labels=&template=20_feature_request.md)

We could then update the aka.ms link to point to the template for unhandled errors, with instructions on what to search for, data to provide on the issue, etc, etc.

Comment (BenVillalobos) [reply src/Build/Resources/Strings.resx:467]: For whoever takes this on, some relevant PR's:

https://github.com/dotnet/msbuild/pull/5380
https://github.com/dotnet/msbuild/pull/6557
https://github.com/dotnet/msbuild/pull/5521

Comment (Forgind) [reply src/Build/Resources/Strings.resx]: I made a separate PR (#7392) for making the unhandled exception issue. That should mean we can merge the two independently and redirect the aka.ms link as necessary later.

By the way, what's the link for changing those? I wrote down that it's just https://aka.ms, but that took me to the benefits page.

Comment (baronfel) [reply src/Build/Resources/Strings.resx]: raw `aka.ms` takes you to the dashboard for updating them, right now Rainer, Marc, and I are set as the owners, so I think only we can see/change it

Comment (Forgind) [reply src/Build/Resources/Strings.resx]: I'm dumb. I typed aka.ms and hit enter without noticing that it autocompleted...
Apparently I most use the vanity links to log all my 2/4 hour absences 😁

**Comment by KirillOsenkov** [comment]
This is awesome. Thanks!
