### PR TITLE
Always respect warning-as-error properties

### LINKED ISSUE #10874: WarningsNotAsErrors ignored for some warnings with /warnaserror option
Given

```xml
<Project>
  <PropertyGroup>
    <MSBuildTreatWarningsAsErrors>true</MSBuildTreatWarningsAsErrors>
    <MSBuildWarningsNotAsErrors>ABC123</MSBuildWarningsNotAsErrors>
  </PropertyGroup>

  <Target Name="Dispatch">
    <ItemGroup>
        <P Include="$(MSBuildThisFileFullPath)" AdditionalProperties="Num=1" />
        <P Include="$(MSBuildThisFileFullPath)" AdditionalProperties="Num=2" />
        <P Include="$(MSBuildThisFileFullPath)" AdditionalProperties="Num=3" />
        <P Include="$(MSBuildThisFileFullPath)" AdditionalProperties="Num=4" />
    </ItemGroup>
    <MSBuild Projects="@(P)" BuildInParallel="true" Targets="Warn" />

  </Target>

  <Target Name="Warn">
    <Warning Code="ABC123" Text="Hello from instance $(Num) in pid $([System.Diagnostics.Process]::GetCurrentProcess().Id)" />
    <Exec Command="sleep 1" /><!-- To give worker nodes some time to spin up -->
  </Target>
</Project>
```

The `MSBuildWarningsNotAsErrors` is not consistently respected:

```sh-session
❯ dotnet msbuild -m .\foo.csproj /warnaserror
   foo succeeded with 1 warning(s) (0.0s)
     C:\Users\raines\Downloads\foo.csproj(19,5): warning ABC123: Hello from instance 1 in pid 39896
   foo succeeded (0.0s)
     C:\Users\raines\Downloads\foo.csproj(19,5): error ABC123: Hello from instance 4 in pid 3804
   foo succeeded (0.0s)
     C:\Users\raines\Downloads\foo.csproj(19,5): error ABC123: Hello from instance 3 in pid 5872
   foo succeeded (0.0s)
     C:\Users\raines\Downloads\foo.csproj(19,5): error ABC123: Hello from instance 2 in pid 8016
  Build failed with 3 error(s) and 1 warning(s) in 0.2s
```

### PR DESCRIPTION
**Pull request by rainersigwald**
Remote (built in another node) projects were not respecting MSBuildWarningsNotAsErrors configured  in the projects, when the API or CLI `-warnaserror` option was enabled.

Fixes #10874.

### CODE REVIEW

File: src/Build/BackEnd/Components/Logging/LoggingService.cs [hunk 1]
```diff
@@ -1666,8 +1666,8 @@ private void RouteBuildEvent(object loggingEvent)
                 }
             }
 
-            // If this is BuildCheck-ed build - add the warnings promotability/demotability to the service
-            if (buildEventArgs is ProjectStartedEventArgs projectStartedEvent && this._componentHost.BuildParameters.IsBuildCheckEnabled)
+            // Respect warning-promotion properties from the remote project
+            if (buildEventArgs is ProjectStartedEventArgs projectStartedEvent)
```
Comment (JanKrivanek) [inline src/Build/BackEnd/Components/Logging/LoggingService.cs:1670]: It'll need the worker node side adjust as well:

https://github.com/dotnet/msbuild/blob/5e119d75b47cbf7f35cdcb0690f2bbb4f6ef2288/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L1282


Hopefuly it shouldn't have significant perf impact - but I haven't test that as it was limited to BuildCheck that's perf hit anyways.

Comment (rainersigwald) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:1670]: I don't think I understand why that needs to change. This does fix the basic issue in #10874.

Comment (JanKrivanek) [reply src/Build/BackEnd/Components/Logging/LoggingService.cs:1670]: If receiving of `ProjectStartedEventArgs.Warnings[Not]As[Errors|Messages]` is wanted to be active regardless of BuildCheck being on - then the population of those properties should not be conditioned on that either. So the `buildCheckManager != null &&` should be removed in that code.

It worked because that conditioning was buggy - it should have conditioned based on `BuildParameters.IsBuildCheckEnabled` - as `buildCheckManager` has the "null object" value if BuildCheck is disabled - so the current condition is misleading. On top of that it causes skipping of the code during restore - which is the stage where we actualy want that to transfer the information.

**Review by maridematte — APPROVED** [review]

**Review by JanKrivanek — APPROVED** [review]
Looks good!
